(function(){'use strict';var Core=window.AXMNeuralVisual,$=function(id){return document.getElementById(id);};var draft=Core.newDraft({}),images={},hubInitialized=false;
var blendMap={normal:'source-over',multiply:'multiply',screen:'screen',overlay:'overlay',darken:'darken',lighten:'lighten','color-dodge':'color-dodge','color-burn':'color-burn','hard-light':'hard-light','soft-light':'soft-light',difference:'difference',exclusion:'exclusion',add:'lighter',subtract:'difference'};
function id(prefix){return prefix+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,6);}function escapeHtml(v){return String(v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function filters(){var out=[],brightness=Number($('brightness').value),contrast=Number($('contrast').value),saturation=Number($('saturation').value),hue=Number($('hue').value),blur=Number($('blur').value);if(brightness)out.push({type:'brightness',value:brightness});if(contrast)out.push({type:'contrast',value:contrast});if(saturation!==1)out.push({type:'saturation',value:saturation});if(hue)out.push({type:'hue',value:hue});if(blur)out.push({type:'blur',radius:blur});return out;}
function previewFilter(){var b=Number($('brightness').value),c=Number($('contrast').value),s=Number($('saturation').value),h=Number($('hue').value),blur=Number($('blur').value);return'brightness('+(1+b)+') contrast('+(1+c)+') saturate('+s+') hue-rotate('+h+'deg) blur('+blur+'px)';}
function sync(){draft.title=$('title').value.trim()||'Visual stack draft';draft.canvas.width=Math.max(1,Math.min(2048,Math.round(Number($('width').value)||1024)));draft.canvas.height=Math.max(1,Math.min(2048,Math.round(Number($('height').value)||1024)));draft.global_filters=filters();$('stageTitle').textContent=draft.title;$('layerCount').textContent=draft.layers.length+(draft.layers.length===1?' layer':' layers');save();}
function save(){if(!hubInitialized)return;AXMHub.save({title:draft.title,canvas:draft.canvas,layers:draft.layers.map(function(l){var copy=JSON.parse(JSON.stringify(l));delete copy.origin;return copy;}),global_filters:draft.global_filters,notice:'Raw image bytes are intentionally not checkpointed; reselect source files after reload.'});}
async function loadImage(artifact){if(images[artifact.id])return images[artifact.id];if(!artifact.data_url)return null;var img=new Image();img.src=artifact.data_url;await img.decode();images[artifact.id]=img;return img;}
async function draw(){sync();var canvas=$('canvas'),ctx=canvas.getContext('2d');canvas.width=draft.canvas.width;canvas.height=draft.canvas.height;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.save();ctx.filter=previewFilter();for(var i=0;i<draft.layers.length;i++){var layer=draft.layers[i];if(layer.visible===false)continue;ctx.globalAlpha=layer.opacity==null?1:Number(layer.opacity);ctx.globalCompositeOperation=blendMap[layer.blend_mode]||'source-over';if(layer.fill){ctx.fillStyle=layer.fill.slice(0,7);ctx.fillRect(layer.offset&&layer.offset.x||0,layer.offset&&layer.offset.y||0,canvas.width,canvas.height);}else if(layer.source_artifact_id){var artifact=draft.source_artifacts.find(function(a){return a.id===layer.source_artifact_id;}),img=artifact?await loadImage(artifact):null;if(img)ctx.drawImage(img,layer.offset&&layer.offset.x||0,layer.offset&&layer.offset.y||0);}}ctx.restore();ctx.globalAlpha=1;ctx.globalCompositeOperation='source-over';ctx.filter='none';$('previewStatus').textContent='Browser preview updated. Exact compositor output still requires the Raster Compositor Hand.';renderLayers();}
function renderLayers(){$('layers').innerHTML=draft.layers.map(function(l,i){var kind=l.source_artifact_id?(l.origin&&l.origin.kind==='ai-provider-proposal'?'NEURAL CANDIDATE':'IMAGE'):'FILL';return'<article class="layer" data-i="'+i+'"><div class="layerHead"><b>'+escapeHtml(l.name)+'</b><span class="badge">'+kind+'</span></div><div class="layerGrid"><label>Visible<select data-k="visible"><option value="true"'+(l.visible!==false?' selected':'')+'>yes</option><option value="false"'+(l.visible===false?' selected':'')+'>no</option></select></label><label>Blend<select data-k="blend">'+['normal','multiply','screen','overlay','darken','lighten','color-dodge','color-burn','hard-light','soft-light','difference','exclusion','add','subtract'].map(function(v){return'<option'+(l.blend_mode===v?' selected':'')+'>'+v+'</option>';}).join('')+'</select></label><label>Opacity<input data-k="opacity" type="number" min="0" max="1" step="0.05" value="'+l.opacity+'"></label><label>Name<input data-k="name" value="'+escapeHtml(l.name)+'"></label></div><div class="layerButtons"><button data-a="down">↓</button><button data-a="up">↑</button><button data-a="delete" class="danger">Delete</button></div></article>';}).join('');}
function addFill(){draft.layers.push({id:id('fill'),name:'Colour layer',visible:true,opacity:1,blend_mode:'normal',offset:{x:0,y:0},fill:$('fill').value.toUpperCase()+'FF',filters:[]});draw();}
async function addImageFile(file){if(!file||!/^image\/(png|jpeg|webp)$/.test(file.type))throw Error('Choose a PNG, JPEG or WebP image');if(file.size>12000000)throw Error('Source image exceeds 12 MB draft limit');var dataUrl=await new Promise(function(resolve,reject){var r=new FileReader();r.onload=function(){resolve(String(r.result));};r.onerror=reject;r.readAsDataURL(file);});var img=new Image();img.src=dataUrl;await img.decode();if(img.naturalWidth>2048||img.naturalHeight>2048)throw Error('Source dimensions exceed 2048 × 2048');var artifact={id:id('source'),mime:file.type,width:img.naturalWidth,height:img.naturalHeight,sha256:await Core.sha256(dataUrl),data_url:dataUrl,name:file.name};draft.source_artifacts.push(artifact);images[artifact.id]=img;draft.layers.push({id:id('image'),name:file.name,visible:true,opacity:1,blend_mode:'normal',offset:{x:0,y:0},source_artifact_id:artifact.id,filters:[]});draw();}
async function importNeural(){var raw=localStorage.getItem('axm.neural-room.transfer.v1');if(!raw)return $('transferStatus').textContent='No waiting neural proposal.';try{var env=JSON.parse(raw);localStorage.removeItem('axm.neural-room.transfer.v1');if(Date.parse(env.expires_at)<=Date.now())throw Error('Neural transfer expired');var check=await Core.verifyResult(env.result,env.request);if(!check.pass)throw Error(check.errors.join(' · '));draft=Core.addNeuralResult(draft,check.result);$('width').value=draft.canvas.width;$('height').value=draft.canvas.height;$('transferStatus').textContent='Verified neural proposal added as a candidate layer; transfer deleted.';AXMHub.log('Visual Draft Room imported one verified neural candidate layer');draw();}catch(e){localStorage.removeItem('axm.neural-room.transfer.v1');$('transferStatus').textContent='Rejected neural proposal: '+e.message;}}
function download(name,data){var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(a.href);},1000);}
function exportDraft(){sync();download('axm-visual-stack-draft.json',draft);}
function exportRecipe(){try{sync();download('axm-raster-composition-recipe.json',Core.toRasterRecipe(draft));$('previewStatus').textContent='Deterministic recipe exported. Run Raster Compositor Hand for exact pixels and receipt.';}catch(e){$('previewStatus').textContent='Recipe blocked: '+e.message;}}
function sendNeural(){sync();try{var request=Core.normalizeRequest({operation:$('neuralOperation').value,prompt:$('neuralPrompt').value,strength:Number($('neuralStrength').value),negative_prompt:'unreadable text, broken anatomy, duplicated objects, unrequested logos',seed:'draft-'+Core.digest(draft),source_draft_digest:Core.digest(draft),target_canvas:draft.canvas});localStorage.setItem('axm.visual-draft.neural-request.v1',JSON.stringify({schema:'axm.visual-draft.neural-transfer/v1',created_at:new Date().toISOString(),expires_at:new Date(Date.now()+600000).toISOString(),request:request}));$('previewStatus').textContent='Neural request prepared; open Neural Room within ten minutes.';}catch(e){$('previewStatus').textContent='Neural request blocked: '+e.message;}}
$('addFill').onclick=addFill;$('resize').onclick=draw;$('importNeural').onclick=importNeural;$('exportDraft').onclick=exportDraft;$('exportRecipe').onclick=exportRecipe;$('sendNeural').onclick=sendNeural;$('addImage').onchange=function(){addImageFile(this.files&&this.files[0]).catch(function(e){$('previewStatus').textContent=e.message;});this.value='';};
['title','width','height','brightness','contrast','saturation','hue','blur'].forEach(function(key){$(key).oninput=function(){var out=$(key+'Out');if(out)out.textContent=this.value;draw();};});
$('layers').onchange=function(e){var article=e.target.closest('.layer');if(!article)return;var layer=draft.layers[Number(article.dataset.i)],key=e.target.dataset.k;if(key==='visible')layer.visible=e.target.value==='true';else if(key==='blend')layer.blend_mode=e.target.value;else if(key==='opacity')layer.opacity=Math.max(0,Math.min(1,Number(e.target.value)));else if(key==='name')layer.name=e.target.value;draw();};$('layers').onclick=function(e){var button=e.target.closest('button');if(!button)return;var article=button.closest('.layer'),index=Number(article.dataset.i),action=button.dataset.a;if(action==='delete'&&draft.layers.length>1)draft.layers.splice(index,1);if(action==='up'&&index<draft.layers.length-1){var x=draft.layers.splice(index,1)[0];draft.layers.splice(index+1,0,x);}if(action==='down'&&index>0){var y=draft.layers.splice(index,1)[0];draft.layers.splice(index-1,0,y);}draw();};
$('importDraft').onchange=function(){var file=this.files&&this.files[0];if(!file)return;var reader=new FileReader();reader.onload=function(){try{var parsed=JSON.parse(String(reader.result||''));draft=Core.newDraft(parsed);images={};$('title').value=draft.title;$('width').value=draft.canvas.width;$('height').value=draft.canvas.height;draw();$('previewStatus').textContent='Draft imported. Embedded source artifacts restored where present.';}catch(e){$('previewStatus').textContent='Draft import blocked: '+e.message;}};reader.readAsText(file);};
AXMHub.onInit(function(init){hubInitialized=true;var s=init.moduleState;if(s&&Array.isArray(s.layers)&&s.layers.length){draft=Core.newDraft({title:s.title,canvas:s.canvas,layers:s.layers,global_filters:s.global_filters,source_artifacts:[]});$('title').value=draft.title;$('width').value=draft.canvas.width;$('height').value=draft.canvas.height;$('previewStatus').textContent='Draft metadata restored. Image bytes were not silently checkpointed; reselect those sources.';}draw();});AXMHub.onShutdown(save);AXMHub.ready({id:'visual-draft-room',name:'Visual Draft Room',version:'v0.1',hubApiVersion:'1.0',permissions:[],savesState:true,handlesShutdown:true});draw();
})();
