from __future__ import annotations

from copy import deepcopy
from typing import Any


def _criterion(
    criterion_id: str,
    label: str,
    weight: float,
    source: str,
    description: str,
) -> dict[str, Any]:
    return {
        "id": criterion_id,
        "label": label,
        "weight": weight,
        "source": source,
        "description": description,
        "score_min": 0,
        "score_max": 100,
    }


def _base(
    challenge_id: str,
    title: str,
    goal: str,
    *,
    category: str,
    source_module: str,
    source_job_id: str | None,
) -> dict[str, Any]:
    return {
        "schema_version": "axm.challenge-arena/0.5",
        "challenge_id": challenge_id,
        "title": title,
        "goal": goal,
        "category": category,
        "constraints": [],
        "inputs": [],
        "deliverables": [],
        "rubric": [],
        "deterministic_checks": [],
        "participant_policy": {
            "minimum_participants": 2,
            "blind_authorship": True,
            "allow_self_vote": False,
            "require_complete_ballot": True,
            "reveal_authors_after_close": True,
            "allow_late_registration": False,
            "require_submission_packet_ack": True,
            "require_review_packet_ack": True,
            "allow_criterion_abstention": True,
            "allow_tied_rankings": True,
            "require_score_evidence": True,
            "minimum_score_evidence_refs": 1,
            "hide_reviewer_own_blind_label": True,
            "require_revision_precondition": True,
            "reject_symlinks": True,
            "max_artifacts_per_submission": 10000,
            "max_single_artifact_bytes": 2147483648,
            "max_total_artifact_bytes": 8589934592,
            "minimum_peer_reviews_per_candidate": 1,
            "minimum_independent_review_groups_per_candidate": 0,
            "review_assignment_mode": "all",
            "reviews_per_reviewer": 0,
            "minimum_automatic_weight_coverage_ratio": 0.2,
        },
        "evaluation_policy": {
            "peer_aggregation": "median",
            "trim_fraction": 0.1,
            "outlier_threshold_points": 25.0,
            "exclude_flagged_reviews": False,
        },
        "integration": {
            "source_module": source_module,
            "source_job_id": source_job_id,
            "return_mode": "result_and_merge_map",
        },
        "notes": [
            "Preset generated by AXM Challenge Arena. Edit while DRAFT; lock before distributing to participants."
        ],
    }


def generic_packet(
    challenge_id: str,
    title: str,
    goal: str,
    *,
    source_module: str = "standalone",
    source_job_id: str | None = None,
) -> dict[str, Any]:
    packet = _base(
        challenge_id,
        title,
        goal,
        category="OPEN",
        source_module=source_module,
        source_job_id=source_job_id,
    )
    packet["deliverables"] = [
        {
            "id": "primary",
            "description": "Primary completed artifact or package.",
            "required": True,
            "accepted_media_types": ["application/octet-stream"],
        }
    ]
    packet["rubric"] = [
        _criterion("contract_compliance", "Contract compliance", 25, "deterministic", "Meets declared file, format, provenance, and packaging requirements."),
        _criterion("goal_fidelity", "Goal fidelity", 25, "peer", "How strongly the result solves the locked goal."),
        _criterion("quality", "Overall quality", 20, "peer", "Craft, coherence, reliability, and completeness."),
        _criterion("originality", "Useful originality", 15, "peer", "Distinctive ideas that remain usable rather than novelty alone."),
        _criterion("integration", "Integration value", 15, "peer", "Ease of reusing, adapting, or connecting the result to AXM modules."),
    ]
    packet["deterministic_checks"] = [
        {"id": "primary_exists", "kind": "artifact_exists", "criterion_id": "contract_compliance", "weight": 3, "required": True, "config": {"deliverable_id": "primary"}},
        {"id": "primary_count", "kind": "file_count", "criterion_id": "contract_compliance", "weight": 1, "required": True, "config": {"deliverable_id": "primary", "min": 1}},
        {"id": "provenance", "kind": "provenance_present", "criterion_id": "contract_compliance", "weight": 1, "required": True, "config": {"required_keys": ["origin", "rights"]}},
    ]
    return packet


def asset_packet(
    challenge_id: str,
    title: str,
    goal: str,
    *,
    source_module: str = "asset_factory",
    source_job_id: str | None = None,
) -> dict[str, Any]:
    packet = _base(challenge_id, title, goal, category="ART", source_module=source_module, source_job_id=source_job_id)
    packet["deliverables"] = [
        {
            "id": "asset",
            "description": "Primary production asset.",
            "required": True,
            "accepted_media_types": ["image/png", "image/jpeg", "image/webp", "image/svg+xml"],
        },
        {
            "id": "asset_manifest",
            "description": "JSON metadata with dimensions, intended use, source method, and rights/provenance.",
            "required": True,
            "accepted_media_types": ["application/json"],
        },
    ]
    packet["rubric"] = [
        _criterion("asset_contract", "Asset contract", 25, "deterministic", "Required files, dimensions, alpha/format, manifest, and provenance."),
        _criterion("brief_fidelity", "Brief fidelity", 25, "peer", "Matches the requested world, subject, function, and mood."),
        _criterion("visual_quality", "Visual quality", 20, "peer", "Readable silhouette, composition, finish, and internal consistency."),
        _criterion("originality", "Useful originality", 15, "peer", "Feels specific rather than generic while remaining production-usable."),
        _criterion("reusability", "Factory reusability", 15, "peer", "Easy to crop, animate, recolor, tile, derive, or reuse."),
    ]
    packet["deterministic_checks"] = [
        {"id": "required_deliverables", "kind": "manifest_deliverables", "criterion_id": "asset_contract", "weight": 2, "required": True, "config": {"required_deliverable_ids": ["asset", "asset_manifest"]}},
        {"id": "asset_exists", "kind": "artifact_exists", "criterion_id": "asset_contract", "weight": 2, "required": True, "config": {"deliverable_id": "asset"}},
        {"id": "manifest_json", "kind": "json_valid", "criterion_id": "asset_contract", "weight": 1, "required": True, "config": {"deliverable_id": "asset_manifest"}},
        {"id": "manifest_keys", "kind": "json_keys", "criterion_id": "asset_contract", "weight": 1, "required": True, "config": {"deliverable_id": "asset_manifest", "required": ["dimensions", "intended_use", "source_method", "rights"]}},
        {"id": "provenance", "kind": "provenance_present", "criterion_id": "asset_contract", "weight": 2, "required": True, "config": {"required_keys": ["origin", "rights"]}},
    ]
    return packet


def code_packet(
    challenge_id: str,
    title: str,
    goal: str,
    *,
    source_module: str = "workshop",
    source_job_id: str | None = None,
) -> dict[str, Any]:
    packet = _base(challenge_id, title, goal, category="BUILD", source_module=source_module, source_job_id=source_job_id)
    packet["deliverables"] = [
        {"id": "source", "description": "Runnable source package.", "required": True, "accepted_media_types": ["application/zip", "text/x-python", "text/javascript", "text/plain"]},
        {"id": "readme", "description": "Beginner-readable setup and use instructions.", "required": True, "accepted_media_types": ["text/markdown", "text/plain"]},
        {"id": "tests", "description": "Deterministic tests or validation script.", "required": True, "accepted_media_types": ["text/plain", "application/zip"]},
    ]
    packet["rubric"] = [
        _criterion("machine_evidence", "Machine evidence", 30, "deterministic", "Packaging, required files, static checks, tests, and optional replay evidence."),
        _criterion("solution_correctness", "Solution correctness", 25, "peer", "Solves the actual goal and handles important failure cases."),
        _criterion("architecture", "Architecture", 15, "peer", "Clear boundaries, maintainability, and appropriate complexity."),
        _criterion("beginner_use", "Beginner usability", 15, "peer", "Can be installed, understood, and operated without hidden expertise."),
        _criterion("integration", "AXM integration", 15, "peer", "Clean module contract, local-first behavior, and reusable interfaces."),
    ]
    packet["deterministic_checks"] = [
        {"id": "required_deliverables", "kind": "manifest_deliverables", "criterion_id": "machine_evidence", "weight": 3, "required": True, "config": {"required_deliverable_ids": ["source", "readme", "tests"]}},
        {"id": "artifacts_exist", "kind": "artifact_exists", "criterion_id": "machine_evidence", "weight": 2, "required": True, "config": {}},
        {"id": "readme_has_start", "kind": "text_contains", "criterion_id": "machine_evidence", "weight": 1, "required": True, "config": {"deliverable_id": "readme", "needles": ["install", "run"], "mode": "all"}},
        {"id": "provenance", "kind": "provenance_present", "criterion_id": "machine_evidence", "weight": 1, "required": True, "config": {"required_keys": ["origin", "rights"]}},
        {"id": "optional_test_command", "kind": "command", "criterion_id": "machine_evidence", "weight": 4, "required": False, "config": {"argv": ["python", "-m", "unittest", "discover", "-v"], "timeout_seconds": 120}},
    ]
    packet["notes"].append("Candidate execution remains disabled unless the operator explicitly starts the Arena with --allow-execution inside an appropriate sandbox.")
    return packet


def game_packet(
    challenge_id: str,
    title: str,
    goal: str,
    *,
    source_module: str = "game_builder",
    source_job_id: str | None = None,
) -> dict[str, Any]:
    packet = _base(challenge_id, title, goal, category="BUILD", source_module=source_module, source_job_id=source_job_id)
    packet["deliverables"] = [
        {"id": "game_package", "description": "Runnable game or prototype package.", "required": True, "accepted_media_types": ["application/zip", "text/html", "application/octet-stream"]},
        {"id": "controls", "description": "JSON control map and accessibility notes.", "required": True, "accepted_media_types": ["application/json"]},
        {"id": "readme", "description": "Launch instructions and known limits.", "required": True, "accepted_media_types": ["text/markdown", "text/plain"]},
    ]
    packet["rubric"] = [
        _criterion("game_contract", "Game contract", 25, "deterministic", "Package integrity, required files, controls metadata, and optional launch test."),
        _criterion("playability", "Playability", 25, "peer", "Clear interaction, understandable feedback, and a functioning play loop."),
        _criterion("challenge_design", "Challenge design", 20, "peer", "Fair, interesting decisions rather than arbitrary difficulty."),
        _criterion("observer_value", "Observer value", 15, "peer", "Visually and narratively understandable to people watching the AI play."),
        _criterion("integration", "Engine integration", 15, "peer", "Portable state, clean controls contract, and reusable systems."),
    ]
    packet["deterministic_checks"] = [
        {"id": "required_deliverables", "kind": "manifest_deliverables", "criterion_id": "game_contract", "weight": 3, "required": True, "config": {"required_deliverable_ids": ["game_package", "controls", "readme"]}},
        {"id": "package_exists", "kind": "artifact_exists", "criterion_id": "game_contract", "weight": 2, "required": True, "config": {"deliverable_id": "game_package"}},
        {"id": "controls_json", "kind": "json_valid", "criterion_id": "game_contract", "weight": 1, "required": False, "config": {"deliverable_id": "controls"}},
        {"id": "zip_safe", "kind": "zip_integrity", "criterion_id": "game_contract", "weight": 2, "required": False, "config": {"deliverable_id": "game_package", "glob": "*.zip"}},
        {"id": "provenance", "kind": "provenance_present", "criterion_id": "game_contract", "weight": 1, "required": True, "config": {"required_keys": ["origin", "rights"]}},
    ]
    return packet


def video_packet(
    challenge_id: str,
    title: str,
    goal: str,
    *,
    source_module: str = "video_pipeline",
    source_job_id: str | None = None,
) -> dict[str, Any]:
    packet = _base(challenge_id, title, goal, category="ART", source_module=source_module, source_job_id=source_job_id)
    packet["deliverables"] = [
        {"id": "video", "description": "Rendered video.", "required": True, "accepted_media_types": ["video/mp4", "video/webm", "video/quicktime"]},
        {"id": "production_manifest", "description": "Shot/source/rights and technical metadata.", "required": True, "accepted_media_types": ["application/json"]},
        {"id": "captions", "description": "Captions or transcript when speech/text is present.", "required": False, "accepted_media_types": ["text/vtt", "application/x-subrip", "text/plain"]},
    ]
    packet["rubric"] = [
        _criterion("technical_delivery", "Technical delivery", 25, "deterministic", "Required files, media readability, duration/resolution requirements, and provenance."),
        _criterion("story_fidelity", "Story fidelity", 25, "peer", "Communicates the intended narrative, meaning, and emotional direction."),
        _criterion("cinematic_quality", "Cinematic quality", 20, "peer", "Pacing, framing, sound, transitions, and visual coherence."),
        _criterion("originality", "Useful originality", 15, "peer", "Specific and memorable choices rather than generic spectacle."),
        _criterion("production_reuse", "Production reuse", 15, "peer", "Editable sources, modular shots, and clean downstream handoff."),
    ]
    packet["deterministic_checks"] = [
        {"id": "required_deliverables", "kind": "manifest_deliverables", "criterion_id": "technical_delivery", "weight": 2, "required": True, "config": {"required_deliverable_ids": ["video", "production_manifest"]}},
        {"id": "video_exists", "kind": "artifact_exists", "criterion_id": "technical_delivery", "weight": 2, "required": True, "config": {"deliverable_id": "video"}},
        {"id": "manifest_json", "kind": "json_valid", "criterion_id": "technical_delivery", "weight": 1, "required": True, "config": {"deliverable_id": "production_manifest"}},
        {"id": "media_probe", "kind": "ffprobe_media", "criterion_id": "technical_delivery", "weight": 3, "required": False, "config": {"deliverable_id": "video", "min_seconds": 1, "max_seconds": 3600}},
        {"id": "provenance", "kind": "provenance_present", "criterion_id": "technical_delivery", "weight": 2, "required": True, "config": {"required_keys": ["origin", "rights"]}},
    ]
    return packet


def research_packet(
    challenge_id: str,
    title: str,
    goal: str,
    *,
    source_module: str = "research",
    source_job_id: str | None = None,
) -> dict[str, Any]:
    packet = _base(challenge_id, title, goal, category="RESEARCH", source_module=source_module, source_job_id=source_job_id)
    packet["deliverables"] = [
        {"id": "report", "description": "Evidence-linked report.", "required": True, "accepted_media_types": ["text/markdown", "text/plain", "application/pdf"]},
        {"id": "source_log", "description": "Machine-readable source and claim ledger.", "required": True, "accepted_media_types": ["application/json"]},
    ]
    packet["rubric"] = [
        _criterion("evidence_contract", "Evidence contract", 25, "deterministic", "Required files, source ledger structure, and explicit uncertainty fields."),
        _criterion("accuracy", "Accuracy", 25, "peer", "Claims are supported, scoped, and distinguish observation from inference."),
        _criterion("coverage", "Coverage", 20, "peer", "Addresses mechanisms, counterevidence, options, risks, and unresolved questions."),
        _criterion("usefulness", "Practical usefulness", 15, "peer", "Turns evidence into grounded decisions or next actions."),
        _criterion("source_integrity", "Source integrity", 15, "peer", "Preserves disagreement, provenance, limitations, and inaccessible evidence."),
    ]
    packet["deterministic_checks"] = [
        {"id": "required_deliverables", "kind": "manifest_deliverables", "criterion_id": "evidence_contract", "weight": 2, "required": True, "config": {"required_deliverable_ids": ["report", "source_log"]}},
        {"id": "source_log_json", "kind": "json_valid", "criterion_id": "evidence_contract", "weight": 2, "required": True, "config": {"deliverable_id": "source_log"}},
        {"id": "source_log_keys", "kind": "json_keys", "criterion_id": "evidence_contract", "weight": 2, "required": True, "config": {"deliverable_id": "source_log", "required": ["sources", "claims", "uncertainties"]}},
        {"id": "report_sections", "kind": "text_contains", "criterion_id": "evidence_contract", "weight": 1, "required": True, "config": {"deliverable_id": "report", "needles": ["evidence", "limitations", "unresolved"], "mode": "all"}},
        {"id": "provenance", "kind": "provenance_present", "criterion_id": "evidence_contract", "weight": 1, "required": True, "config": {"required_keys": ["origin", "rights"]}},
    ]
    return packet


PRESETS = {
    "generic": generic_packet,
    "asset": asset_packet,
    "code": code_packet,
    "hand": code_packet,
    "game": game_packet,
    "video": video_packet,
    "research": research_packet,
    "document": research_packet,
}


def build_preset(kind: str, challenge_id: str, title: str, goal: str, **kwargs: Any) -> dict[str, Any]:
    key = kind.strip().lower()
    if key not in PRESETS:
        raise ValueError(f"Unknown preset {kind!r}. Available: {sorted(PRESETS)}")
    return deepcopy(PRESETS[key](challenge_id, title, goal, **kwargs))
