(function(){
'use strict';
var $=function(id){return document.getElementById(id);};
var state={dictionary:null,geometry:null,records:[],imports:[],notes:[],pending:null,metric:'gdp-per-capita',year:String(new Date().getFullYear()-1),selectedCountry:'NLD',compare:['NLD','HRV','USA'],zoom:{k:1,x:0,y:0},drag:null};
var projection,path,countryByIso={};
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c];});}
function gate(action,detail){if(!window.AXMGate||!AXMGate.submit)return{allow:true};return AXMGate.submit({action:action,actor:'human-user',actorType:'human',tool:'finance-world-room',detail:detail||{}});}
function download(name,content,type){var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type:type||'application/json'}));a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(a.href);},1000);}
function format(v,format){if(!Number.isFinite(v))return'—';if(format==='percent')return new Intl.NumberFormat(undefined,{maximumFractionDigits:2}).format(v)+'%';if(format==='compact')return new Intl.NumberFormat(undefined,{notation:'compact',maximumFractionDigits:2}).format(v);if(format==='currency-compact')return'$'+new Intl.NumberFormat(undefined,{notation:'compact',maximumFractionDigits:2}).format(v);if(format==='currency')return'$'+new Intl.NumberFormat(undefined,{maximumFractionDigits:0}).format(v);return new Intl.NumberFormat(undefined,{maximumFractionDigits:2}).format(v);}
function metricInfo(){if(state.metric.indexOf('lens:')===0){var id=state.metric.slice(5),l=state.dictionary.lenses[id];return{id:id,name:l.name,unit:'relative score / 100',format:'score',lens:l};}var i=state.dictionary.indicators[state.metric];return{id:state.metric,name:i?i.name:state.metric,unit:i?i.unit:'',format:i?i.format:'number'};}
function metricValues(){if(state.metric.indexOf('lens:')===0)return AXMFinanceCore.lensScores(state.records,state.dictionary,state.metric.slice(5),state.year);return AXMFinanceCore.exactMap(state.records,state.metric,state.year);}
function metricValue(item){if(!item)return null;return Number(item.value);}
function countryName(iso){var f=countryByIso[iso];return f?(f.properties.NAME_EN||f.properties.NAME||iso):iso;}
function setBoot(text){$('bootStatus').textContent=text;$('footerStatus').textContent=state.records.length+' observations · '+AXMFinanceCore.quality(state.records).countries+' countries';}
async function save(reason){var data={schema:'axm.finance-world-room-state/0.1',records:state.records,imports:state.imports,notes:state.notes,metric:state.metric,year:state.year,selectedCountry:state.selectedCountry,compare:state.compare};try{await AXM.store.save('finance-world-room-state',data);setBoot((reason||'saved')+' · '+state.records.length+' rows');}catch(e){localStorage.setItem('axm.finance-world-room.fallback',JSON.stringify(data));setBoot('saved in browser fallback');}}
async function load(){try{var saved=await AXM.store.load('finance-world-room-state');if(saved&&saved.data)restore(saved.data);else{var raw=localStorage.getItem('axm.finance-world-room.fallback');if(raw)restore(JSON.parse(raw));}}catch(e){var raw=localStorage.getItem('axm.finance-world-room.fallback');if(raw)restore(JSON.parse(raw));}}
function restore(data){state.records=Array.isArray(data.records)?data.records:[];state.imports=Array.isArray(data.imports)?data.imports:[];state.notes=Array.isArray(data.notes)?data.notes:[];if(data.metric)state.metric=data.metric;if(data.year)state.year=data.year;if(data.selectedCountry)state.selectedCountry=data.selectedCountry;if(Array.isArray(data.compare))state.compare=data.compare;}
function switchView(name){document.querySelectorAll('.view').forEach(function(x){x.classList.toggle('active',x.id==='view-'+name);});document.querySelectorAll('.view-tab').forEach(function(x){x.classList.toggle('active',x.dataset.view===name);});if(name==='timeline')renderTimeline();if(name==='compare')renderCompare();if(name==='quality')renderQuality();if(name==='notes')renderNotes();if(name==='data')renderReceipts();}
function populate(){var indicators=state.dictionary.indicators,lenses=state.dictionary.lenses;var raw='<optgroup label="Observed metrics">'+Object.keys(indicators).map(function(id){return'<option value="'+id+'">'+esc(indicators[id].name)+'</option>';}).join('')+'</optgroup>';var ls='<optgroup label="Transparent composite lenses">'+Object.keys(lenses).map(function(id){return'<option value="lens:'+id+'">'+esc(lenses[id].name)+'</option>';}).join('')+'</optgroup>';$('metricSelect').innerHTML=raw+ls;$('metricSelect').value=state.metric;$('timelineIndicator').innerHTML=raw;$('wbIndicator').innerHTML=Object.keys(indicators).map(function(id){return'<option value="'+id+'">'+esc(indicators[id].name)+' · '+esc(indicators[id].code)+'</option>';}).join('');$('wbIndicator').value='gdp-per-capita';var y=new Date().getFullYear();$('wbStart').value=y-10;$('wbEnd').value=y-1;refreshSelects();}
function refreshSelects(){var periods=AXMFinanceCore.sortedPeriods(state.records);if(periods.indexOf(state.year)<0&&periods.length)state.year=periods[periods.length-1];$('yearSelect').innerHTML=(periods.length?periods:[state.year]).slice().reverse().map(function(y){return'<option>'+y+'</option>';}).join('');$('yearSelect').value=state.year;var geos=Array.from(new Set(state.records.map(function(r){return r.geography;}))).filter(function(g){return countryByIso[g];}).sort(function(a,b){return countryName(a).localeCompare(countryName(b));});var options=geos.map(function(g){return'<option value="'+g+'">'+esc(countryName(g))+'</option>';}).join('');$('timelineCountry').innerHTML=options||'<option value="">No countries loaded</option>';$('compareCountry').innerHTML=options||'<option value="">No countries loaded</option>';if(geos.indexOf(state.selectedCountry)<0&&geos.length)state.selectedCountry=geos[0];$('timelineCountry').value=state.selectedCountry;}
function initMap(){projection=d3.geoNaturalEarth1().fitExtent([[18,18],[1182,602]],state.geometry);path=d3.geoPath(projection);var viewport=$('mapViewport');viewport.innerHTML='';state.geometry.features.forEach(function(f){var iso=f.properties.ADM0_A3;if(iso&&iso!=='-99')countryByIso[iso]=f;var p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',path(f));p.setAttribute('data-iso',iso);p.setAttribute('class','country no-data');p.addEventListener('pointerenter',showTooltip);p.addEventListener('pointermove',moveTooltip);p.addEventListener('pointerleave',hideTooltip);p.addEventListener('click',function(){if(iso&&iso!=='-99'){state.selectedCountry=iso;renderMap();}});p.addEventListener('dblclick',function(ev){ev.preventDefault();focusCountry(f);});viewport.appendChild(p);});applyTransform();}
function renderMap(){var values=metricValues(),info=metricInfo(),nums=Object.keys(values).map(function(k){return metricValue(values[k]);}).filter(Number.isFinite),breaks=AXMFinanceCore.quantileBreaks(nums,5);document.querySelectorAll('.country').forEach(function(p){var iso=p.dataset.iso,v=metricValue(values[iso]),b=AXMFinanceCore.bin(v,breaks);p.setAttribute('class','country '+(b<0?'no-data':'bin-'+b)+(iso===state.selectedCountry?' selected':''));});$('emptyMap').hidden=nums.length>0;$('mapCoverage').textContent=nums.length+' mapped countries · exact '+state.year+' only';renderLegend(breaks,info);renderCountry(values,info);renderLens(info,values);}
function renderLegend(breaks,info){if(!breaks.length){$('mapLegend').innerHTML='<span><i class="swatch" style="background:var(--map0)"></i>no exact-year data</span>';return;}var labels=[];for(var i=0;i<5;i++){var lo=i===0?'lowest':format(breaks[i-1],info.format),hi=i===4?'highest':format(breaks[i],info.format);labels.push('<span><i class="swatch" style="background:var(--map'+(i+1)+')"></i>'+(i===0||i===4?lo:lo+'–'+hi)+'</span>');}$('mapLegend').innerHTML='<span><i class="swatch" style="background:var(--map0)"></i>no exact-year data</span>'+labels.join('');}
function renderCountry(values,info){var iso=state.selectedCountry,item=values[iso],value=metricValue(item),source=item&&item.sourceId?item.sourceId:(item&&item.components?'composite lens':'—'),coverage=item&&Number.isFinite(item.coverage)?Math.round(item.coverage*100)+'%':(item?'exact row':'none');$('countryStrip').innerHTML='<div><span class="eyebrow">Selected country · '+esc(iso)+'</span><h2>'+esc(countryName(iso))+'</h2></div><div class="country-metrics"><div class="metric"><b>'+esc(format(value,info.format))+'</b><small>'+esc(info.unit)+'</small></div><div class="metric"><b>'+esc(state.year)+'</b><small>exact period</small></div><div class="metric"><b>'+esc(coverage)+'</b><small>layer coverage</small></div><div class="metric"><b>'+esc(source)+'</b><small>source / method</small></div></div>';}
function renderLens(info,values){if(!info.lens){$('lensBox').hidden=true;return;}$('lensBox').hidden=false;var item=values[state.selectedCountry];$('lensBox').innerHTML='<span class="eyebrow">Transparent lens · relative, not predictive</span><h2>'+esc(info.lens.name)+'</h2><p>'+esc(info.lens.note)+'</p><div class="lens-components">'+info.lens.components.map(function(c){var used=item&&item.components&&item.components.find(function(x){return x.indicatorId===c.indicatorId;});var d=state.dictionary.indicators[c.indicatorId];return'<div class="lens-component"><b>'+esc(d.name)+'</b><small>'+Math.round(c.weight*100)+'% weight · '+esc(c.direction)+' preferred</small><div>'+(used?format(used.value,d.format)+' · percentile '+Math.round(used.percentile):'missing for '+state.year)+'</div></div>';}).join('')+'</div>';}
function showTooltip(ev){var iso=ev.currentTarget.dataset.iso,values=metricValues(),item=values[iso],info=metricInfo();$('mapTooltip').innerHTML='<b>'+esc(countryName(iso))+'</b><br>'+esc(info.name)+': '+esc(format(metricValue(item),info.format))+'<br><small>'+esc(state.year)+' · click to inspect</small>';$('mapTooltip').hidden=false;moveTooltip(ev);}
function moveTooltip(ev){var box=$('mapStage').getBoundingClientRect(),tip=$('mapTooltip');tip.style.left=Math.min(box.width-190,Math.max(8,ev.clientX-box.left+12))+'px';tip.style.top=Math.min(box.height-80,Math.max(8,ev.clientY-box.top+12))+'px';}
function hideTooltip(){$('mapTooltip').hidden=true;}
function applyTransform(){$('mapViewport').setAttribute('transform','translate('+state.zoom.x+' '+state.zoom.y+') scale('+state.zoom.k+')');}
function zoomBy(factor,cx,cy){var old=state.zoom.k,n=Math.max(1,Math.min(8,old*factor));cx=cx==null?600:cx;cy=cy==null?310:cy;state.zoom.x=cx-(cx-state.zoom.x)*(n/old);state.zoom.y=cy-(cy-state.zoom.y)*(n/old);state.zoom.k=n;if(n===1){state.zoom.x=0;state.zoom.y=0;}applyTransform();}
function focusCountry(feature){var b=path.bounds(feature),dx=b[1][0]-b[0][0],dy=b[1][1]-b[0][1],cx=(b[0][0]+b[1][0])/2,cy=(b[0][1]+b[1][1])/2,k=Math.max(1,Math.min(7,.72/Math.max(dx/1200,dy/620)));state.zoom={k:k,x:600-k*cx,y:310-k*cy};applyTransform();}
function setupMapGestures(){var svg=$('worldMap');svg.addEventListener('wheel',function(ev){ev.preventDefault();var r=svg.getBoundingClientRect(),cx=(ev.clientX-r.left)/r.width*1200,cy=(ev.clientY-r.top)/r.height*620;zoomBy(ev.deltaY<0?1.18:.85,cx,cy);},{passive:false});svg.addEventListener('pointerdown',function(ev){svg.setPointerCapture(ev.pointerId);state.drag={x:ev.clientX,y:ev.clientY,ox:state.zoom.x,oy:state.zoom.y};svg.classList.add('dragging');});svg.addEventListener('pointermove',function(ev){if(!state.drag)return;var r=svg.getBoundingClientRect();state.zoom.x=state.drag.ox+(ev.clientX-state.drag.x)*1200/r.width;state.zoom.y=state.drag.oy+(ev.clientY-state.drag.y)*620/r.height;applyTransform();});function end(){state.drag=null;svg.classList.remove('dragging');}svg.addEventListener('pointerup',end);svg.addEventListener('pointercancel',end);}
function timelineRows(){return state.records.filter(function(r){return r.geography===$('timelineCountry').value&&r.indicatorId===$('timelineIndicator').value;}).sort(function(a,b){return a.period.localeCompare(b.period);});}
function renderTimeline(){refreshSelects();var rows=timelineRows(),svg=$('timelineChart');svg.innerHTML='';$('timelineEmpty').hidden=rows.length>0;if(!rows.length){$('timelineEvidence').innerHTML='<h2>No evidence</h2><p>Load exact-year observations for this country and indicator.</p>';return;}var vals=rows.map(function(r){return r.value;}),min=Math.min.apply(null,vals),max=Math.max.apply(null,vals),pad=(max-min||1)*.12,minY=min-pad,maxY=max+pad,n=rows.length;function x(i){return 70+(n===1?480:i*(970/(n-1)));}function y(v){return 370-(v-minY)/(maxY-minY)*310;}function line(x1,y1,x2,y2,cls){var e=document.createElementNS('http://www.w3.org/2000/svg','line');[['x1',x1],['y1',y1],['x2',x2],['y2',y2],['class',cls]].forEach(function(a){e.setAttribute(a[0],a[1]);});svg.appendChild(e);}line(70,370,1040,370,'chart-axis');line(70,60,70,370,'chart-axis');var d=rows.map(function(r,i){return(i?'L':'M')+x(i)+' '+y(r.value);}).join(' '),p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d',d);p.setAttribute('class','chart-line');svg.appendChild(p);rows.forEach(function(r,i){var c=document.createElementNS('http://www.w3.org/2000/svg','circle');c.setAttribute('cx',x(i));c.setAttribute('cy',y(r.value));c.setAttribute('r','5');c.setAttribute('class','chart-dot');svg.appendChild(c);var t=document.createElementNS('http://www.w3.org/2000/svg','text');t.setAttribute('x',x(i));t.setAttribute('y','398');t.setAttribute('text-anchor','middle');t.setAttribute('class','chart-text');t.textContent=r.period;svg.appendChild(t);});var info=state.dictionary.indicators[$('timelineIndicator').value];$('timelineEvidence').innerHTML='<h2>'+esc(countryName($('timelineCountry').value))+' · '+esc(info.name)+'</h2><p>'+rows.length+' exact observations from '+esc(rows[0].period)+' to '+esc(rows[rows.length-1].period)+'. Latest: <b>'+esc(format(rows[rows.length-1].value,info.format))+'</b> '+esc(info.unit)+'. Sources remain attached in the exported room evidence.</p>';}
function renderCompare(){refreshSelects();var values=metricValues(),info=metricInfo();state.compare=state.compare.filter(function(g){return countryByIso[g];});$('compareChips').innerHTML=state.compare.map(function(g){return'<span class="chip">'+esc(countryName(g))+' <button data-remove-compare="'+g+'" aria-label="Remove '+esc(countryName(g))+'">×</button></span>';}).join('')||'<span class="hint">Add countries to compare.</span>';$('compareRows').innerHTML=state.compare.map(function(g){var item=values[g],source=item&&item.sourceId?item.sourceId:(item&&item.components?'transparent lens':'—'),coverage=item&&Number.isFinite(item.coverage)?Math.round(item.coverage*100)+'%':(item?'exact row':'—');return'<tr><td>'+esc(countryName(g))+'</td><td>'+esc(format(metricValue(item),info.format))+' '+esc(info.unit)+'</td><td>'+coverage+'</td><td>'+esc(state.year)+'</td><td>'+esc(source)+'</td></tr>';}).join('');}
function stage(rows,receipt){var result=AXMFinanceCore.importRows(rows,state.dictionary,state.records);state.pending={result:result,receipt:receipt};$('previewPanel').hidden=false;$('previewTitle').textContent=receipt.label;$('previewStats').innerHTML=statCards([['Accepted',result.accepted.length],['Rejected',result.rejected.length],['Duplicates',result.duplicates.length],['Countries',new Set(result.accepted.map(function(r){return r.geography;})).size],['Years',new Set(result.accepted.map(function(r){return r.period;})).size]]);$('previewSample').textContent=JSON.stringify({accepted:result.accepted.slice(0,4),rejected:result.rejected.slice(0,3)},null,2);}
function statCards(items){return items.map(function(x){return'<div class="stat"><b>'+esc(x[1])+'</b><small>'+esc(x[0])+'</small></div>';}).join('');}
async function fetchWorldBank(){var id=$('wbIndicator').value,i=state.dictionary.indicators[id],start=Number($('wbStart').value),end=Number($('wbEnd').value);if(!Number.isInteger(start)||!Number.isInteger(end)||start>end){alert('Choose a valid year range.');return;}var g=gate('finance-world.preview-network-import',{provider:'World Bank',indicator:i.code,start:start,end:end});if(!g.allow)return;var url=AXMFinanceSources.worldBankUrl(i.code,start,end),proxy='/api/finance-world/world-bank?indicator='+encodeURIComponent(i.code)+'&start='+start+'&end='+end;$('fetchWorldBank').disabled=true;$('fetchWorldBank').textContent='Fetching…';try{var r=await fetch(proxy),json=await r.json();if(!r.ok)throw new Error(json.error||('HTTP '+r.status));var rows=AXMFinanceSources.parseWorldBank(json,Object.assign({id:id},i),url,new Date().toISOString(),new Set(Object.keys(countryByIso)));stage(rows,{kind:'world-bank-v2',label:'World Bank preview · '+i.name,url:url,indicatorId:id,retrievedAt:new Date().toISOString()});}catch(e){alert('World Bank preview failed: '+e.message);}finally{$('fetchWorldBank').disabled=false;$('fetchWorldBank').textContent='Fetch preview';}}
async function previewFile(){var file=$('dataFile').files[0];if(!file){alert('Choose a CSV or JSON file first.');return;}try{var text=await file.text(),rows=AXMFinanceSources.parse(text,file.name);stage(rows,{kind:'local-file',label:'Local file preview · '+file.name,filename:file.name,bytes:file.size,retrievedAt:new Date().toISOString()});}catch(e){alert('File preview failed: '+e.message);}}
async function commitPreview(){if(!state.pending||!state.pending.result.accepted.length)return;var g=gate('finance-world.commit-import',{accepted:state.pending.result.accepted.length,source:state.pending.receipt.kind});if(!g.allow)return;state.records=state.records.concat(state.pending.result.accepted);state.imports.unshift(Object.assign({},state.pending.receipt,{accepted:state.pending.result.accepted.length,rejected:state.pending.result.rejected.length,duplicates:state.pending.result.duplicates.length,committedAt:new Date().toISOString()}));state.pending=null;$('previewPanel').hidden=true;refreshSelects();await save('import committed');renderAll();}
function renderReceipts(){$('importReceipts').innerHTML=state.imports.map(function(r){return'<div class="receipt"><b>'+esc(r.label||r.kind)+'</b><div>'+esc(r.accepted||0)+' accepted · '+esc(r.rejected||0)+' rejected · '+esc(r.duplicates||0)+' duplicates</div><small>'+esc(r.committedAt||r.retrievedAt||'')+'</small></div>';}).join('')||'<p class="hint">No committed imports yet.</p>';}
function renderQuality(){var q=AXMFinanceCore.quality(state.records);$('qualityStats').innerHTML=statCards([['Rows',q.rows],['Countries',q.countries],['Indicators',q.indicators],['Sources',q.sources],['Official rows',Math.round(q.officialShare*100)+'%']]);var indicators={};state.records.forEach(function(r){var x=indicators[r.indicatorId]||(indicators[r.indicatorId]={rows:0,countries:new Set(),years:new Set()});x.rows++;x.countries.add(r.geography);x.years.add(r.period);});$('indicatorCoverage').innerHTML=Object.keys(indicators).map(function(id){var x=indicators[id],d=state.dictionary.indicators[id];return'<tr><td>'+esc(d?d.name:id)+'</td><td>'+x.rows+'</td><td>'+x.countries.size+'</td><td>'+x.years.size+'</td></tr>';}).join('')||'<tr><td colspan="4">No evidence loaded.</td></tr>';var sources={};state.records.forEach(function(r){var x=sources[r.sourceType]||(sources[r.sourceType]={rows:0,ids:new Set()});x.rows++;x.ids.add(r.sourceId);});$('sourceCoverage').innerHTML=Object.keys(sources).map(function(id){return'<tr><td>'+esc(id)+'</td><td>'+sources[id].rows+'</td><td>'+sources[id].ids.size+'</td></tr>';}).join('')||'<tr><td colspan="3">No sources loaded.</td></tr>';}
function renderNotes(){$('noteList').innerHTML=state.notes.map(function(n){return'<div class="note-card"><b>'+esc(n.question)+'</b><p>Could change my mind: '+esc(n.invalidation)+'</p><small>'+esc(n.createdAt)+'</small></div>';}).join('')||'<p class="hint">No room notes yet.</p>';}
async function saveNote(){var q=$('roomQuestion').value.trim(),i=$('roomInvalidation').value.trim();if(!q||!i){alert('Add both the question and what would change your mind.');return;}state.notes.unshift({question:q,invalidation:i,createdAt:new Date().toISOString(),metric:state.metric,year:state.year,country:state.selectedCountry});$('roomQuestion').value='';$('roomInvalidation').value='';await save('room note saved');renderNotes();}
function exportRoom(){var g=gate('finance-world.export-room',{rows:state.records.length});if(!g.allow)return;download('axm-finance-world-room-'+Date.now()+'.json',JSON.stringify({schema:'axm.finance-world-evidence/0.1',exportedAt:new Date().toISOString(),dictionaryVersion:state.dictionary.version,records:state.records,imports:state.imports,notes:state.notes},null,2));}
function renderAll(){renderMap();renderCompare();renderQuality();renderReceipts();renderNotes();setBoot('ready');}
function bind(){document.querySelectorAll('.view-tab').forEach(function(b){b.onclick=function(){switchView(b.dataset.view);};});document.addEventListener('click',function(ev){var v=ev.target.dataset.openView,remove=ev.target.dataset.removeCompare;if(v)switchView(v);if(remove){state.compare=state.compare.filter(function(x){return x!==remove;});renderCompare();}});$('metricSelect').onchange=function(){state.metric=this.value;renderMap();renderCompare();};$('yearSelect').onchange=function(){state.year=this.value;renderMap();renderCompare();};$('zoomIn').onclick=function(){zoomBy(1.25);};$('zoomOut').onclick=function(){zoomBy(.8);};$('resetMap').onclick=function(){state.zoom={k:1,x:0,y:0};applyTransform();};$('timelineCountry').onchange=renderTimeline;$('timelineIndicator').onchange=renderTimeline;$('addCompare').onclick=function(){var g=$('compareCountry').value;if(g&&state.compare.indexOf(g)<0)state.compare.push(g);renderCompare();};$('fetchWorldBank').onclick=fetchWorldBank;$('previewFile').onclick=previewFile;$('commitPreview').onclick=commitPreview;$('discardPreview').onclick=function(){state.pending=null;$('previewPanel').hidden=true;};$('downloadSchema').onclick=function(){download('axm-finance-world-schema.csv',AXMFinanceSources.schemaCsv(),'text/csv');};$('clearData').onclick=async function(){var g=gate('finance-world.clear-room-data',{rows:state.records.length});if(!g.allow||!confirm('Clear all imported finance observations and receipts? Room notes remain.'))return;state.records=[];state.imports=[];state.pending=null;await save('room data cleared');refreshSelects();renderAll();};$('saveNote').onclick=saveNote;$('saveCheckpoint').onclick=function(){save('checkpoint saved');};$('exportRoom').onclick=exportRoom;setupMapGestures();}
(async function(){if(!window.d3||!d3.geoNaturalEarth1)throw new Error('local map projection missing');if(!window.AXMFinanceCore||!window.AXMFinanceSources)throw new Error('finance modules missing');var loaded=await Promise.all([fetch('finance-dictionary.json',{cache:'no-store'}).then(function(r){return r.json();}),fetch('assets/world-countries-110m.geojson',{cache:'no-store'}).then(function(r){return r.json();})]);state.dictionary=loaded[0];state.geometry=loaded[1];await AXM.init({id:'finance-world-room',name:'AXM Finance World Room',version:'v0.1-experimental'});await load();state.geometry.features.forEach(function(f){var iso=f.properties.ADM0_A3;if(iso&&iso!=='-99')countryByIso[iso]=f;});populate();initMap();bind();renderAll();if(window.AXMHub){AXMHub.ready({id:'finance-world-room',name:'AXM Finance World Room',version:'v0.1-experimental',hubApiVersion:'1.0',permissions:[],savesState:true,handlesShutdown:false,capabilities:['flat-world-map','pan-zoom-focus','time-series','country-compare','world-bank-preview','csv-json-preview','transparent-lenses','source-quality','room-notes','evidence-export']});AXMHub.verifyPass();AXMHub.log('Finance World Room ready · '+state.records.length+' sourced observations');}})().catch(function(e){setBoot('boot failed · '+e.message);if(window.AXMHub)AXMHub.error(e.message);});
})();
