(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.AXMFinanceSources=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
  'use strict';
  function parseCsv(text){var rows=[],row=[],cell='',quoted=false,s=String(text||'');for(var i=0;i<s.length;i++){var c=s[i],n=s[i+1];if(c==='"'&&quoted&&n==='"'){cell+='"';i++;continue;}if(c==='"'){quoted=!quoted;continue;}if(c===','&&!quoted){row.push(cell);cell='';continue;}if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell);cell='';if(row.some(function(x){return x!=='';}))rows.push(row);row=[];continue;}cell+=c;}row.push(cell);if(row.some(function(x){return x!=='';}))rows.push(row);if(!rows.length)return[];var h=rows.shift().map(function(x){return x.trim();});return rows.map(function(r){var o={};h.forEach(function(k,j){o[k]=r[j]==null?'':r[j];});return o;});}
  function parseJson(text){var data=typeof text==='string'?JSON.parse(text):text;if(Array.isArray(data))return data;if(data&&Array.isArray(data.records))return data.records;if(data&&Array.isArray(data.observations))return data.observations;throw new Error('JSON must be an array or contain records/observations');}
  function parse(text,filename){var n=String(filename||'').toLowerCase();if(n.endsWith('.csv'))return parseCsv(text);if(n.endsWith('.json'))return parseJson(text);try{return parseJson(text);}catch(e){return parseCsv(text);}}
  function worldBankUrl(code,start,end){return'https://api.worldbank.org/v2/country/all/indicator/'+encodeURIComponent(code)+'?format=json&source=2&date='+encodeURIComponent(start+':'+end)+'&per_page=20000';}
  function parseWorldBank(payload,indicator,url,retrievedAt,validGeographies){if(!Array.isArray(payload)||!Array.isArray(payload[1]))throw new Error('Unexpected World Bank response');return payload[1].filter(function(x){var iso=String(x&&x.countryiso3code||'');return x&&x.value!=null&&/^[A-Z]{3}$/.test(iso)&&!(x.region&&x.region.value==='Aggregates')&&(!validGeographies||validGeographies.has(iso));}).map(function(x){return{indicatorId:indicator.id,indicatorName:indicator.name,geography:x.countryiso3code,countryName:x.country&&x.country.value,period:String(x.date),value:x.value,unit:indicator.unit,sourceId:'world-bank-wdi:'+indicator.code+':'+x.countryiso3code+':'+x.date,sourceType:'official-statistics',sourceUrl:url,retrievedAt:retrievedAt||new Date().toISOString(),observationStatus:x.obs_status==='F'?'forecast':'observed',notes:x.decimal!=null?'World Bank decimals metadata: '+x.decimal:''};});}
  function schemaCsv(){return['indicatorId,indicatorName,geography,countryName,period,value,unit,sourceId,sourceType,sourceUrl,retrievedAt,observationStatus,notes','inflation,Consumer-price inflation,NLD,Netherlands,2024,3.2,% annual,example-source,official-statistics,https://example.test,2026-07-12T00:00:00Z,observed,Replace with sourced evidence'].join('\n');}
  return{parseCsv:parseCsv,parseJson:parseJson,parse:parse,worldBankUrl:worldBankUrl,parseWorldBank:parseWorldBank,schemaCsv:schemaCsv};
});
