// Generated by AXM Machine Geometry Foundry 0.4.0
// Asset: AXM-PICKUP-GEM-001 AXM Energy Pickup Gem v0.4.0
// Units: millimetres; source orientation: +Z up, -Y forward.
// Canonical source is recipe.json. This is an editable generated bridge.

// instance: gem | base: gem | print_group: gem
color([0.66275, 0.32157, 1.00000, 0.92157])
translate([0, 0, 320]) rotate([0, 0, 0]) scale([1, 1, 1]) polyhedron(points=[[190.0, 0.0, 0.0], [134.35028843, 134.35028843, 0.0], [0.0, 190.0, 0.0], [-134.35028843, 134.35028843, 0.0], [-190.0, 0.0, 0.0], [-134.35028843, -134.35028843, 0.0], [-0.0, -190.0, 0.0], [134.35028843, -134.35028843, 0.0], [0.0, 0.0, 260.0], [0.0, 0.0, -260.0]], faces=[[8, 0, 1], [9, 1, 0], [8, 1, 2], [9, 2, 1], [8, 2, 3], [9, 3, 2], [8, 3, 4], [9, 4, 3], [8, 4, 5], [9, 5, 4], [8, 5, 6], [9, 6, 5], [8, 6, 7], [9, 7, 6], [8, 7, 0], [9, 0, 7]], convexity=10);

// instance: lower_orbit | base: lower_orbit | print_group: lower_orbit
color([0.13725, 0.80392, 0.92157, 1.00000])
translate([0, 0, 230]) rotate([12, 0, 0]) scale([1, 1, 1]) rotate_extrude($fn=32) translate([260, 0, 0]) circle(r=24, $fn=10);

// instance: upper_orbit | base: upper_orbit | print_group: upper_orbit
color([1.00000, 0.67451, 0.14510, 1.00000])
translate([0, 0, 420]) rotate([-18, 0, 30]) scale([1, 1, 1]) rotate_extrude($fn=32) translate([230, 0, 0]) circle(r=18, $fn=10);

// instance: base | base: base | print_group: base
color([0.09412, 0.11373, 0.15294, 1.00000])
translate([0, 0, 40]) rotate([0, 0, 0]) scale([1, 1, 1]) cylinder(h=80, r=230, center=true, $fn=32);
