// Generated by AXM Machine Geometry Foundry 0.4.0
// Asset: AXM-VEHICLE-CHASSIS-001 AXM Modular Utility Vehicle Chassis v0.4.0
// Units: millimetres; source orientation: +Z up, -Y forward.
// Canonical source is recipe.json. This is an editable generated bridge.

// instance: chassis | base: chassis | print_group: chassis
color([0.09412, 0.11373, 0.15294, 1.00000])
translate([0, 0, 620]) rotate([0, 0, 0]) scale([1, 1, 1]) cube([1800, 3200, 380], center=true);

// instance: cabin | base: cabin | print_group: cabin
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([0, -500, 1250]) rotate([0, 0, 0]) scale([1, 1, 1]) polyhedron(points=[[-750.0, -650.0, -450.0], [750.0, -650.0, -450.0], [750.0, -650.0, 450.0], [-750.0, 650.0, -450.0], [750.0, 650.0, -450.0], [750.0, 650.0, 450.0]], faces=[[0, 2, 1], [3, 4, 5], [0, 1, 4, 3], [1, 2, 5, 4], [2, 0, 3, 5]], convexity=10);

// instance: cargo | base: cargo | print_group: cargo
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([0, 900, 1160]) rotate([0, 0, 0]) scale([1, 1, 1]) cube([1500, 1200, 850], center=true);

// instance: wheel__g00 | base: wheel | print_group: wheel
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([-970, -1050, 430]) rotate([0, 90, 0]) scale([1, 1, 1]) cylinder(h=260, r=430, center=true, $fn=32);

// instance: wheel__g01 | base: wheel | print_group: wheel
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([-970, 1050, 430]) rotate([0, 90, 0]) scale([1, 1, 1]) cylinder(h=260, r=430, center=true, $fn=32);

// instance: wheel__g02 | base: wheel | print_group: wheel
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([970, -1050, 430]) rotate([0, 90, 0]) scale([1, 1, 1]) cylinder(h=260, r=430, center=true, $fn=32);

// instance: wheel__g03 | base: wheel | print_group: wheel
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([970, 1050, 430]) rotate([0, 90, 0]) scale([1, 1, 1]) cylinder(h=260, r=430, center=true, $fn=32);

// instance: hub__g00 | base: hub | print_group: hub
color([0.13725, 0.80392, 0.92157, 1.00000])
translate([-990, -1050, 430]) rotate([0, 90, 0]) scale([1, 1, 1]) cylinder(h=300, r=180, center=true, $fn=24);

// instance: hub__g01 | base: hub | print_group: hub
color([0.13725, 0.80392, 0.92157, 1.00000])
translate([-990, 1050, 430]) rotate([0, 90, 0]) scale([1, 1, 1]) cylinder(h=300, r=180, center=true, $fn=24);

// instance: hub__g02 | base: hub | print_group: hub
color([0.13725, 0.80392, 0.92157, 1.00000])
translate([990, -1050, 430]) rotate([0, 90, 0]) scale([1, 1, 1]) cylinder(h=300, r=180, center=true, $fn=24);

// instance: hub__g03 | base: hub | print_group: hub
color([0.13725, 0.80392, 0.92157, 1.00000])
translate([990, 1050, 430]) rotate([0, 90, 0]) scale([1, 1, 1]) cylinder(h=300, r=180, center=true, $fn=24);

// instance: front_core | base: front_core | print_group: front_core
color([0.66275, 0.32157, 1.00000, 0.92157])
translate([0, -1680, 760]) rotate([90, 0, 0]) scale([1, 1, 1]) polyhedron(points=[[170.0, 0.0, 0.0], [85.0, 147.22431864, 0.0], [-85.0, 147.22431864, 0.0], [-170.0, 0.0, 0.0], [-85.0, -147.22431864, 0.0], [85.0, -147.22431864, 0.0], [0.0, 0.0, 180.0], [0.0, 0.0, -180.0]], faces=[[6, 0, 1], [7, 1, 0], [6, 1, 2], [7, 2, 1], [6, 2, 3], [7, 3, 2], [6, 3, 4], [7, 4, 3], [6, 4, 5], [7, 5, 4], [6, 5, 0], [7, 0, 5]], convexity=10);
