"""AXM Human Capability Atlas."""

__version__ = "0.11.0"
CONTRACT_VERSION = "0.1.0"
MODULE_ID = "axm.module.human_capability_atlas"
EXPORT_FORMAT_VERSION = "0.1.0"

IMPLEMENTATION_FINGERPRINT_VERSION = "0.1.0"
PRODUCER_RECEIPT_VERSION = "0.2.0"
BATCH_PLAN_VERSION = "0.2.0"
BATCH_RECEIPT_VERSION = "0.2.0"
PRODUCTION_MANIFEST_VERSION = "0.2.0"
PUBLIC_INTAKE_PREFLIGHT_VERSION = "0.1.0"
REPOSITORY_SNAPSHOT_VERSION = "0.1.0"

NORMALIZED_INVENTORY_VERSION = "0.1.0"
INGEST_IN_PROGRESS_MARKER = ".ingest_in_progress.json"
PUBLIC_INTAKE_IN_PROGRESS_MARKER = ".public_intake_in_progress.json"
PRODUCTION_FINALIZE_IN_PROGRESS_SUFFIX = ".in_progress.json"
