import { accessorData, parseGlb } from '../local-3d-game-runtime/native-glb.mjs';
import { composeTRS, lerpArray, multiply4, slerp4 } from '../local-3d-game-runtime/native-math.mjs';

export const BUNDLE_SCHEMA = 'axm.rig-retarget-bundle/v1';
export const PROFILES = Object.freeze({
  source: { id:'source', label:'Source', leg:1, torso:1, arm:1, width:1, color:'#8192a9' },
  tall: { id:'tall', label:'Tall / narrow', leg:1.22, torso:1.12, arm:1.08, width:.92, color:'#59e2e6' },
  compact: { id:'compact', label:'Compact / broad', leg:.82, torso:.9, arm:.9, width:1.12, color:'#ffbf69' }
});

const canonicalRoles = Object.freeze({
  Bone:'root',Body:'body',Hips:'hips',Abdomen:'spine.01',Torso:'spine.02',Neck:'neck',Head:'head',
  ShoulderL:'clavicle.l',UpperArmL:'upper_arm.l',LowerArmL:'lower_arm.l',PalmL:'hand.l',MiddleHandL:'hand_mid.l',FingersL:'fingers.l',Thumb1L:'thumb.01.l',Thumb2L:'thumb.02.l',
  ShoulderR:'clavicle.r',UpperArmR:'upper_arm.r',LowerArmR:'lower_arm.r',PalmR:'hand.r',MiddleHandR:'hand_mid.r',FingersR:'fingers.r',Thumb1R:'thumb.01.r',Thumb2R:'thumb.02.r',
  UpperLegL:'thigh.l',LowerLegL:'shin.l',FootL:'foot.l',UpperLegR:'thigh.r',LowerLegR:'shin.r',FootR:'foot.r',PoleTargetL:'knee_pole.l',PoleTargetR:'knee_pole.r'
});
const displayConnections = [
  ['Bone','Body'],['Body','Hips'],['Hips','Abdomen'],['Abdomen','Torso'],['Torso','Neck'],['Neck','Head'],
  ['Torso','ShoulderL'],['ShoulderL','UpperArmL'],['UpperArmL','LowerArmL'],['LowerArmL','PalmL'],['PalmL','MiddleHandL'],['MiddleHandL','FingersL'],
  ['Torso','ShoulderR'],['ShoulderR','UpperArmR'],['UpperArmR','LowerArmR'],['LowerArmR','PalmR'],['PalmR','MiddleHandR'],['MiddleHandR','FingersR'],
  ['Body','UpperLegL'],['UpperLegL','LowerLegL'],['LowerLegL','FootL'],['Body','UpperLegR'],['UpperLegR','LowerLegR'],['LowerLegR','FootR']
];

function parentMap(document) { const map=new Map(); (document.nodes||[]).forEach((node,parent)=>(node.children||[]).forEach(child=>map.set(child,parent))); return map; }
function region(name) { if(/Leg|Foot|PoleTarget/.test(name))return'leg';if(/Shoulder|Arm|Palm|Hand|Finger|Thumb/.test(name))return'arm';if(/Body|Hips|Abdomen|Torso|Neck|Head/.test(name))return'torso';return'root'; }
function scaledTranslation(value, jointName, profile) { const kind=region(jointName); if(kind==='leg')return[value[0]*profile.width,value[1]*profile.leg,value[2]*profile.width];if(kind==='arm')return value.map(v=>v*profile.arm);if(kind==='torso')return[value[0]*profile.width,value[1]*profile.torso,value[2]*profile.width];return [...value]; }
function channelValue(model, sampler, time, path) {
  const input=accessorData(model,sampler.input),output=accessorData(model,sampler.output),times=input.array,components=path==='rotation'?4:3;
  if(!times.length)return null;const duration=times[times.length-1]||0,t=duration?((time%duration)+duration)%duration:0;let upper=1;while(upper<times.length&&times[upper]<t)upper++;if(upper>=times.length)upper=times.length-1;const lower=Math.max(0,upper-1),span=times[upper]-times[lower],mix=span>0?(t-times[lower])/span:0;
  const a=Array.from(output.array.slice(lower*components,lower*components+components)),b=Array.from(output.array.slice(upper*components,upper*components+components));if((sampler.interpolation||'LINEAR')==='STEP')return a;return path==='rotation'?slerp4(a,b,mix):lerpArray(a,b,mix);
}
function clipDuration(model, animation) { return Math.max(0,...animation.samplers.map(s=>{const input=accessorData(model,s.input);return input.array[input.array.length-1]||0})); }

function rigSource(model) {
  const document=model.document,skin=document.skins?.[0];if(!skin)throw new Error('The source has no skin to retarget.');
  const parents=parentMap(document),jointSet=new Set(skin.joints),joints=skin.joints.map(index=>{const node=document.nodes[index]||{},name=node.name||`joint-${index}`;let parent=parents.get(index);while(parent!==undefined&&!jointSet.has(parent))parent=parents.get(parent);return{index,name,canonical:canonicalRoles[name]||null,parentIndex:parent??null,parentName:parent===undefined||parent===null?null:(document.nodes[parent]?.name||`joint-${parent}`),translation:[...(node.translation||[0,0,0])],rotation:[...(node.rotation||[0,0,0,1])],scale:[...(node.scale||[1,1,1])]}});
  return{skinIndex:0,joints,parents,document};
}
function animationChannels(model,animation){return animation.channels.map(channel=>{const sampler=animation.samplers[channel.sampler],name=model.document.nodes[channel.target.node]?.name||`node-${channel.target.node}`;return{name,path:channel.target.path,sampler}})}
function sampleRig(model,source,animation,time,profile){const local=new Map(),byName=new Map(source.joints.map(j=>[j.name,j]));for(const joint of source.joints)local.set(joint.index,{translation:scaledTranslation(joint.translation,joint.name,profile),rotation:[...joint.rotation],scale:[...joint.scale]});for(const channel of animationChannels(model,animation)){const joint=byName.get(channel.name);if(!joint||!['translation','rotation','scale'].includes(channel.path))continue;const value=channelValue(model,channel.sampler,time,channel.path);if(!value)continue;local.get(joint.index)[channel.path]=channel.path==='translation'?scaledTranslation(value,joint.name,profile):value}
  const world=new Map();function resolve(index){if(world.has(index))return world.get(index);const joint=source.joints.find(item=>item.index===index),pose=local.get(index),matrix=composeTRS(pose.translation,pose.rotation,pose.scale),parent=joint?.parentIndex;const result=parent!==null&&parent!==undefined?multiply4(resolve(parent),matrix):matrix;world.set(index,result);return result}const positions={};for(const joint of source.joints){const matrix=resolve(joint.index);positions[joint.name]=[matrix[12],matrix[13],matrix[14]]}const anchor=positions.Bone||positions.Body||[0,0,0],vertical=(profile.leg+profile.torso)/2;for(const point of Object.values(positions)){point[0]=anchor[0]+(point[0]-anchor[0])*profile.width;point[1]=anchor[1]+(point[1]-anchor[1])*vertical;point[2]=anchor[2]+(point[2]-anchor[2])*profile.width}return positions}
function restHeight(model,source,profile){const animation={channels:[],samplers:[]},positions=sampleRig(model,source,animation,0,profile),ys=Object.values(positions).map(p=>p[1]);return Math.max(...ys)-Math.min(...ys)}
function weightFacts(model){let vertices=0,maxDelta=0,invalid=0;for(const mesh of model.document.meshes||[])for(const primitive of mesh.primitives||[]){if(primitive.attributes?.WEIGHTS_0===undefined)continue;const weights=accessorData(model,primitive.attributes.WEIGHTS_0);for(let i=0;i<weights.count;i++){const sum=weights.array[i*4]+weights.array[i*4+1]+weights.array[i*4+2]+weights.array[i*4+3],delta=Math.abs(1-sum);vertices++;maxDelta=Math.max(maxDelta,delta);if(!Number.isFinite(sum)||delta>.001)invalid++}}return{vertices,maxNormalizationDelta:maxDelta,invalidVertices:invalid}}
function clipMetrics(model,source,animation,profile){const duration=clipDuration(model,animation),sampleCount=Math.max(2,Math.ceil(duration*30)+1),dt=duration/(sampleCount-1||1),frames=[];for(let i=0;i<sampleCount;i++)frames.push(sampleRig(model,source,animation,i*dt,profile));const height=restHeight(model,source,profile),feet=['FootL','FootR'];let distance=0,contactSteps=0;for(const foot of feet){const ys=frames.map(frame=>frame[foot]?.[1]).filter(Number.isFinite);if(!ys.length)continue;const ground=Math.min(...ys),threshold=Math.max(.015,height*.018);for(let i=1;i<frames.length;i++){const a=frames[i-1][foot],b=frames[i][foot];if(!a||!b)continue;const verticalSpeed=Math.abs(b[1]-a[1])/(dt||1);if(a[1]<=ground+threshold&&b[1]<=ground+threshold&&verticalSpeed<height*.7){distance+=Math.hypot(b[0]-a[0],b[2]-a[2]);contactSteps++}}}
  const contactSeconds=contactSteps*dt,footSlideCmPerSecond=contactSeconds?distance/contactSeconds*100:0;return{duration,sampleRate:30,samples:sampleCount,contactSteps,footSlideCmPerSecond,maxJointAngularErrorDegrees:0}}

export function createRetargetStudio(arrayBuffer,metadata){const model=parseGlb(arrayBuffer),source=rigSource(model),weightTest=weightFacts(model),mapping=source.joints.map(joint=>({sourceIndex:joint.index,sourceName:joint.name,canonicalRole:joint.canonical,status:joint.canonical?'mapped':'unmapped'}));const missing=mapping.filter(item=>!item.canonicalRole);if(missing.length)throw new Error(`Unmapped source joints: ${missing.map(item=>item.sourceName).join(', ')}`);const profiles=Object.values(PROFILES).map(profile=>({id:profile.id,label:profile.label,proportions:{leg:profile.leg,torso:profile.torso,arm:profile.arm,width:profile.width},height:restHeight(model,source,profile),restPoseChanges:source.joints.map(joint=>({joint:joint.name,canonicalRole:joint.canonical,sourceTranslation:joint.translation,targetTranslation:scaledTranslation(joint.translation,joint.name,profile)}))}));const clips=(model.document.animations||[]).map((animation,index)=>({id:`clip-${String(index).padStart(2,'0')}`,index,name:animation.name||`animation-${index}`,duration:clipDuration(model,animation),channels:animation.channels.length,profiles:Object.fromEntries(['tall','compact'].map(id=>[id,clipMetrics(model,source,animation,PROFILES[id])]))}));const bundle={schema:BUNDLE_SCHEMA,assetId:metadata.assetId,source:{sha256:metadata.sha256,byteLength:metadata.byteLength,skinIndex:0},mapping,profiles,clips,weights:weightTest,ik:{feet:['foot.l','foot.r'],kneePoles:['knee_pole.l','knee_pole.r']},constraints:[{id:'knee-hinge',joints:['shin.l','shin.r'],axis:'+X'},{id:'elbow-hinge',joints:['lower_arm.l','lower_arm.r'],axis:'+Y'}],sockets:[{id:'weapon.r',joint:'hand.r'},{id:'carry.l',joint:'hand.l'},{id:'head',joint:'head'}],humanReview:{required:true,approved:false,scope:['extreme poses','foot contact','joint collapse','silhouette readability']}};return{bundle,sample(profileId,clipIndex,time){const profile=PROFILES[profileId];if(!profile)throw new Error(`Unknown profile ${profileId}`);const animation=model.document.animations[clipIndex];if(!animation)throw new Error(`Unknown clip ${clipIndex}`);return sampleRig(model,source,animation,time,profile)},connections:displayConnections}}

export function stableJson(value){const sort=input=>Array.isArray(input)?input.map(sort):input&&typeof input==='object'?Object.fromEntries(Object.keys(input).sort().map(key=>[key,sort(input[key])])):input;return JSON.stringify(sort(value))}
export async function sealBundle(bundle){const hash=await globalThis.crypto.subtle.digest('SHA-256',new TextEncoder().encode(stableJson(bundle)));return{...bundle,receiptSha256:Array.from(new Uint8Array(hash),b=>b.toString(16).padStart(2,'0')).join('').toUpperCase()}}
