(function(){'use strict';
  var $=function(id){return document.getElementById(id);},current=null,busy=false;
  function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(char){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char];});}
  function date(value){return value?new Date(value).toLocaleString():'—';}
  function interval(value){var hours=Number(value||0)/3600000;return hours===168?'7 days':hours===24?'24 hours':hours+' hours';}
  async function api(route,options){var response=await fetch(route,Object.assign({headers:{'content-type':'application/json'}},options||{})),json=await response.json();if(!response.ok||json.ok===false)throw new Error(json.error||('HTTP '+response.status));return json;}
  function setBusy(value){busy=value;['enable','disable','check'].forEach(function(id){$(id).disabled=value||(id==='check'&&!(current&&current.config&&current.config.enabled));});}
  function renderReceipts(items){items=(items||[]).slice().reverse();$('receiptCount').textContent=items.length+' RECEIPT'+(items.length===1?'':'S');$('receipts').innerHTML=items.length?items.map(function(item){var label=item.result||(item.enabled===true?'ENABLED':item.enabled===false?'DISABLED':'CONFIG');return '<div class="receipt"><small>'+esc(date(item.at))+'</small><div><strong>'+esc(label)+'</strong><br><small>'+esc(item.reason||item.actor||'local')+(item.commitSha?' · '+esc(item.commitSha.slice(0,12)):'')+'</small></div><span class="badge">'+esc(item.networkRequests==null?'0 WEB':item.networkRequests+' WEB')+'</span></div>';}).join(''):'<p class="muted">No updater action has been recorded.</p>';}
  function render(status){current=status;var enabled=status.config.enabled,candidate=status.candidate,remote=status.remote;
    $('enabledWord').textContent=enabled?'ON':'OFF';$('networkBadge').textContent=enabled?'EXPLICITLY ENABLED':'ZERO NETWORK';$('networkBadge').className='badge '+(enabled?'on':'off');
    $('heroNote').textContent=enabled?'A due scheduled Heartbeat must receive one Body Pulse lease before a '+(status.config.mode==='AUTO_STAGE'?'signed check and verified download':'check-only read')+'.':'No updater network request can occur while this switch is off.';
    $('stateTitle').textContent=enabled?(status.checking?'CHECKING GITHUB':status.lastReason.replace(/-/g,' ').toUpperCase()):'OFF · LOCAL ONLY';
    $('nextCheck').textContent=enabled?date(status.nextCheckAt)+' · '+interval(status.config.intervalMs):'not scheduled';
    $('lastCheck').textContent=date(status.lastCheckAt);$('installed').textContent=status.installed?(status.installed.version||status.installed.releaseId||status.installed.commitSha.slice(0,12)):'unknown · no installed release ledger';
    $('remote').textContent=remote?((remote.version||remote.releaseId)+' · '+remote.commitSha.slice(0,12)):'not read';$('heartbeat').textContent=status.heartbeatBridge.replace(/_/g,' ').toLowerCase();$('pulseGate').textContent=(status.pulseBridge.moduleEnabled?'enabled':'disabled')+' · '+String(status.pulseBridge.pulseMode||'unknown').toLowerCase()+' · 1 lease/check';
    $('error').hidden=!status.lastError;$('error').textContent=status.lastError||'';$('mode').value=status.config.mode;$('interval').value=String(status.config.intervalMs);$('stageConfirmationWrap').hidden=$('mode').value!=='AUTO_STAGE';
    $('checkState').textContent=status.lastCheckAt?(status.lastError?'FAILED':'CHECKED'):'WAITING';$('trustState').textContent=remote?(remote.manifestTrusted?'SIGNED · '+(remote.trustedKeyId||'TRUSTED'):'HELD · UNTRUSTED'):'NO KEY PROMOTED';
    $('stageState').textContent=candidate?(candidate.state==='STAGED_HELD_FOR_INSTALLER'?'VERIFIED · HELD':'AVAILABLE · NOT DOWNLOADED'):'EMPTY';renderReceipts(status.recentReceipts);setBusy(false);
  }
  async function refresh(){try{var result=await api('/api/workshop-updater');render(result.status);}catch(error){$('stateTitle').textContent='SERVICE OFFLINE';$('error').hidden=false;$('error').textContent=error.message;setBusy(false);}}
  $('mode').onchange=function(){$('stageConfirmationWrap').hidden=$('mode').value!=='AUTO_STAGE';};
  $('refresh').onclick=refresh;
  $('enable').onclick=async function(){if(busy)return;setBusy(true);try{var result=await api('/api/workshop-updater/config',{method:'POST',headers:{'content-type':'application/json','x-axm-workshop-updater':'explicit-updater-config'},body:JSON.stringify({enabled:true,mode:$('mode').value,intervalMs:Number($('interval').value),confirmation:$('confirmation').value,stageConfirmation:$('stageConfirmation').value,actorId:'mike'})});$('confirmation').value='';$('stageConfirmation').value='';render(result.status);}catch(error){$('error').hidden=false;$('error').textContent=error.message;setBusy(false);}};
  $('disable').onclick=async function(){if(busy)return;setBusy(true);try{var result=await api('/api/workshop-updater/config',{method:'POST',headers:{'content-type':'application/json','x-axm-workshop-updater':'explicit-updater-config'},body:JSON.stringify({enabled:false,actorId:'mike'})});render(result.status);}catch(error){$('error').hidden=false;$('error').textContent=error.message;setBusy(false);}};
  $('check').onclick=async function(){if(busy)return;setBusy(true);$('stateTitle').textContent='CHECKING CANONICAL GITHUB';try{var result=await api('/api/workshop-updater/check',{method:'POST',headers:{'content-type':'application/json','x-axm-workshop-updater':'explicit-update-check'},body:JSON.stringify({actorId:'mike'})});render(result.status);}catch(error){await refresh();$('error').hidden=false;$('error').textContent=error.message;setBusy(false);}};
  (async function(){if(window.AXM)await AXM.init({id:'workshop-updater',name:'Workshop Update Gate',version:'v0.1'});await refresh();if(window.AXMHub){AXMHub.log('Workshop Update Gate ready · OFF means zero updater network');AXMHub.verifyPass();}})().catch(function(error){$('stateTitle').textContent='SERVICE OFFLINE';$('error').hidden=false;$('error').textContent=error.message;});
})();
