'use strict';
const fs=require('fs'),path=require('path'),crypto=require('crypto');
const ROOT=__dirname,ORGAN_ROOT=path.join(ROOT,'organs'),FAMILIES=require('./families.json').families;
const STAGES=Object.freeze(['parse','understand','projectGraph','dependencies','api','impact','affectedTests','architecture','refactor','verificationAdapters','sandbox','evidencePassport','rollback','governanceReturn']);
function canon(v){if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return`[${v.map(canon).join(',')}]`;return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canon(v[k])}`).join(',')}}`}
function hash(v){return crypto.createHash('sha256').update(v).digest('hex')}
function paths(){return fs.readdirSync(ORGAN_ROOT,{withFileTypes:true}).filter(x=>x.isDirectory()).map(x=>path.join(ORGAN_ROOT,x.name,'organ.json')).sort()}
function load(p){const resolved=path.resolve(p),r=path.resolve(ORGAN_ROOT)+path.sep;if(!resolved.startsWith(r))throw Error(`ORGAN_PATH_ESCAPE:${p}`);const o=JSON.parse(fs.readFileSync(resolved,'utf8')),c={...o};delete c.sha256;const d=hash(canon(c));if(d!==o.sha256)throw Error(`ORGAN_DIGEST_MISMATCH:${o.organId}`);const dir=path.basename(path.dirname(resolved)),expected=`${String(o.priority).padStart(3,'0')}-${o.languageId}`;if(dir!==expected)throw Error(`ORGAN_PATH_ID_MISMATCH:${o.organId}`);return o}
function all(){return paths().map(load)}
function get(organId){return all().find(x=>x.organId===organId)||null}
function pick(xs,preferred,reason){const u=[...new Map(xs.map(x=>[x.organId,x])).values()];if(preferred){const s=u.find(x=>x.organId===preferred);if(s)return{result:'MATCHED',reason:'PREFERRED_EXPLICIT',organ:s,candidates:u.map(x=>x.organId)}}if(u.length===1)return{result:'MATCHED',reason,organ:u[0],candidates:[u[0].organId]};if(u.length>1)return{result:'SELECTION_REQUIRED',reason,organ:null,candidates:u.map(x=>x.organId).sort()};return null}
function detect({filePath='',firstLine='',preferredOrganId=null}={}){const os=all(),n=String(filePath).replace(/\\/g,'/'),l=n.toLowerCase(),ctx=l.startsWith('/')?l:`/${l}`,b=path.posix.basename(n);
 let r=pick(os.filter(o=>o.detect.base.includes(b)),preferredOrganId,'BASENAME');if(r)return r;
 r=pick(os.filter(o=>o.detect.path.some(x=>ctx.includes(x.toLowerCase()))),preferredOrganId,'PATH_CONTEXT');if(r)return r;
 const em=[];for(const o of os)for(const e of o.detect.ext)if(l.endsWith(e.toLowerCase()))em.push({o,n:e.length});if(em.length){const m=Math.max(...em.map(x=>x.n));r=pick(em.filter(x=>x.n===m).map(x=>x.o),preferredOrganId,'LONGEST_EXTENSION');if(r)return r}
 const toks=String(firstLine).startsWith('#!')?String(firstLine).toLowerCase().split(/[^a-z0-9_.+-]+/).filter(Boolean):[];r=pick(os.filter(o=>o.detect.shebang.some(x=>toks.includes(x.toLowerCase()))),preferredOrganId,'SHEBANG');if(r)return r;
 return{result:'UNKNOWN_LANGUAGE',reason:'NO_DETERMINISTIC_MATCH',organ:null,candidates:[]}}
function plan({organId,requestedStages=STAGES}={}){const o=get(organId);if(!o)return{result:'UNKNOWN_ORGAN',organId:organId||null};const bad=requestedStages.filter(s=>!STAGES.includes(s));if(bad.length)return{result:'UNKNOWN_STAGE',organId,unknownStages:bad};const f=FAMILIES[o.family];if(!f)throw Error(`UNKNOWN_FAMILY:${o.family}`);const bound=o.execution==='PR51_EXECUTABLE_DONOR_BOUND';return{result:bound?'PLAN_READY_BOUND_EXECUTOR':'PLAN_READY_EXECUTION_HELD',organId:o.organId,organDigest:o.sha256,family:o.family,kind:o.kind,execution:o.execution,requestedStages:[...requestedStages],familySignals:f,toolchainCandidates:[...o.toolchainCandidates],authority:{workspaceMutation:false,toolExecution:false,network:false,install:false,promotion:false,canon:false},evidenceRequired:['organDigest','inputDigest','adapterId','adapterDigest','toolVersions','verificationResults','outputDigests'],note:bound?'PR51 donor is evidence-bound; this registry still executes nothing.':'Native execution stays held until a language-specific adapter and verifier are bound.'}}
module.exports={STAGES,all,get,detect,plan};
