// Generated by AXM Machine Geometry Foundry 0.4.0
// Asset: AXM-ENERGY-CORE-001 AXM Modular Energy Core v0.4.0
// Units: millimetres; source orientation: +Z up, -Y forward.
// Canonical source is recipe.json. This is an editable generated bridge.

// instance: base | base: base | print_group: base
color([0.09412, 0.11373, 0.15294, 1.00000])
translate([0, 0, 90]) rotate([0, 0, 0]) scale([1, 1, 1]) cylinder(h=180, r=650, center=true, $fn=48);

// instance: lower_ring | base: lower_ring | print_group: lower_ring
color([0.13725, 0.80392, 0.92157, 1.00000])
translate([0, 0, 440]) rotate([0, 0, 0]) scale([1, 1, 1]) difference() { cylinder(h=110, r=565, center=true, $fn=48); cylinder(h=110.02, r=470, center=true, $fn=48); }

// instance: upper_ring | base: upper_ring | print_group: upper_ring
color([0.13725, 0.80392, 0.92157, 1.00000])
translate([0, 0, 1320]) rotate([0, 0, 0]) scale([1, 1, 1]) difference() { cylinder(h=110, r=565, center=true, $fn=48); cylinder(h=110.02, r=470, center=true, $fn=48); }

// instance: core | base: core | print_group: core
color([0.66275, 0.32157, 1.00000, 0.92157])
translate([0, 0, 880]) rotate([0, 0, 0]) scale([1, 1, 1]) scale([310, 310, 430]) sphere(r=1, $fn=48);

// instance: pillar__r00 | base: pillar | print_group: pillar
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([378.30213, 378.30213, 820]) rotate([0, 0, 45]) scale([1, 1, 1]) cube([145, 145, 1080], center=true);

// instance: pillar__r01 | base: pillar | print_group: pillar
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([-378.30213, 378.30213, 820]) rotate([0, 0, 135]) scale([1, 1, 1]) cube([145, 145, 1080], center=true);

// instance: pillar__r02 | base: pillar | print_group: pillar
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([-378.30213, -378.30213, 820]) rotate([0, 0, 225]) scale([1, 1, 1]) cube([145, 145, 1080], center=true);

// instance: pillar__r03 | base: pillar | print_group: pillar
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([378.30213, -378.30213, 820]) rotate([0, 0, 315]) scale([1, 1, 1]) cube([145, 145, 1080], center=true);

// instance: base_gear | base: base_gear | print_group: base_gear
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([0, 0, 225]) rotate([0, 0, 0]) scale([1, 1, 1]) linear_extrude(height=90, center=true, convexity=10) polygon(points=[[515.0, 0.0], [415.3481053, 111.29218939], [446.00308295, 257.5], [304.05591591, 304.05591591], [257.5, 446.00308295], [111.29218939, 415.3481053], [0.0, 515.0], [-111.29218939, 415.3481053], [-257.5, 446.00308295], [-304.05591591, 304.05591591], [-446.00308295, 257.5], [-415.3481053, 111.29218939], [-515.0, 0.0], [-415.3481053, -111.29218939], [-446.00308295, -257.5], [-304.05591591, -304.05591591], [-257.5, -446.00308295], [-111.29218939, -415.3481053], [-0.0, -515.0], [111.29218939, -415.3481053], [257.5, -446.00308295], [304.05591591, -304.05591591], [446.00308295, -257.5], [415.3481053, -111.29218939]]);

// instance: cap | base: cap | print_group: cap
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([0, 0, 1580]) rotate([0, 0, 0]) scale([1, 1, 1]) cylinder(h=180, r1=585, r2=440, center=true, $fn=48);
