// Generated by AXM Machine Geometry Foundry 0.4.0
// Asset: AXM-BARRIER-001 AXM Powered Street Barrier v0.4.0
// Units: millimetres; source orientation: +Z up, -Y forward.
// Canonical source is recipe.json. This is an editable generated bridge.

// instance: foot__l00 | base: foot | print_group: foot
color([0.09412, 0.11373, 0.15294, 1.00000])
translate([-700, 0, 60]) rotate([0, 0, 0]) scale([1, 1, 1]) cube([480, 700, 120], center=true);

// instance: foot__l01 | base: foot | print_group: foot
color([0.09412, 0.11373, 0.15294, 1.00000])
translate([700, 0, 60]) rotate([0, 0, 0]) scale([1, 1, 1]) cube([480, 700, 120], center=true);

// instance: post__l00 | base: post | print_group: post
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([-700, 0, 610]) rotate([0, 0, 0]) scale([1, 1, 1]) cylinder(h=1050, r1=150, r2=110, center=true, $fn=24);

// instance: post__l01 | base: post | print_group: post
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([700, 0, 610]) rotate([0, 0, 0]) scale([1, 1, 1]) cylinder(h=1050, r1=150, r2=110, center=true, $fn=24);

// instance: beam | base: beam | print_group: beam
color([1.00000, 0.67451, 0.14510, 1.00000])
translate([0, 0, 780]) rotate([0, 0, 0]) scale([1, 1, 1]) cube([1700, 180, 230], center=true);

// instance: beam_insert | base: beam_insert | print_group: beam_insert
color([0.13725, 0.80392, 0.92157, 1.00000])
translate([0, -5, 780]) rotate([0, 0, 0]) scale([1, 1, 1]) cube([1250, 195, 80], center=true);

// instance: light__l00 | base: light | print_group: light
color([1.00000, 0.67451, 0.14510, 1.00000])
translate([-700, 0, 1190]) rotate([0, 0, 0]) scale([1, 1, 1]) sphere(r=95, $fn=36);

// instance: light__l01 | base: light | print_group: light
color([1.00000, 0.67451, 0.14510, 1.00000])
translate([700, 0, 1190]) rotate([0, 0, 0]) scale([1, 1, 1]) sphere(r=95, $fn=36);
