(function(){
  'use strict';
  var $=function(id){return document.getElementById(id);},params=new URLSearchParams(location.search),sessionId=params.get('session'),result=null,aiText='';
  function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function key(suffix){return'axm.bondfire.'+(sessionId||'unknown')+'.'+suffix;}
  function evidence(){return{sessionId:result.session_id,game:result.game||{game_id:result.game_id},status:result.status,durationTicks:result.duration_ticks,startedAt:result.started_at,endedAt:result.ended_at,players:(result.selected_players||[]).map(function(p){return{seat:p.seat_id,name:p.display_name,type:p.type};})};}
  function render(){var game=result.game||{};$('gameTitle').textContent=game.name||result.game_id||'Finished game';$('status').textContent=(result.confirmed_finish?'CONFIRMED FINISH':'STOPPED')+' · '+result.session_id;$('facts').innerHTML='<div class="fact"><b>'+esc(result.status||'ended')+'</b><span>RESULT STATE</span></div><div class="fact"><b>'+Number(result.duration_ticks||0)+'</b><span>ENGINE TICKS</span></div><div class="fact"><b>'+((result.selected_players||[]).length)+'</b><span>PLAYERS</span></div>';$('players').innerHTML=(result.selected_players||[]).map(function(p){return'<span class="player">'+esc(p.display_name)+' · '+esc(p.type)+'</span>';}).join('');$('humanView').value=localStorage.getItem(key('human'))||'';$('candidate').value=localStorage.getItem(key('candidate'))||'';renderChat();}
  function renderChat(){var rows=[];try{rows=JSON.parse(localStorage.getItem(key('chat'))||'[]');}catch(e){}$('chat').innerHTML=rows.length?rows.map(function(row){return'<div class="message"><b>'+esc(row.by)+':</b> '+esc(row.text)+'</div>';}).join(''):'<span style="color:#778495">No discussion yet.</span>';}
  function addMessage(by,text){var rows=[];try{rows=JSON.parse(localStorage.getItem(key('chat'))||'[]');}catch(e){}rows.push({by:by,text:text,at:new Date().toISOString()});localStorage.setItem(key('chat'),JSON.stringify(rows.slice(-30)));renderChat();}
  async function askAI(){var human=$('humanView').value.trim();$('askAI').disabled=true;$('aiView').textContent='Waiting for a connected collaborator…';try{var prompt='AXM BONDFIRE\nRecorded evidence:\n'+JSON.stringify(evidence(),null,2)+'\n\nHuman perspective (a perspective, not automatically fact):\n'+(human||'[not supplied]')+'\n\nGive a concise independent perspective. Separate facts from interpretation. End with "Candidate:" and at most one small evidence-backed lesson, or "Candidate: none".';var response=await fetch('http://127.0.0.1:8787/ask',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({messages:[{role:'user',content:prompt}],opts:{maxTokens:450,temperature:.25}})});var body=await response.json();if(!response.ok)throw new Error(body.error||('HTTP '+response.status));aiText=body.text||'';$('aiView').textContent=aiText;var match=aiText.match(/Candidate:\s*([^\n]+(?:\n(?!\w+:)[^\n]+)*)/i);if(match&&!/none/i.test(match[1])&&!$('candidate').value.trim())$('candidate').value=match[1].trim();addMessage('AI',aiText);}catch(e){$('aiView').textContent='No AI response was saved: '+e.message;}finally{$('askAI').disabled=false;}}
  function saveNext(){var text=$('candidate').value.trim();if(!text)return state('Write a candidate first.');localStorage.setItem('axm.bondfire.next-match',JSON.stringify({text:text,sessionId:sessionId,gameId:result.game_id,at:new Date().toISOString()}));state('Kept for the next match only. Not identity wisdom.');}
  function savePrivate(){var text=$('candidate').value.trim();if(!text)return state('Write a candidate first.');localStorage.setItem(key('private'),JSON.stringify({text:text,evidence:evidence(),human:$('humanView').value.trim(),ai:aiText,at:new Date().toISOString()}));state('Private local note saved for this result.');}
  async function saveShared(){var text=$('candidate').value.trim();if(!text)return state('Write a candidate first.');try{if(!window.AXMIdentity)throw new Error('identity service unavailable');await AXMIdentity.init();var stored=await AXMIdentity.absorb({tool:'game-night',author:'human-reviewed-team',kind:'lesson',text:text,tags:['bondfire','game-night',result.game_id],context:{evidence:evidence(),humanPerspective:$('humanView').value.trim(),aiPerspective:aiText,explicitPromotion:true}});state('Shared wisdom '+(stored&&stored.status||'saved')+'. Nothing was auto-promoted.');}catch(e){state('Not saved: '+e.message);}}
  function state(text){$('saveState').textContent=text;}
  $('humanView').oninput=function(){localStorage.setItem(key('human'),this.value);};$('candidate').oninput=function(){localStorage.setItem(key('candidate'),this.value);};$('askAI').onclick=askAI;$('addChat').onclick=function(){var text=$('chatInput').value.trim();if(!text)return;$('chatInput').value='';addMessage('Human',text);};$('discard').onclick=function(){localStorage.removeItem(key('candidate'));localStorage.removeItem(key('private'));$('candidate').value='';state('Discarded. Nothing was promoted.');};$('nextOnly').onclick=saveNext;$('privateSave').onclick=savePrivate;$('sharedSave').onclick=saveShared;
  if(!sessionId){$('status').textContent='No result selected';return;}fetch('/game-api/results?session='+encodeURIComponent(sessionId),{cache:'no-store'}).then(function(r){return r.json().then(function(body){if(!r.ok)throw new Error(body.error||'result unavailable');return body;});}).then(function(body){result=body.result;render();}).catch(function(e){$('status').textContent='Could not load result · '+e.message;});
})();
