#!/usr/bin/env node
'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const read = name => fs.readFileSync(path.join(__dirname, name), 'utf8');
const html = read('index.html'), app = read('app.js'), contract = JSON.parse(read('module.contract.json')), manifest = JSON.parse(read('manifest.json'));
const controls = JSON.parse(fs.readFileSync(path.join(__dirname,'..','..','shared','cognitive-resource','command-center-controls.json'),'utf8'));
assert.equal(manifest.audience, 'human-machine');
assert.equal(manifest.schema, 'axm.tool-manifest/v1');
assert.equal(manifest.kind, 'product');
assert.deepEqual(manifest.permissions, contract.permissions);
assert.deepEqual(contract.lifecycle, { state_owner: 'service', reload: 'resume', disconnect: 'graceful-degrade', cleanup: 'explicit' });
assert(contract.provides.includes('missing-hand-requests'));
assert(contract.boundaries.refuses.includes('invented-capability'));
assert(contract.boundaries.refuses.includes('body-mode-change'));
assert(html.includes('What should the system build?'));
assert(html.includes('SIMPLE LOCAL PLANNING'));
assert(app.includes('Client.compile'));
assert(app.includes('Client.commit'));
assert(app.includes('Client.setStatus'));
assert(!/setInterval|setTimeout/.test(app));
assert(html.includes('Show me the plan'));
assert(html.includes('Save plan &amp; queue safe jobs'));
assert(html.includes('Nothing is saved or started'));
assert(!html.includes('Compile direction'));
assert(!html.includes('Commit bounded direction'));
const directionControls=controls.controls.filter(item=>item.moduleId==='workshop-direction'),ids=directionControls.map(item=>item.id);
assert.deepStrictEqual(ids.sort(),['workshop-direction-commit','workshop-direction-lifecycle','workshop-direction-open','workshop-direction-preview','workshop-direction-status']);
assert(directionControls.every(item=>item.automatic===false));
assert(directionControls.find(item=>item.id==='workshop-direction-preview').mutation===false);
assert(directionControls.find(item=>item.id==='workshop-direction-commit').actionHeader==='x-axm-direction: explicit-commit');
assert(directionControls.every(item=>typeof item.help==='string'&&item.help.length>0));
console.log('PASS Workshop Direction UI · human-machine input · no private timer · no fake hand');
