// Generated by AXM Machine Geometry Foundry 0.4.0
// Asset: AXM-TURRET-001 AXM Compact Defense Turret v0.4.0
// Units: millimetres; source orientation: +Z up, -Y forward.
// Canonical source is recipe.json. This is an editable generated bridge.

// instance: base | base: base | print_group: base
color([0.09412, 0.11373, 0.15294, 1.00000])
translate([0, 0, 90]) rotate([0, 0, 0]) scale([1, 1, 1]) cylinder(h=180, r=620, center=true, $fn=48);

// instance: rotation_ring | base: rotation_ring | print_group: rotation_ring
color([0.13725, 0.80392, 0.92157, 1.00000])
translate([0, 0, 245]) rotate([0, 0, 0]) scale([1, 1, 1]) difference() { cylinder(h=130, r=540, center=true, $fn=48); cylinder(h=130.02, r=390, center=true, $fn=48); }

// instance: body | base: body | print_group: body
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([0, 0, 590]) rotate([0, 0, 0]) scale([1, 1, 1]) cylinder(h=620, r1=500, r2=360, center=true, $fn=36);

// instance: head | base: head | print_group: head
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([0, -40, 980]) rotate([0, 0, 0]) scale([1, 1, 1]) cube([620, 520, 360], center=true);

// instance: barrel | base: barrel | print_group: barrel
color([0.13725, 0.80392, 0.92157, 1.00000])
translate([0, -650, 1010]) rotate([90, 0, 0]) scale([1, 1, 1]) cylinder(h=900, r=95, center=true, $fn=24);

// instance: muzzle | base: muzzle | print_group: muzzle
color([1.00000, 0.67451, 0.14510, 1.00000])
translate([0, -1100, 1010]) rotate([90, 0, 0]) scale([1, 1, 1]) difference() { cylinder(h=150, r=135, center=true, $fn=24); cylinder(h=150.02, r=70, center=true, $fn=24); }

// instance: stabilizer__r00 | base: stabilizer | print_group: stabilizer
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([395.9798, 395.9798, 175]) rotate([0, 0, 45]) scale([1, 1, 1]) cube([260, 360, 150], center=true);

// instance: stabilizer__r01 | base: stabilizer | print_group: stabilizer
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([-395.9798, 395.9798, 175]) rotate([0, 0, 135]) scale([1, 1, 1]) cube([260, 360, 150], center=true);

// instance: stabilizer__r02 | base: stabilizer | print_group: stabilizer
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([-395.9798, -395.9798, 175]) rotate([0, 0, 225]) scale([1, 1, 1]) cube([260, 360, 150], center=true);

// instance: stabilizer__r03 | base: stabilizer | print_group: stabilizer
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([395.9798, -395.9798, 175]) rotate([0, 0, 315]) scale([1, 1, 1]) cube([260, 360, 150], center=true);
