(() => {
  'use strict';
  const AXM=window.AXM, R=window.AXMRender, V=window.AXMValidate, X=window.AXMExport;
  const $=(s,root=document)=>root.querySelector(s), $$=(s,root=document)=>[...root.querySelectorAll(s)];
  const skinLab={controls:AXM.defaultControls(AXM.getMold('axm.mold.living-skin-laboratory')),variant:{theme:'aetherglass',format:'landscape',motion:'ambient',performance:'standard',state:'idle'}};
  const portalLab={controls:AXM.defaultControls(AXM.getMold('axm.mold.atmospheric-portal-scene')),variant:{theme:'aetherglass',format:'landscape',motion:'ambient',performance:'standard',state:'idle'}};
  const effectState={edge_glow:.45,inner_glow:.38,fog:.28,particles:.42,energy_veins:.48,scan_noise:.16,glass_distortion:.12,pulse:.22};
  let currentCandidate=null,currentThemeDraft=null;
  let previewReturnFocus=null;

  function go(view){
    $$('.nav-item').forEach(x=>{const active=x.dataset.view===view;x.classList.toggle('active',active);if(active)x.setAttribute('aria-current','page');else x.removeAttribute('aria-current')});$$('.view').forEach(x=>x.classList.toggle('active',x.dataset.viewPanel===view));
    const panel=$(`[data-view-panel="${view}"]`);panel?.querySelector('h2')?.setAttribute('tabindex','-1');panel?.querySelector('h2')?.focus({preventScroll:true});
    if(view==='editor')renderEditor();if(view==='atlas')renderAtlas();if(view==='proof')renderValidation();if(view==='presets')renderPresets();if(view==='themes')renderThemes();if(view==='extensions')renderExtensions();if(view==='export')renderExports();if(view==='lineage')renderLineage();if(view==='recovery')window.AXMRecoveryUI?.render();if(view==='status')renderStatus();if(view==='preview')renderPreviewLab();if(view==='variants')renderVariants();if(view==='skin')renderSkinLab();if(view==='light')renderLightLab();if(view==='effects')renderEffectLab();
  }
  function setFocusedPreview(active){
    const preview=$('#mainPreview'),button=$('#fullscreenPreview');if(!preview||!button)return;
    const opening=Boolean(active);
    if(opening&&!preview.classList.contains('focused'))previewReturnFocus=document.activeElement instanceof HTMLElement?document.activeElement:button;
    preview.classList.toggle('focused',opening);document.body.classList.toggle('preview-focus-active',opening);
    button.setAttribute('aria-expanded',String(opening));button.textContent=opening?'Exit focus preview':'Focus preview';
    if(opening)requestAnimationFrame(()=>button.focus());
    else if(previewReturnFocus){const target=previewReturnFocus;previewReturnFocus=null;requestAnimationFrame(()=>{if(target.isConnected)target.focus()})}
  }
  function statusClass(status){return status==='APPROVED'?'built':status==='EXPERIMENTAL'?'experimental':'tested'}
  function statusPill(status){return `<span class="status-pill ${statusClass(status)}">${AXM.escapeHTML(status)}</span>`}
  function metric(value,label){return `<div class="metric"><b>${value}</b><span>${AXM.escapeHTML(label)}</span></div>`}
  function setupNavigation(){
    $$('.nav-item').forEach(b=>b.addEventListener('click',()=>go(b.dataset.view)));$$('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));
    const boundedJSONInputs=new Set(['presetFileInput','themeFileInput','extensionFileInput','workspaceFileInput','familyFileInput']);
    document.addEventListener('change',event=>{const input=event.target,file=input?.files?.[0];if(!boundedJSONInputs.has(input?.id)||!file||file.size<=16_000_000)return;event.preventDefault();event.stopImmediatePropagation();input.value='';AXM.toast('Package rejected before reading: the 16 MB JSON limit was exceeded.');},true);
    $('#themeToggle').addEventListener('click',()=>{AXM.state.interfaceTheme=AXM.state.interfaceTheme==='dark'?'light':'dark';document.documentElement.dataset.theme=AXM.state.interfaceTheme;AXM.setSettings({interfaceTheme:AXM.state.interfaceTheme});$('#themeToggle').textContent=`Interface: ${AXM.state.interfaceTheme}`;});
    $('#motionToggle').addEventListener('click',()=>{AXM.state.reducedMotion=!AXM.state.reducedMotion;AXM.setSettings({reducedMotion:AXM.state.reducedMotion});updateTopButtons();R.stopAll();renderMainPreview();AXM.toast(AXM.state.reducedMotion?'Reduced motion enabled.':'Motion enabled.');});
    $('#powerToggle').addEventListener('click',()=>{AXM.state.lowPower=!AXM.state.lowPower;AXM.setSettings({lowPower:AXM.state.lowPower});if(AXM.state.lowPower)AXM.state.variant.performance='low';updateTopButtons();renderEditor();});
    document.addEventListener('keydown',e=>{if(!$('#mainPreview').classList.contains('focused'))return;if(e.key==='Escape'){e.preventDefault();setFocusedPreview(false)}else if(e.key==='Tab'){e.preventDefault();$('#fullscreenPreview').focus()}});
  }
  function updateTopButtons(){document.documentElement.dataset.theme=AXM.state.interfaceTheme;$('#themeToggle').textContent=`Interface: ${AXM.state.interfaceTheme}`;$('#motionToggle').textContent=`Motion: ${AXM.state.reducedMotion?'reduced':'enabled'}`;$('#motionToggle').setAttribute('aria-pressed',String(AXM.state.reducedMotion));$('#powerToggle').textContent=`Power: ${AXM.state.lowPower?'low':'standard'}`;$('#powerToggle').setAttribute('aria-pressed',String(AXM.state.lowPower));}

  function renderOverview(){
    const roots=AXM.REG.molds.filter(m=>m.source_kind==='root').length,derived=AXM.REG.molds.filter(m=>m.source_kind==='derived').length,extensions=AXM.getExtensions(false).length,localThemes=AXM.getLocalThemes(false).length;
    $('#overviewMetrics').innerHTML=[metric(`${roots}+${derived}`,'protected root + sparse derived molds'),metric(extensions,'active local extensions'),metric(`${AXM.REG.themes.length}+${localThemes}`,'protected + active local themes'),metric(AXM.REG.organs.length,'organ contracts'),metric(AXM.REG.tokens.length,'semantic tokens')].join('');
  }
  function populateFilters(){
    const add=(select,items)=>{select.querySelectorAll('option:not(:first-child)').forEach(o=>o.remove());select.insertAdjacentHTML('beforeend',items.map(x=>`<option value="${AXM.escapeHTML(x)}">${AXM.escapeHTML(x)}</option>`).join(''))};
    add($('#atlasCategory'),[...new Set(AXM.getAllMolds().map(m=>m.category))].sort());
    add($('#organCategory'),[...new Set(AXM.REG.organs.map(o=>o.category))].sort());
    add($('#tokenCategory'),[...new Set(AXM.REG.tokens.map(t=>t.category))].sort());
    add($('#atlasTheme'),AXM.getAllThemes().map(t=>t.id));
  }
  function renderAtlas(){
    const q=$('#atlasSearch').value.trim().toLowerCase(),cat=$('#atlasCategory').value,status=$('#atlasStatus').value,theme=$('#atlasTheme').value,all=AXM.getAllMolds();
    const items=all.filter(m=>(!q||`${m.name} ${m.description} ${m.category} ${m.renderer_options?.layout||''} ${m.source_kind} ${m.extension_state||''}`.toLowerCase().includes(q))&&(cat==='all'||m.category===cat)&&(status==='all'||m.approval_state===status)&&(theme==='all'||AXM.variantValues(m,'theme').includes(theme)));
    $('#atlasCount').textContent=`${items.length} shown · ${all.length} usable total`;const grid=$('#moldGrid');grid.innerHTML='';
    items.forEach(m=>{const controls=AXM.defaultControls(m),variant=AXM.defaultVariant(m);if(variant.performance)variant.performance='low';if(variant.motion)variant.motion='still';const card=document.createElement('article');card.className='mold-card';card.dataset.sourceKind=m.source_kind;const extensionTag=m.source_kind==='extension'?`<span class="tag">${AXM.escapeHTML(m.extension_state)}</span>`:'';card.innerHTML=`<div class="mold-thumb"></div><div class="mold-body"><div class="panel-head"><code>${AXM.escapeHTML(m.id)}</code>${statusPill(m.approval_state)}</div><h3>${AXM.escapeHTML(m.name)}</h3><p>${AXM.escapeHTML(m.description)}</p><div class="tag-row"><span class="tag">${AXM.escapeHTML(m.category)}</span><span class="tag">${AXM.escapeHTML(m.source_kind)}</span>${extensionTag}<span class="tag">L${m.composition_level}</span><span class="tag">${m.outputs.length} exports</span></div><div class="card-actions"><button class="primary-button" data-open type="button">Open</button><button class="quiet-button" data-inspect type="button">Inspect</button></div></div>`;R.renderThumbnail($('.mold-thumb',card),m,controls,variant);$('[data-open]',card).addEventListener('click',()=>{AXM.setMold(m.id);go('editor')});$('[data-inspect]',card).addEventListener('click',()=>AXM.openJSON(m.name,m));grid.appendChild(card)});
  }
  function renderOrgans(){
    const q=$('#organSearch').value.trim().toLowerCase(),cat=$('#organCategory').value;const items=AXM.REG.organs.filter(o=>(!q||`${o.id} ${o.description} ${o.category}`.toLowerCase().includes(q))&&(cat==='all'||o.category===cat));$('#organCount').textContent=`${items.length} shown · ${AXM.REG.organs.length} total`;$('#organGrid').innerHTML=items.map(o=>`<article class="registry-card"><div class="panel-head"><code>${AXM.escapeHTML(o.id)}</code>${statusPill(o.status)}</div><h3>${AXM.escapeHTML(o.description)}</h3><p>${o.inputs.length} inputs → ${o.outputs.length} outputs · ${AXM.escapeHTML(o.performance_cost)} cost</p><div class="tag-row"><span class="tag">${o.category}</span>${o.compatible_runtimes.slice(0,3).map(x=>`<span class="tag">${x}</span>`).join('')}</div></article>`).join('');
  }
  function renderTokens(){
    const q=$('#tokenSearch').value.trim().toLowerCase(),cat=$('#tokenCategory').value;const items=AXM.REG.tokens.filter(t=>(!q||`${t.id} ${t.value} ${t.description}`.toLowerCase().includes(q))&&(cat==='all'||t.category===cat));$('#tokenCount').textContent=`${items.length} shown · ${AXM.REG.tokens.length} total`;$('#tokenGrid').innerHTML=items.map(t=>{const sw=t.type==='color'&&t.value!=='transparent'?`<span class="swatch" style="background:${t.value}"></span>`:'';return `<article class="token-card"><code>${AXM.escapeHTML(t.id)}</code><div class="token-value">${sw}${AXM.escapeHTML(String(t.value))}</div></article>`}).join('');
  }

  function themeFieldsFromForm(){
    return {
      name:AXM.sanitizeText($('#themeName').value,100),material_language:AXM.sanitizeText($('#themeMaterial').value,180),public_scope:$('#themePublicScope').value,
      compatible_renderers:$('#themeRenderers').value.split(',').map(item=>item.trim()).filter(Boolean),surface:$('#themeSurface').value,surface_2:$('#themeSurface2').value,panel:AXM.sanitizeText($('#themePanel').value,80),text:$('#themeText').value,muted:$('#themeMuted').value,accent:$('#themeAccent').value,accent_2:$('#themeAccent2').value,warning:$('#themeWarning').value,success:$('#themeSuccess').value,line:AXM.sanitizeText($('#themeLine').value,80),shadow:AXM.sanitizeText($('#themeShadow').value,80),glow_rgb:AXM.sanitizeText($('#themeGlowRGB').value,32),glass:Number($('#themeGlass').value),paper_noise:Number($('#themeNoise').value),contrast_target:Number($('#themeContrast').value),motion_character:AXM.sanitizeText($('#themeMotion').value,160),low_power_fallback:AXM.sanitizeText($('#themeFallback').value,180),provenance:{author:'Local AXM user',license:'user-controlled',rights_scope:$('#themePublicScope').value==='public-safe'?'public-safe-user-controlled':'private-local',transformation_history:['Theme Foundry v0.9.1 form build']}
    };
  }
  function themePreviewValidation(theme){
    const report=AXM.themeValidation(theme);
    if(!AXM.REG.themes.includes(theme))return report;
    const checks=report.checks.map(check=>check.label==='Theme ID uniqueness'&&check.state==='FAIL'?{...check,state:'PASS',evidence:'Existing protected registry theme selected as a read-only preview source.'}:check);
    const summary=checks.reduce((totals,check)=>(totals[check.state.toLowerCase()]++,totals),{pass:0,warn:0,fail:0});
    return {...report,checks,summary,status:summary.fail?'FAIL':summary.warn?'WARN':'PASS'};
  }
  function loadThemeForm(theme){
    if(!theme)return;const set=(id,value)=>{$('#'+id).value=value??''};set('themeName',`${theme.name} Child`);set('themeMaterial',theme.material_language);set('themePublicScope',theme.public_scope||'private');set('themeRenderers',(theme.compatible_renderers||['card','living-skin','portal-scene']).join(','));set('themeSurface',theme.surface);set('themeSurface2',theme.surface_2);set('themePanel',theme.panel);set('themeText',theme.text);set('themeMuted',theme.muted);set('themeAccent',theme.accent);set('themeAccent2',theme.accent_2);set('themeWarning',theme.warning);set('themeSuccess',theme.success);set('themeLine',theme.line);set('themeShadow',theme.shadow);set('themeGlowRGB',theme.glow_rgb);set('themeGlass',theme.glass);set('themeNoise',theme.paper_noise);set('themeContrast',theme.contrast_target);set('themeMotion',theme.motion_character);set('themeFallback',theme.low_power_fallback);currentThemeDraft=null;const report=themePreviewValidation(theme);renderThemePreview(theme,report);$('#themeManifest').value=JSON.stringify(theme,null,2);$('#themeValidationReport').innerHTML='<div class="readout">Edit the fields, then build a local draft. The protected base theme remains unchanged.</div>';
  }
  function renderBlockedThemePreview(host,report){
    if(!host)return false;host.replaceChildren();const message=document.createElement('p');message.className='readout';message.textContent=`Preview blocked: theme validation has ${report?.summary?.fail??1} failure(s). Repair declarative color or manifest fields before rendering.`;host.appendChild(message);return false;
  }
  function renderThemePreview(theme,report=theme?AXM.themeValidation(theme):null){
    const host=$('#themePreview');if(!host||!theme)return false;if(!report||report.summary?.fail)return renderBlockedThemePreview(host,report);
    host.replaceChildren();
    const card=document.createElement('article');card.className='theme-preview-card';card.style.backgroundImage=`linear-gradient(135deg, ${theme.surface}, ${theme.surface_2})`;card.style.backgroundColor=theme.surface;card.style.color=theme.text;card.style.borderColor=theme.line;
    const panel=document.createElement('div');panel.className='theme-preview-panel';panel.style.backgroundColor=theme.panel;panel.style.boxShadow=`0 28px 80px ${theme.shadow}`;panel.style.borderColor=theme.line;
    const eyebrow=document.createElement('p');eyebrow.className='eyebrow';eyebrow.textContent=theme.id||'theme draft';
    const title=document.createElement('h3');title.textContent=theme.name||'Theme Draft';
    const description=document.createElement('p');description.textContent=theme.material_language||'Semantic material language';
    const signal=document.createElement('div');signal.className='theme-preview-signal';signal.style.color=theme.accent;
    const signalLabel=document.createElement('span');signalLabel.textContent='PRIMARY';const signalCopy=document.createElement('b');signalCopy.textContent='Visual meaning stays inspectable.';signal.append(signalLabel,signalCopy);
    const row=document.createElement('div');row.className='button-row';const sample=document.createElement('button');sample.type='button';sample.className='primary-button';sample.disabled=true;sample.tabIndex=-1;sample.textContent=theme.motion_character||'Motion character';sample.style.backgroundColor=theme.accent;sample.style.color=theme.surface;
    const scope=document.createElement('span');scope.className='tag';scope.textContent=theme.public_scope||'private';row.append(sample,scope);
    panel.append(eyebrow,title,description,signal,row);card.appendChild(panel);host.appendChild(card);return true;
  }
  function renderThemeSwatches(host,theme,report){
    if(!host)return false;host.replaceChildren();host.style.backgroundImage='';host.style.backgroundColor='';
    if(!report||report.summary?.fail){const blocked=document.createElement('p');blocked.className='readout';blocked.textContent='Visual swatches blocked until this theme passes validation.';host.appendChild(blocked);return false}
    host.style.backgroundImage=`linear-gradient(135deg, ${theme.surface}, ${theme.surface_2})`;host.style.backgroundColor=theme.surface;
    [theme.accent,theme.accent_2,theme.success].forEach(color=>{const swatch=document.createElement('span');swatch.style.backgroundColor=color;host.appendChild(swatch)});return true;
  }
  function renderThemeValidation(report){
    $('#themeValidationReport').innerHTML=report.checks.map(check=>`<div class="validation-row ${check.state.toLowerCase()}"><span class="check-state">${check.state}</span><div><b>${AXM.escapeHTML(check.label)}</b><p>${AXM.escapeHTML(check.evidence)}</p></div></div>`).join('');
  }
  function buildThemeDraftFromForm(){
    try{currentThemeDraft=AXM.buildThemeDraft($('#themeBase').value,themeFieldsFromForm());const report=AXM.themeValidation(currentThemeDraft);$('#themeManifest').value=JSON.stringify(currentThemeDraft,null,2);renderThemePreview(currentThemeDraft,report);renderThemeValidation(report);AXM.toast(`Theme draft: ${report.status}`);return {theme:currentThemeDraft,report}}catch(err){renderBlockedThemePreview($('#themePreview'));AXM.toast(`Theme draft failed: ${err.message}`);return null}
  }
  function renderThemes(){
    const themes=AXM.getAllThemes(),allBases=AXM.getAllThemes(),base=$('#themeBase'),selected=base.value||'aetherglass';base.innerHTML=allBases.map(theme=>`<option value="${AXM.escapeHTML(theme.id)}">${AXM.escapeHTML(theme.name)}${theme.source_kind==='local-theme'?' · local':''}</option>`).join('');base.value=allBases.some(theme=>theme.id===selected)?selected:(allBases[0]?.id||'aetherglass');
    if(!currentThemeDraft)loadThemeForm(AXM.findTheme(base.value));
    const local=AXM.getLocalThemes(true),active=local.filter(theme=>theme.theme_state==='ACTIVE').length,quarantined=local.filter(theme=>theme.theme_state==='QUARANTINED').length;$('#localThemeMetrics').innerHTML=metric(AXM.REG.themes.length,'protected themes')+metric(active,'active local themes')+metric(quarantined,'quarantined themes')+metric(local.length,'stored local themes');
    const grid=$('#localThemeGrid');grid.innerHTML='';if(!local.length){grid.innerHTML='<article class="panel"><h3>No local themes yet</h3><p class="muted">Derive one from a protected theme. Saving, approval, and activation are separate explicit steps.</p></article>';return}
    local.forEach(theme=>{const report=AXM.themeValidation(theme),valid=!report.summary.fail,card=document.createElement('article');card.className='mold-card';card.innerHTML=`<div class="theme-registry-preview"></div><div class="mold-body"><div class="panel-head"><code>${AXM.escapeHTML(theme.id)}</code>${statusPill(theme.approval_state)}</div><h3>${AXM.escapeHTML(theme.name)}</h3><p>${AXM.escapeHTML(theme.material_language)}</p><div class="tag-row"><span class="tag">${AXM.escapeHTML(theme.theme_state)}</span><span class="tag">${AXM.escapeHTML(theme.public_scope||'private')}</span><span class="tag">${AXM.escapeHTML(report.status)}</span></div><div class="card-actions wrap"><button class="quiet-button" data-inspect type="button">Inspect</button><button class="quiet-button" data-validate type="button">Validate</button><button class="quiet-button" data-export type="button">Export</button>${theme.approval_state!=='APPROVED'&&valid?'<button class="secondary-button" data-approve type="button">Approve</button>':''}${theme.approval_state==='APPROVED'&&theme.theme_state!=='ACTIVE'&&valid?'<button class="primary-button" data-activate type="button">Activate</button>':''}${theme.theme_state==='ACTIVE'&&valid?'<button class="primary-button" data-use type="button">Use</button><button class="secondary-button" data-deprecate type="button">Deprecate</button>':''}${theme.theme_state!=='ARCHIVED'?'<button class="quiet-button" data-archive type="button">Archive</button>':''}</div></div>`;renderThemeSwatches($('.theme-registry-preview',card),theme,report);$('[data-inspect]',card).onclick=()=>AXM.openJSON(theme.name,theme);$('[data-validate]',card).onclick=()=>AXM.openJSON(`${theme.name} validation`,AXM.themeValidation(theme));$('[data-export]',card).onclick=()=>{try{AXM.exportThemePackage(theme);AXM.toast('Theme package exported.')}catch(err){AXM.toast(err.message)}};$('[data-approve]',card)?.addEventListener('click',()=>{try{AXM.approveTheme(theme.id);renderThemes();AXM.toast('Theme approved explicitly; activation remains separate.')}catch(err){AXM.toast(err.message)}});$('[data-activate]',card)?.addEventListener('click',()=>{try{AXM.activateTheme(theme.id);renderThemes();populateFilters();renderEditor();AXM.toast('Theme activated explicitly.')}catch(err){AXM.toast(`Activation blocked: ${err.message}`)}});$('[data-use]',card)?.addEventListener('click',()=>{const mold=AXM.getMold();if(!AXM.themeCompatibleWithMold(theme,mold))AXM.setMold('axm.mold.universal-visual-card');AXM.state.variant.theme=theme.id;renderEditor();go('editor')});$('[data-deprecate]',card)?.addEventListener('click',()=>{try{AXM.deprecateTheme(theme.id);renderThemes();renderEditor();AXM.toast('Theme deprecated; record preserved.')}catch(err){AXM.toast(err.message)}});$('[data-archive]',card)?.addEventListener('click',()=>{try{AXM.archiveTheme(theme.id);renderThemes();renderEditor();AXM.toast('Theme archived; no record deleted.')}catch(err){AXM.toast(err.message)}});grid.appendChild(card)});
  }

  function makeSelect(label,key,values,current,onChange){const wrap=document.createElement('label');wrap.textContent=label;const select=document.createElement('select');select.dataset.key=key;select.innerHTML=values.map(v=>`<option value="${AXM.escapeHTML(v)}" ${v===current?'selected':''}>${AXM.escapeHTML(v)}</option>`).join('');select.addEventListener('change',()=>onChange(select.value));wrap.appendChild(select);return wrap}
  function makeSlider(label,key,spec,value,onChange){const labelEl=document.createElement('label');const row=document.createElement('div');row.className='control-row';const span=document.createElement('span');span.textContent=label;const output=document.createElement('output');output.textContent=Number(value).toFixed(2);row.append(span,output);const input=document.createElement('input');input.type='range';input.min=spec.minimum??0;input.max=spec.maximum??1;input.step=spec.step??.01;input.value=value;input.dataset.key=key;input.addEventListener('input',()=>{output.textContent=Number(input.value).toFixed(2);onChange(Number(input.value))});labelEl.append(row,input);return labelEl}
  function makeText(label,key,spec,value,onChange){const wrap=document.createElement('label');wrap.textContent=`${label} · ${String(value??'').length}/${spec.maximum_characters||'∞'}`;const input=key==='message'?document.createElement('textarea'):document.createElement('input');if(input.tagName==='TEXTAREA')input.rows=5;else input.type='text';input.value=value??'';input.maxLength=spec.maximum_characters||5000;input.dataset.key=key;input.addEventListener('input',()=>{onChange(AXM.sanitizeText(input.value,spec.maximum_characters||5000));wrap.firstChild.textContent=`${label} · ${input.value.length}/${spec.maximum_characters||'∞'}`});wrap.appendChild(input);return wrap}
  function buildControls(container,mold,controls,variant,onUpdate,{includeVariants=true}={}){
    container.innerHTML='';
    if(includeVariants){for(const axis of Object.keys(mold.variants||{})){const values=AXM.variantValues(mold,axis);container.appendChild(makeSelect(axis[0].toUpperCase()+axis.slice(1),axis,values,variant[axis],value=>{variant[axis]=value;if(axis==='performance'&&value!=='low')AXM.state.lowPower=false;onUpdate()}));}}
    for(const [key,spec] of Object.entries(mold.inputs||{})){
      const label=key.replaceAll('_',' ');
      if(spec.type==='number')container.appendChild(makeSlider(label,key,spec,controls[key],value=>{controls[key]=value;onUpdate()}));
      else if(spec.type==='text')container.appendChild(makeText(label,key,spec,controls[key],value=>{controls[key]=value;onUpdate()}));
      else if(spec.type==='enum')container.appendChild(makeSelect(label,key,spec.values||[],controls[key],value=>{controls[key]=value;onUpdate()}));
      else if(spec.type==='boolean'){const wrap=document.createElement('label');wrap.className='toggle-control';const input=document.createElement('input');input.type='checkbox';input.checked=Boolean(controls[key]);input.addEventListener('change',()=>{controls[key]=input.checked;onUpdate()});wrap.append(input,document.createTextNode(label));container.appendChild(wrap)}
      else if(spec.type==='slot'){
        const wrap=document.createElement('label');wrap.textContent='Local media slot';const input=document.createElement('input');input.type='file';input.accept='image/*';input.addEventListener('change',()=>{const file=input.files?.[0];if(!file){delete controls.mediaData;onUpdate();return}if(file.size>8_000_000){AXM.toast('Media rejected: 8 MB local preview limit.');input.value='';return}const reader=new FileReader();reader.onload=()=>{controls.mediaData=String(reader.result);onUpdate()};reader.readAsDataURL(file)});wrap.appendChild(input);container.appendChild(wrap);
      }
    }
  }
  function renderEditor(){
    const mold=AXM.getMold();$('#editorTitle').textContent=mold.name;$('#editorStatus').textContent=mold.approval_state;$('#editorStatus').className=`status-pill ${statusClass(mold.approval_state)}`;
    const usable=AXM.getAllMolds(),molds=usable.some(item=>item.id===mold.id)?usable:[mold,...usable],sel=$('#moldSelect');sel.innerHTML=molds.map(m=>`<option value="${m.id}" ${m.id===mold.id?'selected':''}>${AXM.escapeHTML(m.name)}${m.source_kind==='extension'?' · extension':''}</option>`).join('');
    buildControls($('#dynamicControls'),mold,AXM.state.controls,AXM.state.variant,renderMainPreview);renderMainPreview();
  }
  function renderMainPreview(){const mold=AXM.getMold();const variant={...AXM.state.variant};if(AXM.state.lowPower)variant.performance='low';if(AXM.state.reducedMotion)variant.motion='still';$('#previewDescriptor').textContent=`${variant.theme} · ${variant.format} · ${variant.performance} · ${variant.motion}`;R.renderMoldToElement($('#mainPreview'),mold,AXM.state.controls,variant,{animate:true,key:'main'});}

  function renderSkinLab(){
    const mold=AXM.getMold('axm.mold.living-skin-laboratory');buildControls($('#skinControls'),mold,skinLab.controls,skinLab.variant,()=>{R.startAnimation('skin-lab',R.drawSkin,$('#skinCanvas'),skinLab.controls,{...skinLab.variant,motion:AXM.state.reducedMotion?'still':skinLab.variant.motion});$('#skinReadout').textContent=`${skinLab.variant.theme} · ${skinLab.variant.performance} · age ${skinLab.controls.age.toFixed(2)} · damage ${skinLab.controls.damage.toFixed(2)} · wetness ${skinLab.controls.wetness.toFixed(2)} · inherited semantic skin manifest ready`;});R.startAnimation('skin-lab',R.drawSkin,$('#skinCanvas'),skinLab.controls,{...skinLab.variant,motion:AXM.state.reducedMotion?'still':skinLab.variant.motion});$('#skinReadout').textContent='Semantic skin controls are shared with the exportable skin manifest and adapter maps.';
  }
  function renderLightLab(){
    const controls={...portalLab.controls},specs={key:{minimum:0,maximum:1},fill:{minimum:0,maximum:1},rim:{minimum:0,maximum:1},portal:{minimum:0,maximum:1},temperature:{minimum:-1,maximum:1},depth:{minimum:0,maximum:1}},values={key:.68,fill:.26,rim:.62,portal:.72,temperature:-.2,depth:.66},box=$('#lightControls');box.innerHTML='';box.appendChild(makeSelect('Theme','theme',AXM.getAllThemes().map(t=>t.id),portalLab.variant.theme,value=>{portalLab.variant.theme=value;draw()}));Object.entries(specs).forEach(([key,spec])=>box.appendChild(makeSlider(key,key,spec,values[key],value=>{values[key]=value;draw()})));
    function draw(){controls.portal_energy=values.portal;controls.depth=values.depth;controls.light_contrast=values.key;controls.fog=Math.max(.08,values.fill*.55);controls.particles=Math.max(.05,values.rim*.5);R.drawPortal($('#lightCanvas'),controls,{...portalLab.variant,motion:'still',performance:'standard'},0)}draw();
  }
  function renderEffectLab(){
    const box=$('#effectControls');box.innerHTML='';const specs=Object.fromEntries(Object.keys(effectState).map(k=>[k,{minimum:0,maximum:1}]));Object.entries(specs).forEach(([k,s])=>box.appendChild(makeSlider(k.replaceAll('_',' '),k,s,effectState[k],v=>{effectState[k]=v;draw()})));box.prepend(makeSelect('Performance','performance',['low','standard','ultra'],portalLab.variant.performance,v=>{portalLab.variant.performance=v;draw()}));function draw(){const c={...portalLab.controls,portal_energy:.45+effectState.energy_veins*.35,fog:effectState.fog,particles:effectState.particles,light_contrast:.4+effectState.edge_glow*.5};R.drawPortal($('#effectCanvas'),c,{...portalLab.variant,motion:'still'},0);const active=Object.values(effectState).filter(v=>v>.18).length,b=AXM.performanceBudget(portalLab.variant.performance).effects;$('#effectBudget').textContent=`${active}/${b} effect budget`;$('#effectReadout').textContent=active>b?`FAIL — active effect estimate ${active} exceeds ${portalLab.variant.performance} budget ${b}.`:`PASS — active effect estimate ${active} stays inside ${portalLab.variant.performance} budget ${b}.`; }draw();
  }
  function renderVariants(){
    const mold=AXM.getMold(),box=$('#variantControls');box.innerHTML='<h3>Variant axes</h3>';const local={...AXM.state.variant};Object.keys(mold.variants||{}).forEach(axis=>{const values=AXM.variantValues(mold,axis);box.appendChild(makeSelect(axis,axis,values,local[axis],value=>{local[axis]=value;update()}))});
    function update(){const packet={schema:'axm.variant-selection/0.5',mold:mold.id,axes:local,sparse:true,theme:AXM.getTheme(local.theme),composition:R.describeComposition(mold),combination_count:Object.keys(mold.variants||{}).reduce((total,axis)=>total*Math.max(1,AXM.variantValues(mold,axis).length),1),parent_unchanged:true};$('#variantPacket').textContent=JSON.stringify(packet,null,2)}
    update();$('#applyVariantButton').onclick=()=>{Object.assign(AXM.state.variant,local);renderEditor();go('editor')};
  }

  function proofItem(mold,item){const article=document.createElement('article');article.className='proof-item';const canvasWrap=document.createElement('div');canvasWrap.className='proof-canvas';R.renderThumbnail(canvasWrap,mold,item.controls,{...item.variant,motion:'still',performance:item.variant.performance||'low'});const val=V.validate(mold,item.controls,item.variant,{reducedMotion:item.label==='Reduced motion',extraRegistry:AXM.getExtensions(true).filter(extension=>extension.id!==mold.id)});article.appendChild(canvasWrap);article.insertAdjacentHTML('beforeend',`<footer><b>${AXM.escapeHTML(item.label)}</b><span>${val.status}</span></footer>`);return article}
  function renderPreviewLab(){
    const mold=AXM.getMold(),grid=$('#previewLabGrid');grid.innerHTML='';const formats=mold.variants.format||['landscape'],tiers=mold.variants.performance||['standard'],cases=[];formats.slice(0,5).forEach(format=>tiers.slice(0,3).forEach(performance=>cases.push({label:`${format} · ${performance}`,controls:{...AXM.state.controls},variant:{...AXM.state.variant,format,performance,motion:'still'}})));cases.forEach(item=>grid.appendChild(proofItem(mold,item)));
    const select=$('#snapshotCompareSelect'),selected=select.value,snaps=AXM.getSnapshots();select.innerHTML='<option value="">Choose a snapshot</option>'+snaps.map(s=>`<option value="${s.id}">${AXM.escapeHTML(s.reason)} · ${new Date(s.created_at).toLocaleString()}</option>`).join('');if(snaps.some(s=>s.id===selected))select.value=selected;$('#comparisonSummary').textContent=snaps.length?`${snaps.length} immutable local snapshot${snaps.length===1?'':'s'} available. Comparison changes nothing.`:'Create a snapshot to enable visual and structural comparison.';
  }
  function renderSnapshotComparison(){
    const id=$('#snapshotCompareSelect').value,grid=$('#comparisonGrid');grid.innerHTML='';if(!id){AXM.toast('Choose a snapshot first.');return}
    try{const comparison=AXM.compareWithSnapshot(id),snap=comparison.snapshot,snapMold=AXM.findMold(snap.mold_id)||AXM.getMold(),currentMold=AXM.getMold(),snapControls={...AXM.defaultControls(snapMold),...(snap.controls||{})},snapVariant={...AXM.defaultVariant(snapMold),...(snap.variant||{})};grid.appendChild(proofItem(snapMold,{label:`Snapshot · ${snap.reason}`,controls:snapControls,variant:snapVariant}));grid.appendChild(proofItem(currentMold,{label:'Current state',controls:{...AXM.state.controls},variant:{...AXM.state.variant,motion:'still'}}));const rows=comparison.changes.slice(0,80).map(change=>`<div class="diff-row"><b>${AXM.escapeHTML(change.path)}</b><span>${AXM.escapeHTML(JSON.stringify(change.before))}</span><span>${AXM.escapeHTML(JSON.stringify(change.after))}</span></div>`).join('');grid.insertAdjacentHTML('beforeend',`<div class="comparison-report"><div class="panel-head"><h3>Structural difference report</h3><span class="count-label">${comparison.changes.length} changes</span></div><div class="diff-list">${rows||'<div class="muted">No structural differences detected.</div>'}</div></div>`);$('#comparisonSummary').textContent=`Compared ${snap.fingerprint||'legacy snapshot'} with ${comparison.current.fingerprint}. No state was changed.`;AXM.log(`Compared current state with snapshot ${id}`,'PASS')}catch(err){AXM.toast(`Comparison failed: ${err.message}`);AXM.log(`Comparison failure: ${err.message}`,'FAIL')}
  }

  function renderValidation(){
    const mold=AXM.getMold();const report=V.validate(mold,AXM.state.controls,AXM.state.variant,{reducedMotion:AXM.state.reducedMotion,extraRegistry:AXM.getExtensions(true).filter(extension=>extension.id!==mold.id)});$('#validationSummary').innerHTML=metric(report.summary.pass,'PASS')+metric(report.summary.warn,'WARN')+metric(report.summary.fail,'FAIL');$('#validationResults').innerHTML=report.checks.map(c=>`<div class="validation-row ${c.state.toLowerCase()}"><span class="check-state">${c.state}</span><div><b>${AXM.escapeHTML(c.label)}</b><p>${AXM.escapeHTML(c.evidence)}</p></div><span class="confidence">${Math.round(c.confidence*100)}%</span></div>`).join('');return report;
  }
  function generateProof(){const mold=AXM.getMold();const grid=$('#proofGrid');grid.innerHTML='';X.proofCases(mold,AXM.state.controls,AXM.state.variant).forEach(item=>grid.appendChild(proofItem(mold,item)));renderValidation();AXM.log(`Generated proof sheet for ${mold.name}`,'PASS');AXM.toast('Proof sheet generated locally.');}

  function renderPresets(){
    const presets=AXM.getAllPresets(),grid=$('#presetGrid');grid.innerHTML='';presets.forEach(p=>{
      const card=document.createElement('article');card.className='mold-card';let resolved=null,error=null;
      try{resolved=AXM.resolvePreset(p)}catch(err){error=err}
      card.innerHTML=`<div class="mold-thumb"></div><div class="mold-body"><div class="panel-head"><code>${AXM.escapeHTML(p.id)}</code>${statusPill(p.approval_state)}</div><h3>${AXM.escapeHTML(p.name)}</h3><p>Parent: ${AXM.escapeHTML(p.parent)}</p><div class="tag-row"><span class="tag">${Object.keys(p.sparse_overrides||{}).length} overrides</span><span class="tag">${AXM.escapeHTML(p.public_scope||'private')}</span>${error?'<span class="tag">BLOCKED</span>':''}</div><div class="card-actions">${resolved?'<button class="primary-button" data-use>Use</button>':'<button class="quiet-button" type="button" disabled>Parent inactive</button>'}<button class="quiet-button" data-more>Actions</button></div></div>`;
      if(resolved){R.renderThumbnail($('.mold-thumb',card),resolved.mold,resolved.controls,{...resolved.variant,motion:'still',performance:'low'});$('[data-use]',card).onclick=()=>{try{AXM.applyPreset(p);go('editor')}catch(err){AXM.toast(err.message)}}}
      else $('.mold-thumb',card).innerHTML=`<div class="readout">Preset preserved but unavailable.<br>${AXM.escapeHTML(error?.message||'Parent cannot be resolved.')}</div>`;
      $('[data-more]',card).onclick=()=>presetActions(p);grid.appendChild(card)
    });
  }
  async function presetActions(p){
    const local=!AXM.REG.presets.some(x=>x.id===p.id),choices=['view','export','duplicate',...(local?['approve','deprecate']:[])];
    const action=await window.AXMDialog.choose({title:'Preset actions',message:`Choose one explicit action for “${p.name}”.`,label:'Action',choices,defaultValue:'view',confirmLabel:'Continue'});if(!action)return;
    const a=action.trim().toLowerCase();if(a==='view')AXM.openJSON(p.name,p);else if(a==='export')AXM.downloadBlob(`${AXM.slugify(p.name)}.axmpreset.json`,JSON.stringify(p,null,2)+'\n','application/json');else if(a==='duplicate'){AXM.duplicatePreset(p);renderPresets()}else if(local&&['approve','deprecate'].includes(a)){AXM.updateStoredPreset(p.id,{approval_state:a==='approve'?'APPROVED':'DEPRECATED'});renderPresets()}}


  function renderFoundrySteps(){const steps=['Describe','Protect','Reuse','Vary','Validate','Approve','Promote'];$('#foundrySteps').innerHTML=steps.map((x,i)=>`<div class="foundry-step"><b>${i+1}</b>${x}</div>`).join('');const parent=$('#candidateParent'),selected=parent.value,molds=AXM.getAllMolds();parent.innerHTML=molds.map(m=>`<option value="${m.id}">${AXM.escapeHTML(m.name)}${m.source_kind==='extension'?' · extension':''}</option>`).join('');if(molds.some(m=>m.id===selected))parent.value=selected;}
  function buildCandidate(){
    const parent=AXM.findMold($('#candidateParent').value)||AXM.getMold(),name=AXM.sanitizeText($('#candidateName').value,100)||'Derived Visual Mold',purpose=AXM.sanitizeText($('#candidatePurpose').value,160),changeSummary=AXM.sanitizeText($('#candidateChangeSummary').value,800),tags=$('#candidateTags').value.split(',').map(x=>AXM.sanitizeText(x.trim(),32)).filter(Boolean),candidate=AXM.clone(parent);candidate.schema='axm.visual-mold/0.5';candidate.id=`axm.candidate.${AXM.slugify(name)}.${Date.now().toString(36)}`;candidate.name=name;candidate.version='0.5.0';candidate.source_kind='candidate';candidate.source_manifest='local Foundry candidate';candidate.inherited_from=parent.id;candidate.lineage={parent:parent.id,derived_from:[`${parent.id}@${parent.version}`],change_policy:'explicit-approval'};candidate.approval_state='EXPERIMENTAL';candidate.public_scope=$('#candidatePublicScope').value||'private';candidate.intent={purpose,change_summary:changeSummary,tags};candidate.field_policy={protected:$('#protectedFields').value.split(/\n/).map(x=>x.trim()).filter(Boolean),constrained:$('#constrainedFields').value.split(/\n/).map(x=>x.trim()).filter(Boolean),free:$('#freeFields').value.split(/\n/).map(x=>x.trim()).filter(Boolean)};candidate.sparse_overrides=AXM.buildSparseOverrides(parent,AXM.state.moldId===parent.id?AXM.state.controls:AXM.defaultControls(parent),AXM.state.variant);candidate.provenance={...parent.provenance,consent:'explicit local Foundry build',transformation_history:[...(parent.provenance.transformation_history||[]),'guided Foundry v0.9.1 derivation'],source:parent.id};candidate.preview=parent.preview;const protectedAnalysis=V.protectedChangeAnalysis(parent,candidate);candidate.protected_change_request=protectedAnalysis.actual.filter(path=>candidate.field_policy.protected.includes(path));currentCandidate=candidate;$('#candidateManifest').value=JSON.stringify(candidate,null,2);candidateReport([{state:'PASS',label:'Candidate built',evidence:`Parent preserved. ${Object.keys(candidate.sparse_overrides||{}).length} sparse override group(s), explicit field policy, purpose, and lineage were recorded.`,confidence:1}]);AXM.log(`Built candidate ${candidate.id}`,'PASS');
  }
  function candidateReport(checks){$('#candidateReport').innerHTML=checks.map(c=>`<div class="validation-row ${c.state.toLowerCase()}"><span class="check-state">${c.state}</span><div><b>${AXM.escapeHTML(c.label)}</b><p>${AXM.escapeHTML(c.evidence)}</p></div></div>`).join('')}
  function validateCandidate(){try{const report=V.candidateFromText($('#candidateManifest').value);candidateReport(report.checks);currentCandidate=AXM.safeParseJSON($('#candidateManifest').value);AXM.toast(`Candidate validation: ${report.status}`);return report}catch(err){candidateReport([{state:'FAIL',label:'Candidate JSON',evidence:err.message,confidence:1}]);return null}}
  function saveCandidate(){const report=validateCandidate();if(!report||report.summary.fail){AXM.toast('Candidate not saved: validation has FAIL results.');return}currentCandidate.approval_state='EXPERIMENTAL';AXM.saveCandidate(currentCandidate);$('#candidateManifest').value=JSON.stringify(currentCandidate,null,2);AXM.toast('Candidate saved as EXPERIMENTAL.');renderLineage()}
  function approveCandidate(){const report=validateCandidate();if(!report||report.summary.fail){AXM.toast('Approval blocked: repair FAIL results first.');return}currentCandidate.approval_state='APPROVED';currentCandidate.approved_at=new Date().toISOString();currentCandidate.approval_method='explicit-human-button';AXM.saveCandidate(currentCandidate,{update:true});$('#candidateManifest').value=JSON.stringify(currentCandidate,null,2);candidateReport([{state:'PASS',label:'Manual approval recorded',evidence:'Approval state changed only after explicit button action.',confidence:1},...report.checks]);AXM.toast('Candidate marked APPROVED locally. Not promoted to external canon.')}
  function promoteCurrentCandidate(){
    try{
      const parsed=AXM.safeParseJSON($('#candidateManifest').value),stored=AXM.getCandidates().find(item=>item.id===parsed.id)||parsed,extension=AXM.promoteCandidate(stored);
      candidateReport([{state:'PASS',label:'Promoted to local extension registry',evidence:`${extension.name} entered QUARANTINED state under a new local extension ID. Release-gate review and activation remain separate.`,confidence:1}]);
      renderExtensions();renderAtlas();renderEditor();renderLineage();renderStatus();AXM.toast('Approved candidate promoted into extension quarantine; run the release gate before activation.');
    }catch(err){candidateReport([{state:'FAIL',label:'Extension promotion blocked',evidence:err.message,confidence:1}]);AXM.toast(`Promotion blocked: ${err.message}`)}
  }

  function renderExtensions(){
    const list=AXM.getExtensions(true),active=list.filter(item=>item.extension_state==='ACTIVE').length,quarantined=list.filter(item=>item.extension_state==='QUARANTINED').length,inactive=list.filter(item=>['DEPRECATED','ARCHIVED'].includes(item.extension_state)).length,core=AXM.coreIntegrityReport();
    $('#extensionMetrics').innerHTML=metric(active,'active extensions')+metric(quarantined,'quarantined / test-hold')+metric(inactive,'deprecated or archived')+metric(core.status,'protected core integrity');
    const grid=$('#extensionGrid');grid.innerHTML='';
    if(!list.length){grid.innerHTML='<article class="panel"><h3>No local extensions yet</h3><p class="muted">Approve a Foundry candidate and promote it, or import an extension package. Every extension stays quarantined until approval, release-gate proof, and explicit activation are complete.</p></article>';return}
    list.forEach(extension=>{
      const card=document.createElement('article');card.className='mold-card';card.dataset.sourceKind='extension';const usable=extension.extension_state==='ACTIVE'&&extension.approval_state==='APPROVED',state=AXM.escapeHTML(extension.extension_state||'UNKNOWN'),origin=extension.origin_candidate_id||extension.imported_from_id||'local',gate=extension.release_gate?.status||'NOT RUN';
      card.innerHTML=`<div class="mold-thumb"></div><div class="mold-body"><div class="panel-head"><code>${AXM.escapeHTML(extension.id)}</code>${statusPill(extension.approval_state)}</div><h3>${AXM.escapeHTML(extension.name)}</h3><p>${AXM.escapeHTML(extension.description||'Local visual mold extension')}</p><div class="tag-row"><span class="tag">${state}</span><span class="tag">gate: ${AXM.escapeHTML(gate)}</span><span class="tag">${AXM.escapeHTML(extension.category||'extension')}</span><span class="tag">origin: ${AXM.escapeHTML(origin)}</span></div><div class="card-actions wrap"><button class="quiet-button" data-inspect type="button">Inspect</button><button class="quiet-button" data-validate type="button">Validate</button><button class="quiet-button" data-release type="button">Release gate</button><button class="quiet-button" data-export type="button">Export</button>${extension.approval_state!=='APPROVED'?'<button class="secondary-button" data-approve type="button">Approve</button>':''}${usable?'<button class="primary-button" data-use type="button">Use</button><button class="secondary-button" data-deprecate type="button">Deprecate</button>':extension.approval_state==='APPROVED'?'<button class="primary-button" data-activate type="button">Activate</button>':''}${extension.extension_state!=='ARCHIVED'?'<button class="quiet-button" data-archive type="button">Archive</button>':''}</div></div>`;
      try{R.renderThumbnail($('.mold-thumb',card),extension,AXM.defaultControls(extension),{...AXM.defaultVariant(extension),motion:'still',performance:'low'})}catch(err){$('.mold-thumb',card).innerHTML=`<div class="readout">Preview unavailable until the manifest is repaired.<br>${AXM.escapeHTML(err.message)}</div>`}
      $('[data-inspect]',card).onclick=()=>AXM.openJSON(extension.name,extension);
      $('[data-validate]',card).onclick=()=>AXM.openJSON(`${extension.name} validation`,AXM.extensionValidation(extension));
      $('[data-release]',card).onclick=()=>{try{const report=AXM.prepareExtensionRelease(extension.id);AXM.openJSON(`${extension.name} release gate`,report);renderExtensions();AXM.toast(`Release gate: ${report.status}`)}catch(err){AXM.toast(`Release gate failed: ${err.message}`)}};
      $('[data-export]',card).onclick=()=>{try{AXM.exportExtensionPackage(extension);AXM.toast('Extension package exported.')}catch(err){AXM.toast(err.message)}};
      $('[data-approve]',card)?.addEventListener('click',()=>{try{AXM.approveExtension(extension.id);renderExtensions();AXM.toast('Extension approved explicitly; release and activation remain separate.')}catch(err){AXM.toast(`Approval blocked: ${err.message}`)}});
      $('[data-use]',card)?.addEventListener('click',()=>{AXM.setMold(extension.id);go('editor')});
      $('[data-activate]',card)?.addEventListener('click',async()=>{
        try{
          const gate=AXM.prepareExtensionRelease(extension.id);let acknowledge=false;
          if(gate.summary.warn){
            const approved=await window.AXMDialog.confirm({title:'Activate extension with warnings',eyebrow:'Explicit warning acknowledgement',message:`The release gate has ${gate.summary.warn} warning(s) and no failures. Activation records your acknowledgement without changing the protected core.`,confirmLabel:'Activate and acknowledge',danger:true});
            if(!approved)return;acknowledge=true;
          }
          AXM.activateExtension(extension.id,acknowledge);renderExtensions();renderAtlas();renderEditor();renderLineage();renderStatus();AXM.toast('Extension activated after release-gate proof.');
        }catch(err){AXM.toast(`Activation blocked: ${err.message}`)}
      });
      $('[data-deprecate]',card)?.addEventListener('click',()=>{try{AXM.deprecateExtension(extension.id);if(AXM.state.moldId===extension.id)AXM.setMold('axm.mold.universal-visual-card');renderExtensions();renderAtlas();renderEditor();renderLineage();renderStatus();AXM.toast('Extension deprecated; record preserved.')}catch(err){AXM.toast(err.message)}});
      $('[data-archive]',card)?.addEventListener('click',()=>{try{AXM.archiveExtension(extension.id);if(AXM.state.moldId===extension.id)AXM.setMold('axm.mold.universal-visual-card');renderExtensions();renderAtlas();renderEditor();renderLineage();renderStatus();AXM.toast('Extension archived; no record was deleted.')}catch(err){AXM.toast(err.message)}});
      grid.appendChild(card);
    });
  }

  function renderExports(){
    const mold=AXM.getMold();$('#exportMoldName').textContent=`${mold.name} · ${mold.source_kind}`;const grid=$('#exportGrid');grid.innerHTML='';X.exportersFor(mold).forEach(([id,name,desc])=>{const card=document.createElement('article');card.className='export-card';card.innerHTML=`<p class="eyebrow">WORKING LOCAL EXPORT</p><h3>${AXM.escapeHTML(name)}</h3><p>${AXM.escapeHTML(desc)}</p><button class="primary-button" type="button">Export ${AXM.escapeHTML(name)}</button>`;$('button',card).onclick=()=>{try{X.run(id,mold,AXM.state.controls,{...AXM.state.variant,motion:AXM.state.reducedMotion?'still':AXM.state.variant.motion});AXM.toast(`${name} export created.`)}catch(err){AXM.toast(`Export failed: ${err.message}`);AXM.log(`Export failure ${id}: ${err.message}`,'FAIL')}};grid.appendChild(card)});
  }
  function renderLineage(){
    const map=$('#lineageMap');map.innerHTML='';const presets=AXM.getAllPresets(),candidates=AXM.getCandidates(),molds=AXM.getAllMolds({includeInactive:true}),ids=new Set(molds.map(m=>m.id)),roots=molds.filter(m=>!m.lineage?.parent||!ids.has(m.lineage.parent)),visited=new Set();
    function addMold(mold,depth=0){
      if(visited.has(mold.id)){map.insertAdjacentHTML('beforeend',`<div class="lineage-node child" style="margin-left:${Math.min(depth,8)*18}px"><b>Cycle blocked</b><span>${AXM.escapeHTML(mold.id)}</span></div>`);return}
      visited.add(mold.id);const kind=mold.source_kind==='root'?'source-root':mold.source_kind==='extension'?'source-extension':'source-derived',extensionState=mold.extension_state?` · ${mold.extension_state}`:'';
      map.insertAdjacentHTML('beforeend',`<div class="lineage-node ${kind}" style="margin-left:${Math.min(depth,8)*18}px"><b>${AXM.escapeHTML(mold.name)}</b><span>${AXM.escapeHTML(mold.id)} · ${AXM.escapeHTML(mold.source_kind)} · ${AXM.escapeHTML(mold.approval_state)}${AXM.escapeHTML(extensionState)}</span></div>`);
      presets.filter(p=>p.parent===mold.id).forEach(p=>map.insertAdjacentHTML('beforeend',`<div class="lineage-node child" style="margin-left:${Math.min(depth+1,9)*18}px"><b>${AXM.escapeHTML(p.name)}</b><span>${AXM.escapeHTML(p.id)} · sparse preset · ${AXM.escapeHTML(p.approval_state)}</span></div>`));
      candidates.filter(c=>(c.lineage?.parent||c.parent)===mold.id).forEach(c=>map.insertAdjacentHTML('beforeend',`<div class="lineage-node child" style="margin-left:${Math.min(depth+1,9)*18}px"><b>${AXM.escapeHTML(c.name)}</b><span>${AXM.escapeHTML(c.id)} · candidate · ${AXM.escapeHTML(c.approval_state)}</span></div>`));
      molds.filter(child=>child.lineage?.parent===mold.id).forEach(child=>addMold(child,depth+1));
    }
    roots.forEach(root=>addMold(root));molds.filter(m=>!visited.has(m.id)).forEach(m=>addMold(m));
    const snaps=AXM.getSnapshots();$('#snapshotList').innerHTML=snaps.length?snaps.map(s=>`<div class="snapshot"><div><b>${AXM.escapeHTML(s.reason)}</b><span>${new Date(s.created_at).toLocaleString()} · ${AXM.escapeHTML(s.mold_id)} · ${AXM.escapeHTML(s.fingerprint||'legacy')}</span></div><div class="button-row"><button class="quiet-button" data-compare="${s.id}" type="button">Compare</button><button class="quiet-button" data-restore="${s.id}" type="button">Restore</button></div></div>`).join(''):'<p class="muted">No local snapshots yet.</p>';$$('[data-restore]').forEach(button=>button.onclick=()=>{try{AXM.restoreSnapshot(button.dataset.restore);renderLineage();AXM.toast('Snapshot restored; a pre-rollback snapshot was created.')}catch(err){AXM.toast(err.message)}});$$('[data-compare]').forEach(button=>button.onclick=()=>{go('preview');$('#snapshotCompareSelect').value=button.dataset.compare;renderSnapshotComparison()});
  }
  function renderStatus(){
    const localPresets=AXM.storageRead(AXM.STORAGE.presets,[]).length,candidates=AXM.getCandidates().length,snaps=AXM.getSnapshots().length,roots=AXM.REG.molds.filter(m=>m.source_kind==='root').length,derived=AXM.REG.molds.length-roots,extensions=AXM.getExtensions(true),activeExtensions=extensions.filter(item=>item.extension_state==='ACTIVE').length,quarantined=extensions.filter(item=>item.extension_state==='QUARANTINED').length,localThemes=AXM.getLocalThemes(true),activeThemes=localThemes.filter(item=>item.theme_state==='ACTIVE').length,quarantinedThemes=localThemes.filter(item=>item.theme_state==='QUARANTINED').length,projects=AXM.getProjects?.(true)||[],batches=AXM.getBatches?.(true)||[],core=AXM.coreIntegrityReport(),health=AXM.healthReport();
    $('#statusMetrics').innerHTML=metric('LOCAL','core runtime')+metric(core.status,'protected core integrity')+metric(health.status,'workspace health')+metric(`${roots}+${derived}`,'protected core molds')+metric(activeThemes,'active local themes')+metric(activeExtensions,'active extensions')+metric(projects.length,'visual projects')+metric(batches.length,'data batches')+metric(quarantined+quarantinedThemes,'quarantined records')+metric(snaps,'rollback snapshots');
    $('#runtimeStatus').innerHTML=`<div><b>Browser Studio v0.9.1</b><span>BUILT · direct file and localhost modes use separate browser-storage origins</span></div><div><b>Protected visual library</b><span>${core.status} · ${core.core_count} startup-verified molds across marketing, software UI, game UI, materials, and scenes</span></div><div><b>Declarative Theme Foundry</b><span>BUILT · ${activeThemes} active, ${quarantinedThemes} quarantined, ${localThemes.length} stored local themes</span></div><div><b>Local extension registry</b><span>BUILT · ${activeExtensions} active, ${quarantined} quarantined, ${extensions.length} stored total</span></div><div><b>Workspace health</b><span>${health.status} · ${health.summary.pass} pass, ${health.summary.warn} warn, ${health.summary.fail} fail</span></div><div><b>Sparse inheritance</b><span>BUILT · ${derived} derived package molds plus separately stored local extensions</span></div><div><b>Validation</b><span>BUILT · 23 evidence-based mold checks, theme validation, extension release gates, and proof matrices</span></div><div><b>Project Composer</b><span>BUILT · ${projects.length} stored visual projects with ordering, revisions, approval, and static HTML export</span></div><div><b>Data Batch Builder</b><span>BUILT · ${batches.length} stored CSV/JSON batches with semantic mapping and project materialization</span></div><div><b>Portable packets</b><span>BUILT · integrity fingerprints, dependency remapping, quarantine, projects, batches, and new local IDs</span></div><div><b>Recovery + Intake</b><span>BUILT · raw preservation, staged capsule restore, five-point rescue ring, transactional rollback, and intake-readiness evidence</span></div><div><b>Engine bridges</b><span>Scaffolds for Blender, Godot, ComfyUI, Unity, Unreal, and MaterialX; parity remains unclaimed</span></div><div><b>Foundry candidates</b><span>${candidates} local candidate${candidates===1?'':'s'} · approval, promotion, release, and activation remain separate explicit actions</span></div>`;
    $('#adapterStatus').innerHTML=Object.values(AXM.REG.adapters).map(a=>`<div><b>${AXM.escapeHTML(a.target)}</b><span>${a.status} · visual parity claim: no</span></div>`).join('');renderLog();
  }
  function renderLog(){const el=$('#sessionLog');if(!el)return;el.innerHTML=AXM.state.sessionLog.length?AXM.state.sessionLog.map(x=>`<div class="log-entry">${AXM.escapeHTML(x.time)} [${x.level}] ${AXM.escapeHTML(x.message)}</div>`).join(''):'<div class="log-entry">No session events yet.</div>'}

  function bindEvents(){
    ['atlasSearch','atlasCategory','atlasStatus','atlasTheme'].forEach(id=>$('#'+id).addEventListener(id==='atlasSearch'?'input':'change',renderAtlas));['organSearch','organCategory'].forEach(id=>$('#'+id).addEventListener(id==='organSearch'?'input':'change',renderOrgans));['tokenSearch','tokenCategory'].forEach(id=>$('#'+id).addEventListener(id==='tokenSearch'?'input':'change',renderTokens));
    $('#moldSelect').addEventListener('change',event=>{AXM.setMold(event.target.value);renderEditor()});$('#renderButton').onclick=renderMainPreview;$('#savePresetButton').onclick=async()=>{const name=await window.AXMDialog.askText({title:'Save local preset',message:'Name this sparse preset. Saving creates a rollback snapshot and does not change the parent mold.',label:'Preset name',defaultValue:`${AXM.getMold().name} — local preset`,required:true,confirmLabel:'Save preset'});if(name){AXM.saveCurrentPreset(name);AXM.toast('Preset saved locally with rollback snapshot.')}};$('#newPresetButton').onclick=$('#savePresetButton').onclick;
    $('#deriveButton').onclick=()=>{$('#candidateParent').value=AXM.state.moldId;$('#candidateName').value=`${AXM.getMold().name} child`;buildCandidate();go('foundry')};$('#fullscreenPreview').onclick=()=>setFocusedPreview(!$('#mainPreview').classList.contains('focused'));
    $('#runValidation').onclick=()=>{renderValidation();AXM.toast('Validation complete.')};$('#generateProof').onclick=generateProof;$('#refreshPreviewLab').onclick=renderPreviewLab;$('#compareSnapshotButton').onclick=renderSnapshotComparison;
    $('#importPresetButton').onclick=()=>$('#presetFileInput').click();$('#presetFileInput').addEventListener('change',event=>{const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{AXM.importPreset(String(reader.result));renderPresets();AXM.toast('Preset imported as EXPERIMENTAL.')}catch(err){AXM.toast(`Import rejected: ${err.message}`)}};reader.readAsText(file);event.target.value=''});
    $('#themeBase').addEventListener('change',event=>loadThemeForm(AXM.findTheme(event.target.value)));$('#themeBuildDraft').onclick=buildThemeDraftFromForm;$('#themeValidateDraft').onclick=()=>{try{const raw=$('#themeManifest').value.trim(),theme=raw?AXM.safeParseJSON(raw):(buildThemeDraftFromForm()?.theme);if(!theme)return;currentThemeDraft=theme;const report=AXM.themeValidation(theme);renderThemePreview(theme,report);renderThemeValidation(report);AXM.toast(`Theme validation: ${report.status}`)}catch(err){renderBlockedThemePreview($('#themePreview'));AXM.toast(`Theme validation failed: ${err.message}`)}};$('#themeSaveDraft').onclick=()=>{try{let theme;const raw=$('#themeManifest').value.trim();if(raw)theme=AXM.safeParseJSON(raw);else theme=buildThemeDraftFromForm()?.theme;if(!theme)return;const report=AXM.themeValidation(theme);renderThemeValidation(report);if(report.summary.fail){renderThemePreview(theme,report);AXM.toast('Theme not saved: repair validation failures first.');return}const saved=AXM.saveThemeDraft(theme);currentThemeDraft=null;renderThemes();populateFilters();renderStatus();AXM.toast(`${saved.name} saved into theme quarantine.`)}catch(err){renderBlockedThemePreview($('#themePreview'));AXM.toast(`Theme save blocked: ${err.message}`)}};$('#themeImportButton').onclick=()=>$('#themeFileInput').click();$('#themeFileInput').addEventListener('change',event=>{const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{AXM.importThemePackage(String(reader.result));renderThemes();renderStatus();AXM.toast('Theme imported into QUARANTINED state.')}catch(err){AXM.toast(`Theme import rejected: ${err.message}`)}};reader.readAsText(file);event.target.value=''});
    $('#buildCandidate').onclick=buildCandidate;$('#validateCandidate').onclick=validateCandidate;$('#saveCandidate').onclick=saveCandidate;$('#approveCandidate').onclick=approveCandidate;$('#promoteCandidate').onclick=promoteCurrentCandidate;$('#createSnapshot').onclick=()=>{AXM.snapshot('manual snapshot');renderLineage();AXM.toast('Immutable rollback snapshot created.')};
    $('#importExtensionButton').onclick=()=>$('#extensionFileInput').click();$('#extensionFileInput').addEventListener('change',event=>{const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{AXM.importExtensionPackage(String(reader.result));renderExtensions();renderStatus();renderLineage();AXM.toast('Extension imported into QUARANTINED state.')}catch(err){AXM.toast(`Extension import rejected: ${err.message}`)}};reader.readAsText(file);event.target.value=''});
    $('#exportWorkspaceButton').onclick=()=>{AXM.exportWorkspace();AXM.toast('Portable workspace backup exported.')};$('#importWorkspaceButton').onclick=()=>$('#workspaceFileInput').click();$('#workspaceFileInput').addEventListener('change',event=>{const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const result=AXM.importWorkspace(String(reader.result));renderEditor();renderLineage();renderPresets();renderThemes();renderExtensions();renderStatus();populateFilters();renderAtlas();AXM.toast(`Workspace merged: ${result.themes} themes, ${result.extensions} extensions, ${result.projects||0} projects, ${result.batches||0} batches, ${result.presets} presets, ${result.candidates} candidates, ${result.snapshots} snapshots, ${result.skipped} skipped.`)}catch(err){AXM.toast(`Workspace import rejected: ${err.message}`)}};reader.readAsText(file);event.target.value=''});$('#importFamilyButton').onclick=()=>$('#familyFileInput').click();$('#familyFileInput').addEventListener('change',event=>{const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const result=AXM.importFamilyPackage(String(reader.result));renderEditor();renderLineage();renderPresets();renderThemes();renderExtensions();renderStatus();populateFilters();renderAtlas();AXM.toast(`Family package merged: ${result.themes} themes, ${result.extensions} extensions, ${result.presets} presets, ${result.candidates} candidates, ${result.snapshots} snapshots, ${result.skipped} skipped.`)}catch(err){AXM.toast(`Family import rejected: ${err.message}`)}};reader.readAsText(file);event.target.value=''});
    window.addEventListener('axm:mold-change',()=>{renderEditor();renderVariants();renderExports()});window.addEventListener('axm:registry-change',()=>{populateFilters();renderOverview();renderAtlas();renderFoundrySteps();renderExtensions();renderLineage();renderStatus()});window.addEventListener('axm:theme-change',()=>{populateFilters();renderOverview();renderThemes();renderEditor();renderAtlas();renderStatus()});window.addEventListener('axm:log',renderLog);
  }
  function init(){
    updateTopButtons();setupNavigation();renderOverview();populateFilters();renderAtlas();renderOrgans();renderTokens();renderThemes();renderEditor();renderVariants();renderFoundrySteps();renderExtensions();bindEvents();window.AXMRecoveryUI?.init();renderStatus();AXM.log('AXM Visual Mold Foundry v0.9.1 initialized','PASS');document.body.dataset.axmReady='true';document.documentElement.dataset.axmReady='true';
  }
  try{init()}catch(err){console.error(err);document.body.dataset.axmReady='error';document.body.insertAdjacentHTML('afterbegin',`<div style="padding:16px;background:#5b1818;color:white">AXM initialization error: ${AXM.escapeHTML(err.message)}</div>`)}
})();
