(() => {
  'use strict';
  const A=window.AXM,R=window.AXMRender;
  const $=(selector,root=document)=>root.querySelector(selector),$$=(selector,root=document)=>[...root.querySelectorAll(selector)];
  let currentProject=null,currentBatch=null;
  const metric=(value,label)=>`<div class="metric"><b>${A.escapeHTML(String(value))}</b><span>${A.escapeHTML(label)}</span></div>`;
  const pillClass=state=>state==='APPROVED'?'built':state==='ARCHIVED'?'tested':'experimental';
  const renderChecks=(target,report)=>{target.innerHTML=(report?.checks||[]).map(item=>`<div class="validation-row ${item.state.toLowerCase()}"><span class="check-state">${item.state}</span><div><b>${A.escapeHTML(item.label)}</b><p>${A.escapeHTML(item.evidence)}</p></div></div>`).join('')||'<p class="muted">No validation report yet.</p>';};
  const activeMolds=()=>A.getAllMolds({includeInactive:false}).filter(A.isMoldUsable);
  const activeThemes=()=>A.getAllThemes({includeInactive:false}).filter(A.isThemeUsable);

  function populateAssemblyOptions(){
    const projectTheme=$('#projectTheme'),selected=projectTheme?.value||'';if(projectTheme){projectTheme.innerHTML='<option value="">Keep each item theme</option>'+activeThemes().map(theme=>`<option value="${A.escapeHTML(theme.id)}">${A.escapeHTML(theme.name)}</option>`).join('');if([...projectTheme.options].some(option=>option.value===selected))projectTheme.value=selected;}
    const batchMold=$('#batchMold'),moldSelected=batchMold?.value||A.state.moldId;if(batchMold){batchMold.innerHTML=activeMolds().map(mold=>`<option value="${A.escapeHTML(mold.id)}">${A.escapeHTML(mold.name)}</option>`).join('');if([...batchMold.options].some(option=>option.value===moldSelected))batchMold.value=moldSelected;}
  }
  function projectFromForm(){if(!currentProject)currentProject=A.newProject();currentProject.name=A.sanitizeText($('#projectName').value,120)||'Untitled Visual Project';currentProject.description=A.sanitizeText($('#projectDescription').value,1200);currentProject.layout=$('#projectLayout').value;currentProject.shared_theme=$('#projectTheme').value||null;return currentProject;}
  function setProjectForm(project){currentProject=A.clone(project||A.newProject());$('#projectName').value=currentProject.name||'';$('#projectDescription').value=currentProject.description||'';$('#projectLayout').value=currentProject.layout||'gallery';populateAssemblyOptions();$('#projectTheme').value=currentProject.shared_theme||'';}
  function renderProjectSelect(){const select=$('#projectSelect'),selected=currentProject?.id||'';const projects=A.getProjects(true);select.innerHTML='<option value="">New project</option>'+projects.map(project=>`<option value="${project.id}">${A.escapeHTML(project.name)} · ${project.project_state}</option>`).join('');if(projects.some(project=>project.id===selected))select.value=selected;}
  function renderProjectMetrics(){const projects=A.getProjects(true);$('#projectMetrics').innerHTML=metric(projects.length,'stored visual projects')+metric(projects.filter(item=>item.project_state==='APPROVED').length,'approved projects')+metric(projects.reduce((sum,item)=>sum+(item.items?.length||0),0),'stored visual instances');}
  function projectItemCard(item,index,project){
    const card=document.createElement('article');card.className='assembly-card';const mold=A.findMold(item.mold_id),themeId=project.shared_theme||item.variant?.theme,theme=A.findTheme(themeId),usable=mold&&A.isMoldUsable(mold)&&theme&&A.isThemeUsable(theme)&&A.themeCompatibleWithMold(theme,mold);card.innerHTML=`<div class="assembly-preview ${usable?'':'assembly-unresolved'}"></div><div class="assembly-body"><span class="assembly-order">${String(index+1).padStart(2,'0')}</span><h3>${A.escapeHTML(item.label||mold?.name||'Unresolved item')}</h3><p>${A.escapeHTML(mold?.name||item.mold_id)} · ${A.escapeHTML(themeId||'no theme')}</p>${item.note?`<p class="project-description">${A.escapeHTML(item.note)}</p>`:''}<div class="button-row"><button class="quiet-button" data-edit type="button">Edit</button><button class="quiet-button" data-up type="button">↑</button><button class="quiet-button" data-down type="button">↓</button><button class="danger-button" data-remove type="button">Remove</button></div></div>`;
    const preview=$('.assembly-preview',card);if(usable)R.renderThumbnail(preview,mold,item.controls,{...item.variant,theme:themeId,motion:'still',performance:'low'});else preview.innerHTML='<div>Dependency unavailable or inactive.<br>Record is preserved.</div>';
    $('[data-edit]',card).onclick=()=>{if(!usable){A.toast('This item cannot open until its dependencies are active.');return}A.setMold(mold.id);A.state.controls=A.clone(item.controls);A.state.variant={...A.state.variant,...A.clone(item.variant),theme:themeId};window.dispatchEvent(new CustomEvent('axm:mold-change'));$('[data-view="editor"]')?.click();};
    $('[data-up]',card).onclick=()=>{currentProject=A.moveProjectItem(project.id,item.id,-1);renderProjects();};$('[data-down]',card).onclick=()=>{currentProject=A.moveProjectItem(project.id,item.id,1);renderProjects();};$('[data-remove]',card).onclick=()=>{currentProject=A.removeProjectItem(project.id,item.id);renderProjects();};return card;
  }
  function renderProjectRevisions(project){const target=$('#projectRevisions'),revisions=project.revisions||[];target.innerHTML=revisions.length?revisions.map(revision=>`<div class="snapshot"><div><b>${A.escapeHTML(revision.reason)}</b><span>${new Date(revision.created_at).toLocaleString()} · ${revision.item_count} items · ${A.escapeHTML(revision.fingerprint)}</span></div><div class="revision-actions"><button class="quiet-button" data-revision="${revision.id}" type="button">Restore</button></div></div>`).join(''):'<p class="muted">No earlier project revisions yet.</p>';$$('[data-revision]',target).forEach(button=>button.onclick=()=>{try{currentProject=A.restoreProjectRevision(project.id,button.dataset.revision);setProjectForm(currentProject);renderProjects();A.toast('Project revision restored as DRAFT.')}catch(err){A.toast(err.message)}});}
  function renderProjects(){
    if(!currentProject){const first=A.getProjects(false)[0];setProjectForm(first||A.newProject());}
    populateAssemblyOptions();renderProjectSelect();renderProjectMetrics();const project=projectFromForm(),report=A.projectValidation(project);renderChecks($('#projectValidation'),report);$('#projectStateTitle').textContent=project.project_state;$('#projectStatePill').textContent=project.project_state;$('#projectStatePill').className=`status-pill ${pillClass(project.project_state)}`;$('#projectItemCount').textContent=`${project.items?.length||0} items`;const grid=$('#projectItems');grid.innerHTML='';if(!project.items?.length)grid.innerHTML='<div class="assembly-placeholder">Add the current mold from the editor, or create a project from a data batch.</div>';else project.items.forEach((item,index)=>grid.appendChild(projectItemCard(item,index,project)));renderProjectRevisions(project);
  }
  function saveProject(){try{currentProject=A.upsertProject(projectFromForm(),'manual project save');setProjectForm(currentProject);renderProjects();A.toast('Visual project saved locally.')}catch(err){A.toast(`Project save failed: ${err.message}`)}}

  function batchFromForm(){if(!currentBatch)currentBatch=A.newBatch();const oldMold=currentBatch.mold_id,newMold=$('#batchMold').value;currentBatch.name=A.sanitizeText($('#batchName').value,120)||'Untitled Data Batch';currentBatch.mold_id=newMold;if(oldMold!==newMold){const mold=A.findMold(newMold);currentBatch.defaults={controls:A.defaultControls(mold),variant:{...A.defaultVariant(mold),motion:'still',performance:'low'}};currentBatch.mapping=A.inferBatchMapping(mold,currentBatch.headers||[]);}return currentBatch;}
  function setBatchForm(batch){currentBatch=A.clone(batch||A.newBatch());$('#batchName').value=currentBatch.name||'';populateAssemblyOptions();$('#batchMold').value=currentBatch.mold_id||A.state.moldId;$('#batchSource').value=currentBatch.rows?.length?JSON.stringify(currentBatch.rows,null,2):$('#batchSource').value;}
  function renderBatchSelect(){const select=$('#batchSelect'),selected=currentBatch?.id||'',batches=A.getBatches(true);select.innerHTML='<option value="">New batch</option>'+batches.map(batch=>`<option value="${batch.id}">${A.escapeHTML(batch.name)} · ${batch.batch_state}</option>`).join('');if(batches.some(batch=>batch.id===selected))select.value=selected;}
  function renderBatchMetrics(){const batches=A.getBatches(true);$('#batchMetrics').innerHTML=metric(batches.length,'stored data batches')+metric(batches.reduce((sum,batch)=>sum+(batch.rows?.length||0),0),'stored data rows')+metric(batches.filter(batch=>batch.batch_state==='APPROVED').length,'approved batches');}
  function renderBatchMapping(){const batch=batchFromForm(),mold=A.findMold(batch.mold_id),headers=batch.headers||[],target=$('#batchMapping');target.innerHTML='';if(!headers.length){target.innerHTML='<p class="muted">Parse CSV or JSON first. Mapping is inferred from the column names.</p>';return}const makeRow=(group,key,current)=>{const wrap=document.createElement('label');wrap.className='mapping-row';wrap.innerHTML=`<b>${A.escapeHTML(group)} · ${A.escapeHTML(key)}</b><select><option value="">Use default</option>${headers.map(header=>`<option value="${A.escapeHTML(header)}" ${header===current?'selected':''}>${A.escapeHTML(header)}</option>`).join('')}</select>`;$('select',wrap).onchange=event=>{batch.mapping[group==='input'?'controls':'variants'][key]=event.target.value||null;renderBatchValidation()};return wrap};target.insertAdjacentHTML('beforeend','<div class="mapping-section-title">Mold inputs</div>');Object.keys(mold?.inputs||{}).forEach(key=>target.appendChild(makeRow('input',key,batch.mapping?.controls?.[key])));target.insertAdjacentHTML('beforeend','<div class="mapping-section-title">Variant axes</div>');Object.keys(mold?.variants||{}).forEach(key=>target.appendChild(makeRow('variant',key,batch.mapping?.variants?.[key])));}
  function renderBatchValidation(){const batch=batchFromForm(),validation=A.batchValidation(batch);renderChecks($('#batchValidation'),validation);$('#batchStatePill').textContent=batch.batch_state;$('#batchStatePill').className=`status-pill ${pillClass(batch.batch_state)}`;return validation;}
  function batchPreviewCard(item,index){const card=document.createElement('article');card.className='assembly-card';const mold=A.findMold(item.mold_id),theme=A.findTheme(item.variant.theme),usable=mold&&A.isMoldUsable(mold)&&theme&&A.isThemeUsable(theme)&&A.themeCompatibleWithMold(theme,mold);card.innerHTML=`<div class="assembly-preview ${usable?'':'assembly-unresolved'}"></div><div class="assembly-body"><span class="assembly-order">ROW ${index+1}</span><h3>${A.escapeHTML(item.label)}</h3><p>${A.escapeHTML(mold?.name||item.mold_id)} · ${A.escapeHTML(item.variant.theme||'no theme')}</p></div>`;const preview=$('.assembly-preview',card);if(usable)R.renderThumbnail(preview,mold,item.controls,{...item.variant,motion:'still',performance:'low'});else preview.textContent='Unresolved row dependency.';return card;}
  function renderBatchPreview(){const instances=A.materializeBatch(batchFromForm()),grid=$('#batchPreviewGrid');grid.innerHTML='';instances.slice(0,20).forEach((item,index)=>grid.appendChild(batchPreviewCard(item,index)));if(!instances.length)grid.innerHTML='<div class="assembly-placeholder">Parse source rows to generate a preview.</div>';$('#batchPreviewCount').textContent=`${Math.min(instances.length,20)} shown · ${instances.length} total`;renderBatchValidation();}
  function renderBatches(){if(!currentBatch){const first=A.getBatches(false)[0];setBatchForm(first||A.newBatch());}populateAssemblyOptions();renderBatchSelect();renderBatchMetrics();renderBatchMapping();renderBatchValidation();renderBatchPreview();}
  function parseCurrentBatch(){try{const parsed=A.parseBatchSource($('#batchSource').value),mold=A.findMold($('#batchMold').value);currentBatch=batchFromForm();currentBatch.source_format=parsed.format;currentBatch.headers=parsed.headers;currentBatch.rows=parsed.rows;currentBatch.mapping=A.inferBatchMapping(mold,parsed.headers);currentBatch.intake_report={source_format:parsed.format,delimiter:parsed.delimiter,total_rows:parsed.total_rows,accepted_rows:parsed.rows.length,truncated_count:parsed.truncated_count,renamed_headers:parsed.renamed_headers,accepted_fingerprint:A.fingerprintValue({headers:parsed.headers,rows:parsed.rows})};renderBatches();A.toast(parsed.truncated_count?`Accepted ${parsed.rows.length} of ${parsed.total_rows} rows; ${parsed.truncated_count} were omitted and approval is blocked until the source is split.`:`Parsed all ${parsed.rows.length} local data rows${parsed.delimiter?` using ${parsed.delimiter} separation`:''}.`);return currentBatch}catch(err){A.toast(`Batch intake rejected: ${err.message}`);return null}}
  function saveBatch(){try{if(!currentBatch?.rows?.length&&!parseCurrentBatch())return;currentBatch=A.upsertBatch(batchFromForm());setBatchForm(currentBatch);renderBatches();A.toast('Data batch saved locally.')}catch(err){A.toast(`Batch save failed: ${err.message}`)}}
  function readJSONFile(input,handler){const file=input.files?.[0];if(!file)return;if(file.size>16_000_000){A.toast('Package rejected before reading: the 16 MB JSON limit was exceeded.');input.value='';return}const reader=new FileReader();reader.onload=()=>{try{handler(String(reader.result))}catch(err){A.toast(err.message)}};reader.onerror=()=>A.toast('Package file could not be read locally.');reader.readAsText(file);input.value='';}
  function installEditorProjectButton(){const row=$('#savePresetButton')?.closest('.button-row');if(!row)return;let button=$('#editorAddToProjectButton');if(!button){button=document.createElement('button');button.className='quiet-button';button.id='editorAddToProjectButton';button.type='button';button.textContent='Add to project';row.appendChild(button)}button.onclick=()=>{if(!currentProject||currentProject.project_state==='ARCHIVED')currentProject=A.newProject(`${A.getMold().name} Project`);currentProject=projectFromForm();currentProject=A.addCurrentToProject(currentProject);setProjectForm(currentProject);renderProjects();A.toast('Current mold instance added to Project Composer.');};}

  function bind(){
    $$('[data-view="projects"],[data-go="projects"]').forEach(button=>button.addEventListener('click',()=>renderProjects()));$$('[data-view="batches"],[data-go="batches"]').forEach(button=>button.addEventListener('click',()=>renderBatches()));
    $('#projectSelect').onchange=event=>{const project=A.getProject(event.target.value);setProjectForm(project||A.newProject());renderProjects()};$('#projectNewButton').onclick=()=>{setProjectForm(A.newProject());renderProjects()};$('#projectSaveButton').onclick=saveProject;$('#projectAddCurrentButton').onclick=()=>{currentProject=A.addCurrentToProject(projectFromForm());setProjectForm(currentProject);renderProjects();A.toast('Current mold added to project.')};$('#projectApproveButton').onclick=()=>{try{currentProject=A.upsertProject(projectFromForm(),'pre-approval save');currentProject=A.approveProject(currentProject.id);setProjectForm(currentProject);renderProjects();A.toast('Project approved explicitly.')}catch(err){A.toast(err.message)}};$('#projectArchiveButton').onclick=()=>{try{currentProject=A.archiveProject(projectFromForm().id);setProjectForm(currentProject);renderProjects();A.toast('Project archived without deletion.')}catch(err){A.toast(err.message)}};$('#projectExportButton').onclick=()=>{try{A.exportProjectPackage(projectFromForm());A.toast('Project package exported.')}catch(err){A.toast(err.message)}};$('#projectExportHTMLButton').onclick=()=>{try{A.exportProjectHTML(projectFromForm());A.toast('Project HTML exported.')}catch(err){A.toast(err.message)}};$('#projectImportButton').onclick=()=>$('#projectFileInput').click();$('#projectFileInput').onchange=()=>readJSONFile($('#projectFileInput'),raw=>{currentProject=A.importProjectPackage(raw);setProjectForm(currentProject);renderProjects();A.toast('Project imported as DRAFT; dependencies remain quarantined.')});['projectName','projectDescription','projectLayout','projectTheme'].forEach(id=>$('#'+id).addEventListener(id==='projectDescription'||id==='projectName'?'input':'change',()=>{projectFromForm();renderChecks($('#projectValidation'),A.projectValidation(currentProject))}));
    $('#batchSelect').onchange=event=>{const batch=A.getBatch(event.target.value);setBatchForm(batch||A.newBatch());renderBatches()};$('#batchMold').onchange=()=>{batchFromForm();renderBatchMapping();renderBatchValidation()};$('#batchSourceFileButton').onclick=()=>$('#batchSourceFileInput').click();$('#batchSourceFileInput').onchange=()=>{const input=$('#batchSourceFileInput'),file=input.files?.[0];if(!file)return;if(file.size>4_000_000){A.toast('Data file rejected: the 4 MB batch intake limit was exceeded.');input.value='';return}const reader=new FileReader();reader.onload=()=>{$('#batchSource').value=String(reader.result);parseCurrentBatch();input.value=''};reader.onerror=()=>{A.toast('Data file could not be read locally.');input.value=''};reader.readAsText(file)};$('#batchParseButton').onclick=parseCurrentBatch;$('#batchSaveButton').onclick=saveBatch;$('#batchApproveButton').onclick=()=>{try{currentBatch=A.upsertBatch(batchFromForm());currentBatch=A.approveBatch(currentBatch.id);setBatchForm(currentBatch);renderBatches();A.toast('Batch approved explicitly.')}catch(err){A.toast(err.message)}};$('#batchArchiveButton').onclick=()=>{try{currentBatch=A.archiveBatch(batchFromForm().id);setBatchForm(currentBatch);renderBatches();A.toast('Batch archived without deletion.')}catch(err){A.toast(err.message)}};$('#batchPreviewButton').onclick=renderBatchPreview;$('#batchToProjectButton').onclick=()=>{try{currentBatch=A.upsertBatch(batchFromForm());currentProject=A.projectFromBatch(currentBatch);setProjectForm(currentProject);renderProjects();$('[data-view="projects"]')?.click();A.toast('Data batch materialized into a visual project.')}catch(err){A.toast(err.message)}};$('#batchExportButton').onclick=()=>{try{A.exportBatchPackage(batchFromForm());A.toast('Batch package exported.')}catch(err){A.toast(err.message)}};$('#batchExportHTMLButton').onclick=()=>{try{A.exportBatchHTML(batchFromForm());A.toast('Batch HTML exported.')}catch(err){A.toast(err.message)}};$('#batchImportButton').onclick=()=>$('#batchFileInput').click();$('#batchFileInput').onchange=()=>readJSONFile($('#batchFileInput'),raw=>{currentBatch=A.importBatchPackage(raw);setBatchForm(currentBatch);renderBatches();A.toast('Batch imported as DRAFT; dependencies remain quarantined.')});
    window.addEventListener('axm:project-change',()=>{renderProjectMetrics();renderProjectSelect()});window.addEventListener('axm:batch-change',()=>{renderBatchMetrics();renderBatchSelect()});window.addEventListener('axm:registry-change',populateAssemblyOptions);window.addEventListener('axm:theme-change',populateAssemblyOptions);
  }
  function init(){populateAssemblyOptions();setProjectForm(A.getProjects(false)[0]||A.newProject());setBatchForm(A.getBatches(false)[0]||A.newBatch());bind();installEditorProjectButton();renderProjects();renderBatches();A.log('Project Composer and Data Batch Builder v0.9 initialized','PASS');}
  try{init()}catch(err){console.error(err);A.log(`Assembly UI initialization failed: ${err.message}`,'FAIL');}
})();
