(() => {
  'use strict';
  const A=window.AXM,R=window.AXMRender,V=window.AXMValidate;
  if(!A||!R)throw new Error('AXM assembly module requires core and renderers.');
  const PROJECT_STATES=new Set(['DRAFT','APPROVED','ARCHIVED']);
  const BATCH_STATES=new Set(['DRAFT','APPROVED','ARCHIVED']);
  const MAX_ITEMS=100,MAX_REVISIONS=8,MAX_ROWS=100,MAX_COLUMNS=100,MAX_DEPENDENCIES=100;

  const checksSummary=checks=>checks.reduce((acc,check)=>(acc[check.state.toLowerCase()]++,acc),{pass:0,warn:0,fail:0});
  const report=(schema,checks,extra={})=>{const summary=checksSummary(checks);return A.attachPacketIntegrity({schema,created_at:A.nowISO(),status:summary.fail?'FAIL':summary.warn?'WARN':'PASS',summary,checks,...extra});};
  const check=(state,label,evidence)=>({state,label,evidence:A.safeText(evidence,800)});
  const textBytes=value=>JSON.stringify(value||null).length*2;
  const unsafeScalar=value=>typeof value==='string'&&(/\b(?:https?:\/\/|javascript:|vbscript:)/i.test(value)||/^data:text\/html/i.test(value));
  const activeMold=id=>{const mold=A.findMold(id);return mold&&A.isMoldUsable(mold)?mold:null};
  const cleanProjectShell=project=>{const copy=A.clone(project);for(const key of ['revisions','validation','integrity','updated_at','approved_at','approved_fingerprint','approval_method','archived_at'])delete copy[key];return copy};
  const cleanBatchShell=batch=>{const copy=A.clone(batch);for(const key of ['validation','integrity','updated_at','approved_at','approved_fingerprint','approval_method','archived_at'])delete copy[key];return copy};
  const approvalComparable=(shell,stateKey)=>{const copy=A.clone(shell);if(copy[stateKey]==='ARCHIVED')copy[stateKey]='APPROVED';return copy};
  const assertLimit=(items,limit,label)=>{if(!Array.isArray(items))return [];if(items.length>limit)throw new Error(`${label} exceeds the ${limit}-record limit; nothing was saved or omitted.`);return items};

  function normalizeHeaders(rawHeaders){
    if(!Array.isArray(rawHeaders))throw new Error('Batch headers must be an array.');
    assertLimit(rawHeaders,MAX_COLUMNS,'Batch header count');
    const headers=[],renamed=[],sourceToHeader=new Map();
    rawHeaders.forEach((raw,index)=>{
      const source=String(raw??''),fallback=`column_${index+1}`,base=A.safeText(source.trim()||fallback,64)||fallback;
      let name=base,suffix=2;
      while(headers.includes(name)){const tail=`_${suffix++}`;name=`${base.slice(0,Math.max(1,64-tail.length))}${tail}`;}
      if(name!==source)renamed.push({index:index+1,from:A.safeText(source,160),to:name});
      headers.push(name);sourceToHeader.set(source,name);
    });
    return {headers,renamed,sourceToHeader};
  }

  function projectRevision(project,reason='manual save'){
    const snapshot=cleanProjectShell(project);
    return {schema:'axm.visual-project-revision/0.6',id:A.uid('axm.project.revision'),created_at:A.nowISO(),reason:A.safeText(reason,100),fingerprint:A.fingerprintValue(snapshot),item_count:(snapshot.items||[]).length,project:snapshot};
  }
  function newProject(name='Untitled Visual Project',description='',layout='gallery'){
    return {schema:'axm.visual-project/0.6',id:A.uid('axm.project'),name:A.safeText(name,120),description:A.safeText(description,1200),version:'0.6.0',project_state:'DRAFT',layout:['gallery','story','deck'].includes(layout)?layout:'gallery',shared_theme:null,items:[],revisions:[],created_at:A.nowISO(),updated_at:A.nowISO(),provenance:{author:'Local AXM user',source:`${A.APP.name} v${A.APP.version} Project Composer`,license:'user-controlled',rights_scope:'private-local',consent:'explicit local creation',transformation_history:['created as local visual project']}};
  }
  function getProjects(includeArchived=true){const list=A.storageRead(A.STORAGE.projects,[]);return includeArchived?list:list.filter(item=>item.project_state!=='ARCHIVED');}
  function getProject(id){return getProjects(true).find(item=>item.id===id)||null;}
  function normalizeProjectItem(source,index=0){
    const item=A.clone(source||{}),mold=A.findMold(item.mold_id)||A.getMold();
    return {schema:'axm.visual-project-item/0.6',id:item.id||A.uid('axm.project.item'),order:Number.isFinite(Number(item.order))?Number(item.order):index,label:A.safeText(item.label||mold?.name||`Visual ${index+1}`,120),note:A.safeText(item.note||'',800),mold_id:item.mold_id||mold.id,controls:{...A.defaultControls(mold),...(item.controls||{})},variant:{...A.defaultVariant(mold),...(item.variant||{})},created_at:item.created_at||A.nowISO()};
  }
  function projectValidation(project){
    const p=A.clone(project||{}),checks=[];
    const required=['id','name','project_state','layout','items','provenance'],missing=required.filter(key=>p[key]===undefined||p[key]===null||p[key]==='');
    checks.push(check(missing.length?'FAIL':'PASS','Project manifest',missing.length?`Missing: ${missing.join(', ')}`:'Required project fields are present.'));
    const items=Array.isArray(p.items)?p.items:[];
    checks.push(check(!items.length||items.length>MAX_ITEMS?'FAIL':'PASS','Project item count',!items.length?'A project needs at least one visual item.':items.length>MAX_ITEMS?`${items.length} exceeds the ${MAX_ITEMS}-item limit.`:`${items.length}/${MAX_ITEMS} visual items.`));
    const ids=items.map(item=>item.id).filter(Boolean),duplicates=[...new Set(ids.filter((id,index)=>ids.indexOf(id)!==index))];
    checks.push(check(duplicates.length?'FAIL':'PASS','Project item IDs',duplicates.length?`Duplicate item IDs: ${duplicates.join(', ')}`:'Item IDs are unique.'));
    const missingMolds=[],inactiveMolds=[],missingThemes=[],incompatibleThemes=[],validationFails=[],validationWarnings=[];
    items.slice(0,MAX_ITEMS).forEach((raw,index)=>{
      const item=normalizeProjectItem(raw,index),mold=A.findMold(item.mold_id);
      if(!mold){missingMolds.push(item.mold_id);return}
      if(!A.isMoldUsable(mold)){inactiveMolds.push(item.mold_id);return}
      const themeId=p.shared_theme||item.variant.theme,theme=A.findTheme(themeId);
      if(!theme){missingThemes.push(themeId);return}
      if(!A.isThemeUsable(theme)||!A.themeCompatibleWithMold(theme,mold)){incompatibleThemes.push(`${item.mold_id}→${themeId}`);return}
      if(V){const instanceVariant={...item.variant,theme:themeId,motion:'still'},validation=V.validate(mold,item.controls,instanceVariant,{reducedMotion:true,extraRegistry:A.getExtensions(true).filter(entry=>entry.id!==mold.id)});if(validation.summary.fail)validationFails.push(item.id);else if(validation.summary.warn)validationWarnings.push(item.id)}
    });
    checks.push(check(missingMolds.length?'FAIL':inactiveMolds.length?(p.project_state==='ARCHIVED'?'WARN':'FAIL'):'PASS','Mold dependencies',missingMolds.length?`Missing molds: ${[...new Set(missingMolds)].join(', ')}`:inactiveMolds.length?`${inactiveMolds.length} item(s) depend on inactive extensions; approval is blocked until activation.`:'All item molds are available and active.'));
    checks.push(check(missingThemes.length?'FAIL':incompatibleThemes.length?(p.project_state==='ARCHIVED'?'WARN':'FAIL'):'PASS','Theme dependencies',missingThemes.length?`Missing themes: ${[...new Set(missingThemes)].join(', ')}`:incompatibleThemes.length?`${incompatibleThemes.length} item/theme pair(s) are inactive or incompatible; approval is blocked.`:'All item themes are available and compatible.'));
    checks.push(check(validationFails.length?'FAIL':validationWarnings.length?'WARN':'PASS','Instance validation',validationFails.length?`${validationFails.length} item(s) fail mold validation.`:validationWarnings.length?`${validationWarnings.length} item(s) carry validation warnings.`:'Every resolved item passes its mold validation.'));
    const mediaBytes=items.reduce((sum,item)=>sum+(typeof item?.controls?.mediaData==='string'?item.controls.mediaData.length*2:0),0);
    checks.push(check(mediaBytes>6_000_000?'WARN':'PASS','Embedded media estimate',`${mediaBytes.toLocaleString()} approximate UTF-16 bytes embedded in project items${mediaBytes>6_000_000?'; consider external local asset intake before scaling further.':'.'}`));
    if(p.import_integrity)checks.push(check(p.import_integrity.status==='FAIL'?'FAIL':p.import_integrity.status==='MISSING'?'WARN':'PASS','Import integrity',p.import_integrity.status==='PASS'?'Imported project package fingerprint was verified.':p.import_integrity.status==='MISSING'?'Imported project package had no integrity fingerprint; project remains DRAFT.':'Imported project package fingerprint failed.'));
    checks.push(check(PROJECT_STATES.has(p.project_state)?'PASS':'FAIL','Project state',PROJECT_STATES.has(p.project_state)?`Explicit state: ${p.project_state}.`:`Unsupported state: ${p.project_state}`));
    return report('axm.visual-project-validation/0.6',checks,{project_id:p.id||null,item_count:items.length});
  }
  function upsertProject(project,reason='manual save'){
    const list=getProjects(true),copy=A.clone(project),index=list.findIndex(item=>item.id===copy.id),previous=index>=0?list[index]:null;
    const rawItems=assertLimit(Array.isArray(copy.items)?copy.items:[],MAX_ITEMS,'Project item count');
    copy.schema='axm.visual-project/0.6';copy.version='0.6.0';copy.name=A.safeText(copy.name||'Untitled Visual Project',120);copy.description=A.safeText(copy.description||'',1200);copy.layout=['gallery','story','deck'].includes(copy.layout)?copy.layout:'gallery';copy.project_state=PROJECT_STATES.has(copy.project_state)?copy.project_state:'DRAFT';copy.items=rawItems.map(normalizeProjectItem).map((item,i)=>({...item,order:i}));copy.revisions=Array.isArray(copy.revisions)?copy.revisions.slice(0,MAX_REVISIONS):[];
    if(previous){const before=cleanProjectShell(previous),after=cleanProjectShell(copy);if(A.fingerprintValue(before)!==A.fingerprintValue(after)){copy.revisions=[projectRevision(previous,reason),...copy.revisions].slice(0,MAX_REVISIONS);if(previous.project_state==='APPROVED'&&A.fingerprintValue(approvalComparable(after,'project_state'))!==previous.approved_fingerprint){copy.project_state='DRAFT';delete copy.approved_at;delete copy.approved_fingerprint;}}}
    copy.updated_at=A.nowISO();copy.validation=projectValidation(copy);if(index>=0)list[index]=copy;else list.unshift(copy);A.requireStorageWrite(A.STORAGE.projects,list);A.log(`Saved visual project ${copy.name}`,'PASS');window.dispatchEvent(new CustomEvent('axm:project-change'));return copy;
  }
  function addCurrentToProject(projectOrId,label=''){
    const project=typeof projectOrId==='string'?getProject(projectOrId):A.clone(projectOrId||newProject()),mold=A.getMold(),item=normalizeProjectItem({label:label||`${mold.name} ${project.items.length+1}`,mold_id:mold.id,controls:A.clone(A.state.controls),variant:{...A.clone(A.state.variant),motion:'still'}},project.items.length);project.items.push(item);return upsertProject(project,'add current mold');
  }
  function removeProjectItem(projectId,itemId){const project=getProject(projectId);if(!project)throw new Error('Project not found.');project.items=project.items.filter(item=>item.id!==itemId);return upsertProject(project,'remove project item');}
  function moveProjectItem(projectId,itemId,direction){const project=getProject(projectId);if(!project)throw new Error('Project not found.');const index=project.items.findIndex(item=>item.id===itemId),next=index+Number(direction);if(index<0||next<0||next>=project.items.length)return project;[project.items[index],project.items[next]]=[project.items[next],project.items[index]];return upsertProject(project,'reorder project items');}
  function restoreProjectRevision(projectId,revisionId){const project=getProject(projectId);if(!project)throw new Error('Project not found.');const revision=(project.revisions||[]).find(item=>item.id===revisionId);if(!revision?.project)throw new Error('Project revision not found.');if(!revision.fingerprint)throw new Error('Project revision restore blocked: integrity fingerprint is missing.');const actual=A.fingerprintValue(revision.project);if(actual!==revision.fingerprint)throw new Error(`Project revision restore blocked: fingerprint mismatch (${revision.fingerprint} expected, ${actual} calculated).`);const restored={...A.clone(revision.project),id:project.id,project_state:'DRAFT',revisions:[projectRevision(project,'before project rollback'),...(project.revisions||[])].slice(0,MAX_REVISIONS),updated_at:A.nowISO()};delete restored.approved_at;delete restored.approved_fingerprint;return upsertProject(restored,'restore project revision');}
  function approveProject(id){const project=getProject(id);if(!project)throw new Error('Project not found.');const validation=projectValidation(project),dependencies=validation.checks.filter(item=>['Mold dependencies','Theme dependencies'].includes(item.label));if(validation.summary.fail||dependencies.some(item=>item.state!=='PASS'))throw new Error('Project approval blocked by validation failures or inactive dependencies.');const copy=A.clone(project);copy.project_state='APPROVED';copy.approved_at=A.nowISO();copy.approval_method='explicit-project-composer-action';copy.approved_fingerprint=A.fingerprintValue(cleanProjectShell(copy));copy.validation=validation;return upsertProject(copy,'approve project');}
  function archiveProject(id){const project=getProject(id);if(!project)throw new Error('Project not found.');const copy=A.clone(project);copy.project_state='ARCHIVED';copy.archived_at=A.nowISO();return upsertProject(copy,'archive project');}
  function projectDependencyRecords(project){
    const moldIds=new Set((project.items||[]).map(item=>item.mold_id)),extensions=[],seen=new Set();
    const addExtension=id=>{const mold=A.findMold(id);if(!mold||mold.source_kind!=='extension'||seen.has(id))return;seen.add(id);extensions.push(A.clone(mold));addExtension(mold.lineage?.parent||mold.parent)};moldIds.forEach(addExtension);
    const themeIds=new Set([project.shared_theme,...(project.items||[]).map(item=>item.variant?.theme),...extensions.flatMap(item=>item.variants?.theme||[])].filter(Boolean)),themes=[],themeSeen=new Set();
    const addTheme=id=>{const theme=A.findTheme(id);if(!theme||theme.source_kind!=='local-theme'||themeSeen.has(id))return;themeSeen.add(id);themes.push(A.clone(theme));addTheme(theme.lineage?.parent||theme.parent_theme)};themeIds.forEach(addTheme);
    return {local_extensions:extensions,local_themes:themes};
  }
  function projectPacket(projectOrId){const project=typeof projectOrId==='string'?getProject(projectOrId):A.clone(projectOrId);if(!project)throw new Error('Project not found.');const dependencies=projectDependencyRecords(project);return A.attachPacketIntegrity({schema:'axm.visual-project-package/0.6',version:'0.6.0',created_at:A.nowISO(),application:A.applicationMetadata(),project:A.clone(project),...dependencies,validation:projectValidation(project)},'Project package fingerprint covers project order, controls, variants, local theme and extension dependencies, revisions, and validation. Imported dependencies enter quarantine.');}
  function exportProjectPackage(projectOrId){const packet=projectPacket(projectOrId);A.downloadBlob(`${A.slugify(packet.project.name)}.axmproject.json`,JSON.stringify(packet,null,2)+'\n','application/json');return packet;}
  function importDependencyRecords(packet,origin){
    const rawThemes=packet.local_themes||[],rawExtensions=packet.local_extensions||[];
    if(rawThemes.length>MAX_DEPENDENCIES||rawExtensions.length>MAX_DEPENDENCIES)throw new Error(`Dependency package exceeds the ${MAX_DEPENDENCIES}-record per-type limit.`);
    const themeMap=new Map(),themePairs=[],extensionMap=new Map(),extensionPairs=[];
    for(const source of rawThemes){const item=A.importThemeRecord(source,origin);themeMap.set(source.id,item.id);themePairs.push({source,item});}
    themePairs.forEach(({source,item})=>{const parent=source.lineage?.parent||source.parent_theme,newParent=themeMap.get(parent);if(newParent)A.upsertTheme({...item,parent_theme:newParent,lineage:{...(item.lineage||{}),parent:newParent},updated_at:A.nowISO()});});
    for(const source of rawExtensions){const item=A.importExtensionRecord(source,origin,themeMap);extensionMap.set(source.id,item.id);extensionPairs.push({source,item});}
    extensionPairs.forEach(({source,item})=>{const parent=source.lineage?.parent||source.parent,newParent=extensionMap.get(parent);if(newParent)A.upsertExtension({...item,lineage:{...(item.lineage||{}),parent:newParent},inherited_from:newParent,updated_at:A.nowISO()});});
    return {themeMap,extensionMap};
  }
  function remapProject(project,themeMap=new Map(),extensionMap=new Map(),origin='import'){
    const copy=A.clone(project),items=assertLimit(Array.isArray(copy.items)?copy.items:[],MAX_ITEMS,'Imported project item count');copy.id=A.uid('axm.project.imported');copy.schema='axm.visual-project/0.6';copy.version='0.6.0';copy.name=A.safeText(copy.name||'Imported Visual Project',120);copy.project_state='DRAFT';copy.imported_at=A.nowISO();copy.import_origin=A.safeText(origin,120);copy.imported_from_id=project.id||null;copy.shared_theme=themeMap.get(copy.shared_theme)||copy.shared_theme;copy.items=items.map((item,index)=>normalizeProjectItem({...item,id:A.uid('axm.project.item'),mold_id:extensionMap.get(item.mold_id)||item.mold_id,variant:{...(item.variant||{}),theme:themeMap.get(item.variant?.theme)||item.variant?.theme}},index));copy.revisions=[];delete copy.approved_at;delete copy.approved_fingerprint;return copy;
  }
  function importProjectPackage(raw){const packet=typeof raw==='string'?A.safeParseJSON(raw):A.clone(raw);if(!packet||packet.schema!=='axm.visual-project-package/0.6'||!packet.project)throw new Error('Not a valid AXM visual project package.');assertLimit(Array.isArray(packet.project.items)?packet.project.items:[],MAX_ITEMS,'Imported project item count');const integrity=A.verifyPacketIntegrity(packet);if(integrity.status!=='PASS')throw new Error('Current project packages require a valid integrity fingerprint.');const maps=importDependencyRecords(packet,'project package');const project=remapProject(packet.project,maps.themeMap,maps.extensionMap,'project package');project.import_integrity=integrity;return upsertProject(project,'import project package');}
  function projectHTML(projectOrId){
    const project=typeof projectOrId==='string'?getProject(projectOrId):A.clone(projectOrId);if(!project)throw new Error('Project not found.');const items=assertLimit(Array.isArray(project.items)?project.items:[],MAX_ITEMS,'Project item count'),cards=items.map((raw,index)=>{const item=normalizeProjectItem(raw,index),mold=activeMold(item.mold_id),themeId=project.shared_theme||item.variant.theme,theme=A.findTheme(themeId),usable=mold&&theme&&A.isThemeUsable(theme)&&A.themeCompatibleWithMold(theme,mold);if(!usable)return `<article class="unresolved"><div><b>${A.escapeHTML(item.label)}</b><p>Unresolved or inactive dependency: ${A.escapeHTML(item.mold_id)} / ${A.escapeHTML(themeId||'no theme')}</p></div></article>`;const variant={...item.variant,theme:themeId,motion:'still',performance:'low'},canvas=R.renderCanvasForMold(mold,item.controls,variant,.48),data=canvas.toDataURL('image/png');return `<article><img src="${data}" alt="${A.escapeHTML(item.label)}"><footer><div><b>${A.escapeHTML(item.label)}</b><span>${A.escapeHTML(mold.name)} · ${A.escapeHTML(themeId)}</span></div>${item.note?`<p>${A.escapeHTML(item.note)}</p>`:''}</footer></article>`;}).join('');
    const layout=project.layout||'gallery';return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="generator" content="${A.escapeHTML(A.APP.name)} v${A.escapeHTML(A.APP.version)}"><title>${A.escapeHTML(project.name)}</title><style>body{margin:0;padding:28px;background:#070a10;color:#f3f7fb;font-family:system-ui}header{max-width:920px;margin:0 auto 24px}h1{font-size:clamp(30px,6vw,72px);margin:0 0 10px;line-height:1}header p{color:#a9b7c8;font-size:16px}.project{display:${layout==='story'?'flex':'grid'};${layout==='story'?'flex-direction:column;max-width:980px;margin:auto;':'grid-template-columns:repeat(auto-fit,minmax(280px,1fr));'}gap:18px}.project.deck{grid-template-columns:1fr;max-width:1180px;margin:auto}.project.deck article{min-height:75vh}.project.story article:nth-child(even){margin-left:min(9vw,120px)}article{background:#111a28;border:1px solid #27384e;border-radius:20px;overflow:hidden;break-inside:avoid;box-shadow:0 18px 60px rgba(0,0,0,.28)}article img{display:block;width:100%;height:${layout==='deck'?'68vh':'300px'};object-fit:contain;background:#05070b}footer{padding:14px 16px}footer div{display:flex;justify-content:space-between;gap:10px;align-items:center}footer span,footer p{color:#9fb0c2;font-size:13px}.unresolved{min-height:220px;display:grid;place-items:center;padding:20px;border-color:#9f4d00}@media print{body{background:white;color:black;padding:0}.project.deck article{page-break-after:always;border:none;box-shadow:none}.project.deck article img{height:78vh}}</style></head><body><header><h1>${A.escapeHTML(project.name)}</h1><p>${A.escapeHTML(project.description||'Local visual project')} · ${project.items.length} items · ${A.escapeHTML(project.project_state)} · generated ${A.escapeHTML(A.nowISO())}</p></header><main class="project ${A.escapeHTML(layout)}">${cards}</main></body></html>`;
  }
  function exportProjectHTML(projectOrId){const project=typeof projectOrId==='string'?getProject(projectOrId):projectOrId,html=projectHTML(project);A.downloadBlob(`${A.slugify(project.name)}-${project.layout||'gallery'}.html`,html,'text/html');return html;}

  function delimiterCount(line,delimiter){let quoted=false,count=0;for(let i=0;i<line.length;i++){const char=line[i],next=line[i+1];if(char==='"'&&quoted&&next==='"'){i++;continue}if(char==='"'){quoted=!quoted;continue}if(!quoted&&char===delimiter)count++;}return count;}
  function parseDelimited(source,delimiter=null){
    const text=String(source||'').replace(/^\uFEFF/,''),firstLine=text.split(/\r?\n/,1)[0]||'';
    if(!delimiter){const candidates=['\t',';',','].map(value=>({value,count:delimiterCount(firstLine,value)})).sort((a,b)=>b.count-a.count);delimiter=candidates[0].count?candidates[0].value:',';}
    if(!['\t',';',','].includes(delimiter))throw new Error('Unsupported delimiter. Use comma, semicolon, or tab.');
    const rows=[],row=[];let value='',quoted=false;
    for(let i=0;i<=text.length;i++){const char=text[i]??'\n',next=text[i+1];if(quoted){if(char==='"'&&next==='"'){value+='"';i++;}else if(char==='"')quoted=false;else value+=char;}else if(char==='"')quoted=true;else if(char===delimiter){row.push(value);value='';}else if(char==='\n'||i===text.length){row.push(value.replace(/\r$/,''));value='';const syntheticAfterTerminalNewline=i===text.length&&/[\r\n]$/.test(text)&&row.every(cell=>cell==='');if(!syntheticAfterTerminalNewline)rows.push(row.splice(0));else row.splice(0);}else value+=char;}
    if(quoted)throw new Error('CSV contains an unclosed quoted field.');
    if(!rows.length)return {headers:[],rows:[],delimiter:delimiter==='\t'?'tab':delimiter===';'?'semicolon':'comma',total_rows:0,accepted_rows:0,truncated_count:0,renamed_headers:[]};
    const normalized=normalizeHeaders(rows.shift()),totalRows=rows.length;assertLimit(rows,MAX_ROWS,'CSV source row count');
    rows.forEach((cells,index)=>{if(cells.length!==normalized.headers.length)throw new Error(`CSV row ${index+2} has ${cells.length} cells but ${normalized.headers.length} headers; ragged rows are rejected rather than padded or truncated.`);cells.forEach((cell,column)=>{if(String(cell).length>4000)throw new Error(`CSV row ${index+2}, column ${column+1} exceeds the 4,000-character cell limit; nothing was truncated.`);});});
    const objects=rows.map(cells=>Object.fromEntries(normalized.headers.map((header,index)=>[header,A.safeText(cells[index],4000)])));
    return {headers:normalized.headers,rows:objects,delimiter:delimiter==='\t'?'tab':delimiter===';'?'semicolon':'comma',total_rows:totalRows,accepted_rows:objects.length,truncated_count:0,renamed_headers:normalized.renamed};
  }
  function parseBatchSource(source){
    const sourceText=String(source??''),trimmed=sourceText.trim();if(!trimmed)throw new Error('Batch source is empty.');if(sourceText.length>4_000_000)throw new Error('Batch source exceeds the 4 MB intake limit.');
    if(trimmed.startsWith('[')||trimmed.startsWith('{')){
      const parsed=A.safeParseJSON(trimmed),sourceRows=Array.isArray(parsed)?parsed:parsed.rows;if(!Array.isArray(sourceRows))throw new Error('JSON batch source must be an array or an object with a rows array.');assertLimit(sourceRows,MAX_ROWS,'JSON source row count');
      const rawHeaders=[];
      sourceRows.forEach((row,index)=>{if(!row||typeof row!=='object'||Array.isArray(row))throw new Error(`Row ${index+1} is not an object.`);for(const key of Object.keys(row))if(!rawHeaders.includes(key))rawHeaders.push(key);});
      const normalized=normalizeHeaders(rawHeaders),clean=sourceRows.map((row,rowIndex)=>Object.fromEntries(Object.entries(row).map(([key,value])=>{const serialized=typeof value==='object'?JSON.stringify(value):String(value??'');if(serialized.length>4000)throw new Error(`JSON row ${rowIndex+1}, field ${key} exceeds the 4,000-character cell limit; nothing was truncated.`);return [normalized.sourceToHeader.get(key),A.safeText(serialized,4000)];})));
      return {format:'json',headers:normalized.headers,rows:clean,delimiter:null,total_rows:sourceRows.length,accepted_rows:clean.length,truncated_count:0,renamed_headers:normalized.renamed};
    }
    return {format:'csv',...parseDelimited(sourceText)};
  }
  function inferBatchMapping(mold,headers){
    const normalized=new Map(headers.map(header=>[header.toLowerCase().replace(/[^a-z0-9]+/g,'_'),header])),pick=(...names)=>{for(const name of names){const hit=normalized.get(name);if(hit)return hit}return null},aliases={title:['title','name','heading','label'],message:['message','description','body','text','summary'],badge:['badge','category','type','tag'],metric:['metric','value','number','score','amount'],cta:['cta','action','button','call_to_action']},controls={},variants={};
    Object.keys(mold.inputs||{}).forEach(key=>{controls[key]=pick(key,...(aliases[key]||[]))});Object.keys(mold.variants||{}).forEach(axis=>{variants[axis]=pick(axis)});return {controls,variants};
  }
  function coerceInput(spec,value){if(value===undefined||value===null||value==='')return spec.default;if(spec.type==='number'){const number=Number(value);return Number.isFinite(number)?A.clamp(number,spec.minimum??-Infinity,spec.maximum??Infinity):spec.default}if(spec.type==='boolean')return ['1','true','yes','on'].includes(String(value).toLowerCase());if(spec.type==='enum')return (spec.values||[]).includes(value)?value:spec.default;return A.sanitizeText(value,spec.maximum_characters||4000);}
  function newBatch(name='Untitled Data Batch',mold=A.getMold()){return {schema:'axm.data-batch/0.6',id:A.uid('axm.batch'),name:A.safeText(name,120),version:'0.6.0',batch_state:'DRAFT',mold_id:mold.id,source_format:'json',headers:[],rows:[],mapping:{controls:{},variants:{}},defaults:{controls:A.defaultControls(mold),variant:{...A.defaultVariant(mold),motion:'still',performance:'low'}},created_at:A.nowISO(),updated_at:A.nowISO(),provenance:{author:'Local AXM user',source:`${A.APP.name} v${A.APP.version} Data Batch Builder`,license:'user-controlled',rights_scope:'private-local',consent:'explicit local creation',transformation_history:['created as local data batch']}};}
  function getBatches(includeArchived=true){const list=A.storageRead(A.STORAGE.batches,[]);return includeArchived?list:list.filter(item=>item.batch_state!=='ARCHIVED');}
  function getBatch(id){return getBatches(true).find(item=>item.id===id)||null;}
  function materializeBatch(batch){
    const b=A.clone(batch),mold=A.findMold(b.mold_id);if(!mold)return [];
    const rows=assertLimit(Array.isArray(b.rows)?b.rows:[],MAX_ROWS,'Batch row count');
    return rows.map((row,index)=>{const controls={...A.defaultControls(mold),...(b.defaults?.controls||{})},variant={...A.defaultVariant(mold),...(b.defaults?.variant||{}),motion:'still',performance:'low'};Object.entries(b.mapping?.controls||{}).forEach(([key,column])=>{if(column&&mold.inputs?.[key])controls[key]=coerceInput(mold.inputs[key],row[column])});Object.entries(b.mapping?.variants||{}).forEach(([axis,column])=>{const value=column?row[column]:null;if(value!==null&&value!==undefined&&value!=='')variant[axis]=A.sanitizeText(value,80)});return {schema:'axm.batch-instance/0.6',id:A.uid('axm.batch.item'),row_index:index,mold_id:mold.id,label:A.safeText(row.title||row.name||row.label||`${b.name} ${index+1}`,120),controls,variant,source_row:A.clone(row)};});
  }
  function batchValidation(batch){
    const b=A.clone(batch||{}),checks=[],rows=Array.isArray(b.rows)?b.rows:[],mold=A.findMold(b.mold_id),intake=b.intake_report||{};
    checks.push(check(b.id&&b.name&&b.mold_id&&b.mapping?'PASS':'FAIL','Batch manifest',b.id&&b.name&&b.mold_id&&b.mapping?'Required batch fields are present.':'Batch requires id, name, mold_id, and mapping.'));
    checks.push(check(!rows.length||rows.length>MAX_ROWS?'FAIL':'PASS','Batch row count',!rows.length?'A batch needs at least one row.':rows.length>MAX_ROWS?`${rows.length} exceeds the ${MAX_ROWS}-row limit.`:`${rows.length}/${MAX_ROWS} accepted data rows.`));
    const truncated=Number(intake.truncated_count||0),renamed=(intake.renamed_headers||[]).length;
    checks.push(check(truncated?'FAIL':renamed?'WARN':'PASS','Intake transparency',truncated?`${truncated} source row(s) were omitted by the explicit ${MAX_ROWS}-row cap. Split the source and re-import; approval is blocked until every row is represented explicitly.`:renamed?`${renamed} header(s) were normalized or renamed explicitly; inspect the mapping before approval.`:`All ${Number(intake.total_rows??rows.length)} source rows were accepted without silent truncation.`));
    const acceptedFingerprint=A.fingerprintValue({headers:b.headers||[],rows,intake_report:intake}),fingerprintState=!b.accepted_fingerprint?'WARN':b.accepted_fingerprint===acceptedFingerprint?'PASS':'FAIL';
    checks.push(check(fingerprintState,'Accepted data fingerprint',fingerprintState==='PASS'?`Accepted headers, rows, and intake evidence match ${acceptedFingerprint}.`:fingerprintState==='WARN'?'No accepted-data fingerprint is recorded; save the batch once before approval.':`Accepted data changed after intake: expected ${b.accepted_fingerprint}, calculated ${acceptedFingerprint}.`));
    checks.push(check(!mold?'FAIL':!A.isMoldUsable(mold)?(b.batch_state==='ARCHIVED'?'WARN':'FAIL'):'PASS','Batch mold dependency',!mold?`Missing mold: ${b.mold_id}`:!A.isMoldUsable(mold)?'Batch mold is an inactive extension; approval is blocked until activation.':`${mold.name} is available.`));
    const headers=new Set(b.headers||[]),mapped=[...Object.values(b.mapping?.controls||{}),...Object.values(b.mapping?.variants||{})].filter(Boolean),missingColumns=[...new Set(mapped.filter(column=>!headers.has(column)))],mappedInputs=Object.values(b.mapping?.controls||{}).filter(Boolean).length;
    checks.push(check(missingColumns.length?'FAIL':!mappedInputs?'WARN':'PASS','Column mapping',missingColumns.length?`Mapped columns are missing: ${missingColumns.join(', ')}`:!mappedInputs?'No data columns map to mold inputs; rows will repeat defaults.':`${mappedInputs} input column(s) and ${mapped.length-mappedInputs} variant column(s) are mapped.`));
    const unsafe=[];rows.forEach((row,index)=>Object.entries(row||{}).forEach(([key,value])=>{if(unsafeScalar(value))unsafe.push(`${index+1}.${key}`)}));
    checks.push(check(unsafe.length?'FAIL':'PASS','Data-only intake',unsafe.length?`Remote or executable-looking values rejected at: ${unsafe.slice(0,10).join(', ')}`:'Rows contain local declarative scalar data only.'));
    const instances=mold&&rows.length<=MAX_ROWS?materializeBatch(b):[],fails=[],warnings=[],missingThemes=[];instances.forEach(item=>{const theme=A.findTheme(item.variant.theme);if(!theme||!A.isThemeUsable(theme)||!A.themeCompatibleWithMold(theme,mold)){missingThemes.push(item.row_index+1);return}if(V){const validation=V.validate(mold,item.controls,{...item.variant,motion:'still'},{reducedMotion:true,extraRegistry:A.getExtensions(true).filter(entry=>entry.id!==mold.id)});if(validation.summary.fail)fails.push(item.row_index+1);else if(validation.summary.warn)warnings.push(item.row_index+1)}});
    checks.push(check(missingThemes.length?'FAIL':fails.length?'FAIL':warnings.length?'WARN':'PASS','Materialized instances',missingThemes.length?`${missingThemes.length} row(s) resolve to unavailable themes.`:fails.length?`${fails.length} row(s) fail mold validation.`:warnings.length?`${warnings.length} row(s) carry validation warnings.`:`${instances.length} instances materialize cleanly.`));
    if(b.import_integrity)checks.push(check(b.import_integrity.status==='FAIL'?'FAIL':b.import_integrity.status==='MISSING'?'WARN':'PASS','Import integrity',b.import_integrity.status==='PASS'?'Imported batch package fingerprint was verified.':b.import_integrity.status==='MISSING'?'Imported batch package had no integrity fingerprint; batch remains DRAFT.':'Imported batch package fingerprint failed.'));
    checks.push(check(BATCH_STATES.has(b.batch_state)?'PASS':'FAIL','Batch state',BATCH_STATES.has(b.batch_state)?`Explicit state: ${b.batch_state}.`:`Unsupported state: ${b.batch_state}`));
    return report('axm.data-batch-validation/0.6',checks,{batch_id:b.id||null,row_count:rows.length,source_row_count:Number(intake.total_rows??rows.length),instance_count:instances.length});
  }
  function upsertBatch(batch){const list=getBatches(true),copy=A.clone(batch),index=list.findIndex(item=>item.id===copy.id),rows=assertLimit(Array.isArray(copy.rows)?copy.rows:[],MAX_ROWS,'Batch row count'),headers=assertLimit(Array.isArray(copy.headers)?copy.headers:[],MAX_COLUMNS,'Batch header count');if(new Set(headers).size!==headers.length)throw new Error('Batch headers contain duplicate names; nothing was saved or overwritten.');copy.schema='axm.data-batch/0.6';copy.version='0.6.0';copy.name=A.safeText(copy.name||'Untitled Data Batch',120);copy.rows=rows;copy.headers=headers;copy.batch_state=BATCH_STATES.has(copy.batch_state)?copy.batch_state:'DRAFT';copy.updated_at=A.nowISO();copy.accepted_fingerprint=A.fingerprintValue({headers:copy.headers,rows:copy.rows,intake_report:copy.intake_report||{}});if(index>=0){const previous=list[index],after=cleanBatchShell(copy);if(previous.batch_state==='APPROVED'&&A.fingerprintValue(approvalComparable(after,'batch_state'))!==previous.approved_fingerprint){copy.batch_state='DRAFT';delete copy.approved_at;delete copy.approved_fingerprint;}list[index]=copy;}else list.unshift(copy);copy.validation=batchValidation(copy);if(index>=0)list[index]=copy;else list[0]=copy;A.requireStorageWrite(A.STORAGE.batches,list);A.log(`Saved data batch ${copy.name}`,'PASS');window.dispatchEvent(new CustomEvent('axm:batch-change'));return copy;}
  function approveBatch(id){const batch=getBatch(id);if(!batch)throw new Error('Batch not found.');const validation=batchValidation(batch),dependency=validation.checks.find(item=>item.label==='Batch mold dependency');if(validation.summary.fail||dependency?.state!=='PASS')throw new Error('Batch approval blocked by validation failures or an inactive mold dependency.');const copy=A.clone(batch);copy.batch_state='APPROVED';copy.approved_at=A.nowISO();copy.approval_method='explicit-batch-builder-action';copy.approved_fingerprint=A.fingerprintValue(cleanBatchShell(copy));return upsertBatch(copy);}
  function archiveBatch(id){const batch=getBatch(id);if(!batch)throw new Error('Batch not found.');return upsertBatch({...batch,batch_state:'ARCHIVED',archived_at:A.nowISO()});}
  function batchDependencyRecords(batch){const mold=A.findMold(batch.mold_id),project={items:materializeBatch(batch),shared_theme:null};if(mold&&mold.source_kind==='extension'&&!project.items.length)project.items=[{mold_id:mold.id,variant:A.defaultVariant(mold)}];return projectDependencyRecords(project);}
  function batchPacket(batchOrId){const batch=typeof batchOrId==='string'?getBatch(batchOrId):A.clone(batchOrId);if(!batch)throw new Error('Batch not found.');return A.attachPacketIntegrity({schema:'axm.data-batch-package/0.6',version:'0.6.0',created_at:A.nowISO(),application:A.applicationMetadata(),batch:A.clone(batch),...batchDependencyRecords(batch),validation:batchValidation(batch)},'Batch package fingerprint covers source rows, column mapping, defaults, dependencies, state, and validation. Imported dependencies enter quarantine.');}
  function exportBatchPackage(batchOrId){const packet=batchPacket(batchOrId);A.downloadBlob(`${A.slugify(packet.batch.name)}.axmbatch.json`,JSON.stringify(packet,null,2)+'\n','application/json');return packet;}
  function remapBatch(batch,themeMap=new Map(),extensionMap=new Map(),origin='import'){const copy=A.clone(batch);copy.id=A.uid('axm.batch.imported');copy.schema='axm.data-batch/0.6';copy.version='0.6.0';copy.batch_state='DRAFT';copy.mold_id=extensionMap.get(copy.mold_id)||copy.mold_id;if(copy.defaults?.variant?.theme)copy.defaults.variant.theme=themeMap.get(copy.defaults.variant.theme)||copy.defaults.variant.theme;copy.imported_at=A.nowISO();copy.import_origin=A.safeText(origin,120);copy.imported_from_id=batch.id||null;delete copy.approved_at;delete copy.approved_fingerprint;return copy;}
  function importBatchPackage(raw){const packet=typeof raw==='string'?A.safeParseJSON(raw):A.clone(raw);if(!packet||packet.schema!=='axm.data-batch-package/0.6'||!packet.batch)throw new Error('Not a valid AXM data batch package.');assertLimit(Array.isArray(packet.batch.rows)?packet.batch.rows:[],MAX_ROWS,'Imported batch row count');assertLimit(Array.isArray(packet.batch.headers)?packet.batch.headers:[],MAX_COLUMNS,'Imported batch header count');const integrity=A.verifyPacketIntegrity(packet);if(integrity.status!=='PASS')throw new Error('Current batch packages require a valid integrity fingerprint.');const maps=importDependencyRecords(packet,'batch package'),batch=remapBatch(packet.batch,maps.themeMap,maps.extensionMap,'batch package');batch.import_integrity=integrity;return upsertBatch(batch);}
  function instancesHTML(name,description,instances,layout='gallery'){
    const safeInstances=assertLimit(Array.isArray(instances)?instances:[],MAX_ROWS,'Materialized instance count'),cards=safeInstances.map(item=>{const mold=activeMold(item.mold_id),theme=mold?A.findTheme(item.variant.theme):null,usable=mold&&theme&&A.isThemeUsable(theme)&&A.themeCompatibleWithMold(theme,mold);if(!usable)return `<article class="unresolved"><b>${A.escapeHTML(item.label)}</b><p>Unresolved dependency.</p></article>`;const canvas=R.renderCanvasForMold(mold,item.controls,{...item.variant,motion:'still',performance:'low'},.44),data=canvas.toDataURL('image/png');return `<article><img src="${data}" alt="${A.escapeHTML(item.label)}"><footer><b>${A.escapeHTML(item.label)}</b><span>${A.escapeHTML(mold.name)} · row ${item.row_index+1}</span></footer></article>`;}).join('');return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="generator" content="${A.escapeHTML(A.APP.name)} v${A.escapeHTML(A.APP.version)}"><title>${A.escapeHTML(name)}</title><style>body{margin:0;padding:26px;background:#070a10;color:#f3f7fb;font-family:system-ui}header{max-width:900px;margin:0 auto 22px}header p,footer span{color:#9fb0c2}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:14px}article{background:#111a28;border:1px solid #27384e;border-radius:18px;overflow:hidden}img{width:100%;height:280px;object-fit:contain;display:block;background:#05070b}footer{display:flex;justify-content:space-between;gap:10px;padding:12px 14px}.unresolved{padding:26px;border-color:#9f4d00}</style></head><body><header><h1>${A.escapeHTML(name)}</h1><p>${A.escapeHTML(description)} · ${safeInstances.length} materialized rows · static local export</p></header><main class="grid">${cards}</main></body></html>`;}
  function batchHTML(batchOrId){const batch=typeof batchOrId==='string'?getBatch(batchOrId):A.clone(batchOrId);if(!batch)throw new Error('Batch not found.');return instancesHTML(batch.name,`Data batch using ${batch.mold_id}`,materializeBatch(batch));}
  function exportBatchHTML(batchOrId){const batch=typeof batchOrId==='string'?getBatch(batchOrId):batchOrId,html=batchHTML(batch);A.downloadBlob(`${A.slugify(batch.name)}-data-gallery.html`,html,'text/html');return html;}
  function projectFromBatch(batchOrId,name=null){const batch=typeof batchOrId==='string'?getBatch(batchOrId):A.clone(batchOrId);if(!batch)throw new Error('Batch not found.');const validation=batchValidation(batch);if(validation.summary.fail)throw new Error('Project creation blocked until batch validation failures are repaired.');const project=newProject(name||`${batch.name} Project`,`Generated locally from data batch ${batch.id}.`,'gallery');project.items=materializeBatch(batch).map((item,index)=>normalizeProjectItem({...item,id:A.uid('axm.project.item'),order:index,note:`Source row ${index+1}`},index));project.provenance.transformation_history.push(`materialized from ${batch.id}`);return upsertProject(project,'create project from batch');}

  const baseHealth=A.healthReport.bind(A),baseWorkspace=A.workspacePacket.bind(A),baseImportWorkspace=A.importWorkspace.bind(A);
  A.healthReport=function(){const base=baseHealth(),copy=A.clone(base);delete copy.integrity;const projects=getProjects(true),batches=getBatches(true),projectIssues=projects.filter(item=>{const validation=projectValidation(item);return Boolean(validation.summary.fail)||(item.project_state==='APPROVED'&&validation.status!=='PASS')}).length,batchIssues=batches.filter(item=>{const validation=batchValidation(item);return Boolean(validation.summary.fail)||(item.batch_state==='APPROVED'&&validation.status!=='PASS')}).length;copy.schema='axm.health-report/0.6';copy.counts={...(copy.counts||{}),projects:projects.length,batches:batches.length};copy.checks=[...(copy.checks||[]),check(projectIssues?'FAIL':projects.some(item=>item.project_state==='DRAFT')?'WARN':'PASS','Visual project registry',projectIssues?`${projectIssues} project(s) fail validation or approved-readiness.`:projects.some(item=>item.project_state==='DRAFT')?`${projects.filter(item=>item.project_state==='DRAFT').length} project(s) remain draft.`:`${projects.length} project records are approved or archived cleanly.`),check(batchIssues?'FAIL':batches.some(item=>item.batch_state==='DRAFT')?'WARN':'PASS','Data batch registry',batchIssues?`${batchIssues} batch(es) fail validation or approved-readiness.`:batches.some(item=>item.batch_state==='DRAFT')?`${batches.filter(item=>item.batch_state==='DRAFT').length} batch(es) remain draft.`:`${batches.length} batch records are approved or archived cleanly.`),check(textBytes(projects)+textBytes(batches)>5_000_000?'WARN':'PASS','Assembly storage estimate',`${(textBytes(projects)+textBytes(batches)).toLocaleString()} approximate UTF-16 bytes used by projects and batches.`)];copy.summary=checksSummary(copy.checks);copy.status=copy.summary.fail?'FAIL':copy.summary.warn?'WARN':'PASS';return A.attachPacketIntegrity(copy,'Health report fingerprint includes protected core, local growth, projects, data batches, and assembly storage estimates.');};
  A.exportHealthReport=function(){const health=A.healthReport();A.downloadBlob(`axm-visual-foundry-health-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(health,null,2)+'\n','application/json');return health;};
  A.workspacePacket=function(){const base=baseWorkspace(),copy=A.clone(base);delete copy.integrity;copy.schema='axm.visual-workspace/0.6';copy.version='0.6.0';copy.application=A.applicationMetadata();copy.projects=getProjects(true);copy.batches=getBatches(true);return A.attachPacketIntegrity(copy,'Workspace fingerprint covers current state, themes, extensions, presets, candidates, snapshots, visual projects, data batches, and settings.');};
  A.exportWorkspace=function(){const packet=A.workspacePacket();A.downloadBlob(`axm-visual-workspace-${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(packet,null,2)+'\n','application/json');return packet;};
  A.importWorkspace=function(raw){const packet=typeof raw==='string'?A.safeParseJSON(raw):A.clone(raw),result=baseImportWorkspace(packet),themeMap=new Map(),extensionMap=new Map();A.getLocalThemes(true).filter(item=>item.import_origin==='workspace import'&&item.imported_from_id).forEach(item=>themeMap.set(item.imported_from_id,item.id));A.getExtensions(true).filter(item=>item.import_origin==='workspace import'&&item.imported_from_id).forEach(item=>extensionMap.set(item.imported_from_id,item.id));let projects=0,batches=0;for(const source of packet.projects||[]){try{upsertProject(remapProject(source,themeMap,extensionMap,'workspace import'),'workspace import');projects++;}catch(err){result.skipped=(result.skipped||0)+1;A.log(`Workspace project skipped: ${err.message}`,'WARN')}}for(const source of packet.batches||[]){try{upsertBatch(remapBatch(source,themeMap,extensionMap,'workspace import'));batches++;}catch(err){result.skipped=(result.skipped||0)+1;A.log(`Workspace batch skipped: ${err.message}`,'WARN')}}result.projects=projects;result.batches=batches;A.log(`Workspace assembly import: ${projects} projects, ${batches} batches.`,'PASS');window.dispatchEvent(new CustomEvent('axm:project-change'));window.dispatchEvent(new CustomEvent('axm:batch-change'));return result;};

  Object.assign(A,{PROJECT_STATES,BATCH_STATES,newProject,getProjects,getProject,projectValidation,upsertProject,addCurrentToProject,removeProjectItem,moveProjectItem,restoreProjectRevision,approveProject,archiveProject,projectPacket,exportProjectPackage,importProjectPackage,projectHTML,exportProjectHTML,parseDelimited,parseBatchSource,inferBatchMapping,newBatch,getBatches,getBatch,materializeBatch,batchValidation,upsertBatch,approveBatch,archiveBatch,batchPacket,exportBatchPackage,importBatchPackage,batchHTML,exportBatchHTML,projectFromBatch});
})();
