(() => {
  'use strict';
  const {clone,escapeHTML,slugify,downloadBlob,downloadDataURL}=window.AXM;
  const {renderCanvasForMold}=window.AXMRender;
  function packet(mold,controls,variant){const data={schema:'axm.render-packet/0.5',created_at:new Date().toISOString(),mold:clone(mold),instance:{controls:clone(controls),variant:clone(variant)},composition:window.AXMRender.describeComposition(mold),validation:window.AXMValidate.validate(mold,controls,variant,{reducedMotion:window.AXM.state.reducedMotion}),evidence:{renderer:'browser Canvas/SVG',engine_parity:'not claimed',local_first:true}};return window.AXM.attachPacketIntegrity(data,'Render packet fingerprint covers mold, controls, variant, composition, validation, and evidence.')}
  function exportJSON(mold,controls,variant){const data=packet(mold,controls,variant);downloadBlob(`${slugify(mold.name)}.json`,JSON.stringify(data,null,2)+'\n','application/json');return data}
  function xmlEscape(value){return String(value??'').replace(/[<>&"]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;'}[c]))}
  function svgLines(text,maxChars,maxLines){const words=String(text||'').trim().split(/\s+/),lines=[];let line='';for(const word of words){const next=line?`${line} ${word}`:word;if(next.length<=maxChars||!line)line=next;else{lines.push(line);line=word;if(lines.length>=maxLines-1)break}}if(line&&lines.length<maxLines)lines.push(line);if(lines.join(' ').split(' ').length<words.length&&lines.length)lines[lines.length-1]=lines.at(-1).slice(0,Math.max(1,maxChars-1))+'…';return lines}
  function svgLayoutMotif(layout,w,h,p,accent,pad){
    const rx=(n)=>Math.round(n*10)/10, stroke=p.line, soft=p.muted;
    const rect=(x,y,rw,rh,fill='none',s=stroke,rad=12)=>`<rect x="${rx(x)}" y="${rx(y)}" width="${rx(rw)}" height="${rx(rh)}" rx="${rx(rad)}" fill="${fill}" stroke="${s}"/>`;
    const circle=(x,y,r,fill='none',s=stroke)=>`<circle cx="${rx(x)}" cy="${rx(y)}" r="${rx(r)}" fill="${fill}" stroke="${s}"/>`;
    const line=(x1,y1,x2,y2,s=stroke,sw=2)=>`<path d="M${rx(x1)} ${rx(y1)}L${rx(x2)} ${rx(y2)}" stroke="${s}" stroke-width="${sw}" fill="none"/>`;
    const rightX=w*.59,rightY=h*.18,rightW=w*.31,rightH=h*.64;
    if(layout==='feature-grid')return `<g opacity=".9">${[0,1,2,3].map(i=>rect(rightX+(i%2)*rightW*.52,rightY+Math.floor(i/2)*rightH*.52,rightW*.45,rightH*.43,i===0?accent+'22':p.panel,i===0?accent:stroke,Math.min(w,h)*.022)).join('')}${circle(rightX+rightW*.22,rightY+rightH*.21,Math.min(w,h)*.035,accent,accent)}</g>`;
    if(layout==='case-study-proof')return `<g>${rect(rightX,rightY,rightW,rightH*.42,p.panel,stroke,18)}${rect(rightX,rightY+rightH*.52,rightW,rightH*.42,p.panel,accent,18)}${line(rightX+rightW*.12,rightY+rightH*.31,rightX+rightW*.82,rightY+rightH*.16,soft,4)}${line(rightX+rightW*.12,rightY+rightH*.80,rightX+rightW*.82,rightY+rightH*.61,accent,6)}<text x="${rightX+rightW*.08}" y="${rightY+rightH*.38}" fill="${soft}" font-family="system-ui" font-size="${Math.max(10,w*.011)}">BEFORE</text><text x="${rightX+rightW*.08}" y="${rightY+rightH*.90}" fill="${accent}" font-family="system-ui" font-size="${Math.max(10,w*.011)}">AFTER</text></g>`;
    if(layout==='event-beacon')return `<g transform="translate(${rightX+rightW*.5} ${rightY+rightH*.48})" filter="url(#glow)">${circle(0,0,rightW*.31,'none',accent)}${circle(0,0,rightW*.20,'none',p.accent_2)}${circle(0,0,rightW*.075,accent,accent)}${line(0,-rightH*.48,0,rightH*.48,stroke,2)}${line(-rightW*.48,0,rightW*.48,0,stroke,2)}</g>`;
    if(layout==='collaboration-call'||layout==='profile-network')return `<g>${[[.5,.18],[.18,.45],[.82,.45],[.34,.78],[.68,.78]].map(([xx,yy],i)=>circle(rightX+rightW*xx,rightY+rightH*yy,rightW*(i? .055:.075),i? p.panel:accent,i? p.accent_2:accent)).join('')}${[[.5,.18,.18,.45],[.5,.18,.82,.45],[.18,.45,.34,.78],[.82,.45,.68,.78],[.34,.78,.68,.78]].map(a=>line(rightX+rightW*a[0],rightY+rightH*a[1],rightX+rightW*a[2],rightY+rightH*a[3],stroke,2)).join('')}</g>`;
    if(layout==='dashboard-panel'||layout==='metric-pulse')return `<g>${[0,1,2].map(i=>rect(rightX,rightY+i*rightH*.29,rightW,rightH*.22,p.panel,i===0?accent:stroke,14)).join('')}<path d="M${rightX+rightW*.08} ${rightY+rightH*.72} C${rightX+rightW*.22} ${rightY+rightH*.48},${rightX+rightW*.38} ${rightY+rightH*.82},${rightX+rightW*.54} ${rightY+rightH*.56} S${rightX+rightW*.82} ${rightY+rightH*.44},${rightX+rightW*.92} ${rightY+rightH*.32}" fill="none" stroke="${accent}" stroke-width="5"/></g>`;
    if(layout==='settings-stack')return `<g>${[0,1,2,3,4].map(i=>`${rect(rightX,rightY+i*rightH*.18,rightW,rightH*.12,p.panel,stroke,10)}${rect(rightX+rightW*.74,rightY+rightH*(.035+i*.18),rightW*.16,rightH*.05,i%2? p.panel:accent,i%2?stroke:accent,rightH*.03)}`).join('')}</g>`;
    if(layout==='onboarding-flow')return `<g>${[0,1,2,3].map(i=>`${circle(rightX+rightW*(.12+i*.25),rightY+rightH*.48,rightW*.065,i===0?accent:p.panel,i===0?accent:stroke)}${i<3?line(rightX+rightW*(.185+i*.25),rightY+rightH*.48,rightX+rightW*(.305+i*.25),rightY+rightH*.48,i===0?accent:stroke,4):''}`).join('')}</g>`;
    if(layout==='command-console')return `<g>${rect(rightX,rightY,rightW,rightH,p.surface,accent,16)}${[0,1,2,3,4,5].map(i=>`<text x="${rightX+rightW*.08}" y="${rightY+rightH*(.15+i*.12)}" fill="${i===0?accent:soft}" font-family="ui-monospace,monospace" font-size="${Math.max(10,w*.0105)}">${i===0?'&gt; axm run proof':'status '+String(i).padStart(2,'0')+'  '+(i%2?'PASS':'READY')}</text>`).join('')}</g>`;
    if(layout==='alert-recovery'||layout==='boss-warning')return `<g>${rect(rightX,rightY,rightW,rightH*.40,accent+'18',accent,18)}<path d="M${rightX+rightW*.5} ${rightY+rightH*.08}L${rightX+rightW*.70} ${rightY+rightH*.34}H${rightX+rightW*.30}Z" fill="none" stroke="${accent}" stroke-width="5"/>${[0,1,2].map(i=>`${circle(rightX+rightW*.10,rightY+rightH*(.56+i*.14),rightW*.025,i===0?accent:p.panel,i===0?accent:stroke)}${line(rightX+rightW*.18,rightY+rightH*(.56+i*.14),rightX+rightW*.88,rightY+rightH*(.56+i*.14),i===0?accent:stroke,3)}`).join('')}</g>`;
    if(layout==='activity-timeline'||layout==='quest-ledger')return `<g>${line(rightX+rightW*.14,rightY+rightH*.08,rightX+rightW*.14,rightY+rightH*.92,stroke,4)}${[0,1,2,3,4].map(i=>`${circle(rightX+rightW*.14,rightY+rightH*(.12+i*.19),rightW*.033,i===0?accent:p.panel,i===0?accent:stroke)}${rect(rightX+rightW*.25,rightY+rightH*(.075+i*.19),rightW*.66,rightH*.09,p.panel,i===0?accent:stroke,8)}`).join('')}</g>`;
    if(layout==='mission-brief'||layout==='world-event')return `<g>${rect(rightX,rightY,rightW,rightH,p.panel,stroke,18)}<path d="M${rightX+rightW*.12} ${rightY+rightH*.78} C${rightX+rightW*.24} ${rightY+rightH*.38},${rightX+rightW*.48} ${rightY+rightH*.66},${rightX+rightW*.60} ${rightY+rightH*.30} S${rightX+rightW*.83} ${rightY+rightH*.18},${rightX+rightW*.88} ${rightY+rightH*.12}" fill="none" stroke="${accent}" stroke-width="5" stroke-dasharray="12 10"/>${circle(rightX+rightW*.12,rightY+rightH*.78,rightW*.035,accent,accent)}${circle(rightX+rightW*.88,rightY+rightH*.12,rightW*.055,p.panel,accent)}</g>`;
    if(layout==='character-dossier')return `<g>${circle(rightX+rightW*.32,rightY+rightH*.30,rightW*.13,p.panel,accent)}${rect(rightX+rightW*.14,rightY+rightH*.43,rightW*.36,rightH*.38,p.panel,stroke,18)}${[0,1,2,3].map(i=>`${line(rightX+rightW*.58,rightY+rightH*(.22+i*.16),rightX+rightW*.90,rightY+rightH*(.22+i*.16),stroke,6)}${line(rightX+rightW*.58,rightY+rightH*(.22+i*.16),rightX+rightW*(.68+i*.055),rightY+rightH*(.22+i*.16),i===0?accent:p.accent_2,6)}`).join('')}</g>`;
    if(layout==='loot-inspect')return `<g transform="translate(${rightX+rightW*.5} ${rightY+rightH*.38})" filter="url(#glow)"><path d="M0 ${-rightW*.22}L${rightW*.18} 0L0 ${rightW*.22}L${-rightW*.18} 0Z" fill="${accent}22" stroke="${accent}" stroke-width="5"/>${circle(0,0,rightW*.30,'none',stroke)}</g><g>${[0,1,2].map(i=>`${line(rightX+rightW*.12,rightY+rightH*(.72+i*.09),rightX+rightW*.88,rightY+rightH*(.72+i*.09),stroke,5)}${line(rightX+rightW*.12,rightY+rightH*(.72+i*.09),rightX+rightW*(.48+i*.12),rightY+rightH*(.72+i*.09),i===0?accent:p.accent_2,5)}`).join('')}</g>`;
    if(layout==='hud-status')return `<g>${rect(rightX,rightY,rightW,rightH,p.panel,stroke,18)}${[0,1,2].map(i=>`${rect(rightX+rightW*.10,rightY+rightH*(.12+i*.14),rightW*.80,rightH*.055,p.surface,stroke,rightH*.03)}${rect(rightX+rightW*.10,rightY+rightH*(.12+i*.14),rightW*(.68-i*.11),rightH*.055,i===0?accent:p.accent_2,i===0?accent:p.accent_2,rightH*.03)}`).join('')}${circle(rightX+rightW*.50,rightY+rightH*.70,rightW*.13,'none',accent)}${line(rightX+rightW*.35,rightY+rightH*.70,rightX+rightW*.65,rightY+rightH*.70,accent,3)}${line(rightX+rightW*.50,rightY+rightH*.55,rightX+rightW*.50,rightY+rightH*.85,accent,3)}</g>`;
    return '';
  }
  function cardSVG(controls,variant,mold=window.AXM.getMold()){
    const [w,h]=window.AXM.formatDimensions(variant.format),p=window.AXM.getTheme(variant.theme),pad=Math.max(26,w*.055),layout=mold.renderer_options?.layout||'editorial-split',accent=variant.state==='warning'?p.warning:variant.state==='success'?p.success:p.accent,title=svgLines(controls.title,w/h<.9?21:31,w/h<.9?4:3),message=svgLines(controls.message,w/h<.9?34:54,w/h<.9?6:4),titleSize=Math.max(24,Math.min(w*.066,h*.10)*(String(controls.title||'').length>60?.72:1)),lineHeight=titleSize*1.06,copyX=pad*1.32,copyY=pad*2.25,metric=xmlEscape(controls.metric||''),cta=xmlEscape(controls.cta||''),badge=xmlEscape(String(controls.badge||'AXM VISUAL MOLD').toUpperCase()),mediaX=w*(w/h<.9?.5:.77),mediaY=h*(w/h<.9?.68:.51),r=Math.min(w,h)*(w/h<.9?.22:.25),titleSpans=title.map((line,i)=>`<tspan x="${copyX}" dy="${i?lineHeight:0}">${xmlEscape(line)}</tspan>`).join(''),msgY=copyY+title.length*lineHeight+h*.055,msgSpans=message.map((line,i)=>`<tspan x="${copyX}" dy="${i?Math.max(20,h*.041):0}">${xmlEscape(line)}</tspan>`).join('');
    const motif=svgLayoutMotif(layout,w,h,p,accent,pad),special=motif|| (layout==='public-brief'?`<g transform="translate(${w-pad*2.2} ${pad*1.45})"><circle cx="0" cy="0" r="9" fill="${p.success}"/><circle cx="30" cy="0" r="9" fill="${p.accent}"/><circle cx="60" cy="0" r="9" fill="${p.accent_2}"/></g>`:`<g transform="translate(${mediaX} ${mediaY})"><circle r="${r*1.08}" fill="none" stroke="${p.line}" stroke-width="2"/><ellipse rx="${r*.78}" ry="${r*.52}" fill="none" stroke="${accent}" stroke-opacity=".58" stroke-width="5"/><ellipse rx="${r*.54}" ry="${r*.76}" fill="none" stroke="${p.accent_2}" stroke-opacity=".42" stroke-width="3"/><circle r="${r*.28}" fill="url(#core)" stroke="${p.text}" stroke-opacity=".4"/><g fill="${accent}">${[0,1,2,3,4,5,6,7].map(i=>{const a=i*Math.PI/4,x=Math.cos(a)*r*.92,y=Math.sin(a)*r*.68;return `<circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="${Math.max(3,r*.025)}" opacity="${i%2?.55:.85}"/>`}).join('')}</g></g>`);
    return `<?xml version="1.0" encoding="UTF-8"?><svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" role="img" aria-labelledby="title desc" data-layout="${xmlEscape(layout)}"><title id="title">${xmlEscape(controls.title)}</title><desc id="desc">${xmlEscape(controls.message)}</desc><defs><linearGradient id="bg" x1="0" y1="0" x2="1" y2="1"><stop stop-color="${p.surface}"/><stop offset=".55" stop-color="${p.surface_2}"/><stop offset="1" stop-color="${p.surface}"/></linearGradient><radialGradient id="core"><stop stop-color="${p.text}"/><stop offset=".14" stop-color="${accent}"/><stop offset=".62" stop-color="${p.accent_2}" stop-opacity=".62"/><stop offset="1" stop-color="${p.surface}" stop-opacity=".2"/></radialGradient><filter id="glow"><feGaussianBlur stdDeviation="${Math.max(2,Number(controls.glow||.2)*22)}" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><rect width="${w}" height="${h}" fill="url(#bg)"/><circle cx="${w*.72}" cy="${h*.34}" r="${Math.min(w,h)*.48}" fill="${accent}" opacity="${.035+Number(controls.energy||.5)*.08}"/><rect x="${pad}" y="${pad}" width="${w-pad*2}" height="${h-pad*2}" rx="${Math.min(w,h)*.055}" fill="${p.panel}" stroke="${p.line}"/><path d="M${pad*.65} ${pad*1.2}h${w*.06}M${w-pad*.65} ${pad*1.2}h-${w*.06}M${pad*.65} ${h-pad*1.2}h${w*.06}M${w-pad*.65} ${h-pad*1.2}h-${w*.06}" stroke="${p.line}"/><g filter="url(#glow)">${special}</g><text x="${copyX}" y="${pad*1.5}" fill="${p.text}" font-family="system-ui,sans-serif" font-size="${Math.max(11,w*.012)}" font-weight="700" letter-spacing="2">${badge}</text><text x="${copyX}" y="${copyY-h*.07}" fill="${accent}" font-family="system-ui,sans-serif" font-size="${Math.max(30,Math.min(w*.11,h*.15))}" font-weight="800">${metric}</text><text x="${copyX}" y="${copyY}" fill="${p.text}" font-family="system-ui,sans-serif" font-size="${titleSize}" font-weight="730">${titleSpans}</text><text x="${copyX}" y="${msgY}" fill="${p.muted}" font-family="system-ui,sans-serif" font-size="${Math.max(14,w*.018)}">${msgSpans}</text><text x="${copyX}" y="${h-pad*1.45}" fill="${accent}" font-family="system-ui,sans-serif" font-size="${Math.max(12,w*.015)}" font-weight="700">${cta}</text><text x="${w-pad*1.25}" y="${h-pad*.72}" text-anchor="end" fill="${p.muted}" font-family="system-ui,sans-serif" font-size="${Math.max(9,w*.009)}">${xmlEscape(mold.id)} · v${xmlEscape(mold.version)}</text></svg>`;
  }
  function exportSVG(mold,controls,variant){if(mold.renderer!=='card'||!mold.outputs.includes('svg'))throw new Error('SVG export is only declared for card-family molds.');const svg=cardSVG(controls,variant,mold);downloadBlob(`${slugify(mold.name)}-${variant.format}.svg`,svg,'image/svg+xml');return svg}
  function cardHTML(controls,variant,mold=window.AXM.getMold()){const svg=cardSVG(controls,variant,mold),app=window.AXM.APP;return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="generator" content="${escapeHTML(app.name)} v${escapeHTML(app.version)}"><title>${escapeHTML(controls.title)}</title><style>html,body{height:100%;margin:0}body{display:grid;place-items:center;background:${window.AXM.getTheme(variant.theme).surface};padding:3vw;box-sizing:border-box}svg{max-width:100%;max-height:94vh;filter:drop-shadow(0 30px 70px rgba(0,0,0,.48));border-radius:28px}@media(prefers-reduced-motion:reduce){*{animation:none!important}}</style></head><body>${svg.replace(/^<\?xml[^>]+>\s*/,'')}</body></html>`}
  function imageHTML(mold,controls,variant){const canvas=renderCanvasForMold(mold,controls,variant,1),data=canvas.toDataURL('image/png'),title=escapeHTML(mold.name),app=window.AXM.APP;return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="generator" content="${escapeHTML(app.name)} v${escapeHTML(app.version)}"><title>${title}</title><style>html,body{height:100%;margin:0;background:#06080d;color:#f3f7fb;font-family:system-ui}body{display:grid;place-items:center;padding:3vw;box-sizing:border-box}figure{margin:0;max-width:100%}img{display:block;max-width:100%;max-height:90vh;border-radius:20px;box-shadow:0 30px 100px rgba(0,0,0,.5)}figcaption{margin-top:12px;color:#a9b7c8;font-size:13px}</style></head><body><figure><img src="${data}" alt="${title} locally rendered preview"><figcaption>${title} · ${escapeHTML(variant.theme)} · ${escapeHTML(variant.format)} · ${escapeHTML(variant.performance)} · static local export · no engine parity claimed</figcaption></figure></body></html>`}
  function exportHTML(mold,controls,variant){const html=mold.renderer==='card'?cardHTML(controls,variant,mold):imageHTML(mold,controls,variant);downloadBlob(`${slugify(mold.name)}-${variant.format}.html`,html,'text/html');return html}
  function exportPNG(mold,controls,variant){const canvas=renderCanvasForMold(mold,controls,variant,1),data=canvas.toDataURL('image/png');downloadDataURL(`${slugify(mold.name)}-${variant.format}.png`,data);return data}
  function exportWebP(mold,controls,variant){const canvas=renderCanvasForMold(mold,controls,variant,1),data=canvas.toDataURL('image/webp',.92);if(!data.startsWith('data:image/webp'))throw new Error('This browser did not produce WebP; no mislabeled fallback file was downloaded. Use PNG instead.');downloadDataURL(`${slugify(mold.name)}-${variant.format}.webp`,data);return data}
  function proofCases(mold,controls,variant){
    const supported=mold.variants?.format||[],phone=supported.includes('phone')?'phone':supported[0],success=(mold.variants?.state||[]).includes('success')?'success':(mold.variants?.state||[])[0];
    const cases=[['Default',{},{}],['Long title',{title:'A deliberately long title that tests fitting, wrapping, safe areas, and readability protection across the entire composition.'},{}],['Short title',{title:'AXM.'},{}],['Missing media',{mediaData:null},{}],['Portrait',{}, {format:supported.includes('portrait')?'portrait':supported[0]}],['Square',{}, {format:supported.includes('square')?'square':supported[0]}],['Landscape',{}, {format:supported.includes('landscape')?'landscape':supported[0]}],['Phone / narrow',{}, {format:phone}],['Public calm',{}, {theme:'public-calm'}],['Aetherglass',{}, {theme:'aetherglass'}],['Low power',{}, {performance:'low',motion:'still'}],['Ultra',{}, {performance:'ultra'}],['Warning',{}, {state:'warning'}],['Reduced motion',{}, {motion:'still'}],['Success / fallback',{}, {state:success}],['Lineage',mold.inputs?.badge?{badge:`v${mold.version} · ${mold.lineage?.parent||'root'}`}:{},{}],['Dense content',{message:String(controls.message||'').repeat(2).slice(0,mold.inputs?.message?.maximum_characters||320),density:.9},{}],['Theme contract',{}, {theme:(mold.variants?.theme||[]).at(-1)||variant.theme}]];
    return cases.map(([label,c,v])=>({label,controls:{...controls,...c},variant:{...variant,...v}}));
  }
  function proofData(mold,controls,variant){return proofCases(mold,controls,variant).map(item=>{const canvas=renderCanvasForMold(mold,item.controls,{...item.variant,motion:'still',performance:item.variant.performance||'low'},.52);return {...item,data:canvas.toDataURL('image/png'),validation:window.AXMValidate.validate(mold,item.controls,item.variant,{reducedMotion:item.label==='Reduced motion'})}})}
  function exportProofHTML(mold,controls,variant){const data=proofData(mold,controls,variant),cards=data.map(item=>`<article data-status="${item.validation.status}"><img src="${item.data}" alt="${escapeHTML(item.label)} proof"><footer><b>${escapeHTML(item.label)}</b><span>${item.validation.status} · ${item.validation.summary.pass}/${item.validation.summary.warn}/${item.validation.summary.fail}</span></footer></article>`).join(''),html=`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHTML(mold.name)} Proof Sheet</title><style>body{margin:0;padding:28px;background:#070a10;color:#f3f7fb;font-family:system-ui}h1{font-size:clamp(24px,4vw,52px);margin:0 0 8px}p{color:#a9b7c8}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:12px;margin-top:22px}article{background:#111a28;border:1px solid rgba(255,255,255,.12);border-radius:14px;overflow:hidden}article[data-status=FAIL]{border-color:#ff876f}article[data-status=WARN]{border-color:#ffca6b}img{display:block;width:100%;aspect-ratio:16/10;object-fit:contain;background:#06080d}footer{display:flex;justify-content:space-between;gap:8px;padding:10px 12px;font-size:12px;color:#a9b7c8}</style></head><body><h1>${escapeHTML(mold.name)} Proof Sheet</h1><p>Version ${escapeHTML(mold.version)} · ${escapeHTML(mold.approval_state)} · ${escapeHTML(mold.source_kind)} · generated locally ${new Date().toISOString()}</p><div class="grid">${cards}</div></body></html>`;downloadBlob(`${slugify(mold.name)}-proof-sheet.html`,html,'text/html');return html}
  function exportProofPNG(mold,controls,variant){const cases=proofCases(mold,controls,variant),cols=3,tileW=480,tileH=350,header=100,out=document.createElement('canvas');out.width=cols*tileW;out.height=header+Math.ceil(cases.length/cols)*tileH;const ctx=out.getContext('2d');ctx.fillStyle='#070a10';ctx.fillRect(0,0,out.width,out.height);ctx.fillStyle='#f3f7fb';ctx.font='700 34px system-ui';ctx.fillText(`${mold.name} — Proof Sheet`,28,42);ctx.fillStyle='#a9b7c8';ctx.font='16px system-ui';ctx.fillText(`v${mold.version} · ${mold.source_kind} · ${new Date().toISOString()}`,28,72);cases.forEach((item,i)=>{const c=renderCanvasForMold(mold,item.controls,{...item.variant,motion:'still',performance:'low'},.46),col=i%cols,row=Math.floor(i/cols),x=col*tileW,y=header+row*tileH;ctx.fillStyle='#111a28';ctx.fillRect(x+8,y+8,tileW-16,tileH-16);const maxW=tileW-34,maxH=tileH-70,scale=Math.min(maxW/c.width,maxH/c.height),dw=c.width*scale,dh=c.height*scale;ctx.drawImage(c,x+(tileW-dw)/2,y+16,dw,dh);ctx.fillStyle='#f3f7fb';ctx.font='600 15px system-ui';ctx.fillText(item.label,x+18,y+tileH-25)});const data=out.toDataURL('image/png');downloadDataURL(`${slugify(mold.name)}-proof-sheet.png`,data);return data}
  function exportTokenPackage(mold,controls,variant){const data=window.AXM.attachPacketIntegrity({schema:'axm.visual-token-package/0.5',name:`${mold.name} token package`,exported_at:new Date().toISOString(),theme:clone(window.AXM.getTheme(variant.theme)),performance:variant.performance,tokens:clone(window.AXM.REG.tokens),instance_controls:clone(controls)},'Semantic token package fingerprint.');downloadBlob(`${slugify(mold.name)}-tokens.json`,JSON.stringify(data,null,2)+'\n','application/json');return data}
  function exportSkinManifest(mold,controls,variant){const data=window.AXM.attachPacketIntegrity({schema:'axm.living-skin/0.5',id:`${mold.id}.instance`,version:mold.version,parent:mold.id,semantic_controls:clone(controls),variant:clone(variant),theme:clone(window.AXM.getTheme(variant.theme)),adapter_status:{blender:'LOCAL VALIDATION REQUIRED',godot:'LOCAL VALIDATION REQUIRED',comfyui:'LOCAL VALIDATION REQUIRED',unity:'LOCAL VALIDATION REQUIRED',unreal:'LOCAL VALIDATION REQUIRED',materialx:'LOCAL VALIDATION REQUIRED'},provenance:clone(mold.provenance)},'Living skin manifest fingerprint; downstream parity remains unclaimed.');downloadBlob(`${slugify(mold.name)}-skin-manifest.json`,JSON.stringify(data,null,2)+'\n','application/json');return data}
  function exportMoldPackage(mold,controls,variant){const organIds=new Set(mold.organs||[]),data=window.AXM.attachPacketIntegrity({schema:'axm.mold-package/0.5',package_name:`${mold.id}.local-instance`,created_at:new Date().toISOString(),manifest:clone(mold),composition:window.AXMRender.describeComposition(mold),instance:{controls:clone(controls),variant:clone(variant)},organs:window.AXM.REG.organs.filter(o=>organIds.has(o.id)),theme:clone(window.AXM.getTheme(variant.theme)),tokens:clone(window.AXM.REG.tokens),validation:window.AXMValidate.validate(mold,controls,variant,{reducedMotion:window.AXM.state.reducedMotion}),adapter_scaffolds:clone(window.AXM.REG.adapters),readme:'Human-readable local package. Adapter scaffolds are not engine-validated and cross-engine pixel parity is not claimed. Family packages can capture related local presets, candidates, and snapshots separately.'},'Mold package fingerprint covers the complete local package.');downloadBlob(`${slugify(mold.name)}.axmmold.json`,JSON.stringify(data,null,2)+'\n','application/json');return data}
  function themeCSS(themeId){const t=window.AXM.getTheme(themeId);if(!t)throw new Error(`Theme not found: ${themeId}`);const vars=Object.entries(t).filter(([,value])=>typeof value==='string'&&(/^(#|rgba?\()/.test(value))).map(([key,value])=>`  --axm-${key.replaceAll('_','-')}: ${value};`).join('\n');return `/* ${window.AXM.APP.name} v${window.AXM.APP.version} · ${t.name} · semantic export */\n:root[data-axm-theme="${t.id}"], .axm-theme-${t.id} {\n${vars}\n  --axm-glass-strength: ${t.glass};\n  --axm-paper-noise: ${t.paper_noise};\n}\n`}
  function exportThemeCSS(mold,controls,variant){const css=themeCSS(variant.theme);downloadBlob(`axm-theme-${slugify(variant.theme)}.css`,css,'text/css');return css}
  function themeBookHTML(mold,controls,variant){
    const themes=window.AXM.variantValues(mold,'theme').map(id=>window.AXM.getTheme(id)).filter(Boolean);
    const sections=themes.map(theme=>{const itemVariant={...variant,theme:theme.id,motion:'still',performance:'low'};const canvas=renderCanvasForMold(mold,controls,itemVariant,.42);return `<article><header><div><h2>${escapeHTML(theme.name)}</h2><p>${escapeHTML(theme.material_language||'')}</p></div><div class="chips"><span>${escapeHTML(theme.id)}</span><span>${escapeHTML(theme.public_scope||'private')}</span></div></header><img src="${canvas.toDataURL('image/png')}" alt="${escapeHTML(theme.name)} preview"><div class="swatches"><span><i style="background:${theme.surface}"></i>surface</span><span><i style="background:${theme.panel}"></i>panel</span><span><i style="background:${theme.accent}"></i>accent</span><span><i style="background:${theme.accent_2}"></i>accent 2</span></div><p class="meta">Contrast target ${escapeHTML(String(theme.contrast_target))} · motion ${escapeHTML(theme.motion_character||'steady')}</p></article>`;}).join('');
    return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHTML(mold.name)} Theme Book</title><style>body{margin:0;padding:28px;background:#070a10;color:#eff5fb;font-family:system-ui}h1{margin:0 0 10px;font-size:clamp(24px,4vw,48px)}p.lead{color:#9eb0c5;max-width:70ch}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:16px;margin-top:22px}article{background:#111a28;border:1px solid #243347;border-radius:18px;overflow:hidden}header{display:flex;justify-content:space-between;gap:10px;padding:14px 14px 8px}header h2{margin:0 0 6px;font-size:20px}header p{margin:0;color:#9eb0c5;font-size:13px}.chips{display:flex;gap:8px;flex-wrap:wrap;align-content:flex-start}.chips span{font-size:12px;border:1px solid #33455b;border-radius:999px;padding:4px 8px;color:#c8d3df}img{display:block;width:100%;height:240px;object-fit:contain;background:#05080d}.swatches{display:flex;flex-wrap:wrap;gap:10px;padding:12px 14px 6px}.swatches span{display:inline-flex;align-items:center;gap:8px;font-size:12px;color:#b9c7d5}.swatches i{display:inline-block;width:18px;height:18px;border-radius:6px;border:1px solid rgba(255,255,255,.16)}.meta{padding:0 14px 16px;color:#90a4b9;font-size:13px}</style></head><body><h1>${escapeHTML(mold.name)} — Theme Book</h1><p class="lead">Governed theme preview book generated locally. One mold is rendered across all declared semantic themes so you can compare material language, contrast targets, and public scope without touching the parent mold.</p><div class="grid">${sections}</div></body></html>`
  }
  function exportThemeBook(mold,controls,variant){const html=themeBookHTML(mold,controls,variant);downloadBlob(`${slugify(mold.name)}-theme-book.html`,html,'text/html');return html}
  function batchPlan(mold,variant){const themes=window.AXM.variantValues(mold,'theme').slice(0,6),formats=(mold.variants?.format||[]).slice(0,5);return themes.flatMap(theme=>formats.map(format=>({theme,format,motion:'still',performance:'low',state:(mold.variants?.state||[])[0]}))).slice(0,24)}
  function batchGalleryHTML(mold,controls,variant){const plan=batchPlan(mold,variant),cards=plan.map(item=>{const canvas=renderCanvasForMold(mold,controls,item,.42);return `<article><img src="${canvas.toDataURL('image/png')}" alt="${escapeHTML(item.theme)} ${escapeHTML(item.format)}"><footer><b>${escapeHTML(item.theme)}</b><span>${escapeHTML(item.format)}</span></footer></article>`}).join('');return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escapeHTML(mold.name)} Batch Gallery</title><style>body{margin:0;padding:24px;background:#06080d;color:#f4f8fb;font-family:system-ui}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:14px}article{background:#111a28;border:1px solid #26364c;border-radius:16px;overflow:hidden}img{width:100%;height:250px;object-fit:contain;display:block}footer{display:flex;justify-content:space-between;padding:10px 12px;color:#b8c5d3}</style></head><body><h1>${escapeHTML(mold.name)} — Batch Gallery</h1><p>${plan.length} governed combinations · still · low-power render · generated ${new Date().toISOString()}</p><div class="grid">${cards}</div></body></html>`}
  function exportBatchGallery(mold,controls,variant){const html=batchGalleryHTML(mold,controls,variant);downloadBlob(`${slugify(mold.name)}-batch-gallery.html`,html,'text/html');return html}
  function exportersFor(mold){const list=[['json','JSON','Manifest, composition, controls, variants, validation, and evidence.'],['html','HTML','Self-contained local visual output.'],['png','PNG','Canvas-rendered image.'],['webp','WebP','Compressed browser-rendered image where supported.'],['proof-html','Proof HTML','Eighteen-case proof sheet with validation status.'],['proof-png','Proof PNG','Single image proof sheet.'],['mold-package','Mold package','Manifest + organs + theme + tokens + validation.'],['theme-css','Theme CSS','Semantic CSS custom properties for the selected theme.'],['theme-book','Theme book','One mold rendered across all declared themes with semantic swatches and notes.'],['family-package','Family package','Focused mold plus related local themes, presets, candidates, extensions, snapshots, and proof context.'],['health-report','Health report','Protected-core integrity, local theme and extension state, dependency resolution, and storage estimate.'],['intake-readiness','Intake readiness','Evidence-based readiness gate with blocking and local-validation findings.'],['intake-handoff','Local-intake handoff','Workspace, readiness, health, audit, core evidence, rescue summaries, and adapter status.'],['safety-capsule','Safety capsule','Workspace plus raw managed storage for staged, rescue-protected restoration.'],['workspace','Workspace backup','Portable local themes, presets, candidates, extensions, snapshots, settings, and current state.']];if(mold.source_kind==='extension')list.splice(list.length-1,0,['extension-package','Extension package','Portable extension manifest with dependencies, validation, and integrity fingerprint.']);if(mold.outputs.includes('svg'))list.splice(2,0,['svg','SVG','Scalable card-family export.']);if(mold.outputs.includes('token-package'))list.push(['token-package','Token package','Semantic token and theme package.']);if(mold.outputs.includes('skin-manifest'))list.push(['skin-manifest','Skin manifest','Portable material contract with honest adapter status.']);if(mold.outputs.includes('batch-gallery'))list.push(['batch-gallery','Batch gallery','Up to twenty-four governed theme/format combinations.']);return list}
  function run(type,mold,controls,variant){const map={json:exportJSON,html:exportHTML,svg:exportSVG,png:exportPNG,webp:exportWebP,'proof-html':exportProofHTML,'proof-png':exportProofPNG,'token-package':exportTokenPackage,'skin-manifest':exportSkinManifest,'mold-package':exportMoldPackage,'theme-css':exportThemeCSS,'theme-book':exportThemeBook,'family-package':()=>window.AXM.exportFamilyPackage(mold,controls,variant),'extension-package':()=>window.AXM.exportExtensionPackage(mold),'health-report':()=>window.AXM.exportHealthReport(),'intake-readiness':()=>window.AXM.exportIntakeReadinessReport(),'intake-handoff':()=>window.AXM.exportIntakeHandoffPacket(),'safety-capsule':()=>window.AXM.exportSafetyCapsule(),'batch-gallery':exportBatchGallery,workspace:()=>window.AXM.exportWorkspace()};if(!map[type])throw new Error(`Unknown export: ${type}`);return map[type](mold,controls,variant)}
  window.AXMExport={packet,svgLayoutMotif,cardSVG,cardHTML,imageHTML,exportJSON,exportHTML,exportSVG,exportPNG,exportWebP,proofCases,proofData,exportProofHTML,exportProofPNG,exportTokenPackage,exportSkinManifest,exportMoldPackage,themeCSS,exportThemeCSS,themeBookHTML,exportThemeBook,batchPlan,batchGalleryHTML,exportBatchGallery,exportersFor,run};
})();
