(() => {
  'use strict';
  const animations=new Map();

  function theme(id){
    const t=window.AXM.getTheme(id);
    return t || {id:'fallback',surface:'#06080d',surface_2:'#111a28',panel:'rgba(17,26,40,.88)',text:'#f3f7fb',muted:'#a9b7c8',accent:'#65edff',accent_2:'#9b7cff',warning:'#ffb45e',success:'#6dffba',line:'rgba(101,237,255,.3)',shadow:'rgba(0,0,0,.55)',glow_rgb:'101,237,255',paper_noise:0,glass:.5};
  }
  const PALETTES=new Proxy({}, {get:(_,key)=>theme(key)});
  function palette(id){return theme(id)}
  function rgba(hex,a){
    const rgb=window.AXM.hexToRgb(hex); return rgb?`rgba(${rgb.r},${rgb.g},${rgb.b},${a})`:hex;
  }
  function roundedRect(ctx,x,y,w,h,r){
    const rr=Math.max(0,Math.min(r,w/2,h/2));ctx.beginPath();ctx.moveTo(x+rr,y);ctx.arcTo(x+w,y,x+w,y+h,rr);ctx.arcTo(x+w,y+h,x,y+h,rr);ctx.arcTo(x,y+h,x,y,rr);ctx.arcTo(x,y,x+w,y,rr);ctx.closePath();
  }
  function line(ctx,x1,y1,x2,y2,width,stroke){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.lineWidth=width;ctx.strokeStyle=stroke;ctx.stroke()}
  function wrapLines(ctx,text,maxWidth,maxLines=6){
    const words=String(text??'').replace(/\s+/g,' ').trim().split(' ').filter(Boolean),lines=[];let current='';
    for(const word of words){const test=current?`${current} ${word}`:word;if(ctx.measureText(test).width<=maxWidth||!current)current=test;else{lines.push(current);current=word;if(lines.length===maxLines-1)break}}
    if(current&&lines.length<maxLines)lines.push(current);
    const used=lines.join(' ').split(' ').length;if(used<words.length&&lines.length){let last=lines.at(-1);while(last.length>1&&ctx.measureText(`${last}…`).width>maxWidth)last=last.slice(0,-1);lines[lines.length-1]=`${last.trim()}…`}
    return lines;
  }
  function fittedTitleSize(text,w,h){
    const n=String(text||'').length,base=Math.min(w*.075,h*.115);return Math.max(Math.min(base,n>92?base*.48:n>70?base*.58:n>48?base*.72:n>28?base*.86:base),18);
  }
  function seededNoise(seed){let s=seed>>>0;return()=>{s=(s*1664525+1013904223)>>>0;return s/4294967296}}
  function hashSeed(text){let h=2166136261;for(const c of String(text)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
  function formatCanvas(canvas,variant,scale=1){const [w,h]=window.AXM.formatDimensions(variant.format);canvas.width=Math.round(w*scale);canvas.height=Math.round(h*scale);canvas.style.aspectRatio=`${w}/${h}`;return [canvas.width,canvas.height]}
  function stateAccent(p,variant){return variant.state==='warning'?p.warning:variant.state==='success'?p.success:p.accent}
  function drawBackdrop(ctx,w,h,p,energy=.5,density=.4,time=0,performance='standard'){
    const bg=ctx.createLinearGradient(0,0,w,h);bg.addColorStop(0,p.surface);bg.addColorStop(.55,p.surface_2);bg.addColorStop(1,p.surface);ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);
    const glow=ctx.createRadialGradient(w*(.72+Math.sin(time*.0002)*.03),h*.36,0,w*.7,h*.38,w*.72);glow.addColorStop(0,`rgba(${p.glow_rgb},${.11+.22*energy})`);glow.addColorStop(.45,`rgba(${p.glow_rgb},${.04+.08*energy})`);glow.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=glow;ctx.fillRect(0,0,w,h);
    const lines=performance==='low'?5:performance==='ultra'?18:10;ctx.save();ctx.globalAlpha=.18+density*.16;for(let i=0;i<lines;i++){const y=h*(.12+i/(lines+1));line(ctx,-w*.04,y,w*1.04,y-w*.08,Math.max(1,w*.0008),p.line)}ctx.restore();
    if(p.paper_noise>0&&performance!=='low'){const rnd=seededNoise(hashSeed(p.id));ctx.save();ctx.globalAlpha=p.paper_noise*.42;ctx.fillStyle=p.text;const dots=Math.floor((performance==='ultra'?480:190)*p.paper_noise);for(let i=0;i<dots;i++){const s=1+rnd()*2;ctx.fillRect(rnd()*w,rnd()*h,s,s)}ctx.restore()}
  }
  function drawCornerMarks(ctx,w,h,p,pad){ctx.save();ctx.strokeStyle=p.line;ctx.lineWidth=Math.max(1,w*.0015);const s=Math.min(w,h)*.05;[[pad,pad,1,1],[w-pad,pad,-1,1],[pad,h-pad,1,-1],[w-pad,h-pad,-1,-1]].forEach(([x,y,dx,dy])=>{line(ctx,x,y,x+dx*s,y,ctx.lineWidth,p.line);line(ctx,x,y,x,y+dy*s,ctx.lineWidth,p.line)});ctx.restore()}
  function fillTextLines(ctx,lines,x,y,lineHeight,fill){ctx.fillStyle=fill;lines.forEach((text,i)=>ctx.fillText(text,x,y+i*lineHeight));}
  function drawBadge(ctx,text,x,y,p,scale=1){ctx.font=`700 ${Math.max(10,13*scale)}px system-ui`;const width=ctx.measureText(text).width+28*scale;roundedRect(ctx,x,y-18*scale,width,30*scale,15*scale);ctx.fillStyle=rgba(p.accent,.12);ctx.fill();ctx.strokeStyle=p.line;ctx.lineWidth=1;ctx.stroke();ctx.fillStyle=p.text;ctx.letterSpacing='2px';ctx.fillText(text,x+14*scale,y+2*scale);return width}
  function drawOrbitalMedia(ctx,cx,cy,r,p,controls,variant,time=0,mode='orbital-window'){
    const energy=window.AXM.clamp(controls.energy??.5),glow=window.AXM.clamp(controls.glow??.25,0,.8),accent=stateAccent(p,variant),perf=variant.performance;
    ctx.save();ctx.translate(cx,cy);
    const halo=ctx.createRadialGradient(0,0,r*.1,0,0,r*1.25);halo.addColorStop(0,rgba(accent,.26+.22*energy));halo.addColorStop(.5,rgba(p.accent_2,.09+.12*glow));halo.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=halo;ctx.fillRect(-r*1.4,-r*1.4,r*2.8,r*2.8);
    const rings=perf==='low'?3:perf==='ultra'?8:5;for(let i=0;i<rings;i++){const rr=r*(.42+i*.115);ctx.beginPath();if(mode==='arena-core'){ctx.rect(-rr,-rr,rr*2,rr*2)}else if(mode==='evidence-window'){roundedRect(ctx,-rr,-rr*.72,rr*2,rr*1.44,rr*.22)}else{ctx.ellipse(0,0,rr,rr*(mode==='portal-window'?1.12:.78),time*.00008*(i%2?1:-1),0,Math.PI*2)}ctx.strokeStyle=i%2?rgba(p.accent_2,.20+i*.025):rgba(accent,.24+i*.025);ctx.lineWidth=Math.max(1,r*.009);ctx.stroke()}
    const core=ctx.createRadialGradient(-r*.12,-r*.2,0,0,0,r*.46);core.addColorStop(0,p.text);core.addColorStop(.09,accent);core.addColorStop(.45,rgba(p.accent_2,.52));core.addColorStop(1,rgba(p.surface,.2));ctx.fillStyle=core;ctx.beginPath();if(mode==='data-core'){for(let i=0;i<6;i++){const a=-Math.PI/2+i*Math.PI/3,rr=i%2?r*.44:r*.58;const x=Math.cos(a)*rr,y=Math.sin(a)*rr;i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.closePath()}else{ctx.arc(0,0,r*.34,0,Math.PI*2)}ctx.fill();ctx.strokeStyle=rgba(p.text,.45);ctx.lineWidth=Math.max(1,r*.01);ctx.stroke();
    const markers=perf==='ultra'?18:perf==='low'?6:11;for(let i=0;i<markers;i++){const a=i/markers*Math.PI*2+time*.00012*(i%2?1:-1),rr=r*(.65+(i%3)*.10);ctx.fillStyle=i%2?accent:p.accent_2;ctx.globalAlpha=.42+.35*(i%3)/2;ctx.beginPath();ctx.arc(Math.cos(a)*rr,Math.sin(a)*rr,Math.max(1,r*.018*(1+(i%2))),0,Math.PI*2);ctx.fill()}
    ctx.restore();
  }
  const CARD_LAYOUTS=new Set([
    'editorial-split','public-brief','milestone-ledger','game-signal','service-stage',
    'feature-grid','case-study-proof','event-beacon','collaboration-call',
    'dashboard-panel','settings-stack','onboarding-flow','command-console','alert-recovery','metric-pulse','activity-timeline','profile-network',
    'mission-brief','character-dossier','loot-inspect','quest-ledger','boss-warning','world-event','hud-status'
  ]);
  function panelBox(ctx,x,y,w,h,p,{accent=null,alpha=.055,radius=null}={}){
    roundedRect(ctx,x,y,w,h,radius??Math.min(w,h)*.12);ctx.fillStyle=accent?rgba(accent,alpha):rgba(p.text,alpha);ctx.fill();ctx.strokeStyle=accent?rgba(accent,.30):p.line;ctx.lineWidth=Math.max(1,w*.004);ctx.stroke();
  }
  function progressBar(ctx,x,y,w,h,value,p,accent=null){
    const color=accent||p.accent;roundedRect(ctx,x,y,w,h,h/2);ctx.fillStyle=rgba(p.text,.075);ctx.fill();roundedRect(ctx,x,y,w*window.AXM.clamp(value),h,h/2);ctx.fillStyle=color;ctx.fill();
  }
  function drawMicroLabel(ctx,text,x,y,p,size=12,align='left'){
    ctx.textAlign=align;ctx.fillStyle=p.muted;ctx.font=`700 ${Math.max(10,size)}px system-ui`;ctx.fillText(String(text).toUpperCase(),x,y);ctx.textAlign='left';
  }
  function drawMiniSparkline(ctx,x,y,w,h,p,accent,seedText='spark'){
    const rnd=seededNoise(hashSeed(seedText));ctx.beginPath();for(let i=0;i<12;i++){const px=x+w*i/11,py=y+h*(.72-(.18+i*.032+rnd()*.22)% .62);i?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.strokeStyle=accent;ctx.lineWidth=Math.max(2,w*.006);ctx.stroke();line(ctx,x,y+h,x+w,y+h,1,p.line);
  }
  function titleLines(ctx,title,x,y,w,h,p,{maxLines=3,scale=.82,fill=null}={}){
    const size=fittedTitleSize(title,w,h)*scale;ctx.font=`740 ${size}px system-ui`;const lines=wrapLines(ctx,title,w,maxLines);fillTextLines(ctx,lines,x,y,Math.max(24,size*1.06),fill||p.text);return {lines,size,bottom:y+lines.length*Math.max(24,size*1.06)};
  }
  function messageLines(ctx,message,x,y,w,h,p,{maxLines=5,size=null}={}){
    const fontSize=size||Math.max(13,w*.026);ctx.font=`430 ${fontSize}px system-ui`;const lines=wrapLines(ctx,message,w,maxLines);fillTextLines(ctx,lines,x,y,Math.max(19,fontSize*1.45),p.muted);return {lines,bottom:y+lines.length*Math.max(19,fontSize*1.45)};
  }
  function drawCardCanvas(canvas,controls,variant,scale=1,mold=window.AXM.getMold()){
    const [w,h]=formatCanvas(canvas,variant,scale),ctx=canvas.getContext('2d'),p=theme(variant.theme),energy=window.AXM.clamp(controls.energy??.5),density=window.AXM.clamp(controls.density??.42),depth=window.AXM.clamp(controls.depth??.55),glow=window.AXM.clamp(controls.glow??.25,0,.8),layout=mold?.renderer_options?.layout||'editorial-split';
    drawBackdrop(ctx,w,h,p,energy,density,0,variant.performance);const pad=Math.max(22,w*.055);drawCornerMarks(ctx,w,h,p,pad*.65);
    ctx.save();ctx.shadowColor=`rgba(${p.glow_rgb},${.16+.38*glow})`;ctx.shadowBlur=(variant.performance==='low'?8:variant.performance==='ultra'?42:24)*scale;
    roundedRect(ctx,pad,pad,w-pad*2,h-pad*2,Math.min(w,h)*.055);ctx.fillStyle=p.panel;ctx.fill();ctx.strokeStyle=p.line;ctx.lineWidth=Math.max(1,w*.0015);ctx.stroke();ctx.restore();
    const accent=stateAccent(p,variant),portrait=h>w*1.12,phone=variant.format==='phone',x0=pad*1.35,y0=pad*1.45,iw=w-pad*2.7,ih=h-pad*2.9;
    const title=String(controls.title||mold.name),message=String(controls.message||''),badge=String(controls.badge||'AXM VISUAL MOLD').toUpperCase(),metric=String(controls.metric||''),cta=String(controls.cta||'');

    if(layout==='public-brief'){
      const x=pad*1.45,y=pad*1.55,maxW=w-pad*2.9;drawBadge(ctx,badge,x,y,p,scale);ctx.fillStyle=accent;ctx.font=`760 ${Math.min(w*.12,h*.13)}px system-ui`;ctx.fillText(metric,x,y+h*.17);ctx.font=`720 ${fittedTitleSize(title,maxW,h)*.84}px system-ui`;const tl=wrapLines(ctx,title,maxW,3);fillTextLines(ctx,tl,x,y+h*.30,Math.min(w*.072,h*.08),p.text);ctx.font=`430 ${Math.max(14,w*.019)}px system-ui`;const ml=wrapLines(ctx,message,maxW,6);fillTextLines(ctx,ml,x,y+h*.30+tl.length*Math.min(w*.072,h*.08)+h*.055,Math.max(21,h*.043),p.muted);const by=h-pad*1.55;roundedRect(ctx,x,by-h*.075,maxW,h*.075,h*.018);ctx.fillStyle=rgba(accent,.09);ctx.fill();ctx.strokeStyle=p.line;ctx.stroke();ctx.font=`650 ${Math.max(12,w*.015)}px system-ui`;ctx.fillStyle=accent;ctx.fillText(cta,x+18*scale,by-h*.028);for(let i=0;i<3;i++){const cx=w-pad*1.65-i*h*.075,cy=y+h*.08;ctx.beginPath();ctx.arc(cx,cy,h*.015,0,Math.PI*2);ctx.fillStyle=i===0?p.success:i===1?p.accent:p.accent_2;ctx.fill()}
    } else if(layout==='milestone-ledger'){
      const x=pad*1.3,y=pad*1.45;drawBadge(ctx,badge,x,y,p,scale);ctx.font=`800 ${Math.min(w*.16,h*.22)}px system-ui`;ctx.fillStyle=accent;ctx.fillText(metric,x,y+h*.25);ctx.font=`730 ${fittedTitleSize(title,w*.57,h)*.73}px system-ui`;const tl=wrapLines(ctx,title,w*.56,4);fillTextLines(ctx,tl,x,y+h*.39,Math.min(w*.06,h*.075),p.text);ctx.font=`430 ${Math.max(13,w*.016)}px system-ui`;const ml=wrapLines(ctx,message,w*.56,5);fillTextLines(ctx,ml,x,y+h*.39+tl.length*Math.min(w*.06,h*.075)+h*.045,Math.max(19,h*.038),p.muted);const bx=w*.69,top=y+h*.10,bw=w*.22;for(let i=0;i<5;i++){const yy=top+i*h*.105;ctx.fillStyle=p.muted;ctx.globalAlpha=.65;ctx.font=`650 ${Math.max(10,w*.012)}px system-ui`;ctx.fillText(['STRUCTURE','ORGANS','PROOF','LINEAGE','ROLLBACK'][i],bx,yy);ctx.globalAlpha=1;progressBar(ctx,bx,yy+h*.025,bw,h*.018,.52+i*.1,p,i===4?p.success:accent)}ctx.font=`650 ${Math.max(12,w*.014)}px system-ui`;ctx.fillStyle=accent;ctx.fillText(cta,bx,top+h*.58)
    } else if(layout==='feature-grid'){
      drawBadge(ctx,badge,x0,y0,p,scale);const top=titleLines(ctx,title,x0,y0+h*.16,portrait?iw:iw*.56,h,p,{maxLines:portrait?3:2,scale:.72});messageLines(ctx,message,x0,top.bottom+h*.025,portrait?iw:iw*.55,h,p,{maxLines:portrait?4:5,size:Math.max(13,w*(portrait?.026:.015))});ctx.fillStyle=accent;ctx.font=`800 ${Math.max(26,Math.min(w,h)*.10)}px system-ui`;ctx.fillText(metric,portrait?x0:w*.72,y0+h*.15);
      const gx=portrait?x0:w*.62,gy=portrait?h*.55:y0+h*.27,cols=2,rows=2,gap=Math.min(w,h)*.025,gw=(portrait?iw:iw*.35),gh=(h-pad*1.6-gy),cellW=(gw-gap)/2,cellH=(gh-gap)/2;['PROMISE','PROOF','COMPATIBILITY','NEXT ACTION'].forEach((label,i)=>{const cx=gx+(i%cols)*(cellW+gap),cy=gy+Math.floor(i/cols)*(cellH+gap);panelBox(ctx,cx,cy,cellW,cellH,p,{accent:i===3?p.success:accent,alpha:.07});drawMicroLabel(ctx,label,cx+cellW*.08,cy+cellH*.26,p,Math.max(10,w*.011));progressBar(ctx,cx+cellW*.08,cy+cellH*.55,cellW*.84,Math.max(5,cellH*.06),.48+i*.13,p,i===3?p.success:accent)});
    } else if(layout==='case-study-proof'){
      drawBadge(ctx,badge,x0,y0,p,scale);ctx.fillStyle=accent;ctx.font=`820 ${Math.max(34,Math.min(w,h)*.16)}px system-ui`;ctx.fillText(metric,x0,y0+h*.22);const top=titleLines(ctx,title,x0,y0+h*.34,portrait?iw:iw*.48,h,p,{maxLines:3,scale:.68});messageLines(ctx,message,x0,top.bottom+h*.025,portrait?iw:iw*.48,h,p,{maxLines:5,size:Math.max(13,w*(portrait?.026:.015))});const bx=portrait?x0:w*.59,by=portrait?h*.61:y0+h*.11,bw=portrait?iw:iw*.34,bh=portrait?h*.25:h*.55;['BEFORE','AFTER'].forEach((label,i)=>{const yy=by+i*(bh*.45);drawMicroLabel(ctx,label,bx,yy,p,Math.max(10,w*.012));progressBar(ctx,bx,yy+bh*.10,bw,bh*.09,i?.86:.38,p,i?p.success:p.warning)});panelBox(ctx,bx,by+bh*.78,bw,bh*.20,p,{accent,alpha:.06});drawMicroLabel(ctx,'SOURCE · METHOD · CONSTRAINTS',bx+bw*.05,by+bh*.90,p,Math.max(9,w*.010));ctx.fillStyle=accent;ctx.font=`680 ${Math.max(11,w*.013)}px system-ui`;ctx.fillText(cta,bx,Math.min(h-pad*1.2,by+bh*1.10));
    } else if(layout==='event-beacon'){
      drawBadge(ctx,badge,x0,y0,p,scale);const cx=w*.5,cy=portrait?h*.47:h*.43,r=Math.min(w,h)*(portrait?.21:.23);drawOrbitalMedia(ctx,cx,cy,r,p,controls,variant,0,'portal-window');ctx.textAlign='center';ctx.fillStyle=accent;ctx.font=`850 ${Math.max(34,r*.42)}px system-ui`;ctx.fillText(metric,cx,cy+r*.08);ctx.font=`760 ${Math.max(25,Math.min(w*.075,h*.075))}px system-ui`;const tl=wrapLines(ctx,title,iw,3);tl.forEach((lineText,i)=>ctx.fillText(lineText,cx,portrait?h*.73+i*h*.055:h*.76+i*h*.065));ctx.font=`430 ${Math.max(13,w*(portrait?.026:.015))}px system-ui`;ctx.fillStyle=p.muted;const ml=wrapLines(ctx,message,iw,3);ml.forEach((lineText,i)=>ctx.fillText(lineText,cx,portrait?h*.88+i*h*.035:h*.91+i*h*.04));ctx.textAlign='left';ctx.fillStyle=accent;ctx.font=`680 ${Math.max(11,w*.013)}px system-ui`;ctx.fillText(cta,x0,h-pad*.75);
    } else if(layout==='collaboration-call'){
      drawBadge(ctx,badge,x0,y0,p,scale);ctx.fillStyle=accent;ctx.font=`820 ${Math.max(30,Math.min(w,h)*.12)}px system-ui`;ctx.fillText(metric,x0,y0+h*.18);const top=titleLines(ctx,title,x0,y0+h*.30,portrait?iw:iw*.52,h,p,{maxLines:4,scale:.72});messageLines(ctx,message,x0,top.bottom+h*.025,portrait?iw:iw*.52,h,p,{maxLines:5,size:Math.max(13,w*(portrait?.026:.015))});const cx=portrait?w*.5:w*.76,cy=portrait?h*.72:h*.48,r=Math.min(w,h)*.15;const labels=['HUMAN INTENT','AI COLLABORATION','VISIBLE PROOF'];labels.forEach((label,i)=>{const a=-Math.PI/2+i*Math.PI*2/3,nx=cx+Math.cos(a)*r*1.6,ny=cy+Math.sin(a)*r*1.25;line(ctx,cx,cy,nx,ny,2,p.line);ctx.beginPath();ctx.arc(nx,ny,r*.34,0,Math.PI*2);ctx.fillStyle=rgba(i===2?p.success:accent,.18);ctx.fill();ctx.strokeStyle=i===2?p.success:accent;ctx.stroke();drawMicroLabel(ctx,label,nx,ny+r*.62,p,Math.max(9,w*.009),'center')});ctx.beginPath();ctx.arc(cx,cy,r*.48,0,Math.PI*2);ctx.fillStyle=rgba(accent,.24);ctx.fill();ctx.strokeStyle=p.text;ctx.stroke();ctx.fillStyle=accent;ctx.font=`680 ${Math.max(11,w*.013)}px system-ui`;ctx.fillText(cta,x0,h-pad*.75);
    } else if(layout==='dashboard-panel'){
      drawBadge(ctx,badge,x0,y0,p,scale);const top=titleLines(ctx,title,x0,y0+h*.14,iw,h,p,{maxLines:2,scale:.60});messageLines(ctx,message,x0,top.bottom+h*.015,iw,h,p,{maxLines:2,size:Math.max(12,w*.014)});const gy=portrait?h*.38:h*.38,gap=Math.min(w,h)*.022,cols=portrait?2:4,rows=portrait?2:1,cellW=(iw-gap*(cols-1))/cols,cellH=portrait?h*.14:h*.20;['HEALTH','THROUGHPUT','RISK','PROOF'].forEach((label,i)=>{const cx=x0+(i%cols)*(cellW+gap),cy=gy+Math.floor(i/cols)*(cellH+gap);panelBox(ctx,cx,cy,cellW,cellH,p,{accent:i===2?p.warning:i===3?p.success:accent,alpha:.06});drawMicroLabel(ctx,label,cx+cellW*.08,cy+cellH*.26,p,Math.max(9,w*.010));ctx.fillStyle=i===2?p.warning:i===3?p.success:accent;ctx.font=`780 ${Math.max(18,cellH*.28)}px system-ui`;ctx.fillText([metric,'24','LOW','PASS'][i],cx+cellW*.08,cy+cellH*.68)});const sy=gy+rows*(cellH+gap)+h*.03;panelBox(ctx,x0,sy,iw,Math.max(h*.15,h-pad*1.4-sy),p,{accent,alpha:.035});drawMicroLabel(ctx,'TREND + CURRENT SIGNAL',x0+iw*.04,sy+h*.045,p,Math.max(9,w*.010));drawMiniSparkline(ctx,x0+iw*.04,sy+h*.075,iw*.92,Math.max(h*.08,h-pad*1.6-sy),p,accent,title);ctx.fillStyle=accent;ctx.font=`680 ${Math.max(11,w*.013)}px system-ui`;ctx.fillText(cta,x0,h-pad*.72);
    } else if(layout==='settings-stack'){
      drawBadge(ctx,badge,x0,y0,p,scale);const top=titleLines(ctx,title,x0,y0+h*.14,iw,h,p,{maxLines:2,scale:.62});messageLines(ctx,message,x0,top.bottom+h*.012,iw,h,p,{maxLines:3,size:Math.max(12,w*.014)});const labels=['LOCAL ONLY','PRIVACY GATE','REDUCED MOTION','LOW POWER','ROLLBACK BEFORE CHANGE'],sy=portrait?h*.38:h*.40,rowH=Math.min(h*.095,64*scale),gap=h*.012;labels.forEach((label,i)=>{const y=sy+i*(rowH+gap);panelBox(ctx,x0,y,iw,rowH,p,{accent:i===4?p.success:accent,alpha:.045,radius:rowH*.22});drawMicroLabel(ctx,label,x0+iw*.04,y+rowH*.58,p,Math.max(10,w*.011));const tw=Math.max(38,rowH*.62),th=rowH*.38,tx=x0+iw-tw-iw*.04,ty=y+(rowH-th)/2;roundedRect(ctx,tx,ty,tw,th,th/2);ctx.fillStyle=rgba(i===1?p.warning:i===4?p.success:accent,.25);ctx.fill();ctx.beginPath();ctx.arc(tx+tw*(i===1?.35:.72),ty+th/2,th*.34,0,Math.PI*2);ctx.fillStyle=i===1?p.warning:i===4?p.success:accent;ctx.fill()});ctx.fillStyle=accent;ctx.font=`680 ${Math.max(11,w*.013)}px system-ui`;ctx.fillText(cta,x0,h-pad*.72);
    } else if(layout==='onboarding-flow'){
      drawBadge(ctx,badge,x0,y0,p,scale);const top=titleLines(ctx,title,x0,y0+h*.14,iw,h,p,{maxLines:2,scale:.64});messageLines(ctx,message,x0,top.bottom+h*.012,iw,h,p,{maxLines:3,size:Math.max(12,w*.014)});const labels=['PURPOSE','PERMISSIONS','PREVIEW','REVERSIBLE RESULT'],vertical=portrait,baseY=vertical?h*.38:h*.55,stepW=vertical?iw:iw*.21,gap=vertical?h*.025:iw*.045;labels.forEach((label,i)=>{const cx=vertical?x0:x0+i*(stepW+gap),cy=vertical?baseY+i*h*.115:baseY;panelBox(ctx,cx,cy,stepW,vertical?h*.085:h*.18,p,{accent:i===3?p.success:accent,alpha:.055});ctx.beginPath();ctx.arc(cx+stepW*.12,cy+(vertical?h*.042:h*.09),Math.max(13,Math.min(stepW,h)*.055),0,Math.PI*2);ctx.fillStyle=i===3?p.success:accent;ctx.fill();ctx.fillStyle=p.surface;ctx.font=`800 ${Math.max(11,w*.013)}px system-ui`;ctx.textAlign='center';ctx.fillText(String(i+1),cx+stepW*.12,cy+(vertical?h*.052:h*.102));ctx.textAlign='left';drawMicroLabel(ctx,label,cx+stepW*.24,cy+(vertical?h*.052:h*.105),p,Math.max(9,w*.009));if(!vertical&&i<3)line(ctx,cx+stepW,cy+h*.09,cx+stepW+gap,cy+h*.09,2,p.line)});ctx.fillStyle=accent;ctx.font=`680 ${Math.max(11,w*.013)}px system-ui`;ctx.fillText(cta,x0,h-pad*.72);
    } else if(layout==='command-console'){
      drawBadge(ctx,badge,x0,y0,p,scale);const top=titleLines(ctx,title,x0,y0+h*.14,iw,h,p,{maxLines:2,scale:.60});messageLines(ctx,message,x0,top.bottom+h*.01,iw,h,p,{maxLines:2,size:Math.max(12,w*.014)});const sy=portrait?h*.34:h*.37,searchH=h*.085;panelBox(ctx,x0,sy,iw,searchH,p,{accent,alpha:.07,radius:searchH*.30});ctx.fillStyle=p.muted;ctx.font=`520 ${Math.max(12,w*.014)}px ui-monospace,monospace`;ctx.fillText('Search explicit actions…',x0+iw*.05,sy+searchH*.60);ctx.fillStyle=accent;ctx.font=`720 ${Math.max(11,w*.012)}px ui-monospace,monospace`;ctx.fillText(metric,x0+iw*.84,sy+searchH*.60);['OPEN MOLD','GENERATE PROOF','CREATE SNAPSHOT','EXPORT WORKSPACE'].forEach((label,i)=>{const y=sy+searchH+h*.025+i*h*.095;panelBox(ctx,x0,y,iw,h*.075,p,{accent:i===2?p.success:accent,alpha:.035,radius:h*.02});ctx.fillStyle=i===2?p.success:accent;ctx.font=`700 ${Math.max(11,w*.012)}px ui-monospace,monospace`;ctx.fillText(`${i+1}.`,x0+iw*.035,y+h*.047);drawMicroLabel(ctx,label,x0+iw*.10,y+h*.048,p,Math.max(10,w*.011));ctx.fillStyle=p.muted;ctx.font=`600 ${Math.max(10,w*.010)}px ui-monospace,monospace`;ctx.fillText(['ENTER','P','S','E'][i],x0+iw*.88,y+h*.047)});ctx.fillStyle=accent;ctx.font=`680 ${Math.max(11,w*.013)}px system-ui`;ctx.fillText(cta,x0,h-pad*.72);
    } else if(layout==='alert-recovery'){
      drawBadge(ctx,badge,x0,y0,p,scale);const warn=variant.state==='success'?p.success:p.warning,cx=portrait?w*.5:w*.18,cy=portrait?h*.27:h*.42,r=Math.min(w,h)*.10;ctx.beginPath();ctx.arc(cx,cy,r,0,Math.PI*2);ctx.fillStyle=rgba(warn,.18);ctx.fill();ctx.strokeStyle=warn;ctx.lineWidth=Math.max(3,r*.06);ctx.stroke();ctx.fillStyle=warn;ctx.font=`900 ${r*.92}px system-ui`;ctx.textAlign='center';ctx.fillText('!',cx,cy+r*.34);ctx.textAlign='left';const tx=portrait?x0:w*.31,tw=portrait?iw:iw*.63,top=titleLines(ctx,title,tx,portrait?h*.43:y0+h*.18,tw,h,p,{maxLines:3,scale:.70,fill:warn});messageLines(ctx,message,tx,top.bottom+h*.018,tw,h,p,{maxLines:4,size:Math.max(12,w*.014)});const sy=portrait?h*.65:h*.62;['STATE PRESERVED','IMPACT IDENTIFIED','REPAIR OPTIONS VISIBLE','ROLLBACK AVAILABLE'].forEach((label,i)=>{const y=sy+i*h*.065;ctx.beginPath();ctx.arc(tx+8*scale,y,Math.max(4,w*.004),0,Math.PI*2);ctx.fillStyle=i===3?p.success:warn;ctx.fill();drawMicroLabel(ctx,label,tx+24*scale,y+4*scale,p,Math.max(9,w*.009))});ctx.fillStyle=warn;ctx.font=`680 ${Math.max(11,w*.013)}px system-ui`;ctx.fillText(cta,tx,h-pad*.72);
    } else if(layout==='metric-pulse'){
      drawBadge(ctx,badge,x0,y0,p,scale);const cx=w*.5,cy=portrait?h*.48:h*.48,r=Math.min(w,h)*.25;for(let i=0;i<4;i++){ctx.beginPath();ctx.arc(cx,cy,r*(.42+i*.18),0,Math.PI*2);ctx.strokeStyle=rgba(i===3?p.accent_2:accent,.18+i*.06);ctx.lineWidth=Math.max(2,r*.02);ctx.stroke()}ctx.textAlign='center';ctx.fillStyle=accent;ctx.font=`850 ${Math.max(50,r*.72)}px system-ui`;ctx.fillText(metric,cx,cy+r*.12);ctx.font=`740 ${Math.max(20,Math.min(w,h)*.055)}px system-ui`;ctx.fillStyle=p.text;const tl=wrapLines(ctx,title,iw*.75,3);tl.forEach((lineText,i)=>ctx.fillText(lineText,cx,portrait?h*.75+i*h*.055:h*.79+i*h*.06));ctx.font=`430 ${Math.max(12,w*(portrait?.024:.014))}px system-ui`;ctx.fillStyle=p.muted;ctx.fillText(message.slice(0,96),cx,portrait?h*.91:h*.92);ctx.textAlign='left';ctx.fillStyle=accent;ctx.font=`680 ${Math.max(11,w*.013)}px system-ui`;ctx.fillText(cta,x0,h-pad*.72);
    } else if(layout==='activity-timeline'){
      drawBadge(ctx,badge,x0,y0,p,scale);const top=titleLines(ctx,title,x0,y0+h*.14,iw,h,p,{maxLines:2,scale:.62});messageLines(ctx,message,x0,top.bottom+h*.01,iw,h,p,{maxLines:2,size:Math.max(12,w*.014)});const tx=x0+iw*.08,sy=portrait?h*.36:h*.40,step=h*(portrait?.105:.09);line(ctx,tx,sy,tx,sy+step*4,2,p.line);['INTENT CAPTURED','CANDIDATE BUILT','PROOF GENERATED','APPROVAL RECORDED','HANDOFF READY'].forEach((label,i)=>{const y=sy+i*step;ctx.beginPath();ctx.arc(tx,y,Math.max(6,w*.006),0,Math.PI*2);ctx.fillStyle=i===4?p.success:accent;ctx.fill();drawMicroLabel(ctx,label,tx+iw*.06,y+4*scale,p,Math.max(10,w*.011));ctx.fillStyle=p.muted;ctx.font=`500 ${Math.max(10,w*.010)}px system-ui`;ctx.fillText(['source kept','sparse override','22 checks','explicit action','fingerprint'][i],tx+iw*.48,y+4*scale)});ctx.fillStyle=accent;ctx.font=`680 ${Math.max(11,w*.013)}px system-ui`;ctx.fillText(cta,x0,h-pad*.72);
    } else if(layout==='profile-network'){
      drawBadge(ctx,badge,x0,y0,p,scale);const cx=portrait?w*.5:w*.72,cy=portrait?h*.35:h*.46,r=Math.min(w,h)*.15;drawOrbitalMedia(ctx,cx,cy,r,p,controls,variant,0,'orbital-window');const top=titleLines(ctx,title,x0,portrait?h*.59:y0+h*.18,portrait?iw:iw*.48,h,p,{maxLines:3,scale:.70});messageLines(ctx,message,x0,top.bottom+h*.018,portrait?iw:iw*.48,h,p,{maxLines:5,size:Math.max(12,w*.014)});['ROLE','PERMISSIONS','AVAILABILITY','ESCALATION'].forEach((label,i)=>{const a=i/4*Math.PI*2-.4,nx=cx+Math.cos(a)*r*1.55,ny=cy+Math.sin(a)*r*1.28;ctx.beginPath();ctx.arc(nx,ny,r*.20,0,Math.PI*2);ctx.fillStyle=rgba(i===3?p.warning:accent,.18);ctx.fill();ctx.strokeStyle=i===3?p.warning:accent;ctx.stroke();drawMicroLabel(ctx,label,nx,ny+r*.38,p,Math.max(8,w*.008),'center')});ctx.fillStyle=accent;ctx.font=`680 ${Math.max(11,w*.013)}px system-ui`;ctx.fillText(cta,x0,h-pad*.72);
    } else if(layout==='mission-brief'){
      drawBadge(ctx,badge,x0,y0,p,scale);ctx.fillStyle=accent;ctx.font=`820 ${Math.max(28,Math.min(w,h)*.11)}px system-ui`;ctx.fillText(metric,x0,y0+h*.18);const top=titleLines(ctx,title,x0,y0+h*.30,portrait?iw:iw*.52,h,p,{maxLines:3,scale:.68});messageLines(ctx,message,x0,top.bottom+h*.018,portrait?iw:iw*.52,h,p,{maxLines:4,size:Math.max(12,w*.014)});const lx=x0,sy=portrait?h*.64:h*.67;['PRIMARY OBJECTIVE','OPTIONAL ROUTE','TEAM CONDITION'].forEach((label,i)=>{ctx.beginPath();ctx.arc(lx+6*scale,sy+i*h*.065,Math.max(4,w*.004),0,Math.PI*2);ctx.fillStyle=i===0?accent:i===1?p.accent_2:p.success;ctx.fill();drawMicroLabel(ctx,label,lx+22*scale,sy+i*h*.065+4*scale,p,Math.max(9,w*.009))});const cx=portrait?w*.5:w*.76,cy=portrait?h*.47:h*.48,r=Math.min(w,h)*.18;drawOrbitalMedia(ctx,cx,cy,r,p,controls,variant,0,'arena-core');ctx.fillStyle=accent;ctx.font=`680 ${Math.max(11,w*.013)}px system-ui`;ctx.fillText(cta,x0,h-pad*.72);
    } else if(layout==='character-dossier'){
      drawBadge(ctx,badge,x0,y0,p,scale);const cx=portrait?w*.5:w*.27,cy=portrait?h*.35:h*.50,r=Math.min(w,h)*.19;drawOrbitalMedia(ctx,cx,cy,r,p,controls,variant,0,'evidence-window');const tx=portrait?x0:w*.50,ty=portrait?h*.61:y0+h*.17,tw=portrait?iw:iw*.43;ctx.fillStyle=accent;ctx.font=`820 ${Math.max(25,Math.min(w,h)*.08)}px system-ui`;ctx.fillText(metric,tx,ty);const top=titleLines(ctx,title,tx,ty+h*.11,tw,h,p,{maxLines:3,scale:.70});messageLines(ctx,message,tx,top.bottom+h*.015,tw,h,p,{maxLines:4,size:Math.max(12,w*.014)});['FOCUS','MOBILITY','REPAIR','TRUST'].forEach((label,i)=>{const y=(portrait?h*.82:top.bottom+h*.24)+i*h*.047;drawMicroLabel(ctx,label,tx,y,p,Math.max(8,w*.008));progressBar(ctx,tx+tw*.28,y-h*.013,tw*.70,h*.016,.48+i*.10,p,i===3?p.success:accent)});ctx.fillStyle=accent;ctx.font=`680 ${Math.max(11,w*.013)}px system-ui`;ctx.fillText(cta,tx,h-pad*.72);
    } else if(layout==='loot-inspect'){
      drawBadge(ctx,badge,x0,y0,p,scale);const cx=w*.5,cy=portrait?h*.35:h*.43,r=Math.min(w,h)*.20;drawOrbitalMedia(ctx,cx,cy,r,p,controls,variant,0,'data-core');ctx.textAlign='center';ctx.fillStyle=accent;ctx.font=`820 ${Math.max(22,r*.30)}px system-ui`;ctx.fillText(metric,cx,cy+r*.16);ctx.fillStyle=p.text;ctx.font=`760 ${Math.max(24,Math.min(w,h)*.065)}px system-ui`;const tl=wrapLines(ctx,title,iw*.86,3);tl.forEach((lineText,i)=>ctx.fillText(lineText,cx,portrait?h*.65+i*h*.055:h*.72+i*h*.06));ctx.textAlign='left';const sy=portrait?h*.78:h*.82;['POWER','STABILITY','COMPATIBILITY'].forEach((label,i)=>{const x=x0+i*iw/3;drawMicroLabel(ctx,label,x,sy,p,Math.max(8,w*.008));progressBar(ctx,x,sy+h*.025,iw*.27,h*.018,.56+i*.14,p,i===2?p.success:accent)});ctx.fillStyle=accent;ctx.font=`680 ${Math.max(11,w*.013)}px system-ui`;ctx.fillText(cta,x0,h-pad*.72);
    } else if(layout==='quest-ledger'){
      drawBadge(ctx,badge,x0,y0,p,scale);const top=titleLines(ctx,title,x0,y0+h*.15,iw,h,p,{maxLines:2,scale:.64});messageLines(ctx,message,x0,top.bottom+h*.008,iw,h,p,{maxLines:2,size:Math.max(12,w*.014)});ctx.fillStyle=accent;ctx.font=`820 ${Math.max(24,Math.min(w,h)*.075)}px system-ui`;ctx.fillText(metric,w-pad*2.5,y0+h*.12);const sy=portrait?h*.36:h*.38;['RELAY TOWER','MARKET NODE','CANAL GATE','DEPOT SIGNAL','CENTRAL CORE'].forEach((label,i)=>{const y=sy+i*h*(portrait?.09:.085);panelBox(ctx,x0,y,iw,h*.066,p,{accent:i<2?p.success:accent,alpha:.035,radius:h*.018});ctx.beginPath();ctx.arc(x0+iw*.035,y+h*.033,Math.max(4,w*.004),0,Math.PI*2);ctx.fillStyle=i<2?p.success:accent;ctx.fill();drawMicroLabel(ctx,label,x0+iw*.075,y+h*.040,p,Math.max(9,w*.009));progressBar(ctx,x0+iw*.60,y+h*.025,iw*.34,h*.016,i<2?1:.18+i*.12,p,i<2?p.success:accent)});ctx.fillStyle=accent;ctx.font=`680 ${Math.max(11,w*.013)}px system-ui`;ctx.fillText(cta,x0,h-pad*.72);
    } else if(layout==='boss-warning'){
      const warn=variant.state==='success'?p.success:p.warning;drawBadge(ctx,badge,x0,y0,p,scale);ctx.textAlign='center';ctx.fillStyle=warn;ctx.font=`900 ${Math.max(34,Math.min(w,h)*.12)}px system-ui`;const tl=wrapLines(ctx,title,iw*.92,3);tl.forEach((lineText,i)=>ctx.fillText(lineText,w*.5,h*.27+i*h*.10));const cx=w*.5,cy=portrait?h*.55:h*.58,r=Math.min(w,h)*.16;for(let i=0;i<3;i++){ctx.beginPath();ctx.arc(cx,cy,r*(.70+i*.22),0,Math.PI*2);ctx.strokeStyle=rgba(i===2?p.accent_2:warn,.28+i*.13);ctx.lineWidth=Math.max(3,r*.045);ctx.stroke()}ctx.fillStyle=warn;ctx.font=`850 ${Math.max(26,r*.45)}px system-ui`;ctx.fillText(metric,cx,cy+r*.13);ctx.textAlign='left';progressBar(ctx,x0,portrait?h*.79:h*.83,iw,h*.035,.76,p,warn);drawMicroLabel(ctx,'THREAT INTEGRITY',x0,portrait?h*.77:h*.81,p,Math.max(10,w*.010));ctx.fillStyle=warn;ctx.font=`720 ${Math.max(12,w*.015)}px system-ui`;ctx.fillText(cta,x0,h-pad*.72);
    } else if(layout==='world-event'){
      drawBadge(ctx,badge,x0,y0,p,scale);const cx=w*.5,cy=portrait?h*.43:h*.46,r=Math.min(w,h)*.21;drawOrbitalMedia(ctx,cx,cy,r,p,controls,variant,0,'portal-window');ctx.textAlign='center';ctx.fillStyle=accent;ctx.font=`900 ${Math.max(34,r*.46)}px system-ui`;ctx.fillText(metric,cx,cy+r*.10);ctx.fillStyle=p.text;ctx.font=`760 ${Math.max(24,Math.min(w,h)*.064)}px system-ui`;const tl=wrapLines(ctx,title,iw*.86,3);tl.forEach((lineText,i)=>ctx.fillText(lineText,cx,portrait?h*.71+i*h*.055:h*.76+i*h*.06));ctx.fillStyle=p.muted;ctx.font=`430 ${Math.max(12,w*(portrait?.024:.014))}px system-ui`;ctx.fillText(message.slice(0,100),cx,portrait?h*.90:h*.91);ctx.textAlign='left';for(let i=0;i<6;i++){const a=i/6*Math.PI*2,nx=cx+Math.cos(a)*r*1.35,ny=cy+Math.sin(a)*r*1.12;ctx.beginPath();ctx.arc(nx,ny,Math.max(4,r*.035),0,Math.PI*2);ctx.fillStyle=i<3?accent:p.accent_2;ctx.fill()}ctx.fillStyle=accent;ctx.font=`680 ${Math.max(11,w*.013)}px system-ui`;ctx.fillText(cta,x0,h-pad*.72);
    } else if(layout==='hud-status'){
      drawBadge(ctx,badge,x0,y0,p,scale);const top=titleLines(ctx,title,x0,y0+h*.14,iw*.64,h,p,{maxLines:2,scale:.62});messageLines(ctx,message,x0,top.bottom+h*.01,iw*.64,h,p,{maxLines:3,size:Math.max(12,w*.014)});const sy=portrait?h*.42:h*.46;[['HEALTH',.84,p.success],['ENERGY',.62,accent],['OBJECTIVE',.48,p.accent_2],['CONNECTION',.92,p.success]].forEach(([label,value,color],i)=>{const y=sy+i*h*.09;drawMicroLabel(ctx,label,x0,y,p,Math.max(9,w*.009));progressBar(ctx,x0,y+h*.025,portrait?iw:iw*.60,h*.022,value,p,color)});const cx=portrait?w*.5:w*.78,cy=portrait?h*.77:h*.48,r=Math.min(w,h)*.16;drawOrbitalMedia(ctx,cx,cy,r,p,controls,variant,0,'arena-core');for(let i=0;i<4;i++){const a=i/4*Math.PI*2,nx=cx+Math.cos(a)*r*.65,ny=cy+Math.sin(a)*r*.65;ctx.beginPath();ctx.arc(nx,ny,Math.max(4,r*.045),0,Math.PI*2);ctx.fillStyle=i<3?p.success:p.warning;ctx.fill()}ctx.fillStyle=accent;ctx.font=`800 ${Math.max(24,Math.min(w,h)*.07)}px system-ui`;ctx.fillText(metric,portrait?x0:w*.72,portrait?h*.93:y0+h*.15);ctx.font=`680 ${Math.max(11,w*.013)}px system-ui`;ctx.fillText(cta,x0,h-pad*.72);
    } else {
      const copyW=portrait||phone?w-pad*2.7:w*.53,mediaX=portrait||phone?w*.5:w*.77,mediaY=portrait||phone?h*.67:h*.5,mediaR=Math.min(w,h)*((portrait||phone)?0.25:0.28);
      const x=pad*1.35,y=pad*1.45;drawBadge(ctx,badge,x,y,p,scale);ctx.font=`800 ${portrait?Math.min(w*.13,h*.085):Math.min(w*.095,h*.14)}px system-ui`;ctx.fillStyle=accent;ctx.fillText(metric,x,y+(portrait?h*.14:h*.19));const titleY=y+(portrait?h*.24:h*.31);ctx.font=`730 ${fittedTitleSize(title,copyW,h)*(layout==='game-signal'?.94:1)}px system-ui`;const tl=wrapLines(ctx,title,copyW,portrait?4:3);fillTextLines(ctx,tl,x,titleY,Math.max(27,parseFloat(ctx.font)*1.05),p.text);const titleLine=Math.max(27,fittedTitleSize(title,copyW,h)*1.05);ctx.font=`430 ${Math.max(14,w*(portrait?.028:.017))}px system-ui`;const ml=wrapLines(ctx,message,copyW,portrait?6:5);fillTextLines(ctx,ml,x,titleY+tl.length*titleLine+h*.055,Math.max(21,h*.041),p.muted);const ctaY=Math.min(h-pad*1.25,titleY+tl.length*titleLine+h*.055+ml.length*Math.max(21,h*.041)+h*.07);ctx.font=`680 ${Math.max(12,w*(portrait?.024:.014))}px system-ui`;ctx.fillStyle=accent;ctx.fillText(cta,x,ctaY);
      drawOrbitalMedia(ctx,mediaX,mediaY,mediaR,p,controls,variant,0,mold?.renderer_options?.media_shape||'orbital-window');
      if(layout==='game-signal'){const players=8;for(let i=0;i<players;i++){const a=i/players*Math.PI*2,rr=mediaR*1.1,cx=mediaX+Math.cos(a)*rr,cy=mediaY+Math.sin(a)*rr;ctx.fillStyle=i<4?p.accent:p.accent_2;ctx.globalAlpha=.72;ctx.beginPath();ctx.arc(cx,cy,Math.max(3,mediaR*.025),0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1}
      if(layout==='service-stage'){const priceX=mediaX-mediaR*.43,priceY=mediaY+mediaR*.72;roundedRect(ctx,priceX,priceY,mediaR*.86,mediaR*.22,mediaR*.08);ctx.fillStyle=rgba(accent,.16);ctx.fill();ctx.strokeStyle=p.line;ctx.stroke()}
    }
    ctx.globalAlpha=1;ctx.textAlign='left';
    if(depth>.45){ctx.save();ctx.globalAlpha=(depth-.45)*.5;for(let i=0;i<6;i++){const y=h*(.18+i*.13),x=w*(.08+i*.025);line(ctx,x,y,w-x,y+h*.03,Math.max(1,w*.001),p.line)}ctx.restore()}
    return canvas;
  }

  function canvasDescription(mold,controls,variant){return `${mold?.name||'AXM visual'}: ${String(controls?.title||mold?.name||'Untitled')}. ${String(controls?.message||'').slice(0,240)} Theme ${variant?.theme||'default'}, ${variant?.format||'default'} format, ${variant?.state||'idle'} state.`.replace(/\s+/g,' ').trim()}
  function createCardDOM(controls,variant,{compact=false,mold=window.AXM.getMold()}={}){const wrap=document.createElement('div');wrap.className=`generated-card ${compact?'compact':''}`;const canvas=document.createElement('canvas');drawCardCanvas(canvas,controls,variant,compact?.32:1,mold);if(compact)canvas.setAttribute('aria-hidden','true');else{canvas.setAttribute('role','img');canvas.setAttribute('aria-label',canvasDescription(mold,controls,variant))}wrap.appendChild(canvas);return wrap}

  function drawSkin(canvas,controls,variant,time=0,mold=window.AXM.getMold()){
    const [w,h]=formatCanvas(canvas,variant,1),ctx=canvas.getContext('2d'),p=theme(variant.theme),age=window.AXM.clamp(controls.age),damage=window.AXM.clamp(controls.damage),wet=window.AXM.clamp(controls.wetness),rough=window.AXM.clamp(controls.roughness),trans=window.AXM.clamp(controls.transparency),reflection=window.AXM.clamp(controls.reflection),inner=window.AXM.clamp(controls.inner_glow),edge=window.AXM.clamp(controls.edge_glow),move=window.AXM.clamp(controls.energy_movement),density=window.AXM.clamp(controls.pattern_density),surfaceDepth=window.AXM.clamp(controls.surface_depth??.5),temperature=window.AXM.clamp(controls.temperature??.5),perf=variant.performance;
    drawBackdrop(ctx,w,h,p,inner,density,time,perf);const pad=Math.min(w,h)*.09,r=Math.min(w,h)*.08;ctx.save();roundedRect(ctx,pad,pad,w-pad*2,h-pad*2,r);const surface=ctx.createLinearGradient(pad,pad,w-pad,h-pad);surface.addColorStop(0,rgba(p.surface_2,.94-trans*.35));surface.addColorStop(.45,rgba(temperature>.5?p.accent_2:p.accent,.13+inner*.25));surface.addColorStop(1,rgba(p.surface,.96-trans*.38));ctx.fillStyle=surface;ctx.shadowColor=`rgba(${p.glow_rgb},${.16+edge*.44})`;ctx.shadowBlur=(perf==='low'?8:perf==='ultra'?48:26)*edge;ctx.fill();ctx.strokeStyle=rgba(stateAccent(p,variant),.24+edge*.62);ctx.lineWidth=2+edge*7;ctx.stroke();ctx.clip();
    const rnd=seededNoise(hashSeed(`${variant.theme}:${variant.state}`)),cells=perf==='low'?18:perf==='ultra'?92:46;for(let i=0;i<cells;i++){const x=pad+rnd()*(w-pad*2),y=pad+rnd()*(h-pad*2),s=(12+rnd()*70)*(0.35+density);ctx.beginPath();ctx.moveTo(x-s,y);ctx.lineTo(x+s*.7,y-s*.5);ctx.lineTo(x+s,y+s*.6);ctx.lineTo(x-s*.5,y+s);ctx.closePath();ctx.fillStyle=i%3===0?rgba(p.accent,.025+.10*inner):rgba(p.text,.012+.05*(1-rough));ctx.fill();ctx.strokeStyle=rgba(i%2?p.accent:p.accent_2,.04+.13*density);ctx.lineWidth=1+surfaceDepth*2;ctx.stroke()}
    const veins=perf==='low'?4:perf==='ultra'?18:10;ctx.lineCap='round';for(let i=0;i<veins;i++){const yy=pad+(i+1)*(h-pad*2)/(veins+1),phase=Math.sin(time*.001*move+i)*w*.025;ctx.beginPath();ctx.moveTo(pad,yy);for(let x=pad;x<w-pad;x+=w*.055)ctx.lineTo(x,yy+Math.sin(x*.018+i*1.7)*h*.018+phase);ctx.strokeStyle=rgba(i%2?p.accent:p.accent_2,.07+.32*inner);ctx.lineWidth=1+edge*3;ctx.stroke()}
    const scratches=Math.floor((perf==='ultra'?80:38)*damage);for(let i=0;i<scratches;i++){const x=pad+rnd()*(w-pad*2),y=pad+rnd()*(h-pad*2),len=10+rnd()*75;line(ctx,x,y,x+len,y+(rnd()-.5)*18,1+rnd()*1.4,rgba(p.text,.09+.25*damage))}
    if(wet>.05){const sheen=ctx.createLinearGradient(0,0,w,h);sheen.addColorStop(.25,'rgba(255,255,255,0)');sheen.addColorStop(.48,`rgba(255,255,255,${.04+.20*wet})`);sheen.addColorStop(.64,'rgba(255,255,255,0)');ctx.fillStyle=sheen;ctx.fillRect(pad,pad,w-pad*2,h-pad*2)}
    if(age>.05){ctx.fillStyle=`rgba(95,62,32,${age*.16})`;ctx.fillRect(pad,pad,w-pad*2,h-pad*2)}ctx.restore();
    const materialTitle=String(controls.title||mold?.renderer_options?.material_title||mold?.name||'LIVING SKIN'),materialSubtitle=String(controls.message||mold?.renderer_options?.material_subtitle||`${p.name} · depth ${surfaceDepth.toFixed(2)} · ${perf}`);ctx.fillStyle=p.text;ctx.font=`750 ${Math.max(22,w*.038)}px system-ui`;ctx.fillText(materialTitle,pad*1.32,pad*1.55);ctx.fillStyle=p.muted;ctx.font=`500 ${Math.max(12,w*.015)}px system-ui`;ctx.fillText(materialSubtitle.slice(0,110),pad*1.34,pad*1.92);return canvas;
  }

  function drawPortal(canvas,controls,variant,time=0,mold=window.AXM.getMold()){
    const [w,h]=formatCanvas(canvas,variant,1),ctx=canvas.getContext('2d'),p=theme(variant.theme),fog=window.AXM.clamp(controls.fog_density??controls.fog??.35),particles=window.AXM.clamp(controls.particle_density??controls.particles??.48),depth=window.AXM.clamp(controls.depth??.66),energy=window.AXM.clamp(controls.energy??controls.portal_energy??.58),beam=window.AXM.clamp(controls.beam_strength??controls.light_contrast??.62),camera=window.AXM.clamp(controls.camera_distance??controls.camera_zoom??.5),foreground=window.AXM.clamp(controls.foreground_depth??.52),shape=controls.portal_shape||'ring',perf=variant.performance,accent=stateAccent(p,variant);
    drawBackdrop(ctx,w,h,p,energy,.45,time,perf);const horizon=h*(.66-camera*.08);const floor=ctx.createLinearGradient(0,horizon,0,h);floor.addColorStop(0,rgba(p.accent,.04));floor.addColorStop(1,p.surface);ctx.fillStyle=floor;ctx.fillRect(0,horizon,w,h-horizon);
    const grid=perf==='low'?6:perf==='ultra'?20:12;ctx.save();ctx.globalAlpha=.34;for(let i=0;i<grid;i++){const y=horizon+(i/grid)*(h-horizon);line(ctx,w*.08,y,w*.92,y,1,p.line)}for(let i=0;i<grid;i++){const x=w*.5+(i-grid/2)*w*.06;line(ctx,w*.5,horizon,x,h,1,p.line)}ctx.restore();
    const cx=w*.5,cy=h*(.47+camera*.04),r=Math.min(w,h)*(.18+depth*.08);if(beam>.03){const grd=ctx.createLinearGradient(cx,0,cx,h);grd.addColorStop(0,'rgba(0,0,0,0)');grd.addColorStop(.45,rgba(accent,.03+beam*.16));grd.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=grd;ctx.beginPath();ctx.moveTo(cx-r*.25,0);ctx.lineTo(cx+r*.78,h);ctx.lineTo(cx-r*.78,h);ctx.lineTo(cx+r*.25,0);ctx.closePath();ctx.fill()}
    ctx.save();ctx.translate(cx,cy);ctx.shadowColor=`rgba(${p.glow_rgb},${.28+.48*energy})`;ctx.shadowBlur=perf==='low'?16:perf==='ultra'?72:42;const ring=(rr,width,color)=>{ctx.beginPath();if(shape==='diamond'){ctx.moveTo(0,-rr);ctx.lineTo(rr*.76,0);ctx.lineTo(0,rr);ctx.lineTo(-rr*.76,0);ctx.closePath()}else if(shape==='gate'){roundedRect(ctx,-rr*.62,-rr,rr*1.24,rr*2,rr*.16)}else{ctx.arc(0,0,rr,shape==='split-ring'?.16:0,shape==='split-ring'?Math.PI*1.84:Math.PI*2)}ctx.strokeStyle=color;ctx.lineWidth=width;ctx.stroke()};ring(r,r*.10,rgba(accent,.65));ring(r*.76,r*.025,rgba(p.text,.72));ring(r*1.17,r*.012,rgba(p.accent_2,.42));const inner=ctx.createRadialGradient(0,0,0,0,0,r*.74);inner.addColorStop(0,rgba(p.text,.55));inner.addColorStop(.08,rgba(accent,.52));inner.addColorStop(.52,rgba(p.accent_2,.20));inner.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=inner;ctx.beginPath();ctx.arc(0,0,r*.72,0,Math.PI*2);ctx.fill();ctx.restore();
    const rnd=seededNoise(hashSeed(`${variant.theme}:portal`)),count=Math.floor((perf==='low'?12:perf==='ultra'?100:46)*particles);for(let i=0;i<count;i++){const a=rnd()*Math.PI*2,rr=r*(.55+rnd()*1.35),x=cx+Math.cos(a+time*.00018*(i%2?1:-1))*rr,y=cy+Math.sin(a+time*.00018*(i%2?1:-1))*rr*.72;ctx.fillStyle=i%3===0?p.accent_2:accent;ctx.globalAlpha=.18+rnd()*.65;ctx.beginPath();ctx.arc(x,y,1+rnd()*3,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;
    if(fog>.03){const fogG=ctx.createLinearGradient(0,h*.36,0,h);fogG.addColorStop(0,'rgba(255,255,255,0)');fogG.addColorStop(.72,rgba(p.text,.02+fog*.10));fogG.addColorStop(1,rgba(p.surface_2,.12+fog*.22));ctx.fillStyle=fogG;ctx.fillRect(0,0,w,h)}
    if(foreground>.15){ctx.fillStyle=rgba(p.surface,.55+.35*foreground);ctx.beginPath();ctx.moveTo(0,h);ctx.lineTo(0,h*.74);ctx.lineTo(w*.18,h*.64);ctx.lineTo(w*.28,h);ctx.closePath();ctx.fill();ctx.beginPath();ctx.moveTo(w,h);ctx.lineTo(w,h*.70);ctx.lineTo(w*.82,h*.62);ctx.lineTo(w*.70,h);ctx.closePath();ctx.fill()}
    const sceneTitle=String(controls.title||mold?.renderer_options?.scene_title||mold?.name||'ATMOSPHERIC PORTAL'),sceneSubtitle=String(controls.message||mold?.renderer_options?.scene_subtitle||`${shape} · ${variant.state} · ${perf}`);ctx.fillStyle=p.text;ctx.font=`760 ${Math.max(24,w*.04)}px system-ui`;ctx.fillText(sceneTitle.slice(0,76),w*.06,h*.11);ctx.fillStyle=p.muted;ctx.font=`500 ${Math.max(12,w*.015)}px system-ui`;ctx.fillText(sceneSubtitle.slice(0,120),w*.061,h*.155);return canvas;
  }

  function startAnimation(key,draw,canvas,controls,variant,mold=null){
    stopAnimation(key); if(window.AXM.state.reducedMotion||variant.motion==='still'||variant.performance==='low')return draw(canvas,controls,variant,0,mold);
    let id=0;const tick=t=>{draw(canvas,controls,variant,t,mold);id=requestAnimationFrame(tick);animations.set(key,id)};id=requestAnimationFrame(tick);animations.set(key,id);
  }
  function stopAnimation(key){const id=animations.get(key);if(id)cancelAnimationFrame(id);animations.delete(key)}
  function stopAll(){for(const key of [...animations.keys()])stopAnimation(key)}
  function renderMoldToElement(container,mold,controls,variant,{animate=true,key='main'}={}){
    stopAnimation(key);container.innerHTML='';const canvas=document.createElement('canvas');canvas.className='mold-canvas';canvas.setAttribute('role','img');canvas.setAttribute('aria-label',canvasDescription(mold,controls,variant));container.appendChild(canvas);const mode=mold.renderer||'card';
    if(mode==='card'){drawCardCanvas(canvas,controls,variant,1,mold);if(animate)startAnimation(key,(c,co,v,t,m)=>{drawCardCanvas(c,co,v,1,m);if(t&&v.motion!=='still'){const ctx=c.getContext('2d'),p=theme(v.theme),w=c.width,h=c.height;ctx.save();ctx.globalCompositeOperation='screen';const x=(t*.08%(w*1.4))-w*.2,g=ctx.createLinearGradient(x-w*.18,0,x+w*.18,0);g.addColorStop(0,'rgba(255,255,255,0)');g.addColorStop(.5,rgba(p.accent,.035));g.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.restore()}},canvas,controls,variant,mold)}
    else if(mode==='living-skin'){drawSkin(canvas,controls,variant,0,mold);if(animate)startAnimation(key,drawSkin,canvas,controls,variant,mold)}
    else{drawPortal(canvas,controls,variant,0,mold);if(animate)startAnimation(key,drawPortal,canvas,controls,variant,mold)}
    return canvas;
  }
  function renderThumbnail(container,mold,controls,variant){container.innerHTML='';const canvas=renderCanvasForMold(mold,controls,{...variant,motion:'still',performance:'low'},.28);canvas.className='thumb-canvas';canvas.setAttribute('aria-hidden','true');container.appendChild(canvas);return canvas}
  function renderCanvasForMold(mold,controls,variant,scale=1){const canvas=document.createElement('canvas');if(mold.renderer==='living-skin')drawSkin(canvas,controls,{...variant,motion:'still'},0,mold);else if(mold.renderer==='portal-scene')drawPortal(canvas,controls,{...variant,motion:'still'},0,mold);else drawCardCanvas(canvas,controls,{...variant,motion:'still'},scale,mold);return canvas}
  function describeComposition(mold){return {renderer:mold.renderer,level:mold.composition_level,layout:mold.renderer_options?.layout||mold.renderer,organs:(mold.organs||[]).length,source_kind:mold.source_kind,lineage_parent:mold.lineage?.parent||null}}

  window.AXMRender={CARD_LAYOUTS,PALETTES,palette,theme,rgba,roundedRect,wrapLines,fittedTitleSize,canvasDescription,createCardDOM,drawCardCanvas,drawSkin,drawPortal,startAnimation,stopAnimation,stopAll,renderMoldToElement,renderThumbnail,renderCanvasForMold,describeComposition};
})();
