(function(){
  'use strict';
  var C=window.AXMAudioStudioCore,$=function(id){return document.getElementById(id);},STORE='axm.audio-studio.project.v1',ENGINE_STORE='axm.audio-studio.shared-project.v1',PUBLISH='axm.publish-library.ledger.v1',project=null,engineProject=null,active='arrange',ctx=null,liveNodes=[],toastTimer=null,recorder=null,recordChunks=[],recordings=[],restoreFile=null;
  function clean(v,n){return String(v==null?'':v).trim().slice(0,n||4000);}
  function esc(v){return String(v==null?'':v).replace(/[&<>'"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c];});}
  function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');$('statusText').textContent=msg;clearTimeout(toastTimer);toastTimer=setTimeout(function(){$('toast').classList.remove('show');},2200);if(window.AXMHub)AXMHub.log(msg);}
  function syncSharedProject(label){if(!window.AXMEngines)return;try{if(!engineProject||!AXMEngines.Project.validate(engineProject).ok)engineProject=AXMEngines.Project.create({id:project.id,kind:'audio',name:project.name,documentSchema:C.FORMAT,data:project,actor:{id:'audio-studio',kind:'service'}});else engineProject=AXMEngines.Project.update(engineProject,project,{id:'audio-studio',kind:'service'},label||'autosave');if(label)engineProject=AXMEngines.Project.checkpoint(engineProject,label,{id:'audio-studio',kind:'service'}).project;localStorage.setItem(ENGINE_STORE,JSON.stringify(engineProject));}catch(e){toast('Shared checkpoint unavailable: '+e.message);}}
  function save(msg){project.updatedAt=C.now();try{localStorage.setItem(STORE,JSON.stringify(project));syncSharedProject(msg);$('saveState').textContent='Saved '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});}catch(e){return toast('Save failed: '+e.message);}if(msg)toast(msg);}
  function load(){try{var raw=JSON.parse(localStorage.getItem(STORE)||'null');project=raw?C.normalizeProject(raw):C.emptyProject();try{engineProject=JSON.parse(localStorage.getItem(ENGINE_STORE)||'null');}catch(ignore){}syncSharedProject();}catch(e){project=C.emptyProject();toast('Unreadable project replaced with an empty Audio Studio');}}
  function audio(){if(!ctx)ctx=new(window.AudioContext||window.webkitAudioContext)();if(ctx.state==='suspended')ctx.resume();return ctx;}
  function stop(){liveNodes.forEach(function(n){try{n.stop();}catch(e){}});liveNodes=[];toast('Playback stopped');}
  function playTone(freq,start,duration,wave,gain,pan,context,destination){var ac=context||audio(),o=ac.createOscillator(),g=ac.createGain(),p=ac.createStereoPanner?ac.createStereoPanner():null,t=(ac.currentTime||0)+(start||0);o.type=wave||'sine';o.frequency.value=freq||440;g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(.001,gain||.25),t+.015);g.gain.exponentialRampToValueAtTime(.0001,t+Math.max(.04,duration||.3));o.connect(g);if(p){p.pan.value=pan||0;g.connect(p);p.connect(destination||ac.destination);}else g.connect(destination||ac.destination);o.start(t);o.stop(t+Math.max(.05,duration||.3)+.03);if(!context)liveNodes.push(o);return o;}
  function buildNav(){var nav=$('modeNav');C.groups().forEach(function(g){var cap=document.createElement('div');cap.className='nav-group';cap.textContent=g.name;nav.appendChild(cap);g.modes.forEach(function(m){var b=document.createElement('button');b.className='nav-button';b.dataset.mode=m.id;b.textContent=m.short;b.onclick=function(){selectMode(m.id);};nav.appendChild(b);});});}
  function selectMode(id){var m=C.byId(id);active=m.id;C.MODES.forEach(function(x){$(x.id+'View').hidden=x.id!==active;});document.querySelectorAll('.nav-button').forEach(function(b){b.classList.toggle('active',b.dataset.mode===active);});$('viewGroup').textContent=m.group;$('viewTitle').textContent=m.title;$('viewDescription').textContent=m.description;if(active==='sound'&&!$('soundFrame').src)$('soundFrame').src=$('soundFrame').dataset.src;renderAll();toast('Opened '+m.title);}
  function renderHeader(){var s=C.projectSummary(project);$('projectName').textContent=project.name;$('projectStats').textContent=s.tracks+' tracks · '+s.clips+' clips · '+s.notes+' notes';$('bpm').value=project.bpm;$('bars').value=project.bars;$('timeSignature').value=project.timeSignature;$('playhead').max=project.bars*4;}
  function options(id,items,empty){var el=$(id),chosen=el.value;el.innerHTML=empty?'<option value="">'+empty+'</option>':'';items.forEach(function(x){var o=document.createElement('option');o.value=x.id;o.textContent=x.name;el.appendChild(o);});if(Array.from(el.options).some(function(o){return o.value===chosen;}))el.value=chosen;}
  function renderSelectors(){options('clipTrack',project.tracks,'Add a track first');options('noteTrack',project.tracks.filter(function(t){return t.type==='instrument';}),'Add an instrument track');options('spatialTrack',project.tracks,'Add a track first');}
  function renderTracks(){var box=$('trackList');if(!project.tracks.length){box.innerHTML='<div class="notice">No tracks yet. Add one above or save a Sound Lab effect.</div>';return;}box.innerHTML='';var width=Math.max(project.bars*4,1);project.tracks.forEach(function(t){var row=document.createElement('article');row.className='track';row.innerHTML='<div class="track-head"><b>'+esc(t.name)+'</b><small>'+esc(t.type)+'</small></div><label>Gain<input data-gain type="range" min="0" max="150" value="'+Math.round(t.gain*100)+'"></label><label>Pan<input data-pan type="range" min="-100" max="100" value="'+Math.round(t.pan*100)+'"></label><div><button data-mute class="'+(t.mute?'primary':'')+'">M</button><button data-solo class="'+(t.solo?'primary':'')+'">S</button></div><div class="clip-lane"></div>';var lane=row.querySelector('.clip-lane');project.clips.filter(function(c){return c.trackId===t.id;}).forEach(function(c){var el=document.createElement('div');el.className='clip';el.style.left=(c.startBeat/width*100)+'%';el.style.width=Math.max(2,c.durationBeats/width*100)+'%';el.style.background=c.color;el.textContent=c.name;el.title=c.name+' · '+c.sourceType;lane.appendChild(el);});row.querySelector('[data-gain]').oninput=function(){t.gain=Number(this.value)/100;save();};row.querySelector('[data-pan]').oninput=function(){t.pan=Number(this.value)/100;save();};row.querySelector('[data-mute]').onclick=function(){t.mute=!t.mute;save('Mute '+(t.mute?'on':'off'));renderTracks();};row.querySelector('[data-solo]').onclick=function(){t.solo=!t.solo;save('Solo '+(t.solo?'on':'off'));renderTracks();};box.appendChild(row);});}
  function renderPatches(){var box=$('patchList');box.innerHTML=project.patches.length?'':'<div class="notice">No synth patches yet.</div>';project.patches.slice().reverse().forEach(function(p){var el=document.createElement('article');el.className='card';el.innerHTML='<b>'+esc(p.name)+'</b><span>'+esc(p.waveform)+' · attack '+p.attack+' · release '+p.release+' · '+p.cutoff+' Hz</span><button>Preview C4</button>';el.querySelector('button').onclick=function(){playTone(C.pitchFrequency('C4'),0,.6,p.waveform,.25,0);};box.appendChild(el);});}
  function renderNotes(){var box=$('noteList'),notes=project.notes.slice().sort(function(a,b){return a.beat-b.beat;});box.innerHTML=notes.length?'':'<div class="notice">No score events yet.</div>';notes.forEach(function(n){var t=project.tracks.find(function(x){return x.id===n.trackId;}),el=document.createElement('div');el.className='list-item';el.innerHTML='<b>'+esc(n.pitch)+' · beat '+n.beat+'</b><span>'+esc(t?t.name:'missing track')+' · '+n.duration+' beats · velocity '+n.velocity+'</span>';box.appendChild(el);});}
  function renderSpatial(){var stage=$('spatialStage');stage.querySelectorAll('.spatial-dot').forEach(function(x){x.remove();});project.spatial.forEach(function(s){var t=project.tracks.find(function(x){return x.id===s.trackId;}),dot=document.createElement('button');dot.className='spatial-dot';dot.style.left=((s.x+1)/2*90+5)+'%';dot.style.top=((1-s.depth)*75+10)+'%';dot.title=t?t.name:'Track';stage.appendChild(dot);});}
  function renderRecordings(){var box=$('recordingList');box.innerHTML=recordings.length?'':'<div class="notice">No recordings in this browser session.</div>';recordings.forEach(function(r){var el=document.createElement('div');el.className='list-item';el.innerHTML='<b>'+esc(r.name)+'</b><audio controls src="'+r.url+'"></audio><a download="'+esc(r.name)+'.webm" href="'+r.url+'">Download take</a>';box.appendChild(el);});}
  function renderRestore(){var box=$('restoreList');box.innerHTML=project.restoration.length?'':'<div class="notice">No restoration renders recorded.</div>';project.restoration.slice().reverse().forEach(function(r){var el=document.createElement('div');el.className='list-item';el.innerHTML='<b>'+esc(r.name)+'</b><span>'+r.highpass+'–'+r.lowpass+' Hz · normalize '+(r.normalize?'yes':'no')+' · '+r.status+'</span>';box.appendChild(el);});}
  function renderGeneration(){var box=$('generationList');box.innerHTML=project.generation.length?'':'<div class="notice">No generated patterns yet.</div>';project.generation.slice().reverse().forEach(function(r){var el=document.createElement('div');el.className='list-item';el.innerHTML='<b>'+esc(r.seed)+'</b><span>'+esc(r.root)+' '+esc(r.scale)+' · '+r.notes+' editable notes</span>';box.appendChild(el);});}
  function renderExports(){var box=$('exportList');box.innerHTML=project.exports.length?'':'<div class="notice">No outputs recorded yet.</div>';project.exports.slice().reverse().forEach(function(r){var el=document.createElement('div');el.className='list-item';el.innerHTML='<b>'+esc(r.name)+'</b><span>'+esc(r.format)+' · '+esc(r.status)+' · '+new Date(r.createdAt).toLocaleString()+'</span>';box.appendChild(el);});var s=C.projectSummary(project);$('renderStatus').textContent=s.renderableClips+' generated clips and '+s.notes+' notes renderable · '+s.sessionOnly+' session-only clips excluded unless separately exported.';}
  function renderAll(){renderHeader();renderSelectors();renderTracks();renderPatches();renderNotes();renderSpatial();renderRecordings();renderRestore();renderGeneration();renderExports();}
  function playProject(){stop();var solo=project.tracks.filter(function(t){return t.solo;}),allowed=solo.length?solo:project.tracks.filter(function(t){return !t.mute;});project.notes.forEach(function(n){var t=allowed.find(function(x){return x.id===n.trackId;});if(!t)return;playTone(C.pitchFrequency(n.pitch),C.beatSeconds(project,n.beat),C.beatSeconds(project,n.duration),'triangle',t.gain*(n.velocity/127)*.35,t.pan);});project.clips.forEach(function(c){var t=allowed.find(function(x){return x.id===c.trackId;});if(!t||c.sourceType==='session-file'||c.sourceType==='recording')return;playTone(c.sourceType==='noise'?90:c.frequency,C.beatSeconds(project,c.startBeat),C.beatSeconds(project,c.durationBeats),c.sourceType==='noise'?'sawtooth':c.waveform,t.gain*.25,t.pan);});toast('Playing supported project sources');}
  function bytesDownload(name,bytes,type){var blob=new Blob([bytes],{type:type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(url);},1500);}
  function jsonDownload(name,data){bytesDownload(name,JSON.stringify(data,null,2),'application/json');}
  function wavBytes(buffer){var channels=buffer.numberOfChannels,length=buffer.length*channels*2,out=new ArrayBuffer(44+length),v=new DataView(out),write=function(off,s){for(var i=0;i<s.length;i++)v.setUint8(off+i,s.charCodeAt(i));};write(0,'RIFF');v.setUint32(4,36+length,true);write(8,'WAVE');write(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,channels,true);v.setUint32(24,buffer.sampleRate,true);v.setUint32(28,buffer.sampleRate*channels*2,true);v.setUint16(32,channels*2,true);v.setUint16(34,16,true);write(36,'data');v.setUint32(40,length,true);var offset=44;for(var i=0;i<buffer.length;i++)for(var c=0;c<channels;c++){var sample=Math.max(-1,Math.min(1,buffer.getChannelData(c)[i]));v.setInt16(offset,sample<0?sample*32768:sample*32767,true);offset+=2;}return out;}
  function vlq(n){var b=[n&127];while(n>>=7)b.unshift((n&127)|128);return b;}
  function exportMidi(){var division=480,events=[],tempo=Math.round(60000000/project.bpm);events.push({tick:0,data:[255,81,3,(tempo>>16)&255,(tempo>>8)&255,tempo&255]});project.notes.forEach(function(n){var note=Math.round(69+12*Math.log2(C.pitchFrequency(n.pitch)/440)),start=Math.round(n.beat*division),end=Math.round((n.beat+n.duration)*division);events.push({tick:start,data:[144,note,n.velocity]});events.push({tick:end,data:[128,note,0]});});events.sort(function(a,b){return a.tick-b.tick||(a.data[0]===128?-1:1);});var track=[],last=0;events.forEach(function(e){track=track.concat(vlq(e.tick-last),e.data);last=e.tick;});track=track.concat([0,255,47,0]);var out=[77,84,104,100,0,0,0,6,0,0,0,1,1,224,77,84,114,107,(track.length>>>24)&255,(track.length>>>16)&255,(track.length>>>8)&255,track.length&255].concat(track);bytesDownload((project.name||'axm-score')+'.mid',new Uint8Array(out),'audio/midi');project.exports.push({id:C.id('export'),name:project.name+' score',format:'MIDI',status:'EXPORTED',createdAt:C.now()});save('MIDI exported');renderExports();}
  async function renderRestored(){if(!restoreFile)return toast('Choose an audio file first');$('restoreStatus').textContent='Decoding and rendering locally…';try{var ac=audio(),src=await ac.decodeAudioData(await restoreFile.arrayBuffer()),rate=src.sampleRate,offline=new OfflineAudioContext(src.numberOfChannels,src.length,rate),node=offline.createBufferSource(),high=offline.createBiquadFilter(),low=offline.createBiquadFilter();node.buffer=src;high.type='highpass';high.frequency.value=Number($('restoreHigh').value);low.type='lowpass';low.frequency.value=Number($('restoreLow').value);node.connect(high);high.connect(low);low.connect(offline.destination);node.start();var rendered=await offline.startRendering();if($('restoreNormalize').checked){var peak=0;for(var c=0;c<rendered.numberOfChannels;c++){var d=rendered.getChannelData(c);for(var i=0;i<d.length;i++)peak=Math.max(peak,Math.abs(d[i]));}if(peak>.0001){var gain=.96/peak;for(var cc=0;cc<rendered.numberOfChannels;cc++){var dd=rendered.getChannelData(cc);for(var ii=0;ii<dd.length;ii++)dd[ii]*=gain;}}}var name=restoreFile.name.replace(/\.[^.]+$/,'')+'-restored';bytesDownload(name+'.wav',wavBytes(rendered),'audio/wav');project.restoration.push({id:C.id('restore'),name:name,highpass:Number($('restoreHigh').value),lowpass:Number($('restoreLow').value),normalize:$('restoreNormalize').checked,status:'RENDERED',createdAt:C.now()});save('Restored WAV rendered');$('restoreStatus').textContent='Rendered '+name+'.wav';renderRestore();}catch(e){$('restoreStatus').textContent='Restore failed: '+e.message;}}
  async function renderMix(){var duration=Math.min(600,Math.max(1,C.beatSeconds(project,project.bars*4)+1)),rate=44100,offline=new OfflineAudioContext(2,Math.ceil(duration*rate),rate),solo=project.tracks.filter(function(t){return t.solo;}),allowed=solo.length?solo:project.tracks.filter(function(t){return !t.mute;});project.notes.forEach(function(n){var t=allowed.find(function(x){return x.id===n.trackId;});if(t)playTone(C.pitchFrequency(n.pitch),C.beatSeconds(project,n.beat),C.beatSeconds(project,n.duration),'triangle',t.gain*(n.velocity/127)*.35,t.pan,offline,offline.destination);});project.clips.forEach(function(c){var t=allowed.find(function(x){return x.id===c.trackId;});if(t&&['tone','noise','generated'].indexOf(c.sourceType)>=0)playTone(c.sourceType==='noise'?90:c.frequency,C.beatSeconds(project,c.startBeat),C.beatSeconds(project,c.durationBeats),c.sourceType==='noise'?'sawtooth':c.waveform,t.gain*.25,t.pan,offline,offline.destination);});try{$('renderStatus').textContent='Rendering supported sources locally…';var rendered=await offline.startRendering(),name=project.name.replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'')||'axm-mix';bytesDownload(name+'.wav',wavBytes(rendered),'audio/wav');project.exports.push({id:C.id('export'),name:name+'.wav',format:'Audio',status:'EXPORTED',createdAt:C.now()});save('WAV mix rendered · session-only sources were not claimed');renderExports();}catch(e){toast('Mix render failed: '+e.message);}}
  function sendPublish(){var packet=C.publishPacket(project,{name:$('publishName').value,format:'Audio',version:$('publishVersion').value,license:$('publishLicense').value,provenance:$('publishProvenance').value}),state;try{state=JSON.parse(localStorage.getItem(PUBLISH)||'null');}catch(e){}if(!state||state.schema!=='axm.publish-library.ledger/v1')state={schema:'axm.publish-library.ledger/v1',artifacts:[],releases:[],updatedAt:null};state.artifacts=Array.isArray(state.artifacts)?state.artifacts:[];var a=packet.artifact;state.artifacts.push({id:C.id('artifact'),name:a.name,source:a.source,format:a.format,version:a.version,license:a.license,provenance:a.provenance,state:'INBOX',createdAt:C.now()});state.updatedAt=C.now();localStorage.setItem(PUBLISH,JSON.stringify(state));toast('Sent to Publish & Library as unreviewed');}
  function bind(){
    $('playAll').onclick=playProject;$('stopAll').onclick=stop;$('bpm').onchange=function(){project.bpm=Math.max(30,Math.min(300,Number(this.value)||120));save('Tempo updated');renderHeader();};$('bars').onchange=function(){project.bars=Math.max(1,Math.min(512,Number(this.value)||16));save('Timeline length updated');renderHeader();};$('timeSignature').onchange=function(){project.timeSignature=this.value;save('Time signature updated');};$('playhead').oninput=function(){var beat=Number(this.value);$('clock').textContent=String(Math.floor(beat/4)+1).padStart(3,'0')+'.'+(Math.floor(beat%4)+1)+' · '+Math.floor(C.beatSeconds(project,beat)/60).toString().padStart(2,'0')+':'+Math.floor(C.beatSeconds(project,beat)%60).toString().padStart(2,'0');};
    $('trackForm').onsubmit=function(e){e.preventDefault();C.addTrack(project,{name:$('trackName').value,type:$('trackType').value});e.target.reset();save('Track added');renderAll();};$('clipForm').onsubmit=function(e){e.preventDefault();try{C.addClip(project,{trackId:$('clipTrack').value,name:$('clipName').value,startBeat:Number($('clipStart').value),durationBeats:Number($('clipDuration').value),sourceType:$('clipSource').value,color:'#36d6ec'});save('Clip added');e.target.reset();renderAll();}catch(err){toast(err.message);}};
    $('previewPatch').onclick=function(){playTone(C.pitchFrequency($('patchPitch').value),0,.7,$('patchWave').value,.25,0);};$('patchForm').onsubmit=function(e){e.preventDefault();project.patches.push(C.normalizePatch({name:$('patchName').value,waveform:$('patchWave').value,attack:$('patchAttack').value,release:$('patchRelease').value,cutoff:$('patchCutoff').value}));save('Synth patch saved');e.target.reset();renderPatches();};
    $('noteForm').onsubmit=function(e){e.preventDefault();try{C.addNote(project,{trackId:$('noteTrack').value,pitch:$('notePitch').value.toUpperCase(),beat:$('noteBeat').value,duration:$('noteDuration').value,velocity:$('noteVelocity').value});save('Score note added');renderNotes();}catch(err){toast(err.message);}};$('playScore').onclick=playProject;$('exportMidi').onclick=exportMidi;
    $('spatialForm').onsubmit=function(e){e.preventDefault();var id=$('spatialTrack').value;if(!id)return toast('Choose a track');project.spatial=project.spatial.filter(function(s){return s.trackId!==id;});project.spatial.push({id:C.id('space'),trackId:id,x:Number($('spatialX').value)/100,depth:Number($('spatialDepth').value)/100,width:Number($('spatialWidth').value)/100,createdAt:C.now()});var t=project.tracks.find(function(x){return x.id===id;});if(t)t.pan=Number($('spatialX').value)/100;save('Spatial position saved');renderSpatial();};$('previewSpatial').onclick=function(){playTone(440,0,.7,'sine',.22,Number($('spatialX').value)/100);};
    $('startRecord').onclick=async function(){try{var stream=await navigator.mediaDevices.getUserMedia({audio:true}),name=clean($('voiceName').value,80)||'voice-take-'+(recordings.length+1);recordChunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=function(e){if(e.data.size)recordChunks.push(e.data);};recorder.onstop=function(){var blob=new Blob(recordChunks,{type:recorder.mimeType||'audio/webm'}),url=URL.createObjectURL(blob);recordings.push({name:name,url:url,blob:blob});stream.getTracks().forEach(function(t){t.stop();});$('recordStatus').textContent='Recorded '+name+' · session file ready to download';renderRecordings();};recorder.start();$('startRecord').disabled=true;$('stopRecord').disabled=false;$('recordStatus').textContent='Recording…';}catch(e){$('recordStatus').textContent='Microphone unavailable: '+e.message;}};$('stopRecord').onclick=function(){if(recorder&&recorder.state!=='inactive')recorder.stop();$('startRecord').disabled=false;$('stopRecord').disabled=true;};
    $('restoreFile').onchange=function(){restoreFile=this.files&&this.files[0];$('restoreStatus').textContent=restoreFile?'Ready: '+restoreFile.name:'Choose a local audio file.';};$('renderRestore').onclick=renderRestored;
    $('generateForm').onsubmit=function(e){e.preventDefault();var settings={seed:$('generateSeed').value,root:$('generateRoot').value,scale:$('generateScale').value,bars:Number($('generateBars').value),density:Number($('generateDensity').value)},notes=C.generatePattern(settings),track=project.tracks.find(function(t){return t.type==='instrument';});if(!track)track=C.addTrack(project,{name:'Generated music',type:'instrument'});notes.forEach(function(n){C.addNote(project,Object.assign({trackId:track.id},n));});project.generation.push({id:C.id('gen'),seed:settings.seed,root:settings.root,scale:settings.scale,bars:settings.bars,density:settings.density,notes:notes.length,createdAt:C.now()});save('Generated '+notes.length+' editable notes');renderAll();};
    $('renderMix').onclick=renderMix;$('masterExportProject').onclick=function(){jsonDownload('AXM_AUDIO_'+project.name.replace(/[^a-z0-9]+/gi,'-')+'.json',project);toast('Audio project exported');};$('exportProject').onclick=$('masterExportProject').onclick;$('publishForm').onsubmit=function(e){e.preventDefault();sendPublish();};
    window.addEventListener('message',function(e){if(e.origin!==location.origin||!e.data||e.data.schema!=='axm.audio.sound/v1')return;var sound=e.data.sound||{},track=project.tracks.find(function(t){return t.type==='foley';});if(!track)track=C.addTrack(project,{name:'Sound effects',type:'foley'});var p=sound.params||{};C.addClip(project,{trackId:track.id,name:sound.name,startBeat:0,durationBeats:Math.max(.25,(Number(p.dur)||.15)*project.bpm/60),sourceType:p.kind==='noise'?'noise':'tone',frequency:p.freq,waveform:p.wave,color:'#efbc55'});save('Sound Lab effect added to shared timeline');renderAll();});
  }
  async function init(){buildNav();load();C.TRACK_TYPES.forEach(function(t){var o=document.createElement('option');o.value=t;o.textContent=t;$('trackType').appendChild(o);});bind();renderAll();selectMode('arrange');if(window.AXM&&AXM.init)await AXM.init({id:'audio-studio',name:'AXM Audio Studio',version:'v1.0'});if(window.AXMHub){AXMHub.ready({version:'v1.0',capabilities:['multitrack','mixer','sound-lab','synth','midi-export','spatial-audio','voice-recording','restoration','generative-music','wav-render','publish-handoff']});AXMHub.verifyPass();}toast('Audio Studio ready · listen before approval');}
  init().catch(function(e){toast('Audio Studio failed: '+e.message);});
})();
