(function(){'use strict';var Core=window.AXMNeuralVisual,$=function(id){return document.getElementById(id);},request=null,requestBinding=null,verified=null,hubInitialized=false;
function value(id){return $(id).value;}function setStatus(message,kind){$('resultStatus').textContent=message;$('resultStatus').className='result '+kind;}
function formRequest(){return Core.normalizeRequest({operation:value('operation'),prompt:value('prompt'),negative_prompt:value('negative'),strength:Number(value('strength')),seed:value('seed'),source_draft_digest:value('sourceDigest'),target_canvas:{width:Number(value('width')),height:Number(value('height')),colour_space:'srgb',alpha:true}});}
async function prepare(){try{request=formRequest();requestBinding=await Core.requestSha256(request);verified=null;$('requestView').textContent=JSON.stringify(request,null,2);$('sendDraft').disabled=true;$('preview').style.display='none';$('emptyPreview').style.display='block';setStatus('Request ready · '+requestBinding+' · provider execution still required','neutral');save();return request;}catch(e){requestBinding=null;setStatus(e.message,'fail');return null;}}
function download(name,data){var a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(a.href);},1000);}
async function verify(){if(!request)return setStatus('Prepare the exact request first.','fail');try{var raw=JSON.parse(value('resultInput')),check=await Core.verifyResult(raw,request);if(!check.pass){verified=null;$('sendDraft').disabled=true;return setStatus('REJECTED · '+check.errors.join(' · '),'fail');}verified=check.result;if(verified.status!=='PROPOSED')return setStatus(verified.status+' · provider returned no candidate layer','fail');$('preview').src=verified.artifact.data_url;$('preview').style.display='block';$('emptyPreview').style.display='none';$('sendDraft').disabled=false;$('providerStatus').textContent='VERIFIED PROVIDER PROPOSAL';$('providerStatus').className='status pass';setStatus('PASS · exact request and image SHA-256 match · still candidate-only','pass');AXMHub.log('Neural Room verified a candidate-only provider result');}catch(e){verified=null;$('sendDraft').disabled=true;setStatus('REJECTED · '+e.message,'fail');}}
function send(){if(!verified||!request)return;var envelope={schema:'axm.neural-room-transfer/v1',created_at:new Date().toISOString(),expires_at:new Date(Date.now()+600000).toISOString(),request:request,result:verified};localStorage.setItem('axm.neural-room.transfer.v1',JSON.stringify(envelope));setStatus('Candidate transfer prepared for Draft Room · expires in 10 minutes','pass');AXMHub.log('Explicit ephemeral neural candidate transfer prepared');}
function save(){if(!hubInitialized)return;AXMHub.save({operation:value('operation'),prompt:value('prompt'),negative:value('negative'),strength:value('strength'),seed:value('seed'),width:value('width'),height:value('height'),sourceDigest:value('sourceDigest'),lastRequestDigest:requestBinding});}
$('strength').oninput=function(){$('strengthValue').textContent=this.value;};$('prepare').onclick=prepare;$('verify').onclick=verify;$('sendDraft').onclick=send;$('downloadRequest').onclick=async function(){if(!request)await prepare();if(request)download('axm-neural-request.json',request);};$('resultFile').onchange=function(){var file=this.files&&this.files[0];if(!file)return;var reader=new FileReader();reader.onload=function(){$('resultInput').value=String(reader.result||'');};reader.readAsText(file);};
function restore(init){var s=init&&init.moduleState||{};['operation','prompt','negative','strength','seed','width','height','sourceDigest'].forEach(function(id){if(s[id]!=null)$(id).value=s[id];});$('strengthValue').textContent=$('strength').value;var transfer=localStorage.getItem('axm.visual-draft.neural-request.v1');if(transfer){try{var env=JSON.parse(transfer);if(Date.parse(env.expires_at)>Date.now()){var r=env.request||{};$('prompt').value=r.prompt||'';$('negative').value=r.negative_prompt||'';$('operation').value=r.operation||'refine';$('strength').value=r.strength==null?.55:r.strength;$('strengthValue').textContent=$('strength').value;$('seed').value=r.seed||'axiom-seed';$('sourceDigest').value=r.source_draft_digest||'no-source-draft';$('width').value=r.target_canvas.width;$('height').value=r.target_canvas.height;prepare();}localStorage.removeItem('axm.visual-draft.neural-request.v1');}catch(e){localStorage.removeItem('axm.visual-draft.neural-request.v1');}}}
AXMHub.onInit(function(init){hubInitialized=true;restore(init);});AXMHub.onShutdown(save);AXMHub.ready({id:'neural-room',name:'Neural Room',version:'v0.1',hubApiVersion:'1.0',permissions:[],savesState:true,handlesShutdown:true});restore(null);
})();
