(function(){
'use strict';
var Core=window.AXMGovernedEvolution,Pulse=window.AXMBodyPulseClient,PULSE_MODULE_ID='governed-evolution-lab',STORAGE_KEY='axm.governed-evolution-lab.v1',EXAM_STEP_SECONDS=20,lineage=null,running=false,stopRequested=false,totalExams=0,completedExams=0,heartbeatActive=false,heartbeatTimer=null;
var $=function(id){return document.getElementById(id);};
function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(ch){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[ch];});}
function rankingText(event){return(event.ranking||[]).map(function(entry){return'#'+entry.rank+' '+entry.id+' '+Number(entry.score).toFixed(3)+(entry.collapsed?' · collapsed '+entry.collapsed:'');}).join(' | ')||'ranking unavailable';}
function setRun(state,detail){$('runState').textContent=state;$('progressText').textContent=detail||state;if(window.AXMHub&&AXMHub.log)AXMHub.log('evolution '+state+' · '+(detail||''));}
function save(){lineage.updatedAt=new Date().toISOString();localStorage.setItem(STORAGE_KEY,JSON.stringify(lineage));if(window.AXMHub&&AXMHub.save)AXMHub.save({lineageId:lineage.lineageId,generation:lineage.generation,currentGenomeDigest:lineage.currentGenomeDigest});}
function load(){try{var raw=localStorage.getItem(STORAGE_KEY);lineage=raw?JSON.parse(raw):Core.emptyLineage('mirror-world-seed-0');if(!lineage||lineage.schema!==Core.LINEAGE_SCHEMA)throw new Error('wrong lineage schema');}catch(e){lineage=Core.emptyLineage('mirror-world-seed-0');}if(!lineage.heartbeat)lineage.heartbeat={mode:'body-pulse-leased',totalBeats:0,skippedBeats:0,heldBeats:0,lastBeatAt:null,lastStatus:'never-started',goalId:null,events:[]};lineage.heartbeat.mode='body-pulse-leased';lineage.heartbeat.heldBeats=Number(lineage.heartbeat.heldBeats)||0;save();}
function render(){
  $('generation').textContent=lineage.generation;$('lineageId').textContent=lineage.lineageId;$('genomeDigest').textContent=lineage.currentGenomeDigest;$('genomeJson').textContent=JSON.stringify(lineage.currentGenome,null,2);
  var receipt=lineage.lastReceipt;$('lastOutcome').textContent=!receipt?'UNRUN':receipt.inherited?'INHERITED':'PARENT HELD';$('lastOutcome').style.color=receipt&&receipt.inherited?'var(--green)':'var(--gold)';$('lastReason').textContent=receipt?receipt.reason:'No exam yet.';$('inheritance').textContent=receipt&&receipt.inherited?(receipt.mutations.length+' inherited mutation'+(receipt.mutations.length===1?'':'s')):'original or retained parent';
  $('historyCount').textContent=lineage.history.length+' event'+(lineage.history.length===1?'':'s');$('history').innerHTML=lineage.history.length?lineage.history.slice().reverse().map(function(event){return'<div class="event"><b>GEN '+event.generation+'</b><div><strong class="'+(event.inherited?'inherited':'held')+'">'+(event.inherited?'INHERITED':'PARENT HELD')+'</strong><small>'+esc(event.reason)+'</small><small>'+(event.mutations.length?event.mutations.map(function(m){return esc(m.gene)+' '+m.before+' → '+m.after;}).join(' · '):'no genome change')+'</small><small>trigger: '+esc(event.trigger||'manual')+' · exam: '+esc(event.examPlan?event.examPlan.id:'legacy-unversioned')+'</small><small class="ranking">'+esc(rankingText(event))+'</small></div><code>'+esc(event.selectedDigest)+'</code></div>';}).join(''):'<div class="empty">No generations yet. The immutable seed is waiting.</div>';
  renderHeartbeat();
}
async function mirrorJson(path,options){var response=await fetch('/services/mirror-native'+path,Object.assign({headers:{'content-type':'application/json'}},options||{})),body=await response.json().catch(function(){return{};});if(!response.ok)throw new Error(body.error||('Mirror request failed ('+response.status+')'));return body;}
async function checkMirror(){try{var health=await mirrorJson('/health');var ready=health&&health.ok&&health.worldGenomeOrgan;$('mirrorDot').style.background=ready?'var(--green)':'var(--gold)';$('mirrorState').textContent=ready?'Mirror world organ ready':'Mirror online · organ missing';return!!ready;}catch(e){$('mirrorDot').style.background='var(--red)';$('mirrorState').textContent='Mirror offline';return false;}}
async function requestCandidates(){var sessionId=null;try{var opened=await mirrorJson('/axm/v1/session/open',{method:'POST',body:JSON.stringify({actor:{id:'governed-evolution-lab',kind:'workshop-module'},purpose:'Originate private genome challengers for Mirror\'s disposable Grafthold lineage.'})});sessionId=opened.session.id;var result=await mirrorJson('/axm/v1/organs/world-genome-candidates',{method:'POST',body:JSON.stringify({sessionId:sessionId,surface:'axm-governed-evolution-disposable-globe',lineageSeed:lineage.lineageSeed,generation:lineage.generation,count:3,parentGenome:lineage.currentGenome})});return result.candidateSet;}finally{if(sessionId)await mirrorJson('/axm/v1/session/close',{method:'POST',body:JSON.stringify({sessionId:sessionId})}).catch(function(){});}}
function worldUrl(genome,extra){var query=Core.genomeQuery(genome);return 'subject/grafthold-globe-v0.9.html?'+query+(extra?'&'+extra:'');}
function runExam(genome,seed,years,label){return new Promise(function(resolve,reject){var runId='exam-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,8),frame=$('subjectFrame'),timer;
    function done(event){if(event.origin!==location.origin||event.source!==frame.contentWindow||!event.data||event.data.type!=='axm.governed-evolution.world-exam-result/v1'||event.data.runId!==runId)return;cleanup();completedExams++;$('examCounter').textContent=completedExams+' / '+totalExams;$('progressBar').style.width=(completedExams/Math.max(1,totalExams)*100).toFixed(2)+'%';resolve(event.data.result);}
    function cleanup(){clearTimeout(timer);removeEventListener('message',done);}addEventListener('message',done);timer=setTimeout(function(){cleanup();reject(new Error('world exam timed out for '+label+' seed '+seed));},60000);$('examTitle').textContent=label+' · seed '+seed;frame.src=worldUrl(genome,'exam='+years+'&examstep='+EXAM_STEP_SECONDS+'&wseed='+seed+'&seasons=on&runid='+encodeURIComponent(runId));});}
async function examine(entry,seeds,years){var results=[];for(var i=0;i<seeds.length;i++){if(stopRequested)throw new Error('STOP_REQUESTED');setRun('examining',entry.id+' · world '+(i+1)+' / '+seeds.length);results.push(await runExam(entry.genome,seeds[i],years,entry.id));}return Core.aggregate(entry.id,entry.genome,results);}
async function generation(trigger){var candidateSet=await requestCandidates(),seeds=Core.examSeeds(lineage.lineageSeed,lineage.generation,3),samples=12,examPlan={id:'ecology-epoch-v1',samples:samples,sampleSeconds:EXAM_STEP_SECONDS,sampleUnit:'ecology-epoch'},entries=[{id:'current-parent-g'+lineage.generation,genome:lineage.currentGenome}].concat(candidateSet.candidates.map(function(c){return{id:c.id,genome:c.genome};}));totalExams=entries.length*seeds.length;completedExams=0;$('examCounter').textContent='0 / '+totalExams;$('progressBar').style.width='0%';var aggregates=[];for(var i=0;i<entries.length;i++)aggregates.push(await examine(entries[i],seeds,samples));var parent=aggregates[0],selection=Core.select(parent,aggregates.slice(1)),advanced=Core.inherit(lineage,selection,candidateSet,seeds,examPlan,trigger||'manual');lineage=advanced.lineage;save();render();setRun(advanced.receipt.inherited?'inherited':'held',advanced.receipt.reason);return advanced.receipt;}
async function run(count,trigger){if(running)return false;if(!(await checkMirror())){setRun('held','Mirror world-genome organ is not available. Start Mirror, then retry.');return false;}running=true;stopRequested=false;$('runOne').disabled=true;$('runFive').disabled=true;$('stop').disabled=false;try{for(var i=0;i<count;i++){if(stopRequested)break;setRun('generation '+(lineage.generation+1),'Mirror is originating private challengers.');await generation(trigger||'manual');}if(stopRequested)setRun('stopped','The current completed evidence remains; no partial inheritance was recorded.');return !stopRequested;}catch(e){if(e.message==='STOP_REQUESTED')setRun('stopped','Stopped before another exam. No partial generation was inherited.');else{setRun('error',e.message);console.error(e);}return false;}finally{running=false;$('runOne').disabled=false;$('runFive').disabled=false;$('stop').disabled=true;}}
function heartbeatRecord(status,reason){var pulse=lineage.heartbeat||(lineage.heartbeat={mode:'body-pulse-leased',totalBeats:0,skippedBeats:0,heldBeats:0,lastBeatAt:null,lastStatus:'never-started',goalId:null,events:[]}),at=new Date().toISOString();pulse.mode='body-pulse-leased';pulse.lastBeatAt=at;pulse.lastStatus=status+(reason?': '+reason:'');pulse.events=Array.isArray(pulse.events)?pulse.events:[];if(status==='pulse')pulse.totalBeats++;if(status==='busy-skip')pulse.skippedBeats++;if(status==='held')pulse.heldBeats=(pulse.heldBeats||0)+1;pulse.events.push({at:at,status:status,reason:reason||'',generation:lineage.generation});if(pulse.events.length>200)pulse.events=pulse.events.slice(-200);save();}
function renderHeartbeat(){if(!$('heartbeatState'))return;var pulse=lineage.heartbeat||{},cadence=Number($('heartbeatCadence').value||900000);$('heartbeatState').textContent=heartbeatActive?'Requesting every '+Math.round(cadence/60000)+' minutes':'Stopped';$('heartbeatDetail').textContent=(pulse.totalBeats||0)+' leased beat'+((pulse.totalBeats||0)===1?'':'s')+' · '+(pulse.heldBeats||0)+' held · '+(pulse.skippedBeats||0)+' busy skip'+((pulse.skippedBeats||0)===1?'':'s')+(pulse.lastBeatAt?' · last '+new Date(pulse.lastBeatAt).toLocaleTimeString():'');$('heartbeatToggle').textContent=heartbeatActive?'Stop heartbeat':'Start heartbeat';$('heartbeatToggle').classList.toggle('danger',heartbeatActive);$('heartbeatCadence').disabled=heartbeatActive;$('pulseTag').textContent=heartbeatActive?'body-governed':'pulse stopped';}
function pulseModule(enabled){if(!Pulse)return Promise.reject(new Error('Body Pulse client unavailable'));var cadence=Number($('heartbeatCadence').value||900000);return Pulse.register({moduleId:PULSE_MODULE_ID,name:'Governed Evolution Lab',goalQueueId:'governed-evolution-goals',enabled:enabled===true,allowMaintenance:false,priority:65,activeCadenceMs:cadence,idleCadenceMs:3600000,cost:{cpu:65,memory:35,gpu:45},authority:'disposable-lineage-only',promotionGate:'no-canonical-promotion'});}
function scheduleHeartbeat(){clearTimeout(heartbeatTimer);if(!heartbeatActive)return;heartbeatTimer=setTimeout(heartbeatCycle,Number($('heartbeatCadence').value||900000));}
async function heartbeatCycle(){if(!heartbeatActive)return;if(running){heartbeatRecord('busy-skip');renderHeartbeat();scheduleHeartbeat();return;}try{var decision=await Pulse.runOnce(PULSE_MODULE_ID,async function(){var completed=await run(1,'body-pulse');if(!completed)throw new Error('generation did not complete');heartbeatRecord('pulse');renderHeartbeat();return{summary:'Governed Evolution Lab completed one disposable world generation.',effect:'browser-local-disposable-lineage-only'};},{leaseMs:900000});if(!decision.granted){heartbeatRecord('held',decision.reason);renderHeartbeat();setRun('heartbeat held','Body Pulse held this generation: '+decision.reason+'. The lineage remains alive and unchanged.');}}catch(error){heartbeatRecord('held',error.message);renderHeartbeat();setRun('heartbeat held',error.message);}scheduleHeartbeat();}
async function startHeartbeat(){if(heartbeatActive)return;heartbeatActive=true;lineage.heartbeat.goalId='governed-world-run-'+Date.now().toString(36);heartbeatRecord('started');renderHeartbeat();setRun('heartbeat requesting','Registering one bounded world-lineage goal with Body Pulse.');try{await pulseModule(true);await Pulse.goal({goalId:lineage.heartbeat.goalId,moduleId:PULSE_MODULE_ID,queueId:'governed-evolution-goals',title:'Run a bounded disposable world lineage batch',priority:65,maxPulses:6,status:'OPEN',createdBy:'mike-explicit-heartbeat-start',requiresReview:true});await heartbeatCycle();}catch(error){heartbeatRecord('held',error.message);renderHeartbeat();setRun('heartbeat held',error.message);scheduleHeartbeat();}}
function stopHeartbeat(){if(!heartbeatActive)return;heartbeatActive=false;clearTimeout(heartbeatTimer);heartbeatTimer=null;heartbeatRecord('stopped');renderHeartbeat();setRun('heartbeat stopped','No new automatic generation will begin. Any active exam may finish.');if(Pulse)pulseModule(false).catch(function(){});}
function download(name,type,content){var blob=new Blob([content],{type:type}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(function(){URL.revokeObjectURL(a.href);a.remove();},500);}
function appendFrontierRoutes(room,at){room.cards=Array.isArray(room.cards)?room.cards:[];room.decisions=Array.isArray(room.decisions)?room.decisions:[];function addCard(card){if(!room.cards.some(function(item){return item.id===card.id;}))room.cards.push(card);}addCard({id:'card-globe-heartbeat',title:'Observe automatic globe generations under a visible heartbeat',description:'Preserve every inherited or held generation and determine whether a persistent service heartbeat is justified.',stage:'testing',ownerType:'machine',ownerName:'Mirror with Axiom/Mir stewardship',goalId:'',milestoneId:'milestone-governed-evolution-frontier-2026-07-17',dueDate:'',evidence:[],createdAt:at,updatedAt:at,completedAt:''});addCard({id:'card-twin-workshop-lineages',title:'Future experiment: twin Workshop lineages',description:'Freeze one Workshop ancestor. Let one descendant grow through governed evolution and one through human-machine collaboration, then compare receipts and divergence.',stage:'ideas',ownerType:'shared',ownerName:'Mike × Axiom/Mir × Mirror',goalId:'',milestoneId:'',dueDate:'',evidence:[],createdAt:at,updatedAt:at,completedAt:''});addCard({id:'card-real-world-consent-constitution',title:'Future route: real-world consent and cross-check constitution',description:'Require affected-party consent, independent human and machine recommendations, shadow trials, physical interlocks and HOLD conditions before any connected real-world substrate receives a live change.',stage:'ideas',ownerType:'shared',ownerName:'Human and machine stewards',goalId:'',milestoneId:'',dueDate:'',evidence:[],createdAt:at,updatedAt:at,completedAt:''});}
function appendCreationRung(room,at){room.cards=Array.isArray(room.cards)?room.cards:[];if(room.cards.some(function(item){return item.id==='card-open-ended-creation-rung';}))return;room.cards.push({id:'card-open-ended-creation-rung',title:'Build the creation organ beyond the patch loop',description:'Add novelty search, diversity preservation, changing niches, structural invention, characterization before scoring, and an earned route for extending the inspectable representation itself. The current fixed-genome optimizer is adaptation proof only.',stage:'next',ownerType:'shared',ownerName:'Mike × Axiom/Mir × Mirror',goalId:'',milestoneId:'milestone-governed-evolution-frontier-2026-07-17',dueDate:'',evidence:['logs/AXM_MILESTONE_2026-07-17_GOVERNED_EVOLUTION_FRONTIER.txt · Creation Seam'],createdAt:at,updatedAt:at,completedAt:''});}
function appendFabricRung(room,at){room.cards=Array.isArray(room.cards)?room.cards:[];function add(card){if(!room.cards.some(function(item){return item.id===card.id;}))room.cards.push(card);}add({id:'card-asset-fabric-first-rung',title:'Test the Asset Fabric first creation rung',description:'Use real game or Workshop needs to generate small local candidate families, preserve technical and visual diversity, and dual-review useful primitives before any downstream handoff.',stage:'testing',ownerType:'shared',ownerName:'Mike × Axiom/Mir',goalId:'',milestoneId:'milestone-governed-evolution-frontier-2026-07-17',dueDate:'',evidence:['logs/AXM_MILESTONE_2026-07-17_ASSET_FABRIC_FIRST_RUNG.txt'],createdAt:at,updatedAt:at,completedAt:''});add({id:'card-evolution-foundry-control-room',title:'Verify Evolution Foundry child isolation',description:'Confirm the parent can observe and open each experiment but cannot start a child heartbeat, merge state, promote output or inherit child authority.',stage:'testing',ownerType:'shared',ownerName:'Mike × Axiom/Mir',goalId:'',milestoneId:'',dueDate:'',evidence:['tools/evolution-foundry/module.contract.json'],createdAt:at,updatedAt:at,completedAt:''});}
function appendFrontierEvidence(room,at){var evidence=['Governed Evolution Lab generation 9 · heartbeat · ecology-epoch-v1 · INHERITED · log: logs/AXM_MILESTONE_2026-07-17_GOVERNED_EVOLUTION_FRONTIER.txt','Governed Evolution Lab stopped at generation 13 after thermal cooldown check · final receipt INHERITED · heartbeat now defaults to 15 minutes'];(room.cards||[]).forEach(function(card){if(card.id!=='card-first-globe-generation'&&card.id!=='card-globe-heartbeat')return;card.evidence=Array.isArray(card.evidence)?card.evidence:[];evidence.forEach(function(item){if(card.evidence.indexOf(item)<0)card.evidence.push(item);});card.updatedAt=at;});}
function recordMilestone(){var key='axm.project-room.v1',room=null,at=new Date().toISOString(),id='milestone-governed-evolution-frontier-2026-07-17';try{room=JSON.parse(localStorage.getItem(key)||'null');}catch(e){}if(!room||room.format!=='axm.project-room/v1'){room={format:'axm.project-room/v1',version:2,project:{title:'Untitled project',summary:'',status:'planning',lead:'',createdAt:at,updatedAt:at},cards:[],goals:[],milestones:[],decisions:[],documents:[],messages:[],events:[],forms:[],reviews:[],activity:[],versions:[],updatedAt:at};}room.milestones=Array.isArray(room.milestones)?room.milestones:[];room.documents=Array.isArray(room.documents)?room.documents:[];room.activity=Array.isArray(room.activity)?room.activity:[];var keptActivity=false;room.activity=room.activity.filter(function(item){if(item.id!==id+'-activity')return true;if(keptActivity)return false;keptActivity=true;return true;});if(!room.milestones.some(function(m){return m.id===id;}))room.milestones.push({id:id,title:'Governed evolution loop generalized beyond language',goalId:'',targetDate:'',createdAt:at});if(!room.documents.some(function(d){return d.id===id+'-log';}))room.documents.push({id:id+'-log',title:'Frontier log · systems may evolve when they can be honestly examined',kind:'spec',body:'Mirror\'s baseline → challenger → unseen exam → seam → inherit/hold → receipt loop is substrate-independent. The first non-language subject is a disposable Grafthold globe lineage. Automatic inheritance is allowed only inside that lineage; canonical worlds and Workshop structures remain outside it. See logs/AXM_MILESTONE_2026-07-17_GOVERNED_EVOLUTION_FRONTIER.txt.',createdAt:at,updatedAt:at});if(!room.activity.some(function(item){return item.id===id+'-activity';}))room.activity.push({id:id+'-activity',title:'Milestone recorded: governed evolution frontier',kind:'milestone-handoff',actor:'Governed Evolution Lab',createdAt:at});appendFrontierRoutes(room,at);appendCreationRung(room,at);appendFabricRung(room,at);appendFrontierEvidence(room,at);room.updatedAt=at;room.project=room.project||{};room.project.updatedAt=at;localStorage.setItem(key,JSON.stringify(room));$('milestone').textContent='Milestone recorded';setRun('milestone','Appended adaptation proof, creation seam, Asset Fabric and Foundry routes to Project Room without replacing existing state.');}
function bind(){$('runOne').onclick=function(){run(1,'manual');};$('runFive').onclick=function(){run(5,'manual');};$('stop').onclick=function(){stopRequested=true;$('stop').disabled=true;setRun('stop requested','The active world finishes its current exam; no partial generation will inherit.');};$('heartbeatToggle').onclick=function(){if(heartbeatActive)stopHeartbeat();else startHeartbeat();};$('openWorld').onclick=function(){window.open(worldUrl(lineage.currentGenome,'wseed='+Core.examSeeds(lineage.lineageSeed,lineage.generation,1)[0]+'&seasons=on'),'_blank','noopener');};$('reset').onclick=function(){if(running||!confirm('Give Mirror a fresh disposable globe? The current lineage remains available only if you export it first.'))return;lineage=Core.emptyLineage('mirror-world-seed-0');lineage.heartbeat={mode:'body-pulse-leased',totalBeats:0,skippedBeats:0,heldBeats:0,lastBeatAt:null,lastStatus:'reset',goalId:null,events:[]};save();render();$('subjectFrame').src='about:blank';setRun('reset','A new immutable seed globe is now generation 0.');};$('exportJson').onclick=function(){download('mirror-globe-lineage-g'+lineage.generation+'.json','application/json',JSON.stringify(lineage,null,2));};$('exportTxt').onclick=function(){download('mirror-globe-lineage-g'+lineage.generation+'.txt','text/plain',Core.lineageText(lineage));};$('milestone').onclick=recordMilestone;}
async function init(){load();bind();render();await checkMirror();setRun('idle','Explicit start required. Automatic generations request bounded Body Pulse leases while this page is open.');if(window.AXMHub){AXMHub.onShutdown(function(){stopHeartbeat();save();});AXMHub.ready({id:'governed-evolution-lab',name:'Governed Evolution Lab',version:'v0.2-body-pulse',hubApiVersion:'1.0',permissions:[],savesState:true,handlesShutdown:true,notes:'EXPERIMENTAL · body-governed automatic inheritance only inside a disposable browser-local globe lineage.'});}}
init();
})();
