(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.AXMGovernedEvolution=api;})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';

var VERSION='0.1.1';
var GENOME_SCHEMA='axm.grafthold.world-genome/v1';
var LINEAGE_SCHEMA='axm.governed-evolution.lineage/v1';
var RECEIPT_SCHEMA='axm.governed-evolution.receipt/v1';
var BASELINE={schema:GENOME_SCHEMA,mature:8,lifespan:60,seedFrom:32,offspring:1.2,crowdRadius:3.2,crowdPenalty:0.28,shadePenalty:0.35,minCondition:0.15,treeMinDist:2.2,startTrees:14};
var GENE_KEYS=['mature','lifespan','seedFrom','offspring','crowdRadius','crowdPenalty','shadePenalty','minCondition','treeMinDist','startTrees'];

function clone(v){return JSON.parse(JSON.stringify(v));}
function now(){return new Date().toISOString();}
function finite(v){return typeof v==='number'&&Number.isFinite(v);}
function hash(value){var s=JSON.stringify(value),out=2166136261;for(var i=0;i<s.length;i++){out^=s.charCodeAt(i);out=Math.imul(out,16777619);}return(out>>>0).toString(16).padStart(8,'0');}
function genome(input){var source=input&&typeof input==='object'?input:{},out={schema:GENOME_SCHEMA};GENE_KEYS.forEach(function(key){out[key]=finite(Number(source[key]))?Number(source[key]):BASELINE[key];});return out;}
function genomeDiff(parent,child){parent=genome(parent);child=genome(child);return GENE_KEYS.filter(function(key){return parent[key]!==child[key];}).map(function(key){return{gene:key,before:parent[key],after:child[key],delta:Number((child[key]-parent[key]).toFixed(6))};});}
function emptyLineage(seed){var parent=genome(BASELINE),at=now();return{schema:LINEAGE_SCHEMA,status:'EXPERIMENTAL',lineageId:'mirror-grafthold-'+hash(seed||'mirror-world-seed-0'),lineageSeed:String(seed||'mirror-world-seed-0'),generation:0,currentGenome:parent,currentGenomeDigest:hash(parent),createdAt:at,updatedAt:at,direction:{id:'balanced-longevity-v1',statement:'Prefer ecologies that remain alive without runaway growth while preserving visible birth-and-death turnover across unseen seeded worlds.',proxyWarning:'This measures a declared gameplay-ecology proxy, not fun, beauty, moral value or scientific fitness.'},history:[],lastCandidateSet:null,lastReceipt:null};}
function scoreRun(result){
  if(!result||!Array.isArray(result.series)||!result.series.length)return{score:-10000,components:{invalid:-10000},verdict:'INVALID'};
  var series=result.series,start=Math.max(1,Number(series[0].trees)||0),end=Math.max(0,Number(result.endTrees)||0),min=Math.max(0,Number(result.minTrees)||0),max=Math.max(0,Number(result.maxTrees)||0);
  var collapsed=result.verdict==='COLLAPSED'||min===0;
  var survival=collapsed?-500:120;
  var ratio=end/start;
  var continuity=collapsed?-100:Math.max(-120,80-Math.abs(Math.log(Math.max(0.01,ratio)))*55);
  var range=max/start;
  var bounded=collapsed?-80:Math.max(-120,55-Math.max(0,range-2)*28);
  var activeYears=series.filter(function(p){return(Number(p.born)||0)>0&&(Number(p.died)||0)>0;}).length;
  var turnover=40*(activeYears/series.length);
  var fragile=result.verdict==='FRAGILE'?-70:0;
  var score=survival+continuity+bounded+turnover+fragile;
  return{score:Number(score.toFixed(6)),components:{survival:survival,continuity:Number(continuity.toFixed(6)),boundedGrowth:Number(bounded.toFixed(6)),turnover:Number(turnover.toFixed(6)),fragility:fragile},verdict:result.verdict,startTrees:start,endTrees:end,minTrees:min,maxTrees:max};
}
function aggregate(id,genomeValue,runs){var scored=(runs||[]).map(function(result){return{seed:result.seed,years:result.years,score:scoreRun(result),result:result};});var total=scored.reduce(function(sum,row){return sum+row.score.score;},0);return{id:id,genome:genome(genomeValue),genomeDigest:hash(genome(genomeValue)),runs:scored,score:scored.length?Number((total/scored.length).toFixed(6)):-10000,collapsed:scored.filter(function(row){return row.score.verdict==='COLLAPSED'||row.score.verdict==='INVALID';}).length,fragile:scored.filter(function(row){return row.score.verdict==='FRAGILE';}).length};}
function select(parentEntry,candidateEntries){var all=[parentEntry].concat(candidateEntries||[]).slice().sort(function(a,b){return b.score-a.score||a.id.localeCompare(b.id);});var best=all[0],parent=parentEntry;var inherit=best.id!==parent.id&&best.collapsed===0&&best.score>parent.score;return{winner:inherit?best:parent,challengerBest:best.id===parent.id?null:best,inherit:inherit,reason:inherit?'A challenger survived every exam and exceeded the current parent under the declared direction.':'No challenger both survived and exceeded the current parent; the lineage keeps its present genome.',ranking:all.map(function(entry,index){return{id:entry.id,rank:index+1,score:entry.score,collapsed:entry.collapsed,fragile:entry.fragile,genomeDigest:entry.genomeDigest};})};}
function inherit(lineage,selection,candidateSet,examSeeds,examPlan,trigger){var plan=typeof examPlan==='object'?clone(examPlan):{id:'legacy-world-year-v1',samples:Number(examPlan)||0,sampleSeconds:null,sampleUnit:'world-year'},next=clone(lineage),before=genome(next.currentGenome),after=genome(selection.winner.genome),event={generation:next.generation+1,at:now(),trigger:trigger||'manual',parentDigest:hash(before),selectedId:selection.winner.id,selectedDigest:hash(after),inherited:selection.inherit,mutations:genomeDiff(before,after),reason:selection.reason,examSeeds:(examSeeds||[]).slice(),years:plan.samples,examPlan:plan,ranking:clone(selection.ranking)};next.generation+=1;next.currentGenome=after;next.currentGenomeDigest=hash(after);next.updatedAt=event.at;next.lastCandidateSet=clone(candidateSet||null);next.history.push(event);if(next.history.length>200)next.history=next.history.slice(-200);var receipt={schema:RECEIPT_SCHEMA,status:'EXPERIMENTAL',lineageId:next.lineageId,generation:next.generation,trigger:event.trigger,parentDigest:event.parentDigest,selectedDigest:event.selectedDigest,inherited:event.inherited,mutations:event.mutations,examSeeds:event.examSeeds,years:plan.samples,examPlan:clone(plan),direction:clone(next.direction),reason:event.reason,createdAt:event.at,rollback:{kind:'lineage-reset-or-prior-genome',available:true},truth:'Inheritance changed only the disposable browser-local world genome. No canonical world, Mirror root or Workshop source was rewritten.'};next.lastReceipt=receipt;return{lineage:next,receipt:receipt,event:event};}
function examSeeds(lineageSeed,generation,count){var out=[],base=parseInt(hash({lineageSeed:lineageSeed,generation:generation}),16)>>>0;for(var i=0;i<(count||3);i++){base=(Math.imul(base^0x9e3779b9,1664525)+1013904223)>>>0;out.push(1+(base%2000000000));}return out;}
function genomeQuery(genomeValue){var g=genome(genomeValue),parts=[];GENE_KEYS.forEach(function(key){parts.push('g.'+encodeURIComponent(key)+'='+encodeURIComponent(g[key]));});return parts.join('&');}
function lineageText(lineage){var lines=['AXM GOVERNED EVOLUTION LAB','STATUS: EXPERIMENTAL','','Lineage: '+lineage.lineageId,'Generation: '+lineage.generation,'Current genome: '+lineage.currentGenomeDigest,'Direction: '+lineage.direction.statement,'Proxy warning: '+lineage.direction.proxyWarning,'','HEARTBEAT','Total beats: '+((lineage.heartbeat&&lineage.heartbeat.totalBeats)||0),'Last beat: '+((lineage.heartbeat&&lineage.heartbeat.lastBeatAt)||'never'),'','GENOME',JSON.stringify(lineage.currentGenome,null,2),'','HISTORY'];lineage.history.forEach(function(event){lines.push('Generation '+event.generation+' · '+(event.inherited?'INHERITED':'PARENT HELD')+' · '+event.selectedDigest, 'Trigger: '+(event.trigger||'manual'), 'Exam plan: '+(event.examPlan?JSON.stringify(event.examPlan):'legacy unversioned plan'), event.reason, 'Mutations: '+(event.mutations.length?event.mutations.map(function(m){return m.gene+' '+m.before+' -> '+m.after;}).join('; '):'none'), '');});lines.push('BOUNDARY','This lineage may replace its own disposable genome automatically. It cannot rewrite canonical worlds, Mirror roots, permissions, or Workshop sources.','The current heartbeat is page-local and stops when the lab page closes.','Ecology scores are gameplay proxies, not scientific or moral fitness.');return lines.join('\r\n');}

return{VERSION:VERSION,GENOME_SCHEMA:GENOME_SCHEMA,LINEAGE_SCHEMA:LINEAGE_SCHEMA,RECEIPT_SCHEMA:RECEIPT_SCHEMA,BASELINE:clone(BASELINE),GENE_KEYS:GENE_KEYS.slice(),hash:hash,genome:genome,genomeDiff:genomeDiff,emptyLineage:emptyLineage,scoreRun:scoreRun,aggregate:aggregate,select:select,inherit:inherit,examSeeds:examSeeds,genomeQuery:genomeQuery,lineageText:lineageText};
});
