'use strict';
const fs=require('fs'),vm=require('vm'),path=require('path');
const ROOT=path.resolve(__dirname,'..'),store=new Map();
const legacyPreset={schema:'axm.visual-preset/0.5',id:'axm.legacy.test',name:'Legacy test',version:'0.5.0',parent:'axm.mold.universal-visual-card',sparse_overrides:{theme:'paper-neon'},approval_state:'EXPERIMENTAL',public_scope:'private'};
store.set('axm.visual-foundry.presets.v0.8',JSON.stringify([legacyPreset]));

global.window=global;global.location={protocol:'http:'};global.matchMedia=()=>({matches:false});global.addEventListener=()=>{};global.dispatchEvent=()=>true;global.CustomEvent=class{constructor(type,detail){this.type=type;this.detail=detail}};
global.localStorage={getItem:key=>store.has(key)?store.get(key):null,setItem:(key,value)=>store.set(key,String(value)),removeItem:key=>store.delete(key),clear:()=>store.clear(),key:index=>[...store.keys()][index]??null,get length(){return store.size}};
function gradient(){return {addColorStop(){}}}
function context(){return new Proxy({measureText:text=>({width:String(text).length*10}),createLinearGradient:gradient,createRadialGradient:gradient},{get:(obj,key)=>key in obj?obj[key]:(()=>{}),set:(obj,key,value)=>(obj[key]=value,true)});}
function canvas(){return {width:300,height:150,style:{},dataset:{},setAttribute(){},getContext:()=>context(),toDataURL:(type='image/png')=>`data:${type};base64,${Buffer.from('axm').toString('base64')}`}}
function element(tag='div'){if(tag==='canvas')return canvas();return {tagName:String(tag).toUpperCase(),style:{},dataset:{},className:'',textContent:'',innerHTML:'',classList:{add(){},remove(){},toggle(){},contains(){return false}},appendChild(){},append(){},remove(){},click(){},setAttribute(){},querySelector(){return null},showModal(){}}}
global.document={hidden:false,body:element('body'),createElement:element,getElementById:()=>element('div'),addEventListener(){},querySelector(){return null}};
global.URL={createObjectURL:()=> 'blob:axm',revokeObjectURL(){}};global.Blob=class{constructor(parts,opts){this.parts=parts;this.type=opts?.type}};global.requestAnimationFrame=()=>1;global.cancelAnimationFrame=()=>{};global.performance={now:()=>0};
for(const rel of ['app/js/registry.bundle.js','app/js/core.js','app/js/renderers.js','app/js/validators.js','app/js/exporters.js','app/js/assembly.js','app/js/recovery.js'])vm.runInThisContext(fs.readFileSync(path.join(ROOT,rel),'utf8'),{filename:rel});

const checks=[];const check=(name,ok,detail='')=>checks.push({name,ok:Boolean(ok),detail});const rejected=fn=>{try{fn();return false}catch{return true}};
try{
  const root=AXM.getMold('axm.mold.universal-visual-card'),child=AXM.getMold('axm.mold.game-launch-card'),skin=AXM.getMold('axm.mold.living-skin-laboratory'),portal=AXM.getMold('axm.mold.atmospheric-portal-scene');
  const coreMoldCount=AXM.REG.molds.length,controls=AXM.defaultControls(root),variant={theme:'aetherglass',format:'landscape',motion:'still',performance:'low',state:'idle'};
  check('registry breadth',AXM.REG.tokens.length>=140&&AXM.REG.organs.length>=55&&AXM.REG.molds.length===32&&AXM.REG.themes.length===6&&AXM.REG.presets.length>=38&&Object.keys(AXM.REG.adapters).length===6,`${AXM.REG.tokens.length}/${AXM.REG.organs.length}/${AXM.REG.molds.length}/${AXM.REG.themes.length}/${AXM.REG.presets.length}/${Object.keys(AXM.REG.adapters).length}`);
  const categoryCount=name=>AXM.REG.molds.filter(m=>m.category===name).length,marketing=categoryCount('marketing')+categoryCount('public-explanation')+categoryCount('visual-log'),game=categoryCount('game-ui')+categoryCount('game-marketing');
  check('library family coverage',marketing===8&&categoryCount('software-ui')===8&&game===8&&categoryCount('material')===4&&categoryCount('scene')===4,`marketing=${marketing}, software-ui=${categoryCount('software-ui')}, game=${game}, material=${categoryCount('material')}, scene=${categoryCount('scene')}`);
  const cardMolds=AXM.REG.molds.filter(m=>m.renderer==='card'),cardLayouts=cardMolds.map(m=>m.renderer_options?.layout),unknownLayouts=cardLayouts.filter(layout=>!AXMRender.CARD_LAYOUTS.has(layout));
  check('card layout recipe coverage',cardMolds.length===24&&new Set(cardLayouts).size===24&&!unknownLayouts.length,`cards=${cardMolds.length}, unique=${new Set(cardLayouts).size}, recipes=${AXMRender.CARD_LAYOUTS.size}`);
  const allMoldRuns=AXM.REG.molds.map(m=>{try{const c=AXM.defaultControls(m),v={...AXM.defaultVariant(m),motion:'still',performance:'low'},report=AXMValidate.validate(m,c,v,{reducedMotion:true}),out=AXMRender.renderCanvasForMold(m,c,v,.20);return {id:m.id,fail:report.summary.fail,size:[out.width,out.height]}}catch(error){return {id:m.id,error:error.message}}});
  check('all protected molds validate and render',allMoldRuns.every(item=>!item.error&&!item.fail&&item.size[0]>80&&item.size[1]>80),JSON.stringify(allMoldRuns.filter(item=>item.error||item.fail)));
  check('v0.8 migration',AXM.storageRead(AXM.STORAGE.presets,[]).some(p=>p.id==='axm.legacy.test'),'v0.8 record copied to v0.9 storage');
  const migrationMarkerRaw=store.get(AXM.STORAGE.migration),migrationRecoveryRaw=store.get(AXM.STORAGE.recovery),migrationSettingsRaw=store.get(AXM.STORAGE.settings),legacySettingsKey='axm.visual-foundry.settings.v0.8',legacySettingsRaw=store.get(legacySettingsKey),migrationSetItem=localStorage.setItem;
  store.delete(AXM.STORAGE.migration);store.delete(AXM.STORAGE.settings);store.set(legacySettingsKey,JSON.stringify({interfaceTheme:'light'}));localStorage.setItem=(key,value)=>{if(key===AXM.STORAGE.settings)throw new Error('QuotaExceededError migration test');return migrationSetItem.call(localStorage,key,value)};
  const heldMigration=AXM.migrateLegacyStorage();localStorage.setItem=migrationSetItem;
  check('incomplete migration is retried',heldMigration.failures===1&&heldMigration.marker_saved===false&&!store.has(AXM.STORAGE.migration),'failed legacy area did not receive a completion marker');
  if(migrationMarkerRaw===undefined)store.delete(AXM.STORAGE.migration);else store.set(AXM.STORAGE.migration,migrationMarkerRaw);if(migrationRecoveryRaw===undefined)store.delete(AXM.STORAGE.recovery);else store.set(AXM.STORAGE.recovery,migrationRecoveryRaw);if(migrationSettingsRaw===undefined)store.delete(AXM.STORAGE.settings);else store.set(AXM.STORAGE.settings,migrationSettingsRaw);if(legacySettingsRaw===undefined)store.delete(legacySettingsKey);else store.set(legacySettingsKey,legacySettingsRaw);
  check('protected core start',AXM.coreIntegrityReport().status==='PASS',JSON.stringify(AXM.coreIntegrityReport()));
  check('sparse child resolution',child.source_kind==='derived'&&child.inherited_from===root.id&&child.renderer_options.layout==='game-signal',child.source_manifest);

  const report=AXMValidate.validate(root,controls,variant,{reducedMotion:true});
  check('mold validation',report.summary.fail===0&&report.checks.length>=23,JSON.stringify(report.summary));
  const arbitraryAxisMold=AXM.clone(root);arbitraryAxisMold.variants={...arbitraryAxisMold.variants,arbitrary_runtime_switch:['enabled']};const arbitraryAxisReport=AXMValidate.validate(arbitraryAxisMold,AXM.defaultControls(arbitraryAxisMold),AXM.defaultVariant(arbitraryAxisMold),{reducedMotion:true});
  check('arbitrary declared variant axis rejected',arbitraryAxisReport.summary.fail>0,arbitraryAxisReport.status+' '+JSON.stringify(arbitraryAxisReport.checks.filter(item=>item.state==='FAIL')));
  const renderPacket=AXMExport.packet(root,controls,variant);check('render packet integrity',AXM.verifyPacketIntegrity(renderPacket).status==='PASS',renderPacket.integrity.fingerprint);
  const c=canvas();AXMRender.drawCardCanvas(c,controls,variant,.25,root);check('root canvas render',c.width>100&&c.height>100,`${c.width}x${c.height}`);
  const cc=canvas();AXMRender.drawCardCanvas(cc,AXM.defaultControls(child),{...variant,format:'square'},.25,child);check('derived canvas render',cc.width===195&&cc.height===195,`${cc.width}x${cc.height}`);
  const sc=canvas();AXMRender.drawSkin(sc,AXM.defaultControls(skin),{...AXM.defaultVariant(skin),motion:'still',performance:'low'},0);check('skin render',sc.width>500&&sc.height>500,`${sc.width}x${sc.height}`);
  const pc=canvas();AXMRender.drawPortal(pc,AXM.defaultControls(portal),{...AXM.defaultVariant(portal),motion:'still',performance:'low'},0);check('portal render',pc.width>500&&pc.height>400,`${pc.width}x${pc.height}`);
  const svg=AXMExport.cardSVG(controls,variant,root);check('svg export',svg.includes('<svg')&&svg.includes(root.id)&&svg.includes('data-layout="editorial-split"'),String(svg.length));
  const dashboard=AXM.getMold('axm.mold.operational-dashboard-panel'),dashboardSVG=AXMExport.cardSVG(AXM.defaultControls(dashboard),{...AXM.defaultVariant(dashboard),motion:'still',performance:'low'},dashboard);check('expanded layout SVG motif',dashboardSVG.includes('data-layout="dashboard-panel"')&&dashboardSVG.includes('<path'),String(dashboardSVG.length));
  const html=AXMExport.cardHTML(controls,variant,root);check('html export',html.startsWith('<!doctype html>')&&!html.includes('<script'),String(html.length));
  const themeBook=AXMExport.themeBookHTML(root,controls,variant);check('theme book export',themeBook.includes('Theme Book')&&themeBook.includes('Governed theme preview book'),String(themeBook.length));

  const draft=AXM.buildThemeDraft('aetherglass',{name:'Node Signal Theme',material_language:'node-tested translucent signal glass',accent:'#7df9ff',accent_2:'#bb8cff',compatible_renderers:['card','living-skin','portal-scene'],provenance:{author:'Node smoke',license:'user-controlled',rights_scope:'private-local',transformation_history:['node theme test']}});
  const draftReport=AXM.themeValidation(draft);check('theme draft validation',draftReport.summary.fail===0,draftReport.status+' '+JSON.stringify(draftReport.summary));
  const unsafeTheme=AXM.clone(draft);unsafeTheme.panel='url(https://remote.example/theme.png)';check('unsafe theme CSS rejected',AXM.themeValidation(unsafeTheme).summary.fail>0,'remote CSS value fails declarative color grammar');
  const localTheme=AXM.saveThemeDraft(draft);check('theme quarantine',localTheme.theme_state==='QUARANTINED'&&localTheme.approval_state==='EXPERIMENTAL',localTheme.id);
  const approvedTheme=AXM.approveTheme(localTheme.id);check('theme explicit approval',approvedTheme.approval_state==='APPROVED'&&approvedTheme.theme_state==='QUARANTINED',approvedTheme.approval_method);
  const activeTheme=AXM.activateTheme(localTheme.id);check('theme activation',activeTheme.theme_state==='ACTIVE'&&AXM.variantValues(root,'theme').includes(activeTheme.id),activeTheme.id);
  const themedCanvas=canvas();AXMRender.drawCardCanvas(themedCanvas,controls,{...variant,theme:activeTheme.id},.25,root);check('local theme render',themedCanvas.width>100&&AXM.getTheme(activeTheme.id).id===activeTheme.id,`${themedCanvas.width}x${themedCanvas.height}`);
  const themePacket=AXM.themePacket(activeTheme);check('theme package integrity',themePacket.schema==='axm.theme-package/0.5'&&AXM.verifyPacketIntegrity(themePacket).status==='PASS',themePacket.integrity.fingerprint);
  const tamperedTheme=AXM.clone(themePacket);tamperedTheme.theme.accent='#000000';check('tampered theme rejected',rejected(()=>AXM.importThemePackage(tamperedTheme)),'fingerprint mismatch');
  const importedTheme=AXM.importThemePackage(themePacket);check('theme import quarantine',importedTheme.id!==activeTheme.id&&importedTheme.theme_state==='QUARANTINED'&&importedTheme.approval_state==='EXPERIMENTAL',importedTheme.id);

  const parsedCSV=AXM.parseBatchSource('title,message,badge,metric,cta\n"Hello, world","Quoted, safe",AXM,32,Open\nSecond,Local row,TEST,100,Build');
  check('CSV intake parser',parsedCSV.rows.length===2&&parsedCSV.rows[0].title==='Hello, world'&&parsedCSV.rows[0].message==='Quoted, safe'&&parsedCSV.total_rows===2&&parsedCSV.truncated_count===0,JSON.stringify(parsedCSV));
  const parsedSemicolon=AXM.parseBatchSource('title;message;theme\nEerste;"Veilig; lokaal";aetherglass\nTweede;Nog een rij;paper-neon');
  check('semicolon CSV intake',parsedSemicolon.delimiter==='semicolon'&&parsedSemicolon.rows.length===2&&parsedSemicolon.rows[0].message==='Veilig; lokaal',JSON.stringify(parsedSemicolon));
  check('malformed quoted CSV rejected',rejected(()=>AXM.parseBatchSource('title,message\n"open quote,broken')),'unclosed quote rejected');
  const tooManyHeaders=Array.from({length:101},(_,i)=>`column_${i+1}`).join(',')+'\n'+Array.from({length:101},(_,i)=>`value_${i+1}`).join(',');
  check('CSV header limit enforced',rejected(()=>AXM.parseBatchSource(tooManyHeaders)),'101-column source rejected before any fields can be dropped');
  check('ragged CSV extra cell rejected',rejected(()=>AXM.parseBatchSource('title,message\nVisible,Safe,EXTRA-MUST-NOT-DROP')),'extra cell rejected instead of silently discarded');
  const collidingKeyBase='k'.repeat(64),collisionJSON=AXM.parseBatchSource(JSON.stringify([{[`${collidingKeyBase}A`]:'first-preserved',[`${collidingKeyBase}B`]:'second-preserved'}])),collisionValues=Object.values(collisionJSON.rows[0]||{});
  check('sanitized JSON key collision preserves both values',Object.keys(collisionJSON.rows[0]||{}).length===2&&collisionValues.includes('first-preserved')&&collisionValues.includes('second-preserved'),JSON.stringify({headers:collisionJSON.headers,row:collisionJSON.rows[0],renamed:collisionJSON.renamed_headers}));
  const oversizedSource=['title,message',...Array.from({length:101},(_,i)=>`Row ${i+1},Local ${i+1}`)].join('\n');
  check('CSV row limit enforced',rejected(()=>AXM.parseBatchSource(oversizedSource)),'101-row source rejected instead of silently truncating records');
  const duplicateHeaders=AXM.parseBatchSource('title,title,message\nOne,Two,Three');let duplicateBatch=AXM.newBatch('Duplicate Header Draft',root);duplicateBatch.headers=duplicateHeaders.headers;duplicateBatch.rows=duplicateHeaders.rows;duplicateBatch.mapping=AXM.inferBatchMapping(root,duplicateHeaders.headers);duplicateBatch.intake_report={total_rows:duplicateHeaders.total_rows,accepted_rows:duplicateHeaders.rows.length,truncated_count:duplicateHeaders.truncated_count,renamed_headers:duplicateHeaders.renamed_headers};check('duplicate headers renamed visibly',duplicateHeaders.headers.includes('title_2')&&AXM.batchValidation(duplicateBatch).summary.warn>0,JSON.stringify(duplicateHeaders.renamed_headers));
  let batch=AXM.newBatch('Node Data Batch',root);batch.headers=parsedCSV.headers;batch.rows=parsedCSV.rows;batch.source_format=parsedCSV.format;batch.mapping=AXM.inferBatchMapping(root,parsedCSV.headers);batch.intake_report={source_format:parsedCSV.format,delimiter:parsedCSV.delimiter,total_rows:parsedCSV.total_rows,accepted_rows:parsedCSV.rows.length,truncated_count:parsedCSV.truncated_count,renamed_headers:parsedCSV.renamed_headers};batch=AXM.upsertBatch(batch);const batchReport=AXM.batchValidation(batch);check('data batch validation',batchReport.summary.fail===0&&AXM.materializeBatch(batch).length===2,batchReport.status+' '+JSON.stringify(batchReport.summary));batch=AXM.approveBatch(batch.id);check('data batch approval',batch.batch_state==='APPROVED'&&batch.approved_fingerprint,batch.batch_state);batch=AXM.upsertBatch(AXM.clone(batch));check('unchanged approved batch remains approved',batch.batch_state==='APPROVED',batch.batch_state);batch.rows[0].title='Edited after approval';batch=AXM.upsertBatch(batch);check('approved batch edit returns to draft',batch.batch_state==='DRAFT',batch.batch_state);batch.rows[0].title='Hello, world';batch=AXM.upsertBatch(batch);batch=AXM.approveBatch(batch.id);
  let archiveBatchProbe=AXM.newBatch('Archive Batch Probe',root);archiveBatchProbe.headers=parsedCSV.headers;archiveBatchProbe.rows=parsedCSV.rows;archiveBatchProbe.source_format=parsedCSV.format;archiveBatchProbe.mapping=AXM.inferBatchMapping(root,parsedCSV.headers);archiveBatchProbe.intake_report={source_format:parsedCSV.format,delimiter:parsedCSV.delimiter,total_rows:parsedCSV.total_rows,accepted_rows:parsedCSV.rows.length,truncated_count:0,renamed_headers:[]};archiveBatchProbe=AXM.upsertBatch(archiveBatchProbe);archiveBatchProbe=AXM.approveBatch(archiveBatchProbe.id);archiveBatchProbe=AXM.archiveBatch(archiveBatchProbe.id);const archivedBatchReport=AXM.batchValidation(archiveBatchProbe);
  check('approved batch archives without draft demotion',archiveBatchProbe.batch_state==='ARCHIVED'&&AXM.getBatch(archiveBatchProbe.id)?.batch_state==='ARCHIVED'&&archivedBatchReport.checks.some(item=>item.label==='Batch state'&&item.evidence.includes('ARCHIVED')),archiveBatchProbe.batch_state+' '+JSON.stringify(archivedBatchReport.summary));
  const batchPacket=AXM.batchPacket(batch);check('batch package integrity',batchPacket.schema==='axm.data-batch-package/0.6'&&AXM.verifyPacketIntegrity(batchPacket).status==='PASS',batchPacket.integrity.fingerprint);const badBatch=AXM.clone(batchPacket);badBatch.batch.name='Tampered';check('tampered batch rejected',rejected(()=>AXM.importBatchPackage(badBatch)),'fingerprint mismatch');const importedBatch=AXM.importBatchPackage(batchPacket);check('batch import draft',importedBatch.batch_state==='DRAFT'&&importedBatch.id!==batch.id,importedBatch.id);const noIntegrityBatch=AXM.clone(batchPacket);delete noIntegrityBatch.integrity;check('current batch missing integrity rejected',rejected(()=>AXM.importBatchPackage(noIntegrityBatch)),batchPacket.schema);const batchHTML=AXM.batchHTML(batch);check('batch HTML export',batchHTML.startsWith('<!doctype html>')&&!batchHTML.includes('<script')&&batchHTML.includes('Hello, world'),String(batchHTML.length));
  const unsafeBatch=AXM.newBatch('Unsafe',root);unsafeBatch.headers=['title'];unsafeBatch.rows=[{title:'https://remote.example/image.png'}];unsafeBatch.mapping=AXM.inferBatchMapping(root,unsafeBatch.headers);check('remote batch value rejected',AXM.batchValidation(unsafeBatch).summary.fail>0,'remote data blocked');const missingColumnBatch=AXM.newBatch('Missing mapping',root);missingColumnBatch.headers=['title'];missingColumnBatch.rows=[{title:'Local'}];missingColumnBatch.mapping={controls:{title:'not_present'},variants:{}};check('missing mapped column rejected',AXM.batchValidation(missingColumnBatch).summary.fail>0,'missing mapping blocked');
  let project=AXM.projectFromBatch(batch,'Node Visual Project');const projectReport=AXM.projectValidation(project);check('project from batch',project.items.length===2&&projectReport.summary.fail===0,projectReport.status+' '+JSON.stringify(projectReport.summary));project=AXM.approveProject(project.id);check('project approval',project.project_state==='APPROVED'&&project.approved_fingerprint,project.project_state);project=AXM.upsertProject(AXM.clone(project),'unchanged save');check('unchanged approved project remains approved',project.project_state==='APPROVED',project.project_state);const approvedFingerprint=project.approved_fingerprint;project.description='Changed after approval';project=AXM.upsertProject(project,'node edit');check('approved edit returns to draft',project.project_state==='DRAFT'&&project.revisions.length>0&&approvedFingerprint,'revisions='+project.revisions.length);project=AXM.approveProject(project.id);const projectPacket=AXM.projectPacket(project);check('project package integrity',projectPacket.schema==='axm.visual-project-package/0.6'&&AXM.verifyPacketIntegrity(projectPacket).status==='PASS',projectPacket.integrity.fingerprint);const inspectedProject=AXM.inspectPacket(projectPacket);check('package inspector',inspectedProject.status==='PASS'&&inspectedProject.importer==='importProjectPackage'&&inspectedProject.counts.project_items===2,inspectedProject.status+' '+inspectedProject.importer);const inspectedTampered=AXM.inspectPacket({...AXM.clone(projectPacket),project:{...AXM.clone(projectPacket.project),name:'Inspector tamper'}});check('package inspector catches tamper',inspectedTampered.summary.fail>0&&inspectedTampered.integrity.status==='FAIL',inspectedTampered.status);AXM.inspectPacket(projectPacket);const badProject=AXM.clone(projectPacket);badProject.project.name='Tampered';check('tampered project rejected',rejected(()=>AXM.importProjectPackage(badProject)),'fingerprint mismatch');const importedProject=AXM.importProjectPackage(projectPacket);check('project import draft',importedProject.project_state==='DRAFT'&&importedProject.id!==project.id,importedProject.id);const noIntegrityProject=AXM.clone(projectPacket);delete noIntegrityProject.integrity;check('current project missing integrity rejected',rejected(()=>AXM.importProjectPackage(noIntegrityProject)),projectPacket.schema);const dependencyFlood=AXM.attachPacketIntegrity({...AXM.clone(projectPacket),local_themes:Array.from({length:101},(_,i)=>({id:`fake.${i}`}))});check('dependency flood rejected',rejected(()=>AXM.importProjectPackage(dependencyFlood)),'dependency cap');const projectHTML=AXM.projectHTML(project);check('project HTML export',projectHTML.startsWith('<!doctype html>')&&!projectHTML.includes('<script')&&projectHTML.includes('Node Visual Project'),String(projectHTML.length));
  const projectsBeforeRevisionProbe=store.get(AXM.STORAGE.projects),missingRevisionRecords=JSON.parse(projectsBeforeRevisionProbe),missingRevisionProject=missingRevisionRecords.find(item=>item.id===project.id),missingRevision=missingRevisionProject?.revisions?.[0];if(missingRevision)delete missingRevision.fingerprint;store.set(AXM.STORAGE.projects,JSON.stringify(missingRevisionRecords));const missingRevisionRejected=Boolean(missingRevision)&&rejected(()=>AXM.restoreProjectRevision(project.id,missingRevision.id));store.set(AXM.STORAGE.projects,projectsBeforeRevisionProbe);
  check('project revision missing fingerprint rejected',missingRevisionRejected,missingRevision?.id||'no revision fixture');
  const tamperedRevisionRecords=JSON.parse(projectsBeforeRevisionProbe),tamperedRevisionProject=tamperedRevisionRecords.find(item=>item.id===project.id),tamperedRevision=tamperedRevisionProject?.revisions?.[0];if(tamperedRevision?.project)tamperedRevision.project.description='tampered revision payload';store.set(AXM.STORAGE.projects,JSON.stringify(tamperedRevisionRecords));const tamperedRevisionRejected=Boolean(tamperedRevision)&&rejected(()=>AXM.restoreProjectRevision(project.id,tamperedRevision.id));store.set(AXM.STORAGE.projects,projectsBeforeRevisionProbe);
  check('project revision fingerprint mismatch rejected',tamperedRevisionRejected,tamperedRevision?.id||'no revision fixture');
  let archiveProjectProbe=AXM.newProject('Archive Project Probe','Explicit lifecycle transition','gallery');archiveProjectProbe.items=[{mold_id:root.id,label:'Archive visual',controls:AXM.defaultControls(root),variant:AXM.defaultVariant(root)}];archiveProjectProbe=AXM.upsertProject(archiveProjectProbe,'archive probe save');archiveProjectProbe=AXM.approveProject(archiveProjectProbe.id);archiveProjectProbe=AXM.archiveProject(archiveProjectProbe.id);const archivedProjectReport=AXM.projectValidation(archiveProjectProbe);
  check('approved project archives without draft demotion',archiveProjectProbe.project_state==='ARCHIVED'&&AXM.getProject(archiveProjectProbe.id)?.project_state==='ARCHIVED'&&archivedProjectReport.checks.some(item=>item.label==='Project state'&&item.evidence.includes('ARCHIVED')),archiveProjectProbe.project_state+' '+JSON.stringify(archivedProjectReport.summary));

  const preset=AXM.saveCurrentPreset('Node smoke');check('preset save/load',AXM.storageRead(AXM.STORAGE.presets,[]).some(p=>p.id===preset.id),preset.id);
  const old=AXM.state.controls.title,snap=AXM.snapshot('node smoke');AXM.state.controls.title='changed';const comparison=AXM.compareWithSnapshot(snap.id);check('snapshot comparison',comparison.changes.some(x=>x.path==='controls.title'),String(comparison.changes.length));AXM.restoreSnapshot(snap.id);check('rollback',AXM.state.controls.title===old,AXM.state.controls.title);
  const snapshotsBeforeTamper=store.get(AXM.STORAGE.snapshots),tamperedSnapshots=JSON.parse(snapshotsBeforeTamper),tamperedSnapshot=tamperedSnapshots.find(item=>item.id===snap.id);tamperedSnapshot.controls.title='tampered snapshot payload';store.set(AXM.STORAGE.snapshots,JSON.stringify(tamperedSnapshots));const tamperedSnapshotRejected=rejected(()=>AXM.restoreSnapshot(snap.id));store.set(AXM.STORAGE.snapshots,snapshotsBeforeTamper);
  check('tampered snapshot restore rejected',tamperedSnapshotRejected,snap.id);

  const candidate=AXM.clone(root);Object.assign(candidate,{schema:'axm.visual-mold/0.5',id:'axm.candidate.node-extension',name:'Node Extension',version:'0.5.0',description:'Node-tested local extension candidate.',source_kind:'candidate',source_manifest:'node smoke candidate',inherited_from:root.id,lineage:{parent:root.id,derived_from:[`${root.id}@${root.version}`],change_policy:'explicit-approval'},approval_state:'APPROVED',approved_at:new Date().toISOString(),approval_method:'explicit-human-button',public_scope:'private',intent:{purpose:'Test governed local extension release.',change_summary:'Create one reversible local extension with a local theme dependency.',tags:['test','extension']},sparse_overrides:{title:'Node extension proof',theme:activeTheme.id},protected_change_request:['provenance'],variants:{...candidate.variants,theme:[...new Set([...(candidate.variants.theme||[]),activeTheme.id])]},provenance:{...root.provenance,source:root.id,consent:'explicit node smoke build',transformation_history:[...(root.provenance.transformation_history||[]),'node smoke v0.5 extension candidate']}});
  const candidateReport=AXMValidate.candidateFromText(JSON.stringify(candidate));check('candidate validation',candidateReport.summary.fail===0,candidateReport.status+' '+JSON.stringify(candidateReport.summary));AXM.saveCandidate(candidate);
  check('candidate ID collision rejected without explicit update',rejected(()=>AXM.saveCandidate({...AXM.clone(candidate),description:'silent collision overwrite'})),'duplicate save blocked');
  const explicitlyUpdatedCandidate=AXM.saveCandidate({...AXM.clone(candidate),description:'Explicit candidate update probe'},{update:true});
  check('candidate explicit update accepted',explicitlyUpdatedCandidate.id===candidate.id&&AXM.getCandidates().find(item=>item.id===candidate.id)?.description==='Explicit candidate update probe',explicitlyUpdatedCandidate.description);
  const extension=AXM.promoteCandidate(candidate.id);check('promotion enters quarantine',extension.source_kind==='extension'&&extension.extension_state==='QUARANTINED'&&extension.approval_state==='APPROVED',extension.id);
  check('quarantine excluded from usable atlas',AXM.REG.molds.length===coreMoldCount&&AXM.getAllMolds().length===coreMoldCount&&AXM.getExtensions(true).some(item=>item.id===extension.id),`protected=${coreMoldCount} usable=${AXM.getAllMolds().length}`);
  const gate=AXM.prepareExtensionRelease(extension.id);check('full release gate',gate.summary.fail===0&&gate.proof_matrix.length===18&&AXM.verifyPacketIntegrity(gate).status==='PASS',`${gate.status} ${JSON.stringify(gate.summary)}`);
  const activated=AXM.activateExtension(extension.id,gate.summary.warn>0);check('release-gated activation',activated.extension_state==='ACTIVE'&&AXM.getAllMolds().length===coreMoldCount+1,activated.id);
  check('duplicate promotion blocked',rejected(()=>AXM.promoteCandidate(candidate.id)),'same candidate cannot create a second live extension');
  check('core unchanged after growth',AXM.coreIntegrityReport().status==='PASS',JSON.stringify(AXM.coreIntegrityReport()));
  const extCanvas=canvas();AXMRender.drawCardCanvas(extCanvas,AXM.defaultControls(activated),{...AXM.defaultVariant(activated),motion:'still',performance:'low'},.25,activated);check('extension render',extCanvas.width>100&&extCanvas.height>100,`${extCanvas.width}x${extCanvas.height}`);
  const extensionPacket=AXM.extensionPacket(activated);check('extension package integrity',extensionPacket.schema==='axm.extension-package/0.5'&&AXM.verifyPacketIntegrity(extensionPacket).status==='PASS'&&extensionPacket.local_themes.some(t=>t.id===activeTheme.id),extensionPacket.integrity.fingerprint);
  const tamperedExtension=AXM.clone(extensionPacket);tamperedExtension.extension.name='Tampered';check('tampered extension rejected',rejected(()=>AXM.importExtensionPackage(tamperedExtension)),'fingerprint mismatch');

  const childSource=AXM.clone(activated);childSource.id='external.extension.node-child';childSource.name='Node Child Extension';childSource.lineage={parent:activated.id,derived_from:[activated.id],change_policy:'explicit-approval'};childSource.inherited_from=activated.id;childSource.origin_candidate_id=null;childSource.provenance={...activated.provenance,source:activated.id,consent:'explicit child package test',transformation_history:[...(activated.provenance.transformation_history||[]),'node child package']};
  const childPacket=AXM.attachPacketIntegrity({schema:'axm.extension-package/0.5',version:'0.5.0',created_at:new Date().toISOString(),application:{name:'AXM Visual Mold Foundry',version:'0.5.0',local_first:true},extension:childSource,dependencies:{organs:childSource.organs,parent:activated.id,themes:childSource.variants.theme},theme_summaries:[],local_themes:[],validation:AXM.extensionValidation(childSource),release_gate:AXM.extensionReleaseGate(childSource)},'Node child extension packet.');
  const importedChild=AXM.importExtensionPackage(childPacket);check('extension import quarantine',importedChild.extension_state==='QUARANTINED'&&importedChild.approval_state==='EXPERIMENTAL',importedChild.id);
  const projectsBeforeInactiveDependency=store.get(AXM.STORAGE.projects),batchesBeforeInactiveDependency=store.get(AXM.STORAGE.batches);
  let inactiveProject=AXM.newProject('Inactive Dependency Project','Must remain draft','gallery');inactiveProject.items=[{mold_id:importedChild.id,label:'Quarantined dependency',controls:AXM.defaultControls(importedChild),variant:AXM.defaultVariant(importedChild)}];inactiveProject=AXM.upsertProject(inactiveProject,'inactive dependency probe');
  check('inactive project dependency blocks approval',AXM.projectValidation(inactiveProject).summary.fail>0&&rejected(()=>AXM.approveProject(inactiveProject.id)),JSON.stringify(AXM.projectValidation(inactiveProject).summary));
  let inactiveBatch=AXM.newBatch('Inactive Dependency Batch',importedChild);inactiveBatch.headers=['title'];inactiveBatch.rows=[{title:'Quarantined dependency'}];inactiveBatch.mapping={controls:{title:'title'},variants:{}};inactiveBatch.intake_report={source_format:'json',delimiter:null,total_rows:1,accepted_rows:1,truncated_count:0,renamed_headers:[],accepted_fingerprint:AXM.fingerprintValue({headers:inactiveBatch.headers,rows:inactiveBatch.rows})};inactiveBatch=AXM.upsertBatch(inactiveBatch);
  check('inactive batch dependency blocks approval',AXM.batchValidation(inactiveBatch).summary.fail>0&&rejected(()=>AXM.approveBatch(inactiveBatch.id)),JSON.stringify(AXM.batchValidation(inactiveBatch).summary));
  if(projectsBeforeInactiveDependency===undefined)store.delete(AXM.STORAGE.projects);else store.set(AXM.STORAGE.projects,projectsBeforeInactiveDependency);
  if(batchesBeforeInactiveDependency===undefined)store.delete(AXM.STORAGE.batches);else store.set(AXM.STORAGE.batches,batchesBeforeInactiveDependency);
  check('unapproved activation blocked',rejected(()=>AXM.activateExtension(importedChild.id,true)),'separate approval required');
  AXM.approveExtension(importedChild.id);const childGate=AXM.prepareExtensionRelease(importedChild.id);const activeChild=AXM.activateExtension(importedChild.id,childGate.summary.warn>0);check('child release-gated activation',activeChild.extension_state==='ACTIVE',activeChild.id);
  check('active child protects parent',rejected(()=>AXM.deprecateExtension(activated.id)),'parent deactivation blocked');
  check('active extension protects theme',rejected(()=>AXM.deprecateTheme(activeTheme.id)),'theme deactivation blocked');

  AXM.setMold(activeChild.id);const workspace=AXM.workspacePacket();check('workspace packet integrity',workspace.schema==='axm.visual-workspace/0.6'&&AXM.verifyPacketIntegrity(workspace).status==='PASS'&&workspace.themes.length>=2&&workspace.projects.length>=2&&workspace.batches.length>=2,workspace.integrity.fingerprint);
  const tamperedWorkspace=AXM.clone(workspace);tamperedWorkspace.current.mold_id='tampered';check('tampered workspace rejected',rejected(()=>AXM.importWorkspace(tamperedWorkspace)),'fingerprint mismatch');
  const currentWorkspaceWithoutIntegrity=AXM.clone(workspace);delete currentWorkspaceWithoutIntegrity.integrity;check('current workspace missing integrity rejected',rejected(()=>AXM.importWorkspace(currentWorkspaceWithoutIntegrity)),workspace.schema);
  const importedWorkspace=AXM.importWorkspace(workspace);check('workspace merge/quarantine',importedWorkspace.themes>=2&&importedWorkspace.extensions>=2&&importedWorkspace.projects>=2&&importedWorkspace.batches>=2&&AXM.getExtensions(true).some(x=>x.import_origin==='workspace import'&&x.extension_state==='QUARANTINED'),JSON.stringify(importedWorkspace));

  const family=AXM.familyPacket(activeChild,AXM.defaultControls(activeChild),AXM.defaultVariant(activeChild));check('family packet integrity',family.schema==='axm.family-package/0.5'&&AXM.verifyPacketIntegrity(family).status==='PASS'&&family.local_themes.some(t=>t.id===activeTheme.id),family.integrity.fingerprint);
  const tamperedFamily=AXM.clone(family);tamperedFamily.focus_mold='tampered';check('tampered family rejected',rejected(()=>AXM.importFamilyPackage(tamperedFamily)),'fingerprint mismatch');
  const currentFamilyWithoutIntegrity=AXM.clone(family);delete currentFamilyWithoutIntegrity.integrity;check('current family missing integrity rejected',rejected(()=>AXM.importFamilyPackage(currentFamilyWithoutIntegrity)),family.schema);
  const importedFamily=AXM.importFamilyPackage(family);check('family merge/quarantine',importedFamily.themes>=1&&importedFamily.extensions>=1,JSON.stringify(importedFamily));

  AXM.deprecateExtension(activeChild.id);const parentDeprecated=AXM.deprecateExtension(activated.id);check('dependency-safe extension shutdown',parentDeprecated.extension_state==='DEPRECATED',parentDeprecated.id);
  const themeDeprecated=AXM.deprecateTheme(activeTheme.id);check('dependency-safe theme shutdown',themeDeprecated.theme_state==='DEPRECATED',themeDeprecated.id);
  const failedPersistenceLabel='forced persistence failure',persistenceRaw=store.get(AXM.STORAGE.presets),recoveryRaw=store.get(AXM.STORAGE.recovery),originalSetItem=localStorage.setItem;let persistenceRejected=false;
  localStorage.setItem=(key,value)=>{if(key===AXM.STORAGE.presets)throw new Error('QuotaExceededError test');return originalSetItem.call(localStorage,key,value)};
  try{AXM.withStorageTransaction(failedPersistenceLabel,()=>AXM.storageWrite(AXM.STORAGE.presets,[{id:'must-not-save'}]))}catch(error){persistenceRejected=true}finally{localStorage.setItem=originalSetItem}
  const persistenceRecords=AXM.transactionRecords().filter(item=>item.label===failedPersistenceLabel),falsePersistencePass=AXM.state.sessionLog.some(item=>item.level==='PASS'&&String(item.message||'').includes(failedPersistenceLabel));
  check('failed local persistence is not reported committed',persistenceRejected&&store.get(AXM.STORAGE.presets)===persistenceRaw&&!persistenceRecords.some(item=>item.status==='COMMIT')&&persistenceRecords.some(item=>item.status==='ROLLBACK')&&!falsePersistencePass,JSON.stringify(persistenceRecords));
  if(recoveryRaw===undefined)store.delete(AXM.STORAGE.recovery);else store.set(AXM.STORAGE.recovery,recoveryRaw);
  const beforeRollbackRaw=store.get(AXM.STORAGE.presets);check('forced transaction throws',rejected(()=>AXM.withStorageTransaction('forced node rollback',()=>{AXM.storageWrite(AXM.STORAGE.presets,[{id:'temporary-write'}]);throw new Error('forced rollback')})),'exception propagated');check('transaction restores storage',store.get(AXM.STORAGE.presets)===beforeRollbackRaw&&AXM.transactionRecords().some(item=>item.status==='ROLLBACK'&&item.label==='forced node rollback'),'raw preset area restored');
  const capsule=AXM.safetyCapsule();check('safety capsule integrity',capsule.schema==='axm.safety-capsule/0.9'&&AXM.verifyPacketIntegrity(capsule).status==='PASS'&&capsule.raw_storage.presets.key===AXM.STORAGE.presets,capsule.integrity.fingerprint);
  const staged=AXM.stageSafetyCapsule(capsule);check('safety capsule staged without mutation',staged.summary.fail===0&&staged.entries.length===8&&AXM.getStagedCapsule().capsule_schema==='axm.safety-capsule/0.9',`${staged.status}/${staged.changed_areas}`);
  const tamperedCapsule=AXM.clone(capsule);tamperedCapsule.raw_storage.presets.raw='[]';const tamperedStage=AXM.stageSafetyCapsule(tamperedCapsule);check('tampered capsule restore blocked',tamperedStage.summary.fail>0&&rejected(()=>AXM.restoreStagedCapsule('replace','RESTORE')),tamperedStage.status);
  AXM.stageSafetyCapsule(capsule);const capsulePresetRaw=store.get(AXM.STORAGE.presets),changedPresets=AXM.storageRead(AXM.STORAGE.presets,[]);changedPresets.push({id:'axm.after.capsule'});AXM.storageWrite(AXM.STORAGE.presets,changedPresets);check('restore confirmation required',rejected(()=>AXM.restoreStagedCapsule('replace','NO')),'RESTORE required');const restoredCapsule=AXM.restoreStagedCapsule('replace','RESTORE');check('capsule replace restore',store.get(AXM.STORAGE.presets)===capsulePresetRaw&&restoredCapsule.restored_areas===8&&AXM.rescuePoints().length>=1,JSON.stringify(restoredCapsule));
  const rescue=AXM.createRescuePoint('node rescue point'),rescueRaw=store.get(AXM.STORAGE.presets);AXM.storageWrite(AXM.STORAGE.presets,[{id:'temporary-after-rescue'}]);const rescueRestore=AXM.restoreRescuePoint(rescue.id,'RESTORE');check('rescue point restore',store.get(AXM.STORAGE.presets)===rescueRaw&&rescueRestore.health_status!=='FAIL'&&AXM.rescuePoints().length>=2,rescueRestore.rescue_id);
  const readiness=AXM.intakeReadinessReport();check('intake readiness gate',readiness.summary.fail===0&&readiness.gate==='READY_WITH_LOCAL_VALIDATION'&&AXM.verifyPacketIntegrity(readiness).status==='PASS',readiness.gate+' '+JSON.stringify(readiness.summary));AXM.markTargetBrowserValidated('Node simulated target-browser check');const handoff=AXM.intakeHandoffPacket();check('local intake handoff',handoff.schema==='axm.local-intake-handoff/0.9'&&AXM.verifyPacketIntegrity(handoff).status==='PASS'&&handoff.readiness.summary.fail===0,handoff.integrity.fingerprint);
  AXM.completeOnboarding();check('onboarding state',AXM.onboardingStatus().complete===true&&AXM.onboardingStatus().version==='0.9.1',JSON.stringify(AXM.onboardingStatus()));
  store.set(AXM.STORAGE.settings,'{broken-json');const corruptFallback=AXM.storageRead(AXM.STORAGE.settings,{recovered:true}),corruptRaw=store.get(AXM.STORAGE.settings),corruptAudit=AXM.inspectStorage();check('corrupt storage preserved',corruptFallback.recovered===true&&corruptRaw==='{broken-json'&&corruptAudit.status==='FAIL'&&corruptAudit.open_issues.some(item=>item.key===AXM.STORAGE.settings),corruptAudit.status);AXM.resetStorageKey(AXM.STORAGE.settings,'RESET');check('explicit reset only after export',!store.has(AXM.STORAGE.settings)&&AXM.inspectStorage().open_issues.every(item=>item.key!==AXM.STORAGE.settings),'settings area removed and issue resolved');
  const health=AXM.healthReport();check('health report',health.summary.fail===0&&AXM.verifyPacketIntegrity(health).status==='PASS'&&health.counts.projects>=2&&health.counts.batches>=2&&health.counts.transactions>=1&&health.counts.rescue_points>=1,health.status+' '+JSON.stringify(health.summary));
  check('unsafe import guards',rejected(()=>AXM.safeParseJSON('{"path":"../escape"}'))&&rejected(()=>AXM.safeParseJSON('{"__proto__":{"x":1}}')),'traversal and unsafe key rejected');
  check('export catalog',AXMExport.exportersFor(root).some(x=>x[0]==='health-report')&&AXMExport.exportersFor(root).some(x=>x[0]==='workspace')&&AXMExport.exportersFor(root).some(x=>x[0]==='family-package')&&typeof AXM.projectPacket==='function'&&typeof AXM.batchPacket==='function'&&typeof AXM.inspectStorage==='function'&&typeof AXM.exportSafetyCapsule==='function'&&typeof AXM.stageSafetyCapsule==='function'&&typeof AXM.restoreStagedCapsule==='function'&&typeof AXM.intakeReadinessReport==='function'&&typeof AXM.exportIntakeHandoffPacket==='function','health/workspace/family plus project/batch/recovery/intake APIs present');
}catch(e){check('exception',false,e.stack||e.message)}
const ok=checks.every(c=>c.ok);console.log(JSON.stringify({status:ok?'PASS':'FAIL',checks},null,2));process.exit(ok?0:1);
