'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const Core = require('./judgement-core');
const root = __dirname;
const html = fs.readFileSync(path.join(root, 'index.html'), 'utf8');
const app = fs.readFileSync(path.join(root, 'app.js'), 'utf8');
const manifest = JSON.parse(fs.readFileSync(path.join(root, 'manifest.json'), 'utf8'));
const contract = JSON.parse(fs.readFileSync(path.join(root, 'module.contract.json'), 'utf8'));

assert.equal(manifest.id, 'judgement-chamber');
assert.equal(contract.id, manifest.id);
assert.equal(manifest.schema, 'axm.tool-manifest/v1');
assert.equal(manifest.kind, 'product');
assert.deepEqual(manifest.permissions, contract.permissions);
assert.deepEqual(contract.lifecycle, { state_owner: 'service', reload: 'resume', disconnect: 'graceful-degrade', cleanup: 'explicit' });
assert.equal(Core.DIMENSIONS.length, 4);
assert.equal(Core.completeness(Core.emptyDimensions()).ready, false);
const dimensions = Core.emptyDimensions();
Core.DIMENSIONS.forEach(item => { dimensions[item.id] = { rating: 4, finding: 'Explicit finding', evidence: 'Named evidence' }; });
assert.equal(Core.completeness(dimensions).ready, true);
assert.equal(Core.flowState({ state:'APPROVED' }).key, 'ready');
assert.equal(Core.flowState({ state:'REJECTED' }).key, 'repair');
assert.equal(Core.reviewNeedsMiddle({ state:'HOLD' }), true);
assert.equal(Core.reviewNeedsMiddle({ state:'APPROVED' }), false);
assert(html.includes('THE EXACT THING BEING JUDGED'));
assert(html.includes('DISAGREEMENT &amp; REPAIR FLOW'));
assert(html.includes('Add a Fabric or Workshop goal here'));
assert(html.includes('responsive-fix.css'));
assert(app.includes("'/api/reviews/vote'"));
assert(app.includes("'/api/reviews/route'"));
assert(app.includes("'/api/workshop-direction/compile'"));
assert(app.includes("'/api/workshop-direction/commit'"));
assert(!/localStorage|sessionStorage/.test(app), 'service truth must not be shadowed in browser storage');
assert(contract.boundaries.refuses.includes('automatic-vote'));
console.log('Judgement Chamber selftest passed.');
