'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const Digest = require('../src/digest');
const Reference = require('../src/reference-intake');
const Ai = require('../src/ai-broker');
const AiExecutor = require('../src/ai-executor');
const ImageSearch = require('../src/image-search-broker');
const ImageSearchExecutor = require('../src/image-search-executor');
const ReferenceLab = require('../src/reference-lab');
const ReferenceLabHost = require('../src/reference-lab-host');

function imageReference(){return Reference.createFileReference(Buffer.from([0x89,0x50,0x4e,0x47,1,2,3,4]),{name:'park.png',mediaType:'image/png',purpose:'find-similar',userHint:'find rides with this visual feel'});}

test('query reference is digest-bound and inert',function(){const ref=Reference.createQueryReference('retro water ride park');assert.equal(ref.receipt.kind,'query');assert.equal(ref.receipt.authority.executableContentAllowed,false);assert.equal(ref.receipt.authority.networkAuthorityGranted,false);assert.equal(ReferenceLab.directQuery(ref),'retro water ride park');assert.doesNotThrow(()=>Reference.validateReference(ref));});

test('uploaded image tampering is refused',function(){const ref=imageReference(),tampered=JSON.parse(JSON.stringify(ref));tampered.runtime.dataBase64=Buffer.from('different').toString('base64');assert.throws(()=>Reference.validateReference(tampered),error=>error&&error.code==='REFERENCE_CONTENT_DIGEST_MISMATCH');});

test('PDF and safe UTF-8 documents are accepted without executing content',function(){const pdf=Reference.createFileReference(Buffer.from('%PDF-1.7\nfixture'),{name:'brief.pdf',mediaType:'application/pdf'}),text=Reference.createFileReference(Buffer.from('portable browser notes'),{name:'notes.md',mediaType:'text/markdown'});assert.equal(pdf.receipt.kind,'document');assert.equal(text.runtime.text,'portable browser notes');assert.equal(pdf.receipt.authority.executableContentAllowed,false);});

test('unsupported document types fail closed',function(){assert.throws(()=>Reference.createFileReference(Buffer.from('x'),{name:'thing.docx',mediaType:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}),error=>error&&error.code==='REFERENCE_MEDIA_UNSUPPORTED');});

test('neutral registry covers common cloud, compatible-local, Gemini, and Ollama adapters',function(){const registry=Ai.createRegistry([{id:'openai',adapter:'openai-responses',model:'a',enabled:true},{id:'anthropic',adapter:'anthropic-messages',model:'b',enabled:true},{id:'lmstudio',adapter:'openai-compatible-chat',endpoint:'http://127.0.0.1:1234/v1/chat/completions',model:'local',enabled:true,supportsImages:true},{id:'gemini',adapter:'gemini-generate-content',model:'g',enabled:true},{id:'ollama',adapter:'ollama-chat',model:'llava',enabled:true}],{mode:'panel'});assert.deepEqual(registry.providers.map(p=>p.adapter),['openai-responses','anthropic-messages','openai-compatible-chat','gemini-generate-content','ollama-chat']);assert.equal(registry.providers.find(p=>p.id==='lmstudio').capabilities.image,true);assert.equal(registry.providers.find(p=>p.id==='ollama').local,true);});

test('reference access off sends neither reference bytes nor receipt preview',function(){const ref=Reference.createTextReference('private preview text',{name:'private.txt'}),registry=Ai.createRegistry([{id:'cloud',adapter:'openai-responses',model:'m',enabled:true,referenceAccess:false}],{mode:'single'}),plan=Ai.buildAiPlan('summarize current browser only',registry,{reference:ref});const serialized=JSON.stringify(plan.requests[0]);assert.equal(plan.requests[0].referenceAttached,false);assert.equal(plan.requests[0].referenceReceiptDigest,null);assert.doesNotMatch(serialized,/private preview text/);assert.doesNotMatch(serialized,/private\.txt/);});

test('OpenAI multimodal plan attaches image only with reference access',function(){const registry=Ai.createRegistry([{id:'vision',adapter:'openai-responses',model:'vision',enabled:true,referenceAccess:true}],{mode:'single'}),plan=Ai.buildAiPlan('describe',registry,{reference:imageReference()});assert.equal(plan.requests[0].referenceAttached,true);assert.equal(plan.requests[0].body.input[0].content[1].type,'input_image');assert.match(plan.requests[0].body.input[0].content[1].image_url,/^data:image\/png;base64,/);});

test('Gemini and Ollama map the same AXM image reference to native request shapes',function(){const ref=imageReference(),g=Ai.createRegistry([{id:'g',adapter:'gemini-generate-content',model:'gemini-model',enabled:true,referenceAccess:true}],{mode:'single'}),gp=Ai.buildAiPlan('describe',g,{reference:ref});assert.equal(gp.requests[0].url,'https://generativelanguage.googleapis.com/v1beta/models/gemini-model:generateContent');assert.equal(gp.requests[0].body.contents[0].parts[1].inlineData.mimeType,'image/png');const o=Ai.createRegistry([{id:'o',adapter:'ollama-chat',model:'llava',enabled:true,referenceAccess:true}],{mode:'single'}),op=Ai.buildAiPlan('describe',o,{reference:ref});assert.equal(op.requests[0].url,'http://127.0.0.1:11434/api/chat');assert.equal(op.requests[0].body.messages[0].images.length,1);});

test('Gemini executor pins endpoint and normalizes output',async function(){const registry=Ai.createRegistry([{id:'g',adapter:'gemini-generate-content',model:'gemini-model',enabled:true,referenceAccess:true}],{mode:'single'}),plan=Ai.buildAiPlan('describe',registry,{reference:imageReference()}),result=await AiExecutor.executeAiPlan(plan,{networkAuthority:'EXPLICIT_ALLOW',env:{GEMINI_API_KEY:'secret-g'},fetchImpl:async function(url,init){assert.equal(url,'https://generativelanguage.googleapis.com/v1beta/models/gemini-model:generateContent');assert.equal(init.headers['x-goog-api-key'],'secret-g');return new Response(JSON.stringify({candidates:[{content:{parts:[{text:'retro water coaster'}]}}]}),{status:200,headers:{'content-type':'application/json'}});}});assert.equal(result.outputs[0].output,'retro water coaster');assert.equal(result.outputs[0].referenceUsed,true);assert.doesNotMatch(JSON.stringify(result),/secret-g/);});

test('Brave image search uses its dedicated image endpoint',function(){const plan=ImageSearch.buildImageSearchPlan({query:'retro theme park ride',provider:'brave'},{brave:{enabled:true}});assert.equal(plan.requests[0].url.startsWith('https://api.search.brave.com/res/v1/images/search?'),true);assert.equal(plan.authority.imageFetchGranted,false);});

test('SearXNG and Brave image results normalize and federate',function(){const a=ImageSearch.parseProviderResponse('searxng',{results:[{title:'Ride',url:'https://example.com/page',img_src:'https://cdn.example.com/ride.jpg',thumbnail_src:'https://cdn.example.com/thumb.jpg',resolution:'1600x900'}]},'retro ride'),b=ImageSearch.parseProviderResponse('brave',{results:[{title:'Ride',url:'https://example.com/page',properties:{url:'https://cdn.example.com/ride.jpg',width:1600,height:900},thumbnail:{src:'https://thumb.example.net/ride.jpg'}}]},'retro ride'),merged=ImageSearch.mergeResultSets([a,b]);assert.equal(a.results[0].imageUrl,'https://cdn.example.com/ride.jpg');assert.equal(b.results[0].width,1600);assert.equal(merged.results[0].agreementCount,2);});

test('image executor requires explicit authority and never fetches result image bytes',async function(){const plan=ImageSearch.buildImageSearchPlan('retro ride',{searxng:{endpoint:'http://127.0.0.1:8888/search'}});await assert.rejects(()=>ImageSearchExecutor.executeImageSearchPlan(plan,{}),error=>error&&error.code==='IMAGE_SEARCH_NETWORK_NOT_AUTHORIZED');let calls=0;const result=await ImageSearchExecutor.executeImageSearchPlan(plan,{networkAuthority:'EXPLICIT_ALLOW',allowedSearxngEndpoints:['http://127.0.0.1:8888/search'],fetchImpl:async function(){calls+=1;return new Response(JSON.stringify({results:[{title:'A',url:'https://example.com/a',img_src:'https://img.example/a.jpg'}]}),{status:200,headers:{'content-type':'application/json'}});}});assert.equal(calls,1);assert.equal(result.authority.imageBytesFetched,false);});

test('Reference Lab direct query does image search without spending an AI call',async function(){const lab=new ReferenceLab.ReferenceLab({searchNetworkAuthority:'EXPLICIT_ALLOW',imageSearchConfig:{searxng:{endpoint:'http://127.0.0.1:8888/search'}},imageSearchOptions:{allowedSearxngEndpoints:['http://127.0.0.1:8888/search'],fetchImpl:async()=>new Response(JSON.stringify({results:[{title:'Water ride',url:'https://example.com/a',img_src:'https://img.example/a.jpg'}]}),{status:200,headers:{'content-type':'application/json'}})}});lab.intakeQuery('water ride concept art');const run=await lab.findMatches({vertical:'images',userInitiated:true});assert.equal(run.interpretation,null);assert.equal(run.aiExecutionDigest,null);assert.equal(run.resultSet.resultCount,1);});

test('Reference Lab image path records AI interpretation separately from search evidence',async function(){const registry=Ai.createRegistry([{id:'vision-local',adapter:'ollama-chat',model:'llava',enabled:true,referenceAccess:true}],{mode:'single'}),lab=new ReferenceLab.ReferenceLab({aiRegistry:registry,aiNetworkAuthority:'EXPLICIT_ALLOW',searchNetworkAuthority:'EXPLICIT_ALLOW',aiOptions:{allowLoopbackOllama:true,fetchImpl:async()=>new Response(JSON.stringify({message:{content:'retro red water flume ride'}}),{status:200,headers:{'content-type':'application/json'}})},imageSearchConfig:{searxng:{endpoint:'http://127.0.0.1:8888/search'}},imageSearchOptions:{allowedSearxngEndpoints:['http://127.0.0.1:8888/search'],fetchImpl:async()=>new Response(JSON.stringify({results:[{title:'Similar flume',url:'https://example.com/flume',img_src:'https://img.example/flume.jpg'}]}),{status:200,headers:{'content-type':'application/json'}})}});lab.intakeFile(Buffer.from([1,2,3,4,5]),{name:'reference.png',mediaType:'image/png'});const run=await lab.findMatches({vertical:'images',userInitiated:true});assert.equal(run.interpretation.method,'AI_REFERENCE_DESCRIPTION');assert.equal(run.interpretation.trusted,false);assert.equal(run.query,'retro red water flume ride');});

test('Reference Lab shell exposes upload/search controls but refuses remote image loading',function(){const html=ReferenceLabHost.renderReferenceLabHtml();assert.match(html,/type="file"/);assert.match(html,/Find matching things/);assert.match(html,/AI eyesight/);assert.match(ReferenceLabHost.contentSecurityPolicy(),/img-src 'none'/);assert.doesNotMatch(html,/<img\b/i);});

test('image-search executor refuses re-digested credential reference tampering',async function(){const plan=ImageSearch.buildImageSearchPlan({query:'retro ride',provider:'brave'},{brave:{enabled:true}});plan.requests[0].auth.secretEnv='OPENAI_API_KEY';delete plan.planDigest;plan.planDigest=Digest.canonicalDigest(plan);let called=false;await assert.rejects(()=>ImageSearchExecutor.executeImageSearchPlan(plan,{networkAuthority:'EXPLICIT_ALLOW',env:{OPENAI_API_KEY:'must-not-leave-process'},fetchImpl:async()=>{called=true;return new Response('{}',{status:200,headers:{'content-type':'application/json'}})}}),error=>error&&error.code==='IMAGE_SEARCH_PROVIDER_FAILED'&&error.details.code==='IMAGE_SEARCH_AUTH_REF_REFUSED');assert.equal(called,false);});

test('image-search response byte limit cancels the stream before full buffering',async function(){let pulls=0,canceled=false;const stream=new ReadableStream({pull(controller){pulls+=1;controller.enqueue(new Uint8Array(700));if(pulls>=5)controller.close();},cancel(){canceled=true;}}),response=new Response(stream,{headers:{'content-type':'application/json'}});await assert.rejects(()=>ImageSearchExecutor.readBoundedJson(response,1024),error=>error&&error.code==='IMAGE_SEARCH_RESPONSE_BYTES_LIMIT');assert.equal(canceled,true);assert.ok(pulls<5);});
