#!/usr/bin/env node
'use strict';
const assert=require('assert');
const fs=require('fs');
const path=require('path');
const {validateContract}=require('../../hub/module-contract-verifier.js');
const screenContracts=require('../../shared/presentation-spine/screen-contract.js');
const presentationRecipe=require('../../shared/presentation-spine/presentation-recipe.js');
const read=name=>fs.readFileSync(path.join(__dirname,name),'utf8');
const manifest=JSON.parse(read('manifest.json'));
const contract=JSON.parse(read('module.contract.json'));
const html=read('index.html'),css=read('styles.css'),app=read('app.js');
const report=JSON.parse(read('migration-report.json'));
const checked=validateContract(contract,manifest);
assert.equal(checked.pass,true,checked.errors.join('; '));
assert.equal(manifest.status,'TEST');
assert.equal(manifest.version,contract.version);
assert.deepStrictEqual(manifest.permissions,[]);
assert(html.includes('../../shared/presentation-spine/presentation-spine.css'));
assert(html.includes('../../shared/presentation-spine/presentation-recipe.js'));
assert(html.includes('data-axm-profile="lab"'));
assert(html.includes('Shared by default. Module by choice.'));
assert.equal(manifest.presentation.schema,'axm.presentation-policy/v1');
assert.equal(manifest.presentation.moduleVisual,true);
assert.equal(manifest.presentation.screenPreset,'creative');
assert.deepStrictEqual(manifest.presentation.editableLayers,['surface','depth','motion','density','signal']);
const diagnostic=screenContracts.resolve({id:'verifier-lab',tags:['verification']});
assert.equal(diagnostic.schema,'axm.screen-contract/v1');
assert.equal(diagnostic.preset,'instrument');
assert.deepStrictEqual(diagnostic.presentation.editableLayers,['density','signal']);
assert.equal(diagnostic.behavior.editable,false);
assert.equal(diagnostic.resourcePolicy.separation,'capability-first');
assert(diagnostic.resourcePolicy.presentationFallbacks.includes('lower-asset-resolution'));
assert(diagnostic.boundaries.includes('no-silent-capability-downgrade'));
assert.equal(screenContracts.resolve({id:'technical-art-validator',tags:['visual']}).preset,'instrument');
const limited=screenContracts.limitRecipe(presentationRecipe,{layers:{surface:'solid',depth:'dimensional',motion:'ambient',density:'compact',signal:'luminous'}},diagnostic);
assert.equal(limited.layers.surface,'glass');
assert.equal(limited.layers.density,'compact');
['cockpit','studio','dashboard','lab'].forEach(profile=>assert(html.includes(`data-profile="${profile}"`)));
assert(app.includes('AXMPresentationSpine.applyProfile'));
assert(html.includes('id="recipeForm"') && html.includes('id="applyRecipe"') && html.includes('id="recipeFile"'));
assert(app.includes("type:'hub:presentation:recipe'"));
assert(app.includes('recipeApi.validate(parsed)'));
assert(app.includes("link.download='axm-presentation-recipe-"));
assert(css.includes('.recipe-preview[data-depth="dimensional"]'));
assert(!/https?:\/\//.test(html+css+app));
assert.equal(report.schema,'axm.presentation-spine.migration-report/v1');
assert.equal(report.deterministic,true);
assert(contract.boundaries.refuses.includes('automatic-host-rewrite'));
assert(contract.boundaries.refuses.includes('automatic-visual-approval'));
assert(contract.boundaries.refuses.includes('behavior-change'));
assert(contract.boundaries.refuses.includes('hardware-capability-claim'));
console.log(`PASS Presentation Spine tool · 4 profiles · ${report.totals.surfaces} mapped surfaces · no host authority`);
