(function () {
  'use strict';
  var O=AXMOps,notice=document.getElementById('notice'),zero=new Array(65).join('0'),loadedGoal=null,activeMeter=null,lastState=null;
  var observation={schema:'axm.mirror.cognitive-work-observation-draft/v1',source:{sourceSystemId:'openai.codex.goal-tracker',sourceRecordId:'goal-record-id',sourceRecordDigest:null,collectionMethod:'DIRECT_MACHINE_METER',authorshipState:'DECLARED_NOT_CERTIFIED',measurementDefinitionDigest:null},objective:{objectiveKind:'SOFTWARE_BUILD',objectiveDigest:zero,startingStateDigest:null,endingStateDigest:null},workShape:{operationKinds:['BUILD'],domainKinds:['SOFTWARE'],requestedOutputKinds:['WORKSHOP_MODULE'],riskTier:'MEDIUM',requiredVerificationKinds:['SELFTEST']},execution:{modelProfileDigest:null,toolchainDigest:null,environmentDigest:null,hardwareProfileDigest:null,tokenMeter:{definitionId:'axm.workshop.codex-goal-total-tokens/v1',coverage:'PARTIAL',inputTokens:null,cachedInputTokens:null,outputTokens:null,reasoningTokens:null,totalTokens:null},computeMeter:{definitionId:null,coverage:'UNKNOWN',cpuCoreMilliseconds:null,acceleratorMilliseconds:null,peakMemoryBytes:null,providerComputeUnitsMicros:null},timing:{wallMilliseconds:null,toolMilliseconds:null},workCounts:{filesExamined:null,filesChanged:null,linesAdded:null,linesRemoved:null,toolCalls:null},verification:{testsExecuted:null,testsPassed:null,testsFailed:null,testsNotRun:null,verificationDigest:null}},outcome:{state:'HOLD',status:'TEST',preexistingImplementationState:'UNKNOWN'},costObservation:{basis:'UNKNOWN',profileDigest:null,currency:null,moneyMicros:null,energyMilliwattHours:null,carbonMilligrams:null},permission:{status:'UNKNOWN',basisDigest:null}};
  var economics={schema:'axm.mirror.cognitive-resource-economics-profile-draft/v1',source:{sourceSystemId:'declared-rate-source',sourceRecordId:'rate-schedule-id',sourceRecordDigest:null,collectionMethod:'MANUAL_DECLARATION',authorshipState:'DECLARED_NOT_CERTIFIED',rateScheduleDigest:null,effectiveWindowId:null,freshnessState:'UNKNOWN'},scope:{accountingMode:'PROVIDER_TOKEN_BILLING',currency:'USD',modelProfileDigest:null,hardwareProfileDigest:null,tokenMeterDefinitionId:'axm.workshop.codex-goal-total-tokens/v1',computeMeterDefinitionId:null},components:[{metric:'TOTAL_TOKENS',quantityDenominator:1000000,moneyMicrosPerQuantity:0,energyMilliwattHoursPerQuantity:null,carbonMilligramsPerQuantity:null}],permission:{status:'UNKNOWN',basisDigest:null}};
  var profile={schema:'axm.cognitive-resource.machine-profile-seal/v1',kind:'HARDWARE',source:{sourceSystemId:'axm.workshop.local-hardware-meter',sourceRecordId:'hardware-profile-id',sourceRecordDigest:null,collectionMethod:'MANUAL_DECLARATION',authorshipState:'DECLARED_NOT_CERTIFIED'},attributes:{cpuArchitecture:null,cpuModelClass:null,cpuLogicalCores:null,memoryBytes:null,acceleratorClass:null,acceleratorCount:null},permission:{status:'UNKNOWN',basisDigest:null}};
  document.getElementById('observation').value=JSON.stringify(observation,null,2);document.getElementById('economics').value=JSON.stringify(economics,null,2);document.getElementById('profileSeal').value=JSON.stringify(profile,null,2);
  function parse(id){try{return JSON.parse(document.getElementById(id).value);}catch(_){throw new Error(id+' must contain valid JSON');}}
  function number(id){var text=document.getElementById(id).value.trim();if(text==='')return null;var value=Number(text);if(!Number.isSafeInteger(value)||value<0)throw new Error(id+' requires a non-negative safe integer');return value;}
  function digestText(text){return crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(text))).then(function(bytes){return Array.from(new Uint8Array(bytes)).map(function(v){return v.toString(16).padStart(2,'0');}).join('');});}
  function result(value,message){if(value&&value.record&&value.record.id)document.getElementById('recordId').value=value.record.id;O.notice(notice,message,'ok');document.getElementById('out').textContent=O.pretty(value);setTimeout(load,150);}
  function error(reason){O.notice(notice,reason.message||String(reason),'bad');}
  function explanation(value){var x=value&&value.explanation;if(!x)return O.pretty(value);if(!x.issues.length)return 'READY — no structural holds detected. This remains evidence, not authority.';return x.state+'\n\n'+x.issues.map(function(item){return '• '+item.code+'\n  '+item.guidance;}).join('\n');}
  function permissionDigest(){return digestText('local-explicit-cognitive-evidence-permission-v1');}
  function buildGoal(){return Promise.all([digestText(document.getElementById('objectiveLabel').value),permissionDigest()]).then(function(values){var executed=number('testsExecuted'),failed=number('testsFailed'),passed=number('testsPassed');if(executed!==null){failed=failed===null?0:failed;passed=passed===null?executed-failed:passed;}else{passed=null;failed=null;}var receipt={schema:'axm.workshop.codex-goal-completion-receipt/v1',goalRunId:document.getElementById('goalRunId').value.trim(),objectiveDigest:values[0],startingStateDigest:null,endingStateDigest:null,workShape:{operationKinds:['BUILD'],domainKinds:['SOFTWARE'],requestedOutputKinds:['WORKSHOP_MODULE'],riskTier:'MEDIUM',requiredVerificationKinds:['SELFTEST']},profiles:{modelProfileDigest:null,toolchainDigest:null,environmentDigest:null,hardwareProfileDigest:null},totalTokens:number('totalTokens'),timing:{wallMilliseconds:number('wallMilliseconds'),toolMilliseconds:null},workCounts:{filesExamined:null,filesChanged:null,linesAdded:null,linesRemoved:null,toolCalls:null},verification:{testsExecuted:executed,testsPassed:passed,testsFailed:failed,testsNotRun:null,verificationDigest:null},outcome:{state:'VERIFIED_PARTIAL',status:'TEST',preexistingImplementationState:'UNKNOWN'},permission:{status:'ALLOWED',basisDigest:values[1]}};document.getElementById('goalJson').value=JSON.stringify(receipt,null,2);return receipt;});}
  function currentGoal(){if(loadedGoal)return Promise.resolve(loadedGoal);var text=document.getElementById('goalJson').value.trim();if(text){try{return Promise.resolve(JSON.parse(text));}catch(_){}}return buildGoal();}
  document.getElementById('goalFile').onchange=function(event){var file=event.target.files&&event.target.files[0];if(!file)return;file.text().then(function(text){var value=JSON.parse(text);if(value.schema==='axm.workshop.codex-goal-completion-receipt/v1'){loadedGoal=value;document.getElementById('goalJson').value=JSON.stringify(value,null,2);O.notice(notice,'Goal receipt loaded locally; preview before import.','ok');}else if(value.schema==='axm.mirror.cognitive-work-observation-draft/v1'){document.getElementById('observation').value=JSON.stringify(value,null,2);O.notice(notice,'Exact observation loaded into Advanced tools; nothing archived.','ok');}else throw new Error('unsupported receipt schema');}).catch(error);};
  document.getElementById('previewGoal').onclick=function(){currentGoal().then(function(receipt){return O.post('/api/cognitive-resource-meter/preview-goal-receipt',{receipt:receipt});}).then(function(value){document.getElementById('goalHold').textContent=explanation(value);document.getElementById('observation').value=JSON.stringify(value.draft,null,2);document.getElementById('out').textContent=O.pretty(value);}).catch(error);};
  document.getElementById('importGoal').onclick=function(){currentGoal().then(function(receipt){return O.post('/api/cognitive-resource-meter/goal-receipt/import',{receipt:receipt,supersedesId:null},{'x-axm-cognitive-resource':'explicit-goal-import'});}).then(function(value){loadedGoal=null;result(value,'Goal receipt processed: '+value.state);}).catch(error);};
  function objectivePermission(labelId){return Promise.all([digestText(document.getElementById(labelId).value),permissionDigest()]).then(function(values){return {objectiveDigest:values[0],permission:{status:'ALLOWED',basisDigest:values[1]}};});}
  document.getElementById('startLocalMeter').onclick=function(){objectivePermission('meterObjectiveLabel').then(function(body){return O.post('/api/cognitive-resource-meter/local-meter/start',body,{'x-axm-cognitive-resource':'explicit-meter-start'});}).then(function(value){activeMeter=value.session&&value.session.id||null;document.getElementById('meterResult').textContent=O.pretty(value);O.notice(notice,activeMeter?'Explicit process window started.':'Meter held; nothing started.',activeMeter?'ok':'bad');}).catch(error);};
  document.getElementById('stopLocalMeter').onclick=function(){if(!activeMeter)return error(new Error('No local meter session is active in this page.'));O.post('/api/cognitive-resource-meter/local-meter/stop',{sessionId:activeMeter},{'x-axm-cognitive-resource':'explicit-meter-stop'}).then(function(value){activeMeter=null;document.getElementById('meterResult').textContent=O.pretty(value);var draft=parse('observation');draft.execution.computeMeter=value.observationPatch.computeMeter;draft.execution.timing=value.observationPatch.timing;document.getElementById('observation').value=JSON.stringify(draft,null,2);result(value,'Partial local process evidence archived and patched into Advanced observation.');}).catch(error);};
  document.getElementById('cancelLocalMeter').onclick=function(){if(!activeMeter)return error(new Error('No local meter session is active in this page.'));O.post('/api/cognitive-resource-meter/local-meter/cancel',{sessionId:activeMeter,confirmation:'CANCEL LOCAL PROCESS METER'},{'x-axm-cognitive-resource':'explicit-meter-cancel'}).then(function(value){activeMeter=null;document.getElementById('meterResult').textContent=O.pretty(value);O.notice(notice,'Local meter cancelled without archive.','ok');}).catch(error);};
  var metrics={PROVIDER_TOKEN_BILLING:['TOTAL_TOKENS','INPUT_TOKENS','CACHED_INPUT_TOKENS','OUTPUT_TOKENS','REASONING_TOKENS'],PROVIDER_COMPUTE_UNIT_BILLING:['PROVIDER_COMPUTE_UNITS_MICROS'],LOCAL_HARDWARE_TIME:['CPU_CORE_MILLISECONDS','ACCELERATOR_MILLISECONDS']};
  function rateMode(){var mode=document.getElementById('rateMode').value,select=document.getElementById('rateMetric'),current=select.value;select.innerHTML=metrics[mode].map(function(metric){return '<option>'+metric+'</option>';}).join('');if(metrics[mode].indexOf(current)>=0)select.value=current;}
  document.getElementById('rateMode').onchange=rateMode;rateMode();
  function buildRate(){var mode=document.getElementById('rateMode').value,metric=document.getElementById('rateMetric').value,sourceId=document.getElementById('rateSourceId').value.trim(),profileDigest=document.getElementById('rateProfileDigest').value.trim()||null,money=number('rateMoney'),energy=number('rateEnergy'),carbon=number('rateCarbon');if(money===null&&energy===null&&carbon===null)throw new Error('Declare at least one money, energy or carbon rate.');var seed={mode:mode,metric:metric,sourceId:sourceId,profileDigest:profileDigest,money:money,energy:energy,carbon:carbon,denominator:number('rateDenominator'),freshness:document.getElementById('rateFreshness').value};return Promise.all([digestText(JSON.stringify(seed)),permissionDigest()]).then(function(values){var isToken=mode==='PROVIDER_TOKEN_BILLING',isLocal=mode==='LOCAL_HARDWARE_TIME',currency=money===null?null:document.getElementById('rateCurrency').value.trim().toUpperCase();var draft={schema:'axm.mirror.cognitive-resource-economics-profile-draft/v1',source:{sourceSystemId:'declared-rate-source',sourceRecordId:sourceId,sourceRecordDigest:values[0],collectionMethod:'MANUAL_DECLARATION',authorshipState:'DECLARED_NOT_CERTIFIED',rateScheduleDigest:values[0],effectiveWindowId:null,freshnessState:seed.freshness},scope:{accountingMode:mode,currency:currency,modelProfileDigest:isLocal?null:profileDigest,hardwareProfileDigest:isLocal?profileDigest:null,tokenMeterDefinitionId:isToken?'axm.workshop.codex-goal-total-tokens/v1':null,computeMeterDefinitionId:isToken?null:(isLocal?'axm.workshop.local-process-time/v1':'provider.compute-unit/v1')},components:[{metric:metric,quantityDenominator:seed.denominator,moneyMicrosPerQuantity:money,energyMilliwattHoursPerQuantity:energy,carbonMilligramsPerQuantity:carbon}],permission:{status:'ALLOWED',basisDigest:values[1]}};document.getElementById('economics').value=JSON.stringify(draft,null,2);return draft;});}
  document.getElementById('previewRate').onclick=function(){Promise.resolve().then(buildRate).then(function(draft){return O.post('/api/cognitive-resource-meter/preview-economics',{draft:draft});}).then(function(value){document.getElementById('rateHold').textContent=explanation(value);document.getElementById('out').textContent=O.pretty(value);}).catch(error);};
  document.getElementById('saveRate').onclick=function(){Promise.resolve().then(buildRate).then(function(draft){return O.post('/api/cognitive-resource-meter/economics-profile',{draft:draft,supersedesId:null},{'x-axm-cognitive-resource':'explicit-capture'});}).then(function(value){result(value,'Rate schedule processed: '+value.state);}).catch(error);};
  function renderVaults(vaults){document.getElementById('profileCount').textContent=vaults.profiles.length;document.getElementById('rateCount').textContent=vaults.rateSchedules.length;document.getElementById('profileVault').innerHTML=vaults.profiles.length?vaults.profiles.map(function(item){return '<button class="vault-card" data-record="'+O.esc(item.recordId)+'"><b>'+O.esc(item.record.kind)+'</b><span>'+O.esc(item.recordId)+'</span><span>'+O.esc(item.recordDigest)+'</span></button>';}).join(''):'No sealed profiles.';document.getElementById('rateVault').innerHTML=vaults.rateSchedules.length?vaults.rateSchedules.map(function(item){return '<button class="vault-card" data-record="'+O.esc(item.recordId)+'"><b>'+O.esc(item.record.scope.accountingMode)+'</b><span>'+O.esc(item.record.source.freshnessState)+' · '+O.esc(item.record.scope.currency||'NO MONEY')+'</span><span>'+O.esc(item.recordId)+'</span></button>';}).join(''):'No schedules.';Array.from(document.querySelectorAll('[data-record]')).forEach(function(node){node.onclick=function(){document.getElementById('recordId').value=node.dataset.record;O.get('/api/cognitive-resource-meter/record?id='+encodeURIComponent(node.dataset.record)).then(function(value){document.getElementById('out').textContent=O.pretty(value);}).catch(error);};});}
  function renderTimeline(data){var observations=data.observations||[],dimensions=[['Tokens',function(x){return x.tokenMeter.totalTokens;}],['CPU core ms',function(x){return x.computeMeter.cpuCoreMilliseconds;}],['Wall ms',function(x){return x.timing.wallMilliseconds;}],['Tests',function(x){return x.verification.testsExecuted;}]],maxima=dimensions.map(function(d){return Math.max.apply(null,[1].concat(observations.map(function(x){return Number(d[1](x))||0;})));});document.getElementById('timeline').innerHTML=observations.length?observations.map(function(item){return '<article class="timeline-run"><header><b>'+O.esc(item.sourceRecordId||item.recordId)+'</b><span>'+O.esc(item.outcome.state)+'</span></header>'+dimensions.map(function(d,index){var value=d[1](item),width=value===null?0:Math.round((Number(value)||0)/maxima[index]*100);return '<div class="dimension"><span>'+d[0]+'</span><span class="bar"><i style="width:'+width+'%"></i></span><b>'+(value===null?'UNKNOWN':O.esc(value))+'</b></div>';}).join('')+'</article>';}).join(''):'No observations yet.';}
  function load(){Promise.all([O.get('/api/cognitive-resource-meter'),O.get('/api/cognitive-resource-meter/vaults'),O.get('/api/cognitive-resource-meter/timeline')]).then(function(values){var state=values[0];lastState=state;document.getElementById('facts').innerHTML='<span>'+state.counts.records+' records</span><span>'+state.counts.profiles+' profiles</span><span>'+state.counts.rateSchedules+' rate schedules</span><span>'+state.counts.activeLocalMeters+' active meters</span><span>'+state.hands.length+' Hands</span><span>'+state.requiredThirdPartyDependencies.length+' dependencies</span>';document.getElementById('providers').textContent=O.pretty({contracts:state.contracts,providers:state.providers,meterDefinitions:state.meterDefinitions,hands:state.hands,limits:state.knownLimits});renderVaults(values[1]);renderTimeline(values[2]);document.getElementById('bundleIds').placeholder=state.records.filter(function(item){return item.state==='ACTIVE';}).map(function(item){return item.id;}).join('\n')||'No active records yet';document.getElementById('out').textContent=O.pretty(state.records);}).catch(error);}
  document.getElementById('exportBundle').onclick=function(){var ids=document.getElementById('bundleIds').value.split(/\r?\n/).map(function(x){return x.trim();}).filter(Boolean);if(!ids.length&&lastState)ids=lastState.records.filter(function(item){return item.state==='ACTIVE';}).map(function(item){return item.id;});O.post('/api/cognitive-resource-meter/bundle',{recordIds:ids,confirmation:'EXPORT COGNITIVE EVIDENCE BUNDLE'},{'x-axm-cognitive-resource':'explicit-bundle'}).then(function(value){result(value,'Portable evidence bundle exported.');}).catch(error);};
  document.getElementById('previewObservation').onclick=function(){var draft;try{draft=parse('observation');}catch(reason){return error(reason);}O.post('/api/cognitive-resource-meter/preview-observation',{draft:draft}).then(function(value){document.getElementById('goalHold').textContent=explanation(value);document.getElementById('out').textContent=O.pretty(value);}).catch(error);};
  document.getElementById('captureObservation').onclick=function(){var draft;try{draft=parse('observation');}catch(reason){return error(reason);}O.post('/api/cognitive-resource-meter/provider-run',{providerDeclarationId:document.getElementById('provider').value,draft:draft,supersedesId:null},{'x-axm-cognitive-resource':'explicit-capture'}).then(function(value){result(value,'Observation processed: '+value.state);}).catch(error);};
  document.getElementById('previewEconomics').onclick=function(){var draft;try{draft=parse('economics');}catch(reason){return error(reason);}O.post('/api/cognitive-resource-meter/preview-economics',{draft:draft}).then(function(value){document.getElementById('rateHold').textContent=explanation(value);document.getElementById('out').textContent=O.pretty(value);}).catch(error);};
  document.getElementById('captureEconomics').onclick=function(){var draft;try{draft=parse('economics');}catch(reason){return error(reason);}O.post('/api/cognitive-resource-meter/economics-profile',{draft:draft,supersedesId:null},{'x-axm-cognitive-resource':'explicit-capture'}).then(function(value){result(value,'Economics profile processed: '+value.state);}).catch(error);};
  document.getElementById('allowProfile').onclick=function(){var value;try{value=parse('profileSeal');}catch(reason){return error(reason);}Promise.all([permissionDigest(),digestText(JSON.stringify({kind:value.kind,sourceSystemId:value.source.sourceSystemId,sourceRecordId:value.source.sourceRecordId,attributes:value.attributes}))]).then(function(digests){value.permission={status:'ALLOWED',basisDigest:digests[0]};value.source.sourceRecordDigest=value.source.sourceRecordDigest||digests[1];document.getElementById('profileSeal').value=JSON.stringify(value,null,2);O.notice(notice,'Local permission and content digests added; inspect before sealing.','ok');}).catch(error);};
  document.getElementById('sealProfile').onclick=function(){var value;try{value=parse('profileSeal');}catch(reason){return error(reason);}O.post('/api/cognitive-resource-meter/profile-seal',{profile:value},{'x-axm-cognitive-resource':'explicit-seal'}).then(function(receipt){result(receipt,'Profile processed: '+receipt.state);}).catch(error);};
  function id(){return document.getElementById('recordId').value.trim();}
  document.getElementById('inspect').onclick=function(){O.get('/api/cognitive-resource-meter/record?id='+encodeURIComponent(id())).then(function(value){document.getElementById('out').textContent=O.pretty(value);}).catch(error);};
  document.getElementById('archive').onclick=function(){O.post('/api/cognitive-resource-meter/archive',{id:id(),confirmation:'ARCHIVE COGNITIVE RECORD'},{'x-axm-cognitive-resource':'explicit-archive'}).then(function(value){result(value,'Record archived.');}).catch(error);};
  document.getElementById('restore').onclick=function(){O.post('/api/cognitive-resource-meter/restore',{id:id(),confirmation:'RESTORE COGNITIVE RECORD'},{'x-axm-cognitive-resource':'explicit-restore'}).then(function(value){result(value,'Record restored.');}).catch(error);};
  document.getElementById('export').onclick=function(){O.post('/api/cognitive-resource-meter/export',{id:id(),confirmation:'EXPORT EXACT COGNITIVE DRAFT'},{'x-axm-cognitive-resource':'explicit-export'}).then(function(value){result(value,'Exact draft exported without a Mirror write.');}).catch(error);};
  document.getElementById('refresh').onclick=load;buildGoal().catch(error);load();
})();
