#!/usr/bin/env node
'use strict';
const http=require('http'),crypto=require('crypto'),fs=require('fs'),path=require('path'),Core=require('./lumenwake-core.cjs'),SeatInterface=require('./seat-interface.cjs');
const HOST=process.env.AXM_LUMEN_HOST||'0.0.0.0',PORT=Number(process.env.PORT||8796),ROOM='AXM1',SESSION_ID=process.env.AXM_SESSION_ID||crypto.randomUUID(),ROOT=__dirname,CLIENT=path.join(ROOT,'lumenwake-client.html'),THREE_CLIENT=path.join(ROOT,'lumenwake-three.js'),THREE_VENDOR=path.resolve(ROOT,'../../../../../shared/vendor/three-r160/three.module.js'),TICK=1000/30,STREAM=66;
function loadSeats(){try{const list=JSON.parse(process.env.AXM_PLAYERS_JSON||'[]');if(Array.isArray(list)&&list.length)return list.slice(0,4);}catch(e){}return[{display_name:'Player 1',type:'human'}];}
const configuredSeats=loadSeats();
let selectedMap='aurora-basin',game=Core.create(configuredSeats,Date.now(),{mapId:selectedMap}),last=Date.now(),lastTickError=null;const inputs={},streams=new Set(),seatBindings=SeatInterface.createSeatBindings(game,configuredSeats);
function resetInputs(){Object.keys(inputs).forEach(id=>delete inputs[id]);Object.keys(game.players).forEach(id=>inputs[id]={moveX:0,moveY:0,action:false,dash:false,updatedAt:0,sequence:-1,rateWindow:[]});}
resetInputs();
function tick(){const now=Date.now(),dt=Math.min(.08,(now-last)/1000);last=now;try{Core.step(game,inputs,dt,now);Object.values(inputs).forEach(input=>{input.action=false;input.dash=false;});lastTickError=null;}catch(error){lastTickError=String(error&&error.message||error).slice(0,180);game.event='AURORA TICK RECOVERED · INPUTS RESET';game.eventAt=now;resetInputs();}}
function send(res,code,value){const body=JSON.stringify(value);res.writeHead(code,{'content-type':'application/json; charset=utf-8','content-length':Buffer.byteLength(body),'cache-control':'no-store','access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,x-axm-seat-token,authorization'});res.end(body);}
function body(req){return new Promise((resolve,reject)=>{let raw='';req.on('data',c=>{raw+=c;if(raw.length>25000)req.destroy();});req.on('end',()=>{try{resolve(raw?JSON.parse(raw):{});}catch(e){reject(e);}});req.on('error',reject);});}
function serve(file,res,type){res.writeHead(200,{'content-type':type,'cache-control':'no-store'});fs.createReadStream(file).pipe(res);}
function isLoopback(req){const remote=String(req.socket&&req.socket.remoteAddress||'');return /^(?:127\.|::1$|::ffff:127\.)/.test(remote);}
function bearer(req){return String(req.headers['x-axm-seat-token']||req.headers.authorization||'').replace(/^Bearer\s+/i,'');}
function hostBootstrap(){return{ok:true,launch:{controllers:Object.values(game.players).filter(player=>player.kind==='human').map(player=>({seatId:player.seatId,playerId:player.id,displayName:player.name,url:'/?room='+ROOM+'&player='+player.id})),adapterBindings:SeatInterface.publicBindings(seatBindings),partyScreens:[{partyId:'A',url:'/?room='+ROOM+'&player=screen'}]}};}
const mime={'.svg':'image/svg+xml','.png':'image/png','.webmanifest':'application/manifest+json'};
const server=http.createServer(async(req,res)=>{const url=new URL(req.url,'http://lumenwake.local');try{
  if(req.method==='OPTIONS'){res.writeHead(204,{'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,OPTIONS','access-control-allow-headers':'content-type,x-axm-seat-token,authorization'});return res.end();}
  if(req.method==='GET'&&(url.pathname==='/'||url.pathname==='/index.html'))return serve(CLIENT,res,'text/html; charset=utf-8');
  if(req.method==='GET'&&url.pathname==='/lumenwake-three.js')return serve(THREE_CLIENT,res,'text/javascript; charset=utf-8');
  if(req.method==='GET'&&url.pathname==='/vendor/three.module.js')return serve(THREE_VENDOR,res,'text/javascript; charset=utf-8');
  if(req.method==='GET'&&url.pathname==='/api/host/bootstrap'){if(!isLoopback(req))return send(res,403,{ok:false,error:'host-bootstrap-loopback-only'});return send(res,200,hostBootstrap());}
  if(req.method==='GET'&&url.pathname==='/api/adapter-observation'){const result=SeatInterface.buildAdapterObservation(game,{roomCode:url.searchParams.get('room'),seatId:url.searchParams.get('seat'),token:bearer(req)},{bindings:seatBindings,inputs,roomCode:ROOM,sessionId:SESSION_ID});return send(res,result.statusCode||(result.ok?200:400),result);}
  if(req.method==='GET'&&(url.pathname==='/state'||url.pathname==='/health')){const state=Core.publicState(game);state.runtime={ok:!lastTickError,lastTickError};return send(res,200,state);}
  if(req.method==='GET'&&url.pathname==='/controller-state'){const id=/^p[1-4]$/.test(url.searchParams.get('player')||'')?url.searchParams.get('player'):'';if(!game.players[id])return send(res,404,{ok:false,error:'seat not found'});return send(res,200,Core.controllerState(game,id));}
  if(req.method==='GET'&&url.pathname==='/events'){const player=/^p[1-4]$/.test(url.searchParams.get('player')||'')?url.searchParams.get('player'):null,client={res,player,compact:!!player};res.writeHead(200,{'content-type':'text/event-stream','cache-control':'no-cache',connection:'keep-alive','access-control-allow-origin':'*'});res.write('retry: 800\n\n');streams.add(client);const drop=()=>streams.delete(client);req.on('close',drop);res.on('close',drop);res.on('error',drop);return;}
  if(req.method==='GET'&&url.pathname.startsWith('/assets/')){const file=path.resolve(ROOT,'.'+url.pathname),base=path.resolve(ROOT,'assets')+path.sep;if(!file.startsWith(base)||!fs.existsSync(file))return send(res,404,{ok:false});return serve(file,res,mime[path.extname(file)]||'application/octet-stream');}
  if(req.method==='POST'&&url.pathname==='/api/input'){const packet=await body(req),result=SeatInterface.routeSemanticInput(game,inputs,Object.assign({},packet,{token:packet.token||bearer(req)}),{bindings:seatBindings,requireToken:true,roomCode:ROOM});return send(res,result.statusCode||(result.ok?200:400),result.ok?result:Object.assign({error:result.reason},result));}
  if(req.method==='POST'&&url.pathname==='/input'){const id=/^p[1-4]$/.test(url.searchParams.get('player')||'')?url.searchParams.get('player'):'';const payload=await body(req),result=SeatInterface.routeSemanticInput(game,inputs,{intent:payload},{playerId:id,requireToken:false,roomCode:ROOM});return send(res,result.statusCode||(result.ok?200:400),result.ok?result:Object.assign({error:result.reason},result));}
  if(req.method==='POST'&&url.pathname==='/start'){const started=Core.start(game,Date.now());return send(res,started?200:409,{ok:started,state:Core.publicState(game),error:started?null:'run is not waiting to start'});}
  if(req.method==='POST'&&url.pathname==='/map'){if(game.phase==='running'||game.phase==='countdown')return send(res,409,{ok:false,error:'route can only change between runs'});const payload=await body(req),ids=Core.MAPS.map(map=>map.id),requested=String(payload.mapId||''),index=ids.indexOf(selectedMap);selectedMap=ids.includes(requested)?requested:ids[(index+1)%ids.length];game=Core.create(configuredSeats,Date.now(),{mapId:selectedMap});resetInputs();last=Date.now();return send(res,200,{ok:true,state:Core.publicState(game)});}
  if(req.method==='POST'&&url.pathname==='/restart'){game=Core.create(configuredSeats,Date.now(),{mapId:selectedMap});resetInputs();last=Date.now();return send(res,200,{ok:true,state:Core.publicState(game)});}
  return send(res,404,{ok:false,error:'not found'});
}catch(e){return send(res,400,{ok:false,error:e.message});}});
const physics=setInterval(tick,TICK),stream=setInterval(()=>{let fullPacket=null;for(const client of streams){try{if(client.res.destroyed||client.res.writableEnded){streams.delete(client);continue;}const packet=client.compact?'data: '+JSON.stringify(Core.controllerState(game,client.player))+'\n\n':(fullPacket||(fullPacket='data: '+JSON.stringify(Core.publicState(game))+'\n\n'));client.res.write(packet);}catch(e){streams.delete(client);try{client.res.destroy();}catch(_){}}}},STREAM);
server.on('clientError',(error,socket)=>{try{socket.end('HTTP/1.1 400 Bad Request\r\n\r\n');}catch(_){try{socket.destroy();}catch(__){}}});
server.listen(PORT,HOST,()=>{console.log('Lumenwake '+game.version+' · 1–4 player co-op · Human/Adapter/AI seats');console.log('Local: http://127.0.0.1:'+PORT+'/?player=screen');});
function shutdown(){clearInterval(physics);clearInterval(stream);for(const client of streams){try{client.res.end();}catch(e){}}server.close(()=>process.exit(0));setTimeout(()=>process.exit(0),700).unref();}process.on('SIGINT',shutdown);process.on('SIGTERM',shutdown);
