'use strict';
const COLORS=['cyan','violet','gold'];
const PALETTE=['#55ecff','#ff6bd6','#ffd66b','#82ff9f'];
const MAPS=[
  {id:'aurora-basin',name:'Aurora Basin',description:'Open orbit · balanced light routes',enemySpeedScale:.9,enemySpawnScale:1.12,shardRadius:[15,40],duets:[{id:'duet_1',label:'EMBER WEAVE',color:'#ff6bd6',pads:[{x:22,y:18},{x:34,y:18}]},{id:'duet_2',label:'SKY WEAVE',color:'#55ecff',pads:[{x:66,y:46},{x:78,y:46}]}],shrines:[{id:'shrine_1',label:'NORTH CHORD',color:'#55ecff',x:50,y:12},{id:'shrine_2',label:'WEST CHORD',color:'#ff6bd6',x:16,y:40},{id:'shrine_3',label:'EAST CHORD',color:'#ffd66b',x:84,y:40}]},
  {id:'prism-causeway',name:'Prism Causeway',description:'Crossing lanes · slower gloom · tighter duets',enemySpeedScale:.78,enemySpawnScale:1.24,shardRadius:[10,34],duets:[{id:'duet_1',label:'LOW TIDE WEAVE',color:'#55ecff',pads:[{x:18,y:49},{x:31,y:49}]},{id:'duet_2',label:'HIGH TIDE WEAVE',color:'#ff6bd6',pads:[{x:69,y:15},{x:82,y:15}]}],shrines:[{id:'shrine_1',label:'PRISM ENTRY',color:'#ffd66b',x:24,y:32},{id:'shrine_2',label:'PRISM HEART',color:'#ff6bd6',x:50,y:32},{id:'shrine_3',label:'PRISM EXIT',color:'#55ecff',x:76,y:32}]}
];
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
function length(x,y){return Math.hypot(x,y)||.0001;}
function clean(v,fallback){const s=String(v||'').replace(/[^a-z0-9 _-]/gi,'').trim().slice(0,22);return s||fallback;}
function random(g){g.seed=(Math.imul(g.seed,1664525)+1013904223)>>>0;return g.seed/4294967296;}
function event(g,text,now){g.event=text;g.eventAt=now;g.timeline.push({at:now,text});if(g.timeline.length>80)g.timeline.shift();}
function seatKind(value){return value==='human'||value==='adapter'||value==='ai'?value:'ai';}
function seats(input){let raw=Array.isArray(input)?input.slice(0,4):[];if(!raw.length)raw=[{display_name:'Player 1',type:'human'}];return raw.map((seat,i)=>({id:'p'+(i+1),seatId:seat.seat_id||'seat_'+(i+1),name:clean(seat.display_name,'Player '+(i+1)),kind:seatKind(seat.type),color:PALETTE[i]}));}
function mapDefinition(id){const source=MAPS.find(map=>map.id===id)||MAPS[0];return JSON.parse(JSON.stringify(source));}
function spawnShard(g,now,forcedColor){const range=g.map&&g.map.shardRadius||[15,40],angle=random(g)*Math.PI*2,radius=range[0]+random(g)*(range[1]-range[0]);g.shards.push({id:'s'+g.nextId++,color:forcedColor||COLORS[Math.floor(random(g)*COLORS.length)],x:50+Math.cos(angle)*radius,y:32+Math.sin(angle)*radius,bornAt:now});}
function spawnGloom(g,now){const edge=Math.floor(random(g)*4),p=random(g);let x=edge===0?2:edge===1?98:4+p*92,y=edge===2?2:edge===3?62:4+p*56;g.enemies.push({id:'g'+g.nextId++,x,y,hp:2,speed:(1.8+g.wave*.055)*(g.map&&g.map.enemySpeedScale||1),stunnedUntil:0,hitAt:0});}
function duetSites(map){return map.duets.map(site=>Object.assign(site,{progress:0,complete:false,occupants:[null,null]}));}
function resonanceSites(map){return map.shrines.map(site=>Object.assign(site,{progress:0,complete:false,firstPlayer:null,expiresAt:0}));}
function create(rawSeats,now,options){now=Number(now)||Date.now();const roster=seats(rawSeats),map=mapDefinition(options&&options.mapId),g={schema:'axm.lumenwake-state/v1',gameId:'006-lumenwake',version:'0.3.1-semantic-seat',seed:Number(options&&options.seed)||0x6a09e667,nextId:1,phase:'ready',createdAt:now,startAt:null,startedAt:null,endsAt:null,durationMs:210000,now,charge:0,goal:60+(roster.length-1)*58,wave:1,map,availableMaps:MAPS.map(item=>({id:item.id,name:item.name,description:item.description})),event:'FALLEN LIGHT DETECTED',eventAt:now,timeline:[],players:{},shards:[],enemies:[],effects:[],duets:duetSites(map),duetsCompleted:0,resonances:resonanceSites(map),resonancesCompleted:0,nextShardAt:now,nextEnemyAt:now+6500,result:null};
  roster.forEach((seat,i)=>{const angle=Math.PI*2*i/roster.length-Math.PI/2;g.players[seat.id]=Object.assign(seat,{x:50+Math.cos(angle)*9,y:32+Math.sin(angle)*9,hp:100,maxHp:100,down:false,downedAt:0,revive:0,invulnerableUntil:0,pulseReadyAt:0,dashReadyAt:0,dashUntil:0,carried:[],stats:{deposited:0,pulses:0,stuns:0,combos:0,revives:0,downs:0,colors:{cyan:0,violet:0,gold:0}}});});
  for(let i=0;i<9;i++)spawnShard(g,now,COLORS[i%3]);event(g,'CARRY THE LIGHT · COVER THE CARRIER',now);return g;
}
function start(g,now){now=Number(now)||Date.now();if(g.phase!=='ready')return false;g.phase='countdown';g.startAt=now+3500;g.now=now;event(g,'PARTY READY · LUMENWAKE BEGINS IN 3',now);return true;}
function inputShape(v){v=v||{};return{moveX:clamp(Number(v.moveX)||0,-1,1),moveY:clamp(Number(v.moveY)||0,-1,1),action:!!v.action,dash:!!v.dash,updatedAt:Number(v.updatedAt)||0};}
function nearest(list,p){let best=null,score=Infinity;for(const x of list){const d=Math.hypot(x.x-p.x,x.y-p.y);if(d<score){score=d;best=x;}}return{item:best,distance:score};}
function aiInput(g,p,now){const mates=Object.values(g.players),down=nearest(mates.filter(x=>x.down&&x.id!==p.id),p),threat=nearest(g.enemies.filter(x=>x.stunnedUntil<=now),p),coreThreat=g.enemies.filter(x=>x.stunnedUntil<=now).sort((a,b)=>Math.hypot(a.x-50,a.y-32)-Math.hypot(b.x-50,b.y-32))[0],partySize=mates.length,playerIndex=Number(p.id.slice(1))-1,duet=partySize>1&&g.duets.find(x=>!x.complete),assigned=g.shards.filter(s=>(Number(String(s.id).replace(/\D/g,''))||0)%partySize===playerIndex),gather=nearest(assigned.length?assigned:g.shards,p).item,defender=partySize===1||p.id==='p'+partySize;let target=null;if(down.item)target=down.item;else if(p.carried.length)target={x:50,y:32};else if(duet)target=duet.pads[playerIndex%2];else if(defender&&coreThreat&&Math.hypot(coreThreat.x-50,coreThreat.y-32)<15)target=coreThreat;else target=gather||{x:50,y:32};const dx=target.x-p.x,dy=target.y-p.y,d=length(dx,dy),wobble=Math.sin(now*.0017+Number(p.id.slice(1))*2.13)*.16;return{moveX:dx/d-wobble*dy/d,moveY:dy/d+wobble*dx/d,action:!!(threat.item&&threat.distance<8.5),dash:d>20&&now>=p.dashReadyAt,updatedAt:now};}
function updateResonance(g,p,now){for(const shrine of g.resonances){if(shrine.complete||Math.hypot(shrine.x-p.x,shrine.y-p.y)>7)continue;if(!shrine.firstPlayer||now>shrine.expiresAt){shrine.firstPlayer=p.id;shrine.progress=1;shrine.expiresAt=now+2300;event(g,p.name.toUpperCase()+' SET '+shrine.label+' · PARTNER PULSE NOW',now);return;}const solo=Object.keys(g.players).length===1;if(shrine.firstPlayer===p.id&&!solo)return;const partner=g.players[shrine.firstPlayer];shrine.complete=true;shrine.progress=2;shrine.expiresAt=0;g.resonancesCompleted++;g.charge=clamp(g.charge+7,0,g.goal);Object.values(g.players).forEach(player=>player.hp=Math.min(player.maxHp,player.hp+12));g.enemies.forEach(enemy=>enemy.stunnedUntil=Math.max(enemy.stunnedUntil,now+2200));p.stats.combos++;if(partner)partner.stats.combos++;g.effects.push({id:'e'+g.nextId++,kind:'resonance',x:shrine.x,y:shrine.y,color:shrine.color,bornAt:now});event(g,(partner?partner.name.toUpperCase()+' + ':'')+p.name.toUpperCase()+' COMBO · '+shrine.label+' RESONATES',now);return;}}
function pulse(g,p,now){if(now<p.pulseReadyAt||p.down)return;p.pulseReadyAt=now+1650;p.stats.pulses++;let hits=0;for(const enemy of g.enemies){if(Math.hypot(enemy.x-p.x,enemy.y-p.y)>9)continue;enemy.hp--;enemy.stunnedUntil=now+1500;enemy.hitAt=now;hits++;p.stats.stuns++;}g.effects.push({id:'e'+g.nextId++,kind:'pulse',x:p.x,y:p.y,color:p.color,bornAt:now});updateResonance(g,p,now);if(hits)event(g,p.name.toUpperCase()+' PULSED '+hits+' GLOOM',now);}
function movePlayer(g,p,input,dt,now){if(p.down)return;let x=input.moveX,y=input.moveY,l=Math.hypot(x,y);if(input.dash&&now>=p.dashReadyAt){p.dashUntil=now+240;p.dashReadyAt=now+3800;g.effects.push({id:'e'+g.nextId++,kind:'dash',x:p.x,y:p.y,color:p.color,bornAt:now});}const speed=(now<p.dashUntil?11.8:5.4)*(1-p.carried.length*.08);if(l>.04){p.x=clamp(p.x+x/l*speed*dt,3,97);p.y=clamp(p.y+y/l*speed*dt,3,61);}if(input.action)pulse(g,p,now);}
function collectAndDeposit(g,p,now){if(p.down)return;for(let i=g.shards.length-1;i>=0&&p.carried.length<3;i--){const s=g.shards[i];if(Math.hypot(s.x-p.x,s.y-p.y)>2.2)continue;p.carried.push(s.color);p.stats.colors[s.color]++;g.shards.splice(i,1);g.effects.push({id:'e'+g.nextId++,kind:'collect',x:p.x,y:p.y,color:s.color,bornAt:now});}
  if(!p.carried.length||Math.hypot(p.x-50,p.y-32)>6.4)return;const amount=p.carried.length*6+(p.carried.length===3?3:0);g.charge=clamp(g.charge+amount,0,g.goal);p.stats.deposited+=p.carried.length;event(g,p.name.toUpperCase()+' RETURNED '+p.carried.length+' LIGHT · AURORA '+Math.round(g.charge/g.goal*100)+'%',now);p.carried=[];g.effects.push({id:'e'+g.nextId++,kind:'deposit',x:50,y:32,color:p.color,bornAt:now});}
function damage(g,p,amount,now){if(p.down||now<p.invulnerableUntil)return;p.hp=Math.max(0,p.hp-amount);p.invulnerableUntil=now+700;if(p.hp)return;p.down=true;p.downedAt=now;p.revive=0;p.stats.downs++;event(g,p.name.toUpperCase()+' FELL · STAY CLOSE TO RELIGHT THEM',now);}
function revive(g,dt,now){const all=Object.values(g.players),downed=all.filter(x=>x.down);for(const fallen of downed){const helpers=all.filter(x=>!x.down&&Math.hypot(x.x-fallen.x,x.y-fallen.y)<4.4);if(helpers.length){fallen.revive+=dt*helpers.length/1.8;if(fallen.revive>=1){fallen.down=false;fallen.hp=55;fallen.revive=0;fallen.invulnerableUntil=now+1800;helpers[0].stats.revives++;event(g,helpers[0].name.toUpperCase()+' RELIT '+fallen.name.toUpperCase(),now);}}else fallen.revive=Math.max(0,fallen.revive-dt*.2);}
  if(all.length&&all.every(x=>x.down)&&now-Math.min.apply(null,all.map(x=>x.downedAt))>1800){g.charge=Math.max(0,g.charge-12);all.forEach((p,i)=>{const a=Math.PI*2*i/all.length-Math.PI/2;p.x=50+Math.cos(a)*9;p.y=32+Math.sin(a)*9;p.hp=70;p.down=false;p.revive=0;p.invulnerableUntil=now+2200;});event(g,'THE CORE SPENT 12% LIGHT TO RELIGHT THE PARTY',now);}}
function updateDuets(g,dt,now){const active=Object.values(g.players).filter(p=>!p.down);for(const duet of g.duets){if(duet.complete)continue;const occupants=duet.pads.map(pad=>{const found=nearest(active,pad);return found.item&&found.distance<3.4?found.item:null;});duet.occupants=occupants.map(p=>p&&p.id||null);const linked=occupants[0]&&occupants[1]&&occupants[0].id!==occupants[1].id;if(!linked){duet.progress=Math.max(0,duet.progress-dt*.22);continue;}duet.progress=clamp(duet.progress+dt/2.2,0,1);if(duet.progress<1)continue;duet.complete=true;g.duetsCompleted++;g.charge=clamp(g.charge+8,0,g.goal);active.forEach(p=>p.hp=Math.min(p.maxHp,p.hp+20));g.enemies.forEach(enemy=>enemy.stunnedUntil=Math.max(enemy.stunnedUntil,now+2400));const x=(duet.pads[0].x+duet.pads[1].x)/2,y=(duet.pads[0].y+duet.pads[1].y)/2;g.effects.push({id:'e'+g.nextId++,kind:'duet',x,y,color:duet.color,bornAt:now});event(g,duet.label+' COMPLETE · PARTY HEALED · GLOOM STUNNED',now);}}
function updateEnemies(g,dt,now){const players=Object.values(g.players);for(const enemy of g.enemies){if(enemy.hp<=0||enemy.stunnedUntil>now)continue;const carriers=players.filter(p=>!p.down&&p.carried.length),choice=nearest(carriers.length?carriers:[{x:50,y:32,core:true}],enemy).item,dx=choice.x-enemy.x,dy=choice.y-enemy.y,d=length(dx,dy);enemy.x+=dx/d*enemy.speed*dt;enemy.y+=dy/d*enemy.speed*dt;if(d<1.6){if(choice.core){g.charge=Math.max(0,g.charge-2);enemy.hp=0;event(g,'GLOOM DRAINED THE AURORA · '+Math.round(g.charge/g.goal*100)+'%',now);}else{damage(g,choice,18,now);enemy.stunnedUntil=now+900;}}}g.enemies=g.enemies.filter(x=>x.hp>0);}
function achievements(g,won){const players=Object.values(g.players),teamColors={cyan:0,violet:0,gold:0};players.forEach(p=>COLORS.forEach(c=>teamColors[c]+=p.stats.colors[c]));const out=[];if(won)out.push({id:'first-light',title:'First Light',detail:'Wake the aurora.'});if(won&&players.length===1)out.push({id:'solo-spark',title:'Solo Spark',detail:'Wake Lumenwake alone.'});if(won&&players.length===4)out.push({id:'full-constellation',title:'Full Constellation',detail:'Win with four visible seats.'});if(won&&players.every(p=>p.stats.downs===0))out.push({id:'unbroken-orbit',title:'Unbroken Orbit',detail:'Win without anyone falling.'});if(won&&COLORS.every(c=>teamColors[c]>0))out.push({id:'three-colors-one-dawn',title:'Three Colors, One Dawn',detail:'Return cyan, violet and gold light.'});if(won&&g.duetsCompleted===g.duets.length)out.push({id:'woven-together',title:'Woven Together',detail:'Complete both optional Aurora Duets and wake the aurora.'});if(won&&g.resonancesCompleted===g.resonances.length)out.push({id:'full-chord',title:'Full Chord',detail:'Complete every partner Pulse combo in one route.'});if(won&&g.endsAt-g.now>60000)out.push({id:'early-dawn',title:'Early Dawn',detail:'Win with more than one minute left.'});if(players.reduce((n,p)=>n+p.stats.stuns,0)>=25)out.push({id:'pulse-artist',title:'Pulse Artist',detail:'Stun 25 gloom in one run.'});return out;}
function finish(g,won,now){g.phase=won?'won':'lost';g.now=now;const list=achievements(g,won);g.result={won,map:{id:g.map.id,name:g.map.name},charge:g.charge,duetsCompleted:g.duetsCompleted,resonancesCompleted:g.resonancesCompleted,durationMs:Math.max(0,now-g.startedAt),players:Object.values(g.players).map(p=>({id:p.id,name:p.name,kind:p.kind,stats:p.stats})),achievements:list};event(g,won?'LUMENWAKE · THE AURORA IS AWAKE':'ECLIPSE · THE LIGHT WILL TRY AGAIN',now);}
function step(g,rawInputs,dt,now){now=Number(now)||Date.now();dt=clamp(Number(dt)||0,0,.08);g.now=now;if(g.phase==='countdown'&&now>=g.startAt){g.phase='running';g.startedAt=now;g.endsAt=now+g.durationMs;event(g,'LUMENWAKE BEGINS · RETURN 100% LIGHT',now);}if(g.phase!=='running'){g.effects=g.effects.filter(e=>now-e.bornAt<900);return g;}
  g.wave=1+Math.floor((now-g.startedAt)/35000);const partySize=Object.keys(g.players).length;if(now>=g.nextShardAt&&g.shards.length<12){spawnShard(g,now);g.nextShardAt=now+1100+random(g)*1000;}if(now>=g.nextEnemyAt&&g.enemies.length<5+Math.floor(partySize/2)){spawnGloom(g,now);g.nextEnemyAt=now+Math.max(1400,(3100-g.wave*85)*(g.map.enemySpawnScale||1));}for(const shrine of g.resonances){if(!shrine.complete&&shrine.firstPlayer&&now>shrine.expiresAt){shrine.firstPlayer=null;shrine.progress=0;shrine.expiresAt=0;}}
  for(const p of Object.values(g.players)){let input=p.kind==='ai'?aiInput(g,p,now):inputShape(rawInputs&&rawInputs[p.id]);if(p.kind!=='ai'&&now-input.updatedAt>700)input=inputShape({});movePlayer(g,p,input,dt,now);collectAndDeposit(g,p,now);}revive(g,dt,now);updateDuets(g,dt,now);updateEnemies(g,dt,now);g.effects=g.effects.filter(e=>now-e.bornAt<900);if(g.charge>=g.goal)finish(g,true,now);else if(now>=g.endsAt)finish(g,false,now);return g;}
function publicState(g){return JSON.parse(JSON.stringify(g));}
function controllerState(g,playerId){const p=g.players[playerId];return{schema:'axm.lumenwake-controller-state/v1',gameId:g.gameId,version:g.version,phase:g.phase,now:g.now,startAt:g.startAt,endsAt:g.endsAt,durationMs:g.durationMs,wave:g.wave,charge:g.charge,goal:g.goal,event:g.event,eventAt:g.eventAt,map:{id:g.map.id,name:g.map.name,description:g.map.description},availableMaps:g.availableMaps,duetsCompleted:g.duetsCompleted,duetCount:g.duets.length,resonancesCompleted:g.resonancesCompleted,resonanceCount:g.resonances.length,resonances:g.resonances.map(shrine=>({id:shrine.id,label:shrine.label,complete:shrine.complete,firstPlayer:shrine.firstPlayer,expiresAt:shrine.expiresAt})),player:p?JSON.parse(JSON.stringify(p)):null,result:g.result};}
module.exports={COLORS,MAPS,create,start,inputShape,step,publicState,controllerState,achievements,mapDefinition};
