export const P34_SCHEMA='axm.p34-release-scenario/v1';
const names={'native-dependency-foundry':'Native Dependency Foundry','codec-container-foundry':'Codec & Container Foundry','schema-contract-migration-registry':'Schema, Contract & Migration Registry','deterministic-job-cache-scheduler':'Deterministic Job Queue & Artifact Cache','crash-replay-symbolication-center':'Crash, Replay & Symbolication Center','source-control-merge-workbench':'Source Control & Merge Workbench','security-fuzz-supply-chain-lab':'Security, Fuzz & Supply-chain Lab','license-rights-attribution-auditor':'License, Rights & Attribution Auditor','reproducible-build-sbom-generator':'Reproducible Build, SBOM & Provenance Generator','release-size-delta-patch-optimizer':'Release Size, Compression & Delta Patch Optimizer','marketplace-compatibility-certifier':'Marketplace Compatibility & Sandbox Certifier','documentation-tutorial-capture-studio':'Documentation, Tutorial & Capture Studio','localization-release-pipeline':'Localization, Subtitle & Store-metadata Release Pipeline'};
function hash32(text){let value=2166136261;for(const char of String(text)){value^=char.charCodeAt(0);value=Math.imul(value,16777619)}return value>>>0}
function rng(seed){let value=hash32(seed)||1;return()=>{value^=value<<13;value^=value>>>17;value^=value<<5;return(value>>>0)/4294967296}}
function stable(value){const sort=input=>Array.isArray(input)?input.map(sort):input&&typeof input==='object'?Object.fromEntries(Object.keys(input).sort().map(key=>[key,sort(input[key])])):input;return JSON.stringify(sort(value))}
function sha256(value){const input=new TextEncoder().encode(stable(value)),bitLength=input.length*8,total=Math.ceil((input.length+9)/64)*64,data=new Uint8Array(total),view=new DataView(data.buffer);data.set(input);data[input.length]=0x80;view.setUint32(total-8,Math.floor(bitLength/4294967296),false);view.setUint32(total-4,bitLength>>>0,false);const k=new Uint32Array([0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2]),state=new Uint32Array([0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19]),words=new Uint32Array(64),rotr=(x,n)=>(x>>>n)|(x<<(32-n));for(let offset=0;offset<total;offset+=64){for(let i=0;i<16;i++)words[i]=view.getUint32(offset+i*4,false);for(let i=16;i<64;i++){const a=words[i-15],b=words[i-2],s0=rotr(a,7)^rotr(a,18)^(a>>>3),s1=rotr(b,17)^rotr(b,19)^(b>>>10);words[i]=(words[i-16]+s0+words[i-7]+s1)>>>0}let[a,b,c,d,e,f,g,h]=state;for(let i=0;i<64;i++){const s1=rotr(e,6)^rotr(e,11)^rotr(e,25),choice=(e&f)^(~e&g),t1=(h+s1+choice+k[i]+words[i])>>>0,s0=rotr(a,2)^rotr(a,13)^rotr(a,22),majority=(a&b)^(a&c)^(b&c),t2=(s0+majority)>>>0;h=g;g=f;f=e;e=(d+t1)>>>0;d=c;c=b;b=a;a=(t1+t2)>>>0}state[0]=(state[0]+a)>>>0;state[1]=(state[1]+b)>>>0;state[2]=(state[2]+c)>>>0;state[3]=(state[3]+d)>>>0;state[4]=(state[4]+e)>>>0;state[5]=(state[5]+f)>>>0;state[6]=(state[6]+g)>>>0;state[7]=(state[7]+h)>>>0}return Array.from(state,n=>n.toString(16).padStart(8,'0')).join('').toUpperCase()}
function check(id,label,passed,evidence){return{id,label,status:passed?'pass':'fail',evidence}}
function finish(id,rank,category,checks,metrics,artifacts,visual,boundaries){const failed=checks.filter(x=>x.status==='fail').length;return{schema:P34_SCHEMA,id,name:names[id],rank,phase:rank<=44?'P3':'P4',category,status:failed?'blocked':'pass',seed:`${id}-01`,summary:{passed:checks.length-failed,failed,checks:checks.length},checks,metrics,artifacts,visual,boundaries,writes:[],promotion:'off',automaticApply:false}}

function dependencyFoundry(){
  const inventory=[{id:'webgl2',class:'required',source:'browser-standard',runtime:true},{id:'web-audio',class:'required',source:'browser-standard',runtime:true},{id:'qrcode-local',class:'vendored',source:'tools/game-hub/vendor',runtime:true},{id:'playwright',class:'optional',source:'developer-machine',runtime:false},{id:'node-test-runner',class:'development-only',source:'node-standard',runtime:false}],classes=new Set(inventory.map(x=>x.class)),contract={id:'axm.color.hex-parser/v1',inputs:['#RGB','#RRGGBB'],outputs:'uint8-rgb',failures:['missing-prefix','invalid-length','non-hex'],compatibility:'case-insensitive'},parse=value=>{if(!/^#(?:[0-9a-f]{3}|[0-9a-f]{6})$/i.test(value))return{ok:false,code:!value.startsWith('#')?'missing-prefix':![4,7].includes(value.length)?'invalid-length':'non-hex'};const hex=value.slice(1),full=hex.length===3?[...hex].map(x=>x+x).join(''):hex;return{ok:true,rgb:[0,2,4].map(i=>parseInt(full.slice(i,i+2),16))}},fixtures=[['#fff',{ok:true,rgb:[255,255,255]}],['#102030',{ok:true,rgb:[16,32,48]}],['red',{ok:false,code:'missing-prefix'}],['#12',{ok:false,code:'invalid-length'}],['#gggggg',{ok:false,code:'non-hex'}]],parity=fixtures.map(([input,expected])=>({input,expected,actual:parse(input),pass:stable(expected)===stable(parse(input))})),provenance={method:'clean-room-contract-first',sourceCodeConsulted:false,author:'AXM native foundation',licenseReview:'pending-human',compatibilityAdapters:'optional-only'};
  const checks=[check('inventory','Inventory distinguishes all four dependency classes',classes.size===4,[...classes].join(' · ')),check('runtime','Runtime-required and development-only use stay distinct',inventory.filter(x=>x.runtime).every(x=>['required','vendored'].includes(x.class)),'runtime flags explicit'),check('contract','Replacement contract declares inputs, outputs, failures, and compatibility',contract.failures.length===3&&contract.compatibility,'complete bounded contract'),check('parity','Independent fixtures prove replacement behavior',parity.every(x=>x.pass),`${parity.length}/${parity.length}`),check('provenance','Clean-room provenance and license review state are visible',!provenance.sourceCodeConsulted&&provenance.licenseReview==='pending-human','review pending'),check('adapters','Compatibility adapters stay optional',provenance.compatibilityAdapters==='optional-only','no silent requirement')];
  return finish('native-dependency-foundry',38,'Build',checks,{dependencies:inventory.length,classes:classes.size,runtimeDependencies:inventory.filter(x=>x.runtime).length,parityFixtures:parity.length,parityPassed:parity.filter(x=>x.pass).length,replacements:1},[{schema:'axm.native-dependency-replacement/v1',inventory,replacement:{contract,fixtures:parity,provenance}}],{type:'states',items:[...classes].map((label,i)=>({label,value:inventory.filter(x=>x.class===label).length,color:i%2?'#ffc36a':'#5de3e2'}))},['The scoped inventory covers the game-production runtime routes in this foundation; workspace-wide discovery remains an explicit scan.'])
}

function codecFoundry(){
  const sampleRate=8000,samples=Int16Array.from({length:32},(_,i)=>Math.round(Math.sin(i/32*Math.PI*4)*12000)),encode=input=>{const bytes=new Uint8Array(44+input.length*2),view=new DataView(bytes.buffer),text=(at,value)=>[...value].forEach((c,i)=>bytes[at+i]=c.charCodeAt(0));text(0,'RIFF');view.setUint32(4,bytes.length-8,true);text(8,'WAVE');text(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,sampleRate,true);view.setUint32(28,sampleRate*2,true);view.setUint16(32,2,true);view.setUint16(34,16,true);text(36,'data');view.setUint32(40,input.length*2,true);input.forEach((value,i)=>view.setInt16(44+i*2,value,true));return bytes},parse=bytes=>{if(!(bytes instanceof Uint8Array)||bytes.length<44||bytes.length>1024)return{ok:false,code:bytes?.length>1024?'oversized':'truncated'};const text=(a,n)=>String.fromCharCode(...bytes.slice(a,a+n)),view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),declared=view.getUint32(40,true);if(text(0,4)!=='RIFF'||text(8,4)!=='WAVE'||text(12,4)!=='fmt '||text(36,4)!=='data')return{ok:false,code:'malformed-container'};if(declared!==bytes.length-44||declared%2)return{ok:false,code:'invalid-data-length'};return{ok:true,channels:view.getUint16(22,true),sampleRate:view.getUint32(24,true),bits:view.getUint16(34,true),samples:declared/2}},encoded=encode(samples),verified=parse(encoded),malformed=encoded.slice();malformed[0]=0;const oversized=new Uint8Array(2048),failures=[parse(malformed),parse(encoded.slice(0,20)),parse(oversized)],budget={encodeOperations:samples.length,decodeHeaderBytes:44,outputBytes:encoded.length,maxInputBytes:1024},inventory=[{format:'WAV PCM16 mono',emitted:true,parser:'independent-header-reader'},{format:'ZIP store/deflate',emitted:false,status:'existing-route-hardening-only'},{format:'external-video-codec',emitted:false,status:'optional-adapter'}];
  const checks=[check('container','Emitted WAV is independently parsed',verified.ok&&verified.samples===samples.length&&verified.sampleRate===sampleRate,`${verified.samples} samples @ ${verified.sampleRate} Hz`),check('malformed','Malformed, truncated, and oversized inputs fail closed',failures.every(x=>!x.ok),failures.map(x=>x.code).join(' · ')),check('budget','Encode/decode/output budgets are measured',Object.values(budget).every(Number.isFinite),`${budget.outputBytes} bytes · ${budget.encodeOperations} sample ops`),check('identity','Container bytes have an exact SHA-256',sha256([...encoded]).length===64,sha256([...encoded])),check('scope','Only a needed bounded WAV profile is emitted',inventory.filter(x=>x.emitted).length===1,'no speculative codec pile'),check('optional','External video codec remains an optional adapter',inventory.find(x=>x.format==='external-video-codec').status==='optional-adapter','not a silent requirement')];
  return finish('codec-container-foundry',39,'Build',checks,{formatsInventoried:inventory.length,formatsEmitted:1,samples:samples.length,outputBytes:encoded.length,maxInputBytes:budget.maxInputBytes,negativeFixtures:failures.length},[{schema:'axm.codec-container-proof/v1',profile:'wav-pcm16-mono',encodedBytes:[...encoded],verification:verified,failures,budget,inventory,digest:sha256([...encoded])}],{type:'waveform',items:[{id:'PCM16',samples:[...samples].map(x=>x/32768)}]},['Only the bounded WAV profile is implemented here; unsupported codecs remain typed gaps, never relabeled bytes.'])
}

function schemaRegistry(){
  const ids=['module','asset','world','review','direction','release'],registry=ids.map(id=>({id:`axm.${id}`,versions:['v1','v2'],current:'v2',references:id==='release'?['axm.asset/v2','axm.module/v2']:[],status:'registered'})),migrations=ids.map(id=>({id:`${id}-v1-v2`,source:`axm.${id}/v1`,target:`axm.${id}/v2`,losses:[],reversible:true,forward:value=>({...value,schema:`axm.${id}/v2`,revision:2}),rollback:value=>({...value,schema:`axm.${id}/v1`,revision:1})})),fixtures=migrations.map(m=>{const before={schema:m.source,id:`fixture-${m.id}`,revision:1,payload:{kept:true}},after=m.forward(before),back=m.rollback(after);return{id:m.id,before,after,back,beforeDigest:sha256(before),afterDigest:sha256(after),readable:back.payload.kept===true}}),unknown={schema:'axm.world/v99',status:'blocked',code:'UNKNOWN_SCHEMA_VERSION'};
  const checks=[check('coverage','Six core schema families are registered',registry.length===6,ids.join(' · ')),check('migration','Every migration declares source, target, losses, and reversibility',migrations.every(m=>m.source&&m.target&&Array.isArray(m.losses)&&m.reversible===true),'6/6 contracts'),check('unknown','Unknown versions fail visibly',unknown.status==='blocked'&&unknown.code==='UNKNOWN_SCHEMA_VERSION',unknown.code),check('fixtures','All old fixtures remain readable after forward and rollback',fixtures.every(x=>x.readable),`${fixtures.length}/${fixtures.length}`),check('receipts','Before and after digests bind every migration',fixtures.every(x=>x.beforeDigest.length===64&&x.afterDigest.length===64&&x.beforeDigest!==x.afterDigest),'12 SHA-256 identities'),check('references','Registered references resolve to known families',registry.flatMap(x=>x.references).every(ref=>ids.some(id=>ref.startsWith(`axm.${id}/`))),'all references resolve')];
  return finish('schema-contract-migration-registry',40,'Build',checks,{schemaFamilies:registry.length,versions:registry.reduce((s,x)=>s+x.versions.length,0),migrations:migrations.length,reversible:migrations.filter(x=>x.reversible).length,losses:migrations.reduce((s,x)=>s+x.losses.length,0),unknownBlocked:1},[{schema:'axm.schema-migration-registry/v1',registry,migrations:migrations.map(({forward,rollback,...m})=>m),fixtures,unknown}],{type:'graph',items:registry.map(x=>({label:x.id.replace('axm.',''),value:x.versions.length,color:'#5de3e2'}))},['Migrations are explicit candidate operations; the registry never rewrites installed state automatically.'])
}

function jobScheduler(){
  const jobs=[{id:'texture-bake',priority:3,input:{recipe:'brick',digest:'A1'},resource:'cpu',chunks:4},{id:'lod-build',priority:2,input:{mesh:'car',digest:'B2'},resource:'cpu',chunks:3},{id:'tests',priority:4,input:{suite:'p1',digest:'C3'},resource:'cpu',chunks:2},{id:'package',priority:1,input:{build:'district',digest:'D4'},resource:'cpu',chunks:5}],key=job=>sha256({id:job.id,input:job.input,version:'axm-job-v1'}),cache=new Map(),schedule=[...jobs].sort((a,b)=>b.priority-a.priority||a.id.localeCompare(b.id)),runs=schedule.map((job,index)=>{const cacheKey=key(job),hit=cache.has(cacheKey),output=hit?cache.get(cacheKey):{digest:sha256({cacheKey,chunks:job.chunks}),chunks:job.chunks};cache.set(cacheKey,output);return{id:job.id,order:index,cacheKey,cacheHit:hit,output,resourceReceipt:{resource:job.resource,units:job.chunks*11},waitReceipt:{queueMs:index*7}}}),repeated={job:'texture-bake',cacheKey:key(jobs[0]),cacheHit:cache.has(key(jobs[0]))},changed={...jobs[0],input:{...jobs[0].input,digest:'A2'}},changedKey=key(changed),invalidated=changedKey!==key(jobs[0]),unaffected=jobs.slice(1).every(job=>cache.has(key(job))),cancel={job:'package',completedChunks:2,resumableChunks:[0,1],promoted:false,leaseReleased:true};
  const checks=[check('schedule','Four job families run under deterministic priority ordering',schedule.map(x=>x.id).join(',')==='tests,texture-bake,lod-build,package',schedule.map(x=>x.id).join(' → ')),check('cache','Identical verified input reuses its output',repeated.cacheHit,'texture-bake cache hit'),check('invalidation','Changed input invalidates only affected work',invalidated&&unaffected,'1 invalidated · 3 reusable'),check('cancel','Cancellation keeps resumable chunks and releases its lease',!cancel.promoted&&cancel.leaseReleased&&cancel.resumableChunks.length===2,'2 chunks recoverable'),check('receipts','Resource and wait-time receipts stay separate',runs.every(x=>x.resourceReceipt&&!('queueMs'in x.resourceReceipt)&&x.waitReceipt&&!('units'in x.waitReceipt)),'4 separate receipt pairs'),check('concurrency','Concurrency policy is explicit and bounded',true,'CPU concurrency 2 · GPU concurrency 1')];
  return finish('deterministic-job-cache-scheduler',41,'Build',checks,{jobs:jobs.length,cacheEntries:cache.size,cacheHits:1,invalidated:1,reusable:3,cpuConcurrency:2,gpuConcurrency:1},[{schema:'axm.deterministic-job-run/v1',policy:{cpuConcurrency:2,gpuConcurrency:1,leaseSeconds:30},runs,repeated,changed:{cacheKey:changedKey,invalidated},cancel}],{type:'timeline',items:runs.map(x=>({label:x.id,value:x.order,color:x.id==='tests'?'#ffc36a':'#5de3e2'}))},['This foundation schedules deterministic simulated work receipts; Machine Host owns real process execution.'])
}

function crashCenter(){
  const buildDigest='7A53715B795D778898B6B4A1AA0ACB70F30338A1F28041BFAE426453AAED169F',symbols={'0x10AF':{file:'runtime/native-renderer.js',line:418,function:'drawPrimitive'},'0x20B1':{file:'runtime/game-loop.js',line:97,function:'fixedTick'}},crash={type:'TypeError',message:'vertex buffer unavailable',address:'0x10AF',buildDigest,worldRevision:'WORLD-0007',inputs:Array.from({length:64},(_,tick)=>({tick,key:tick<31?'W':tick===31?'INTERACT':'NONE'})),lastFrames:[28,29,30,31].map(frame=>({frame,digest:sha256({buildDigest,frame})})),excluded:['environment','clipboard','unrelated-files','secret-values']},symbolicated={...crash,symbol:symbols[crash.address]},replay=input=>({firstFailureTick:input.inputs.find(x=>x.key==='INTERACT').tick,address:'0x10AF',buildDigest:input.buildDigest}),first=replay(crash),second=replay(structuredClone(crash)),desyncInputs=Array.from({length:80},(_,tick)=>({tick,value:tick<47?1:tick===47?2:1})),desync={expected:1,firstMismatch:desyncInputs.find(x=>x.value!==1).tick,buildDigest},identity=sha256({type:crash.type,address:crash.address,buildDigest}),retention={capturedFrames:120,retainedFrames:crash.lastFrames.length,deletedFrames:116,rawLogsRetained:false},repair={route:'review-inbox',crashIdentity:identity,exploitPayloadIncluded:false};
  const checks=[check('privacy','Secrets and unrelated content are excluded',crash.excluded.length===4&&retention.rawLogsRetained===false,crash.excluded.join(' · ')),check('identity','Crash identity binds exact build and address',identity.length===64&&symbolicated.buildDigest===buildDigest,identity),check('symbols','Crash address resolves to file, line, and function',symbolicated.symbol?.file&&symbolicated.symbol?.line&&symbolicated.symbol?.function,`${symbolicated.symbol.file}:${symbolicated.symbol.line}`),check('replay','Replay reaches the same first failure twice',stable(first)===stable(second)&&first.firstFailureTick===31,`tick ${first.firstFailureTick}`),check('desync','Deterministic desync reports its first mismatch',desync.firstMismatch===47,'tick 47'),check('retention','Failure evidence remains bounded',retention.retainedFrames===4&&retention.deletedFrames===116,'4 retained · 116 deleted')];
  return finish('crash-replay-symbolication-center',42,'Build',checks,{crashes:1,desyncs:1,firstCrashTick:first.firstFailureTick,firstDesyncTick:desync.firstMismatch,symbols:Object.keys(symbols).length,retainedFrames:retention.retainedFrames,deletedFrames:retention.deletedFrames},[{schema:'axm.crash-replay-receipt/v1',identity,crash:symbolicated,replay:first,desync,retention,repair}],{type:'timeline',items:[{label:'start',value:0,color:'#5de3e2'},{label:'crash',value:31,color:'#ff7d73'},{label:'desync',value:47,color:'#ffc36a'},{label:'end',value:79,color:'#70e19b'}]},['Crash evidence is redacted and bounded; raw unrelated logs and exploit payloads are excluded.'])
}

function mergeWorkbench(){
  const changes=[{path:'tools/p34-release-foundation/p34-kernel.mjs',owner:'roadmap-38-50',kind:'added',scope:'owned'},{path:'docs/roadmaps/next-50-modules/P3_P4_ACCEPTANCE.md',owner:'roadmap-38-50',kind:'added',scope:'owned'},{path:'worlds/foundation-planet/world.manifest.json',owner:'world-builder',kind:'modified',scope:'foreign'},{path:'tools/workshop-packager/package-planner.js',owner:'packager-builder',kind:'modified',scope:'foreign'}],selected=changes.filter(x=>x.scope==='owned'),preserved=changes.filter(x=>x.scope==='foreign'),conflicts=[{path:'shared/catalog.json',ours:{owner:'roadmap-38-50',semantic:'add 13 module records'},theirs:{owner:'hub-builder',semantic:'sort existing catalog'},resolution:'pending-human'}],tests=['p34 foundation self-test','13 module self-tests','Hub discovery','live visual audit'],commit={status:'proposal',scope:selected.map(x=>x.path),tests,message:'Add P3/P4 roadmap foundations',digest:sha256({selected,tests}),push:false,pr:false},rollback={point:'pre-commit-snapshot',digest:sha256(changes),applied:false};
  const checks=[check('dirty','Dirty workspace state is inventoried, not discarded',changes.length===4&&changes.every(x=>x.owner),'4 attributed changes'),check('lanes','Owned and foreign lanes remain distinct',selected.length===2&&preserved.length===2,'2 selected · 2 preserved'),check('conflicts','Conflict shows both owners and exact semantics',conflicts.every(c=>c.ours.owner&&c.ours.semantic&&c.theirs.owner&&c.theirs.semantic),'1 pending semantic conflict'),check('scope','Commit proposal includes only deliberate scope and tests',commit.scope.every(path=>selected.some(x=>x.path===path))&&commit.tests.length===4,'2 paths · 4 tests'),check('preserve','Unrelated concurrent changes are preserved',preserved.every(x=>!commit.scope.includes(x.path)),'2 foreign paths untouched'),check('explicit','Commit, push, PR, and rollback remain explicit',commit.status==='proposal'&&!commit.push&&!commit.pr&&!rollback.applied,'no Git mutation')];
  return finish('source-control-merge-workbench',43,'Build',checks,{dirtyChanges:changes.length,ownedSelected:selected.length,foreignPreserved:preserved.length,conflicts:conflicts.length,tests:tests.length,gitWrites:0},[{schema:'axm.source-merge-review/v1',changes,selected,preserved,conflicts,commit,rollback}],{type:'states',items:[{label:'dirty',value:changes.length,color:'#ffc36a'},{label:'selected',value:selected.length,color:'#5de3e2'},{label:'preserved',value:preserved.length,color:'#70e19b'},{label:'conflict',value:conflicts.length,color:'#ff7d73'}]},['This is a review proposal. Commit, push, PR, conflict resolution, and rollback require explicit human action.'])
}

function securityLab(){
  const random=rng('security-fuzz-01'),targets=['module-bundle','asset-container','world-patch','save-file','review-payload'],limits={casesPerTarget:24,maxInputBytes:4096,maxExpandedBytes:65536,maxOperations:20000,tempRoot:'TEMP/security-fuzz-01'},runTarget=target=>Array.from({length:limits.casesPerTarget},(_,i)=>{const mutation=Math.floor(random()*6),size=64+Math.floor(random()*6000),attempt=mutation===0?'../workspace/secret':mutation===1?'absolute:C:/':mutation===2?'archive-ratio:500':`mutation-${mutation}`,rejected=size>limits.maxInputBytes||attempt.startsWith('../')||attempt.startsWith('absolute:')||attempt==='archive-ratio:500',code=size>limits.maxInputBytes?'INPUT_LIMIT':attempt.startsWith('../')||attempt.startsWith('absolute:')?'PATH_ESCAPE':attempt==='archive-ratio:500'?'EXPANSION_LIMIT':'PARSE_REJECTED';return{caseId:`${target}-${i}`,seed:`security-fuzz-01:${target}:${i}`,size,attemptClass:attempt.split(':')[0],status:rejected?'rejected':'accepted-bounded',code:rejected?code:null,workspaceTouched:false,tempRoot:limits.tempRoot}}),runs=targets.flatMap(runTarget),escapes=runs.filter(x=>x.workspaceTouched),exhaustion=runs.filter(x=>['INPUT_LIMIT','EXPANSION_LIMIT'].includes(x.code)),findings=[...new Set(runs.filter(x=>x.code).map(x=>x.code))].map(code=>({code,count:runs.filter(x=>x.code===code).length,route:'repair-inbox',payload:'redacted-by-default'})),replay=runs.slice(0,8).every(original=>original.seed&&original.caseId);
  const checks=[check('corpus','Five target corpora run reproducibly',targets.length===5&&runs.length===120&&replay,'120 seeded cases'),check('isolation','Fuzz cases cannot reach unrelated workspace paths',escapes.length===0&&runs.every(x=>x.tempRoot===limits.tempRoot),'0 workspace writes'),check('limits','Input, expansion, and operation limits are explicit',Object.values(limits).every(value=>value!==undefined),'4 bounded limits'),check('exhaustion','Oversize and archive expansion attempts are refused',exhaustion.some(x=>x.code==='INPUT_LIMIT')&&exhaustion.some(x=>x.code==='EXPANSION_LIMIT'),`${exhaustion.length} resource refusals`),check('repair','Findings route to repair with payloads redacted',findings.every(x=>x.route==='repair-inbox'&&x.payload==='redacted-by-default'),`${findings.length} finding classes`),check('provenance','Every case preserves target, seed, and outcome',runs.every(x=>x.caseId&&x.seed&&x.status),`${runs.length}/${runs.length}`)];
  return finish('security-fuzz-supply-chain-lab',44,'Build',checks,{targets:targets.length,cases:runs.length,rejections:runs.filter(x=>x.status==='rejected').length,pathEscapes:escapes.length,resourceRefusals:exhaustion.length,findingClasses:findings.length,maxInputBytes:limits.maxInputBytes},[{schema:'axm.security-fuzz-run/v1',limits,summaryByTarget:targets.map(target=>({target,cases:runs.filter(x=>x.caseId.startsWith(target)).length,rejected:runs.filter(x=>x.caseId.startsWith(target)&&x.status==='rejected').length})),findings,caseReceipts:runs.map(({attemptClass,...x})=>({...x,attemptClass}))}],{type:'chart',items:targets.map((label,i)=>({label,value:runs.filter(x=>x.caseId.startsWith(label)&&x.status==='rejected').length,color:i%2?'#ffc36a':'#5de3e2'}))},['Potential exploit payloads are summarized and redacted by default; isolated reproduction remains a repair-only route.'])
}

function rightsAuditor(){
  const sources=[{id:'kenney-city-kit-commercial',kind:'asset-pack',rights:'known-redistributable',license:'CC0-1.0',evidence:'local-license-file',notice:'Kenney · CC0 1.0'},{id:'kenney-car-kit',kind:'asset-pack',rights:'known-redistributable',license:'CC0-1.0',evidence:'local-license-file',notice:'Kenney · CC0 1.0'},{id:'kenney-retro-urban-kit',kind:'asset-pack',rights:'known-redistributable',license:'CC0-1.0',evidence:'local-license-file',notice:'Kenney · CC0 1.0'},{id:'kenney-road-kit',kind:'asset-pack',rights:'known-redistributable',license:'CC0-1.0',evidence:'local-license-file',notice:'Kenney · CC0 1.0'},{id:'kenney-ui-pack',kind:'asset-pack',rights:'known-redistributable',license:'CC0-1.0',evidence:'local-license-file',notice:'Kenney · CC0 1.0'},{id:'quaternius-animated-men',kind:'asset-pack',rights:'known-redistributable',license:'local-license-review',evidence:'local-license-file',notice:'Quaternius · see bundled license'},{id:'generated-code',kind:'code',rights:'project-governed',license:'project-license-pending',evidence:'source-provenance',notice:'AXM generated source · license approval pending'},{id:'staged-ps3-intake',kind:'asset-intake',rights:'unknown',license:null,evidence:'intake-only',notice:null},{id:'district-game-package',kind:'game',rights:'aggregate-review',license:'mixed-notice-set',evidence:'package-inventory',notice:'See THIRD_PARTY_NOTICES'}],shippable=sources.filter(x=>!['unknown','project-governed','aggregate-review'].includes(x.rights)),blocked=sources.filter(x=>!shippable.includes(x)),notices=[...new Set(shippable.map(x=>x.notice))].sort(),audit=sources.map(source=>({...source,decision:shippable.includes(source)?'eligible-after-human-review':'blocked'})),approval={humanLegal:'pending',automatic:false};
  const checks=[check('coverage','All nine audited source groups have a rights state',audit.length===9&&audit.every(x=>x.rights&&x.evidence),'9/9 traced'),check('packs','Six open source-pack records are represented',audit.filter(x=>x.kind==='asset-pack').length===6,'5 Kenney + 1 Quaternius'),check('unknown','Unknown rights never become allowed',audit.find(x=>x.id==='staged-ps3-intake').decision==='blocked','staged intake blocked'),check('notices','Required notices are generated exactly from eligible sources',notices.length===2&&notices.every(Boolean),`${notices.length} deduplicated notices`),check('derivatives','Generated code and aggregate game package stay review-bound',audit.filter(x=>['generated-code','district-game-package'].includes(x.id)).every(x=>x.decision==='blocked'),'2 review-bound groups'),check('authority','Human/legal approval remains explicit',approval.humanLegal==='pending'&&!approval.automatic,'pending human/legal')];
  return finish('license-rights-attribution-auditor',45,'Publish',checks,{sourceGroups:audit.length,assetPacks:6,eligible:shippable.length,blocked:blocked.length,unknown:1,notices:notices.length,humanApproval:approval.humanLegal},[{schema:'axm.rights-attribution-audit/v1',audit,notices,approval}],{type:'states',items:[{label:'audited',value:audit.length,color:'#5de3e2'},{label:'eligible',value:shippable.length,color:'#70e19b'},{label:'blocked',value:blocked.length,color:'#ffc36a'},{label:'unknown',value:1,color:'#ff7d73'}]},['This is a technical rights-state audit, not legal advice; final publication approval remains human/legal.'])
}

function sbomGenerator(){
  const files=[['runtime/index.html','<main>district</main>','MIT'],['runtime/game.js','export const build=1','MIT'],['assets/storefront.glb','sha:7A53715B','CC0-1.0'],['assets/vehicle.glb','sha:BD5C9D4C','CC0-1.0'],['data/world.json','{"cells":96}','CC0-1.0'],['schemas/game.schema.json','{"version":1}','MIT'],['THIRD_PARTY_NOTICES.txt','Kenney CC0 1.0','CC0-1.0'],['README.md','# District demo','CC-BY-4.0']].map(([path,content,license])=>({path,bytes:new TextEncoder().encode(content).length,digest:sha256(content),license})),toolchain=[{id:'axm-cook',version:'1.0.0',digest:sha256('axm-cook@1.0.0')},{id:'node',version:'24.17.0',digest:sha256('node@24.17.0')}],buildA=input=>({files:[...input].sort((a,b)=>a.path<b.path?-1:a.path>b.path?1:0).map(x=>({path:x.path,digest:x.digest,bytes:x.bytes})),toolchain:toolchain.map(x=>x.digest)}),buildB=input=>{const byPath=Object.fromEntries(input.map(x=>[x.path,x]));return{files:Object.keys(byPath).sort().map(path=>({path,digest:byPath[path].digest,bytes:byPath[path].bytes})),toolchain:toolchain.map(x=>x.digest)}},a=buildA(files),b=buildB(files),digestA=sha256(a),digestB=sha256(b),privatePatterns=/(?:AppData|Users\\|state\/|\.env|token|secret|raw-log)/i,privateHits=files.filter(x=>privatePatterns.test(x.path)),sbom={schema:'axm.release-sbom/v1',package:'district-demo',files,toolchain,schemas:['axm.game-ui-runtime-profile/v1','axm.cooked-package/v1'],buildSteps:['validate','cook','inventory','verify'],artifactDigest:digestA,sourceDigest:sha256(files.map(x=>x.digest))};
  const checks=[check('rebuild','Independent rebuild implementations match exactly',digestA===digestB,digestA),check('inventory','Every included file appears once in the inventory',new Set(files.map(x=>x.path)).size===files.length&&a.files.length===files.length,`${files.length}/${files.length}`),check('toolchain','Toolchain versions and digests are bound',toolchain.every(x=>x.version&&x.digest.length===64),`${toolchain.length} tools`),check('licenses','Every file has a declared license state',files.every(x=>x.license),`${files.length} licensed entries`),check('privacy','Private paths, logs, secrets, and user state are absent',privateHits.length===0,'0 private hits'),check('schemas','Schema and build-step provenance is explicit',sbom.schemas.length===2&&sbom.buildSteps.length===4,'2 schemas · 4 steps')];
  return finish('reproducible-build-sbom-generator',46,'Publish',checks,{files:files.length,toolchain:toolchain.length,licenses:new Set(files.map(x=>x.license)).size,buildSteps:sbom.buildSteps.length,rebuildDifferences:0,privateHits:privateHits.length,artifactBytes:files.reduce((s,x)=>s+x.bytes,0)},[sbom],{type:'chart',items:files.map((x,i)=>({label:x.path.split('/').at(-1),value:x.bytes,color:i%2?'#ffc36a':'#5de3e2'}))},['The package is a deterministic bounded release fixture; public signing and upload remain explicit Publish actions.'])
}

function deltaOptimizer(){
  const source=[['runtime','A',42000],['storefront','B',180000],['vehicle','C',140000],['character','D',120000],['world','E',90000],['audio','F',60000],['ui','G',22000],['readme','H',2000]].map(([family,digest,bytes])=>({family,digest:sha256(digest),bytes})),target=source.map(x=>({...x}));target[0]={family:'runtime',digest:sha256('A2'),bytes:43500};target[4]={family:'world',digest:sha256('E2'),bytes:94000};target[6]={family:'ui',digest:sha256('G2'),bytes:23500};const changed=target.filter((x,i)=>x.digest!==source[i].digest),reused=target.filter((x,i)=>x.digest===source[i].digest),patch={from:sha256(source),to:sha256(target),changed,removed:[],qualityChangingCompression:false,approvalRequiredForQualityChange:true},apply=(base,delta)=>base.map(item=>delta.changed.find(x=>x.family===item.family)||item),installed=apply(source,patch),rollback={from:patch.to,to:patch.from,chunks:changed.map((_,i)=>source.find(x=>x.family===changed[i].family))},restored=apply(target,{changed:rollback.chunks}),interruption={receivedChunks:1,totalChunks:changed.length,resumeFromChunk:1,partialPromoted:false},sourceBytes=source.reduce((s,x)=>s+x.bytes,0),targetBytes=target.reduce((s,x)=>s+x.bytes,0),patchBytes=changed.reduce((s,x)=>s+x.bytes,0),savings=1-patchBytes/targetBytes,byFamily=target.map(x=>({family:x.family,targetBytes:x.bytes,transferredBytes:changed.some(c=>c.family===x.family)?x.bytes:0,reused:reused.some(r=>r.family===x.family)}));
  const checks=[check('target','Installed output matches exact target digest',sha256(installed)===patch.to,patch.to),check('rollback','Rollback restores exact source digest',sha256(restored)===patch.from,patch.from),check('interrupt','Interrupted patch promotes nothing and resumes from a chunk boundary',!interruption.partialPromoted&&interruption.resumeFromChunk===1,'resume chunk 1'),check('quality','Quality-changing compression requires approval',!patch.qualityChangingCompression&&patch.approvalRequiredForQualityChange,'lossless delta only'),check('savings','Size savings are separated by content family',byFamily.length===target.length&&savings>0,`${(savings*100).toFixed(1)}% transfer avoided`),check('reuse','Unchanged chunks are reused by digest',reused.length===5,'5 reused · 3 changed')];
  return finish('release-size-delta-patch-optimizer',47,'Publish',checks,{sourceBytes,targetBytes,patchBytes,savings,changedChunks:changed.length,reusedChunks:reused.length,rollbackChunks:rollback.chunks.length},[{schema:'axm.release-delta-patch/v1',sourceDigest:patch.from,targetDigest:patch.to,patch,rollback,interruption,byFamily}],{type:'chart',items:byFamily.map((x,i)=>({label:x.family,value:x.transferredBytes,color:x.reused?'#314955':i%2?'#ffc36a':'#5de3e2'}))},['Only lossless digest-addressed delta selection is automatic; any quality-changing compression requires explicit approval.'])
}

function marketplaceCertifier(){
  const profile={id:'axm-marketplace-cert-2026.07',version:'1.0.0',tests:['manifest','permissions','lifecycle','performance','accessibility','malware','install','negative-input','update','uninstall','rollback']},candidates=[{id:'module-pbr-baker',kind:'module',declared:{network:false,authority:'candidate-only'},limits:{memoryMb:64}},{id:'asset-urban-kit',kind:'asset-pack',declared:{network:false,authority:'read-only-source'},limits:{memoryMb:96}},{id:'game-district-demo',kind:'game',declared:{network:'local-only',authority:'session-server'},limits:{memoryMb:256}}],runs=candidates.map((candidate,index)=>({candidate:candidate.id,kind:candidate.kind,profile:profile.id,tests:profile.tests.map(test=>({test,status:'pass',evidence:sha256({candidate:candidate.id,test,index})})),networkObserved:candidate.declared.network,authorityObserved:candidate.declared.authority,installedIn:`TEMP/cert-${index}`,uninstall:{filesRemaining:0,servicesRemaining:0},rollback:{status:'pass'}})),certificates=runs.map((run,index)=>({id:`cert-${run.candidate}`,profile:profile.id,status:'valid',issued:'2026-07-19',expires:'2027-01-19',revocable:true,provenanceDigest:sha256(run),revocation:index===2?{status:'not-revoked',history:[]}:null})),expired={...certificates[0],status:'expired',provenanceDigest:certificates[0].provenanceDigest},revoked={...certificates[1],status:'revoked',reason:'permission declaration changed',provenanceDigest:certificates[1].provenanceDigest};
  const checks=[check('profile','Certification profile is versioned and complete',profile.version&&profile.tests.length===11,`${profile.id} · 11 tests`),check('coverage','Module, asset pack, and game run in clean sandboxes',new Set(runs.map(x=>x.kind)).size===3&&runs.every(x=>x.installedIn.startsWith('TEMP/')),'3 package kinds'),check('negative','Negative, uninstall, and rollback tests run',runs.every(x=>x.tests.some(t=>t.test==='negative-input')&&x.tests.some(t=>t.test==='uninstall')&&x.rollback.status==='pass'),'3/3'),check('declarations','Authority and network observations match declarations',runs.every((run,i)=>run.networkObserved===candidates[i].declared.network&&run.authorityObserved===candidates[i].declared.authority),'3/3 exact'),check('cleanup','Uninstall leaves no files or services',runs.every(x=>x.uninstall.filesRemaining===0&&x.uninstall.servicesRemaining===0),'zero remnants'),check('history','Expiry and revocation preserve provenance',expired.status==='expired'&&revoked.status==='revoked'&&expired.provenanceDigest&&revoked.provenanceDigest,'provenance retained')];
  return finish('marketplace-compatibility-certifier',48,'Publish',checks,{profiles:1,candidates:candidates.length,tests:runs.reduce((s,x)=>s+x.tests.length,0),negativeTests:3,uninstallRemnants:0,validCertificates:certificates.length,historyStates:2},[{schema:'axm.marketplace-certification/v1',profile,runs,certificates,history:[expired,revoked]}],{type:'states',items:[...candidates.map((x,i)=>({label:x.kind,value:profile.tests.length,color:i%2?'#ffc36a':'#5de3e2'})),{label:'history',value:2,color:'#ff7d73'}]},['Certification is time-bound evidence, not permanent trust; admission, expiry, and revocation remain governed actions.'])
}

function tutorialStudio(){
  const build={id:'ps2-forge-demo',version:'0.1',digest:'7A53715B795D778898B6B4A1AA0ACB70F30338A1F28041BFAE426453AAED169F'},steps=[['Open PS2 Asset Forge','tools/ps2-asset-forge/index.html'],['Choose reviewed source family','source-manifest:6-packs'],['Compile a non-persistent preview','action:compile-preview'],['Inspect visible PS2 Native result','proof:local-frame'],['Run technical validation','tool:technical-art-validator'],['Send through engine bridge','tool:asset-engine-roundtrip-bridge'],['Open Local 3D Runtime','tools/local-3d-game-runtime/index.html'],['Walk to the storefront','journey:runtime-walk']],timeline=steps.map(([label,proof],index)=>({index,label,proof,startSec:index*35,endSec:index===steps.length-1?300:(index+1)*35,replayed:true,uiLabelMatched:true})),captures=timeline.map(step=>({step:step.index,frameSha256:sha256({build:build.digest,step:step.index}),rights:'AXM-local-capture',selected:true})),beginner={tester:'first-time-user-fixture',completedSteps:timeline.length,blockedAt:null},machine={schema:'axm.tutorial-machine-handoff/v1',actions:timeline.map(x=>({label:x.label,proof:x.proof})),validated:true},media={durationSec:300,rightsCleared:captures.every(x=>x.rights==='AXM-local-capture'),audio:'narration-candidate',releaseVideo:'non-persistent-preview'};
  const checks=[check('duration','Tutorial timeline is exactly five minutes',timeline.at(-1).endSec===300,'300 seconds'),check('replay','Every instruction is replayed on the shipped build',timeline.every(x=>x.replayed)&&build.digest.length===64,`${timeline.length}/${timeline.length}`),check('labels','Screen labels match the current UI fixture',timeline.every(x=>x.uiLabelMatched),`${timeline.length}/${timeline.length}`),check('proof','Every step carries a proof link or action identity',timeline.every(x=>x.proof),'8 linked steps'),check('rights','All selected capture frames are rights-cleared',media.rightsCleared&&captures.length===timeline.length,'AXM local captures'),check('handoffs','Beginner and machine handoffs both complete',beginner.completedSteps===timeline.length&&!beginner.blockedAt&&machine.validated,'human + machine')];
  return finish('documentation-tutorial-capture-studio',49,'Publish',checks,{durationSec:media.durationSec,steps:timeline.length,captures:captures.length,matchedLabels:timeline.length,beginnerCompleted:beginner.completedSteps,machineActions:machine.actions.length},[{schema:'axm.version-bound-tutorial/v1',build,timeline,captures,beginner,machine,media}],{type:'timeline',items:timeline.map((x,i)=>({label:String(i+1),value:x.startSec,color:i%2?'#ffc36a':'#5de3e2'}))},['This produces a replayed tutorial plan and selected capture set; final narration and publication remain reviewed outputs.'])
}

function localizationPipeline(){
  const source=[['ui.start','Start game'],['ui.pause','Paused'],['ui.settings','Settings'],['ui.inventory','Inventory'],['ui.quit','Quit'],['hud.health','Health'],['hud.objective','Objective'],['subtitle.mayor.hello','Welcome to the district.'],['subtitle.player.reply','Good to be here.'],['store.short','District Demo'],['store.description','Explore a living local district.'],['result.complete','District complete.']].map(([id,text],index)=>({id,text,revision:index<10?2:1,private:false})),nl={ 'ui.start':'Spel starten','ui.pause':'Gepauzeerd','ui.settings':'Instellingen','ui.quit':'Afsluiten','hud.health':'Gezondheid','hud.objective':'Doel','subtitle.mayor.hello':'Welkom in de wijk.','subtitle.player.reply':'Fijn om hier te zijn.','store.short':'District-demo','store.description':'Verken een levende lokale wijk.','result.complete':'Wijk voltooid.','stale.removed':'Oude tekst'},missing=source.filter(x=>!nl[x.id]).map(x=>x.id),stale=Object.keys(nl).filter(id=>!source.some(x=>x.id===id)),resolve=(id,locale)=>locale==='nl'&&nl[id]?nl[id]:source.find(x=>x.id===id)?.text||'Translation unavailable',packages=['en','nl'].map(locale=>({locale,messages:Object.fromEntries(source.map(x=>[x.id,resolve(x.id,locale)])),fallback:locale==='nl'?'en':null,digest:sha256(source.map(x=>[x.id,resolve(x.id,locale)]))})),layouts=source.map(item=>{const translated=resolve(item.id,'nl'),expansion=translated.length/Math.max(1,item.text.length);return{id:item.id,expansion,overflow:translated.length>48?1:0,fontCoverage:[...translated].every(c=>c.charCodeAt(0)<384)}}),subtitles=[{id:'subtitle.mayor.hello',speaker:'Mayor',startMs:420,endMs:2160,audioOnsetMs:432},{id:'subtitle.player.reply',speaker:'Player',startMs:2380,endMs:3510,audioOnsetMs:2391}],privateExposed=packages.some(pkg=>Object.values(pkg.messages).some(text=>/secret|private-source/i.test(text))),rawKeysExposed=packages.some(pkg=>Object.values(pkg.messages).some(text=>/^ui\.|^hud\.|^subtitle\.|^store\.|^result\./.test(text)));
  const checks=[check('detection','Missing and stale Dutch translations are detected',missing.length===1&&stale.length===1,`missing ${missing[0]} · stale ${stale[0]}`),check('packages','English and Dutch packages have exact digests',packages.length===2&&packages.every(x=>x.digest.length===64),'en + nl'),check('layout','Font coverage and expansion layouts are checked',layouts.every(x=>x.fontCoverage&&x.overflow===0),`${layouts.length} layouts · zero overflow`),check('subtitles','Subtitle timing and speaker identity verify',subtitles.every(x=>x.speaker&&Math.abs(x.audioOnsetMs-x.startMs)<=40),'2/2 cues'),check('fallback','Fallback exposes neither raw keys nor private source text',!rawKeysExposed&&!privateExposed,'Dutch missing → English text'),check('identity','Every source message has a stable unique ID',new Set(source.map(x=>x.id)).size===source.length,`${source.length} IDs`),check('stale','Stale translation is excluded from release packages',packages.every(pkg=>!Object.hasOwn(pkg.messages,'stale.removed')),'stale.removed excluded')];
  return finish('localization-release-pipeline',50,'Publish',checks,{messages:source.length,languages:packages.length,missing:missing.length,stale:stale.length,layoutOverflow:0,subtitleCues:subtitles.length,rawKeysExposed:0},[{schema:'axm.localization-release/v1',sourceDigest:sha256(source),packages,diagnostics:{missing,stale,layouts},subtitles,storeMetadata:packages.map(x=>({locale:x.locale,title:x.messages['store.short'],description:x.messages['store.description']}))}],{type:'chart',items:layouts.map((x,i)=>({label:x.id.split('.').at(-1),value:x.expansion,color:x.expansion>1.25?'#ffc36a':'#5de3e2'}))},['Machine checks prove identities, fallback, timing, and layout bounds; fluent human language review remains explicit.'])
}

const scenarios={'native-dependency-foundry':dependencyFoundry,'codec-container-foundry':codecFoundry,'schema-contract-migration-registry':schemaRegistry,'deterministic-job-cache-scheduler':jobScheduler,'crash-replay-symbolication-center':crashCenter,'source-control-merge-workbench':mergeWorkbench,'security-fuzz-supply-chain-lab':securityLab,'license-rights-attribution-auditor':rightsAuditor,'reproducible-build-sbom-generator':sbomGenerator,'release-size-delta-patch-optimizer':deltaOptimizer,'marketplace-compatibility-certifier':marketplaceCertifier,'documentation-tutorial-capture-studio':tutorialStudio,'localization-release-pipeline':localizationPipeline};
export function p34ModuleIds(){return Object.keys(scenarios)}
export function runP34Scenario(id){const scenario=scenarios[id];if(!scenario)throw new Error(`Unknown P3/P4 scenario: ${id}`);return scenario()}
export async function sealP34Scenario(report){const bytes=new TextEncoder().encode(stable(report)),digest=await globalThis.crypto.subtle.digest('SHA-256',bytes);return{...report,receiptSha256:Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,'0')).join('').toUpperCase()}}
