'use strict';
const fs=require('fs'),path=require('path'),assert=require('assert');
const root=__dirname;
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const manifest=JSON.parse(fs.readFileSync(path.join(root,'world.manifest.json'),'utf8'));
const adapter=JSON.parse(fs.readFileSync(path.join(root,'mirror-adapter.descriptor.json'),'utf8'));
const registry=JSON.parse(fs.readFileSync(path.join(root,'..','world-registry.json'),'utf8'));
assert.equal(manifest.id,'world.grafthold.globe');
assert.equal(manifest.ownership.state_owner,'living-world');
assert.equal(manifest.ownership.games_may_own_world,false);
assert.equal(manifest.runtime.remote_dependencies,false);
assert.ok(/\/shared\/vendor\/three-r160\/three\.module\.js/.test(html),'local renderer import');
assert.ok(!/https?:\/\//.test(html),'no remote runtime URL');
assert.ok(/window\.AXMLivingWorld/.test(html),'read-only world seam');
assert.ok(!/Math\.random\(/.test(html),'world randomness uses persisted seeded state');
assert.equal(adapter.status,'DESCRIPTOR_ONLY');
assert.equal(adapter.live_apply_supported,false);
assert.deepEqual(adapter.supported_operations,[]);
assert.equal(registry.worlds.filter(x=>x.id===manifest.id).length,1);
console.log('living globe selftest: PASS (12 assertions)');
