#!/usr/bin/env python3
"""Validate every shipped schema against a real runtime-produced object.

This is a release/audit helper, not a runtime dependency. It requires the
third-party ``jsonschema`` package in the verification environment.
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
import tempfile
import zipfile
from unittest import mock
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

try:
    from jsonschema import Draft202012Validator
except ImportError as exc:  # pragma: no cover - release environment guard
    raise SystemExit(
        "tools/verify_runtime_contracts.py requires jsonschema in the verification environment"
    ) from exc

from axm_challenge_arena import (
    ChallengeArena,
    build_receipt,
    load_schema,
    schema_names,
    verify_evidence_bundle,
)
from axm_challenge_arena.bridge import FileBridge
from axm_challenge_arena.orchestration import public_orchestration_report, task_receipt
from axm_challenge_arena.presets import generic_packet
from axm_challenge_arena.store import ChallengeStore
from axm_challenge_arena.utils import atomic_write_json, read_json, strict_json_loads


def _submission_manifest(
    arena: ChallengeArena,
    challenge_id: str,
    participant_id: str,
) -> dict[str, Any]:
    contract = arena.submission_contract(challenge_id, participant_id)
    return {
        "schema_version": "axm.challenge-submission/0.2",
        "challenge_id": challenge_id,
        "packet_hash": contract["packet_hash"],
        "rubric_hash": contract["rubric_hash"],
        "participant_id": participant_id,
        "summary": f"Runtime contract specimen from {participant_id}.",
        "artifacts": [
            {
                "path": "result.txt",
                "deliverable_id": "primary",
                "role": "primary",
                "media_type": "text/plain",
                "provenance": {
                    "origin": "generated by runtime contract verification",
                    "rights": "CC0-1.0",
                    "source_refs": [],
                },
            }
        ],
        "claims": {"contract_specimen": True},
        "notes": [],
    }


def build_runtime_objects(workspace: Path) -> tuple[dict[str, Any], dict[str, str]]:
    arena = ChallengeArena(workspace, trusted_runner_keys={"audit-key": "audit-secret"})
    challenge_id = "runtime-contract-audit"

    module_job = read_json(ROOT / "examples" / "module_job_asset_factory.json")
    packet = generic_packet(
        challenge_id,
        "Runtime contract audit",
        "Produce real objects for every shipped Arena schema.",
        source_module="release-audit",
        source_job_id="runtime-contract-audit-job",
    )
    packet["created_at"] = "2026-08-15T00:00:00Z"
    packet["created_by"] = "tools/verify_runtime_contracts.py"
    packet["inputs"] = [{"id": "brief", "kind": "file", "required": True}]
    arena.create_challenge(packet, actor="release-audit")

    source_input = workspace / "source-brief.txt"
    source_input.write_text("Locked runtime contract audit brief.\n", encoding="utf-8")
    sealed = arena.seal_draft_input(
        challenge_id, "brief", source_input, actor="release-audit"
    )

    participants = ["agent-a", "agent-b", "agent-c"]
    for participant in participants:
        arena.register_participant(
            challenge_id,
            participant,
            display_name=participant.upper(),
            actor="release-audit",
        )
    arena.lock_challenge(challenge_id, actor="release-audit")

    locked_task_state = arena.get(challenge_id)
    seat_task_plan = locked_task_state["seat_task_plans"]["BUILD"]
    first_task_id = locked_task_state["seat_task_index"][f"BUILD:{participants[0]}"]

    bridge = FileBridge(arena, workspace / "bridge")
    build_dirs = bridge.export_build_packets(challenge_id)
    build_packet = read_json(build_dirs[0] / "challenge-packet.json")

    seat_lease = arena.claim_task(
        challenge_id,
        first_task_id,
        worker_id=participants[0],
        actor="release-audit",
    )
    first_task_token = seat_lease["lease_token"]

    submissions: dict[str, dict[str, Any]] = {}
    stored_submission_manifest: dict[str, Any] | None = None
    for index, participant in enumerate(participants):
        source = workspace / f"candidate-{participant}"
        source.mkdir(parents=True)
        (source / "result.txt").write_text(
            f"Candidate {participant} quality {90 - index * 10}.\n", encoding="utf-8"
        )
        record = arena.submit(
            challenge_id,
            participant,
            source,
            _submission_manifest(arena, challenge_id, participant),
            task_token=first_task_token if index == 0 else None,
            task_usage=(
                {
                    "wall_seconds": 12.5,
                    "token_units": 2048,
                    "tool_calls": 3,
                    "input_bytes": 1024,
                    "output_bytes": 4096,
                    "measurement_source": "release-audit",
                    "notes": "Runtime contract specimen.",
                }
                if index == 0
                else None
            ),
        )
        submissions[participant] = record
        if stored_submission_manifest is None:
            stored_submission_manifest = read_json(
                arena.store.challenge_dir(challenge_id)
                / record["relative_directory"]
                / "submission.json"
            )

    first = submissions[participants[0]]
    external_job = arena.external_runner_job(challenge_id, first["submission_id"])
    locked = arena.get(challenge_id)
    deterministic_receipt = build_receipt(
        challenge_id=challenge_id,
        submission_id=first["submission_id"],
        packet_hash=locked["packet_hash"],
        rubric_hash=locked["rubric_hash"],
        submission_content_hash=first["content_hash"],
        artifact_set_hash=first["artifact_set_hash"],
        runner_id="audit-runner",
        results=[
            {
                "result_id": "runtime-audit",
                "status": "PASS",
                "score": 100,
                "summary": "Bound release audit result.",
                "evidence": {"mode": "contract-specimen"},
            }
        ],
        key_id="audit-key",
        key="audit-secret",
        metadata={"purpose": "runtime contract validation"},
    )
    arena.attach_external_receipt(
        challenge_id, first["submission_id"], deterministic_receipt
    )

    completed_build_state = arena.get(challenge_id)
    seat_task_specimen = completed_build_state["seat_tasks"][first_task_id]
    seat_task_receipt = task_receipt(seat_task_specimen)

    arena.close_submissions(challenge_id, actor="release-audit")
    build_orchestration_report = arena.get(challenge_id)["orchestration_reports"]["BUILD"]
    public_build_orchestration_report = public_orchestration_report(
        build_orchestration_report
    )
    arena.run_deterministic_checks(challenge_id)
    arena.open_review(challenge_id, actor="release-audit")
    seat_task_list = arena.list_tasks(challenge_id, include_private=False)
    review_state = arena.get(challenge_id)
    review_assignment = review_state["review_assignment_report"]
    review_content_safety = review_state["review_content_safety"]
    review_protocol = read_json(
        arena.store.challenge_dir(challenge_id) / "reports" / "review-protocol.json"
    )
    review_packet = arena.review_packet(challenge_id, participants[0])

    stored_review: dict[str, Any] | None = None
    preferred_author = participants[0]
    label_to_author = {
        label: review_state["submissions"][submission_id]["participant_id"]
        for label, submission_id in review_state["blind_map"].items()
    }
    for reviewer in participants:
        packet_for_reviewer = arena.review_packet(challenge_id, reviewer)
        evaluations: dict[str, Any] = {}
        for label in packet_for_reviewer["candidate_labels"]:
            author = label_to_author[label]
            base = 92 if author == preferred_author else (78 if author == participants[1] else 66)
            criterion_ids = [
                criterion["id"] for criterion in packet_for_reviewer["peer_criteria"]
            ]
            evaluations[label] = {
                "scores": {criterion_id: base for criterion_id in criterion_ids},
                "abstentions": {},
                "evidence_refs": {
                    criterion_id: [
                        {
                            "kind": "artifact",
                            "path": "result.txt",
                            "locator": "complete file",
                            "note": "Direct candidate output used for this audit score.",
                        }
                    ]
                    for criterion_id in criterion_ids
                },
                "strengths": ["Clear runtime specimen."],
                "weaknesses": ["Audit-only content."],
                "risks": [],
                "merge_worthy": [],
            }
        ranking = sorted(
            packet_for_reviewer["candidate_labels"],
            key=lambda label: (
                label_to_author[label] != preferred_author,
                label_to_author[label],
            ),
        )
        stored = arena.submit_review(
            challenge_id,
            reviewer,
            {
                "schema_version": "axm.challenge-review/0.4",
                "rubric_hash": packet_for_reviewer["rubric_hash"],
                "assignment_hash": packet_for_reviewer["assignment_hash"],
                "review_packet_hash": packet_for_reviewer["review_packet_hash"],
                "evaluations": evaluations,
                "ranking_tiers": [[label] for label in ranking],
                "ranking": ranking,
                "overall_reason": "Runtime contract audit ranking.",
            },
        )
        if stored_review is None:
            stored_review = stored

    arena.close_voting(challenge_id, actor="release-audit")
    blind_seed_reveal = read_json(
        arena.store.challenge_dir(challenge_id) / "reports" / "blind-seed-reveal.json"
    )
    arena.synthesize(challenge_id)
    synthesized = arena.get(challenge_id)
    if not synthesized.get("result", {}).get("provisional_winner"):
        raise RuntimeError("Runtime contract audit did not produce a provisional winner")

    followup = arena.spawn_followup(
        challenge_id,
        "runtime-contract-audit-child",
        mode="BEAT_WINNER",
        copy_participants=False,
        copy_inputs=True,
        actor="release-audit",
    )
    lineage_receipt = followup["lineage_input_receipt"]
    if not lineage_receipt:
        raise RuntimeError("Runtime contract audit did not produce a lineage receipt")

    winner = arena.get(challenge_id)["result"]["provisional_winner"]
    final_decision = arena.finalize(
        challenge_id,
        {
            "action": "HOLD",
            "selected_blind_labels": [winner],
            "notes": "Release audit only; no downstream approval.",
        },
        actor="release-audit",
    )
    integration_return = arena.integration_return(challenge_id)
    capabilities = arena.capabilities()

    bundle_path = workspace / "runtime-contract-audit.zip"
    arena.export_evidence_bundle(challenge_id, bundle_path)
    bundle_verification = verify_evidence_bundle(bundle_path)
    if not bundle_verification.get("valid"):
        raise RuntimeError(
            f"Runtime contract evidence bundle verification failed: {bundle_verification}"
        )
    with zipfile.ZipFile(bundle_path, "r") as archive:
        bundle_manifest = strict_json_loads(archive.read("BUNDLE-MANIFEST.json").decode("utf-8"))

    state = arena.get(challenge_id)
    if stored_submission_manifest is None or stored_review is None:
        raise RuntimeError("Runtime contract audit failed to capture submission/review objects")

    checkpoint_files = sorted(
        (arena.store.challenge_dir(challenge_id) / "checkpoints").glob("*.json")
    )
    if not checkpoint_files:
        raise RuntimeError("Runtime contract audit produced no checkpoint specimen")
    checkpoint = read_json(checkpoint_files[0])

    # Create a real interrupted legacy migration marker through the production
    # migration path. The injected interruption happens only after the exact JSONL
    # projection has been hashed and the resumable marker has been committed.
    migration_workspace = workspace / "legacy-migration-contract-specimen"
    legacy_store = ChallengeStore(migration_workspace)
    legacy_challenge_dir = legacy_store.challenge_dir(challenge_id)
    legacy_challenge_dir.mkdir(parents=True, exist_ok=True)
    legacy_store.event_files_dir(challenge_id).mkdir(parents=True, exist_ok=True)
    shutil.copyfile(
        arena.store.events_path(challenge_id),
        legacy_store.events_path(challenge_id),
    )
    with mock.patch.object(
        legacy_store,
        "_write_event_file",
        side_effect=RuntimeError("intentional contract-audit interruption"),
    ):
        try:
            legacy_store.migrate_legacy_events(challenge_id)
        except RuntimeError as exc:
            if "intentional contract-audit interruption" not in str(exc):
                raise
    migration_marker = read_json(legacy_store.legacy_migration_path(challenge_id))

    objects: dict[str, Any] = {
        "module-job.schema.json": module_job,
        "challenge-packet.schema.json": state["packet"],
        "build-packet.schema.json": build_packet,
        "seat-task.schema.json": seat_task_specimen,
        "seat-task-plan.schema.json": seat_task_plan,
        "seat-task-receipt.schema.json": seat_task_receipt,
        "seat-task-list.schema.json": seat_task_list,
        "seat-lease.schema.json": seat_lease,
        "orchestration-report.schema.json": build_orchestration_report,
        "orchestration-public-report.schema.json": public_build_orchestration_report,
        "input-receipt.schema.json": sealed["receipt"],
        "submission.schema.json": stored_submission_manifest,
        "external-runner-job.schema.json": external_job,
        "deterministic-receipt.schema.json": deterministic_receipt,
        "review-assignment.schema.json": review_assignment,
        "review-content-safety.schema.json": review_content_safety,
        "review-protocol.schema.json": review_protocol,
        "candidate-diagnostics.schema.json": review_state["candidate_diagnostics"],
        "candidate-diagnostics-blind.schema.json": review_state["blind_candidate_diagnostics"],
        "blind-seed-reveal.schema.json": blind_seed_reveal,
        "review-packet.schema.json": review_packet,
        "review.schema.json": stored_review,
        "final-decision.schema.json": final_decision,
        "return.schema.json": integration_return,
        "bundle-manifest.schema.json": bundle_manifest,
        "bundle-verification.schema.json": bundle_verification,
        "checkpoint.schema.json": checkpoint,
        "legacy-event-migration.schema.json": migration_marker,
        "lineage-input-receipt.schema.json": lineage_receipt,
        "capabilities.schema.json": capabilities,
    }
    origins = {
        name: "runtime-produced" for name in objects
    }
    origins["module-job.schema.json"] = "shipped producer example"
    return objects, origins


def verify(workspace: Path) -> dict[str, Any]:
    names = list(schema_names())
    objects, origins = build_runtime_objects(workspace)
    missing = sorted(set(names) - set(objects))
    extra = sorted(set(objects) - set(names))
    if missing or extra:
        raise RuntimeError(f"Schema/object mismatch: missing={missing}, extra={extra}")

    validated: list[dict[str, Any]] = []
    for name in names:
        schema = load_schema(name)
        Draft202012Validator.check_schema(schema)
        Draft202012Validator(schema).validate(objects[name])
        validated.append(
            {
                "schema_file": name,
                "schema_id": schema.get("$id"),
                "object_origin": origins[name],
                "status": "PASS",
            }
        )

    arena = ChallengeArena(workspace, trusted_runner_keys={"audit-key": "audit-secret"})
    integrity = arena.verify_integrity("runtime-contract-audit")
    if not integrity.get("valid"):
        raise RuntimeError(f"Runtime contract challenge integrity failed: {integrity}")

    return {
        "schema_version": "axm.challenge-arena-runtime-contract-audit/0.4",
        "status": "PASS",
        "schema_count": len(validated),
        "draft_2020_12_meta_schema_checks": len(validated),
        "runtime_object_validations": len(validated),
        "challenge_integrity_valid": True,
        "validated": validated,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--workspace", help="Optional empty workspace to retain after the audit")
    parser.add_argument("--out", help="Optional JSON report path")
    args = parser.parse_args()

    if args.workspace:
        workspace = Path(args.workspace).expanduser().resolve()
        workspace.mkdir(parents=True, exist_ok=True)
        report = verify(workspace)
    else:
        with tempfile.TemporaryDirectory(prefix="axm-contract-audit-") as temp:
            report = verify(Path(temp))

    if args.out:
        atomic_write_json(Path(args.out), report)
    print(json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
