(function(){
  'use strict';
  const canvas=document.querySelector('#partyWorld'),ctx=canvas.getContext('2d');let view=null,time=0,last=performance.now();
  function resize(){const d=Math.min(2,devicePixelRatio||1);canvas.width=innerWidth*d;canvas.height=innerHeight*d;ctx.setTransform(d,0,0,d,0,0)}addEventListener('resize',resize);resize();
  function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'})[c])}
  function map(p){const s=view.screen;return{x:(p.x-s.x)*s.zoom+innerWidth/2,y:(p.y-s.y)*s.zoom+innerHeight/2}}
  function rounded(x,y,w,h,r){r=Math.min(r,w/2,h/2);ctx.beginPath();if(typeof ctx.roundRect==='function'){ctx.roundRect(x,y,w,h,r);return}ctx.moveTo(x+r,y);ctx.lineTo(x+w-r,y);ctx.quadraticCurveTo(x+w,y,x+w,y+r);ctx.lineTo(x+w,y+h-r);ctx.quadraticCurveTo(x+w,y+h,x+w-r,y+h);ctx.lineTo(x+r,y+h);ctx.quadraticCurveTo(x,y+h,x,y+h-r);ctx.lineTo(x,y+r);ctx.quadraticCurveTo(x,y,x+r,y);ctx.closePath()}
  function draw(now){time+=Math.min(50,now-last);last=now;const g=ctx.createRadialGradient(innerWidth*.5,innerHeight*.45,20,innerWidth*.5,innerHeight*.5,Math.max(innerWidth,innerHeight));g.addColorStop(0,'#123039');g.addColorStop(1,'#02080c');ctx.fillStyle=g;ctx.fillRect(0,0,innerWidth,innerHeight);
    if(view&&view.visible){view.visible.regions.forEach(r=>{const p=map(r.bounds),w=r.bounds.width*view.screen.zoom,h=r.bounds.height*view.screen.zoom;ctx.fillStyle=r.palette[0]+'bb';ctx.strokeStyle=r.palette[2]+'29';ctx.lineWidth=1;rounded(p.x,p.y,w,h,60);ctx.fill();ctx.stroke();ctx.fillStyle=r.palette[2]+'45';ctx.font='700 18px ui-monospace,monospace';ctx.fillText(r.name.toUpperCase(),p.x+22,p.y+36)});
      view.visible.paths.forEach((r,i)=>{const a=map(r.from),b=map(r.to);ctx.strokeStyle='rgba(4,18,23,.9)';ctx.lineWidth=r.width*view.screen.zoom;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();ctx.strokeStyle=i%2?'#ec91ff55':'#6ef4cf55';ctx.lineWidth=2;ctx.setLineDash([8,18]);ctx.lineDashOffset=-time*.02;ctx.stroke();ctx.setLineDash([])});
      view.visible.points.forEach((p,i)=>{const q=map(p),c=p.kind==='breach'?'#ff7a99':p.kind==='thread-knot'?'#ec91ff':p.kind==='memory-echo'?'#ffd66e':p.kind==='relay'?'#ffd66e':'#6ef4cf';ctx.save();ctx.translate(q.x,q.y);ctx.rotate(time*.00025+i);ctx.strokeStyle=c;ctx.fillStyle=c+'24';ctx.shadowColor=c;ctx.shadowBlur=18;if(p.kind==='memory-echo'){ctx.beginPath();ctx.arc(0,0,14,0,Math.PI*2);ctx.stroke();ctx.rotate(Math.PI/4);ctx.strokeRect(-8,-8,16,16)}else{ctx.strokeRect(-11,-11,22,22);ctx.fillRect(-6,-6,12,12)}ctx.restore()});
      view.visible.resources.forEach(p=>{const q=map(p);ctx.fillStyle='#ffd66e';ctx.shadowColor='#ffd66e';ctx.shadowBlur=13;ctx.beginPath();ctx.arc(q.x,q.y,5+Math.sin(time*.004+p.x),0,Math.PI*2);ctx.fill()});
      view.visible.actors.forEach((a,i)=>{const q=map(a.position),colors=['#6ef4cf','#4de8ff','#ffd66e','#ec91ff','#ff7a99','#d3ff7a','#90a8ff','#7fffe8'],c=colors[i%colors.length];ctx.fillStyle='#06161c';ctx.strokeStyle=c;ctx.lineWidth=2;ctx.shadowColor=c;ctx.shadowBlur=18;ctx.beginPath();ctx.arc(q.x,q.y,13,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.fillStyle='#effffb';ctx.font='700 10px system-ui';ctx.textAlign='center';ctx.fillText(a.displayName,q.x,q.y-23);ctx.textAlign='left'});
    }requestAnimationFrame(draw)}
  async function poll(){try{const r=await fetch('/api/party-state?width='+innerWidth+'&height='+innerHeight),d=await r.json();if(!r.ok||d.ok===false||d.status==='waiting')return;view=d;document.querySelector('#mission h1').textContent=d.hud.mission.title;document.querySelector('#mission p').textContent=d.hud.mission.brief;document.querySelector('#condition').textContent=(d.hud.region+' · '+d.hud.conditions.dayPhase+' · '+d.hud.conditions.weather+' · '+d.hud.conditions.expeditionModifier+' · LOCAL ONLY').replace(/-/g,' ').toUpperCase();document.querySelector('#archiveMeta').textContent='ARCHIVE '+d.hud.journal.recovered+' / '+d.hud.journal.total;document.querySelector('#requestMeta').textContent='REQUESTS '+d.hud.requests.claimed+' / '+d.hud.requests.total+(d.hud.requests.ready?' · '+d.hud.requests.ready+' READY':'');document.querySelector('#collectionMeta').textContent='KIN '+d.hud.collection.connected+' / '+d.hud.collection.total;document.querySelector('#party').innerHTML=d.partyHud.map((a,i)=>'<article class="seat '+(!a.active?'off':'')+'"><i style="filter:hue-rotate('+(i*50)+'deg)"></i><div><strong>'+esc(a.displayName)+'</strong><small>'+esc(a.role)+' · '+esc(a.controllerType)+'</small></div><b>'+a.integrity+'/'+a.maxIntegrity+'</b></article>').join('')}catch(e){}}
  setInterval(poll,220);poll();requestAnimationFrame(draw);
})();
