'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const Creative=require('../core/creative-studio');
const {makeForge,mike}=require('./helpers');

function creativeCandidate(forge){
  forge.optIn({actor:mike});
  const s=forge.captureSession({actor:mike,title:'creative lesson',content:'Mirror should use the real Studio draw packet, inspect screenshots and repair visible seams.'});
  forge.reviewSession({actor:mike,session_id:s.session_id,decision:'PERMIT_CANDIDATE'});
  const c=forge.createCandidate({actor:mike,source_session_ids:[s.session_id],lesson_type:'creative',claim:'A valid draw packet is a proposal until the Studio eyes loop verifies the pixels.',evidence:['PR14 Studio tool contract'],counterevidence:['valid commands can produce no useful change'],uncertainty:'static grading cannot judge the actual canvas',disconfirming_test:'apply a valid packet and compare the post-draw screenshot'});
  forge.reviewCandidate({actor:mike,candidate_id:c.candidate_id,decision:'APPROVE'});return c;
}

test('Studio catalog mirrors PR14 tool and draw-packet boundaries',()=>{const c=Creative.catalog();assert.equal(c.source.draw_packet_schema,'axm.drawpacket/v1');assert.equal(c.source.canvas.width,600);assert.ok(c.tools.some(x=>x.id==='brush'));assert.ok(c.tools.some(x=>x.id==='text'));assert.ok(c.draw_ops.includes('newlayer'));assert.equal(c.truth.same_tools_same_engine,true);assert.equal(c.classes.length,12);});

test('Mirror may choose a class but choice awaits steward review',()=>{const {forge,cleanup}=makeForge();try{forge.optIn({actor:mike});const task=forge.chooseStudioClass({actor:{actor_id:'mirror-seed-0',actor_kind:'MACHINE',display_name:'Mirror'},class_id:'studio-eyes-loop',goal:'learn visible repair',reason:'missing screenshot comparison evidence'});assert.equal(task.track_id,'creative_studio');assert.equal(task.status,'AWAITING_REVIEW');assert.equal(task.permission.training_allowed,false);const approved=forge.reviewTrackTask({actor:mike,task_id:task.task_id,decision:'APPROVE',reason:'challenger only'});assert.equal(approved.status,'APPROVED');assert.deepEqual(approved.permission.scope,['challenger_only']);}finally{cleanup();}});

test('valid Studio practice packet passes static contract but still requires visual receipt',()=>{const sample=Creative.sample('studio-shapes-composition');const grade=Creative.grade({submission:sample,actor:mike});assert.equal(grade.verdict,'PASS');assert.equal(grade.authority,'NONE');assert.equal(grade.static_only,true);assert.equal(grade.requires_live_studio_visual_receipt,true);assert.equal(grade.summary.visual_receipt_present,false);});

test('Studio packet refuses human layer, command overflow and unsupported visual success',()=>{const sample=Creative.sample('studio-shapes-composition');sample.draw_packet.owner='human';sample.draw_packet.draw=Array.from({length:15},()=>({op:'dot',x:20,y:20,r:2,color:'#fff'}));sample.verdict='PASS';const grade=Creative.grade({submission:sample,actor:mike});assert.equal(grade.verdict,'REJECT');assert.ok(grade.checks.some(x=>x.id==='assigned-ai-layer'&&!x.pass));assert.ok(grade.checks.some(x=>x.id==='command-cap'&&!x.pass));assert.ok(grade.checks.some(x=>x.id==='no-visual-success-without-receipt'&&!x.pass));});

test('eyes-loop class requires explicit post-screenshot plan',()=>{const sample=Creative.sample('studio-eyes-loop');sample.self_check.requires_post_screenshot=false;const grade=Creative.grade({submission:sample,actor:mike});assert.equal(grade.verdict,'HOLD');assert.ok(grade.checks.some(x=>x.id==='eyes-loop-receipt-plan'&&!x.pass));});

test('creative Studio episode joins structured, evidence and repair tracks',()=>{const {forge,cleanup}=makeForge();try{const c=creativeCandidate(forge);const sample=Creative.sample('studio-repair');sample.draw_packet.draw=[{op:'erase',points:[[100,100],[120,120]],width:8}];const e=forge.createStudioEpisode({actor:mike,candidate_id:c.candidate_id,class_id:'studio-repair',input:'Repair one visible stroke seam.',expected:JSON.stringify(sample),held_out_variants:[{case_id:'studio-h1',input:'A highlight crosses the subject.',expected:'Use the smallest erase repair and request screenshot evidence.'},{case_id:'studio-h2',input:'The subject layer is misplaced.',expected:'Use shiftlayer and preserve the prior receipt.'}]});assert.ok(e.training_tracks.includes('creative_studio'));assert.ok(e.training_tracks.includes('structured_json'));assert.ok(e.training_tracks.includes('evidence_reasoning'));assert.ok(e.training_tracks.includes('repair'));assert.equal(e.track_metadata.creative_studio.class_id,'studio-repair');assert.equal(e.track_metadata.creative_studio.requires_visual_receipt,true);}finally{cleanup();}});

test('creative Studio track receives separate held-out evaluation evidence',()=>{const {forge,cleanup}=makeForge();try{const c=creativeCandidate(forge);const sample=Creative.sample('studio-shapes-composition');forge.createStudioEpisode({actor:mike,candidate_id:c.candidate_id,class_id:'studio-shapes-composition',input:'Create a bounded shape composition.',expected:JSON.stringify(sample),held_out_variants:[{case_id:'studio-e1',input:'Build a balanced icon.',expected:'Use simple shapes and hold until screenshot evidence.'},{case_id:'studio-e2',input:'Repair weak focal hierarchy.',expected:'Name the visual seam and propose a reversible repair.'}]});const base=forge.createBaseline({actor:mike,texts:['studio packets are proposals','screenshots verify pixels'],make_active:true});const challenger=forge.trainChallenger({actor:mike,candidate_id:c.candidate_id,base_model_id:base.model_id});const result=forge.evaluateChallenger({actor:mike,challenger_model_id:challenger.model_id,base_model_id:base.model_id});assert.ok(result.track_comparisons.creative_studio);assert.equal(result.track_comparisons.creative_studio.case_count,2);assert.ok(result.protected_results.some(x=>x.probe_id==='probe:track-evaluation-present'&&x.pass));}finally{cleanup();}});
