'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),path=require('path');
const root=path.resolve(__dirname,'..');
test('technical, creative, rooted, reasoning and adaptive curriculum definitions are present and non-authoritative',()=>{for(const file of ['structured-json-v1.json','coding-foundations-v1.json','creative-studio-classes-v1.json']){const row=JSON.parse(fs.readFileSync(path.join(root,'curricula',file),'utf8'));assert.equal(row.authority,'NONE');assert.ok(row.levels.length>=8);assert.match(row.truth_boundary,/truth|execution gate/i);}const rooted=JSON.parse(fs.readFileSync(path.join(root,'curricula','rooted-intelligence-v1.json'),'utf8'));assert.equal(rooted.authority,'NONE');assert.equal(rooted.canon_edit_authority,false);assert.equal(rooted.assessment.phrase_overlap_primary,false);assert.equal(rooted.roots.length,4);assert.ok(rooted.classes.length>=12);const reasoning=JSON.parse(fs.readFileSync(path.join(root,'curricula','reasoning-development-v1.json'),'utf8'));assert.equal(reasoning.authority,'NONE');assert.equal(reasoning.assessment.single_iq_score,false);assert.equal(reasoning.assessment.hidden_chain_of_thought_required,false);assert.equal(reasoning.skills.length,18);assert.equal(reasoning.stages.length,6);const adaptive=JSON.parse(fs.readFileSync(path.join(root,'curricula','adaptive-communication-v1.json'),'utf8'));assert.equal(adaptive.authority,'NONE');assert.equal(adaptive.track_id,'adaptive_communication');assert.ok(adaptive.classes.length>=14);assert.ok(adaptive.delivery_fields.includes('tone'));assert.ok(adaptive.protected_fields.includes('core_claim'));});
test('human UI exposes technical, creative and grounded-root, reasoning and adaptive schools without authority',()=>{const html=fs.readFileSync(path.join(root,'ui','index.html'),'utf8');assert.match(html,/JSON literacy grader/);assert.match(html,/Coding foundations grader/);assert.match(html,/MIRROR ART SCHOOL/);assert.match(html,/Studio practice packet grader/);assert.match(html,/MIRROR ROOT SCHOOL/);assert.match(html,/Grounded response grader/);assert.match(html,/canon-edit authority off/i);assert.match(html,/MIRROR REASONING SCHOOL/);assert.match(html,/non-ranking development profile/i);assert.match(html,/ADAPTIVE COMMUNICATION SCHOOL/);assert.match(html,/Semantic-preserving adaptation receipt/);assert.match(html,/Agreement is not success/i);});

test('rooted adversarial and held-out fixtures are packaged and frozen',()=>{const adv=JSON.parse(fs.readFileSync(path.join(root,'fixtures','rooted','adversarial-cases.json'),'utf8'));const held=JSON.parse(fs.readFileSync(path.join(root,'fixtures','rooted','held-out-cases.json'),'utf8'));assert.ok(adv.cases.length>=6);assert.equal(held.frozen,true);assert.ok(held.cases.length>=12);const response=JSON.parse(fs.readFileSync(path.join(root,'schemas','rooted-response.schema.json'),'utf8'));assert.equal(response.$id,'axm.mirror.rooted-response/v1');});

test('adaptive adversarial and held-out fixtures are packaged and frozen',()=>{const adv=JSON.parse(fs.readFileSync(path.join(root,'fixtures','adaptive','adversarial-cases.json'),'utf8'));const held=JSON.parse(fs.readFileSync(path.join(root,'fixtures','adaptive','held-out-cases.json'),'utf8'));assert.equal(adv.frozen,true);assert.ok(adv.cases.length>=8);assert.equal(held.frozen,true);assert.ok(held.cases.length>=14);const response=JSON.parse(fs.readFileSync(path.join(root,'schemas','adaptive-response.schema.json'),'utf8'));assert.equal(response.$id,'axm.mirror.adaptive-response/v1');});
