'use strict';
(function(){
  const Fabric=window.AXMDeterministicOrganFabric,Zip=window.AXMZipStore,ArchiveCtor=window.AXMOrganBrowserArchive&&window.AXMOrganBrowserArchive.BrowserArchive;
  const $=function(id){return document.getElementById(id);};
  const state={packs:[],intent:null,run:null,comparison:null,archive:null};
  function el(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=String(text);return node;}
  function setNotice(node,message,tone){node.textContent=message;node.className=node.className.split(' ')[0]+(tone?' '+tone:'');}
  function selectedPack(){return state.packs.find(function(pack){return pack.id===$('field-pack').value;});}
  function switchView(name){document.querySelectorAll('.view').forEach(function(view){view.classList.toggle('active',view.id==='view-'+name);});document.querySelectorAll('.tab').forEach(function(tab){const active=tab.dataset.view===name;tab.classList.toggle('active',active);tab.setAttribute('aria-selected',String(active));});}
  function showIntent(intent,message){state.intent=intent;$('intent-json').value=JSON.stringify(intent,null,2);$('reviewed').checked=false;setNotice($('preview-status'),message||'Structured preview loaded. Review every field before generation.','good');validateEditor();}
  function parseEditor(){try{return JSON.parse($('intent-json').value);}catch(error){setNotice($('intent-validation'),'Invalid JSON: '+error.message,'bad');return null;}}
  function validateEditor(){const intent=parseEditor(),pack=selectedPack();if(!intent||!pack)return false;const result=Fabric.validateIntent(intent,pack);state.intent=intent;if(result.ok)setNotice($('intent-validation'),'VALID · exact pack lineage, closed intent fields, typed ports, bounded resources, and canonical digest.','good');else setNotice($('intent-validation'),'REFUSED · '+result.errors.slice(0,4).map(function(row){return row.code+' at '+row.path;}).join(' · '),'bad');return result.ok;}
  function renderWeights(){const root=$('weights');root.replaceChildren();Object.entries(Fabric.METRIC_PROFILE.weights).forEach(function(entry){const card=el('div','weight');card.append(el('strong',null,entry[1]+'%'),el('span',null,entry[0].replace(/[A-Z]/g,function(c){return ' '+c.toLowerCase();})));root.append(card);});}
  function download(name,bytes,type){const blob=bytes instanceof Uint8Array?new Blob([bytes],{type:type}):new Blob([bytes],{type:type}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download=name;anchor.click();setTimeout(function(){URL.revokeObjectURL(url);},1000);}
  function candidateCard(candidate){
    const card=el('article','panel candidate-card');card.dataset.strategy=candidate.definition.strategy;const top=el('div','candidate-top'),heading=el('div');heading.append(el('p','strategy',candidate.definition.strategy),el('h3',null,candidate.package.id));const score=el('div','score',candidate.evaluation.metrics.score);score.append(el('small',null,' /100'));top.append(heading,score);card.append(top,el('code','digest',candidate.package.packageDigest));
    const gates=el('ul','gate-list');candidate.evaluation.gates.forEach(function(gate){const row=el('li');row.append(el('span',null,gate.id),el('span',gate.ok?'pass':'fail',gate.ok?'PASS':'FAIL'));gates.append(row);});card.append(gates);
    const traceDetails=document.createElement('details'),traceSummary=document.createElement('summary');traceSummary.textContent='Logic trace · first required fixture';traceDetails.append(traceSummary);const trace=el('ul','trace-list'),fixture=candidate.evaluation.fixtures.required[0];(fixture&&fixture.trace||[]).forEach(function(step){const row=el('li');row.append(el('span',null,step.node+' · '+step.op),el('code',null,step.valueDigest.slice(7,17)));trace.append(row);});traceDetails.append(trace);card.append(traceDetails);
    const judgments=el('div','judgments');candidate.evaluation.limitations.forEach(function(text){judgments.append(el('p',null,'OPEN JUDGMENT · '+text));});card.append(judgments);
    const buttons=el('div','button-row'),zipButton=el('button','secondary','Download deterministic ZIP');zipButton.type='button';zipButton.addEventListener('click',function(){download(candidate.package.id+'.zip',Zip.build(candidate.files,candidate.package.id),'application/zip');});buttons.append(zipButton);card.append(buttons);return card;
  }
  function renderCandidates(){const root=$('candidate-list');root.replaceChildren();if(!state.run||!state.run.candidates.length){root.append(el('p','empty','No valid candidates. Review the typed failure receipts below.'));return;}state.run.candidates.forEach(function(candidate){root.append(candidateCard(candidate));});$('candidate-count').textContent=state.run.candidates.length;const failures=$('failure-list');failures.replaceChildren();(state.run.failures||[]).forEach(function(failure){const card=el('article','panel');card.append(el('h3',null,failure.strategy+' · REJECTED'),el('code','digest',failure.failureDigest),el('p','judgments',failure.failedGates.map(function(g){return g.id;}).join(' · ')));failures.append(card);});}
  function comparisonRow(row,index){const line=el('div','comparison-row');line.append(el('span','strategy',row.strategy),el('code','digest',row.packageDigest.slice(0,25)+'…'),el('strong','score',row.score));const metrics=el('div','metric-mini',Object.entries(row.components).map(function(entry){return entry[0]+': '+entry[1];}).join(' · ')),button=el('button','secondary','Select for implementation');button.type='button';button.dataset.packageDigest=row.packageDigest;button.addEventListener('click',async function(){const candidate=state.run.candidates.find(function(item){return item.package.packageDigest===row.packageDigest;}),receipt=Fabric.selectCandidate(state.comparison,candidate,'Mike Tobi');await state.archive.addSelection(receipt);const panel=$('selection-receipt');panel.hidden=false;panel.replaceChildren(el('strong',null,'Selection receipt recorded · nothing applied'),el('p',null,receipt.candidateId+' is selected for implementation review only.'),el('code',null,receipt.selectionDigest),el('p','helper','installed false · registered false · staged false · promoted false · canonChanged false'));await refreshArchive();panel.scrollIntoView({behavior:'smooth',block:'nearest'});});line.append(metrics,button);return line;}
  function renderComparison(){renderWeights();const root=$('comparison');root.replaceChildren();if(!state.comparison||!state.comparison.rows.length){root.append(el('p','empty','No valid candidates to compare yet.'));return;}state.comparison.rows.forEach(function(row,index){root.append(comparisonRow(row,index));});if(state.comparison.ties.length){root.append(el('p','helper','TIES PRESERVED · '+state.comparison.ties.map(function(group){return group.score+': '+group.candidateIds.join(', ');}).join(' · ')));}}
  async function refreshArchive(){const index=await state.archive.list(),dormant=index.objects.filter(function(row){return row.startupPolicy==='DORMANT';}).length,connected=index.objects.filter(function(row){return row.archiveConnections&&row.archiveConnections.length;}).length;$('archive-mode').textContent=index.persistence==='INDEXEDDB_DURABLE'?'ARCHIVE DURABLE':'EXPORT-ONLY MEMORY';$('archive-mode').classList.toggle('quiet',index.persistence==='INDEXEDDB_DURABLE');$('archive-count').textContent=index.objects.length;$('archive-summary').textContent=dormant+' valid dormant organ'+(dormant===1?'':'s')+' · '+connected+' Mirror archive acknowledgement'+(connected===1?'':'s')+' · '+index.events.length+' durable event'+(index.events.length===1?'':'s');$('archive-reason').textContent=index.persistence==='INDEXEDDB_DURABLE'?'IndexedDB persistence is active. Valid unselected organs remain in the dormant stash across reloads.':(index.reason||'Browser persistence is unavailable; export before closing.');const root=$('archive-list');root.replaceChildren();if(!index.objects.length){root.append(el('p','empty','No dormant organs stashed yet.'));return;}index.objects.forEach(function(row){const card=el('article','archive-row'),identity=el('div','archive-identity'),connection=row.archiveConnections&&row.archiveConnections[0];identity.append(el('strong',null,row.id+' · '+row.strategy),el('span','archive-meta',row.primaryPurposeCategory+' · '+row.classificationState));if(connection)identity.append(el('span','archive-meta','Mirror Organ Archive '+connection.targetVersion+' acknowledged · runtimeConnected false'));const stateLabel=connection?'DORMANT · MIRROR ARCHIVED':(row.selected?'DORMANT · SELECTED FOR REVIEW':'DORMANT · UNSELECTED'),button=el('button','secondary','Export dormant source handoff');button.type='button';button.addEventListener('click',async function(){try{const envelope=await state.archive.exportStashEnvelope(row.objectDigest);download(row.id+'-dormant-organ-handoff.json',JSON.stringify(envelope,null,2)+'\n','application/json');setNotice($('archive-verification'),'EXPORTED · dormant source handoff · no execution, admission, install, or registration','good');}catch(error){setNotice($('archive-verification'),'EXPORT REFUSED · '+error.message,'bad');}});card.append(identity,el('span','status-chip',stateLabel),el('code',null,row.objectDigest),button);root.append(card);});}
  async function generate(){if(!validateEditor()){switchView('brief');return;}if(!$('reviewed').checked){setNotice($('preview-status'),'HUMAN REVIEW REQUIRED · Confirm the structured preview before generation.','bad');return;}const pack=selectedPack(),run=Fabric.generateCandidates(state.intent,pack);state.run=run;state.comparison=Fabric.compareCandidates(run);for(const candidate of run.candidates)await state.archive.putCandidate(candidate);renderCandidates();renderComparison();await refreshArchive();switchView('candidates');if(window.AXMHub)AXMHub.log('Organ Fabric generated '+run.candidates.length+' detached candidates · '+run.failures.length+' rejected','info');}
  async function start(){
    if(!Fabric||!Zip||!ArchiveCtor)throw new Error('Deterministic Fabric dependencies are unavailable.');
    state.packs=await Promise.all(['software-workshop','games-entertainment','creative-production'].map(function(name){return fetch('/shared/deterministic-organ-fabric/field-packs/'+name+'.json').then(function(response){if(!response.ok)throw new Error('Could not load '+name);return response.json();});}));
    const select=$('field-pack');state.packs.forEach(function(pack){const option=document.createElement('option');option.value=pack.id;option.textContent=pack.title;select.append(option);});
    state.archive=await new ArchiveCtor().init();await refreshArchive();renderWeights();$('allowed-grammar').textContent=Fabric.ALLOWED_OPERATIONS.join(' · ');
    function updatePack(){const pack=selectedPack();$('pack-description').textContent=pack.description+' Unresolved judgments: '+pack.humanJudgments.join(' ');}
    select.addEventListener('change',updatePack);updatePack();
    document.querySelectorAll('.tab').forEach(function(tab){tab.addEventListener('click',function(){switchView(tab.dataset.view);});});
    $('load-starter').addEventListener('click',function(){const pack=selectedPack();showIntent(Fabric.sealIntent(pack.exampleIntent,pack),'Starter proof normalized. Review it before generation.');});
    $('preview-sentence').addEventListener('click',function(){const preview=Fabric.parseSentence($('sentence').value,state.packs,selectedPack().id);if(preview.draft)showIntent(preview.draft,'PREVIEW REQUIRED · '+preview.unresolved.map(function(row){return row.message;}).join(' '));else setNotice($('preview-status'),'STOPPED · '+preview.unresolved.map(function(row){return row.message;}).join(' '),'bad');});
    $('validate-intent').addEventListener('click',validateEditor);$('intent-json').addEventListener('input',function(){$('reviewed').checked=false;});$('brief-form').addEventListener('submit',function(event){event.preventDefault();generate().catch(reportError);});
    $('verify-archive').addEventListener('click',async function(){const result=await state.archive.verify();setNotice($('archive-verification'),result.ok?'PASS · '+result.objects+' objects and '+result.events+' events verified.':'FAIL · '+result.errors.map(function(row){return row.code;}).join(' · '),result.ok?'good':'bad');});
    $('export-archive').addEventListener('click',async function(){const pack=await state.archive.exportPack();download('axm-organ-archive-'+pack.packDigest.slice(7,19)+'.json',JSON.stringify(pack,null,2)+'\n','application/json');setNotice($('archive-verification'),'EXPORTED · '+pack.objects.length+' verified objects · detached JSON · installed false · registered false','good');});
    $('import-archive').addEventListener('change',async function(event){try{const file=event.target.files[0];if(!file)return;const result=await state.archive.importPack(JSON.parse(await file.text()));setNotice($('archive-verification'),result.status+' · '+result.objects+' verified objects · installed false · registered false','good');await refreshArchive();}catch(error){setNotice($('archive-verification'),'IMPORT REFUSED · '+error.message,'bad');}finally{event.target.value='';}});
    if(window.AXMHub){AXMHub.ready({id:'deterministic-organ-fabric',name:'Deterministic Organ Fabric',version:'v0.1',hubApiVersion:'1.0',permissions:['storage'],savesState:false});AXMHub.log('Deterministic Organ Fabric ready · no-AI path · EXPERIMENTAL','info');}
  }
  function reportError(error){console.error(error);setNotice($('preview-status'),'REFUSED · '+String(error&&error.message||error),'bad');if(window.AXMHub)AXMHub.error(String(error&&error.message||error));}
  start().catch(reportError);
}());
