(function(root,factory){const api=factory(root.AXMDeterministicOrganFabric,root);if(typeof window!=='undefined')root.AXMOrganBrowserArchive=api;})(typeof self!=='undefined'?self:this,function(Fabric,globalScope){
  'use strict';
  const DB_NAME='axm-deterministic-organ-archive-v1',DB_VERSION=2;
  function omit(value,key){const copy=JSON.parse(JSON.stringify(value));delete copy[key];return copy;}
  function requestResult(request){return new Promise(function(resolve,reject){request.onsuccess=function(){resolve(request.result);};request.onerror=function(){reject(request.error);};if('onblocked' in request)request.onblocked=function(){reject(new Error('IndexedDB upgrade is blocked by another open Organ Fabric view.'));};});}
  function transactionDone(transaction){return new Promise(function(resolve,reject){transaction.oncomplete=resolve;transaction.onerror=function(){reject(transaction.error);};transaction.onabort=function(){reject(transaction.error||new Error('Archive transaction aborted.'));};});}
  function BrowserArchive(){this.db=null;this.mode='INITIALIZING';this.memory={objects:new Map(),stash:new Map(),failures:new Map(),events:[]};this.reason=null;}
  BrowserArchive.prototype.init=async function(){
    if(!globalScope.indexedDB){this.mode='MEMORY_EXPORT_ONLY';this.reason='IndexedDB is unavailable.';return this;}
    try{
      const request=globalScope.indexedDB.open(DB_NAME,DB_VERSION);
      request.onupgradeneeded=function(){const db=request.result;if(!db.objectStoreNames.contains('objects'))db.createObjectStore('objects',{keyPath:'objectDigest'});if(!db.objectStoreNames.contains('stash'))db.createObjectStore('stash',{keyPath:'stashDigest'});if(!db.objectStoreNames.contains('failures'))db.createObjectStore('failures',{keyPath:'failureDigest'});if(!db.objectStoreNames.contains('events'))db.createObjectStore('events',{keyPath:'eventDigest'});if(!db.objectStoreNames.contains('meta'))db.createObjectStore('meta',{keyPath:'key'});};
      this.db=await requestResult(request);this.mode='INDEXEDDB_DURABLE';return this;
    }catch(error){this.mode='MEMORY_EXPORT_ONLY';this.reason=String(error&&error.message||error);return this;}
  };
  BrowserArchive.prototype.event=function(type,objectDigest,payload,sequence){const row={schema:'axm.organ-archive-event/v1',sequence:sequence,eventType:type,objectDigest:objectDigest,payload:payload||{},eventDigest:''};row.eventDigest=Fabric.digest(omit(row,'eventDigest'));return row;};
  BrowserArchive.prototype.putCandidate=async function(candidate){
    const verification=Fabric.verifyPackage(candidate);if(!verification.ok)throw new Error('Candidate package failed verification.');
    const object={schema:'axm.organ-archive-object/v1',objectDigest:candidate.package.packageDigest,objectKind:'candidate-package',status:'CURRENT',package:candidate},stash=Fabric.projectArchiveStash(candidate);
    if(this.mode!=='INDEXEDDB_DURABLE'){const existing=this.memory.objects.get(object.objectDigest),existingStash=this.memory.stash.get(stash.stashDigest),disposition=existing?'DEDUPLICATED':'MEMORY_ONLY';if(existing&&Fabric.canonicalJson(existing)!==Fabric.canonicalJson(object))throw new Error('DIGEST_COLLISION');if(existingStash&&Fabric.canonicalJson(existingStash)!==Fabric.canonicalJson(stash))throw new Error('DIGEST_COLLISION');this.memory.objects.set(object.objectDigest,object);this.memory.stash.set(stash.stashDigest,stash);if(disposition==='MEMORY_ONLY')this.memory.events.push(this.event('ARCHIVED',object.objectDigest,{persistence:'MEMORY_EXPORT_ONLY',stashDigest:stash.stashDigest,disposition:stash.archiveState.disposition,retentionPolicy:stash.archiveState.retentionPolicy,admissionStatus:stash.archiveState.admissionStatus,startupPolicy:stash.archiveState.startupPolicy},this.memory.events.length+1));return {disposition:disposition,objectDigest:object.objectDigest,stashDigest:stash.stashDigest,persistence:this.mode};}
    const tx=this.db.transaction(['objects','stash','events','meta'],'readwrite'),objects=tx.objectStore('objects'),stashStore=tx.objectStore('stash'),events=tx.objectStore('events'),meta=tx.objectStore('meta');
    const existing=await requestResult(objects.get(object.objectDigest));let disposition='DEDUPLICATED';
    if(existing){if(Fabric.canonicalJson(existing)!==Fabric.canonicalJson(object)){tx.abort();throw new Error('DIGEST_COLLISION');}}
    else{const sequenceRow=await requestResult(meta.get('nextSequence')),sequence=sequenceRow?sequenceRow.value:1,event=this.event('ARCHIVED',object.objectDigest,{status:'EXPERIMENTAL',stashDigest:stash.stashDigest,disposition:stash.archiveState.disposition,retentionPolicy:stash.archiveState.retentionPolicy,admissionStatus:stash.archiveState.admissionStatus,startupPolicy:stash.archiveState.startupPolicy},sequence);objects.add(object);events.add(event);meta.put({key:'nextSequence',value:sequence+1});disposition='CREATED';}
    const existingStash=await requestResult(stashStore.get(stash.stashDigest));if(existingStash&&Fabric.canonicalJson(existingStash)!==Fabric.canonicalJson(stash)){tx.abort();throw new Error('DIGEST_COLLISION');}if(!existingStash)stashStore.add(stash);
    await transactionDone(tx);return {disposition:disposition,objectDigest:object.objectDigest,stashDigest:stash.stashDigest,persistence:this.mode};
  };
  BrowserArchive.prototype.addSelection=async function(receipt){
    if(!receipt||receipt.schema!=='axm.organ-selection-receipt/v1'||receipt.selectionDigest!==Fabric.digest(omit(receipt,'selectionDigest'))||receipt.applied||receipt.installed||receipt.registered||receipt.staged||receipt.promoted||receipt.canonChanged||receipt.permissionsChanged)throw new Error('Selection receipt is invalid or exceeds authority ceiling.');
    if(this.mode!=='INDEXEDDB_DURABLE'){if(!this.memory.objects.has(receipt.packageDigest))throw new Error('Selected object is absent from archive.');const event=this.event('SELECTED',receipt.packageDigest,{selectionReceipt:receipt},this.memory.events.length+1);this.memory.events.push(event);return event;}
    const tx=this.db.transaction(['objects','events','meta'],'readwrite'),objects=tx.objectStore('objects'),events=tx.objectStore('events'),meta=tx.objectStore('meta');
    const object=await requestResult(objects.get(receipt.packageDigest));if(!object){tx.abort();throw new Error('Selected object is absent from archive.');}
    const sequenceRow=await requestResult(meta.get('nextSequence')),sequence=sequenceRow?sequenceRow.value:1,event=this.event('SELECTED',receipt.packageDigest,{selectionReceipt:receipt},sequence);events.add(event);meta.put({key:'nextSequence',value:sequence+1});await transactionDone(tx);return event;
  };
  BrowserArchive.prototype.readAll=async function(storeName){if(this.mode!=='INDEXEDDB_DURABLE'){if(storeName==='objects')return Array.from(this.memory.objects.values());if(storeName==='stash')return Array.from(this.memory.stash.values());if(storeName==='failures')return Array.from(this.memory.failures.values());return this.memory.events.slice();}const tx=this.db.transaction([storeName],'readonly'),rows=await requestResult(tx.objectStore(storeName).getAll());await transactionDone(tx);return rows;};
  BrowserArchive.prototype.list=async function(){const objects=await this.readAll('objects'),storedStash=await this.readAll('stash'),events=await this.readAll('events'),stashByPackage={};storedStash.forEach(function(row){stashByPackage[row.packageDigest]=row;});const selected={},connections={};events.forEach(function(row){if(row.eventType==='SELECTED')selected[row.objectDigest]=true;if(row.eventType==='ARCHIVE_CONNECTED'&&row.payload&&row.payload.connectionReceipt){const receipt=row.payload.connectionReceipt;if(!connections[row.objectDigest])connections[row.objectDigest]=[];if(!connections[row.objectDigest].some(function(item){return item.receiptDigest===receipt.receiptDigest;}))connections[row.objectDigest].push({targetModuleId:receipt.receiver.targetModuleId,targetVersion:receipt.receiver.targetVersion,receiptDigest:receipt.receiptDigest,archiveObjectId:receipt.receiver.archiveObjectId,sourcePath:receipt.sourceArtifact.path,state:receipt.outcome,runtimeConnected:false});}});const index={schema:'axm.organ-archive-index/v1',derived:true,persistence:this.mode,reason:this.reason,objects:objects.map(function(row){const stash=stashByPackage[row.objectDigest]||Fabric.projectArchiveStash(row.package);return {objectDigest:row.objectDigest,status:row.status,id:row.package.package.id,strategy:row.package.definition.strategy,score:row.package.evaluation.metrics.score,stashDigest:stash.stashDigest,archiveDisposition:stash.archiveState.disposition,retentionPolicy:stash.archiveState.retentionPolicy,admissionStatus:stash.archiveState.admissionStatus,startupPolicy:stash.archiveState.startupPolicy,implementationStatus:selected[row.objectDigest]?'SELECTED_FOR_IMPLEMENTATION_REVIEW':stash.archiveState.implementationStatus,selected:Boolean(selected[row.objectDigest]),primaryPurposeCategory:stash.purposeClassification.primaryPurposeCategory,useFields:stash.purposeClassification.useFields,functionalRoles:stash.purposeClassification.functionalRoles,classificationState:stash.purposeClassification.state,archiveConnections:(connections[row.objectDigest]||[]).slice().sort(function(a,b){return a.receiptDigest.localeCompare(b.receiptDigest);})};}).sort(function(a,b){return a.objectDigest.localeCompare(b.objectDigest);}),failures:[],events:events.slice().sort(function(a,b){return a.sequence-b.sequence;}).map(function(row){return {sequence:row.sequence,eventType:row.eventType,objectDigest:row.objectDigest,eventDigest:row.eventDigest};}),indexDigest:''};index.indexDigest=Fabric.digest(omit(index,'indexDigest'));return index;};
  BrowserArchive.prototype.verify=async function(){const objects=await this.readAll('objects'),storedStash=await this.readAll('stash'),events=await this.readAll('events'),errors=[],objectByDigest={};objects.forEach(function(row){objectByDigest[row.objectDigest]=row.package;const check=Fabric.verifyPackage(row.package);if(!check.ok||row.objectDigest!==row.package.package.packageDigest)errors.push({code:'ARCHIVE_OBJECT_INVALID',objectDigest:row.objectDigest,details:check.errors});});storedStash.forEach(function(row){const check=Fabric.verifyArchiveStashProjection(row,objectByDigest[row.packageDigest]);if(!check.ok)errors.push({code:'STASH_PROJECTION_INVALID',stashDigest:row.stashDigest,details:check.errors});});events.forEach(function(row){if(row.eventDigest!==Fabric.digest(omit(row,'eventDigest')))errors.push({code:'ARCHIVE_EVENT_INVALID',eventDigest:row.eventDigest});if(row.eventType==='ARCHIVE_CONNECTED'){const receipt=row.payload&&row.payload.connectionReceipt,candidate=objectByDigest[row.objectDigest],check=Fabric.verifyArchiveConnectionReceipt(receipt,candidate);if(!check.ok||!candidate||receipt.packageDigest!==row.objectDigest)errors.push({code:'ARCHIVE_CONNECTION_RECEIPT_INVALID',eventDigest:row.eventDigest,details:check.errors});}});return {schema:'axm.organ-archive-verification/v1',ok:errors.length===0,errors:errors,objects:objects.length,stash:storedStash.length,events:events.length,persistence:this.mode};};
  BrowserArchive.prototype.exportPack=async function(){const objects=await this.readAll('objects'),stash=await this.readAll('stash'),byPackage={};stash.forEach(function(row){byPackage[row.packageDigest]=true;});objects.forEach(function(row){if(!byPackage[row.objectDigest])stash.push(Fabric.projectArchiveStash(row.package));});const portable={schema:'axm.organ-archive-pack/v1',objects:objects,stash:stash,failures:await this.readAll('failures'),events:await this.readAll('events'),packDigest:''};portable.objects.sort(function(a,b){return a.objectDigest.localeCompare(b.objectDigest);});portable.stash.sort(function(a,b){return a.stashDigest.localeCompare(b.stashDigest);});portable.failures.sort(function(a,b){return a.failureDigest.localeCompare(b.failureDigest);});portable.events.sort(function(a,b){return a.sequence-b.sequence;});portable.packDigest=Fabric.digest(omit(portable,'packDigest'));return portable;};
  BrowserArchive.prototype.importPack=async function(portable){
    if(!portable||portable.schema!=='axm.organ-archive-pack/v1'||portable.packDigest!==Fabric.digest(omit(portable,'packDigest')))throw new Error('Archive pack verification failed.');
    const portableStash=Array.isArray(portable.stash)?portable.stash:[];for(const object of portable.objects){const check=Fabric.verifyPackage(object.package);if(!check.ok||object.objectDigest!==object.package.package.packageDigest)throw new Error('Imported object failed package verification.');const stash=portableStash.find(function(row){return row.packageDigest===object.objectDigest;})||Fabric.projectArchiveStash(object.package);if(!Fabric.verifyArchiveStashProjection(stash,object.package).ok)throw new Error('Imported dormant stash projection failed verification.');}
    for(const event of portable.events){if(event.eventDigest!==Fabric.digest(omit(event,'eventDigest')))throw new Error('Imported event digest failed verification.');if(event.eventType==='ARCHIVE_CONNECTED'){const receipt=event.payload&&event.payload.connectionReceipt,object=portable.objects.find(function(row){return row.objectDigest===event.objectDigest;}),check=Fabric.verifyArchiveConnectionReceipt(receipt,object&&object.package);if(!check.ok||!object||receipt.packageDigest!==event.objectDigest)throw new Error('Imported archive connection receipt failed verification.');}}
    if(this.mode!=='INDEXEDDB_DURABLE'){portable.objects.forEach((row)=>{this.memory.objects.set(row.objectDigest,row);const stash=portableStash.find((item)=>item.packageDigest===row.objectDigest)||Fabric.projectArchiveStash(row.package);this.memory.stash.set(stash.stashDigest,stash);});portable.failures.forEach((row)=>this.memory.failures.set(row.failureDigest,row));portable.events.forEach((row)=>{if(!this.memory.events.some((x)=>x.eventDigest===row.eventDigest))this.memory.events.push(row);});return {status:'MEMORY_EXPORT_ONLY',objects:portable.objects.length,installed:false,registered:false};}
    const tx=this.db.transaction(['objects','stash','failures','events','meta'],'readwrite'),objects=tx.objectStore('objects'),stashStore=tx.objectStore('stash'),failures=tx.objectStore('failures'),events=tx.objectStore('events'),meta=tx.objectStore('meta');let maxSequence=0;
    for(const row of portable.objects){const existing=await requestResult(objects.get(row.objectDigest));if(existing&&Fabric.canonicalJson(existing)!==Fabric.canonicalJson(row)){tx.abort();throw new Error('DIGEST_COLLISION');}if(!existing)objects.add(row);}
    for(const object of portable.objects){const row=portableStash.find(function(item){return item.packageDigest===object.objectDigest;})||Fabric.projectArchiveStash(object.package),existing=await requestResult(stashStore.get(row.stashDigest));if(existing&&Fabric.canonicalJson(existing)!==Fabric.canonicalJson(row)){tx.abort();throw new Error('DIGEST_COLLISION');}if(!existing)stashStore.add(row);}
    for(const row of portable.failures){const existing=await requestResult(failures.get(row.failureDigest));if(existing&&Fabric.canonicalJson(existing)!==Fabric.canonicalJson(row)){tx.abort();throw new Error('DIGEST_COLLISION');}if(!existing)failures.add(row);}
    for(const row of portable.events){const existing=await requestResult(events.get(row.eventDigest));if(existing&&Fabric.canonicalJson(existing)!==Fabric.canonicalJson(row)){tx.abort();throw new Error('DIGEST_COLLISION');}if(!existing)events.add(row);maxSequence=Math.max(maxSequence,row.sequence);}
    const sequenceRow=await requestResult(meta.get('nextSequence'));meta.put({key:'nextSequence',value:Math.max(maxSequence+1,sequenceRow?sequenceRow.value:1)});await transactionDone(tx);return {status:'IMPORTED',objects:portable.objects.length,installed:false,registered:false};
  };
  BrowserArchive.prototype.exportStashEnvelope=async function(packageDigest){const objects=await this.readAll('objects'),object=objects.find(function(row){return row.objectDigest===packageDigest;});if(!object)throw new Error('Dormant stash export package is absent.');const rows=await this.readAll('stash'),stash=rows.find(function(row){return row.packageDigest===packageDigest;})||Fabric.projectArchiveStash(object.package);return Fabric.buildArchiveStashEnvelope(object.package,stash);};
  return {BrowserArchive:BrowserArchive,DB_NAME:DB_NAME};
});
