export const KIT_SCHEMA='axm.modular-environment-kit/v1';
const DIRS={N:[0,-1],E:[1,0],S:[0,1],W:[-1,0]},opposite={N:'S',E:'W',S:'N',W:'E'},order=['N','E','S','W'];
const definitions=[
  ['avenue','North Avenue',(x,y)=>x===5],
  ['cross','Civic Cross',(x,y)=>x===5||y===3],
  ['ring','Courtyard Ring',(x,y)=>(x>=2&&x<=9&&(y===1||y===6))||(y>=1&&y<=6&&(x===2||x===9))],
  ['twin','Twin Boulevards',(x,y)=>x===3||x===8||y===4&&x>=3&&x<=8],
  ['market','Market Grid',(x,y)=>[2,6,10].includes(x)||[2,5].includes(y)],
  ['waterfront','Waterfront Branches',(x,y)=>y===5||x===2&&y<=5||x===9&&y>=5],
  ['arcade','Arcade Court',(x,y)=>(x>=3&&x<=8&&(y===2||y===5))||(y>=2&&y<=5&&(x===3||x===8))||x===5&&y<=2],
  ['junction','T Junction',(x,y)=>x===6||y===2&&x>=1&&x<=10],
  ['zigzag','Zigzag Ward',(x,y)=>y===1&&x<=4||x===4&&y<=4||y===4&&x>=4&&x<=9||x===9&&y>=4],
  ['old-town','Old Town',(x,y)=>x===2||y===2&&x>=2&&x<=9||x===9&&y>=2||y===6&&x>=5&&x<=9||x===5&&y>=4&&y<=6]
];
function key(x,y){return`${x},${y}`}function sameSet(a,b){return a.length===b.length&&a.every(value=>b.includes(value))}function rotateDir(direction,turns){return order[(order.indexOf(direction)+turns)%4]}function chooseRoad(connectors){const catalog=[['road-straight',['N','S']],['road-bend-square',['N','E']],['road-crossroad',['N','E','S','W']],['road-intersection',['N','E','S']],['road-end',['N']]];for(const[id,base]of catalog)for(let rotation=0;rotation<4;rotation++){const rotated=base.map(direction=>rotateDir(direction,rotation));if(sameSet(connectors,rotated))return{id,rotation:rotation*90}}throw new Error(`No road piece for ${connectors.join('')||'isolated cell'}`)}
function roadSet(rule,width,height){const set=new Set();for(let y=0;y<height;y++)for(let x=0;x<width;x++)if(rule(x,y))set.add(key(x,y));return set}
function buildLayout(definition,index,width=12,height=8){const[id,name,rule]=definition,roads=roadSet(rule,width,height),cells=[];for(let y=0;y<height;y++)for(let x=0;x<width;x++){const here=key(x,y);if(roads.has(here)){const connectors=order.filter(direction=>{const[dx,dy]=DIRS[direction];return roads.has(key(x+dx,y+dy))}),piece=chooseRoad(connectors);cells.push({x,y,kind:'road',partId:piece.id,rotation:piece.rotation,connectors,position:[x,0,y],scale:[1,1,1],manualOffset:false,sockets:connectors.map(direction=>({id:`road.${direction}`,direction,local:direction==='N'?[0,0,-.5]:direction==='E'?[.5,0,0]:direction==='S'?[0,0,.5]:[-.5,0,0]}))});continue}const adjacent=order.some(direction=>{const[dx,dy]=DIRS[direction];return roads.has(key(x+dx,y+dy))}),hash=(index+1)*97+x*31+y*17;if(adjacent&&hash%4!==0){const recipe=hash%3===0?'shopfront':hash%3===1?'apartment':'workshop',partId=hash%2?'building-b':'building-g';cells.push({x,y,kind:'building',partId,recipe,rotation:(hash%4)*90,position:[x,0,y],scale:[1,1,1],manualOffset:false,sockets:[{id:'door.front',local:[0,0,.5]},{id:'roof.center',local:[0,1,0]},{id:'interior.origin',local:[0,0,0]},{id:'prop.front',local:[.3,0,.55]}]})}else{const prop=hash%11===0?['detail-bench','detail-dumpster-closed','detail-light-traffic'][hash%3]:null;cells.push({x,y,kind:'ground',partId:'grass',rotation:0,position:[x,0,y],scale:[1,1,1],manualOffset:false,prop:prop?{partId:prop,socket:'ground.detail',local:[.22,0,.18],rotation:(hash%4)*90}:null})}}const signature=cells.filter(cell=>cell.kind==='road').map(cell=>`${cell.x}.${cell.y}.${cell.partId}.${cell.rotation}`).join('|');return{id,name,width,height,cells,signature,review:{gap:'machine-pass',visualCoherence:'live-review-required'}}}
export function buildEnvironmentKit(sources){const sourceById=Object.fromEntries(sources.map(source=>[source.id,source]));const layouts=definitions.map((definition,index)=>buildLayout(definition,index));const families=[{id:'shopfront',floor:'scaffolding-floor',facades:['wall-a-door','wall-a-window','wall-a-flat','wall-a-window'],roof:'wall-a-roof',door:'door-type-a',interiorSocket:'interior.origin',damage:{intact:'wall-a-flat',damaged:'wall-broken-type-a'}},{id:'apartment',floor:'scaffolding-floor',facades:['wall-a-window','wall-a-window','wall-a-flat','wall-a-flat'],roof:'roof-metal-type-a',door:'door-type-a',interiorSocket:'interior.origin',damage:{intact:'wall-a-flat',damaged:'wall-broken-type-a'}},{id:'workshop',floor:'scaffolding-floor',facades:['wall-a-door','wall-a-flat','wall-a-flat','wall-a-window'],roof:'roof-metal-type-a',door:'door-type-a',interiorSocket:'interior.origin',damage:{intact:'detail-barrier-strong-damaged',damaged:'wall-broken-type-a'}}];const instances=layouts.flatMap(layout=>layout.cells.flatMap(cell=>[cell.partId,cell.prop?.partId].filter(Boolean))),used=new Set(instances);const sourceTests=sources.map(source=>({id:source.id,digestBound:source.sha256?.length===64,pivotInside:source.bounds.minimum.every((value,index)=>source.pivot[index]>=value-1e-6&&source.pivot[index]<=source.bounds.maximum[index]+1e-6),grounded:Math.abs(source.bounds.minimum[1])<1e-5,boundsFinite:[...source.bounds.minimum,...source.bounds.maximum,...source.bounds.size].every(Number.isFinite),fitsCell:source.bounds.size[0]<=1.2&&source.bounds.size[2]<=1.2}));const bundle={schema:KIT_SCHEMA,id:'axm-street-kit-01',grid:{unit:1,rotationStep:90,origin:'cell-center'},sources,families,layouts,assemblyRules:{snap:'integer-xz',connectorTolerance:1e-9,rotation:[0,90,180,270],scale:[1,1,1],manualOffsets:'forbidden'},metrics:{sourceParts:sources.length,layoutCount:layouts.length,totalPrimaryInstances:layouts.reduce((sum,layout)=>sum+layout.cells.length,0),referencedInstances:instances.length,usedSourceParts:used.size,reuseRatio:1-used.size/instances.length,uniqueLayoutSignatures:new Set(layouts.map(layout=>layout.signature)).size},sourceTests,humanReview:{required:true,approved:false,scope:['district silhouette','facade rhythm','prop density','damage readability']}};for(const family of families)for(const id of[family.floor,...family.facades,family.roof,family.door,family.damage.intact,family.damage.damaged])if(!sourceById[id])throw new Error(`Missing family source ${id}`);return bundle}
export async function sealKit(bundle){const sort=value=>Array.isArray(value)?value.map(sort):value&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().map(key=>[key,sort(value[key])])):value,bytes=new TextEncoder().encode(JSON.stringify(sort(bundle))),hash=await globalThis.crypto.subtle.digest('SHA-256',bytes);return{...bundle,receiptSha256:Array.from(new Uint8Array(hash),b=>b.toString(16).padStart(2,'0')).join('').toUpperCase()}}
export const connectorMath={DIRS,opposite,key};
