#!/usr/bin/env node
'use strict';
const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');
const root = __dirname;
const shared = require('../../shared/visual-fx/fx-blocks');
assert.equal(Object.keys(shared.Blocks).length, 15);
['index.html','styles.css','app.js','manifest.json','module.contract.json','shapeable-block-pack.json','assets/gallery.png'].forEach(file => assert.ok(fs.existsSync(path.join(root,file)), 'missing '+file));
const manifest = JSON.parse(fs.readFileSync(path.join(root,'manifest.json'),'utf8'));
const contract = JSON.parse(fs.readFileSync(path.join(root,'module.contract.json'),'utf8'));
const pack = JSON.parse(fs.readFileSync(path.join(root,'shapeable-block-pack.json'),'utf8'));
assert.equal(manifest.id,'fx-blocks');
assert.equal(contract.id,'fx-blocks');
assert.equal(pack.schema,'axm.shapeable.block-pack');
assert.equal(pack.blocks.length,15);
assert.equal(new Set(pack.blocks.map(item=>item.type)).size,15);
assert.ok(pack.blocks.every(item=>item.layer==='visual' && item.type.startsWith(pack.id+'--')));
global.window = {};
require('../shapeable-builder/model');
const Builder = global.window.AXMBuilderModel;
const validation = Builder.validateBlockPack(pack);
assert.equal(validation.valid,true,(validation.errors||[]).join('; '));
delete global.window;
const html = fs.readFileSync(path.join(root,'index.html'),'utf8');
const app = fs.readFileSync(path.join(root,'app.js'),'utf8');
assert.match(html,/shared\/visual-fx\/fx-blocks\.js/);
assert.match(app,/automatic_apply: false/);
assert.doesNotMatch(app,/fetch\s*\(/);
console.log('fx-blocks tool selftest: PASS - 15 effects - valid Shapeable pack - no network - explicit export only');
