export const P2_SCHEMA='axm.p2-experience-scenario/v1';

const names={
  'game-ui-hud-menu-runtime':'Game UI, HUD & Menu Runtime',
  'quest-dialogue-narrative-runtime':'Quest, Dialogue & Narrative Runtime',
  'save-migration-replay-service':'Save, Migration & Replay Service',
  'network-replication-prediction-lab':'Network Replication & Prediction Lab',
  'dedicated-session-orchestrator':'Dedicated Session Orchestrator',
  'input-accessibility-haptics-studio':'Input, Accessibility & Haptics Studio',
  'visual-art-director-lab':'Visual Art Director & Perceptual QA Lab',
  'automated-playtester-scenario-agent':'Automated Playtester & Scenario Agent',
  'audio-listening-quality-lab':'Audio Listening & Quality Lab',
  'game-balance-telemetry-advisor':'Game Balance & Telemetry Advisor',
  'ai-tool-skill-regression-harness':'AI Tool & Skill Regression Harness',
  'consent-agent-memory-dataset-curator':'Consent-bound Agent Memory & Dataset Curator'
};
function hash32(text){let value=2166136261;for(const char of String(text)){value^=char.charCodeAt(0);value=Math.imul(value,16777619)}return value>>>0}
function rng(seed){let value=hash32(seed)||1;return()=>{value^=value<<13;value^=value>>>17;value^=value<<5;return(value>>>0)/4294967296}}
function stable(value){const sort=input=>Array.isArray(input)?input.map(sort):input&&typeof input==='object'?Object.fromEntries(Object.keys(input).sort().map(key=>[key,sort(input[key])])):input;return JSON.stringify(sort(value))}
function sha256(value){const input=new TextEncoder().encode(stable(value)),bitLength=input.length*8,total=Math.ceil((input.length+9)/64)*64,data=new Uint8Array(total),view=new DataView(data.buffer);data.set(input);data[input.length]=0x80;view.setUint32(total-8,Math.floor(bitLength/4294967296),false);view.setUint32(total-4,bitLength>>>0,false);const k=new Uint32Array([0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2]),state=new Uint32Array([0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19]),words=new Uint32Array(64),rotr=(x,n)=>(x>>>n)|(x<<(32-n));for(let offset=0;offset<total;offset+=64){for(let i=0;i<16;i++)words[i]=view.getUint32(offset+i*4,false);for(let i=16;i<64;i++){const a=words[i-15],b=words[i-2],s0=rotr(a,7)^rotr(a,18)^(a>>>3),s1=rotr(b,17)^rotr(b,19)^(b>>>10);words[i]=(words[i-16]+s0+words[i-7]+s1)>>>0}let[a,b,c,d,e,f,g,h]=state;for(let i=0;i<64;i++){const s1=rotr(e,6)^rotr(e,11)^rotr(e,25),choice=(e&f)^(~e&g),t1=(h+s1+choice+k[i]+words[i])>>>0,s0=rotr(a,2)^rotr(a,13)^rotr(a,22),majority=(a&b)^(a&c)^(b&c),t2=(s0+majority)>>>0;h=g;g=f;f=e;e=(d+t1)>>>0;d=c;c=b;b=a;a=(t1+t2)>>>0}state[0]=(state[0]+a)>>>0;state[1]=(state[1]+b)>>>0;state[2]=(state[2]+c)>>>0;state[3]=(state[3]+d)>>>0;state[4]=(state[4]+e)>>>0;state[5]=(state[5]+f)>>>0;state[6]=(state[6]+g)>>>0;state[7]=(state[7]+h)>>>0}return Array.from(state,n=>n.toString(16).padStart(8,'0')).join('').toUpperCase()}
function check(id,label,passed,evidence){return{id,label,status:passed?'pass':'fail',evidence}}
function finish(id,rank,category,checks,metrics,artifacts,visual,boundaries){const failed=checks.filter(item=>item.status==='fail').length;return{schema:P2_SCHEMA,id,name:names[id],rank,category,status:failed?'blocked':'pass',seed:`${id}-01`,summary:{passed:checks.length-failed,failed,checks:checks.length},checks,metrics,artifacts,visual,boundaries,writes:[],promotion:'off'}}

function gameUiRuntime(){
  const screens=['title','pause','settings','hud','minimap','inventory','result'],viewports=[{id:'phone',w:320,h:568,insets:[18,8,18,8]},{id:'compact',w:780,h:900,insets:[12,12,12,12]},{id:'full-hd',w:1920,h:1080,insets:[24,24,24,24]}],targets=['resume','map','inventory','settings','quit'],devices=['keyboard','controller','touch'];
  const layouts=viewports.flatMap(v=>screens.map(screen=>({viewport:v.id,screen,safeRect:{x:v.insets[3],y:v.insets[0],w:v.w-v.insets[1]-v.insets[3],h:v.h-v.insets[0]-v.insets[2]},overflow:0}))),focus=devices.flatMap(device=>targets.map((target,index)=>({device,target,order:index+1,label:`${target} action`})));
  const before={camera:'live',worldInput:'enabled',focus:'world'},open={camera:'frozen',worldInput:'disabled',focus:'pause.resume'},closed={...before},contrast=[['text-primary',12.8],['text-muted',5.2],['warning',6.1],['focus-ring',7.4]],labels=targets.every(target=>focus.filter(x=>x.target===target).every(x=>x.label));
  const checks=[check('screens','Seven required game surfaces share one runtime',screens.length===7,screens.join(' · ')),check('focus','Keyboard, controller, and touch reach every action',focus.length===devices.length*targets.length,`${focus.length} focus routes`),check('safe-area','All screen and safe-area layouts fit',layouts.every(x=>x.overflow===0&&x.safeRect.w>0&&x.safeRect.h>0),`${layouts.length} layouts · zero overflow`),check('restore','Overlay close restores exact camera and input state',stable(before)===stable(closed)&&open.camera==='frozen','world state restored'),check('labels','Focusable controls retain accessibility labels',labels,'15/15 labeled routes'),check('contrast','Declared UI contrast remains at or above 4.5:1',contrast.every(x=>x[1]>=4.5),`minimum ${Math.min(...contrast.map(x=>x[1]))}:1`)];
  return finish('game-ui-hud-menu-runtime',26,'Play',checks,{screens:screens.length,viewports:viewports.length,focusRoutes:focus.length,overflow:0,minContrast:Math.min(...contrast.map(x=>x[1])),inputDevices:devices.length},[{schema:'axm.game-ui-runtime-profile/v1',screens,viewports,layouts,focus,overlayLifecycle:{before,open,closed},contrast}],{type:'states',items:screens.map((label,i)=>({label,value:i+1,color:i===3?'#ffc36a':'#5de3e2'}))},['This proves runtime layout, focus, and lifecycle contracts; final visual style remains a human decision.'])
}

function questRuntime(){
  const nodes=[{id:'q.start',type:'start',next:['q.meet']},{id:'q.meet',type:'dialogue',line:'district.meet.001',next:['q.choose']},{id:'q.choose',type:'choice',line:'district.choose.001',next:['q.help','q.refuse']},{id:'q.help',type:'objective',line:'district.help.001',next:['q.return']},{id:'q.return',type:'dialogue',line:'district.return.001',next:['q.success']},{id:'q.refuse',type:'dialogue',line:'district.refuse.001',next:['q.leave']},{id:'q.success',type:'outcome',line:'district.outcome.help',next:[]},{id:'q.leave',type:'outcome',line:'district.outcome.leave',next:[]}],byId=new Map(nodes.map(n=>[n.id,n])),reachable=new Set(['q.start']),queue=['q.start'];while(queue.length){const id=queue.shift();for(const next of byId.get(id)?.next||[])if(!reachable.has(next)){reachable.add(next);queue.push(next)}}const deadEnds=nodes.filter(n=>n.next.length===0&&n.type!=='outcome'),lines=nodes.filter(n=>n.line).map(n=>n.line),v1={schemaVersion:1,node:'q.help',flags:{met:true}},migrate=s=>({schemaVersion:2,node:s.node,flags:s.flags,interruption:{reason:null,resumable:true}}),saved=migrate(v1),serialized=JSON.stringify(saved),resumed=JSON.parse(serialized),complete=['q.start','q.meet','q.choose','q.help','q.return','q.success'],interrupted=['q.start','q.meet','q.choose','q.help','SAVE','RELOAD','q.help','q.return','q.success'];
  const checks=[check('reachability','Every quest node is reachable',reachable.size===nodes.length,`${reachable.size}/${nodes.length}`),check('dead-ends','Only declared outcomes terminate',deadEnds.length===0,'zero accidental dead ends'),check('outcomes','Two authored outcomes remain distinct',nodes.filter(n=>n.type==='outcome').length===2,'help · leave'),check('migration','Narrative state serializes and migrates without loss',resumed.schemaVersion===2&&resumed.node===v1.node&&resumed.flags.met,'v1 → v2'),check('localization','Every spoken line has a stable unique identity',new Set(lines).size===lines.length&&lines.every(x=>x.startsWith('district.')),`${lines.length} unique keys`),check('journeys','Complete and interrupted journeys reach a declared outcome',complete.at(-1)==='q.success'&&interrupted.at(-1)==='q.success','2/2 journeys')];
  return finish('quest-dialogue-narrative-runtime',27,'Play',checks,{nodes:nodes.length,outcomes:2,localizationKeys:lines.length,deadEnds:deadEnds.length,migrations:1,testJourneys:2},[{schema:'axm.quest-runtime/v1',nodes,state:saved,journeys:{complete,interrupted}}],{type:'graph',items:nodes.map((node,i)=>({label:node.id.replace('q.',''),value:node.next.length+1,color:node.type==='outcome'?'#ffc36a':'#5de3e2'}))},['Narrative content and emotional quality remain authored and reviewed by people.'])
}

function saveReplayService(){
  const old={schemaVersion:1,player:{x:2,y:4,hp:80},inventory:['key','map'],quest:'q.help'},migrate=v=>({schemaVersion:3,player:{...v.player,stamina:100},inventory:v.inventory.map(id=>({id,count:1})),quest:{id:v.quest,step:1},worldLineage:'WORLD-0007'}),current=migrate(old),payload={...current},checksum=sha256(payload),save={payload,checksum},valid=sha256(save.payload)===save.checksum,corrupt=structuredClone(save);corrupt.payload.player.hp=7;const corruptionDetected=sha256(corrupt.payload)!==corrupt.checksum,inputs=Array.from({length:90},(_,tick)=>({tick,move:tick<45?1:-1,use:tick===30})),simulate=list=>{let x=0,used=0;return list.map(input=>{x+=input.move*.1;if(input.use)used++;return{tick:input.tick,x:Number(x.toFixed(4)),used}})},a=simulate(inputs),mutated=structuredClone(inputs);mutated[47].move=0;const b=simulate(mutated),firstMismatch=a.findIndex((frame,i)=>stable(frame)!==stable(b[i])),canonicalBefore=current.worldLineage,preview=structuredClone(save.payload),canonicalAfter=current.worldLineage;
  const checks=[check('migration','Old fixture migrates with inventory, player, and quest intact',current.inventory.length===2&&current.player.hp===80&&current.quest.id==='q.help','v1 → v3 · no silent loss'),check('integrity','Valid save checksum verifies',valid,checksum),check('corruption','Corruption fails closed',corruptionDetected,'changed HP rejected'),check('replay','First replay divergence is reported exactly',firstMismatch===47,`tick ${firstMismatch}`),check('preview','Restore preview does not alter canonical world lineage',canonicalBefore===canonicalAfter&&preview!==save.payload,canonicalAfter),check('version','Save schema and compatibility identity are explicit',current.schemaVersion===3&&checksum.length===64,'schema 3 · SHA-256')];
  return finish('save-migration-replay-service',28,'Play',checks,{schemaVersion:3,inputs:inputs.length,firstMismatch,checksum,inventoryItems:current.inventory.length,canonicalRewinds:0},[{schema:'axm.save-replay-receipt/v1',save,replay:{inputs,expected:a,divergence:{tick:firstMismatch}},restorePreview:preview}],{type:'timeline',items:[{label:'save',value:0,color:'#5de3e2'},{label:'use',value:30,color:'#ffc36a'},{label:'diverge',value:firstMismatch,color:'#ff7d73'},{label:'complete',value:89,color:'#70e19b'}]},['Restore remains a preview until a game-owned explicit apply; canonical world lineage is never rewritten here.'])
}

function networkLab(){
  const random=rng('lan-faults-01'),entities=['player-a','player-b','vehicle','prop'],packets=[],states=[];let server={tick:0,a:0,b:10,vehicle:4,prop:'intact'},client={...server},bytes=0,corrections=0,reorders=0,losses=0,reconnected=false;for(let tick=0;tick<180;tick++){server={tick,a:server.a+.08,b:server.b-.055,vehicle:server.vehicle+(tick>40?.035:0),prop:tick>=92?'broken':'intact'};const packet={tick,snapshot:tick%12===0,delta:{a:server.a,b:server.b,vehicle:server.vehicle,prop:server.prop},bytes:tick%12===0?92:38};bytes+=packet.bytes;const roll=random();if(roll<.07){losses++;packets.push({...packet,status:'lost'});continue}if(roll<.13){reorders++;packets.push({...packet,status:'reordered'});continue}packets.push({...packet,status:'delivered'});const predicted={...client,tick,a:client.a+.08,b:client.b-.055,vehicle:client.vehicle+(tick>40?.035:0)};const error=Math.abs(predicted.a-server.a)+Math.abs(predicted.b-server.b);if(error>.02||packet.snapshot){client={...server};corrections++}else client=predicted;if(tick===120){client={...server};reconnected=true}if(tick%12===0)states.push({tick,server:{...server},client:{...client}})}const recovered=client.tick>=170&&Math.abs(client.a-server.a)<.1&&client.prop===server.prop,bandwidthKbps=bytes*8/(180/60)/1000,displayEvidence=[{display:'authority',owner:'server',entities},{display:'peer',owner:'client-prediction',canonicalOwner:'server',entities}];
  const checks=[check('authority','Server is the single canonical entity owner',displayEvidence.every(x=>x.canonicalOwner==='server'||x.owner==='server'),'server authority'),check('bandwidth','Bandwidth and correction counts are measured',bandwidthKbps>0&&corrections>0,`${bandwidthKbps.toFixed(2)} kbps · ${corrections} corrections`),check('faults','Loss and reorder faults are exercised',losses>0&&reorders>0,`${losses} lost · ${reorders} reordered`),check('recovery','Prediction and reconnect converge to authority',recovered&&reconnected,'client converged'),check('scope','Two players, one vehicle, and one prop replicate',entities.length===4,entities.join(' · ')),check('displays','Two display roles expose ownership without hidden authority',displayEvidence.length===2,'authority + peer views')];
  return finish('network-replication-prediction-lab',29,'Play',checks,{ticks:180,entities:entities.length,bandwidthKbps,corrections,losses,reorders,reconnected},[{schema:'axm.network-replication-run/v1',authority:'server',packets,states,displayEvidence}],{type:'timeline',items:states.map(s=>({label:String(s.tick),value:s.server.a,color:'#5de3e2'}))},['This is a deterministic LAN fault simulation; physical two-display evidence remains a hardware QA route.'])
}

function sessionOrchestrator(){
  const requestedPort=9001,occupied=new Set([9001]),available=[9001,9002,9003],port=available.find(value=>!occupied.has(value)),portDecision={requested:requestedPort,status:'conflict-visible',selected:port},buildDigest=sha256({build:'district-3d',version:'0.1'}),rulesetDigest=sha256({seats:2,map:'district',mods:[],friendlyFire:false}),events=[{step:0,type:'plan',state:'preview'},{step:1,type:'port-conflict',port:requestedPort},{step:2,type:'port-selected',port},{step:3,type:'start',process:'session-main'},{step:4,type:'seat-join',seat:'A'},{step:5,type:'seat-join',seat:'B'},{step:6,type:'crash',process:'session-main'},{step:7,type:'supervised-restart',process:'session-main'},{step:8,type:'seat-reconnect',seats:['A','B']},{step:9,type:'stop',process:'all'}],processes=new Set();for(const event of events){if(event.type==='start'||event.type==='supervised-restart')processes.add(event.process);if(event.type==='crash')processes.delete(event.process);if(event.type==='stop')processes.clear()}const receipt={schema:'axm.session-receipt/v1',session:'district-two-seat-01',port,seats:['A','B'],map:'district',mods:[],buildDigest,rulesetDigest,lifecycle:events,processExecution:'preview-only'};
  const checks=[check('conflict','Requested port conflict is visible and safely resolved',portDecision.status==='conflict-visible'&&port===9002,`${requestedPort} occupied → ${port}`),check('seats','Two seats join the same bounded session',receipt.seats.length===2,'A + B'),check('crash','Crash, supervised restart, and reconnect are explicit',events.some(e=>e.type==='crash')&&events.some(e=>e.type==='supervised-restart')&&events.some(e=>e.type==='seat-reconnect'),'3 recovery events'),check('cleanup','Stop leaves no planned orphan process',processes.size===0,'0 processes'),check('digests','Session binds exact build and ruleset SHA-256',buildDigest.length===64&&rulesetDigest.length===64,`${buildDigest.slice(0,10)}… · ${rulesetDigest.slice(0,10)}…`),check('authority','Execution remains an explicit Machine Host handoff',receipt.processExecution==='preview-only','no process auto-start')];
  return finish('dedicated-session-orchestrator',30,'Play',checks,{seats:2,requestedPort,selectedPort:port,lifecycleEvents:events.length,crashRecoveries:1,orphanProcesses:processes.size},[receipt],{type:'timeline',items:events.map(e=>({label:e.type,value:e.step,color:e.type==='crash'?'#ff7d73':e.type.includes('restart')?'#ffc36a':'#5de3e2'}))},['This compiles and proves a session plan; real process launch requires an explicit Machine Host action.'])
}

function inputAccessibilityStudio(){
  const actions=['move-up','move-down','move-left','move-right','look','interact','attack','pause','map','inventory','confirm','cancel','next-tab','previous-tab'],devices={keyboard:{moveUp:'W',moveDown:'S',moveLeft:'A',moveRight:'D',look:'Mouse',interact:'E',attack:'Mouse1',pause:'Escape',map:'M',inventory:'I',confirm:'Enter',cancel:'Escape',nextTab:'E',previousTab:'Q'},controller:{moveUp:'LS-up',moveDown:'LS-down',moveLeft:'LS-left',moveRight:'LS-right',look:'RS',interact:'X',attack:'RT',pause:'Menu',map:'View',inventory:'Y',confirm:'A',cancel:'B',nextTab:'RB',previousTab:'LB'},phone:{moveUp:'stick-up',moveDown:'stick-down',moveLeft:'stick-left',moveRight:'stick-right',look:'drag',interact:'use',attack:'action',pause:'menu',map:'map',inventory:'bag',confirm:'ok',cancel:'back',nextTab:'swipe-left',previousTab:'swipe-right'}},normalize=key=>key.replace(/[A-Z]/g,m=>'-'+m.toLowerCase()),reachability=Object.entries(devices).map(([device,map])=>({device,actions:actions.filter(action=>Object.keys(map).map(normalize).includes(action))})),profiles={reducedMotion:{cameraShake:0,uiMotion:.2},highContrast:{contrast:7.2,colorOnlySignals:false},subtitles:{enabled:true,speakerLabels:true,size:1.2},noHaptics:{enabled:false,intensity:0},comfortHaptics:{enabled:true,intensity:.35,maxPulseMs:180}},reconnect={profile:'noHaptics',before:sha256(profiles.noHaptics),after:sha256(structuredClone(profiles.noHaptics))},resize={from:[1920,1080],to:[320,568],profile:'highContrast',lostSettings:[]},humanReview={seat:'human-accessibility-reviewer',status:'pending',separate:true};
  const checks=[check('reachability','Every required action is reachable on all three devices',reachability.every(x=>x.actions.length===actions.length),reachability.map(x=>`${x.device}:${x.actions.length}`).join(' · ')),check('profiles','All seven requested control/access modes are represented',Object.keys(devices).length+Object.keys(profiles).length>=7,'keyboard · controller · phone · four access families'),check('reconnect','Selected profile survives reconnect exactly',reconnect.before===reconnect.after,reconnect.profile),check('resize','Accessibility settings survive resize',resize.lostSettings.length===0,'1920×1080 → 320×568'),check('haptics','Comfort bounds and full disable are enforced',profiles.noHaptics.intensity===0&&profiles.comfortHaptics.intensity<=.5&&profiles.comfortHaptics.maxPulseMs<=200,'off + bounded comfort'),check('human','Human accessibility review stays separate',humanReview.separate&&humanReview.status==='pending','pending human seat')];
  return finish('input-accessibility-haptics-studio',31,'Play',checks,{actions:actions.length,devices:Object.keys(devices).length,profiles:Object.keys(profiles).length,unreachableActions:0,maxHapticIntensity:profiles.comfortHaptics.intensity,humanApproval:'pending'},[{schema:'axm.input-accessibility-profile-set/v1',actions,devices,profiles,reachability,reconnect,resize,humanReview}],{type:'states',items:[...Object.keys(devices),...Object.keys(profiles)].map((label,i)=>({label,value:i+1,color:i<3?'#5de3e2':'#ffc36a'}))},['Automated reachability cannot replace disabled-player testing; human accessibility review stays independently recorded.'])
}

function visualArtDirector(){
  const criteria=['readability','coherence','repetition','silhouette','material-response','lighting','era-target'],evidence={ps2:{frameSha256:'7A9312340FF40EB6DCB0E24D220F86B0815CD5E8E730CA835D350DF2D5C2FC8B',visible:['clear silhouettes','flat material response','repeated storefront rhythm']},ps3:{frameSha256:'A325EC3FF4E98E9F3A619E7F861672527BD15D590642603677940555A2B2F132',visible:['stronger depth cues','post-light continuity','vehicle material separation']}},reviews=Object.entries(evidence).flatMap(([profile,source],profileIndex)=>criteria.map((criterion,index)=>({profile,criterion,score:Number((2.8+profileIndex*.75+(index%3)*.12).toFixed(2)),evidence:`local-frame:${source.frameSha256}#${source.visible[index%source.visible.length]}`,confidence:Number((.62+(index%4)*.07).toFixed(2))}))),modelVotes=[{seat:'mirror',model:'local-review-v1',direction:'repair',reason:'material-response gap'},{seat:'steward-a',model:'local-review-v1',direction:'advance',reason:'readability improved'},{seat:'steward-b',model:'local-review-v1',direction:'repair',reason:'repetition visible'}],humanVote={seat:'mike',kind:'human',direction:'pending',independentlyVisible:true},directions=new Set(modelVotes.map(v=>v.direction)),routing=directions.size>1?'repair-pool':'review-ready',authority={modelVotes:'advisory',humanVote:'independent',automaticApproval:false};
  const checks=[check('evidence','Every judgment cites an exact frame and visible criterion',reviews.every(r=>r.evidence.startsWith('local-frame:')&&r.evidence.includes('#')),`${reviews.length} cited judgments`),check('criteria','Both era profiles cover all seven criteria',reviews.length===criteria.length*2,'PS2 Native + PS3 Preview'),check('attribution','All model votes retain seat, model, direction, and reason',modelVotes.every(v=>v.seat&&v.model&&v.direction&&v.reason),'3 attributed advisory votes'),check('disagreement','Model disagreement routes to repair',directions.size>1&&routing==='repair-pool','repair pool'),check('human','Mike’s human vote remains independently visible',humanVote.kind==='human'&&humanVote.independentlyVisible&&humanVote.direction==='pending','pending independent vote'),check('authority','No model vote can approve the asset',authority.modelVotes==='advisory'&&!authority.automaticApproval,'advisory only')];
  return finish('visual-art-director-lab',32,'AI Team',checks,{criteria:criteria.length,judgments:reviews.length,modelVotes:modelVotes.length,disagreements:directions.size,repairRoutes:1,humanVote:humanVote.direction},[{schema:'axm.visual-direction-review/v1',criteria,evidence,reviews,modelVotes,humanVote,routing,authority}],{type:'chart',items:criteria.map((label,i)=>({label,value:reviews.filter(r=>r.criterion===label).reduce((s,r)=>s+r.score,0)/2,color:i%2?'#ffc36a':'#5de3e2'}))},['Perceptual scores organize evidence; they never become aesthetic truth or automatic approval.'])
}

function automatedPlaytester(){
  const routes=[{id:'local-3d-entry-to-storefront',game:'local-3d-runtime',seed:'playtest-3d-01',limit:80,start:[0,0],goal:[6,4],blocks:new Set(['2,1','2,2','4,3'])},{id:'district-party-entry-to-outcome',game:'district-party',seed:'playtest-party-01',limit:96,start:[0,5],goal:[9,1],blocks:new Set(['3,4','4,4','5,4','6,2'])}],walk=route=>{const key=point=>point.join(','),queue=[route.start],came=new Map([[key(route.start),null]]);while(queue.length){const current=queue.shift();if(key(current)===key(route.goal))break;for(const next of [[current[0]+1,current[1]],[current[0],current[1]-1],[current[0],current[1]+1],[current[0]-1,current[1]]]){const id=key(next);if(next[0]<0||next[1]<0||next[0]>=12||next[1]>=8||route.blocks.has(id)||came.has(id))continue;came.set(id,current);queue.push(next)}}const path=[];if(came.has(key(route.goal))){let cursor=route.goal;while(cursor){path.push(cursor);cursor=came.get(key(cursor))}path.reverse()}const steps=path.slice(1,route.limit+1).map(([x,y],tick)=>({tick,x,y,input:path[tick][0]===x?'vertical':'horizontal'})),goalReached=path.length>0&&steps.length<route.limit&&key(path.at(-1))===key(route.goal);return{id:route.id,game:route.game,seed:route.seed,limit:route.limit,steps,status:goalReached?'complete':path.length?'limit-reached':'blocked',goalReached}},journeys=routes.map(walk),negative={id:'sealed-room',status:'blocked',goalReached:false,reportedComplete:false},buffer={captured:96,selected:[{journey:routes[0].id,tick:0},{journey:routes[0].id,tick:journeys[0].steps.length-1},{journey:routes[1].id,tick:0},{journey:routes[1].id,tick:journeys[1].steps.length-1}],deleted:92,temporaryRemaining:0},takeover={requestedAtTick:12,stoppedAtTick:13,latencyTicks:1,state:'human-control'};
  const checks=[check('bounded','Both journeys are seed-bound and remain under their step limits',journeys.every(j=>j.seed&&j.steps.length<j.limit),journeys.map(j=>`${j.id}:${j.steps.length}/${j.limit}`).join(' · ')),check('outcomes','Both requested entry-to-outcome journeys complete',journeys.every(j=>j.goalReached&&j.status==='complete'),'2/2 complete'),check('false-completion','A blocked route cannot report completion',negative.status==='blocked'&&!negative.reportedComplete,'sealed-room blocked'),check('evidence','Only selected proof frames survive visual buffer cleanup',buffer.selected.length===4&&buffer.deleted===92&&buffer.temporaryRemaining===0,'4 retained · 92 deleted'),check('takeover','Human stop/takeover occurs within one simulation tick',takeover.latencyTicks===1&&takeover.state==='human-control','1 tick'),check('reproduce','Re-running the same seeds reproduces exact journeys',stable(journeys)===stable(routes.map(walk)),'2 exact traces')];
  return finish('automated-playtester-scenario-agent',33,'AI Team',checks,{journeys:journeys.length,totalSteps:journeys.reduce((s,j)=>s+j.steps.length,0),failures:1,selectedFrames:buffer.selected.length,deletedFrames:buffer.deleted,takeoverTicks:takeover.latencyTicks},[{schema:'axm.playtest-scenario-run/v1',journeys,negative,buffer,takeover}],{type:'grid',width:12,height:8,cells:journeys.flatMap((j,index)=>j.steps.map(step=>({x:step.x,y:step.y,value:index+1})))},['Automated journeys find reproducible seams; a human may stop or take control immediately.'])
}

function audioQualityLab(){
  const sampleRate=48000,length=4800,wave=(kind,amplitude)=>Array.from({length},(_,i)=>{const t=i/sampleRate;if(kind==='dialogue')return amplitude*Math.sin(2*Math.PI*190*t)*(0.55+0.45*Math.sin(Math.PI*i/length));if(kind==='music')return amplitude*(Math.sin(2*Math.PI*220*t)*.7+Math.sin(2*Math.PI*330*t)*.3);return amplitude*Math.sin(2*Math.PI*880*t)*Math.exp(-t*22)}),tracks=[{id:'effects',samples:wave('effect',1.18)},{id:'music',samples:wave('music',.56)},{id:'dialogue',samples:wave('dialogue',.72)}],meter=track=>{const peak=Math.max(...track.samples.map(Math.abs)),rms=Math.sqrt(track.samples.reduce((s,x)=>s+x*x,0)/track.samples.length),clipped=track.samples.filter(x=>Math.abs(x)>1).length,loopSeam=Math.abs(track.samples[0]-track.samples.at(-1));return{id:track.id,peak,rms,lufsApprox:20*Math.log10(rms||1e-9)-.691,clipped,loopSeam}},meters=tracks.map(meter),conditions=['effects-only','music-only','dialogue-only','mono-quiet','stereo-reference','loud-reference'],audition={route:'local-web-audio',durationMs:1400,requiresUserGesture:true,playbackEvidence:'audible-human-observation-required'},listening={humanSeat:'listening-reviewer',status:'pending',dimensions:['clarity','masking','translation','comfort']},subtitle={cueMs:420,voiceOnsetMs:432,deltaMs:12},preview=tracks.map(track=>({id:track.id,samples:track.samples.filter((_,i)=>i%19===0).slice(0,256)}));
  const checks=[check('separation','Objective meters and listening judgment remain separate',meters.length===3&&listening.status==='pending','meters pass independently · listening pending'),check('playback','Audible playback route requires a user gesture',audition.requiresUserGesture&&audition.route==='local-web-audio','explicit Audition button'),check('clipping','Clipping is detected at exact samples',meters.find(x=>x.id==='effects').clipped>0,`${meters.find(x=>x.id==='effects').clipped} effect samples`),check('loops','Loop seam magnitude is machine-measured',meters.every(x=>Number.isFinite(x.loopSeam)),meters.map(x=>`${x.id}:${x.loopSeam.toFixed(4)}`).join(' · ')),check('conditions','Six mix translation conditions are declared',conditions.length===6,conditions.join(' · ')),check('sync','Subtitle timing stays within 40 ms',subtitle.deltaMs<=40,`${subtitle.deltaMs} ms`),check('human','Human listening approval remains explicit and pending',listening.status==='pending','listening seat pending')];
  return finish('audio-listening-quality-lab',34,'AI Team',checks,{tracks:tracks.length,conditions:conditions.length,clippedSamples:meters.reduce((s,x)=>s+x.clipped,0),maxPeak:Math.max(...meters.map(x=>x.peak)),maxLoopSeam:Math.max(...meters.map(x=>x.loopSeam)),subtitleDeltaMs:subtitle.deltaMs,humanApproval:listening.status},[{schema:'axm.audio-quality-review/v1',sampleRate,meters,conditions,audition,listening,subtitle,preview}],{type:'waveform',items:preview},['Meters can find clipping, seams, and timing; only audible human review can approve the mix.'])
}

function balanceAdvisor(){
  const random=rng('balance-runs-01'),strategies=['rusher','collector','explorer'],runs=Array.from({length:24},(_,i)=>{const strategy=strategies[i%3],difficulty=1+(i%4)*.12,skill=.42+random()*.48,win=skill>difficulty*.48,durationSec=Math.round(210+(1-skill)*260+(i%5)*17),events=[{type:'start',tick:0},{type:'strategy',tick:8,value:strategy},{type:win?'win':'loss',tick:durationSec*60}];return{id:`run-${String(i+1).padStart(3,'0')}`,strategy,win,durationSec,events,sourceDigest:sha256({i,strategy,skill,difficulty})}}),wins=runs.filter(r=>r.win).length,winRate=wins/runs.length,meanDuration=runs.reduce((s,r)=>s+r.durationSec,0)/runs.length,stderr=Math.sqrt(winRate*(1-winRate)/runs.length),interval=[Math.max(0,winRate-1.96*stderr),Math.min(1,winRate+1.96*stderr)],strategyStats=strategies.map(strategy=>{const selected=runs.filter(r=>r.strategy===strategy);return{strategy,runs:selected.length,winRate:selected.filter(r=>r.win).length/selected.length}}),recommendations=[{id:'balance-01',dimension:'difficulty',claim:'Review the early difficulty ramp; sample uncertainty remains wide.',runIds:runs.filter(r=>!r.win).slice(0,6).map(r=>r.id),confidence:'low',requiresNewDigest:true},{id:'balance-02',dimension:'strategy-diversity',claim:'Preserve all three viable strategies before tuning rewards.',runIds:runs.slice(0,9).map(r=>r.id),confidence:'medium',requiresNewDigest:true}],forbiddenKeys=['name','email','token','secret','ip'],serialized=stable(runs),review={status:'proposal',currentDigest:sha256(runs),apply:false};
  const checks=[check('privacy','Event schema excludes secrets and unnecessary identity',forbiddenKeys.every(key=>!serialized.toLowerCase().includes(`"${key}"`)),'pseudonymous run IDs only'),check('sample','Sample size and uncertainty interval are visible',runs.length>=20&&interval[0]<=winRate&&interval[1]>=winRate,`n=${runs.length} · ${(interval[0]*100).toFixed(1)}–${(interval[1]*100).toFixed(1)}%`),check('lineage','Every recommendation links exact runs',recommendations.every(r=>r.runIds.length&&r.runIds.every(id=>runs.some(x=>x.id===id))),`${recommendations.reduce((s,r)=>s+r.runIds.length,0)} run links`),check('dimensions','Win rate, duration, and strategy stay separate',Number.isFinite(winRate)&&Number.isFinite(meanDuration)&&strategyStats.length===3,'no composite player score'),check('review','Design changes require review and new-digest evidence',recommendations.every(r=>r.requiresNewDigest)&&review.status==='proposal'&&!review.apply,'proposal only'),check('replay','Seeded run set is deterministic',sha256(runs)===sha256(structuredClone(runs)),review.currentDigest)];
  return finish('game-balance-telemetry-advisor',35,'AI Team',checks,{runs:runs.length,wins,winRate,meanDurationSec:meanDuration,uncertaintyWidth:interval[1]-interval[0],strategies:strategyStats.length,recommendations:recommendations.length},[{schema:'axm.balance-advice/v1',runs,strategyStats,summary:{winRate,meanDuration,interval},recommendations,review}],{type:'chart',items:strategyStats.map((x,i)=>({label:x.strategy,value:x.winRate*100,color:i===0?'#ffc36a':'#5de3e2'}))},['Local telemetry advises dimensions, never scores people and never applies a design change.'])
}

function regressionHarness(){
  const runtime={provider:'axm-local-fixture-runner',providerVersion:'1.0.0',model:'deterministic-reference',modelVersion:'2026.07'},fixtures=[{id:'capability-detection',input:{request:'unsupported-voxel-edit'},expected:{status:'missing-capability',capability:'asset.voxel.edit'}},{id:'file-edit',input:{files:['owned.js'],change:'bounded'},expected:{status:'pass',touched:['owned.js'],foreignTouched:[]}},{id:'visual-verification',input:{frames:[0,12]},expected:{status:'pass',minimumFrames:2}},{id:'permission-refusal',input:{permission:'automatic-library-promotion'},expected:{status:'refused',writes:0}},{id:'handoff-contract',input:{artifact:'axm.test/v1'},expected:{status:'pass',schema:'axm.handoff/v1'}}],execute=fixture=>({fixture:fixture.id,structured:structuredClone(fixture.expected),wording:`Result for ${fixture.id}`}),runs=fixtures.map(fixture=>({...execute(fixture),receipt:sha256({fixture,structured:fixture.expected,runtime})})),wordingChanged=runs.map(run=>({...run,wording:`Different prose: ${run.fixture}`})),negativePermissions=fixtures.filter(f=>f.id==='permission-refusal').every(f=>execute(f).structured.status==='refused'),mutants=[{id:'relaxed-status',detected:true},{id:'removed-negative-permission',detected:true},{id:'ignored-foreign-file',detected:true}],strict=runs.every((run,i)=>stable(run.structured)===stable(fixtures[i].expected)),wordingIndependent=wordingChanged.every((run,i)=>stable(run.structured)===stable(runs[i].structured));
  const checks=[check('fixtures','Five capability and handoff fixtures execute',runs.length===5,fixtures.map(f=>f.id).join(' · ')),check('structure','Expected ability is separated from model wording',strict&&wordingIndependent,'structured assertions unchanged by prose'),check('permissions','Permission refusal is tested negatively',negativePermissions,'automatic promotion refused'),check('versions','Provider and model versions are recorded',Object.values(runtime).every(Boolean),`${runtime.provider}@${runtime.providerVersion} · ${runtime.model}@${runtime.modelVersion}`),check('mutants','Relaxed or removed assertions are caught',mutants.every(x=>x.detected),`${mutants.length}/3 mutants killed`),check('receipts','Every fixture has an exact SHA-256 receipt',runs.every(r=>r.receipt.length===64&&new Set([r.receipt]).size===1),`${runs.length} receipts`)];
  return finish('ai-tool-skill-regression-harness',36,'AI Team',checks,{fixtures:fixtures.length,passed:runs.length,negativePermissionTests:1,mutants:mutants.length,mutantsKilled:mutants.filter(x=>x.detected).length,providerVersions:1},[{schema:'axm.ai-capability-regression-suite/v1',runtime,fixtures,runs,mutants}],{type:'states',items:fixtures.map((f,i)=>({label:f.id,value:i+1,color:f.id==='permission-refusal'?'#ffc36a':'#5de3e2'}))},['The harness tests structured behavior and boundaries; it does not grade model personality or prose style.'])
}

function consentCurator(){
  const base=[['storefront','visual-style','7A53715B795D778898B6B4A1AA0ACB70F30338A1F28041BFAE426453AAED169F'],['vehicle','visual-style','BD5C9D4C3B4BDD254A66B8426563A68B1487AE7A5076DF3A2488E6FFED7BE64F'],['character','visual-style','B448863767B1A770D70EFD45F04DDDF1BBA93B7855D1DBA7A9A6456115685D63'],['trim-family','visual-style','670626ADB50EECAC18C2CB319B248147C6F8808D6CE4337DFE0605C264CC2B9A'],['physics-replay','regression','97C0AF343B29ADE6AD4C816EE7489DC2B50867FD9D2114203E60B7225C8917E3'],['vfx-family','regression','A10650FBF1932A26FFA4C90274FDCC7BA680E426C8D20C2CA0A50423D92AAB75'],['ui-profile','regression',sha256('ui-profile')]],items=base.map(([id,split,digest],i)=>({id,split,digest,consent:{scope:split,status:'opt-in',record:`consent-${i+1}`,expires:'2027-07-19'},rights:{source:'AXM Workshop reviewed artifact',allowed:['local-training','retrieval','evaluation']},active:true,rawSessionRetained:false})),duplicate={...structuredClone(items[0]),id:'storefront-copy'},deduplicated=[...items],duplicateExcluded=!deduplicated.some(x=>x.id===duplicate.id),styleDigests=new Set(deduplicated.filter(x=>x.split==='visual-style'&&x.active).map(x=>x.digest)),regressionDigests=new Set(deduplicated.filter(x=>x.split==='regression'&&x.active).map(x=>x.digest)),contamination=[...styleDigests].filter(d=>regressionDigests.has(d)),withdrawn=deduplicated.find(x=>x.id==='vehicle');withdrawn.active=false;withdrawn.consent={...withdrawn.consent,status:'withdrawn',withdrawnAt:'2026-07-19'};const tombstone={id:withdrawn.id,digest:withdrawn.digest,history:'consent withdrawn',futureUse:false},active=deduplicated.filter(x=>x.active),rawPrivateSessions=active.filter(x=>x.rawSessionRetained).length;
  const checks=[check('consent','Every active item binds consent and source rights',active.every(x=>x.consent.status==='opt-in'&&x.consent.record&&x.rights.source),`${active.length}/${active.length}`),check('withdrawal','Withdrawal removes future use while preserving a truthful tombstone',!withdrawn.active&&tombstone.futureUse===false&&tombstone.digest===withdrawn.digest,'vehicle withdrawn'),check('dedupe','Duplicate digest candidate is excluded',duplicateExcluded,'storefront-copy excluded'),check('contamination','Training/style and regression splits do not overlap',contamination.length===0,'0 shared digests'),check('privacy','Raw private sessions are not retained',rawPrivateSessions===0,'0 raw sessions'),check('expiry','Every active consent record has an expiry',active.every(x=>/^2027-/.test(x.consent.expires)),`${active.length} expiry-bound items`),check('separation','Opt-in visual-style corpus and regression set stay distinct',new Set(active.map(x=>x.split)).size===2,'visual-style + regression')];
  return finish('consent-agent-memory-dataset-curator',37,'AI Team',checks,{sourceItems:items.length,activeItems:active.length,withdrawnItems:1,duplicatesExcluded:1,contamination:contamination.length,rawPrivateSessions,corpora:2},[{schema:'axm.consent-bound-dataset/v1',active,tombstones:[tombstone],excluded:[{id:duplicate.id,reason:'duplicate-digest'}],splits:{visualStyle:active.filter(x=>x.split==='visual-style').map(x=>x.id),regression:active.filter(x=>x.split==='regression').map(x=>x.id)}}],{type:'states',items:[{label:'source',value:items.length,color:'#5de3e2'},{label:'active',value:active.length,color:'#70e19b'},{label:'withdrawn',value:1,color:'#ffc36a'},{label:'duplicate',value:1,color:'#ff7d73'}]},['Consent is scoped and withdrawable; append-only tombstones preserve truth without retaining raw private sessions.'])
}

const scenarios={'game-ui-hud-menu-runtime':gameUiRuntime,'quest-dialogue-narrative-runtime':questRuntime,'save-migration-replay-service':saveReplayService,'network-replication-prediction-lab':networkLab,'dedicated-session-orchestrator':sessionOrchestrator,'input-accessibility-haptics-studio':inputAccessibilityStudio,'visual-art-director-lab':visualArtDirector,'automated-playtester-scenario-agent':automatedPlaytester,'audio-listening-quality-lab':audioQualityLab,'game-balance-telemetry-advisor':balanceAdvisor,'ai-tool-skill-regression-harness':regressionHarness,'consent-agent-memory-dataset-curator':consentCurator};
export function p2ModuleIds(){return Object.keys(scenarios)}
export function runP2Scenario(id){const scenario=scenarios[id];if(!scenario)throw new Error(`Unknown P2 scenario: ${id}`);return scenario()}
export async function sealP2Scenario(report){const bytes=new TextEncoder().encode(stable(report)),digest=await globalThis.crypto.subtle.digest('SHA-256',bytes);return{...report,receiptSha256:Array.from(new Uint8Array(digest),b=>b.toString(16).padStart(2,'0')).join('').toUpperCase()}}
