import {runP2Scenario,sealP2Scenario} from './p2-kernel.mjs';
import {verifyP2Scenario} from './p2-verifier.mjs';

const $=id=>document.getElementById(id);
const moduleId=document.body.dataset.module;
let current=null;

function pretty(value){
  if(typeof value==='boolean')return value?'YES':'NO';
  if(typeof value==='number')return Number.isInteger(value)?value.toLocaleString():value.toFixed(value<1?4:1);
  return String(value);
}
function renderMetrics(metrics){
  $('metric-grid').innerHTML=Object.entries(metrics).slice(0,8).map(([key,value])=>`<dl class="metric"><dt>${key.replace(/([A-Z])/g,' $1')}</dt><dd>${pretty(value)}</dd></dl>`).join('');
}
function renderChecks(checks){
  $('check-list').innerHTML=checks.map(item=>`<div class="check ${item.status==='pass'?'':'fail'}"><i>${item.status==='pass'?'✓':'!'}</i><div><strong>${item.label}</strong><small>${item.evidence}</small></div></div>`).join('');
}
function renderArtifacts(artifacts){
  $('artifact-list').innerHTML=artifacts.map((artifact,index)=>`<div class="artifact"><code>${artifact.schema}</code><span>${Object.keys(artifact).length-1} payload routes · candidate ${index+1}</span></div>`).join('');
}
function canvasContext(){
  const canvas=$('visual');const rect=canvas.getBoundingClientRect();const ratio=Math.min(2,window.devicePixelRatio||1),width=Math.max(720,Math.round(rect.width*ratio)),height=Math.round(width/2);if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height}const ctx=canvas.getContext('2d');ctx.setTransform(canvas.width/1200,0,0,canvas.height/600,0,0);return ctx;
}
function background(ctx){
  ctx.clearRect(0,0,1200,600);const g=ctx.createLinearGradient(0,0,1200,600);g.addColorStop(0,'#0c1b25');g.addColorStop(1,'#071017');ctx.fillStyle=g;ctx.fillRect(0,0,1200,600);ctx.strokeStyle='#18303e';ctx.lineWidth=1;for(let x=0;x<=1200;x+=60){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,600);ctx.stroke()}for(let y=0;y<=600;y+=60){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(1200,y);ctx.stroke()}
}
function label(ctx,text,x,y,color='#9db0bc',align='left',size=18){ctx.fillStyle=color;ctx.font=`700 ${size}px ui-monospace, monospace`;ctx.textAlign=align;ctx.fillText(String(text).toUpperCase(),x,y)}
function drawBars(ctx,items){const max=Math.max(1,...items.map(i=>Number(i.value)||0)),gap=18,w=Math.min(100,(1040-gap*(items.length-1))/items.length);items.forEach((item,i)=>{const x=80+i*(w+gap),h=360*(Number(item.value)||0)/max;ctx.fillStyle=item.color||'#5de3e2';ctx.globalAlpha=.82;ctx.fillRect(x,470-h,w,h);ctx.globalAlpha=1;label(ctx,item.label,x+w/2,510,'#aebec7','center',Math.max(11,16-items.length/2));label(ctx,pretty(item.value),x+w/2,445-h,item.color||'#5de3e2','center',14)})}
function drawGrid(ctx,v){const cells=v.cells||[],cols=v.width||Math.max(1,...cells.map(c=>c.x))+1,rows=v.height||Math.max(1,...cells.map(c=>c.y))+1,size=Math.min(68,440/rows,960/cols),ox=(1200-cols*size)/2,oy=(560-rows*size)/2;cells.forEach(c=>{const hue=c.value===2?'#ffc36a':'#5de3e2';ctx.fillStyle=hue;ctx.globalAlpha=.2+Math.min(.65,(Number(c.value)||1)/6);ctx.fillRect(ox+c.x*size+2,oy+c.y*size+2,size-4,size-4);ctx.globalAlpha=1;ctx.strokeStyle=hue;ctx.strokeRect(ox+c.x*size+2,oy+c.y*size+2,size-4,size-4)});label(ctx,`${cols} × ${rows} deterministic cells`,600,552,'#9db0bc','center',16)}
function drawAtlas(ctx,v){const sx=900/v.width,sy=470/v.height,ox=150,oy=55;ctx.fillStyle='#09131a';ctx.fillRect(ox,oy,900,470);v.rects.forEach((r,i)=>{ctx.fillStyle=i<8?'#5de3e2':'#ffc36a';ctx.globalAlpha=.35;ctx.fillRect(ox+r.x*sx,oy+r.y*sy,Math.max(2,r.w*sx),Math.max(2,r.h*sy));ctx.globalAlpha=1;ctx.strokeStyle=i<8?'#8ff5ee':'#ffdd9a';ctx.strokeRect(ox+r.x*sx,oy+r.y*sy,Math.max(2,r.w*sx),Math.max(2,r.h*sy))});label(ctx,`${v.rects.length} packed regions`,600,558,'#9db0bc','center',16)}
function drawPeople(ctx,items){items.forEach((item,i)=>{const x=100+i*108,y=455,scale=.75+(item.value||2)*.08;ctx.strokeStyle=item.color;ctx.lineWidth=7;ctx.beginPath();ctx.arc(x,y-245*scale,30*scale,0,Math.PI*2);ctx.moveTo(x,y-212*scale);ctx.lineTo(x,y-92*scale);ctx.moveTo(x,y-180*scale);ctx.lineTo(x-45*scale,y-125*scale);ctx.moveTo(x,y-180*scale);ctx.lineTo(x+45*scale,y-125*scale);ctx.moveTo(x,y-92*scale);ctx.lineTo(x-32*scale,y);ctx.moveTo(x,y-92*scale);ctx.lineTo(x+32*scale,y);ctx.stroke();label(ctx,String(i+1).padStart(2,'0'),x,y+35,'#9db0bc','center',13)})}
function drawTimeline(ctx,items){const min=Math.min(0,...items.map(i=>Number(i.value)||0)),max=Math.max(1,...items.map(i=>Number(i.value)||0));ctx.strokeStyle='#426073';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(90,300);ctx.lineTo(1110,300);ctx.stroke();items.forEach((item,i)=>{const x=100+(1020*(Number(item.value)-min))/(max-min||1),above=i%2===0;ctx.fillStyle=item.color||'#ffc36a';ctx.beginPath();ctx.arc(x,300,10,0,Math.PI*2);ctx.fill();ctx.strokeStyle=item.color||'#ffc36a';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,300);ctx.lineTo(x,above?205:395);ctx.stroke();label(ctx,item.label,x,above?185:425,item.color||'#ffc36a','center',Math.max(11,15-items.length/3));label(ctx,pretty(item.value),x,above?225:375,'#a9bbc5','center',12)})}
function drawStates(ctx,items){const gap=14,w=Math.min(180,(1100-gap*Math.max(0,items.length-1))/Math.max(1,items.length)),total=w*items.length+gap*Math.max(0,items.length-1),start=(1200-total)/2,h=170;items.forEach((item,i)=>{const x=start+i*(w+gap),y=200;ctx.fillStyle='#0e202b';ctx.strokeStyle=item.color||'#5de3e2';ctx.lineWidth=2;ctx.fillRect(x,y,w,h);ctx.strokeRect(x,y,w,h);ctx.fillStyle=item.color||'#5de3e2';ctx.fillRect(x,y,w,9);label(ctx,item.label,x+w/2,y+68,item.color||'#5de3e2','center',Math.max(9,15-items.length/2));label(ctx,`STATE ${item.value}`,x+w/2,y+120,'#9db0bc','center',11);if(i<items.length-1){ctx.strokeStyle='#486274';ctx.beginPath();ctx.moveTo(x+w+3,y+h/2);ctx.lineTo(x+w+gap-3,y+h/2);ctx.stroke()}})}
function drawGraph(ctx,items){const cx=600,cy=300,r=205;items.forEach((item,i)=>{const a=Math.PI*2*i/items.length-Math.PI/2,x=cx+Math.cos(a)*r,y=cy+Math.sin(a)*r,nx=cx+Math.cos(a+Math.PI*2/items.length)*r,ny=cy+Math.sin(a+Math.PI*2/items.length)*r;ctx.strokeStyle='#355266';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(nx,ny);ctx.stroke()});items.forEach((item,i)=>{const a=Math.PI*2*i/items.length-Math.PI/2,x=cx+Math.cos(a)*r,y=cy+Math.sin(a)*r;ctx.fillStyle='#102530';ctx.strokeStyle=item.color;ctx.lineWidth=4;ctx.beginPath();ctx.arc(x,y,64,0,Math.PI*2);ctx.fill();ctx.stroke();label(ctx,item.label,x,y-4,item.color,'center',13);label(ctx,`${item.value} NODES`,x,y+22,'#9db0bc','center',11)})}
function drawPhysics(ctx,visual,time){const frames=visual.frames||[],frame=frames[Math.floor(time/90)%Math.max(1,frames.length)]||{},map=x=>100+(Math.max(-4,Math.min(4,x))+4)*125;ctx.fillStyle='#14252d';ctx.fillRect(65,390,1070,8);for(let x=-4;x<=4;x++)label(ctx,x,map(x),430,'#536d7c','center',11);const carX=map(frame.carX||0);ctx.fillStyle='#5de3e2';ctx.fillRect(carX-56,330,112,46);ctx.fillStyle='#10222c';ctx.fillRect(carX-32,338,54,24);ctx.fillStyle='#8293a8';ctx.beginPath();ctx.arc(carX-32,380,13,0,Math.PI*2);ctx.arc(carX+34,380,13,0,Math.PI*2);ctx.fill();const personX=map(frame.personX||2),down=frame.personState==='ragdoll';ctx.strokeStyle=down?'#ff7d73':'#ffc36a';ctx.lineWidth=7;ctx.beginPath();if(down){ctx.moveTo(personX-28,370);ctx.lineTo(personX+30,380);ctx.arc(personX+42,381,10,0,Math.PI*2)}else{ctx.arc(personX,295,15,0,Math.PI*2);ctx.moveTo(personX,312);ctx.lineTo(personX,358);ctx.moveTo(personX,329);ctx.lineTo(personX-22,345);ctx.moveTo(personX,329);ctx.lineTo(personX+22,345);ctx.moveTo(personX,358);ctx.lineTo(personX-18,390);ctx.moveTo(personX,358);ctx.lineTo(personX+18,390)}ctx.stroke();const propX=map(3.2);ctx.fillStyle=frame.propState==='broken'?'#6b3e35':'#a36f45';if(frame.propState==='broken'){ctx.fillRect(propX-22,376,20,12);ctx.fillRect(propX+7,368,27,15)}else ctx.fillRect(propX-18,330,36,60);label(ctx,`TICK ${frame.tick??0}`,82,80,'#5de3e2','left',17);label(ctx,String(frame.personState||'standing'),82,108,down?'#ff7d73':'#ffc36a','left',14);label(ctx,'LIVE FIXED-STEP REPLAY',1115,80,'#9db0bc','right',14)}
function drawVfx(ctx,visual,time){drawBars(ctx,visual.items||[]);const items=visual.items||[],phase=time*.001;items.forEach((item,i)=>{const x=130+i*155,color=item.color||'#5de3e2';for(let p=0;p<12;p++){const t=(phase*(.35+i*.025)+p/12)%1,y=420-t*320,jitter=Math.sin((p+1)*13.7+i*8.1+phase*2)*34;ctx.globalAlpha=.18+.7*(1-t);ctx.strokeStyle=color;ctx.fillStyle=color;if(item.label==='rain'){ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x+jitter,y);ctx.lineTo(x+jitter-7,y+22);ctx.stroke()}else{ctx.beginPath();ctx.arc(x+jitter,y,3+(p%4),0,Math.PI*2);ctx.fill()}}ctx.globalAlpha=1});label(ctx,`MOTION FRAME ${Math.floor(phase*8)%32}`,1115,72,'#ffc36a','right',14)}
function drawWaveform(ctx,visual){const tracks=visual.items||[],colors=['#5de3e2','#ffc36a','#ff7d73'];tracks.forEach((track,index)=>{const mid=130+index*170,amp=62,samples=track.samples||[];ctx.strokeStyle=colors[index%colors.length];ctx.lineWidth=2;ctx.beginPath();samples.forEach((value,i)=>{const x=80+i*(1040/Math.max(1,samples.length-1)),y=mid-value*amp;if(i)ctx.lineTo(x,y);else ctx.moveTo(x,y)});ctx.stroke();label(ctx,track.id,90,mid-78,colors[index%colors.length],'left',14);ctx.strokeStyle='#29404d';ctx.beginPath();ctx.moveTo(80,mid);ctx.lineTo(1120,mid);ctx.stroke()})}
function drawVisual(visual,time=performance.now()){const ctx=canvasContext();background(ctx);if(visual.type==='atlas')drawAtlas(ctx,visual);else if(visual.type==='grid')drawGrid(ctx,visual);else if(visual.type==='people')drawPeople(ctx,visual.items);else if(visual.type==='timeline')drawTimeline(ctx,visual.items);else if(visual.type==='states')drawStates(ctx,visual.items);else if(visual.type==='graph')drawGraph(ctx,visual.items);else if(visual.type==='physics')drawPhysics(ctx,visual,time);else if(visual.type==='vfx')drawVfx(ctx,visual,time);else if(visual.type==='waveform')drawWaveform(ctx,visual);else drawBars(ctx,visual.items||[])}
async function compile(){
  const base=runP2Scenario(moduleId);current=await sealP2Scenario(base);const verification=verifyP2Scenario(current);document.title=`${current.name} · AXM`;$('module-name').textContent=current.name;$('module-rank').textContent=`${current.category} / P2 / PRIORITY ${String(current.rank).padStart(2,'0')}`;$('module-intro').textContent=`Deterministic local experience route for ${current.id.replaceAll('-',' ')}. Preview first; authority stays explicit.`;$('status').dataset.state=verification.status;$('status').textContent=verification.status==='pass'?'EVIDENCE PASS':'BLOCKED';$('score').textContent=`${verification.summary.passed}/${verification.summary.checks}`;$('score-note').textContent=`${current.summary.passed}/${current.summary.checks} scenario gates and ${verification.summary.passed}/${verification.summary.checks} independent evidence routes passed.`;renderChecks(current.checks);renderMetrics(current.metrics);renderArtifacts(current.artifacts);$('boundary').textContent=current.boundaries.join(' ');$('receipt-sha').textContent=current.receiptSha256;$('receipt-json').textContent=JSON.stringify({receiptSha256:current.receiptSha256,verification,report:current},null,2);$('visual-note').textContent=`${current.visual.type.toUpperCase()} · SEE THE OUTPUT, NOT ONLY THE COUNT`;drawVisual(current.visual);document.body.dataset.scenarioStatus=current.status;document.body.dataset.receiptSha256=current.receiptSha256;document.body.dataset.moduleId=current.id;$('export').disabled=false;
}
const audition=$('audition');if(moduleId==='audio-listening-quality-lab'&&audition){audition.classList.remove('hidden');audition.addEventListener('click',()=>{const Audio=window.AudioContext||window.webkitAudioContext,context=new Audio(),master=context.createGain();master.gain.value=.12;master.connect(context.destination);[[190,.5],[330,.24],[880,.1]].forEach(([frequency,gain],index)=>{const oscillator=context.createOscillator(),level=context.createGain();oscillator.frequency.value=frequency;oscillator.type=index===2?'square':'sine';level.gain.value=gain;oscillator.connect(level);level.connect(master);oscillator.start();oscillator.stop(context.currentTime+1.4)});audition.textContent='Playing local mix…';setTimeout(()=>{audition.textContent='Audition local mix';context.close()},1500)})}
$('compile').addEventListener('click',compile);$('seal').addEventListener('click',compile);$('export').addEventListener('click',()=>{if(!current)return;const url=URL.createObjectURL(new Blob([JSON.stringify(current,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=`${moduleId}-candidate-receipt.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),0)});window.addEventListener('resize',()=>current&&drawVisual(current.visual));let lastAnimation=0;function animate(time){if(time-lastAnimation>=80&&current&&['physics','vfx'].includes(current.visual.type)){lastAnimation=time;drawVisual(current.visual,time)}requestAnimationFrame(animate)}requestAnimationFrame(animate);compile().catch(error=>{document.body.dataset.scenarioStatus='blocked';$('status').textContent='BLOCKED';$('receipt-json').textContent=error.stack||error.message});

