(function(){
  'use strict';
  var Core=window.AXMAITeamCore,STORE='axm.ai-team.workspace.v1',BRIDGE='http://127.0.0.1:8787',$=function(id){return document.getElementById(id);};
  var state,services=new Map(),notices=[],paused=false,pollTimer=null,refreshing=false,pendingPrompt=null;
  try{state=Core.normalize(JSON.parse(localStorage.getItem(STORE)||'null'));}catch(e){state=Core.normalize({});}
  var icons={
    home:'<path d="M4 11l8-7 8 7v9H5z"/><path d="M9 20v-6h6v6"/>',
    chat:'<path d="M4 5h16v11H9l-5 4z"/><path d="M8 9h8M8 12h5"/>',
    duo:'<circle cx="8" cy="10" r="4"/><circle cx="17" cy="10" r="3"/><path d="M2 21c1-4 3-6 6-6s5 2 6 6M14 16c3 0 5 2 6 5"/>',
    agent:'<circle cx="12" cy="8" r="4"/><path d="M4 21c1-5 4-7 8-7s7 2 8 7M5 4l2 2M19 4l-2 2"/>',
    tool:'<path d="M14 5l5 5-9 9H5v-5z"/><path d="M13 6l2-2 5 5-2 2"/>',
    prompt:'<path d="M6 3h9l3 3v15H6z"/><path d="M9 9h6M9 13h6M9 17h4"/>',
    model:'<path d="M4 7l8-4 8 4-8 4zM4 7v10l8 4 8-4V7M12 11v10"/>',
    reason:'<path d="M9 18h6M10 21h4"/><path d="M8 14c-2-1-3-3-3-5a7 7 0 0114 0c0 2-1 4-3 5-1 1-1 2-1 2H9s0-1-1-2z"/>',
    data:'<ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v6c0 2 4 3 8 3s8-1 8-3V5M4 11v6c0 2 4 3 8 3s8-1 8-3v-6"/>',
    service:'<circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M19 5l-2 2M7 17l-2 2"/>'
  };
  function svg(name){return'<svg viewBox="0 0 24 24" aria-hidden="true">'+icons[name]+'</svg>';}
  function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function toast(text){var t=$('toast');t.textContent=text;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(function(){t.classList.remove('show');},2100);}
  function persist(message){state.updatedAt=new Date().toISOString();localStorage.setItem(STORE,JSON.stringify(state));$('saveState').textContent='Saved '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});if(window.AXMHub)AXMHub.save({workspace:state});if(message)toast(message);}
  function ensureFrame(frame){if(frame&&frame.dataset.src&&!frame.dataset.loaded){frame.src=frame.dataset.src;frame.dataset.loaded='1';}}
  function renderNav(){var nav=$('viewNav');nav.innerHTML='';Core.groups().forEach(function(group){var title=document.createElement('div');title.className='view-group-title';title.textContent=group.name;nav.appendChild(title);group.views.forEach(function(view){var b=document.createElement('button');b.className='view-button';b.dataset.view=view.id;b.innerHTML='<span class="nav-icon">'+svg(view.icon)+'</span><b></b>';b.querySelector('b').textContent=view.short;b.onclick=function(){selectView(view.id);};nav.appendChild(b);});});}
  var frames={task:$('taskFrame'),duo:$('duoFrame'),agents:$('agentsFrame'),forge:$('forgeFrame'),prompts:$('promptsFrame'),models:$('modelsFrame'),reasoning:$('reasoningFrame')};
  Object.keys(frames).forEach(function(key){frames[key].addEventListener('load',function(){this.dataset.ready='1';if(key==='models'&&pendingPrompt){this.contentWindow.postMessage({schema:'axm.ai-team-prompt/v1',type:'axm-model-compare-prompt',prompt:pendingPrompt},'*');pendingPrompt=null;}});});
  function selectView(id,silent){var view=Core.byId(id);state.view=view.id;document.querySelectorAll('.view-button').forEach(function(b){b.classList.toggle('active',b.dataset.view===view.id);});$('viewGroup').textContent=view.group+' view';$('viewTitle').textContent=view.title;$('viewDescription').textContent=view.description;$('overviewSurface').hidden=view.route!=='native';$('servicesSurface').hidden=view.route!=='services';$('dataSurface').hidden=view.route!=='data';$('frameSurface').hidden=['native','services','data'].indexOf(view.route)>=0;Object.keys(frames).forEach(function(key){frames[key].hidden=key!==view.route;});if(frames[view.route])ensureFrame(frames[view.route]);if(view.route==='services')refreshAll();if(view.route==='data')renderDataWorkspace();$('statusText').textContent=view.title+' ready';if(!silent)persist('Opened '+view.title);}
  function fetchTimed(url,ms,options){var c=new AbortController(),timer=setTimeout(function(){c.abort();},ms||2500),opts=options||{};opts.cache='no-store';opts.signal=c.signal;return fetch(url,opts).finally(function(){clearTimeout(timer);});}
  function service(id,stateName,detail,action){services.set(id,{state:stateName||'offline',detail:detail||'Unavailable',action:action||null});}
  async function loadBridge(){try{var h=await fetchTimed(BRIDGE+'/health',2200);if(!h.ok)throw Error('HTTP '+h.status);var g=await fetchTimed(BRIDGE+'/agent-state',2200),gate=g.ok?await g.json():{};paused=!!gate.paused;service('bridge',paused?'paused':'ready',paused?'Local agent gate is paused':'Local bridge connected and accepting supervised routes','agents');var m=await fetchTimed(BRIDGE+'/local-models',3000),mj=m.ok?await m.json():{},ids=(mj.data||[]).map(function(x){return String(x.id||'').toLowerCase();});service('nova',ids.indexOf('axm-llama-3.1-8b')>=0?(paused?'paused':'active'):'offline',ids.indexOf('axm-llama-3.1-8b')>=0?'axm-llama-3.1-8b loaded':'Nova model is not loaded','collaborate');service('gemini-local',ids.indexOf('gemini-local')>=0?(paused?'paused':'active'):'offline',ids.indexOf('gemini-local')>=0?'gemini-local loaded':'Gemini Local model is not loaded','duo');}catch(e){paused=false;service('bridge','offline','Local bridge unreachable');service('nova','offline','Bridge unavailable','collaborate');service('gemini-local','offline','Bridge unavailable','duo');}renderPause();}
  async function loadPresence(){try{var r=await fetchTimed('/api/presence',1800),j=r.ok?await r.json():{},members=j.members||[],claude=members.find(function(x){return x.id==='claude';});service('claude',claude?(claude.state||'ready'):'offline',claude?('Heartbeat '+(claude.location?'from '+claude.location:'received')):'No current Claude heartbeat','claude');$('liveCount').textContent=members.length;}catch(e){service('claude','offline','Presence service unavailable','claude');$('liveCount').textContent='0';}}
  async function loadChatGPT(){try{var r=await fetchTimed('/api/chatgpt-connector/status',2200),j=r.ok?await r.json():{},s=j.status||{},seat=s.codingSeat||{},app=s.chatApp||{},platform=s.platformMcp||{};service('codex',seat.loginVerified?'ready':'offline',seat.loginVerified?'Authenticated coding seat verified':'Codex coding seat is not verified','chatgpt');service('chatgpt',platform.connected&&platform.safeTunnel?'ready':app.appOpen?'paused':'offline',platform.connected&&platform.safeTunnel?'Platform MCP safe tunnel connected':app.appOpen?'ChatGPT app open; platform handoff remains manual':'ChatGPT connector unavailable','chatgpt');}catch(e){service('codex','offline','Status endpoint unavailable','chatgpt');service('chatgpt','offline','Status endpoint unavailable','chatgpt');}}
  async function loadGrok(){try{var r=await fetchTimed('/api/grok/status',2200),j=r.ok?await r.json():{},s=j.status||{},st=s.state==='tripped'?'tripped':s.state||'offline';service('grok',st,s.installed?(st==='tripped'?('Guardian tripped · '+(s.guardianReason||'review required')):'Grok Build '+st+' · Guardian armed'):'Grok Build not installed','guardian');}catch(e){service('grok','offline','Grok status unavailable','guardian');}}
  async function loadGuardian(){try{var r=await fetchTimed('/api/shell-guardian/status',1800),j=r.ok?await r.json():{},s=j.status||{};service('guardian',s.tripped?'tripped':'armed',s.tripped?((s.reason||'Severe trigger')+' · human reset required'):'Circuit breaker armed · normal creation remains open','guardian');}catch(e){service('guardian','offline','Guardian status endpoint unavailable','guardian');}}
  async function loadNotices(){try{var r=await fetchTimed('/api/presence/notices',1800),j=r.ok?await r.json():{};notices=(j.notices||[]).filter(function(n){return n&&n.state!=='acknowledged';});}catch(e){notices=[];}renderNotices();}
  function renderNotices(){var root=$('attentionInbox');$('noticeCount').textContent=notices.length;if(!notices.length){root.innerHTML='<div class="empty">No open questions, proposals or warnings. Quiet is a valid team state.</div>';return;}root.innerHTML=notices.map(function(n){var type=n.type||'message',mark=type==='question'?'?':type==='proposal'?'◆':type==='warning'?'!':'•';return'<article class="notice-card '+esc(type)+'"><span class="notice-mark">'+mark+'</span><div><small>'+esc((n.fromName||n.fromId||'Collaborator')+' · '+type.toUpperCase())+'</small><b>'+esc(n.message||'Notice')+'</b>'+(n.context?'<p>'+esc(n.context)+'</p>':'')+'</div><div class="notice-actions"><button data-open-notice="'+esc(n.id)+'">Open in Talk</button><button data-ack-notice="'+esc(n.id)+'">Acknowledge</button></div></article>';}).join('');root.querySelectorAll('[data-open-notice]').forEach(function(b){b.onclick=function(){openNoticeInTalk(notices.find(function(n){return n.id===b.dataset.openNotice;}));};});root.querySelectorAll('[data-ack-notice]').forEach(function(b){b.onclick=function(){ackNotice(b.dataset.ackNotice);};});}
  function openNoticeInTalk(notice){if(!notice)return;localStorage.setItem('axm.collaboration.notice.open',JSON.stringify(notice));var f=frames.task;if(f.dataset.loaded)f.src=f.src;selectView('collaborate');toast('Notice context opened in Collaboration & Tasks');}
  async function ackNotice(id){var notice=notices.find(function(n){return n.id===id;});if(!notice)return;try{var r=await fetchTimed('/api/presence/notice/ack',1800,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:id,by:localStorage.getItem('axm.presence.name')||'Mike'})});if(!r.ok)throw Error('HTTP '+r.status);notices=notices.filter(function(n){return n.id!==id;});renderNotices();toast('Notice acknowledged · no approval was inferred');}catch(e){toast('Could not acknowledge notice');}}
  function renderServices(){var root=$('serviceGrid'),healthy=0;root.innerHTML=Core.SERVICES.map(function(def){var s=services.get(def.id)||{state:'offline',detail:'Not checked'},good=['ready','active','armed'].indexOf(s.state)>=0;if(good)healthy++;return'<article class="service-card"><header><div><h4>'+esc(def.name)+'</h4><small>'+esc(def.kind)+'</small></div><span class="service-state '+esc(s.state)+'">'+esc(s.state.toUpperCase())+'</span></header><p>'+esc(s.detail)+'</p>'+(s.action?'<button data-service-action="'+esc(s.action)+'" data-service-name="'+esc(def.name)+'">'+(s.action==='guardian'||s.action==='chatgpt'||s.action==='claude'?'Open dashboard →':'Manage in AI Team →')+'</button>':'')+'</article>';}).join('');$('healthyCount').textContent=healthy;root.querySelectorAll('[data-service-action]').forEach(function(b){b.onclick=function(){var action=b.dataset.serviceAction;if(frames[action])selectView(action);else openServiceDetail(action,b.dataset.serviceName);};});var available=Array.from(services.values()).filter(function(s){return s.state!=='offline';}).length;$('presenceTitle').textContent=paused?'Local agents paused':available+' AI services visible';$('presenceDetail').textContent=paused?'Connectors remain visible while local inference is held':'Status is live; identity and connector boundaries remain separate';}
  async function refreshAll(){if(refreshing)return;refreshing=true;clearTimeout(pollTimer);services.clear();$('statusText').textContent='Refreshing actual service state…';try{await Promise.allSettled([loadBridge(),loadPresence(),loadChatGPT(),loadGrok(),loadGuardian(),loadNotices()]);renderServices();$('statusText').textContent='AI Team status checked · '+new Date().toLocaleTimeString();}finally{refreshing=false;pollTimer=setTimeout(refreshAll,6500);}}
  function renderPause(){var b=$('pauseLocal');b.classList.toggle('paused',paused);b.querySelector('b').textContent=paused?'Resume local AI':'Pause local AI';b.setAttribute('aria-pressed',paused?'true':'false');}
  async function togglePause(){var b=$('pauseLocal');b.disabled=true;try{var r=await fetchTimed(BRIDGE+'/agents/pause',2200,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({paused:!paused})});if(!r.ok)throw Error('HTTP '+r.status);var j=await r.json();paused=!!j.paused;toast(paused?'Local AI agents paused; connectors remain visible':'Local AI agents resumed');}catch(e){toast('Local pause gate is unreachable');}b.disabled=false;renderPause();refreshAll();}
  var serviceFrames={chatgpt:$('chatgptFrame'),claude:$('claudeFrame'),guardian:$('guardianFrame')};
  function openServiceDetail(route,name){route=route==='grok'?'guardian':route;if(!serviceFrames[route])return;Object.keys(serviceFrames).forEach(function(key){serviceFrames[key].hidden=key!==route;});ensureFrame(serviceFrames[route]);$('serviceDetailTitle').textContent=(name||Core.SERVICES.find(function(s){return s.id===route;}).name)+' dashboard';$('serviceDetail').hidden=false;$('serviceDetail').scrollIntoView({behavior:'smooth',block:'start'});}
  function closeServiceDetail(){$('serviceDetail').hidden=true;Object.keys(serviceFrames).forEach(function(key){serviceFrames[key].hidden=true;});}
  var DATA_STORE='axm.ai-team.data-runs.v1',dataState=loadDataState();
  function uid(prefix){return prefix+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7);}
  function loadDataState(){try{var d=JSON.parse(localStorage.getItem(DATA_STORE)||'null');if(d&&d.schema==='axm.ai-team.data-runs/v1')return{schema:d.schema,datasets:Array.isArray(d.datasets)?d.datasets:[],runs:Array.isArray(d.runs)?d.runs:[],activeDatasetId:d.activeDatasetId||null};}catch(e){}return{schema:'axm.ai-team.data-runs/v1',datasets:[],runs:[],activeDatasetId:null};}
  function saveData(message){localStorage.setItem(DATA_STORE,JSON.stringify(dataState));if(window.AXMHub)AXMHub.save({workspace:state,dataLedger:{datasets:dataState.datasets.length,runs:dataState.runs.length}});renderDataWorkspace();if(message)toast(message);}
  function activeDataset(){return dataState.datasets.find(function(d){return d.id===dataState.activeDatasetId;})||dataState.datasets[0]||null;}
  function renderDataWorkspace(){var ds=activeDataset();if(ds&&!dataState.activeDatasetId)dataState.activeDatasetId=ds.id;var options=dataState.datasets.map(function(d){return'<option value="'+esc(d.id)+'" '+(ds&&d.id===ds.id?'selected':'')+'>'+esc(d.name)+'</option>';}).join('');$('datasetSelect').innerHTML=options||'<option value="">Create a dataset first</option>';$('runDataset').innerHTML=options||'<option value="">No dataset</option>';$('datasetTotal').textContent=dataState.datasets.length;$('exampleTotal').textContent=dataState.datasets.reduce(function(n,d){return n+(d.examples||[]).length;},0);$('runTotal').textContent=dataState.runs.length;
    var examples=ds&&Array.isArray(ds.examples)?ds.examples:[];$('exampleList').innerHTML=examples.length?examples.slice().reverse().map(function(x){return'<article class="record"><header><div><b>'+esc((x.output||'Unlabelled').slice(0,90))+'</b><small>'+esc((x.tags||[]).join(' · ')||'no tags')+'</small></div><span class="record-state '+(x.reviewed?'reviewed':'')+'">'+(x.reviewed?'REVIEWED':'NEEDS REVIEW')+'</span></header><p>'+esc(x.input||'')+'</p><div class="record-actions"><button data-review-example="'+esc(x.id)+'">'+(x.reviewed?'Reopen review':'Mark reviewed')+'</button><button class="danger" data-delete-example="'+esc(x.id)+'">Delete</button></div></article>';}).join(''):'<div class="empty">'+(ds?'No examples in this dataset yet.':'Create a dataset to begin.')+'</div>';
    $('runList').innerHTML=dataState.runs.length?dataState.runs.slice().reverse().map(function(r){var d=dataState.datasets.find(function(x){return x.id===r.datasetId;});return'<article class="record"><header><div><b>'+esc(r.name)+'</b><small>'+esc((d?d.name:'missing dataset')+' · '+(r.model||'model not recorded'))+'</small></div><span class="record-state '+(r.accepted?'accepted':'')+'">'+esc(r.accepted?'ACCEPTED':r.status)+'</span></header><p>'+esc(r.evidence||'No evidence note recorded.')+'</p><div class="record-actions">'+(r.status==='PLANNED'?'<button data-run-state="'+esc(r.id)+'" data-next="RUNNING">Start</button>':'')+(r.status==='RUNNING'?'<button data-run-state="'+esc(r.id)+'" data-next="COMPLETED">Complete</button><button data-run-state="'+esc(r.id)+'" data-next="FAILED">Fail</button>':'')+((r.status==='COMPLETED'||r.status==='FAILED')?'<button data-accept-run="'+esc(r.id)+'">'+(r.accepted?'Reopen review':'Accept evidence')+'</button>':'')+'<button class="danger" data-delete-run="'+esc(r.id)+'">Delete</button></div></article>';}).join(''):'<div class="empty">No training runs recorded.</div>';
    $('exampleList').querySelectorAll('[data-review-example]').forEach(function(b){b.onclick=function(){var x=examples.find(function(e){return e.id===b.dataset.reviewExample;});if(x){x.reviewed=!x.reviewed;x.reviewedAt=x.reviewed?new Date().toISOString():null;saveData(x.reviewed?'Example reviewed':'Example returned to review');}};});$('exampleList').querySelectorAll('[data-delete-example]').forEach(function(b){b.onclick=function(){if(!confirm('Delete this labelled example?'))return;ds.examples=examples.filter(function(e){return e.id!==b.dataset.deleteExample;});saveData('Example deleted');};});$('runList').querySelectorAll('[data-run-state]').forEach(function(b){b.onclick=function(){var r=dataState.runs.find(function(x){return x.id===b.dataset.runState;});if(r){r.status=b.dataset.next;r.updatedAt=new Date().toISOString();r.accepted=false;saveData('Run marked '+r.status);}};});$('runList').querySelectorAll('[data-accept-run]').forEach(function(b){b.onclick=function(){var r=dataState.runs.find(function(x){return x.id===b.dataset.acceptRun;});if(r){r.accepted=!r.accepted;r.acceptedAt=r.accepted?new Date().toISOString():null;saveData(r.accepted?'Run evidence accepted by human':'Run returned to review');}};});$('runList').querySelectorAll('[data-delete-run]').forEach(function(b){b.onclick=function(){if(!confirm('Delete this training-run record?'))return;dataState.runs=dataState.runs.filter(function(r){return r.id!==b.dataset.deleteRun;});saveData('Run record deleted');};});}
  function createDataset(){var name=$('datasetName').value.trim(),purpose=$('datasetPurpose').value.trim();if(!name)return toast('Dataset name required');var d={id:uid('dataset'),name:name.slice(0,80),purpose:purpose.slice(0,180),createdAt:new Date().toISOString(),examples:[]};dataState.datasets.push(d);dataState.activeDatasetId=d.id;$('datasetName').value='';$('datasetPurpose').value='';saveData('Dataset created');}
  function addExample(){var ds=activeDataset(),input=$('exampleInput').value.trim(),output=$('exampleOutput').value.trim();if(!ds)return toast('Create a dataset first');if(!input||!output)return toast('Input and reviewed output are both required');ds.examples=Array.isArray(ds.examples)?ds.examples:[];ds.examples.push({id:uid('example'),input:input,output:output,tags:$('exampleTags').value.split(',').map(function(x){return x.trim();}).filter(Boolean).slice(0,20),reviewed:false,createdAt:new Date().toISOString()});$('exampleInput').value='';$('exampleOutput').value='';$('exampleTags').value='';saveData('Labelled example added · human review still needed');}
  function addRun(){var name=$('runName').value.trim(),datasetId=$('runDataset').value,status=$('runStatus').value,evidence=$('runEvidence').value.trim();if(!name||!datasetId)return toast('Run name and dataset are required');if((status==='COMPLETED'||status==='FAILED')&&!evidence)return toast('Completed or failed runs need an evidence note');dataState.runs.push({id:uid('run'),name:name.slice(0,100),datasetId:datasetId,model:$('runModel').value.trim().slice(0,120),status:status,evidence:evidence.slice(0,3000),accepted:false,createdAt:new Date().toISOString()});$('runName').value='';$('runModel').value='';$('runEvidence').value='';saveData('Training run recorded · not accepted automatically');}
  function childFrame(source){return[].slice.call(document.querySelectorAll('.team-frame,.service-frame')).find(function(f){return f.contentWindow===source;});}
  function routePromptComparison(message,source){if(source!==frames.prompts.contentWindow||!message||message.schema!=='axm.ai-team-prompt/v1'||message.type!=='axm-ai-team-prompt')return false;var p=message.prompt||{},text=String(p.text||'').slice(0,16000);if(!text){toast('Prompt handoff refused · empty prompt');return true;}pendingPrompt={id:String(p.id||''),title:String(p.title||'Prompt comparison').slice(0,120),revision:Math.max(1,Number(p.revision)||1),text:text,role:String(p.role||'any-model').slice(0,80),provider:String(p.provider||'').slice(0,120),tags:Array.isArray(p.tags)?p.tags.slice(0,20).map(String):[]};selectView('models');if(frames.models.dataset.ready){frames.models.contentWindow.postMessage({schema:'axm.ai-team-prompt/v1',type:'axm-model-compare-prompt',prompt:pendingPrompt},'*');pendingPrompt=null;}toast('Prompt revision routed to Model Evaluation');return true;}
  window.addEventListener('message',function(ev){routePromptComparison(ev.data,ev.source);});
  window.addEventListener('message',function(ev){var msg=ev.data;if(!msg||typeof msg.type!=='string'||msg.type.indexOf('hub:')!==0)return;var child=childFrame(ev.source);if(!child)return;var key='axm.ai-team.child.'+child.id;if(msg.type==='hub:ready')ev.source.postMessage({type:'hub:init',moduleId:'ai-team',settings:{},moduleState:JSON.parse(localStorage.getItem(key)||'null'),granted:[]},'*');if(msg.type==='hub:save'){localStorage.setItem(key,JSON.stringify(msg.state||{}));persist();}if(msg.type==='hub:settings:get')ev.source.postMessage({type:'hub:settings:value',settings:{}},'*');if(msg.type==='hub:log'&&window.AXMHub)AXMHub.log('AI Team · '+String(msg.msg||''),msg.level||'info');});
  renderNav();document.querySelectorAll('[data-open-view]').forEach(function(b){b.onclick=function(){selectView(b.dataset.openView);};});$('refreshAll').onclick=refreshAll;$('pauseLocal').onclick=togglePause;$('openGuardian').onclick=function(){openServiceDetail('guardian','Shell Guardian');};$('closeServiceDetail').onclick=closeServiceDetail;$('createDataset').onclick=createDataset;$('addExample').onclick=addExample;$('addRun').onclick=addRun;$('datasetSelect').onchange=function(){dataState.activeDatasetId=this.value;saveData();};document.addEventListener('visibilitychange',function(){if(!document.hidden)refreshAll();});
  if(window.AXMHub){AXMHub.onInit(function(){AXMHub.log('AI Team v1.1 ready · tools, prompts, model comparison and data ledgers consolidated');});AXMHub.onShutdown(function(){persist();clearTimeout(pollTimer);});AXMHub.ready({id:'ai-team',name:'AXM AI Team',version:'v1.1',hubApiVersion:'1.0',permissions:[],savesState:true,handlesShutdown:true});}
  try{var pendingNotice=JSON.parse(localStorage.getItem('axm.collaboration.notice.open')||'null');if(pendingNotice&&pendingNotice.message)state.view='collaborate';}catch(e){}
  selectView(state.view,true);refreshAll();
})();
