(function(){
  'use strict';
  var Core=window.AXMAITeamCore,Orientation=window.AXMOrientationCore,STORE='axm.ai-team.workspace.v1',ORIENTATION_STORE='axm.ai-team.orientation-ledger.v0.1',BRIDGE='http://127.0.0.1:8787',$=function(id){return document.getElementById(id);};
  var state,services=new Map(),notices=[],paused=false,pollTimer=null,refreshing=false,pendingPrompt=null,garden=null,activeExplorationId=null,specialistLibrary=null,selectedSpecialistId=null,returnCheckoutId=null,specialistRecommendation=null;
  try{state=Core.normalize(JSON.parse(localStorage.getItem(STORE)||'null'));}catch(e){state=Core.normalize({});}
  var icons={
    home:'<path d="M4 11l8-7 8 7v9H5z"/><path d="M9 20v-6h6v6"/>',
    glasses:'<path d="M3 9h7l1 2h2l1-2h7"/><path d="M4 9l1 7h4l2-5M20 9l-1 7h-4l-2-5"/><path d="M2 9l2-2M22 9l-2-2"/>',
    chat:'<path d="M4 5h16v11H9l-5 4z"/><path d="M8 9h8M8 12h5"/>',
    duo:'<circle cx="8" cy="10" r="4"/><circle cx="17" cy="10" r="3"/><path d="M2 21c1-4 3-6 6-6s5 2 6 6M14 16c3 0 5 2 6 5"/>',
    agent:'<circle cx="12" cy="8" r="4"/><path d="M4 21c1-5 4-7 8-7s7 2 8 7M5 4l2 2M19 4l-2 2"/>',
    specialist:'<path d="M4 5h16v14H4z"/><path d="M8 9h8M8 13h5M17 16l2 2 3-4"/>',
    tool:'<path d="M14 5l5 5-9 9H5v-5z"/><path d="M13 6l2-2 5 5-2 2"/>',
    prompt:'<path d="M6 3h9l3 3v15H6z"/><path d="M9 9h6M9 13h6M9 17h4"/>',
    model:'<path d="M4 7l8-4 8 4-8 4zM4 7v10l8 4 8-4V7M12 11v10"/>',
    reason:'<path d="M9 18h6M10 21h4"/><path d="M8 14c-2-1-3-3-3-5a7 7 0 0114 0c0 2-1 4-3 5-1 1-1 2-1 2H9s0-1-1-2z"/>',
    explore:'<path d="M12 2l2.1 5.4L20 9l-4.6 3.7L16 19l-4-3-4 3 .6-6.3L4 9l5.9-1.6z"/><path d="M12 7v5l3 2"/>',
    data:'<ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v6c0 2 4 3 8 3s8-1 8-3V5M4 11v6c0 2 4 3 8 3s8-1 8-3v-6"/>',
    service:'<circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M19 5l-2 2M7 17l-2 2"/>'
  };
  function svg(name){return'<svg viewBox="0 0 24 24" aria-hidden="true">'+icons[name]+'</svg>';}
  function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function toast(text){var t=$('toast');t.textContent=text;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(function(){t.classList.remove('show');},2100);}
  function persist(message){state.updatedAt=new Date().toISOString();localStorage.setItem(STORE,JSON.stringify(state));$('saveState').textContent='Saved '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});if(window.AXMHub)AXMHub.save({workspace:state});if(message)toast(message);}
  function loadOrientationLedger(){var empty={schema:'axm.ai-team.orientation-ledger/v0.1',packets:[]};try{var saved=JSON.parse(localStorage.getItem(ORIENTATION_STORE)||'null');if(saved&&saved.schema===empty.schema&&Array.isArray(saved.packets))empty.packets=saved.packets.filter(function(p){return Orientation&&Orientation.validate(p).ok;}).slice(-50);}catch(e){}return empty;}
  var orientationLedger=loadOrientationLedger();
  function orientationOwnerId(name){return String(name||'unassigned').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,100)||'unassigned';}
  function saveOrientationLedger(message){orientationLedger.packets=orientationLedger.packets.slice(-50);localStorage.setItem(ORIENTATION_STORE,JSON.stringify(orientationLedger));if(window.AXMHub)AXMHub.save({workspace:state,orientationLedger:{schema:orientationLedger.schema,count:orientationLedger.packets.length}});renderOrientation();if(message)toast(message);}
  function renderBoundaryOptions(){if(!Orientation)return;var select=$('orientationBoundaryType');Orientation.listBoundaryTypes().forEach(function(item){var option=document.createElement('option');option.value=item.type;option.textContent=item.label;select.appendChild(option);});}
  function saveOrientation(){if(!Orientation)return toast('Orientation contract is unavailable');var owner=$('orientationOwner').value.trim(),purpose=$('orientationPurpose').value.trim(),nextTest=$('orientationNextTest').value.trim(),type=$('orientationBoundaryType').value,note=$('orientationBoundaryNote').value.trim();if(!owner||!purpose)return toast('Who is working and the purpose are required');if(!nextTest)return toast('Add the smallest honest next test');if(type&&!note)return toast('Describe what happened at the named boundary');if(!type&&$('orientationBlocking').checked)return toast('Choose the boundary that is stopping progress');var boundaries=type?[{type:type,detail:note,blocking:$('orientationBlocking').checked,evidenceRefs:[]}]:[];try{var packet=Orientation.create({owner:{id:orientationOwnerId(owner),name:owner,kind:$('orientationOwnerKind').value},purpose:purpose,currentTerrain:$('orientationTerrain').value.trim(),sourceInterfaces:['AI Team Orientation Desk'],observations:lines('orientationObservations'),interpretations:lines('orientationInterpretations'),uncertainties:lines('orientationUncertainties'),boundaries:boundaries,nextTest:nextTest,permittedUpdateScope:['append orientation card'],authority:{deciderId:'local-human',actionLimit:'Orient, recommend, and preserve evidence only.'}});orientationLedger.packets.push(packet);['orientationPurpose','orientationTerrain','orientationObservations','orientationInterpretations','orientationUncertainties','orientationBoundaryNote','orientationNextTest'].forEach(function(id){$(id).value='';});$('orientationBoundaryType').value='';$('orientationBlocking').checked=false;saveOrientationLedger('Orientation card saved · no action or approval implied');}catch(e){toast(e.message);}}
  function orientationText(packet){var r=Orientation.reentry(packet),rows=['CONTINUE FROM ORIENTATION '+r.packetId,'State: '+r.state,'Owner: '+r.owner.name+' ('+r.owner.kind+')','Purpose: '+r.purpose,'Current focus: '+(r.currentTerrain||'Not recorded'),'Observed: '+(r.observed.join(' | ')||'None recorded'),'Working interpretation: '+(r.workingInterpretations.join(' | ')||'None recorded'),'Uncertain or unseen: '+(r.uncertainties.join(' | ')||'None recorded')];if(r.boundaries.length)rows.push('Boundary: '+r.boundaries.map(function(b){return b.label+': '+b.detail+(b.blocking?' [BLOCKING]':'');}).join(' | '));rows.push('Next test: '+(r.nextTest||'Not recorded'),'Truth: re-entry summary only; no automatic resume, approval, authority transfer, or copied project state.');return rows.join('\n');}
  function copyText(value,success){if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(value).then(function(){toast(success);}).catch(function(){fallback();});}else fallback();function fallback(){var area=document.createElement('textarea');area.value=value;area.setAttribute('readonly','');area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();try{document.execCommand('copy');toast(success);}catch(e){toast('Copy is unavailable in this browser');}document.body.removeChild(area);}}
  function downloadOrientation(packet){var blob=new Blob([JSON.stringify(packet,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=packet.id+'.json';document.body.appendChild(a);a.click();document.body.removeChild(a);URL.revokeObjectURL(url);toast('Orientation packet downloaded');}
  function renderOrientation(){var packets=orientationLedger.packets.slice().reverse(),root=$('orientationList');$('orientationCount').textContent=packets.length;root.innerHTML=packets.length?packets.map(function(p){var boundary=(p.boundaries||[])[0],observed=(p.observations||[]).map(function(x){return x.statement;}).join('\n'),interpreted=(p.interpretations||[]).map(function(x){return x.statement;}).join('\n');return'<article class="orientation-card '+(p.state==='BLOCKED'?'blocked':'')+'"><header><div><b>'+esc(p.purpose)+'</b><small>'+esc(p.owner.name+' · '+new Date(p.updatedAt).toLocaleString())+'</small></div><span class="orientation-state">'+esc(p.state)+'</span></header>'+(p.currentTerrain?'<p class="orientation-terrain">'+esc(p.currentTerrain)+'</p>':'')+'<div class="orientation-facts"><div><b>Observed</b><span>'+esc(observed||'None recorded.')+'</span></div><div><b>Working interpretation</b><span>'+esc(interpreted||'None recorded.')+'</span></div></div><div class="orientation-uncertain"><b>Uncertain or unseen</b><span>'+esc((p.uncertainties||[]).join('\n')||'None recorded.')+'</span></div>'+(boundary?'<div class="orientation-boundary"><b>'+esc(boundary.label)+(boundary.blocking?' · BLOCKING':'')+'</b><span>'+esc(boundary.detail+'\n'+boundary.recommendedResponse)+'</span></div>':'')+'<div class="orientation-next"><b>Next test</b><span>'+esc(p.nextTest||'Not recorded.')+'</span></div><div class="orientation-actions"><button data-copy-orientation="'+esc(p.id)+'">Copy re-entry summary</button><button data-download-orientation="'+esc(p.id)+'">Download JSON</button></div></article>';}).join(''):'<div class="empty">No orientation cards yet.</div>';root.querySelectorAll('[data-copy-orientation]').forEach(function(b){b.onclick=function(){var p=orientationLedger.packets.find(function(x){return x.id===b.dataset.copyOrientation;});if(p)copyText(orientationText(p),'Re-entry summary copied');};});root.querySelectorAll('[data-download-orientation]').forEach(function(b){b.onclick=function(){var p=orientationLedger.packets.find(function(x){return x.id===b.dataset.downloadOrientation;});if(p)downloadOrientation(p);};});}
  function ensureFrame(frame){if(frame&&frame.dataset.src&&!frame.dataset.loaded){frame.src=frame.dataset.src;frame.dataset.loaded='1';}}
  function renderNav(){var nav=$('viewNav');nav.innerHTML='';Core.groups().forEach(function(group){var title=document.createElement('div');title.className='view-group-title';title.textContent=group.name;nav.appendChild(title);group.views.forEach(function(view){var b=document.createElement('button');b.className='view-button';b.dataset.view=view.id;b.innerHTML='<span class="nav-icon">'+svg(view.icon)+'</span><b></b>';b.querySelector('b').textContent=view.short;b.onclick=function(){selectView(view.id);};nav.appendChild(b);});});}
  var frames={technical:$('technicalFrame'),task:$('taskFrame'),duo:$('duoFrame'),agents:$('agentsFrame'),forge:$('forgeFrame'),prompts:$('promptsFrame'),models:$('modelsFrame'),reasoning:$('reasoningFrame'),learning:$('learningFrame')};
  Object.keys(frames).forEach(function(key){frames[key].addEventListener('load',function(){this.dataset.ready='1';if(key==='models'&&pendingPrompt){this.contentWindow.postMessage({schema:'axm.ai-team-prompt/v1',type:'axm-model-compare-prompt',prompt:pendingPrompt},'*');pendingPrompt=null;}});});
  function selectView(id,silent){var view=Core.byId(id);state.view=view.id;document.querySelectorAll('.view-button').forEach(function(b){b.classList.toggle('active',b.dataset.view===view.id);});$('viewGroup').textContent=view.group+' view';$('viewTitle').textContent=view.title;$('viewDescription').textContent=view.description;$('overviewSurface').hidden=view.route!=='native';$('servicesSurface').hidden=view.route!=='services';$('dataSurface').hidden=view.route!=='data';$('exploreSurface').hidden=view.route!=='explore';$('specialistSurface').hidden=view.route!=='specialists';$('frameSurface').hidden=['native','services','data','explore','specialists'].indexOf(view.route)>=0;Object.keys(frames).forEach(function(key){frames[key].hidden=key!==view.route;});if(frames[view.route])ensureFrame(frames[view.route]);if(view.route==='services')refreshAll();if(view.route==='data')renderDataWorkspace();if(view.route==='explore')loadGarden();if(view.route==='specialists')loadSpecialists();$('statusText').textContent=view.title+' ready';if(!silent)persist('Opened '+view.title);}
  function fetchTimed(url,ms,options){var c=new AbortController(),timer=setTimeout(function(){c.abort();},ms||2500),opts=options||{};opts.cache='no-store';opts.signal=c.signal;return fetch(url,opts).finally(function(){clearTimeout(timer);});}
  function service(id,stateName,detail,action){services.set(id,{state:stateName||'offline',detail:detail||'Unavailable',action:action||null});}
  async function loadBridge(){try{var h=await fetchTimed(BRIDGE+'/health',2200);if(!h.ok)throw Error('HTTP '+h.status);var gate={};try{var g=await fetchTimed(BRIDGE+'/agent-state',2200);if(g.ok)gate=await g.json();}catch(e){}paused=!!gate.paused;service('bridge',paused?'paused':'ready',paused?'Local agent gate is paused':'Local bridge connected and accepting supervised routes','agents');var ids=[];try{var m=await fetchTimed(BRIDGE+'/local-models',3000);if(m.ok){var mj=await m.json();ids=(mj.data||[]).map(function(x){return String(x.id||'').toLowerCase();});}}catch(e){}service('nova',ids.indexOf('axm-llama-3.1-8b')>=0?(paused?'paused':'active'):'offline',ids.indexOf('axm-llama-3.1-8b')>=0?'axm-llama-3.1-8b loaded':'Local model service unavailable or Nova is not loaded','collaborate');service('gemini-local',ids.indexOf('gemini-local')>=0?(paused?'paused':'active'):'offline',ids.indexOf('gemini-local')>=0?'gemini-local loaded':'Local model service unavailable or Gemini Local is not loaded','duo');}catch(e){paused=false;service('bridge','offline','Local bridge unreachable');service('nova','offline','Bridge unavailable','collaborate');service('gemini-local','offline','Bridge unavailable','duo');}renderPause();}
  async function loadPresence(){try{var r=await fetchTimed('/api/presence',1800),j=r.ok?await r.json():{},members=j.members||[],claude=members.find(function(x){return x.id==='claude';});service('claude',claude?(claude.state||'ready'):'offline',claude?('Heartbeat '+(claude.location?'from '+claude.location:'received')):'No current Claude heartbeat','claude');$('liveCount').textContent=members.length;}catch(e){service('claude','offline','Presence service unavailable','claude');$('liveCount').textContent='0';}}
  async function loadMirror(){try{var r=await fetchTimed('/api/mirror-native/status',1800),j=r.ok?await r.json():{},s=j.status||{};service('mirror',s.running?'ready':'offline',s.running?('Seed-0 connected - '+(s.body||'deterministic kernel')+' - learned weights '+(s.learnedWeights?'present':'absent')):s.installed?'Seed-0 installed but explicitly offline':'Mirror Native body not installed');}catch(e){service('mirror','offline','Mirror Native status unavailable');}}
  async function loadChatGPT(){try{var r=await fetchTimed('/api/chatgpt-connector/status',2200),j=r.ok?await r.json():{},s=j.status||{},seat=s.codingSeat||{},app=s.chatApp||{},platform=s.platformMcp||{};service('codex',seat.loginVerified?'ready':'offline',seat.loginVerified?'Authenticated coding seat verified':'Codex coding seat is not verified','chatgpt');service('chatgpt',platform.connected&&platform.safeTunnel?'ready':app.appOpen?'paused':'offline',platform.connected&&platform.safeTunnel?'Platform MCP safe tunnel connected':app.appOpen?'ChatGPT app open; platform handoff remains manual':'ChatGPT connector unavailable','chatgpt');}catch(e){service('codex','offline','Status endpoint unavailable','chatgpt');service('chatgpt','offline','Status endpoint unavailable','chatgpt');}}
  async function loadGrok(){try{var r=await fetchTimed('/api/grok/status',2200),j=r.ok?await r.json():{},s=j.status||{},st=s.state==='tripped'?'tripped':s.state||'offline';service('grok',st,s.installed?(st==='tripped'?('Guardian tripped · '+(s.guardianReason||'review required')):'Grok Build '+st+' · Guardian armed'):'Grok Build not installed','guardian');}catch(e){service('grok','offline','Grok status unavailable','guardian');}}
  async function loadGuardian(){try{var r=await fetchTimed('/api/shell-guardian/status',1800),j=r.ok?await r.json():{},s=j.status||{};service('guardian',s.tripped?'tripped':'armed',s.tripped?((s.reason||'Severe trigger')+' · human reset required'):'Circuit breaker armed · normal creation remains open','guardian');}catch(e){service('guardian','offline','Guardian status endpoint unavailable','guardian');}}
  async function loadNotices(){try{var r=await fetchTimed('/api/presence/notices',1800),j=r.ok?await r.json():{};notices=(j.notices||[]).filter(function(n){return n&&n.state!=='acknowledged';});}catch(e){notices=[];}renderNotices();}
  function renderNotices(){var root=$('attentionInbox');$('noticeCount').textContent=notices.length;if(!notices.length){root.innerHTML='<div class="empty">No open questions, proposals or warnings. Quiet is a valid team state.</div>';return;}root.innerHTML=notices.map(function(n){var type=n.type||'message',mark=type==='question'?'?':type==='proposal'?'◆':type==='warning'?'!':'•';return'<article class="notice-card '+esc(type)+'"><span class="notice-mark">'+mark+'</span><div><small>'+esc((n.fromName||n.fromId||'Collaborator')+' · '+type.toUpperCase())+'</small><b>'+esc(n.message||'Notice')+'</b>'+(n.context?'<p>'+esc(n.context)+'</p>':'')+'</div><div class="notice-actions"><button data-open-notice="'+esc(n.id)+'">Open in Talk</button><button data-ack-notice="'+esc(n.id)+'">Acknowledge</button></div></article>';}).join('');root.querySelectorAll('[data-open-notice]').forEach(function(b){b.onclick=function(){openNoticeInTalk(notices.find(function(n){return n.id===b.dataset.openNotice;}));};});root.querySelectorAll('[data-ack-notice]').forEach(function(b){b.onclick=function(){ackNotice(b.dataset.ackNotice);};});}
  function openNoticeInTalk(notice){if(!notice)return;localStorage.setItem('axm.collaboration.notice.open',JSON.stringify(notice));var f=frames.task;if(f.dataset.loaded)f.src=f.src;selectView('collaborate');toast('Notice context opened in Collaboration & Tasks');}
  async function ackNotice(id){var notice=notices.find(function(n){return n.id===id;});if(!notice)return;try{var r=await fetchTimed('/api/presence/notice/ack',1800,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:id,by:localStorage.getItem('axm.presence.name')||'Mike'})});if(!r.ok)throw Error('HTTP '+r.status);notices=notices.filter(function(n){return n.id!==id;});renderNotices();toast('Notice acknowledged · no approval was inferred');}catch(e){toast('Could not acknowledge notice');}}
  function renderServices(){var root=$('serviceGrid'),healthy=0;root.innerHTML=Core.SERVICES.map(function(def){var s=services.get(def.id)||{state:'offline',detail:'Not checked'},good=['ready','active','armed'].indexOf(s.state)>=0;if(good)healthy++;return'<article class="service-card"><header><div><h4>'+esc(def.name)+'</h4><small>'+esc(def.kind)+'</small></div><span class="service-state '+esc(s.state)+'">'+esc(s.state.toUpperCase())+'</span></header><p>'+esc(s.detail)+'</p>'+(s.action?'<button data-service-action="'+esc(s.action)+'" data-service-name="'+esc(def.name)+'">'+(s.action==='guardian'||s.action==='chatgpt'||s.action==='claude'?'Open dashboard →':'Manage in AI Team →')+'</button>':'')+'</article>';}).join('');$('healthyCount').textContent=healthy;root.querySelectorAll('[data-service-action]').forEach(function(b){b.onclick=function(){var action=b.dataset.serviceAction;if(frames[action])selectView(action);else openServiceDetail(action,b.dataset.serviceName);};});var available=Array.from(services.values()).filter(function(s){return s.state!=='offline';}).length;$('presenceTitle').textContent=paused?'Local agents paused':available+' AI services visible';$('presenceDetail').textContent=paused?'Connectors remain visible while local inference is held':'Status is live; identity and connector boundaries remain separate';}
  async function refreshAll(){if(refreshing)return;refreshing=true;clearTimeout(pollTimer);services.clear();$('statusText').textContent='Refreshing actual service state…';try{await Promise.allSettled([loadBridge(),loadPresence(),loadChatGPT(),loadGrok(),loadMirror(),loadGuardian(),loadNotices()]);renderServices();$('statusText').textContent='AI Team status checked · '+new Date().toLocaleTimeString();}finally{refreshing=false;pollTimer=setTimeout(refreshAll,6500);}}
  function renderPause(){var b=$('pauseLocal');b.classList.toggle('paused',paused);b.querySelector('b').textContent=paused?'Resume local AI':'Pause local AI';b.setAttribute('aria-pressed',paused?'true':'false');}
  async function togglePause(){var b=$('pauseLocal');b.disabled=true;try{var r=await fetchTimed(BRIDGE+'/agents/pause',2200,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({paused:!paused})});if(!r.ok)throw Error('HTTP '+r.status);var j=await r.json();paused=!!j.paused;toast(paused?'Local AI agents paused; connectors remain visible':'Local AI agents resumed');}catch(e){toast('Local pause gate is unreachable');}b.disabled=false;renderPause();refreshAll();}
  var serviceFrames={chatgpt:$('chatgptFrame'),claude:$('claudeFrame'),guardian:$('guardianFrame')};
  function openServiceDetail(route,name){route=route==='grok'?'guardian':route;if(!serviceFrames[route])return;Object.keys(serviceFrames).forEach(function(key){serviceFrames[key].hidden=key!==route;});ensureFrame(serviceFrames[route]);$('serviceDetailTitle').textContent=(name||Core.SERVICES.find(function(s){return s.id===route;}).name)+' dashboard';$('serviceDetail').hidden=false;$('serviceDetail').scrollIntoView({behavior:'smooth',block:'start'});}
  function closeServiceDetail(){$('serviceDetail').hidden=true;Object.keys(serviceFrames).forEach(function(key){serviceFrames[key].hidden=true;});}
  function specialistCall(path,method,body,receipt){return fetchTimed('/api/specialists'+path,3500,{method:method||'GET',headers:body?{'content-type':'application/json','x-axm-specialist':receipt||'identity-action'}:{},body:body?JSON.stringify(body):undefined}).then(function(r){return r.json().catch(function(){return{};}).then(function(j){if(!r.ok)throw Error(j.error||('specialist HTTP '+r.status));return j;});});}
  function loadSpecialists(){return specialistCall('','GET').then(function(j){specialistLibrary=j.library;renderSpecialists();}).catch(function(e){toast(e.message);});}
  function selectedSpecialist(){return specialistLibrary&&(specialistLibrary.catalog||[]).find(function(x){return x.id===selectedSpecialistId;});}
  function renderSpecialists(){if(!specialistLibrary)return;renderCapabilityBridges();var all=specialistLibrary.catalog||[],q=$('specialistSearch').value.trim().toLowerCase(),category=$('specialistCategory').value,visible=all.filter(function(m){var hay=[m.title,m.category,m.purpose,m.fearedFailure].concat(m.methods||[],m.requiredEvidence||[]).join(' ').toLowerCase();return(!category||m.category===category)&&(!q||hay.indexOf(q)>=0);});$('specialistTotal').textContent=all.length;$('specialistVisible').textContent=visible.length+' shown';$('specialistCatalog').innerHTML=visible.length?visible.map(function(m){return'<button class="specialist-card '+(m.id===selectedSpecialistId?'active':'')+'" data-specialist="'+esc(m.id)+'"><span>'+esc(m.category)+' · '+esc(m.source.roleId)+'</span><b>'+esc(m.title)+'</b><small>'+esc((m.methods||[]).slice(0,2).join(' · '))+'</small></button>';}).join(''):'<div class="empty">No specialists match this search.</div>';$('specialistCatalog').querySelectorAll('[data-specialist]').forEach(function(b){b.onclick=function(){selectedSpecialistId=b.dataset.specialist;renderSpecialists();};});renderSpecialistDetail();renderSpecialistCheckouts();}
  function renderCapabilityBridges(){var skills=window.AXMCapabilityBridges?AXMCapabilityBridges.list():[];$('capabilityBridgeShelf').innerHTML=skills.length?skills.map(function(s){return'<article><span>'+esc(s.kind)+'</span><b>'+esc(s.title)+'</b><p>'+esc(s.whenNeeded)+'</p><small>'+esc((s.provides||[]).join(' · '))+'</small></article>';}).join(''):'<div class="empty">Capability bridge contracts unavailable.</div>';}
  function chipList(title,items,tone){return'<div class="specialist-facts '+(tone||'')+'"><b>'+esc(title)+'</b><div>'+((items||[]).map(function(x){return'<span>'+esc(x)+'</span>';}).join('')||'<span>None declared</span>')+'</div></div>';}
  function renderSpecialistDetail(){var m=selectedSpecialist();$('checkoutSpecialist').disabled=!m;if(!m){$('specialistDetail').innerHTML='<div class="empty">Choose a specialist to inspect its inputs, tools, method, output contract and boundaries.</div>';return;}var rp=m.runtimeProfile||{},tools=(rp.tools||[]).map(function(t){return t.capability+' · '+t.mode+' · '+t.requestedPermission;}),inputs=(rp.inputs&&rp.inputs.required)||[],outputs=(rp.artifact&&rp.artifact.requiredFields)||[];$('specialistDetail').innerHTML='<header><div><span class="eyebrow">'+esc(m.category+' · '+m.source.packTitle)+'</span><h3>'+esc(m.title)+'</h3><p>'+esc(m.purpose)+'</p></div><div class="mask-head-actions"><span class="mask-version">v'+esc(m.version)+'</span><button data-download-mask="'+esc(m.id)+'">Download mask JSON</button></div></header>'+chipList('Focus questions',rp.focusQuestions||[],'focus-facts')+chipList('Required inputs',inputs,'input-facts')+chipList('Gated tool capabilities',tools,'tool-facts')+chipList('Required output · '+((rp.artifact&&rp.artifact.type)||'artifact'),outputs,'output-facts')+chipList('Jurisdiction',m.jurisdiction)+chipList('Professional methods',m.methods)+chipList('Required evidence',m.requiredEvidence,'evidence')+'<div class="specialist-artifact"><b>Artifact contract</b><p>'+esc(m.artifactContract)+'</p><b>Feared failure</b><p>'+esc(m.fearedFailure)+'</p></div>'+chipList('Abstain when',m.abstentionConditions,'boundary-facts')+chipList('Forbidden overreach',m.forbiddenOverreach,'danger-facts')+'<p class="independence-warning">'+esc(m.independenceWarning)+'</p>';$('specialistDetail').querySelector('[data-download-mask]').onclick=function(){downloadSpecialistMask(m.id);};}
  function capabilitiesFor(p,screen,visual){if(p==='text-local')return{nativeVision:false,nativeImageGeneration:false,nativeToolCalling:false,strictJson:false,largeContext:false,needsScreenObservation:screen,needsVisualComposition:visual};if(p==='tool-text')return{nativeVision:false,nativeImageGeneration:false,nativeToolCalling:true,strictJson:true,largeContext:true,needsScreenObservation:screen,needsVisualComposition:visual};if(p==='multimodal')return{nativeVision:true,nativeImageGeneration:true,nativeToolCalling:true,strictJson:true,largeContext:true,needsScreenObservation:screen,needsVisualComposition:visual};return{};}
  function modelCapabilities(){return capabilitiesFor($('specialistModelPreset').value,$('needsScreenObservation').checked,$('needsVisualComposition').checked);}
  function routerCapabilities(){return capabilitiesFor($('routerModelPreset').value,$('routerNeedsScreen').checked,$('routerNeedsVisual').checked);}
  function recommendSpecialists(){var task=$('routerTask').value.trim();if(!task)return toast('Describe the task first');$('recommendSpecialists').disabled=true;specialistCall('/recommend','POST',{task:task,maxSpecialists:Number($('routerTeamSize').value),modelCapabilities:routerCapabilities()},'recommendation-request').then(function(j){specialistRecommendation=j.recommendation;renderRecommendation();toast('Recommendation ready · nothing assigned');}).catch(function(e){toast(e.message);}).finally(function(){$('recommendSpecialists').disabled=false;});}
  function renderRecommendation(){var r=specialistRecommendation,root=$('routerResults');if(!r){root.innerHTML='<div class="empty">No recommendation requested. Nothing will be assigned automatically.</div>';return;}root.innerHTML='<div class="router-truth"><b>Recommendation only</b><span>'+esc(r.nextAction)+'</span></div>'+r.recommendations.map(function(x){var bridges=(x.capabilityBridges.selected||[]).map(function(s){return s.title;});return'<article class="router-card"><span>STEP '+x.sequence+' · '+esc(x.confidence)+' HEURISTIC</span><h4>'+esc(x.specialist.title)+'</h4><p>'+esc(x.reason)+'</p><small>'+esc(x.matchedSignals.length?'Matched: '+x.matchedSignals.join(' · '):'Balanced fallback because the task is underspecified')+'</small>'+(bridges.length?'<div>Bridge skills: '+esc(bridges.join(' · '))+'</div>':'<div>No fallback skill selected yet</div>')+'<button data-prepare-specialist="'+esc(x.specialist.id)+'">Inspect & prepare checkout</button></article>';}).join('');root.querySelectorAll('[data-prepare-specialist]').forEach(function(b){b.onclick=function(){prepareRecommendation(b.dataset.prepareSpecialist);};});}
  function prepareRecommendation(maskId){var item=specialistRecommendation&&specialistRecommendation.recommendations.find(function(x){return x.specialist.id===maskId;});if(!item)return;selectedSpecialistId=maskId;$('specialistTask').value=specialistRecommendation.task;$('specialistLease').value=item.suggestedLeaseMinutes;$('specialistModelPreset').value=$('routerModelPreset').value;$('needsScreenObservation').checked=$('routerNeedsScreen').checked;$('needsVisualComposition').checked=$('routerNeedsVisual').checked;renderSpecialists();$('specialistDetail').scrollIntoView({behavior:'smooth',block:'start'});toast('Checkout form prepared · still not assigned');}
  function downloadSpecialistMask(maskId){fetchTimed('/api/specialists/package/'+encodeURIComponent(maskId),3500).then(function(r){return r.json().then(function(j){if(!r.ok)throw Error(j.error||('HTTP '+r.status));var a=document.createElement('a');a.download='axm-specialist-'+maskId.replace(/[^a-z0-9]+/gi,'-').toLowerCase()+'.json';a.href=URL.createObjectURL(new Blob([JSON.stringify(j.package,null,2)],{type:'application/json'}));a.click();setTimeout(function(){URL.revokeObjectURL(a.href);},500);toast('Loadable specialist package downloaded');});}).catch(function(e){toast(e.message);});}
  function checkoutSpecialist(){var m=selectedSpecialist();if(!m)return;var body={actorId:$('specialistActorId').value.trim(),actorName:$('specialistActorName').value.trim(),actorKind:$('specialistActorKind').value,connectorId:$('specialistConnector').value.trim(),modelCapabilities:modelCapabilities(),specialistId:m.id,task:$('specialistTask').value.trim(),leaseMinutes:Number($('specialistLease').value),identityBinding:{}};specialistCall('/checkout','POST',body,'identity-action').then(function(j){specialistLibrary=j.library;$('specialistTask').value='';renderSpecialists();var selected=j.packet&&j.packet.loadableMask&&j.packet.loadableMask.runtime.capabilityBridges.selected||[];toast(m.title+' checked out · '+selected.length+' capability bridge'+(selected.length===1?'':'s')+' attached · no permissions granted');}).catch(function(e){toast(e.message);});}
  function renderSpecialistCheckouts(){if(!specialistLibrary)return;var items=(specialistLibrary.checkouts||[]).slice().reverse();$('specialistCheckoutCount').textContent=items.filter(function(x){return x.state==='ACTIVE';}).length+' active';$('specialistCheckouts').innerHTML=items.length?items.map(function(x){var result=x.result&&x.result.summary?'<p>'+esc(x.result.summary)+'</p>':'';return'<article class="checkout-card '+esc(x.state.toLowerCase())+'"><header><div><b>'+esc(x.specialist.title)+'</b><small>'+esc(x.actorName+' · '+x.specialist.source.roleId)+'</small></div><span>'+esc(x.state)+'</span></header><p>'+esc(x.task)+'</p>'+result+'<footer><small>'+(x.state==='ACTIVE'?'expires '+new Date(x.expiresAt).toLocaleString():'returned '+new Date(x.returnedAt||x.expiresAt).toLocaleString())+'</small>'+(x.state==='ACTIVE'?'<button data-return-specialist="'+esc(x.id)+'">Return →</button>':'')+'</footer></article>';}).join(''):'<div class="empty">No specialist has been checked out.</div>';$('specialistCheckouts').querySelectorAll('[data-return-specialist]').forEach(function(b){b.onclick=function(){openSpecialistReturn(b.dataset.returnSpecialist);};});}
  function openSpecialistReturn(checkoutId){var x=(specialistLibrary.checkouts||[]).find(function(c){return c.id===checkoutId;});if(!x)return;returnCheckoutId=x.id;$('specialistReturnTitle').textContent='Return '+x.specialist.title;$('specialistReturnBy').value=x.actorId;$('specialistReturn').hidden=false;$('specialistReturn').scrollIntoView({behavior:'smooth',block:'start'});}
  function closeSpecialistReturn(){returnCheckoutId=null;$('specialistReturn').hidden=true;}
  function lines(id){return $(id).value.split(/\r?\n/).map(function(x){return x.trim();}).filter(Boolean);}
  function returnSpecialist(){if(!returnCheckoutId)return;var structured=null,raw=$('specialistStructured').value.trim();if(raw){try{structured=JSON.parse(raw);}catch(e){toast('Structured result JSON is invalid');return;}}var body={checkoutId:returnCheckoutId,returnedById:$('specialistReturnBy').value.trim(),relevance:$('specialistRelevance').value,summary:$('specialistSummary').value.trim(),evidence:lines('specialistEvidence'),artifact:$('specialistArtifact').value.trim(),limitations:lines('specialistLimitations'),structuredResult:structured,learning:$('specialistLearning').value.trim(),learningEvidence:$('specialistLearningEvidence').value.trim()};specialistCall('/return','POST',body,'identity-action').then(function(j){specialistLibrary=j.library;['specialistSummary','specialistEvidence','specialistArtifact','specialistLimitations','specialistStructured','specialistLearning','specialistLearningEvidence'].forEach(function(id){$(id).value='';});closeSpecialistReturn();renderSpecialists();toast('Specialist returned with evidence · '+(structured?'structured output validated':'manual summary labelled')+' · learning remains candidate');}).catch(function(e){toast(e.message);});}
  function exploreCall(path,method,body,receipt){return fetchTimed('/api/exploration'+path,3000,{method:method||'GET',headers:body?{'content-type':'application/json','x-axm-exploration':receipt||'identity-action'}:{},body:body?JSON.stringify(body):undefined}).then(function(r){return r.json().catch(function(){return{};}).then(function(j){if(!r.ok)throw Error(j.error||('exploration HTTP '+r.status));return j;});});}
  function loadGarden(){return exploreCall('','GET').then(function(j){garden=j.garden;renderGarden();}).catch(function(e){toast(e.message);});}
  function selectedExploration(){return garden&&(garden.sessions||[]).find(function(item){return item.id===activeExplorationId;});}
  function renderGarden(){if(!garden)return;$('exploreState').textContent=garden.enabled?'OPEN':'OFF';$('exploreState').classList.toggle('on',garden.enabled);$('exploreStateNote').textContent=garden.enabled?'Bounded identity explorations may run; proposals still require discussion.':'Nothing can start until the local user opts in.';$('exploreEnable').hidden=garden.enabled;$('exploreDisable').hidden=!garden.enabled;$('startExploration').disabled=!garden.enabled;var sessions=garden.sessions||[];$('exploreCount').textContent=sessions.length;$('explorationList').innerHTML=sessions.length?sessions.slice().reverse().map(function(item){return'<button class="exploration-card '+esc(item.state.toLowerCase())+'" data-exploration="'+esc(item.id)+'"><span>'+esc(item.kind)+' · '+esc(item.state)+'</span><b>'+esc(item.title)+'</b><small>'+esc(item.ownerName)+' · '+item.artifacts.length+' artifact'+(item.artifacts.length===1?'':'s')+' · '+item.wisdomCandidates.length+' wisdom candidate'+(item.wisdomCandidates.length===1?'':'s')+'</small></button>';}).join(''):'<div class="empty">No explorations yet.</div>';$('explorationList').querySelectorAll('[data-exploration]').forEach(function(button){button.onclick=function(){activeExplorationId=button.dataset.exploration;renderExplorationDetail();};});renderExplorationDetail();}
  function renderExplorationDetail(){var item=selectedExploration();$('explorationDetail').hidden=!item;if(!item)return;$('exploreDetailKind').textContent=item.kind+' · '+item.state;$('exploreDetailTitle').textContent=item.title;$('exploreDetailMeta').textContent=item.ownerName+' · '+item.timeBudgetMin+' minute budget · started '+new Date(item.createdAt).toLocaleString();$('exploreDetailTruth').innerHTML='<b>Question</b><span>'+esc(item.question)+'</span><b>Boundary</b><span>'+esc(item.boundary)+'</span>';$('addArtifact').disabled=item.state!=='EXPLORING';$('addWisdom').disabled=item.state!=='EXPLORING';$('submitExploration').disabled=item.state!=='EXPLORING';var artifacts=item.artifacts||[],wisdom=item.wisdomCandidates||[];$('exploreArtifacts').innerHTML='<div><h4>Artifacts</h4>'+(artifacts.length?artifacts.map(function(a){return'<article><span>'+esc(a.type)+'</span><b>'+esc(a.title)+'</b><p>'+esc(a.summary)+'</p><small>'+esc(a.evidence)+(a.path?' · '+esc(a.path):'')+'</small></article>';}).join(''):'<div class="empty">No evidenced artifact yet.</div>')+'</div><div><h4>Wisdom candidates</h4>'+(wisdom.length?wisdom.map(function(w){return'<article><span>CANDIDATE</span><b>'+esc(w.statement)+'</b><small>'+esc(w.evidence)+'</small></article>';}).join(''):'<div class="empty">No wisdom candidates. That is valid.</div>')+'</div>';$('exploreDiscussion').hidden=item.state!=='DISCUSSION';if(item.state==='DISCUSSION'){$('exploreComments').innerHTML=(item.comments||[]).length?item.comments.map(function(c){return'<article class="discussion-comment '+esc(c.stance)+'"><header><b>'+esc(c.authorName)+'</b><span>'+esc(c.stance)+'</span></header><p>'+esc(c.body)+'</p></article>';}).join(''):'<div class="empty">Proposal raised. Discussion has not started yet.</div>';}}
  function enableGarden(enabled){exploreCall(enabled?'/opt-in':'/opt-out','POST',{decidedBy:'local-human'},enabled?'local-opt-in':'local-opt-out').then(function(j){garden=j.garden;renderGarden();toast(enabled?'Exploration Garden opted in':'Exploration Garden paused');}).catch(function(e){toast(e.message);});}
  function startExploration(){var body={ownerId:$('exploreOwnerId').value.trim(),ownerName:$('exploreOwnerName').value.trim(),kind:$('exploreKind').value,title:$('exploreTitle').value.trim(),question:$('exploreQuestion').value.trim(),boundary:$('exploreBoundary').value.trim(),timeBudgetMin:Number($('exploreBudget').value)};exploreCall('/start','POST',body,'identity-action').then(function(j){garden=j.garden;activeExplorationId=j.session.id;['exploreTitle','exploreQuestion','exploreBoundary'].forEach(function(id){$(id).value='';});renderGarden();toast('Exploration started · bounded draft space only');}).catch(function(e){toast(e.message);});}
  function addExplorationArtifact(){var item=selectedExploration();if(!item)return;var body={sessionId:item.id,type:$('artifactType').value,title:$('artifactTitle').value.trim(),summary:$('artifactSummary').value.trim(),evidence:$('artifactEvidence').value.trim(),path:$('artifactPath').value.trim()};exploreCall('/artifact','POST',body,'identity-action').then(function(j){garden=j.garden;['artifactTitle','artifactSummary','artifactEvidence','artifactPath'].forEach(function(id){$(id).value='';});renderGarden();toast('Evidenced draft artifact saved');}).catch(function(e){toast(e.message);});}
  function addExplorationWisdom(){var item=selectedExploration();if(!item)return;exploreCall('/wisdom','POST',{sessionId:item.id,statement:$('wisdomStatement').value.trim(),evidence:$('wisdomEvidence').value.trim()},'identity-action').then(function(j){garden=j.garden;$('wisdomStatement').value='';$('wisdomEvidence').value='';renderGarden();toast('Wisdom saved as candidate · not promoted');}).catch(function(e){toast(e.message);});}
  function submitExploration(){var item=selectedExploration();if(!item)return;exploreCall('/submit','POST',{sessionId:item.id,qualityClaim:$('proposalQuality').value.trim(),whyAXM:$('proposalFit').value.trim(),risks:$('proposalRisks').value.trim(),nextTest:$('proposalNext').value.trim()},'identity-action').then(function(j){garden=j.garden;renderGarden();loadNotices();toast('Proposal raised for discussion · no installation implied');}).catch(function(e){toast(e.message);});}
  function addExplorationComment(){var item=selectedExploration();if(!item)return;exploreCall('/comment','POST',{sessionId:item.id,authorId:$('commentAuthorId').value.trim(),authorName:$('commentAuthorName').value.trim(),stance:$('commentStance').value,body:$('commentBody').value.trim()},'discussion-comment').then(function(j){garden=j.garden;$('commentBody').value='';renderGarden();toast('Discussion comment added');}).catch(function(e){toast(e.message);});}

  var DATA_STORE='axm.ai-team.data-runs.v1',dataState=loadDataState();
  function uid(prefix){return prefix+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7);}
  function loadDataState(){try{var d=JSON.parse(localStorage.getItem(DATA_STORE)||'null');if(d&&d.schema==='axm.ai-team.data-runs/v1')return{schema:d.schema,datasets:Array.isArray(d.datasets)?d.datasets:[],runs:Array.isArray(d.runs)?d.runs:[],activeDatasetId:d.activeDatasetId||null};}catch(e){}return{schema:'axm.ai-team.data-runs/v1',datasets:[],runs:[],activeDatasetId:null};}
  function saveData(message){localStorage.setItem(DATA_STORE,JSON.stringify(dataState));if(window.AXMHub)AXMHub.save({workspace:state,dataLedger:{datasets:dataState.datasets.length,runs:dataState.runs.length}});renderDataWorkspace();if(message)toast(message);}
  function activeDataset(){return dataState.datasets.find(function(d){return d.id===dataState.activeDatasetId;})||dataState.datasets[0]||null;}
  function renderDataWorkspace(){var ds=activeDataset();if(ds&&!dataState.activeDatasetId)dataState.activeDatasetId=ds.id;var options=dataState.datasets.map(function(d){return'<option value="'+esc(d.id)+'" '+(ds&&d.id===ds.id?'selected':'')+'>'+esc(d.name)+'</option>';}).join('');$('datasetSelect').innerHTML=options||'<option value="">Create a dataset first</option>';$('runDataset').innerHTML=options||'<option value="">No dataset</option>';$('datasetTotal').textContent=dataState.datasets.length;$('exampleTotal').textContent=dataState.datasets.reduce(function(n,d){return n+(d.examples||[]).length;},0);$('runTotal').textContent=dataState.runs.length;
    var examples=ds&&Array.isArray(ds.examples)?ds.examples:[];$('exampleList').innerHTML=examples.length?examples.slice().reverse().map(function(x){return'<article class="record"><header><div><b>'+esc((x.output||'Unlabelled').slice(0,90))+'</b><small>'+esc((x.tags||[]).join(' · ')||'no tags')+'</small></div><span class="record-state '+(x.reviewed?'reviewed':'')+'">'+(x.reviewed?'REVIEWED':'NEEDS REVIEW')+'</span></header><p>'+esc(x.input||'')+'</p><div class="record-actions"><button data-review-example="'+esc(x.id)+'">'+(x.reviewed?'Reopen review':'Mark reviewed')+'</button><button class="danger" data-delete-example="'+esc(x.id)+'">Delete</button></div></article>';}).join(''):'<div class="empty">'+(ds?'No examples in this dataset yet.':'Create a dataset to begin.')+'</div>';
    $('runList').innerHTML=dataState.runs.length?dataState.runs.slice().reverse().map(function(r){var d=dataState.datasets.find(function(x){return x.id===r.datasetId;});return'<article class="record"><header><div><b>'+esc(r.name)+'</b><small>'+esc((d?d.name:'missing dataset')+' · '+(r.model||'model not recorded'))+'</small></div><span class="record-state '+(r.accepted?'accepted':'')+'">'+esc(r.accepted?'ACCEPTED':r.status)+'</span></header><p>'+esc(r.evidence||'No evidence note recorded.')+'</p><div class="record-actions">'+(r.status==='PLANNED'?'<button data-run-state="'+esc(r.id)+'" data-next="RUNNING">Start</button>':'')+(r.status==='RUNNING'?'<button data-run-state="'+esc(r.id)+'" data-next="COMPLETED">Complete</button><button data-run-state="'+esc(r.id)+'" data-next="FAILED">Fail</button>':'')+((r.status==='COMPLETED'||r.status==='FAILED')?'<button data-accept-run="'+esc(r.id)+'">'+(r.accepted?'Reopen review':'Accept evidence')+'</button>':'')+'<button class="danger" data-delete-run="'+esc(r.id)+'">Delete</button></div></article>';}).join(''):'<div class="empty">No training runs recorded.</div>';
    $('exampleList').querySelectorAll('[data-review-example]').forEach(function(b){b.onclick=function(){var x=examples.find(function(e){return e.id===b.dataset.reviewExample;});if(x){x.reviewed=!x.reviewed;x.reviewedAt=x.reviewed?new Date().toISOString():null;saveData(x.reviewed?'Example reviewed':'Example returned to review');}};});$('exampleList').querySelectorAll('[data-delete-example]').forEach(function(b){b.onclick=function(){if(!confirm('Delete this labelled example?'))return;ds.examples=examples.filter(function(e){return e.id!==b.dataset.deleteExample;});saveData('Example deleted');};});$('runList').querySelectorAll('[data-run-state]').forEach(function(b){b.onclick=function(){var r=dataState.runs.find(function(x){return x.id===b.dataset.runState;});if(r){r.status=b.dataset.next;r.updatedAt=new Date().toISOString();r.accepted=false;saveData('Run marked '+r.status);}};});$('runList').querySelectorAll('[data-accept-run]').forEach(function(b){b.onclick=function(){var r=dataState.runs.find(function(x){return x.id===b.dataset.acceptRun;});if(r){r.accepted=!r.accepted;r.acceptedAt=r.accepted?new Date().toISOString():null;saveData(r.accepted?'Run evidence accepted by human':'Run returned to review');}};});$('runList').querySelectorAll('[data-delete-run]').forEach(function(b){b.onclick=function(){if(!confirm('Delete this training-run record?'))return;dataState.runs=dataState.runs.filter(function(r){return r.id!==b.dataset.deleteRun;});saveData('Run record deleted');};});}
  function createDataset(){var name=$('datasetName').value.trim(),purpose=$('datasetPurpose').value.trim();if(!name)return toast('Dataset name required');var d={id:uid('dataset'),name:name.slice(0,80),purpose:purpose.slice(0,180),createdAt:new Date().toISOString(),examples:[]};dataState.datasets.push(d);dataState.activeDatasetId=d.id;$('datasetName').value='';$('datasetPurpose').value='';saveData('Dataset created');}
  function addExample(){var ds=activeDataset(),input=$('exampleInput').value.trim(),output=$('exampleOutput').value.trim();if(!ds)return toast('Create a dataset first');if(!input||!output)return toast('Input and reviewed output are both required');ds.examples=Array.isArray(ds.examples)?ds.examples:[];ds.examples.push({id:uid('example'),input:input,output:output,tags:$('exampleTags').value.split(',').map(function(x){return x.trim();}).filter(Boolean).slice(0,20),reviewed:false,createdAt:new Date().toISOString()});$('exampleInput').value='';$('exampleOutput').value='';$('exampleTags').value='';saveData('Labelled example added · human review still needed');}
  function addRun(){var name=$('runName').value.trim(),datasetId=$('runDataset').value,status=$('runStatus').value,evidence=$('runEvidence').value.trim();if(!name||!datasetId)return toast('Run name and dataset are required');if((status==='COMPLETED'||status==='FAILED')&&!evidence)return toast('Completed or failed runs need an evidence note');dataState.runs.push({id:uid('run'),name:name.slice(0,100),datasetId:datasetId,model:$('runModel').value.trim().slice(0,120),status:status,evidence:evidence.slice(0,3000),accepted:false,createdAt:new Date().toISOString()});$('runName').value='';$('runModel').value='';$('runEvidence').value='';saveData('Training run recorded · not accepted automatically');}
  function childFrame(source){return[].slice.call(document.querySelectorAll('.team-frame,.service-frame')).find(function(f){return f.contentWindow===source;});}
  function routePromptComparison(message,source){if(source!==frames.prompts.contentWindow||!message||message.schema!=='axm.ai-team-prompt/v1'||message.type!=='axm-ai-team-prompt')return false;var p=message.prompt||{},text=String(p.text||'').slice(0,16000);if(!text){toast('Prompt handoff refused · empty prompt');return true;}pendingPrompt={id:String(p.id||''),title:String(p.title||'Prompt comparison').slice(0,120),revision:Math.max(1,Number(p.revision)||1),text:text,role:String(p.role||'any-model').slice(0,80),provider:String(p.provider||'').slice(0,120),tags:Array.isArray(p.tags)?p.tags.slice(0,20).map(String):[]};selectView('models');if(frames.models.dataset.ready){frames.models.contentWindow.postMessage({schema:'axm.ai-team-prompt/v1',type:'axm-model-compare-prompt',prompt:pendingPrompt},'*');pendingPrompt=null;}toast('Prompt revision routed to Model Evaluation');return true;}
  window.addEventListener('message',function(ev){routePromptComparison(ev.data,ev.source);});
  window.addEventListener('message',function(ev){var msg=ev.data;if(!msg||typeof msg.type!=='string'||msg.type.indexOf('hub:')!==0)return;var child=childFrame(ev.source);if(!child)return;var key='axm.ai-team.child.'+child.id;if(msg.type==='hub:ready')ev.source.postMessage({type:'hub:init',moduleId:'ai-team',settings:{},moduleState:JSON.parse(localStorage.getItem(key)||'null'),granted:[]},'*');if(msg.type==='hub:save'){localStorage.setItem(key,JSON.stringify(msg.state||{}));persist();}if(msg.type==='hub:settings:get')ev.source.postMessage({type:'hub:settings:value',settings:{}},'*');if(msg.type==='hub:log'&&window.AXMHub)AXMHub.log('AI Team · '+String(msg.msg||''),msg.level||'info');});
  renderNav();renderBoundaryOptions();renderOrientation();document.querySelectorAll('[data-open-view]').forEach(function(b){b.onclick=function(){selectView(b.dataset.openView);};});$('refreshAll').onclick=refreshAll;$('pauseLocal').onclick=togglePause;$('saveOrientation').onclick=saveOrientation;$('openGuardian').onclick=function(){openServiceDetail('guardian','Shell Guardian');};$('closeServiceDetail').onclick=closeServiceDetail;$('recommendSpecialists').onclick=recommendSpecialists;$('specialistSearch').oninput=renderSpecialists;$('specialistCategory').onchange=renderSpecialists;$('checkoutSpecialist').onclick=checkoutSpecialist;$('closeSpecialistReturn').onclick=closeSpecialistReturn;$('returnSpecialist').onclick=returnSpecialist;$('exploreEnable').onclick=function(){enableGarden(true);};$('exploreDisable').onclick=function(){enableGarden(false);};$('startExploration').onclick=startExploration;$('addArtifact').onclick=addExplorationArtifact;$('addWisdom').onclick=addExplorationWisdom;$('submitExploration').onclick=submitExploration;$('addExplorationComment').onclick=addExplorationComment;$('closeExploration').onclick=function(){activeExplorationId=null;renderExplorationDetail();};$('createDataset').onclick=createDataset;$('addExample').onclick=addExample;$('addRun').onclick=addRun;$('datasetSelect').onchange=function(){dataState.activeDatasetId=this.value;saveData();};document.addEventListener('visibilitychange',function(){if(!document.hidden)refreshAll();});
  if(window.AXMHub){AXMHub.onInit(function(){AXMHub.log('AI Team v1.7 ready · bounded orientation, Technical Glasses, Mirror learning, specialists, prompts and evidence ledgers');});AXMHub.onShutdown(function(){persist();clearTimeout(pollTimer);});AXMHub.ready({id:'ai-team',name:'AXM AI Team',version:'v1.7',hubApiVersion:'1.0',permissions:[],savesState:true,handlesShutdown:true});}
  try{var pendingNotice=JSON.parse(localStorage.getItem('axm.collaboration.notice.open')||'null');if(pendingNotice&&pendingNotice.message)state.view='collaborate';}catch(e){}
  selectView(state.view,true);refreshAll();
})();
