#!/usr/bin/env node
'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),Core=require('./ai-team-core.js');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const js=fs.readFileSync(path.join(__dirname,'ai-team.js'),'utf8');
const manifest=JSON.parse(fs.readFileSync(path.join(__dirname,'manifest.json'),'utf8'));
const contract=JSON.parse(fs.readFileSync(path.join(__dirname,'module.contract.json'),'utf8'));
assert.equal(Core.VIEWS.length,15);
assert.deepEqual(Core.groups().map(g=>g.name),['Control','Work','Build','Evaluate','Learn']);
assert.equal(Core.normalize({view:'ghost'}).view,'overview');
['technical','task','steward','duo','agents','forge','prompts','models','reasoning','learning','explore','data'].forEach(route=>assert.equal(Core.VIEWS.filter(v=>v.route===route).length,1));
assert.equal(Core.VIEWS.filter(v=>v.route==='specialists').length,1);
assert.ok(Core.SERVICES.some(s=>s.id==='guardian'));
assert.ok(html.includes('id="attentionInbox"')&&html.includes('id="serviceGrid"')&&html.includes('id="guardianFrame"'));
assert.ok(html.includes('id="technicalFrame"')&&html.includes('../technical-glasses/index.html')&&html.includes('id="forgeFrame"')&&html.includes('id="dataSurface"')&&html.includes('id="runList"'));
assert.ok(html.includes('id="stewardFrame"')&&html.includes('../ai-team-steward-lab/index.html?ai-team=1')&&js.includes("steward:$('stewardFrame')"));
assert.ok(html.includes('id="exploreSurface"')&&html.includes('id="explorationList"')&&html.includes('id="submitExploration"'));
assert.ok(html.includes('id="specialistSurface"')&&html.includes('id="capabilityBridgeShelf"')&&html.includes('id="routerTask"')&&html.includes('id="recommendSpecialists"')&&html.includes('id="specialistCatalog"')&&html.includes('id="specialistModelPreset"')&&html.includes('id="checkoutSpecialist"')&&html.includes('id="returnSpecialist"'));
assert.ok(js.includes('/api/presence/notices')&&js.includes('/api/shell-guardian/status')&&js.includes("'/agents/pause'"));
assert.ok(js.includes("service('bridge',paused?'paused':'ready'")&&js.includes('var ids=[];try{var m=await fetchTimed')&&js.includes('Local model service unavailable or Nova is not loaded'));
assert.ok(html.includes('Automatic approval is never implied')&&js.includes('openNoticeInTalk'));
assert.ok(js.includes("localStorage.getItem('axm.collaboration.notice.open')")&&js.includes("state.view='collaborate'"));
assert.ok(js.includes('if(refreshing)return')&&js.includes('refreshing=false'));
assert.ok(js.includes("schema:'axm.ai-team-prompt/v1'")&&js.includes('routePromptComparison'));
assert.ok(js.includes("DATA_STORE='axm.ai-team.data-runs.v1'")&&js.includes('Accept evidence'));
assert.ok(js.includes("'/api/exploration'")&&js.includes('Wisdom saved as candidate')&&js.includes('Proposal raised for discussion'));
assert.ok(js.includes("'/api/specialists'")&&js.includes('no permissions granted')&&js.includes('capability bridge')&&js.includes('structured output validated')&&js.includes('learning remains candidate'));
assert.ok(js.includes("specialistCall('/recommend'")&&js.includes('Recommendation ready · nothing assigned')&&js.includes('Checkout form prepared · still not assigned'));
assert.ok(html.includes('runtime-profiles.js')&&html.includes('capability-bridges.js')&&html.includes('specialist-router.js'));
assert.ok(html.includes('orientation.css')&&html.includes('/shared/orientation/axm-orientation-core.js')&&html.includes('id="orientationList"')&&html.includes('id="saveOrientation"')&&html.includes('What did we actually observe?')&&html.includes('What do we think it means?'));
assert.ok(js.includes("ORIENTATION_STORE='axm.ai-team.orientation-ledger.v0.1'")&&js.includes('Orientation.create')&&js.includes('Orientation.reentry')&&js.includes('Copy re-entry summary')&&js.includes('no automatic resume, approval, authority transfer, or copied project state'));
assert.equal(manifest.id,'ai-team');assert.equal(manifest.version,'v1.12');assert.equal(contract.version,'v1.12');assert.equal(contract.lifecycle.state_owner,'mixed');assert.ok(manifest.accepts.includes('axm.ai-repair-design-request/v1'));
assert.ok(contract.provides.includes('collaboration-contract-preflight-view')&&contract.provides.includes('source-parity-collaboration-operation-view')&&contract.consumes.includes('service:ai-team-steward'));
assert.ok(contract.boundaries.refuses.includes('automatic-guardian-reset'));
assert.ok(contract.boundaries.refuses.includes('automatic-shared-knowledge-rewrite'));
console.log('AI Team selftest: PASS (15 views, 100-seed local contract preflight, 58 source-parity operations, bounded orientation, live Technical Glasses, Mirror learning route, recommendation-only Specialist Router, evidence and Guardian)');
