#!/usr/bin/env node
'use strict';
const assert=require('assert'),fs=require('fs'),path=require('path'),Core=require('./ai-team-core.js');
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8');
const js=fs.readFileSync(path.join(__dirname,'ai-team.js'),'utf8');
const manifest=JSON.parse(fs.readFileSync(path.join(__dirname,'manifest.json'),'utf8'));
const contract=JSON.parse(fs.readFileSync(path.join(__dirname,'module.contract.json'),'utf8'));
assert.equal(Core.VIEWS.length,14);
assert.deepEqual(Core.groups().map(g=>g.name),['Control','Work','Build','Evaluate','Learn']);
assert.equal(Core.normalize({view:'ghost'}).view,'overview');
['technical','task','duo','agents','forge','prompts','models','reasoning','learning','explore','data'].forEach(route=>assert.equal(Core.VIEWS.filter(v=>v.route===route).length,1));
assert.equal(Core.VIEWS.filter(v=>v.route==='specialists').length,1);
assert.ok(Core.SERVICES.some(s=>s.id==='guardian'));
assert.ok(html.includes('id="attentionInbox"')&&html.includes('id="serviceGrid"')&&html.includes('id="guardianFrame"'));
assert.ok(html.includes('id="technicalFrame"')&&html.includes('../technical-glasses/index.html')&&html.includes('id="forgeFrame"')&&html.includes('id="dataSurface"')&&html.includes('id="runList"'));
assert.ok(html.includes('id="exploreSurface"')&&html.includes('id="explorationList"')&&html.includes('id="submitExploration"'));
assert.ok(html.includes('id="specialistSurface"')&&html.includes('id="capabilityBridgeShelf"')&&html.includes('id="routerTask"')&&html.includes('id="recommendSpecialists"')&&html.includes('id="specialistCatalog"')&&html.includes('id="specialistModelPreset"')&&html.includes('id="checkoutSpecialist"')&&html.includes('id="returnSpecialist"'));
assert.ok(js.includes('/api/presence/notices')&&js.includes('/api/shell-guardian/status')&&js.includes("'/agents/pause'"));
assert.ok(js.includes("service('bridge',paused?'paused':'ready'")&&js.includes('var ids=[];try{var m=await fetchTimed')&&js.includes('Local model service unavailable or Nova is not loaded'));
assert.ok(html.includes('Automatic approval is never implied')&&js.includes('openNoticeInTalk'));
assert.ok(js.includes("localStorage.getItem('axm.collaboration.notice.open')")&&js.includes("state.view='collaborate'"));
assert.ok(js.includes('if(refreshing)return')&&js.includes('refreshing=false'));
assert.ok(js.includes("schema:'axm.ai-team-prompt/v1'")&&js.includes('routePromptComparison'));
assert.ok(js.includes("DATA_STORE='axm.ai-team.data-runs.v1'")&&js.includes('Accept evidence'));
assert.ok(js.includes("'/api/exploration'")&&js.includes('Wisdom saved as candidate')&&js.includes('Proposal raised for discussion'));
assert.ok(js.includes("'/api/specialists'")&&js.includes('no permissions granted')&&js.includes('capability bridge')&&js.includes('structured output validated')&&js.includes('learning remains candidate'));
assert.ok(js.includes("specialistCall('/recommend'")&&js.includes('Recommendation ready · nothing assigned')&&js.includes('Checkout form prepared · still not assigned'));
assert.ok(html.includes('runtime-profiles.js')&&html.includes('capability-bridges.js')&&html.includes('specialist-router.js'));
assert.equal(manifest.id,'ai-team');assert.equal(contract.version,'v1.6');
assert.ok(contract.boundaries.refuses.includes('automatic-guardian-reset'));
console.log('AI Team selftest: PASS (14 views, live Technical Glasses, Mirror learning route, recommendation-only Specialist Router, AI-native masks, capability bridges, evidence and Guardian)');
