import { optimizeAsset, optimizationReceipt, serializeOptimization } from './mesh-optimizer-core.mjs';
import { verifyOptimization } from './mesh-optimizer-verifier.mjs';
import { transformPoint4 } from '../local-3d-game-runtime/native-math.mjs';

const assets={building:{label:'Commercial building G',copy:'Static architecture · one material group',url:'../ps2-asset-forge/assets/kenney/city-commercial/models/building-g.glb',sha:'9A28FA2FDFAC07492EE95589882213CFD6EB32D6752CB3B2F5404604C676D27A'},vehicle:{label:'Sports hatchback',copy:'Five-part vehicle · one material family',url:'../ps2-asset-forge/assets/kenney/car-kit/models/hatchback-sports.glb',sha:'BD5C9D4C3B4BDD254A66B8426563A68B1487AE7A5076DF3A2488E6FFED7BE64F'},person:{label:'Rigged pedestrian',copy:'Thirteen skins · 22 source animation clips',url:'../ps2-asset-forge/proof/exports/animated-pedestrian.glb',sha:'B448863767B1A770D70EFD45F04DDDF1BBA93B7855D1DBA7A9A6456115685D63'}};
const tabs=[...document.querySelectorAll('.asset')],ratioInput=document.querySelector('#ratio-input'),ratioOutput=document.querySelector('#ratio-output'),errorInput=document.querySelector('#error-input'),errorOutput=document.querySelector('#error-output'),boundaryInput=document.querySelector('#boundary-input'),optimizeButton=document.querySelector('#optimize-button'),exportButton=document.querySelector('#export-button'),assetTitle=document.querySelector('#asset-title'),assetCopy=document.querySelector('#asset-copy'),verdict=document.querySelector('#verdict'),verdictIcon=document.querySelector('#verdict-icon'),verdictTitle=document.querySelector('#verdict-title'),verdictCopy=document.querySelector('#verdict-copy'),checkScore=document.querySelector('#check-score'),sourceCanvas=document.querySelector('#source-canvas'),optimizedCanvas=document.querySelector('#optimized-canvas'),checkList=document.querySelector('#check-list'),receiptSha=document.querySelector('#receipt-sha'),receiptShort=document.querySelector('#receipt-short'),receiptJson=document.querySelector('#receipt-json');
const fields={sourceTriangles:document.querySelector('#source-triangles'),optimizedTriangles:document.querySelector('#optimized-triangles'),reduction:document.querySelector('#reduction'),vertices:document.querySelector('#vertices'),positionError:document.querySelector('#position-error'),uvError:document.querySelector('#uv-error'),weightError:document.querySelector('#weight-error'),groups:document.querySelector('#groups')};
let selected='building',currentResult=null,currentReceipt=null;
async function sha256(bytes){const digest=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(digest),value=>value.toString(16).padStart(2,'0')).join('').toUpperCase();}
async function textDigest(text){return sha256(new TextEncoder().encode(text).buffer);}
function stable(value){const sort=input=>Array.isArray(input)?input.map(sort):input&&typeof input==='object'?Object.fromEntries(Object.keys(input).sort().map(key=>[key,sort(input[key])])):input;return JSON.stringify(sort(value));}
function drawWireframe(canvas,primitives,color){const ratio=Math.min(devicePixelRatio||1,1.5),width=Math.max(320,canvas.clientWidth),height=Math.max(230,canvas.clientHeight);canvas.width=Math.round(width*ratio);canvas.height=Math.round(height*ratio);const context=canvas.getContext('2d'),projected=[],worldPoint=(primitive,index)=>{const local=[primitive.positions[index*3],primitive.positions[index*3+1],primitive.positions[index*3+2]];return primitive.previewMatrix?transformPoint4(primitive.previewMatrix,local):local;},project=point=>selected==='person'?[point[0],-point[1]]:[point[0]*.86-point[2]*.52,-point[1]+point[2]*.22];for(const primitive of primitives)for(let index=0;index<primitive.positions.length/3;index+=1)projected.push(project(worldPoint(primitive,index)));let minX=Infinity,maxX=-Infinity,minY=Infinity,maxY=-Infinity;for(const point of projected){minX=Math.min(minX,point[0]);maxX=Math.max(maxX,point[0]);minY=Math.min(minY,point[1]);maxY=Math.max(maxY,point[1]);}const scale=Math.min(canvas.width/Math.max(maxX-minX,.001),canvas.height/Math.max(maxY-minY,.001))*.82,offsetX=(canvas.width-(maxX-minX)*scale)/2-minX*scale,offsetY=(canvas.height-(maxY-minY)*scale)/2-minY*scale;context.clearRect(0,0,canvas.width,canvas.height);context.strokeStyle=color;context.lineWidth=.65*ratio;context.globalAlpha=.48;for(const primitive of primitives){const indices=primitive.indices,point=index=>project(worldPoint(primitive,index));for(let index=0;index<indices.length;index+=3){const a=point(indices[index]),b=point(indices[index+1]),c=point(indices[index+2]);context.beginPath();context.moveTo(a[0]*scale+offsetX,a[1]*scale+offsetY);context.lineTo(b[0]*scale+offsetX,b[1]*scale+offsetY);context.lineTo(c[0]*scale+offsetX,c[1]*scale+offsetY);context.closePath();context.stroke();}}}
function renderChecks(verification){checkList.replaceChildren(...verification.checks.map(item=>{const card=document.createElement('article');card.className=`check-item ${item.status}`;card.innerHTML=`<i>${item.status==='pass'?'✓':'×'}</i><div><strong>${item.label}</strong><small>${item.evidence}</small></div>`;return card;}));}
async function optimize(){const asset=assets[selected];optimizeButton.disabled=true;exportButton.disabled=true;verdict.className='verdict';verdictIcon.textContent='···';verdictTitle.textContent=`Optimizing ${asset.label}`;verdictCopy.textContent='Source bytes remain read-only while the candidate is built in memory.';try{const response=await fetch(asset.url);if(!response.ok)throw new Error(`${asset.label}: HTTP ${response.status}`);const bytes=await response.arrayBuffer(),sourceSha=await sha256(bytes);if(sourceSha!==asset.sha)throw new Error(`Source digest mismatch: ${sourceSha}`);currentResult=optimizeAsset(bytes,{targetRatio:Number(ratioInput.value)/100,errorLimit:Number(errorInput.value)/100,protectBoundaries:boundaryInput.checked});const verification=verifyOptimization(currentResult),receiptBase=optimizationReceipt(currentResult,{assetId:selected,sha256:sourceSha,byteLength:bytes.byteLength,immutable:true}),geometry=serializeOptimization(currentResult,receiptBase.source),geometrySha=await textDigest(stable(geometry)),receiptCore={...receiptBase,geometrySha256:geometrySha,verification},receiptDigest=await textDigest(stable(receiptCore));currentReceipt={...receiptCore,receiptSha256:receiptDigest};currentReceipt.geometry=geometry;
 const s=currentResult.summary;fields.sourceTriangles.textContent=s.sourceTriangles.toLocaleString('en-US');fields.optimizedTriangles.textContent=s.optimizedTriangles.toLocaleString('en-US');fields.reduction.textContent=`${(s.triangleReduction*100).toFixed(1)}%`;fields.vertices.textContent=`${s.sourceVertices.toLocaleString('en-US')} → ${s.optimizedVertices.toLocaleString('en-US')}`;fields.positionError.textContent=`${(s.maximumNormalizedPositionError*100).toFixed(3)}%`;fields.uvError.textContent=s.maximumUvError.toFixed(5);fields.weightError.textContent=s.maximumWeightError.toFixed(5);fields.groups.textContent=`${s.materialGroupsAfter} mat · ${s.riggedPrimitives} rig`;
 drawWireframe(sourceCanvas,currentResult.sourcePrimitives,'#55c9df');drawWireframe(optimizedCanvas,currentResult.optimizedPrimitives,'#59e593');renderChecks(verification);verdict.className=`verdict ${verification.status}`;verdictIcon.textContent=verification.status==='pass'?'✓':'×';verdictTitle.textContent=verification.status==='pass'?'Bounded candidate ready for human review':'Candidate blocked';verdictCopy.textContent=`${(s.triangleReduction*100).toFixed(1)}% triangles removed inside a ${(currentResult.settings.errorLimit*100).toFixed(1)}% vertex envelope.`;checkScore.textContent=`${verification.summary.passed}/${verification.checks.length} PASS`;receiptSha.textContent=`RECEIPT ${receiptDigest.slice(0,16)}…`;receiptShort.textContent=`SHA256 ${receiptDigest}`;receiptJson.textContent=JSON.stringify({...currentReceipt,geometry:undefined},null,2);exportButton.disabled=verification.status!=='pass';document.body.dataset.optimizeStatus=verification.status;document.body.dataset.assetId=selected;document.body.dataset.receiptSha256=receiptDigest;
 }catch(error){verdictIcon.textContent='!';verdictTitle.textContent='Optimizer stopped honestly';verdictCopy.textContent=error.message||String(error);receiptJson.textContent=error.stack||String(error);console.error(error);}finally{optimizeButton.disabled=false;}}
function selectAsset(id){selected=id;tabs.forEach(tab=>{const active=tab.dataset.asset===id;tab.classList.toggle('active',active);tab.setAttribute('aria-pressed',String(active));});assetTitle.textContent=assets[id].label;assetCopy.textContent=assets[id].copy;optimize();}
tabs.forEach(tab=>tab.addEventListener('click',()=>selectAsset(tab.dataset.asset)));ratioInput.addEventListener('input',()=>ratioOutput.textContent=`${ratioInput.value}%`);errorInput.addEventListener('input',()=>errorOutput.textContent=`${Number(errorInput.value).toFixed(1)}%`);optimizeButton.addEventListener('click',optimize);exportButton.addEventListener('click',()=>{if(!currentReceipt)return;const url=URL.createObjectURL(new Blob([JSON.stringify(currentReceipt.geometry)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download=`${selected}-${currentReceipt.geometrySha256.slice(0,12)}.axm-mesh.json`;link.click();URL.revokeObjectURL(url);});window.addEventListener('resize',()=>{if(currentResult){drawWireframe(sourceCanvas,currentResult.sourcePrimitives,'#55c9df');drawWireframe(optimizedCanvas,currentResult.optimizedPrimitives,'#59e593');}});optimize();
