#!/usr/bin/env node
'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const contract = JSON.parse(fs.readFileSync(path.join(__dirname, 'module.contract.json'), 'utf8'));
const html = fs.readFileSync(path.join(__dirname, 'index.html'), 'utf8');
const app = fs.readFileSync(path.join(__dirname, 'app.js'), 'utf8');
const server = fs.readFileSync(path.join(__dirname, '..', '..', 'server.js'), 'utf8');
const manifest = JSON.parse(fs.readFileSync(path.join(__dirname, 'manifest.json'), 'utf8'));
const heartbeatCore = fs.readFileSync(path.join(__dirname, '..', '..', 'shared', 'heartbeat', 'axm-platform-heartbeat-core.js'), 'utf8');
assert(contract.boundaries.refuses.includes('promotion-authority'));
assert(contract.boundaries.refuses.includes('real-world-authority'));
assert(html.includes('Unknown signals'));
assert(html.includes('Goal queues'));
assert(html.includes('Dormant lines'));
assert(html.includes('Request archive'));
assert(html.includes('Warmest known sensor'));
assert(html.includes('Battery'));
assert(html.includes('PLATFORM HEARTBEAT'));
assert(html.includes('Next deterministic checks'));
assert(html.includes('findings only'));
assert(html.includes('type="datetime-local"'));
assert(html.includes('Save schedule'));
assert(html.includes('axm-platform-heartbeat-client.js'));
assert(app.includes("!module.activeLease"));
assert(app.includes('module.promotionGate'));
assert(app.includes('PAUSED'));
assert(app.includes('Pulse.deleteGoals'));
assert(app.includes('confirm(question)'));
assert(app.includes('retention.approximateBytes'));
assert(app.includes('Heartbeat.configure'));
assert(app.includes('Heartbeat.manual'));
assert(app.includes('anchorAt'));
assert(app.includes('scheduleMode'));
assert(app.includes('verificationBridge'));
assert(server.includes('BodyPulseService.deleteGoals'));
assert(!server.includes('bodyPulse.deleteGoals'));
assert(server.includes('HeartbeatVerificationBridge.onBeat'));
assert(server.includes('/api/platform-heartbeat'));
assert(heartbeatCore.includes('cadenceMs: 3600000'));
assert(heartbeatCore.includes("scheduleMode: state.config.anchorAt ? 'ANCHORED' : 'INTERVAL_FROM_CHANGE'"));
assert(contract.provides.includes('explicit-local-time-heartbeat-anchor'));
assert(manifest.accepts.includes('axm.platform-heartbeat.beat/v1'));
assert(contract.boundaries.refuses.includes('automatic-publish'));
assert(contract.boundaries.refuses.includes('automatic-merge'));
assert(!/setInterval|setTimeout/.test(app));
console.log('PASS body-pulse dashboard · no private timer · no promotion authority');
