#!/usr/bin/env node
'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const contract = JSON.parse(fs.readFileSync(path.join(__dirname, 'module.contract.json'), 'utf8'));
const html = fs.readFileSync(path.join(__dirname, 'index.html'), 'utf8');
const app = fs.readFileSync(path.join(__dirname, 'app.js'), 'utf8');
const evidenceCss = fs.readFileSync(path.join(__dirname, 'heartbeat-evidence.css'), 'utf8');
const server = fs.readFileSync(path.join(__dirname, '..', '..', 'server.js'), 'utf8');
const manifest = JSON.parse(fs.readFileSync(path.join(__dirname, 'manifest.json'), 'utf8'));
const heartbeatCore = fs.readFileSync(path.join(__dirname, '..', '..', 'shared', 'heartbeat', 'axm-platform-heartbeat-core.js'), 'utf8');
assert(contract.boundaries.refuses.includes('promotion-authority'));
assert.equal(manifest.schema, 'axm.tool-manifest/v1');
assert.equal(manifest.kind, 'product');
assert.equal(manifest.contract, 'module.contract.json');
assert.equal(contract.id, manifest.id);
assert.equal(contract.version, manifest.version);
assert.deepEqual(contract.permissions, manifest.permissions);
assert.deepEqual(contract.lifecycle, { state_owner: 'service', reload: 'resume', disconnect: 'graceful-degrade', cleanup: 'explicit' });
assert(contract.boundaries.refuses.includes('real-world-authority'));
assert(html.includes('Unknown signals'));
assert(html.includes('Goal queues'));
assert(html.includes('Dormant lines'));
assert(html.includes('Request archive'));
assert(html.includes('Warmest known sensor'));
assert(html.includes('Battery'));
assert(html.includes('PLATFORM HEARTBEAT'));
assert(html.includes('Next deterministic checks'));
assert(html.includes('Heartbeat improvement drafts'));
assert(html.includes('What the last heartbeat actually did'));
assert(html.includes('elapsed wall time, not CPU time'));
assert(html.includes('id="heartbeatCpuEvidence"'));
assert(html.includes('Hourly private lesson lane'));
assert(html.includes('OFF BY DEFAULT'));
assert(html.includes('codeDraftRuns'));
assert(html.includes('SEVEN-DAY REVIEW QUEUE'));
assert(html.includes('CODE CLONE · DORMANT · SEVEN-DAY REVIEW QUEUE'));
assert(html.includes('STOPPED'));
assert(html.includes('findings only'));
assert(html.includes('type="datetime-local"'));
assert(html.includes('Save schedule'));
assert(html.includes('axm-platform-heartbeat-client.js'));
assert(app.includes("!module.activeLease"));
assert(app.includes('module.promotionGate'));
assert(app.includes('PAUSED'));
assert(app.includes('Pulse.deleteGoals'));
assert(app.includes('confirm(question)'));
assert(app.includes('retention.approximateBytes'));
assert(app.includes('Heartbeat.configure'));
assert(app.includes('Heartbeat.manual'));
assert(app.includes('anchorAt'));
assert(app.includes('scheduleMode'));
assert(app.includes('verificationBridge'));
assert(app.includes('codeDraftBridge'));
assert(app.includes('mirrorLearningBridge'));
assert(app.includes('verificationEvidence'));
assert(app.includes('draftEvidence'));
assert(app.includes("$('heartbeatCpuEvidence')"));
assert(app.includes('Historical run had no bounded pressure series'));
assert(app.includes('Heartbeat.configureMirrorLearning'));
assert(app.includes("$('codeDraftRuns')"));
assert(app.includes('../workshop-command-center/index.html#codeDraftReviewTitle'));
assert(app.includes('OPEN PLAIN-LANGUAGE REVIEW'));
assert(!app.includes("'/api/reviews/vote'"), 'Heartbeat settings must route technical decisions to the informed review surface');
assert(server.includes('BodyPulseService.deleteGoals'));
assert(!server.includes('bodyPulse.deleteGoals'));
assert(server.includes('HeartbeatVerificationBridge.onBeat'));
assert(server.includes('HeartbeatCodeDraftBridge.onBeat'));
assert(server.includes('HeartbeatMirrorLearningBridge.onBeat'));
assert(server.includes('/api/platform-heartbeat/mirror-learning/config'));
assert(server.includes('HeartbeatOrganOrchestrator.onBeat'));
assert(server.includes('OperationsUtils.atomicJson(HEARTBEAT_CODE_DRAFT_STATE_FILE, state)'));
assert(server.includes('/api/platform-heartbeat'));
assert(heartbeatCore.includes('cadenceMs: 3600000'));
assert(heartbeatCore.includes("scheduleMode: state.config.anchorAt ? 'ANCHORED' : 'INTERVAL_FROM_CHANGE'"));
assert(contract.provides.includes('explicit-local-time-heartbeat-anchor'));
assert(contract.provides.includes('dormant-code-draft-lane'));
assert(contract.provides.includes('one-code-draft-hourly-cap'));
assert(contract.provides.includes('bounded-pressure-sample-evidence'));
assert(contract.provides.includes('plain-language-code-draft-review-handoff'));
assert(!contract.provides.includes('exact-digest-code-draft-vote'));
assert(contract.provides.includes('seven-day-code-draft-review-queue'));
assert(contract.provides.includes('heartbeat-code-draft-run-ledger'));
assert(contract.provides.includes('dormant-hourly-mirror-lesson-lane'));
assert(manifest.accepts.includes('axm.platform-heartbeat.beat/v1'));
assert(contract.boundaries.refuses.includes('automatic-publish'));
assert(contract.boundaries.refuses.includes('automatic-merge'));
assert(contract.boundaries.refuses.includes('workshop-source-edit'));
assert(contract.boundaries.refuses.includes('original-mirror-edit'));
assert(!/setInterval|setTimeout/.test(app));
assert(evidenceCss.includes('.heartbeatEvidenceGrid'));
console.log('PASS body-pulse dashboard · no private timer · no promotion authority');
