// Generated by AXM Machine Geometry Foundry 0.4.0
// Asset: AXM-CRATE-001 AXM Reinforced Modular Crate v0.4.0
// Units: millimetres; source orientation: +Z up, -Y forward.
// Canonical source is recipe.json. This is an editable generated bridge.

// instance: body | base: body | print_group: body
color([0.09412, 0.11373, 0.15294, 1.00000])
translate([0, 0, 350]) rotate([0, 0, 0]) scale([1, 1, 1]) cube([800, 800, 700], center=true);

// instance: bottom_rim | base: bottom_rim | print_group: bottom_rim
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([0, 0, 35]) rotate([0, 0, 0]) scale([1, 1, 1]) cube([860, 860, 70], center=true);

// instance: top_rim | base: top_rim | print_group: top_rim
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([0, 0, 665]) rotate([0, 0, 0]) scale([1, 1, 1]) cube([860, 860, 70], center=true);

// instance: corner_post__g00 | base: corner_post | print_group: corner_post
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([-330, -330, 350]) rotate([0, 0, 0]) scale([1, 1, 1]) cube([75, 75, 720], center=true);

// instance: corner_post__g01 | base: corner_post | print_group: corner_post
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([-330, 330, 350]) rotate([0, 0, 0]) scale([1, 1, 1]) cube([75, 75, 720], center=true);

// instance: corner_post__g02 | base: corner_post | print_group: corner_post
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([330, -330, 350]) rotate([0, 0, 0]) scale([1, 1, 1]) cube([75, 75, 720], center=true);

// instance: corner_post__g03 | base: corner_post | print_group: corner_post
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([330, 330, 350]) rotate([0, 0, 0]) scale([1, 1, 1]) cube([75, 75, 720], center=true);

// instance: front_brace_a | base: front_brace_a | print_group: front_brace_a
color([0.13725, 0.80392, 0.92157, 1.00000])
translate([0, -423, 350]) rotate([0, 46, 0]) scale([1, 1, 1]) cube([70, 45, 790], center=true);

// instance: front_brace_b | base: front_brace_b | print_group: front_brace_b
color([0.13725, 0.80392, 0.92157, 1.00000])
translate([0, -423, 350]) rotate([0, -46, 0]) scale([1, 1, 1]) cube([70, 45, 790], center=true);
