// Generated by AXM Machine Geometry Foundry 0.4.0
// Asset: AXM-MACHINE-TREE-001 AXM Machine-Energy Tree v0.4.0
// Units: millimetres; source orientation: +Z up, -Y forward.
// Canonical source is recipe.json. This is an editable generated bridge.

// instance: root | base: root | print_group: root
color([0.09412, 0.11373, 0.15294, 1.00000])
translate([0, 0, 250]) rotate([0, 0, 0]) scale([1, 1, 1]) cylinder(h=500, r1=600, r2=350, center=true, $fn=16);

// instance: trunk | base: trunk | print_group: trunk
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([0, 0, 1450]) rotate([0, 0, 0]) scale([1, 1, 1]) cylinder(h=2200, r1=360, r2=180, center=true, $fn=16);

// instance: branch__r00 | base: branch | print_group: branch
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([220, 0, 2200]) rotate([0, 62, 0]) scale([1, 1, 1]) hull() { translate([0,0,-445]) sphere(r=105, $fn=32); translate([0,0,445]) sphere(r=105, $fn=32); }

// instance: branch__r01 | base: branch | print_group: branch
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([110, 190.52559, 2200]) rotate([0, 62, 60]) scale([1, 1, 1]) hull() { translate([0,0,-445]) sphere(r=105, $fn=32); translate([0,0,445]) sphere(r=105, $fn=32); }

// instance: branch__r02 | base: branch | print_group: branch
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([-110, 190.52559, 2200]) rotate([0, 62, 120]) scale([1, 1, 1]) hull() { translate([0,0,-445]) sphere(r=105, $fn=32); translate([0,0,445]) sphere(r=105, $fn=32); }

// instance: branch__r03 | base: branch | print_group: branch
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([-220, 2.694223e-14, 2200]) rotate([0, 62, 180]) scale([1, 1, 1]) hull() { translate([0,0,-445]) sphere(r=105, $fn=32); translate([0,0,445]) sphere(r=105, $fn=32); }

// instance: branch__r04 | base: branch | print_group: branch
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([-110, -190.52559, 2200]) rotate([0, 62, 240]) scale([1, 1, 1]) hull() { translate([0,0,-445]) sphere(r=105, $fn=32); translate([0,0,445]) sphere(r=105, $fn=32); }

// instance: branch__r05 | base: branch | print_group: branch
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([110, -190.52559, 2200]) rotate([0, 62, 300]) scale([1, 1, 1]) hull() { translate([0,0,-445]) sphere(r=105, $fn=32); translate([0,0,445]) sphere(r=105, $fn=32); }

// instance: crown__r00 | base: crown | print_group: crown
color([0.28235, 0.63922, 0.43922, 1.00000])
translate([720, 0, 2800]) rotate([0, 0, 0]) scale([1, 1, 1]) scale([520, 400, 430]) sphere(r=1, $fn=36);

// instance: crown__r01 | base: crown | print_group: crown
color([0.28235, 0.63922, 0.43922, 1.00000])
translate([360, 623.53829, 2800]) rotate([0, 0, 0]) scale([1, 1, 1]) scale([520, 400, 430]) sphere(r=1, $fn=36);

// instance: crown__r02 | base: crown | print_group: crown
color([0.28235, 0.63922, 0.43922, 1.00000])
translate([-360, 623.53829, 2800]) rotate([0, 0, 0]) scale([1, 1, 1]) scale([520, 400, 430]) sphere(r=1, $fn=36);

// instance: crown__r03 | base: crown | print_group: crown
color([0.28235, 0.63922, 0.43922, 1.00000])
translate([-720, 8.817457e-14, 2800]) rotate([0, 0, 0]) scale([1, 1, 1]) scale([520, 400, 430]) sphere(r=1, $fn=36);

// instance: crown__r04 | base: crown | print_group: crown
color([0.28235, 0.63922, 0.43922, 1.00000])
translate([-360, -623.53829, 2800]) rotate([0, 0, 0]) scale([1, 1, 1]) scale([520, 400, 430]) sphere(r=1, $fn=36);

// instance: crown__r05 | base: crown | print_group: crown
color([0.28235, 0.63922, 0.43922, 1.00000])
translate([360, -623.53829, 2800]) rotate([0, 0, 0]) scale([1, 1, 1]) scale([520, 400, 430]) sphere(r=1, $fn=36);

// instance: heart | base: heart | print_group: heart
color([0.66275, 0.32157, 1.00000, 0.92157])
translate([0, 0, 2250]) rotate([0, 0, 0]) scale([1, 1, 1]) polyhedron(points=[[250.0, 0.0, 0.0], [155.87245046, 195.45787062, 0.0], [-55.63023349, 243.73197805, 0.0], [-225.24221698, 108.47093478, 0.0], [-225.24221698, -108.47093478, 0.0], [-55.63023349, -243.73197805, 0.0], [155.87245046, -195.45787062, 0.0], [0.0, 0.0, 310.0], [0.0, 0.0, -310.0]], faces=[[7, 0, 1], [8, 1, 0], [7, 1, 2], [8, 2, 1], [7, 2, 3], [8, 3, 2], [7, 3, 4], [8, 4, 3], [7, 4, 5], [8, 5, 4], [7, 5, 6], [8, 6, 5], [7, 6, 0], [8, 0, 6]], convexity=10);
