// Generated by AXM Machine Geometry Foundry 0.4.0
// Asset: AXM-DOORWAY-001 AXM Modular Powered Doorway v0.4.0
// Units: millimetres; source orientation: +Z up, -Y forward.
// Canonical source is recipe.json. This is an editable generated bridge.

// instance: foot__l00 | base: foot | print_group: foot
color([0.09412, 0.11373, 0.15294, 1.00000])
translate([-650, 0, 70]) rotate([0, 0, 0]) scale([1, 1, 1]) cube([480, 850, 140], center=true);

// instance: foot__l01 | base: foot | print_group: foot
color([0.09412, 0.11373, 0.15294, 1.00000])
translate([650, 0, 70]) rotate([0, 0, 0]) scale([1, 1, 1]) cube([480, 850, 140], center=true);

// instance: column__l00 | base: column | print_group: column
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([-650, 0, 1250]) rotate([0, 0, 0]) scale([1, 1, 1]) cube([300, 520, 2300], center=true);

// instance: column__l01 | base: column | print_group: column
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([650, 0, 1250]) rotate([0, 0, 0]) scale([1, 1, 1]) cube([300, 520, 2300], center=true);

// instance: top_beam | base: top_beam | print_group: top_beam
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([0, 0, 2400]) rotate([0, 0, 0]) scale([1, 1, 1]) cube([1600, 520, 330], center=true);

// instance: door | base: door | print_group: door
color([0.09412, 0.11373, 0.15294, 1.00000])
translate([0, 80, 1120]) rotate([0, 0, 0]) scale([1, 1, 1]) cube([950, 180, 2050], center=true);

// instance: energy_strip__l00 | base: energy_strip | print_group: energy_strip
color([0.13725, 0.80392, 0.92157, 1.00000])
translate([-500, -20, 1200]) rotate([0, 0, 0]) scale([1, 1, 1]) cube([65, 200, 1750], center=true);

// instance: energy_strip__l01 | base: energy_strip | print_group: energy_strip
color([0.13725, 0.80392, 0.92157, 1.00000])
translate([500, -20, 1200]) rotate([0, 0, 0]) scale([1, 1, 1]) cube([65, 200, 1750], center=true);

// instance: header_core | base: header_core | print_group: header_core
color([0.66275, 0.32157, 1.00000, 0.92157])
translate([0, -300, 2420]) rotate([90, 0, 0]) scale([1, 1, 1]) polyhedron(points=[[150.0, 0.0, 0.0], [75.0, 129.90381057, 0.0], [-75.0, 129.90381057, 0.0], [-150.0, 0.0, 0.0], [-75.0, -129.90381057, 0.0], [75.0, -129.90381057, 0.0], [0.0, 0.0, 160.0], [0.0, 0.0, -160.0]], faces=[[6, 0, 1], [7, 1, 0], [6, 1, 2], [7, 2, 1], [6, 2, 3], [7, 3, 2], [6, 3, 4], [7, 4, 3], [6, 4, 5], [7, 5, 4], [6, 5, 0], [7, 0, 5]], convexity=10);
