(function(){
  'use strict';
  var C=window.AXMFilmMotionCore,$=function(id){return document.getElementById(id);},STORE='axm.film-motion.project.v1',ENGINE_STORE='axm.film-motion.shared.v1',PUBLISH='axm.publish-library.ledger.v1',project=null,engineEnvelope=null,mode='edit',selectedClip=null,selectedScene=null,selectedLayer=null,sessionUrls={},playing=null,cameraStream=null,toastTimer=null;
  function esc(v){return String(v==null?'':v).replace(/[&<>'"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c];});}
  function clean(v,n){return String(v==null?'':v).trim().slice(0,n||4000);}
  function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');$('statusText').textContent=msg;clearTimeout(toastTimer);toastTimer=setTimeout(function(){$('toast').classList.remove('show');},2200);if(window.AXMHub)AXMHub.log(msg);}
  function syncEngines(label){if(!window.AXMEngines)return;try{
    if(!engineEnvelope||!AXMEngines.Project.validate(engineEnvelope).ok)engineEnvelope=AXMEngines.Project.create({id:project.id,kind:'film-motion',name:project.name,documentSchema:C.FORMAT,data:project,actor:{id:'film-motion-studio',kind:'service'}});else engineEnvelope=AXMEngines.Project.update(engineEnvelope,project,{id:'film-motion-studio',kind:'service'},label||'autosave');if(label)engineEnvelope=AXMEngines.Project.checkpoint(engineEnvelope,label,{id:'film-motion-studio',kind:'service'}).project;
    var timeline=AXMEngines.Timeline.create({unit:'frames',rate:project.fps,duration:project.durationFrames}),trackMap={};project.tracks.forEach(function(t){var r=AXMEngines.Timeline.addTrack(timeline,{id:t.id,name:t.name,kind:t.kind});timeline=r.timeline;trackMap[t.id]=r.track.id;});project.clips.forEach(function(c){timeline=AXMEngines.Timeline.addClip(timeline,{id:c.id,trackId:trackMap[c.trackId],name:c.name,start:c.startFrame,duration:c.durationFrames,sourceId:c.assetId,data:{inFrame:c.inFrame,speed:c.speed}}).timeline;});
    var scene=AXMEngines.Scene.create(2),s=project.scenes[0];if(s)s.layers.forEach(function(l){scene=AXMEngines.Scene.add(scene,{id:l.id,type:l.kind,name:l.name,x:l.x,y:l.y,rotation:l.rotation,scaleX:l.scale,scaleY:l.scale,props:{text:l.text,color:l.color,opacity:l.opacity}}).graph;});
    var assets=AXMEngines.Asset.createLibrary(project.name+' media');project.assets.forEach(function(a){assets=AXMEngines.Asset.record(assets,{id:a.id,name:a.name,kind:a.kind,mime:a.mime,bytes:a.bytes,source:a.source,licenseStatus:a.rights},{id:'film-motion-studio',kind:'service'}).library;});
    var room=AXMEngines.Collaboration.create(project.name+' dailies');project.reviews.forEach(function(r){var kind=r.kind==='daily'?'comment':r.kind;room=AXMEngines.Collaboration.post(room,kind,{title:r.title,body:r.body,target:r.targetId},{id:r.reviewer,kind:'human'}).room;});
    var evidence=AXMEngines.Evidence.create(project.name+' delivery');project.reviews.filter(function(r){return r.kind==='daily';}).forEach(function(r){evidence=AXMEngines.Evidence.add(evidence,{kind:'observation',statement:r.title+': '+r.body,evidence:[r.body],confidence:'medium'},{id:r.reviewer,kind:'human'}).ledger;});
    var motionGraph=AXMEngines.NodeGraph.create('film-motion');if(s)s.layers.forEach(function(l){motionGraph=AXMEngines.NodeGraph.addNode(motionGraph,{id:l.id,type:'layer',name:l.name,data:{kind:l.kind}}).graph;});
    localStorage.setItem(ENGINE_STORE,JSON.stringify({schema:'axm.film-motion.shared-snapshot/v1',project:engineEnvelope,timeline:timeline,scene:scene,assets:assets,collaboration:room,evidence:evidence,motionGraph:motionGraph,updatedAt:C.now()}));
  }catch(e){toast('Shared engine checkpoint unavailable: '+e.message);}}
  function save(msg){project.updatedAt=C.now();try{localStorage.setItem(STORE,JSON.stringify(project));syncEngines(msg);$('saveState').textContent='Saved '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});}catch(e){return toast('Save failed: '+e.message);}if(window.AXMWorkshopContinuity)AXMWorkshopContinuity.announce({workspaceId:'film-motion-studio',workspaceName:'Film & Motion Studio',projectId:project.id,projectName:project.name,documentSchema:C.FORMAT,updatedAt:project.updatedAt,resumeHint:'Continue editing the timeline, motion and review.'});if(msg)toast(msg);}
  function load(){try{var raw=JSON.parse(localStorage.getItem(STORE)||'null');project=raw?C.normalizeProject(raw):C.emptyProject();project.assets.forEach(function(a){a.sessionAvailable=false;});try{var shared=JSON.parse(localStorage.getItem(ENGINE_STORE)||'null');engineEnvelope=shared&&shared.project;}catch(ignore){}syncEngines();}catch(e){project=C.emptyProject();toast('Unreadable project replaced with an empty Film & Motion project');}selectedScene=project.scenes[0]&&project.scenes[0].id;selectedLayer=project.scenes[0]&&project.scenes[0].layers[0]&&project.scenes[0].layers[0].id;}
  function download(name,data,type){var blob=data instanceof Blob?data:new Blob([data],{type:type||'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(function(){URL.revokeObjectURL(url);},1500);}
  function jsonDownload(name,data){download(name,JSON.stringify(data,null,2),'application/json');}
  function buildNav(){C.groups().forEach(function(g){var cap=document.createElement('div');cap.className='nav-group';cap.textContent=g.name;$('modeNav').appendChild(cap);g.modes.forEach(function(m){var b=document.createElement('button');b.className='nav-button';b.dataset.mode=m.id;b.textContent=m.short;b.onclick=function(){selectMode(m.id);};$('modeNav').appendChild(b);});});}
  function selectMode(id){var m=C.byId(id);mode=m.id;C.MODES.forEach(function(x){$(x.id+'View').hidden=x.id!==mode;});document.querySelectorAll('.nav-button').forEach(function(b){b.classList.toggle('active',b.dataset.mode===mode);});$('viewGroup').textContent=m.group;$('viewTitle').textContent=m.title;$('viewDescription').textContent=m.description;$('previewWrap').hidden=['storyboard','review','tracking','virtual','deliver'].indexOf(mode)>=0;renderAll();toast('Opened '+m.title);}
  function options(id,items,empty,label){var el=$(id),old=el.value;el.innerHTML=empty?'<option value="">'+esc(empty)+'</option>':'';(items||[]).forEach(function(x){var o=document.createElement('option');o.value=x.id;o.textContent=label?label(x):x.name;el.appendChild(o);});if(Array.from(el.options).some(function(o){return o.value===old;}))el.value=old;}
  function frame(){return Number($('playhead').value)||0;}
  function renderHeader(){var s=C.summary(project);$('projectName').textContent=project.name;$('projectStats').textContent=s.assets+' media · '+s.clips+' clips · '+s.shots+' shots';$('playhead').max=project.durationFrames;$('timecode').textContent=C.frameTimecode(frame(),project.fps);}
  function renderSelectors(){
    options('clipAsset',project.assets,'Import media first');options('clipTrack',project.tracks,'Add a track first',function(t){return t.name+' · '+t.kind;});options('sceneSelect',project.scenes);options('motionScene',project.scenes);var scene=project.scenes.find(function(s){return s.id===selectedScene;})||project.scenes[0],layers=scene?scene.layers:[];options('layerSelect',layers,'Add a layer first');options('motionLayer',layers,'Add a layer first');if(selectedScene){$('sceneSelect').value=selectedScene;$('motionScene').value=selectedScene;}if(selectedLayer){$('layerSelect').value=selectedLayer;$('motionLayer').value=selectedLayer;}
    options('effectClip',project.clips,'Add a clip first');options('trackingClip',project.clips,'Add a clip first');var targets=project.storyboards.concat(project.clips);options('reviewTarget',targets,'Whole project',function(x){return x.title||x.name||x.id;});
  }
  function renderAssets(){var box=$('assetList');box.innerHTML=project.assets.length?'':'<div class="notice">No session media yet.</div>';project.assets.forEach(function(a){var el=document.createElement('div');el.className='asset-item';el.innerHTML='<b>'+esc(a.name)+'</b><span>'+esc(a.kind)+' · '+esc(a.rights)+' · '+(sessionUrls[a.id]?'session ready':'source unavailable this session')+'</span>';if(!sessionUrls[a.id]){var button=document.createElement('button');button.type='button';button.textContent='Reconnect source';button.onclick=function(){$('reconnectFile').dataset.assetId=a.id;$('reconnectFile').click();};el.appendChild(button);}box.appendChild(el);});}
  function renderTimeline(){var box=$('timeline'),duration=Math.max(1,project.durationFrames);box.innerHTML='<div class="timeline-ruler"></div>';project.tracks.slice().sort(function(a,b){return a.order-b.order;}).forEach(function(t){var row=document.createElement('div');row.className='timeline-row';row.innerHTML='<div class="track-head"><b>'+esc(t.name)+'</b><small>'+esc(t.kind)+'</small></div><div class="clip-lane"></div>';var lane=row.querySelector('.clip-lane');project.clips.filter(function(c){return c.trackId===t.id;}).forEach(function(c){var b=document.createElement('button');b.className='clip'+(selectedClip===c.id?' selected':'');b.style.left=(c.startFrame/duration*100)+'%';b.style.width=Math.max(1.5,c.durationFrames/duration*100)+'%';b.textContent=c.name;b.title=C.frameTimecode(c.startFrame,project.fps)+' · '+c.durationFrames+' frames';b.onclick=function(){selectedClip=c.id;renderAll();};lane.appendChild(b);});box.appendChild(row);});var c=project.clips.find(function(x){return x.id===selectedClip;});$('selectedClipName').textContent=c?c.name:'No clip selected';}
  function sceneAt(){return project.scenes.find(function(s){return s.id===selectedScene;})||project.scenes[0];}
  function renderScenePreview(){var box=$('scenePreview'),s=sceneAt(),f=frame();box.innerHTML='';if(!s)return;box.style.background=s.background;s.layers.filter(function(l){return l.visible;}).forEach(function(l){var el=document.createElement('div'),x=C.valueAt(project,s.id,l.id,'x',f,l.x),y=C.valueAt(project,s.id,l.id,'y',f,l.y),scale=C.valueAt(project,s.id,l.id,'scale',f,l.scale),rotation=C.valueAt(project,s.id,l.id,'rotation',f,l.rotation),opacity=C.valueAt(project,s.id,l.id,'opacity',f,l.opacity);el.className='scene-object';el.style.left=x+'%';el.style.top=y+'%';el.style.opacity=opacity;el.style.color=l.color;el.style.transform='translate(-50%,-50%) scale('+scale+') rotate('+rotation+'deg)';el.textContent=l.kind==='text'?(l.text||l.name):l.kind==='shape'?'◆':l.name;box.appendChild(el);});}
  function activeClipAt(){var f=frame(),tracks=project.tracks.slice().sort(function(a,b){return b.order-a.order;}),order={};tracks.forEach(function(t,i){order[t.id]=i;});return project.clips.filter(function(c){return f>=c.startFrame&&f<c.startFrame+c.durationFrames;}).sort(function(a,b){return(order[a.trackId]||0)-(order[b.trackId]||0);})[0]||null;}
  function clipFilter(clipId){var effects=project.effects.filter(function(e){return e.clipId===clipId&&e.enabled;}),p={brightness:1,contrast:1,saturation:1,hue:0,blur:0};effects.forEach(function(e){Object.assign(p,e.params||{});});return'brightness('+p.brightness+') contrast('+p.contrast+') saturate('+p.saturation+') hue-rotate('+p.hue+'deg) blur('+p.blur+'px)';}
  function renderPreview(){renderScenePreview();var clip=activeClipAt(),video=$('previewVideo'),image=$('previewImage'),empty=$('previewEmpty'),scene=sceneAt();video.hidden=true;image.hidden=true;video.style.filter='none';image.style.filter='none';empty.hidden=!!(scene&&scene.layers.length);$('previewLabel').textContent='Scene preview · '+C.frameTimecode(frame(),project.fps);if(!clip)return;$('scenePreview').style.background='transparent';var asset=project.assets.find(function(a){return a.id===clip.assetId;}),url=asset&&sessionUrls[asset.id],filter=clipFilter(clip.id);video.style.filter=filter;image.style.filter=filter;if(!asset||!url){$('previewLabel').textContent=clip.name+' · media must be reconnected this session';return;}empty.hidden=true;$('previewLabel').textContent=clip.name+' · '+C.frameTimecode(frame(),project.fps);if(asset.kind==='image'){image.hidden=false;if(image.src!==url)image.src=url;}else if(asset.kind==='video'){video.hidden=false;if(video.src!==url)video.src=url;var seconds=(clip.inFrame+(frame()-clip.startFrame)*clip.speed)/project.fps;if(video.readyState>=1&&Math.abs(video.currentTime-seconds)>.08)try{video.currentTime=Math.max(0,seconds);}catch(e){}}}
  function renderScenes(){var box=$('sceneList');box.innerHTML='';project.scenes.forEach(function(s){var el=document.createElement('button');el.textContent=s.name+' · '+s.layers.length+' layers';el.onclick=function(){selectedScene=s.id;selectedLayer=s.layers[0]&&s.layers[0].id;renderAll();};box.appendChild(el);});var s=sceneAt(),layers=s?s.layers:[];$('keyList').innerHTML='';project.keyframes.filter(function(k){return s&&k.sceneId===s.id;}).sort(function(a,b){return a.frame-b.frame;}).slice(-18).forEach(function(k){var l=layers.find(function(x){return x.id===k.layerId;}),el=document.createElement('div');el.className='list-item';el.innerHTML='<b>'+esc(l?l.name:'Layer')+' · '+esc(k.property)+'</b><span>frame '+k.frame+' → '+k.value+' · '+esc(k.easing)+'</span>';$('keyList').appendChild(el);});}
  function renderMotion(){var box=$('motionList'),s=sceneAt();box.innerHTML='';project.keyframes.filter(function(k){return s&&k.sceneId===s.id;}).slice().sort(function(a,b){return a.frame-b.frame;}).forEach(function(k){var el=document.createElement('div');el.className='list-item';el.innerHTML='<b>'+esc(k.property)+' · frame '+k.frame+'</b><span>'+k.value+' · '+esc(k.easing)+'</span>';box.appendChild(el);});if(!box.children.length)box.innerHTML='<div class="notice">No motion keyframes yet.</div>';}
  function renderEffects(){var box=$('effectList');box.innerHTML='';project.effects.forEach(function(e){var c=project.clips.find(function(x){return x.id===e.clipId;}),el=document.createElement('div');el.className='list-item';el.innerHTML='<b>'+esc(c?c.name:'Clip')+' · '+esc(e.type)+'</b><span>'+Object.keys(e.params).map(function(k){return k+' '+e.params[k];}).join(' · ')+'</span>';box.appendChild(el);});if(!box.children.length)box.innerHTML='<div class="notice">No effects saved.</div>';}
  function renderBoards(){var box=$('boardList');box.innerHTML='';project.storyboards.slice().sort(function(a,b){return a.order-b.order;}).forEach(function(b){var el=document.createElement('article');el.className='board';el.innerHTML='<div class="board-visual" style="background:'+b.color+'"><b>SHOT '+esc(b.shot)+'</b><span>'+esc(b.framing)+'</span></div><div class="board-copy"><b>'+esc(b.title)+'</b><span>'+b.durationFrames+' frames · '+esc(b.description)+'</span></div>';box.appendChild(el);});if(!box.children.length)box.innerHTML='<div class="notice">No storyboard cards yet.</div>';}
  function renderReviews(){var box=$('reviewList');box.innerHTML='';project.reviews.slice().reverse().forEach(function(r){var el=document.createElement('div');el.className='list-item';el.innerHTML='<b>'+esc(r.title)+' · '+esc(r.verdict).toUpperCase()+'</b><span>'+esc(r.kind)+' · '+esc(r.reviewer)+' · '+esc(r.body)+'</span>';box.appendChild(el);});if(!box.children.length)box.innerHTML='<div class="notice">No dailies or review records yet.</div>';}
  function renderTracking(){var map=$('trackingList');map.innerHTML='';project.tracking.forEach(function(t){var dot=document.createElement('span');dot.className='track-point';dot.style.left=t.x+'%';dot.style.top=t.y+'%';dot.title='frame '+t.frame+' · '+t.method+' · '+Math.round(t.confidence*100)+'%';map.appendChild(dot);});if(!project.tracking.length)map.innerHTML='<div class="preview-empty"><b>NO TRACK</b><span>Record manual points or import a verified packet.</span></div>';}
  function renderTakes(){var box=$('takeList');box.innerHTML='';project.captureTakes.slice().reverse().forEach(function(t){var el=document.createElement('div');el.className='list-item';el.innerHTML='<b>'+esc(t.name)+'</b><span>'+t.lens+'mm · '+t.fps+' fps · focus '+t.focus+'m · metadata only</span>';box.appendChild(el);});}
  function renderExports(){var box=$('exportList');box.innerHTML='';project.exports.slice().reverse().forEach(function(e){var el=document.createElement('div');el.className='list-item';el.innerHTML='<b>'+esc(e.name)+'</b><span>'+esc(e.format)+' · '+esc(e.status)+' · '+new Date(e.createdAt).toLocaleString()+'</span>';box.appendChild(el);});var s=C.summary(project),unready=project.assets.filter(function(a){return !sessionUrls[a.id];}).length;$('deliveryTruth').textContent=s.assets+' assets · '+unready+' need session reconnect · '+s.reviews+' review records · project/EDL/frame proof supported · final video encoder unavailable.';}
  function renderAll(){renderHeader();renderSelectors();renderAssets();renderTimeline();renderScenes();renderMotion();renderEffects();renderBoards();renderReviews();renderTracking();renderTakes();renderExports();renderPreview();}
  function play(){if(playing)return;renderPreview();var v=$('previewVideo');if(!v.hidden){v.muted=false;v.play().catch(function(){});}playing=setInterval(function(){var n=frame()+1;if(n>project.durationFrames)n=0;$('playhead').value=n;renderHeader();renderPreview();},Math.max(16,1000/project.fps));$('play').disabled=true;toast('Playing project preview');}
  function stop(){clearInterval(playing);playing=null;$('play').disabled=false;try{$('previewVideo').pause();}catch(e){}toast('Preview stopped');}
  function mediaKind(file){return/^video\//.test(file.type)?'video':/^audio\//.test(file.type)?'audio':'image';}
  function importMedia(files){Array.from(files||[]).forEach(function(file){var kind=mediaKind(file),a=C.addAsset(project,{name:file.name,kind:kind,mime:file.type,bytes:file.size,durationFrames:Number($('mediaDuration').value)||120,source:'local session file',rights:$('mediaRights').value,sessionAvailable:true});sessionUrls[a.id]=URL.createObjectURL(file);});save('Imported '+files.length+' session media file'+(files.length===1?'':'s'));renderAll();}
  function reconnectMedia(assetId,file){var asset=project.assets.find(function(a){return a.id===assetId;});if(!asset||!file)throw Error('Choose the source for an existing media record');var kind=mediaKind(file);if(kind!==asset.kind)throw Error('Expected '+asset.kind+' media, received '+kind);if(sessionUrls[asset.id]&&/^blob:/.test(sessionUrls[asset.id]))URL.revokeObjectURL(sessionUrls[asset.id]);sessionUrls[asset.id]=URL.createObjectURL(file);asset.sessionAvailable=true;asset.mime=file.type||asset.mime;asset.bytes=file.size;save('Reconnected '+asset.name+' for this session');renderAll();}
  function renderFrameProof(){var canvas=$('frameCanvas'),w=Math.min(project.width,1280),h=Math.round(w*project.height/project.width),ctx=canvas.getContext('2d'),clip=activeClipAt(),asset=clip&&project.assets.find(function(a){return a.id===clip.assetId;});canvas.width=w;canvas.height=h;ctx.fillStyle=sceneAt()?sceneAt().background:'#07101b';ctx.fillRect(0,0,w,h);if(clip)ctx.filter=clipFilter(clip.id);try{if(asset&&asset.kind==='video'&&!$('previewVideo').hidden&&$('previewVideo').readyState>=2)ctx.drawImage($('previewVideo'),0,0,w,h);else if(asset&&asset.kind==='image'&&!$('previewImage').hidden)ctx.drawImage($('previewImage'),0,0,w,h);}catch(e){}ctx.filter='none';var s=sceneAt();if(s)s.layers.filter(function(l){return l.visible;}).forEach(function(l){var x=C.valueAt(project,s.id,l.id,'x',frame(),l.x)/100*w,y=C.valueAt(project,s.id,l.id,'y',frame(),l.y)/100*h,scale=C.valueAt(project,s.id,l.id,'scale',frame(),l.scale),opacity=C.valueAt(project,s.id,l.id,'opacity',frame(),l.opacity);ctx.save();ctx.translate(x,y);ctx.rotate(C.valueAt(project,s.id,l.id,'rotation',frame(),l.rotation)*Math.PI/180);ctx.scale(scale,scale);ctx.globalAlpha=opacity;ctx.fillStyle=l.color;ctx.font='bold '+Math.max(18,Math.round(h*.055))+'px system-ui';if(l.kind==='shape'){ctx.beginPath();ctx.arc(0,0,30,0,Math.PI*2);ctx.fill();}else ctx.fillText(l.text||l.name,-ctx.measureText(l.text||l.name).width/2,0);ctx.restore();});return new Promise(function(resolve){canvas.toBlob(function(blob){if(!blob)return resolve(false);var name=(project.name.replace(/[^a-z0-9]+/gi,'-')||'film')+'-frame-'+frame()+'.png';download(name,blob,'image/png');project.exports.push({id:C.id('export'),name:name,format:'PNG frame proof',status:'EXPORTED',frame:frame(),evidence:['browser canvas produced '+blob.size+' bytes','frame '+frame()+' at '+C.frameTimecode(frame(),project.fps)],createdAt:C.now()});save('Current-frame PNG proof rendered');$('frameStatus').textContent='Rendered '+name+' · '+blob.size+' bytes';renderExports();resolve(true);},'image/png');});}
  function sendPublish(){var packet=C.publishPacket(project,{name:$('publishName').value,format:$('publishFormat').value,version:$('publishVersion').value,license:$('publishLicense').value,provenance:$('publishProvenance').value}),state;try{state=JSON.parse(localStorage.getItem(PUBLISH)||'null');}catch(e){}if(!state||state.schema!=='axm.publish-library.ledger/v1')state={schema:'axm.publish-library.ledger/v1',artifacts:[],releases:[],updatedAt:null};state.artifacts=Array.isArray(state.artifacts)?state.artifacts:[];var a=packet.artifact;state.artifacts.push({id:C.id('artifact'),name:a.name,source:a.source,format:a.format,version:a.version,license:a.license,provenance:a.provenance,state:'INBOX',createdAt:C.now()});state.updatedAt=C.now();localStorage.setItem(PUBLISH,JSON.stringify(state));toast('Sent to Publish & Library as unreviewed');}
  function openHands(){var drawer=$('handsDrawer');drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');if(!$('handsFrame').dataset.loaded){$('handsFrame').dataset.loaded='1';$('handsFrame').src='/shared/asset-hands/index.html?host=film-motion&kind=illustration&target='+encodeURIComponent(project.name||'Film project');}}
  function closeHands(){var drawer=$('handsDrawer');drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true');}
  function importHandResult(result){var hand=C.assetFromHandResult(result),asset=C.addAsset(project,hand.asset);sessionUrls[asset.id]=hand.dataUrl;save('Imported technically-passed Creation Hand candidate');renderAll();selectMode('edit');$('clipAsset').value=asset.id;closeHands();$('statusText').textContent=asset.name+' ready as session media · timeline placement still required';toast('Added '+asset.name+' from '+result.hand.title+' as an unplaced candidate');}
  function bind(){
    $('play').onclick=play;$('stop').onclick=stop;$('playhead').oninput=function(){renderHeader();renderPreview();};$('mediaFiles').onchange=function(){importMedia(this.files);this.value='';};$('reconnectFile').onchange=function(){var file=this.files&&this.files[0],assetId=this.dataset.assetId;try{reconnectMedia(assetId,file);}catch(error){toast('Reconnect refused · '+error.message);}this.value='';delete this.dataset.assetId;};$('trackKind').innerHTML=C.TRACK_KINDS.map(function(k){return'<option>'+k+'</option>';}).join('');
    $('trackForm').onsubmit=function(e){e.preventDefault();C.addTrack(project,{name:$('trackName').value,kind:$('trackKind').value});e.target.reset();save('Track added');renderAll();};$('clipForm').onsubmit=function(e){e.preventDefault();try{var a=project.assets.find(function(x){return x.id===$('clipAsset').value;}),c=C.addClip(project,{trackId:$('clipTrack').value,assetId:a&&a.id,name:$('clipName').value||a.name,startFrame:$('clipStart').value,durationFrames:$('clipDuration').value,inFrame:$('clipIn').value,speed:$('clipSpeed').value});selectedClip=c.id;save('Clip added to sequence');renderAll();}catch(err){toast(err.message);}};
    $('splitClip').onclick=function(){try{C.splitClip(project,selectedClip,frame());save('Clip split at '+C.frameTimecode(frame(),project.fps));renderAll();}catch(e){toast(e.message);}};$('deleteClip').onclick=function(){if(!selectedClip)return toast('Select a clip first');if(!confirm('Remove this clip from the project? Source media will remain untouched.'))return;project.clips=project.clips.filter(function(c){return c.id!==selectedClip;});project.effects=project.effects.filter(function(e){return e.clipId!==selectedClip;});selectedClip=null;save('Clip reference removed');renderAll();};
    $('sceneSelect').onchange=function(){selectedScene=this.value;var s=sceneAt();selectedLayer=s&&s.layers[0]&&s.layers[0].id;renderAll();};$('motionScene').onchange=function(){selectedScene=this.value;var s=sceneAt();selectedLayer=s&&s.layers[0]&&s.layers[0].id;renderAll();};$('layerSelect').onchange=$('motionLayer').onchange=function(){selectedLayer=this.value;renderPreview();};
    $('sceneForm').onsubmit=function(e){e.preventDefault();var s=C.normalizeScene({name:$('sceneName').value,durationFrames:$('sceneDuration').value});project.scenes.push(s);selectedScene=s.id;selectedLayer=null;save('Scene added');e.target.reset();renderAll();};$('layerForm').onsubmit=function(e){e.preventDefault();try{var l=C.addLayer(project,selectedScene,{name:$('layerName').value,kind:$('layerKind').value,text:$('layerText').value,x:$('layerX').value,y:$('layerY').value,color:$('layerColor').value});selectedLayer=l.id;save('Animation layer added');e.target.reset();renderAll();}catch(err){toast(err.message);}};$('keyForm').onsubmit=function(e){e.preventDefault();try{C.addKeyframe(project,{sceneId:selectedScene,layerId:$('layerSelect').value,property:$('keyProperty').value,frame:$('keyFrame').value,value:$('keyValue').value,easing:$('keyEasing').value});save('Keyframe set');renderAll();}catch(err){toast(err.message);}};
    $('motionForm').onsubmit=function(e){e.preventDefault();try{selectedScene=$('motionScene').value;selectedLayer=$('motionLayer').value;var made=C.procedural(project,{sceneId:selectedScene,layerId:selectedLayer,preset:$('motionPreset').value,startFrame:$('motionStart').value,endFrame:$('motionEnd').value,amount:$('motionAmount').value});save('Generated '+made.length+' editable keyframes');renderAll();}catch(err){toast(err.message);}};
    $('gradeForm').onsubmit=function(e){e.preventDefault();try{C.addEffect(project,{clipId:$('effectClip').value,type:'grade',params:{brightness:$('gradeBrightness').value,contrast:$('gradeContrast').value,saturation:$('gradeSaturation').value,hue:$('gradeHue').value,blur:$('gradeBlur').value}});selectedClip=$('effectClip').value;save('Grade effect saved');renderAll();}catch(err){toast(err.message);}};$('renderFrame').onclick=renderFrameProof;
    $('boardForm').onsubmit=function(e){e.preventDefault();project.storyboards.push(C.normalizeStoryboard({shot:$('boardShot').value,title:$('boardTitle').value,durationFrames:$('boardDuration').value,framing:$('boardFraming').value,description:$('boardDescription').value,dialogue:$('boardDialogue').value,notes:$('boardNotes').value,order:project.storyboards.length,color:['#193a51','#39275d','#214c42','#55352e'][project.storyboards.length%4]}));save('Storyboard shot added');e.target.reset();renderAll();};
    $('reviewForm').onsubmit=function(e){e.preventDefault();project.reviews.push(C.normalizeReview({targetId:$('reviewTarget').value,kind:$('reviewKind').value,verdict:$('reviewVerdict').value,title:$('reviewTitle').value,body:$('reviewBody').value,reviewer:$('reviewer').value}));save('Review record saved');$('reviewTitle').value='';$('reviewBody').value='';renderAll();};
    $('trackingForm').onsubmit=function(e){e.preventDefault();try{C.addTracking(project,{clipId:$('trackingClip').value,frame:$('trackingFrame').value,x:$('trackingX').value,y:$('trackingY').value,confidence:$('trackingConfidence').value,method:'manual',evidence:'manually recorded in Film & Motion Studio'});save('Manual tracking point recorded');renderAll();}catch(err){toast(err.message);}};$('trackingImport').onchange=async function(){var file=this.files&&this.files[0];if(!file)return;try{var p=JSON.parse(await file.text());if(p.schema!=='axm.motion-capture.points/v1'||!Array.isArray(p.points))throw Error('Unsupported motion-capture packet');var clipId=p.clipId||$('trackingClip').value,count=0;p.points.slice(0,50000).forEach(function(t){C.addTracking(project,{clipId:clipId,frame:t.frame,x:t.x,y:t.y,confidence:t.confidence,method:'imported',evidence:p.source||file.name});count++;});save('Imported '+count+' verified tracking points');$('trackingImportStatus').textContent='Imported '+count+' points from '+file.name;renderAll();}catch(e){$('trackingImportStatus').textContent='Import refused: '+e.message;}this.value='';};
    $('startCamera').onclick=async function(){try{cameraStream=await navigator.mediaDevices.getUserMedia({video:true,audio:false});$('cameraVideo').srcObject=cameraStream;await $('cameraVideo').play();$('startCamera').disabled=true;$('stopCamera').disabled=false;$('cameraStatus').textContent='Camera preview active · stream is not recorded or persisted';}catch(e){$('cameraStatus').textContent='Camera unavailable: '+e.message;}};$('stopCamera').onclick=function(){if(cameraStream)cameraStream.getTracks().forEach(function(t){t.stop();});cameraStream=null;$('cameraVideo').srcObject=null;$('startCamera').disabled=false;$('stopCamera').disabled=true;$('cameraStatus').textContent='Camera is off.';};$('takeForm').onsubmit=function(e){e.preventDefault();project.captureTakes.push({id:C.id('take'),name:clean($('takeName').value,120),lens:Number($('takeLens').value),fps:Number($('takeFps').value),focus:Number($('takeFocus').value),exposure:clean($('takeExposure').value,120),notes:clean($('takeNotes').value,2000),previewOnly:true,createdAt:C.now()});save('Take metadata saved · no recording claimed');e.target.reset();renderAll();};
    function exportProject(){jsonDownload('AXM_FILM_'+(project.name.replace(/[^a-z0-9]+/gi,'-')||'project')+'.json',project);project.exports.push({id:C.id('export'),name:project.name+' project',format:'JSON project',status:'EXPORTED',createdAt:C.now()});save('Film project exported');renderExports();}$('exportProject').onclick=exportProject;$('deliverProject').onclick=exportProject;$('exportEdl').onclick=function(){var e=C.edl(project);jsonDownload((project.name.replace(/[^a-z0-9]+/gi,'-')||'film')+'.edl.json',e);project.exports.push({id:C.id('export'),name:project.name+' EDL',format:'Frame EDL JSON',status:'EXPORTED',createdAt:C.now()});save('Frame EDL exported');renderExports();};$('deliverFrame').onclick=renderFrameProof;$('publishForm').onsubmit=function(e){e.preventDefault();sendPublish();};
    $('openHands').onclick=openHands;document.querySelectorAll('[data-close-hands]').forEach(function(button){button.onclick=closeHands;});window.addEventListener('keydown',function(e){if(e.key==='Escape')closeHands();});window.addEventListener('message',function(ev){var msg=ev.data;if(!msg||msg.type!=='axm-asset-hand-result'||msg.schema!=='axm.asset-hand-result/v1'||ev.source!==$('handsFrame').contentWindow)return;try{importHandResult(msg.result||{});}catch(error){toast('Creation Hand result refused · '+error.message);}});
    $('importProject').onclick=function(){$('projectFile').click();};$('projectFile').onchange=async function(){var file=this.files&&this.files[0];if(!file)return;try{var imported=C.normalizeProject(JSON.parse(await file.text()));if(!confirm('Replace the current project with "'+imported.name+'"? Session media must be reconnected.'))return;imported.assets.forEach(function(a){a.sessionAvailable=false;});project=imported;sessionUrls={};selectedClip=null;selectedScene=project.scenes[0]&&project.scenes[0].id;selectedLayer=project.scenes[0]&&project.scenes[0].layers[0]&&project.scenes[0].layers[0].id;save('Imported portable Film & Motion project');renderAll();}catch(e){toast('Import refused: '+e.message);}this.value='';};
  }
  async function init(){buildNav();load();bind();renderAll();selectMode('edit');if(window.AXM&&AXM.init)await AXM.init({id:'film-motion-studio',name:'AXM Film & Motion Studio',version:'v1.1'});if(window.AXMHub){AXMHub.ready({version:'v1.1',capabilities:['edit','animation','motion-graphics','composite','storyboard','dailies','tracking','camera-preview','project-export','edl-export','frame-proof','publish-handoff','asset-hands']});AXMHub.verifyPass();}toast('Film & Motion Studio ready · session media stays session-only');}
  init().catch(function(e){toast('Film & Motion Studio failed: '+e.message);});
})();
