// Generated by AXM Machine Geometry Foundry 0.4.0
// Asset: AXM-TERRAIN-TILE-001 AXM Modular Terrain Platform v0.4.0
// Units: millimetres; source orientation: +Z up, -Y forward.
// Canonical source is recipe.json. This is an editable generated bridge.

// instance: platform | base: platform | print_group: platform
color([0.09412, 0.11373, 0.15294, 1.00000])
translate([0, 0, 110]) rotate([0, 0, 0]) scale([1, 1, 1]) cube([4000, 4000, 220], center=true);

// instance: edge_x__l00 | base: edge_x | print_group: edge_x
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([0, -1910, 250]) rotate([0, 0, 0]) scale([1, 1, 1]) cube([4000, 180, 280], center=true);

// instance: edge_x__l01 | base: edge_x | print_group: edge_x
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([0, 1910, 250]) rotate([0, 0, 0]) scale([1, 1, 1]) cube([4000, 180, 280], center=true);

// instance: edge_y__l00 | base: edge_y | print_group: edge_y
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([-1910, 0, 250]) rotate([0, 0, 0]) scale([1, 1, 1]) cube([180, 3640, 280], center=true);

// instance: edge_y__l01 | base: edge_y | print_group: edge_y
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([1910, 0, 250]) rotate([0, 0, 0]) scale([1, 1, 1]) cube([180, 3640, 280], center=true);

// instance: corner_node__g00 | base: corner_node | print_group: corner_node
color([0.13725, 0.80392, 0.92157, 1.00000])
translate([-1800, -1800, 300]) rotate([0, 0, 0]) scale([1, 1, 1]) cylinder(h=360, r=180, center=true, $fn=20);

// instance: corner_node__g01 | base: corner_node | print_group: corner_node
color([0.13725, 0.80392, 0.92157, 1.00000])
translate([-1800, 1800, 300]) rotate([0, 0, 0]) scale([1, 1, 1]) cylinder(h=360, r=180, center=true, $fn=20);

// instance: corner_node__g02 | base: corner_node | print_group: corner_node
color([0.13725, 0.80392, 0.92157, 1.00000])
translate([1800, -1800, 300]) rotate([0, 0, 0]) scale([1, 1, 1]) cylinder(h=360, r=180, center=true, $fn=20);

// instance: corner_node__g03 | base: corner_node | print_group: corner_node
color([0.13725, 0.80392, 0.92157, 1.00000])
translate([1800, 1800, 300]) rotate([0, 0, 0]) scale([1, 1, 1]) cylinder(h=360, r=180, center=true, $fn=20);

// instance: center_plate | base: center_plate | print_group: center_plate
color([1.00000, 0.67451, 0.14510, 1.00000])
translate([0, 0, 265]) rotate([0, 0, 0]) scale([1, 1, 1]) linear_extrude(height=90, center=true, convexity=10) polygon(points=[[680.0, 0.0], [531.25920446, 142.35047481], [588.89727457, 340.0], [388.90872965, 388.90872965], [340.0, 588.89727457], [142.35047481, 531.25920446], [0.0, 680.0], [-142.35047481, 531.25920446], [-340.0, 588.89727457], [-388.90872965, 388.90872965], [-588.89727457, 340.0], [-531.25920446, 142.35047481], [-680.0, 0.0], [-531.25920446, -142.35047481], [-588.89727457, -340.0], [-388.90872965, -388.90872965], [-340.0, -588.89727457], [-142.35047481, -531.25920446], [-0.0, -680.0], [142.35047481, -531.25920446], [340.0, -588.89727457], [388.90872965, -388.90872965], [588.89727457, -340.0], [531.25920446, -142.35047481]]);
