(function(){'use strict';var O=window.AXMOps,state=null,notice=document.getElementById('notice');
function parse(id){return JSON.parse(document.getElementById(id).value);}
function show(text,tone){O.notice(notice,text,tone);}
function esc(v){return O.esc(v);}
function render(){
 document.getElementById('facts').innerHTML='<span>'+state.families.length+' family contracts</span><span>'+state.candidates.length+' candidates</span><span>'+state.promoted.length+' promoted pieces</span><span>'+state.backup.pendingRequests+' backup requests</span>';
 document.getElementById('families').innerHTML=state.families.map(function(f){return '<div class="card"><b>'+esc(f.title)+'</b><p><code>'+esc(f.id)+'</code></p><p class="truth">'+esc(f.storagePolicy)+' · execution '+esc(f.executionAuthority)+'</p></div>';}).join('');
 document.getElementById('familyProposals').innerHTML=state.familyProposals.map(function(p){return '<div class="candidate"><span class="state">'+esc(p.state)+'</span><h3>'+esc(p.contract.title)+'</h3><code>'+esc(p.contractDigest)+'</code>'+(p.state==='PENDING_REVIEW'?'<div class="actions"><button data-family="'+esc(p.id)+'">Register after approval</button></div>':'')+'</div>';}).join('')||'<p class="truth">No custom-family proposals.</p>';
 document.getElementById('candidates').innerHTML=state.candidates.map(function(c){var unknown=c.state==='QUARANTINED_CATEGORY_PROPOSAL';return '<article class="candidate '+(unknown?'unknown':'')+'"><span class="state">'+esc(c.state)+'</span><h3>'+esc(c.piece.title)+'</h3><p>'+esc(c.piece.family)+' · '+esc(c.piece.id)+'@'+esc(c.piece.version)+'</p><code>'+esc(c.packageDigest)+'</code><p class="truth">'+c.fileCount+' files · '+O.bytes(c.bytes)+'</p><p>'+esc((c.compatibility.errors||[]).join(' · ')||(c.compatibility.warnings||[]).join(' · ')||'Contract compatible; no runtime claim.')+'</p><div class="actions">'+(c.state==='QUARANTINED_PENDING_REVIEW'?'<button data-review="'+esc(c.id)+'">Open review</button>':'')+(c.state==='QUARANTINED_REVIEW'?'<button data-promote="'+esc(c.id)+'">Promote approved digest</button>':'')+'</div></article>';}).join('')||'<p class="truth">Quarantine is empty.</p>';
 document.getElementById('promoted').innerHTML=state.promoted.map(function(p){return '<div class="card inert"><span class="state">'+esc(p.state)+'</span><h3>'+esc(p.piece.title)+'</h3><p>'+esc(p.targetRef)+'</p><code>'+esc(p.packageDigest)+'</code></div>';}).join('')||'<p class="truth">No promoted pieces. Promotion never happens automatically.</p>';
 bindDynamic();
}
function load(){return O.get('/api/modular-intake').then(function(v){state=v;render();}).catch(function(e){show(e.message,'bad');});}
function post(url,data,header,value){return O.post(url,data,(function(){var h={};h[header]=value;return h;})()).then(function(result){show('Recorded: '+(result.state||result.id||'done'),'ok');return load();}).catch(function(e){show(e.message,'bad');});}
function bindDynamic(){document.querySelectorAll('[data-review]').forEach(function(b){b.onclick=function(){post('/api/modular-intake/review',{candidateId:b.dataset.review,actor:'Mike'},'x-axm-modular-intake','open-exact-review');};});document.querySelectorAll('[data-promote]').forEach(function(b){b.onclick=function(){if(!confirm('Promote this exact approved digest? It remains inert.'))return;post('/api/modular-intake/promote',{candidateId:b.dataset.promote,actor:'Mike',confirmation:'PROMOTE REVIEWED PIECE'},'x-axm-modular-intake','promote-approved-digest');};});document.querySelectorAll('[data-family]').forEach(function(b){b.onclick=function(){if(!confirm('Register this exact reviewed neutral family contract?'))return;post('/api/modular-intake/family/apply',{proposalId:b.dataset.family,actor:'Mike',confirmation:'REGISTER REVIEWED FAMILY'},'x-axm-modular-intake','register-approved-family');};});}
document.getElementById('packageFile').onchange=function(e){var f=e.target.files[0];if(!f)return;f.text().then(function(text){document.getElementById('packageJson').value=text;});};
document.getElementById('inspect').onclick=function(){try{O.post('/api/modular-intake/inspect',parse('packageJson')).then(function(v){document.getElementById('inspectResult').textContent=O.pretty(v);}).catch(function(e){show(e.message,'bad');});}catch(e){show('Invalid JSON: '+e.message,'bad');}};
document.getElementById('stage').onclick=function(){try{post('/api/modular-intake/stage',parse('packageJson'),'x-axm-modular-intake','explicit-quarantine');}catch(e){show('Invalid JSON: '+e.message,'bad');}};
document.getElementById('proposeFamily').onclick=function(){try{post('/api/modular-intake/family/propose',{contract:parse('familyJson'),actor:'Mike'},'x-axm-modular-intake','propose-neutral-family');}catch(e){show('Invalid JSON: '+e.message,'bad');}};
document.getElementById('refresh').onclick=load;load();
})();
