// Generated by AXM Machine Geometry Foundry 0.4.0
// Asset: AXM-CONSOLE-001 AXM Interactive Control Console v0.4.0
// Units: millimetres; source orientation: +Z up, -Y forward.
// Canonical source is recipe.json. This is an editable generated bridge.

// instance: base | base: base | print_group: base
color([0.09412, 0.11373, 0.15294, 1.00000])
translate([0, 0, 75]) rotate([0, 0, 0]) scale([1, 1, 1]) cube([900, 700, 150], center=true);

// instance: pedestal | base: pedestal | print_group: pedestal
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([0, 40, 510]) rotate([0, 0, 0]) scale([1, 1, 1]) cylinder(h=760, r1=390, r2=300, center=true, $fn=12);

// instance: panel | base: panel | print_group: panel
color([0.17647, 0.22745, 0.29804, 1.00000])
translate([0, -170, 980]) rotate([0, 0, 0]) scale([1, 1, 1]) polyhedron(points=[[-425.0, -250.0, -130.0], [425.0, -250.0, -130.0], [425.0, -250.0, 130.0], [-425.0, 250.0, -130.0], [425.0, 250.0, -130.0], [425.0, 250.0, 130.0]], faces=[[0, 2, 1], [3, 4, 5], [0, 1, 4, 3], [1, 2, 5, 4], [2, 0, 3, 5]], convexity=10);

// instance: screen | base: screen | print_group: screen
color([0.13725, 0.80392, 0.92157, 1.00000])
translate([0, -430, 1060]) rotate([-10, 0, 0]) scale([1, 1, 1]) cube([560, 35, 260], center=true);

// instance: button__l00 | base: button | print_group: button
color([1.00000, 0.67451, 0.14510, 1.00000])
translate([-180, -446, 910]) rotate([90, 0, 0]) scale([1, 1, 1]) cylinder(h=35, r=45, center=true, $fn=16);

// instance: button__l01 | base: button | print_group: button
color([1.00000, 0.67451, 0.14510, 1.00000])
translate([-60, -446, 910]) rotate([90, 0, 0]) scale([1, 1, 1]) cylinder(h=35, r=45, center=true, $fn=16);

// instance: button__l02 | base: button | print_group: button
color([1.00000, 0.67451, 0.14510, 1.00000])
translate([60, -446, 910]) rotate([90, 0, 0]) scale([1, 1, 1]) cylinder(h=35, r=45, center=true, $fn=16);

// instance: button__l03 | base: button | print_group: button
color([1.00000, 0.67451, 0.14510, 1.00000])
translate([180, -446, 910]) rotate([90, 0, 0]) scale([1, 1, 1]) cylinder(h=35, r=45, center=true, $fn=16);
