(function(){
  'use strict';
  var profile=null,selectedMemberId=null,$=function(id){return document.getElementById(id);};
  function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function fmt(value){return Number(value||0).toLocaleString();}
  function call(url,options){return fetch(url,Object.assign({cache:'no-store'},options||{})).then(function(r){return r.json().catch(function(){return{};}).then(function(body){if(!r.ok)throw Error(body.error||('profile HTTP '+r.status));return body;});});}
  function liveMembers(){
    var list=window.AXMAIPresence&&AXMAIPresence.members?AXMAIPresence.members():[];
    var out=list.filter(function(m){return m&&m.id&&m.name;}).map(function(m){return{id:m.id,name:m.name,kind:['human','ai','machine'].indexOf(m.kind)>=0?m.kind:'ai'};});
    if(!out.some(function(m){return m.kind==='human';}))out.unshift({id:'local-human',name:'Mike',kind:'human'});
    return out.filter(function(m,i,a){return a.findIndex(function(x){return x.id===m.id;})===i;});
  }
  function statCard(value,label){return'<div class="profile-stat"><b>'+fmt(value)+'</b><span>'+label+'</span></div>';}
  function codeMoodBadges(m){var moods=m.codeMoods||{},labels={infrastructure:'infrastructure code',entertainment:'entertainment code',software:'software code'};return Object.keys(labels).map(function(key){return Number(moods[key])>0?'<span>'+labels[key]+'</span>':'';}).join('');}
  function codeMoodSummary(m){var moods=m.codeMoods||{},labels={infrastructure:'INFRA',entertainment:'PLAY',software:'SOFT'};return Object.keys(labels).map(function(key){return Number(moods[key])>0?'<small>'+labels[key]+' '+fmt(moods[key])+'</small>':'';}).join('');}
  function taskBadges(m){var categories=[['gamesPlayed','game testing'],['picturesMade','visual work'],['projectsCompleted','project delivery']];return categories.map(function(entry){return Number(m.stats&&m.stats[entry[0]])>0?'<span>'+entry[1]+'</span>':'';}).join('')+codeMoodBadges(m);}
  function lastCodeReceipt(){var events=profile&&profile.events||[],latest=null,latestTime=-1;events.forEach(function(event){if(!event||event.type!=='code-characters')return;var stamp=Date.parse(event.createdAt||0);if(!latest||Number.isFinite(stamp)&&stamp>latestTime){latest=event;latestTime=stamp;}});return latest;}
  function receiptHealth(){var event=lastCodeReceipt(),node=$('profileReceiptHealth');if(!node)return;if(!event){node.className='profile-receipt-health stale';node.innerHTML='<b>No code task receipt yet.</b> Code totals never guess authorship; a reviewed task must submit an exact count and evidence.';return;}var age=Date.now()-Date.parse(event.createdAt||0),stale=!Number.isFinite(age)||age>24*60*60*1000;node.className='profile-receipt-health'+(stale?' stale':'');node.innerHTML='<b>Last code receipt:</b> '+esc(new Date(event.createdAt).toLocaleString())+' · '+fmt(event.count)+' characters · '+esc(event.source||'AXM')+(stale?' · later coding may be waiting for a task receipt.':'');}
  function holderSpot(label,valueOf){var members=profile.members||[],values=members.map(function(m){return Number(valueOf(m))||0;}),amount=values.length?Math.max.apply(null,values):0,names=amount>0?members.filter(function(m){return Number(valueOf(m))===amount;}).map(function(m){return m.name;}):[];return'<article class="profile-holder '+(amount>0?'claimed':'open')+'"><span>'+esc(label)+'</span><b>'+esc(names.length?names.join(' + '):'Open spot')+'</b><small>'+fmt(amount)+' verified</small></article>';}
  function holderBoard(){return holderSpot('Game testing',function(m){return m.stats.gamesPlayed;})+holderSpot('Visual work',function(m){return m.stats.picturesMade;})+holderSpot('Project delivery',function(m){return m.stats.projectsCompleted;})+holderSpot('Infrastructure code',function(m){return(m.codeMoods||{}).infrastructure;})+holderSpot('Entertainment code',function(m){return(m.codeMoods||{}).entertainment;})+holderSpot('Software code',function(m){return(m.codeMoods||{}).software;});}
  function reflectionBars(items,kind){return'<div class="reflection-column '+kind+'"><h4>'+(kind==='strengths'?'Strengths':'Growth edges')+'</h4>'+items.map(function(item){return'<div class="reflection-trait"><div><b>'+esc(item.label)+'</b><span>'+fmt(item.score)+' / 5</span></div><i><em style="width:'+(Number(item.score)||0)*20+'%"></em></i><p>'+esc(item.evidence)+'</p></div>';}).join('')+'</div>';}
  function reflectionPanel(){var member=selectedMemberId&&profile.members.find(function(m){return m.id===selectedMemberId;});if(!member)return'<div class="reflection-empty"><h3>Evidence-backed strengths profile</h3><p>Choose a collaborator name above to view that identity’s self-authored and cross-validated infographic.</p></div>';var all=(profile.assessments||[]).filter(function(item){return item.subjectId===member.id;}),latest=all.slice(-1)[0],published=all.filter(function(item){return['VERIFIED','TRUTH','LINEAGE'].indexOf(item.status)>=0;}).slice(-1)[0],votes=latest?(latest.reviews||[]).filter(function(review){return review.verdict==='agree';}).length:0;var workflow=!latest?'<span class="reflection-status open">Waiting for '+esc(member.name)+' to submit</span>':latest.status==='REVISE'?'<span class="reflection-status revise">Changes requested · revision '+latest.revision+'</span>':'<span class="reflection-status '+latest.status.toLowerCase()+'">'+(latest.status==='IN_REVIEW'?'Review '+votes+' / 2':latest.status)+' · '+votes+' / 5 votes</span>';if(!published)return'<div class="reflection-head"><div><h3>'+esc(member.name)+' · strengths profile</h3><p>Self-authored, evidence-backed, and reviewed like a profile pull request.</p></div>'+workflow+'</div><div class="reflection-empty compact">Two independent approvals are required before an infographic becomes a verified profile claim.</div>';var reviewers=(published.reviews||[]).filter(function(review){return review.verdict==='agree';}).map(function(review){var found=profile.members.find(function(m){return m.id===review.reviewerId;});return found&&found.name;}).filter(Boolean);return'<div class="reflection-head"><div><h3>'+esc(member.name)+' · strengths profile</h3><p>'+esc(published.summary||'Self-authored reflection')+'</p></div>'+workflow+'</div><div class="reflection-infographic level-'+published.status.toLowerCase()+'">'+reflectionBars(published.strengths,'strengths')+reflectionBars(published.growthEdges,'growth')+'</div><div class="reflection-proof"><b>'+esc(published.status)+'</b> · '+(published.reviews||[]).filter(function(review){return review.verdict==='agree';}).length+' independent votes · '+esc(reviewers.join(', ')||'reviewers hidden')+'</div>';}
  function memberCard(m){var records=profile&&profile.achievements&&profile.achievements.records||[],lit=records.filter(function(r){return(r.unlockedFor||[]).some(function(x){return x.memberId===m.id;});}).length,badges=taskBadges(m);return'<article class="profile-member contribution-row"><div class="profile-member-head contribution-identity"><div><button class="member-profile-button" type="button" data-profile-member="'+esc(m.id)+'" aria-label="View '+esc(m.name)+' profile and achievements">'+esc(m.name)+'</button><div class="task-badges">'+badges+'</div></div><small>'+esc(m.kind.toUpperCase())+'</small></div><div class="contribution-number"><b>'+fmt(m.stats.gamesPlayed)+'</b><span>games</span></div><div class="contribution-number"><b>'+fmt(m.stats.picturesMade)+'</b><span>pictures</span></div><div class="contribution-number"><b>'+fmt(m.stats.projectsCompleted)+'</b><span>projects</span></div><div class="contribution-number code"><b>'+fmt(m.stats.codeCharacters)+'</b><span>code characters</span><div class="code-mood-list">'+codeMoodSummary(m)+'</div></div><div class="contribution-number emblem"><b>'+lit+'</b><span>emblems</span></div></article>';}
  function achievementCard(definition){var achievements=profile.achievements||{},record=(achievements.records||[]).find(function(r){return r.id===definition.id;})||{unlockedFor:[]},member=selectedMemberId&&profile.members.find(function(m){return m.id===selectedMemberId;}),value=Number((member?member.stats:profile.stats)&&((member?member.stats:profile.stats)[definition.stat]))||0,memberUnlock=member&&(record.unlockedFor||[]).find(function(entry){return entry.memberId===member.id;}),unlocked=member?!!memberUnlock:!!record.teamUnlockedAt,progress=Math.max(0,Math.min(100,Math.round(value/definition.threshold*100))),memberNames=(record.unlockedFor||[]).map(function(entry){var found=profile.members.find(function(m){return m.id===entry.memberId;});return found&&found.name;}).filter(Boolean);var unlockedBy=member?(unlocked?'Lit for '+member.name:'Locked for '+member.name):(memberNames.length?'Lit for '+memberNames.join(', '):(unlocked?'Team total':'Locked')),tier=['primal','gold','diamond'].indexOf(definition.tier)>=0?definition.tier:'primal';return'<article class="profile-achievement tier-'+tier+' '+(unlocked?'unlocked':'locked')+'" data-tier="'+tier+'" data-achievement="'+esc(definition.id)+'"><div class="achievement-emblem" data-master-size="512" data-safe-artwork="420" title="512 x 512 master, 420 x 420 safe artwork"><img src="'+esc(definition.asset)+'" alt="" onerror="this.hidden=true"><span>'+esc(definition.symbol)+'</span></div><h4>'+esc(definition.title)+'</h4><p>'+esc(definition.description)+'</p><div class="achievement-progress"><i style="width:'+progress+'%"></i></div><div class="achievement-meta"><span>'+esc(unlockedBy)+'</span><span>'+fmt(Math.min(value,definition.threshold))+' / '+fmt(definition.threshold)+'</span></div></article>';}
  function render(){
    if(!profile)return;
    $('profileState').textContent=profile.enabled?'OPTED IN · PAUSE':'OFF · OPT IN';$('profileState').classList.toggle('on',profile.enabled);$('profileState').setAttribute('aria-pressed',profile.enabled?'true':'false');$('profileState').title=profile.enabled?'Pause profile tracking · existing history stays':'Set up the optional local profile';$('profileMark').classList.toggle('profile-on',profile.enabled);
    $('profileOff').hidden=profile.enabled;$('profileOn').hidden=!profile.enabled;
    var button=$('profileToggle');button.classList.toggle('on',profile.enabled);button.innerHTML=profile.enabled?'<span>Profile</span> · '+fmt(profile.stats.gamesPlayed+profile.stats.picturesMade+profile.stats.projectsCompleted)+' moments':'<span>Profile</span> off';
    if(!profile.enabled)return;
    $('profileName').textContent=profile.displayName;
    $('profileTotals').innerHTML=statCard(profile.stats.gamesPlayed,'games played')+statCard(profile.stats.picturesMade,'pictures made')+statCard(profile.stats.projectsCompleted,'projects completed')+statCard(profile.stats.codeCharacters,'code characters');
    $('profileHolders').innerHTML=holderBoard();
    $('profileMembers').innerHTML=profile.members.map(memberCard).join('')||'<p class="profile-note">No collaborators have joined yet.</p>';
    $('profileReflection').innerHTML=reflectionPanel();
    var catalog=profile.achievements&&profile.achievements.catalog||[],records=profile.achievements&&profile.achievements.records||[],selectedMember=selectedMemberId&&profile.members.find(function(m){return m.id===selectedMemberId;});if(selectedMemberId&&!selectedMember)selectedMemberId=null;var lit=selectedMember?records.filter(function(r){return(r.unlockedFor||[]).some(function(x){return x.memberId===selectedMember.id;});}).length:records.filter(function(r){return!!r.teamUnlockedAt;}).length;$('profileAchievementOwner').textContent=selectedMember?selectedMember.name:profile.displayName;$('profileAchievementTeam').hidden=!selectedMember;$('profileAchievements').innerHTML=catalog.map(achievementCard).join('');$('profileAchievementCount').textContent=lit+' / '+catalog.length+' lit';
    $('profileCodeActor').innerHTML=profile.members.map(function(m){return'<option value="'+esc(m.id)+'">'+esc(m.name)+'</option>';}).join('');
    receiptHealth();
  }
  function refresh(){return call('/api/profile').then(function(r){profile=r.profile;render();return profile;}).catch(function(e){message(e.message,true);});}
  function message(text,bad){var node=$('profileMessage');node.textContent=text||'';node.style.color=bad?'#ff8292':'';}
  function open(){document.querySelectorAll('.overlay.show').forEach(function(n){n.classList.remove('show');});$('profileScreen').classList.add('show');refresh();}
  function close(){$('profileScreen').classList.remove('show');}
  $('profileToggle').addEventListener('click',open);$('profileMark').addEventListener('click',open);$('profileClose').addEventListener('click',close);$('profileScreen').addEventListener('click',function(e){if(e.target===$('profileScreen'))close();});
  function pauseProfile(){return call('/api/profile/opt-out',{method:'POST',headers:{'content-type':'application/json','x-axm-profile':'local-opt-out'},body:JSON.stringify({decidedBy:'local-human'})}).then(function(r){profile=r.profile;render();message('Tracking paused. Achievements and local history are preserved.');});}
  $('profileState').addEventListener('click',function(){if(profile&&profile.enabled)pauseProfile().catch(function(e){message(e.message,true);});else{$('profileOff').scrollIntoView({behavior:'smooth',block:'start'});setTimeout(function(){$('profileDisplayName').focus();},250);}});
  $('profileEnable').addEventListener('click',function(){
    var name=$('profileDisplayName').value.trim()||'AXM Team';
    call('/api/profile/opt-in',{method:'POST',headers:{'content-type':'application/json','x-axm-profile':'local-opt-in'},body:JSON.stringify({displayName:name,decidedBy:'local-human',members:liveMembers()})}).then(function(r){profile=r.profile;render();message('Profile enabled locally. New activity can now be counted.');}).catch(function(e){message(e.message,true);});
  });
  $('profileSync').addEventListener('click',function(){call('/api/profile/members',{method:'POST',headers:{'content-type':'application/json','x-axm-profile':'sync-local-members'},body:JSON.stringify({members:liveMembers()})}).then(function(r){profile=r.profile;render();message('Current collaborators added. Existing member history stayed intact.');}).catch(function(e){message(e.message,true);});});
  $('profileStop').addEventListener('click',function(){pauseProfile().catch(function(e){message(e.message,true);});});
  $('profileDelete').addEventListener('click',function(){if(!confirm('Delete the complete local shared profile and its activity history?'))return;if(!confirm('This cannot be undone. Delete it now?'))return;call('/api/profile',{method:'DELETE',headers:{'x-axm-profile':'delete-local-profile'}}).then(function(r){profile=r.profile;render();message('Local profile deleted.');}).catch(function(e){message(e.message,true);});});
  $('profileExport').addEventListener('click',function(){var blob=new Blob([JSON.stringify(profile,null,2)+'\n'],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='axm-shared-profile.json';a.click();setTimeout(function(){URL.revokeObjectURL(a.href);},1000);});
  $('profileMembers').addEventListener('click',function(e){var button=e.target.closest('[data-profile-member]');if(!button)return;selectedMemberId=button.dataset.profileMember;render();$('profileAchievements').scrollIntoView({behavior:'smooth',block:'start'});});
  $('profileAchievementTeam').addEventListener('click',function(){selectedMemberId=null;render();});
  $('profileCodeReceipt').addEventListener('submit',function(e){e.preventDefault();var actor=$('profileCodeActor').value,mood=$('profileCodeMood').value,count=Number($('profileCodeCount').value),evidence=$('profileCodeEvidence').value.trim();window.AXMProfile.record({type:'code-characters',codeMood:mood,count:count,dedupeKey:'code:'+actor+':'+Date.now(),participants:[actor],actorId:actor,evidence:evidence,source:'AXM reviewed code receipt',meta:{codeMood:mood}}).then(function(){e.target.reset();message('Verified '+mood+' code contribution counted.');return refresh();}).catch(function(err){message(err.message,true);});});
  refresh();setInterval(function(){if($('profileScreen').classList.contains('show'))refresh();},15000);
})();
