(function(){
  'use strict';
  var KEY='axm.hub.spotify.v1',PKCE='axm.hub.spotify.pkce.v1',API='https://api.spotify.com/v1';
  var state={clientId:'',accessToken:'',refreshToken:'',expiresAt:0};
  var current=null,poll=null,status,setup,controls,clientInput,redirectInput;
  function read(){try{state=Object.assign(state,JSON.parse(localStorage.getItem(KEY)||'{}'));}catch(e){}}
  function save(){try{localStorage.setItem(KEY,JSON.stringify(state));}catch(e){}}
  function redirectUri(){return location.origin+'/hub/index.html';}
  function setStatus(text,kind){status.textContent=text;status.className=kind||'';}
  function randomString(length){var chars='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~',bytes=crypto.getRandomValues(new Uint8Array(length)),out='';for(var i=0;i<bytes.length;i++)out+=chars[bytes[i]%chars.length];return out;}
  function base64url(buffer){var bytes=new Uint8Array(buffer),binary='';for(var i=0;i<bytes.length;i++)binary+=String.fromCharCode(bytes[i]);return btoa(binary).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_');}
  async function connect(){var clientId=clientInput.value.trim();if(!/^[a-z0-9]{20,64}$/i.test(clientId)){setStatus('CLIENT ID LOOKS INVALID','bad');return;}state.clientId=clientId;save();var verifier=randomString(64),requestState=randomString(32),digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier)),challenge=base64url(digest);sessionStorage.setItem(PKCE,JSON.stringify({verifier:verifier,state:requestState,redirect:redirectUri()}));var url=new URL('https://accounts.spotify.com/authorize');url.search=new URLSearchParams({client_id:clientId,response_type:'code',redirect_uri:redirectUri(),state:requestState,scope:'user-read-playback-state user-modify-playback-state',code_challenge_method:'S256',code_challenge:challenge,show_dialog:'false'}).toString();location.href=url.toString();}
  async function exchange(code,record){var response=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:state.clientId,grant_type:'authorization_code',code:code,redirect_uri:record.redirect,code_verifier:record.verifier})}),body=await response.json();if(!response.ok)throw new Error(body.error_description||body.error||('token HTTP '+response.status));storeTokens(body);sessionStorage.removeItem(PKCE);}
  function storeTokens(body){state.accessToken=body.access_token||'';if(body.refresh_token)state.refreshToken=body.refresh_token;state.expiresAt=Date.now()+Math.max(30,Number(body.expires_in||3600)-30)*1000;save();}
  async function refreshToken(){if(!state.refreshToken||!state.clientId)throw new Error('Spotify reconnection required');var response=await fetch('https://accounts.spotify.com/api/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'refresh_token',refresh_token:state.refreshToken,client_id:state.clientId})}),body=await response.json();if(!response.ok){if(body.error==='invalid_grant')disconnect(false);throw new Error(body.error_description||body.error||('refresh HTTP '+response.status));}storeTokens(body);return state.accessToken;}
  async function token(){if(state.accessToken&&state.expiresAt>Date.now()+15000)return state.accessToken;return refreshToken();}
  async function spotify(path,options,retry){var access=await token(),response=await fetch(API+path,Object.assign({},options||{},{headers:Object.assign({},options&&options.headers||{},{authorization:'Bearer '+access})}));if(response.status===401&&retry!==false){state.expiresAt=0;return spotify(path,options,false);}if(response.status===204)return null;if(response.status===429)throw new Error('Spotify rate limit · retry later');if(!response.ok){var body=null;try{body=await response.json();}catch(e){}throw new Error(body&&body.error&&body.error.message||('Spotify HTTP '+response.status));}var type=response.headers.get('content-type')||'';return type.indexOf('json')>=0?response.json():null;}
  function connected(){return!!(state.clientId&&state.refreshToken);}
  function showConnected(value){setup.hidden=value;controls.hidden=!value;if(!value){current=null;setStatus(state.clientId?'READY TO CONNECT':'NOT CONNECTED','');}}
  function renderPlayback(playback){current=playback;if(!playback||!playback.device){document.getElementById('spotifyTrack').textContent='No active Spotify device';document.getElementById('spotifyArtist').textContent='Start DJ in Spotify, then press Refresh.';document.getElementById('spotifyToggle').textContent='▶';setStatus('CONNECTED · WAITING FOR DEVICE','');return;}var item=playback.item||{},artists=(item.artists||[]).map(function(a){return a.name;}).join(', ');document.getElementById('spotifyTrack').textContent=item.name||playback.currently_playing_type||'Spotify playback';document.getElementById('spotifyArtist').textContent=(artists?artists+' · ':'')+playback.device.name+' · '+(playback.device.volume_percent==null?'volume unavailable':playback.device.volume_percent+'%');document.getElementById('spotifyToggle').textContent=playback.is_playing?'❚❚':'▶';setStatus('CONNECTED · '+(playback.is_playing?'PLAYING':'PAUSED'),'live');}
  async function refreshPlayback(){if(!connected())return;try{renderPlayback(await spotify('/me/player'));}catch(e){setStatus(e.message,'bad');}}
  async function command(path,method){try{if(path==='/me/player/play'&&window.AXMHubRadio&&AXMHubRadio.isPlaying())AXMHubRadio.stop();await spotify(path,{method:method});setTimeout(refreshPlayback,450);}catch(e){setStatus(e.message,'bad');}}
  async function volumeBy(delta){var amount=current&&current.device&&Number(current.device.volume_percent);if(!Number.isFinite(amount)){setStatus('NO ACTIVE VOLUME DEVICE','bad');return;}amount=Math.max(0,Math.min(100,amount+delta));await command('/me/player/volume?volume_percent='+amount,'PUT');}
  function disconnect(keepClient){state.accessToken='';state.refreshToken='';state.expiresAt=0;if(!keepClient)state.clientId='';save();clientInput.value=state.clientId;showConnected(false);if(poll){clearInterval(poll);poll=null;}}
  async function callback(){var params=new URLSearchParams(location.search),code=params.get('code'),error=params.get('error');if(!code&&!error)return false;document.getElementById('radioScreen').classList.add('show');history.replaceState({},'',location.pathname+location.hash);if(error){setStatus('SPOTIFY DENIED · '+error,'bad');return true;}var record=null;try{record=JSON.parse(sessionStorage.getItem(PKCE)||'null');}catch(e){}if(!record||record.state!==params.get('state')){setStatus('SPOTIFY STATE CHECK FAILED','bad');return true;}setStatus('CONNECTING ACCOUNT…','');try{await exchange(code,record);showConnected(true);startPolling();await refreshPlayback();}catch(e){setStatus(e.message,'bad');}return true;}
  function startPolling(){if(poll)clearInterval(poll);poll=setInterval(function(){if(document.visibilityState==='visible')refreshPlayback();},7000);}
  async function init(){status=document.getElementById('spotifyStatus');setup=document.getElementById('spotifySetup');controls=document.getElementById('spotifyControls');clientInput=document.getElementById('spotifyClientId');redirectInput=document.getElementById('spotifyRedirect');if(!status||!setup||!controls||!clientInput||!redirectInput)return;read();clientInput.value=state.clientId||'';redirectInput.value=redirectUri();document.getElementById('spotifyConnect').onclick=connect;document.getElementById('spotifyCopyRedirect').onclick=async function(){try{await navigator.clipboard.writeText(redirectUri());this.textContent='Copied';}catch(e){redirectInput.select();this.textContent='Select + copy';}};document.getElementById('spotifyDisconnect').onclick=function(){disconnect(true);};document.getElementById('spotifyRefresh').onclick=refreshPlayback;document.getElementById('spotifyPrevious').onclick=function(){command('/me/player/previous','POST');};document.getElementById('spotifyNext').onclick=function(){command('/me/player/next','POST');};document.getElementById('spotifyToggle').onclick=function(){command(current&&current.is_playing?'/me/player/pause':'/me/player/play','PUT');};document.getElementById('spotifyVolumeDown').onclick=function(){volumeBy(-10);};document.getElementById('spotifyVolumeUp').onclick=function(){volumeBy(10);};showConnected(connected());var handled=await callback();if(connected()){startPolling();if(!handled)await refreshPlayback();}window.AXMSpotifyController={connected:connected,refresh:refreshPlayback};}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
