'use strict';
const Discovery=require('../../tools/discovery-engine/discovery-core'),Canaries=require('./physics-canaries'),Physics=require('./axm-physics-core');
const BASE='2026-07-12T20:00:00.000Z';
function meta(id,offset){return{actorId:'axiom-mir',actorKind:'MACHINE',provider:'codex-local-workshop',model:'gpt-5',now:new Date(Date.parse(BASE)+(offset||0)*1000).toISOString(),recordId:id,eventId:'event-'+id};}
function add(state,stage,id,text,rationale,offset){const r=Discovery.recordDiscovery(state,stage,{text,claimLabel:'HYPOTHESIS',source:'AXM Physics Core local code and harness',rationale,status:'INTERNAL_MACHINE_REVIEW'},meta(id,offset));if(!r.ok)throw Error(r.errors[0].message);return r.state;}
function candidate(state,id,data,offset){const r=Discovery.createCandidate(state,data,meta(id,offset));if(!r.ok)throw Error(r.errors[0].message);return r.state;}
function run(){let state=Discovery.createSession({id:'physics-inventor-loop',title:'AXM Physics Core invention loop',subject:'AXM shared 2D Physics Core',question:'Which bounded changes make the core more inspectable, replayable and useful without overstating scientific validity?',intendedUse:'Shared games and interactive-prototype infrastructure',boundaries:['2D translation','local deterministic-order JavaScript','prototype and game logic'],exclusions:['scientific certification','general 3D','fluids','deformables'],stakes:'MEDIUM',evidenceProfile:'COMPUTATIONAL',discoveryMode:'MANUAL'},meta('session',0));
  const pass1=[
    ['knownSpace','p1-known','The v0.1 slice already had fixed stepping, adaptive substeps, circles, axis-aligned boxes, impulses, friction, restitution, sensors, bounds, queries and checksums.','Preserve working mechanics before widening scope.'],
    ['rejectedDirections','p1-reject','Do not jump directly to 3D, fluids or a large external engine before the shared adapter, evidence contract and game-project seam are stable.','Large scope would hide whether the reusable spine is sound.'],
    ['blindSpots','p1-blind','The engine lacked permanent analytic canaries, replay traces, contact lifecycle events and collision filtering.','These omissions make a game engine difficult to debug or safely reuse.'],
    ['seams','p1-seam-substeps','Adaptive substeps changed the internal discrete method while the first free-fall canary assumed one integration step per outer step.','A numerical control must isolate requested timestep from adaptive safety behavior.'],
    ['seams','p1-seam-sensors','Sensors exposed overlap contacts but not ENTER, STAY and EXIT transitions.','Gameplay triggers need lifecycle semantics rather than polling raw contact arrays.'],
    ['seams','p1-seam-ray','Circle raycasts used an AABB approximation, making hit distance geometrically inaccurate.','Queries should match declared shape geometry.'],
    ['patterns','p1-pattern','Canaries, sampled trace lineage and explicit contact events form one evidence spine: every motion result becomes easier to reproduce and challenge.','The same evidence mechanics serve games, tests and future research adapters.'],
    ['realityChecks','p1-reality','The strongest near-term value is inspectability, not more shape types. The solver is still O(n²), translation-only and prototype-grade.','Do not confuse feature count with trustworthy capability.'],
    ['soulChecks','p1-soul','Replayable diagnostics and explicit triggers help both human and machine collaborators understand the same simulation state without privileged controls.','Same-gate inspection is useful even outside commercial game work.'],
    ['minimalChecks','p1-test','Run stationary, constant-velocity, free-fall convergence, isolated momentum, deterministic replay and units canaries before promoting the next core version.','These cheap checks can disconfirm basic integration claims.']
  ];pass1.forEach((x,i)=>{state=add(state,x[0],x[1],x[2],x[3],10+i);});
  state=candidate(state,'candidate-evidence-spine',{term:'Inspectable Physics Evidence Spine',summary:'Add permanent canaries, replay trace lineage, exact queries, collision filters and contact lifecycle events before widening the solver.',mechanism:'Expose numerical and interaction semantics as versioned machine-readable outputs around the existing fixed-step core.',whyNotYet:'v0.1 returned useful final state but hid important lifecycle and evidence structure.',viableNowBecause:'The shared adapter, Game Forge lab and Discovery physics controls now exist.',dependencies:['AXM Physics Core','Discovery computational controls','Game Forge Physics Lab'],noveltyStatus:'UNCHECKED',soulGate:{genuineNeed:'PASS',nonCommercialWorth:'PASS',reducesPain:'PASS',sameGateAccess:'PASS',avoidsLockIn:'PASS',notes:['No external dependency required.']},minimalForm:'Seven canaries, bounded traces, exact circle rays, filters and ENTER/STAY/EXIT events.',cheapestDisconfirmingCheck:'Run the permanent canaries and focused lifecycle/filter/query tests.',disconfirmingOutcome:'Any canary failure or mismatched replay checksum blocks the version claim.',limitations:['Still 2D translation only','Internal review, not independent validation']},20);
  const canaries=Canaries.run();
  const pass2=[
    ['knownSpace','p2-known','After iteration, seven permanent computational/physics canaries pass and v'+Physics.VERSION+' exposes filters, lifecycle events, energy fields, exact circle raycasts and bounded replay traces.','This is measured in the local harness but remains internal machine review.'],
    ['seams','p2-seam-broadphase','The all-pairs broadphase remains O(n²); the API complexity gate limits damage but does not make large scenes efficient.','A spatial index should be a versioned adapter change with equivalence tests.'],
    ['seams','p2-seam-manifold','Contacts use one normal and one representative point with no rotation, angular mass, warm starting or persistent manifold impulses.','Stacking and compound shapes will eventually need a constraint branch.'],
    ['seams','p2-seam-energy','Potential energy uses an arbitrary zero reference and energy delta includes damping, inelastic impacts and boundary work; it is a diagnostic, not a conservation verdict.','The UI must not turn a convenient number into proof.'],
    ['blindSpots','p2-blind','High-speed thin-wall tunnelling at the maximum substep cap, long-stack jitter and randomized shape/property invariants are not yet covered.','Passing analytic canaries does not cover adversarial geometry.'],
    ['patterns','p2-pattern','The next useful branch is not “more physics” generally; it is a constraint/manifold branch paired with adversarial and performance harnesses.','Keep mechanics and evidence controls advancing together.'],
    ['realityChecks','p2-reality','v0.2 is suitable for small games and prototypes. It should refuse scientific, large-scene, rotational or general-purpose engine claims.','The remaining gaps are architectural rather than cosmetic.'],
    ['minimalChecks','p2-test','Before v0.3, sweep thin-wall speed/size ratios, measure 16/32/64/128-body cost, run a ten-box rest stack, and fuzz symmetric collision invariants.','These tests choose whether broadphase, CCD or manifolds deserve the next implementation slot.']
  ];pass2.forEach((x,i)=>{state=add(state,x[0],x[1],x[2],x[3],30+i);});
  state=candidate(state,'candidate-constraint-branch',{term:'Constraint and Manifold Branch',summary:'A future v0.3 branch for rotational bodies, persistent contact manifolds and joints, gated by adversarial and performance harnesses.',mechanism:'Introduce angular state and iterative constraints behind a new adapter capability while retaining v0.2 translation compatibility.',whyNotYet:'Current evidence does not establish acceptable stacking, thin-wall or scaling behavior for the larger branch.',viableNowBecause:'v0.2 provides replay traces, canaries and lifecycle evidence needed to compare a new solver.',dependencies:['adversarial CCD sweep','stack stability harness','broadphase benchmark','compatibility fixtures'],noveltyStatus:'UNCHECKED',soulGate:{genuineNeed:'PASS',nonCommercialWorth:'PASS',reducesPain:'PASS',sameGateAccess:'PASS',avoidsLockIn:'PASS',notes:['Keep as proposed work until its disconfirming tests exist.']},minimalForm:'Rotating box/circle state, one persistent manifold type and one distance joint behind explicit v0.3 capability flags.',cheapestDisconfirmingCheck:'Demonstrate a stable ten-box stack and timestep-consistent pendulum without breaking v0.2 replay fixtures.',disconfirmingOutcome:'Unbounded energy growth, worsening convergence or incompatible v0.2 fixtures rejects the branch.',limitations:['Proposal only','No implementation or performance claim yet'],supersedes:'candidate-evidence-spine'},45);
  const validation=Discovery.validate(state);if(!validation.ok)throw Error(validation.errors.join('; '));return{schema:'axm.physics-inventor-loop/v1',passes:2,engineVersion:Physics.VERSION,canaries,state,summary:{records:state.history.events.length,candidates:state.discovery.candidates.map(x=>({id:x.id,term:x.term,status:x.status})),remainingSeams:state.discovery.seams.filter(x=>/^p2-/.test(x.id)).map(x=>x.text)},truth:{modelReviewIsIndependent:false,findingsAreCanon:false,implementedCandidate:'Inspectable Physics Evidence Spine',proposedCandidate:'Constraint and Manifold Branch'}};}
if(require.main===module){const r=run();console.log('AXM Physics Inventor loop: PASS · passes='+r.passes+' · engine='+r.engineVersion+' · canaries='+r.canaries.summary.pass+'/'+(r.canaries.summary.pass+r.canaries.summary.fail));console.log('Implemented:',r.truth.implementedCandidate);console.log('Next proposal:',r.truth.proposedCandidate);r.summary.remainingSeams.forEach((x,i)=>console.log('OPEN '+(i+1)+' · '+x));}
module.exports={run};
