(function(){
  'use strict';
  var STORAGE='axm.accessibility-adaptation-lab.profile.v1',state={catalog:null,profile:null};
  function $(id){return document.getElementById(id);}
  function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(ch){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch];});}
  function profileFromControls(){return{textScale:Number($('textScale').value),contrast:$('contrast').value,spacing:$('spacing').value,density:$('density').value,focus:$('focus').value,language:$('language').value};}
  function controlsFromProfile(value){value=value||{};$('textScale').value=value.textScale||110;$('contrast').value=value.contrast||'standard';$('spacing').value=value.spacing||'standard';$('density').value=value.density||'standard';$('focus').value=value.focus||'enhanced';$('language').value=value.language||'standard';}
  function renderPreview(profile,persisted){
    var preview=$('preview');profile=profile||profileFromControls();state.profile=profile;preview.style.setProperty('--preview-scale',profile.textScale+'%');preview.dataset.contrast=profile.contrast;preview.dataset.spacing=profile.spacing;preview.dataset.density=profile.density;preview.dataset.focus=profile.focus;$('textScaleValue').value=profile.textScale+'%';
    var plain=profile.language==='plain';$('previewHeading').textContent=plain?'Check this change':'Review this change before continuing';$('previewCopy').textContent=plain?'Check where this will go and who can change it. Choose Go back to cancel.':'Confirm the destination and access level. You can go back without saving any changes.';$('profileState').textContent=persisted?'SAVED LOCALLY':'SESSION';
  }
  function saveProfile(){var profile=profileFromControls();localStorage.setItem(STORAGE,JSON.stringify(profile));renderPreview(profile,true);announce('Local preview saved. It affects this tool only.');}
  function resetProfile(){localStorage.removeItem(STORAGE);var profile={textScale:110,contrast:'standard',spacing:'standard',density:'standard',focus:'enhanced',language:'standard'};controlsFromProfile(profile);renderPreview(profile,false);announce('Local preview reset.');}
  function announce(message){$('planResult').textContent=message;}
  function moduleCard(row){return'<article class="module-card"><b>'+esc(row.title)+'</b><p>'+esc(row.purpose)+'</p><div class="module-meta"><span>#'+esc(row.seed)+'</span><span>'+esc(row.package)+'</span><span>'+esc(row.riskClass.replace(/_/g,' '))+'</span>'+(row.adapterOrEvidenceBound?'<span>ADAPTER / EVIDENCE BOUND</span>':'')+'</div><a href="'+esc(row.packetUrl)+'" target="_blank" rel="noopener">Open source packet</a></article>';}
  function renderCatalog(){if(!state.catalog)return;var query=$('search').value.trim().toLowerCase(),family=$('familyFilter').value;var rows=state.catalog.modules.filter(function(row){var text=(row.id+' '+row.title+' '+row.purpose+' '+row.family).toLowerCase();return(!query||text.indexOf(query)>=0)&&(!family||row.family===family);});$('visibleCount').textContent=rows.length+' VISIBLE';$('catalogList').innerHTML=rows.length?rows.map(moduleCard).join(''):'<p class="empty">No packets match this filter.</p>';}
  function selectedGoals(){var goals=Array.prototype.slice.call(document.querySelectorAll('.goal-grid input:checked')).map(function(input){return input.value;}),custom=$('customGoal').value.trim();if(custom)goals.push(custom);return goals;}
  async function buildPlan(){var button=$('buildPlan');button.disabled=true;announce('Building a bounded local plan…');try{var response=await fetch('/api/accessibility-adaptation/plan',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({goals:selectedGoals(),profile:profileFromControls()})}),body=await response.json();if(!response.ok)throw new Error(body.error||('HTTP '+response.status));var cards=body.recommendedModules.map(function(row){return'<div class="plan-card"><b>'+esc(row.title)+'</b><span>'+esc(row.package)+' · score '+esc(row.score)+'</span></div>';}).join('');$('planResult').innerHTML='<h3>'+body.recommendedModules.length+' packets recommended for review</h3><p>This plan does not activate them or claim compatibility.</p><div class="plan-grid">'+cards+'</div>';}
    catch(error){announce('Plan unavailable: '+String(error.message||error));}finally{button.disabled=false;}}
  async function loadCatalog(){try{var response=await fetch('/api/accessibility-adaptation/catalog'),body=await response.json();if(!response.ok)throw new Error(body.error||('HTTP '+response.status));state.catalog=body;$('moduleCount').textContent=body.moduleCount;$('familyCount').textContent=body.familyCount;$('packageCount').textContent=body.packageCount;$('boundCount').textContent=body.adapterOrEvidenceBoundCount;var families=Array.from(new Set(body.modules.map(function(row){return row.family;}))).sort();families.forEach(function(family){var option=document.createElement('option');option.value=family;option.textContent=family;$('familyFilter').appendChild(option);});renderCatalog();}catch(error){$('catalogList').innerHTML='<p class="empty">Catalog unavailable: '+esc(error.message||error)+'</p>';$('visibleCount').textContent='OFFLINE';}}
  function init(){var saved=null;try{saved=JSON.parse(localStorage.getItem(STORAGE)||'null');}catch(error){}controlsFromProfile(saved);renderPreview(profileFromControls(),!!saved);['textScale','contrast','spacing','density','focus','language'].forEach(function(id){$(id).addEventListener('input',function(){renderPreview(profileFromControls(),false);});});$('applyProfile').addEventListener('click',saveProfile);$('resetProfile').addEventListener('click',resetProfile);$('buildPlan').addEventListener('click',buildPlan);$('search').addEventListener('input',renderCatalog);$('familyFilter').addEventListener('change',renderCatalog);loadCatalog();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
