(function(){
  'use strict';
  var C=window.AXMSpatialCore,G=window.AXMSpatialGeometry,R=window.AXMSpatialRenderer,$=function(id){return document.getElementById(id);},STORE='axm.spatial.project.v1',SHARED_STORE='axm.spatial.shared.v1',PUBLISH='axm.publish-library.ledger.v1',project=null,sharedProject=null,renderer=null,selectedId=null,mode='scene',playing=null,toastTimer=null;
  function esc(v){return String(v==null?'':v).replace(/[&<>'"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c];});}
  function clean(v,n){return String(v==null?'':v).trim().slice(0,n||2000);}
  function selected(){return project.objects.find(function(o){return o.id===selectedId;})||null;}
  function toast(message){$('toast').textContent=message;$('toast').classList.add('show');$('engine-status').textContent=message;clearTimeout(toastTimer);toastTimer=setTimeout(function(){$('toast').classList.remove('show');},2200);if(window.AXMHub)AXMHub.log(message);}
  function download(name,data,type){var blob=data instanceof Blob?data:new Blob([data],{type:type||'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url);},1200);}
  function jsonDownload(name,data){download(name,JSON.stringify(data,null,2),'application/json');}
  function slug(){return C.slug(project.name||'spatial');}
  function openHands(){var drawer=$('hands-drawer'),backdrop=$('hands-backdrop'),frame=$('hands-frame');drawer.classList.add('open');drawer.setAttribute('aria-hidden','false');backdrop.hidden=false;if(!frame.dataset.loaded){frame.dataset.loaded='1';frame.src='../../shared/asset-hands/index.html?host=spatial-studio&kind=mesh&medium=3d-surface&use=mesh&target='+encodeURIComponent(project.name||'spatial');}}
  function closeHands(){var drawer=$('hands-drawer');drawer.classList.remove('open');drawer.setAttribute('aria-hidden','true');$('hands-backdrop').hidden=true;}
  function syncShared(label){if(!window.AXMEngines)return;try{
    var actor={id:'spatial-studio',kind:'service',name:'Spatial Studio'};
    if(!sharedProject||!AXMEngines.Project.validate(sharedProject).ok)sharedProject=AXMEngines.Project.create({id:project.id,kind:'spatial-3d',name:project.name,documentSchema:C.FORMAT,data:project,actor:actor});else sharedProject=AXMEngines.Project.update(sharedProject,project,actor,label||'local autosave');
    if(label)sharedProject=AXMEngines.Project.checkpoint(sharedProject,label,actor).project;
    var scene=AXMEngines.Scene.create(3);project.objects.forEach(function(o){scene=AXMEngines.Scene.add(scene,{id:o.id,parentId:o.parentId,type:o.type,name:o.name,x:o.position[0],y:o.position[1],z:o.position[2],rotation:o.rotation[1],scaleX:o.scale[0],scaleY:o.scale[1],scaleZ:o.scale[2],props:{materialId:o.materialId,geometry:o.geometry}}).graph;});
    var timeline=AXMEngines.Timeline.create({unit:'frames',rate:project.fps,duration:project.durationFrames}),trackBy={};project.objects.forEach(function(o){var t=AXMEngines.Timeline.addTrack(timeline,{id:'track-'+o.id,name:o.name,kind:'transform'});timeline=t.timeline;var c=AXMEngines.Timeline.addClip(timeline,{id:'clip-'+o.id,trackId:t.track.id,name:o.name+' transform',start:0,duration:project.durationFrames,sourceId:o.id});timeline=c.timeline;trackBy[o.id]=c.clip.id;});project.keyframes.forEach(function(k){if(trackBy[k.objectId])timeline=AXMEngines.Timeline.addKeyframe(timeline,{clipId:trackBy[k.objectId],property:k.property,time:k.frame,value:k.value,easing:k.easing}).timeline;});
    var evidence=AXMEngines.Evidence.create(project.name+' spatial receipts');project.simulationReceipts.slice(-20).forEach(function(r){evidence=AXMEngines.Evidence.add(evidence,{kind:'test',statement:'Bounded 2D projection simulation completed',evidence:[r.checksum||r.status||'receipt'],confidence:'medium'},actor).ledger;});
    localStorage.setItem(SHARED_STORE,JSON.stringify({schema:'axm.spatial.shared-snapshot/v1',project:sharedProject,scene:scene,timeline:timeline,evidence:evidence,updatedAt:C.now()}));
  }catch(error){console.warn('Spatial shared-engine sync',error);}}
  function save(message){project.name=clean($('project-name').value,120)||project.name;project.updatedAt=C.now();localStorage.setItem(STORE,JSON.stringify(project));syncShared(message);$('save-state').textContent='saved '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});if(window.AXMWorkshopContinuity)AXMWorkshopContinuity.announce({workspaceId:'spatial-studio',workspaceName:'Spatial Studio',projectId:project.id,projectName:project.name,documentSchema:C.FORMAT,updatedAt:project.updatedAt,resumeHint:'Continue the 3D scene, animation or delivery workflow.'});if(message)toast(message);}
  function load(){try{var raw=JSON.parse(localStorage.getItem(STORE)||'null');project=raw?C.normalizeProject(raw):C.emptyProject();try{var shared=JSON.parse(localStorage.getItem(SHARED_STORE)||'null');sharedProject=shared&&shared.project;}catch(ignore){}}catch(error){project=C.emptyProject();toast('Unreadable Spatial draft replaced with an empty project');}selectedId=project.objects.find(function(o){return !o.locked;})?.id||project.objects[0]?.id||null;$('project-name').value=project.name;}
  function buildModes(){var icons={scene:'⌂',model:'◇',surface:'◐',rig:'⌘',animate:'▶',simulate:'∿',render:'◉',capture:'⌗',templates:'▦',deliver:'⇧'},rail=$('mode-rail');C.MODES.forEach(function(m){var b=document.createElement('button');b.className='mode-button';b.dataset.mode=m.id;b.innerHTML='<span class="mode-icon">'+icons[m.id]+'</span><span>'+esc(m.short||m.title)+'</span>';b.onclick=function(){selectMode(m.id);};rail.appendChild(b);});C.TEMPLATE_NAMES.forEach(function(name){var b=document.createElement('button');b.className='template-button';b.innerHTML='<strong>'+esc(name.charAt(0).toUpperCase()+name.slice(1))+'</strong><small>shared scene recipe</small>';b.onclick=function(){if(!confirm('Replace this draft with the '+name+' starter?'))return;project=C.templateProject(name);selectedId=project.objects.find(function(o){return !o.locked;})?.id||project.objects[0]?.id;save('Loaded '+name+' domain starter');renderAll();};$('template-grid').appendChild(b);});$('key-property').innerHTML=C.KEY_PROPERTIES.map(function(p){return'<option>'+p+'</option>';}).join('');}
  function selectMode(id){mode=id;var meta=C.MODES.find(function(m){return m.id===id;})||C.MODES[0];document.querySelectorAll('.mode-button').forEach(function(b){b.classList.toggle('active',b.dataset.mode===id);});document.querySelectorAll('.mode-panel').forEach(function(p){p.classList.toggle('active',p.dataset.panel===id);});$('mode-label').textContent=meta.title;$('inspector-title').textContent=meta.title;$('truth-label').textContent=meta.description;$('mode-badge').textContent=['simulate','rig','capture'].indexOf(id)>=0?'MIXED':'REAL';renderAll();}
  function renderObjects(){var box=$('object-list');box.innerHTML='';project.objects.forEach(function(o){var row=document.createElement('div');row.className='object-row'+(o.id===selectedId?' active':'');row.dataset.id=o.id;var vis=document.createElement('button');vis.className='visibility';vis.textContent=o.visible?'◉':'○';vis.title=o.visible?'Hide object':'Show object';vis.onclick=function(e){e.stopPropagation();o.visible=!o.visible;save('Object visibility changed');renderAll();};var name=document.createElement('div');name.innerHTML='<b>'+esc(o.name)+'</b><small>'+esc(o.parentId?'child object':'scene root')+'</small>';var type=document.createElement('span');type.className='object-type';type.textContent=o.type;row.append(vis,name,type);row.onclick=function(){selectedId=o.id;renderAll();};box.appendChild(row);});var s=C.summary(project);$('scene-summary').innerHTML='OBJECTS '+s.objects+'<br>MATERIALS '+s.materials+'<br>KEYFRAMES '+s.keyframes+'<br>VOXELS '+s.voxels+'<br>TRIANGLES ~'+s.trianglesEstimate;}
  function renderTransform(){var o=selected(),ids=['object-name','pos-x','pos-y','pos-z','rot-x','rot-y','rot-z','scale-x','scale-y','scale-z'];$('selection-empty').hidden=!!o;$('transform-controls').hidden=!o;if(!o)return;$('object-name').value=o.name;['pos','rot','scale'].forEach(function(prefix){var prop=prefix==='pos'?'position':prefix==='rot'?'rotation':'scale';['x','y','z'].forEach(function(axis,i){$(prefix+'-'+axis).value=o[prop][i];});});var parent=$('object-parent'),old=o.parentId;parent.innerHTML='<option value="">Scene root</option>'+project.objects.filter(function(x){return x.id!==o.id;}).map(function(x){return'<option value="'+esc(x.id)+'">'+esc(x.name)+'</option>';}).join('');parent.value=old;$('delete-object').disabled=o.locked;$('geometry-detail').value=o.geometry.detail;$('detail-output').value=o.geometry.detail;$('geometry-inflate').value=o.geometry.inflate;$('inflate-output').value=o.geometry.inflate;$('geometry-twist').value=o.geometry.twist;$('twist-output').value=o.geometry.twist;}
  function renderMaterials(){var s=$('material-select'),old=s.value;s.innerHTML=project.materials.map(function(m){return'<option value="'+esc(m.id)+'">'+esc(m.name)+'</option>';}).join('');var o=selected();s.value=o&&o.materialId||old;}
  function renderReceipts(){function list(id,items,render){var box=$(id);box.innerHTML='';items.slice().reverse().slice(0,20).forEach(function(x){var d=document.createElement('div');d.className='receipt';d.innerHTML=render(x);box.appendChild(d);});if(!box.children.length)box.innerHTML='<div class="fine-print">No records yet.</div>';}
    list('rig-list',project.rigs,function(r){return'<strong>'+esc(r.name)+'</strong>'+r.bones.length+' bones · skin '+esc(r.skinAdapter);});
    list('key-list',project.keyframes,function(k){return'<strong>'+esc(k.property)+' → '+k.value+'</strong>frame '+k.frame+' · '+esc(k.easing);});
    list('simulation-receipts',project.simulationReceipts,function(r){return'<strong>'+esc(r.status)+'</strong>'+r.steps+' projected steps · checksum '+esc(r.checksum);});
    list('render-receipts',project.renderReceipts,function(r){return'<strong>'+esc(r.kind)+'</strong>'+esc(r.bytes?r.bytes+' bytes':r.status);});
    list('capture-list',project.captures,function(c){return'<strong>'+esc(c.name)+'</strong>'+c.imageCount+' images · solver '+esc(c.solverStatus);});
    list('delivery-log',project.exports,function(e){return'<strong>'+esc(e.format)+'</strong>'+esc(e.status)+' · '+new Date(e.createdAt).toLocaleTimeString();});
  }
  function renderHeader(){var f=Number($('current-frame').value)||0;$('project-name').value=project.name;$('frame-scrubber').max=project.durationFrames;$('frame-scrubber').value=f;$('current-frame').max=project.durationFrames;$('timeline-readout').textContent=f+' / '+project.durationFrames+' · '+project.fps+' fps';$('camera-fov').value=project.camera.fov;$('camera-target-y').value=project.camera.target[1];}
  function renderViewport(){if(!renderer)return;var f=Number($('current-frame').value)||0,view=project.keyframes.length?C.poseAt(project,f):project;renderer.render(view,selectedId);}
  function renderAll(){renderHeader();renderObjects();renderTransform();renderMaterials();renderReceipts();renderViewport();}
  function bindRange(id,out){$(id).oninput=function(){$(out).value=this.value;};}
  function number(id){return Number($(id).value);}
  function createFrameProof(shouldDownload){var data=renderer&&renderer.frameProof();if(!data)return toast('Frame proof unavailable because WebGL did not start');var bytes=Math.round((data.length-data.indexOf(',')-1)*.75),record={id:C.id('render'),kind:'WebGL frame proof',status:'EXPORTED',frame:number('current-frame'),bytes:bytes,createdAt:C.now()};project.renderReceipts.push(record);project.exports.push({id:C.id('export'),format:'PNG frame proof',status:'EXPORTED',createdAt:C.now(),bytes:bytes});if(shouldDownload){var a=document.createElement('a');a.href=data;a.download=slug()+'-frame-'+record.frame+'.png';a.click();}save('Captured inspectable WebGL frame proof');renderReceipts();}
  function publish(){var packet=C.publishPacket(project,{license:$('publish-license').value,provenance:$('publish-provenance').value}),state;try{state=JSON.parse(localStorage.getItem(PUBLISH)||'null');}catch(ignore){}if(!state||state.schema!=='axm.publish-library.ledger/v1')state={schema:'axm.publish-library.ledger/v1',artifacts:[],releases:[],updatedAt:null};state.artifacts=Array.isArray(state.artifacts)?state.artifacts:[];var a=packet.artifact;state.artifacts.push({id:C.id('artifact'),name:a.name,source:a.source,format:a.format,version:a.version,license:a.license,provenance:a.provenance,state:'INBOX',createdAt:C.now()});state.updatedAt=C.now();localStorage.setItem(PUBLISH,JSON.stringify(state));project.exports.push({id:C.id('export'),format:'Publish inbox artifact',status:'INBOX',createdAt:C.now()});save('Prepared an unreviewed Publish inbox artifact');renderReceipts();}
  function bind(){
    $('open-hands').onclick=openHands;$('close-hands').onclick=closeHands;$('hands-backdrop').onclick=closeHands;
    $('project-name').onchange=function(){project.name=clean(this.value,120)||project.name;save('Project renamed');};$('new-project').onclick=function(){if(!confirm('Start an empty Spatial project? Export the current draft first if needed.'))return;project=C.emptyProject();selectedId=project.objects.find(function(o){return !o.locked;})?.id;save('Started an empty Spatial project');renderAll();};$('export-project').onclick=$('download-project').onclick=function(){jsonDownload('AXM_SPATIAL_'+slug()+'.json',project);project.exports.push({id:C.id('export'),format:'Spatial project JSON',status:'EXPORTED',createdAt:C.now()});save('Portable Spatial project downloaded');renderReceipts();};$('import-project').onclick=function(){$('project-file').click();};$('project-file').onchange=async function(){var file=this.files&&this.files[0];if(!file)return;try{var next=C.normalizeProject(JSON.parse(await file.text()));if(!confirm('Replace this draft with '+next.name+'?'))return;project=next;selectedId=project.objects.find(function(o){return !o.locked;})?.id||project.objects[0]?.id;save('Imported portable Spatial project');renderAll();}catch(error){toast('Import refused: '+error.message);}this.value='';};
    $('add-object').onclick=function(){var type=$('primitive-type').value,o=C.addObject(project,{name:type.charAt(0).toUpperCase()+type.slice(1)+' '+(project.objects.length+1),type:type,position:[0,1,0]});selectedId=o.id;save('Added '+type+' primitive');renderAll();};$('apply-transform').onclick=function(){var o=selected();if(!o)return;try{o.name=clean($('object-name').value,120)||o.name;C.transformObject(project,o.id,{position:[number('pos-x'),number('pos-y'),number('pos-z')],rotation:[number('rot-x'),number('rot-y'),number('rot-z')],scale:[number('scale-x'),number('scale-y'),number('scale-z')],parentId:$('object-parent').value});save('Applied object transform');renderAll();}catch(error){toast('Transform refused: '+error.message);}};$('delete-object').onclick=function(){var o=selected();if(!o||o.locked)return;if(!confirm('Delete '+o.name+' and its children?'))return;C.removeObject(project,o.id);selectedId=project.objects.find(function(x){return !x.locked;})?.id||project.objects[0]?.id;save('Removed object subtree');renderAll();};
    bindRange('geometry-detail','detail-output');bindRange('geometry-inflate','inflate-output');bindRange('geometry-twist','twist-output');$('apply-geometry').onclick=function(){var o=selected();if(!o)return toast('Select an object first');try{C.transformObject(project,o.id,{geometry:{detail:number('geometry-detail'),inflate:number('geometry-inflate'),twist:number('geometry-twist')}});save('Rebuilt editable geometry recipe');renderAll();}catch(error){toast(error.message);}};
    $('assign-material').onclick=function(){var o=selected();if(!o)return toast('Select an object first');C.assignMaterial(project,o.id,$('material-select').value);save('Assigned material recipe');renderAll();};$('create-material').onclick=function(){var m=C.addMaterial(project,{name:$('material-name').value,baseColor:$('material-color').value,metallic:number('material-metallic'),roughness:number('material-roughness')});if(selected())C.assignMaterial(project,selectedId,m.id);save('Created reusable material recipe');renderAll();};
    $('create-rig').onclick=function(){var o=selected();if(!o)return toast('Select a rig root first');C.addRig(project,{name:$('rig-name').value,rootObjectId:o.id,bones:[{name:'Root',objectId:o.id,length:1}],skinAdapter:'UNAVAILABLE'});save('Recorded a rig structure without claiming skin deformation');renderAll();};
    $('add-keyframe').onclick=function(){var o=selected();if(!o)return toast('Select an object first');C.setKeyframe(project,{objectId:o.id,property:$('key-property').value,frame:number('current-frame'),value:number('key-value'),easing:$('key-easing').value});save('Set editable transform keyframe');renderAll();};
    $('frame-scrubber').oninput=function(){$('current-frame').value=this.value;renderHeader();renderViewport();};$('current-frame').oninput=function(){$('frame-scrubber').value=this.value;renderHeader();renderViewport();};$('play-toggle').onclick=function(){if(playing){clearInterval(playing);playing=null;this.textContent='▶';return;}this.textContent='■';playing=setInterval(function(){var n=number('current-frame')+1;if(n>project.durationFrames)n=0;$('current-frame').value=n;renderHeader();renderViewport();},Math.max(16,1000/project.fps));};
    $('run-simulation').onclick=function(){if(!window.AXMPhysics2D)return toast('Shared physics core is unavailable');var steps=Math.max(1,Math.min(600,number('simulation-steps'))),world=AXMPhysics2D.createWorld({gravity:{x:0,y:9.81},bounds:{minX:0,minY:0,maxX:20,maxY:20,restitution:.45}});project.objects.filter(function(o){return o.visible&&o.type!=='plane';}).slice(0,100).forEach(function(o){var shape=o.type==='sphere'?{kind:'circle',radius:Math.max(.1,o.scale[0])}:{kind:'box',halfWidth:Math.max(.1,o.scale[0]),halfHeight:Math.max(.1,o.scale[1])};world=AXMPhysics2D.addBody(world,{id:o.id,type:o.locked?'static':'dynamic',shape:shape,position:{x:Math.max(.2,Math.min(19.8,o.position[0]+10)),y:Math.max(.2,Math.min(19.8,10-o.position[1]))},mass:1,restitution:.3}).world;});var result=AXMPhysics2D.simulate(world,steps);project.simulationReceipts.push({id:C.id('simulation'),engine:'axm-physics-2d',dimension:'2D projection only',status:result.ok?'COMPLETE':'FAILED',steps:steps,checksum:result.diagnostics.checksum,contacts:result.diagnostics.contactCount,createdAt:C.now()});save('Completed bounded 2D projection proof; scene geometry was not mutated');renderAll();};$('add-emitter').onclick=function(){var o=selected();C.addEmitter(project,{name:(o?o.name:'Scene')+' emitter',objectId:o&&o.id,count:number('emitter-count'),seed:project.emitters.length+1});save('Added inspectable particle recipe');renderAll();};
    $('apply-camera').onclick=function(){project.camera.fov=number('camera-fov');project.camera.target[1]=number('camera-target-y');save('Applied camera recipe');renderAll();};$('add-light').onclick=function(){project.lights.push(C.normalizeLight({name:'Light '+(project.lights.length+1),type:$('light-type').value,position:[4,7,5]}));save('Added light recipe');renderAll();};$('capture-render').onclick=function(){createFrameProof(false);};$('frame-proof').onclick=function(){createFrameProof(false);};$('download-frame').onclick=function(){createFrameProof(true);};$('focus-view').onclick=function(){renderer.setOrbit({distance:project.objects.length>15?18:10});};
    $('record-capture').onclick=function(){C.recordCapture(project,{name:$('capture-name').value,imageCount:number('capture-count'),source:'local capture manifest',solverStatus:'UNAVAILABLE',evidence:['Image count and source manifest recorded; no reconstruction performed']});save('Recorded image-set manifest without claiming reconstruction');renderAll();};$('add-voxel').onclick=function(){C.addVoxel(project,{x:number('voxel-x'),y:number('voxel-y'),z:number('voxel-z'),size:number('voxel-size'),materialId:selected()?.materialId});save('Added editable voxel cell');renderAll();};
    $('download-scene').onclick=function(){jsonDownload(slug()+'.scene.json',C.scenePacket(project));project.exports.push({id:C.id('export'),format:'3D scene packet JSON',status:'EXPORTED',createdAt:C.now()});save('Exported shared scene packet');renderReceipts();};$('download-obj').onclick=function(){var obj=G.toOBJ(project);download(slug()+'.obj',obj,'text/plain');project.exports.push({id:C.id('export'),format:'Wavefront OBJ',status:'EXPORTED',bytes:obj.length,createdAt:C.now()});save('Exported real triangulated OBJ geometry');renderReceipts();};$('publish-inbox').onclick=publish;
  }
  async function init(){if(!C||!G||!R)throw Error('Spatial modules are incomplete');buildModes();load();renderer=R.create($('spatial-canvas'),G);if(!renderer.available){$('adapter-warning').hidden=false;$('adapter-warning').textContent='Viewport unavailable: '+renderer.reason;}else if(window.AXMEngines){AXMEngines.Renderer.register({id:'axm-spatial-webgl',version:'1.0.0',capabilities:['preview-3d','frame-proof'],run:async function(){var data=renderer.frameProof();return data?{ok:true,output:{dataUrl:data},evidence:['Current WebGL canvas produced an inspectable PNG data URL']}:{ok:false};}});}
    if(window.AXMPhysicsAdapter&&window.AXMEngines)try{AXMPhysicsAdapter.register(AXMEngines);}catch(ignore){}
    bind();selectMode('scene');save();if(window.AXM&&AXM.init)await AXM.init({id:'spatial-studio',name:'AXM Spatial Studio',version:'v0.1'});if(window.AXMHub){AXMHub.ready({version:'v0.1',capabilities:['scene-3d','parametric-modeling','material-recipes','object-animation','webgl-preview','frame-proof','obj-export','voxel-edit','domain-templates','physics-2d-projection','publish-handoff']});AXMHub.verifyPass();}toast('Spatial Studio ready · one parent, modular engines underneath');
  }
  window.addEventListener('message',function(event){
    var message=event.data;if(!message||message.type!=='axm-asset-hand-result'||message.schema!=='axm.asset-hand-result/v1'||event.source!==$('hands-frame').contentWindow)return;
    try{
      var imported=C.importAssetHandResult(project,message.result);
      if(imported.action==='replace-project'&&!confirm('Replace this Spatial draft with the validated Asset Hand project?'))return;
      project=imported.project;selectedId=project.objects.find(function(o){return !o.locked;})?.id||project.objects[0]?.id||null;
      save(imported.action==='replace-project'?'Imported validated Asset Hand project':'Added validated Asset Hand material');renderAll();closeHands();
    }catch(error){toast('Asset Hand import refused: '+error.message);}
  });
  window.addEventListener('keydown',function(event){if(event.key==='Escape')closeHands();});
  window.addEventListener('resize',function(){if(renderer){renderer.resize();renderViewport();}});init().catch(function(error){console.error(error);$('engine-status').textContent='Spatial Studio failed: '+error.message;});
})();
