(function(){
  'use strict';
  var Core=window.AXMPublishCore,$=function(id){return document.getElementById(id);};
  var STORE_KEY='axm.publish-library.ledger.v1',WORK_KEY='axm.publish-library.workspace.v1';
  var frames={library:$('libraryFrame'),packs:$('packsFrame'),packages:$('packagesFrame'),distribution:$('distributionFrame')};
  var state={schema:'axm.publish-library.ledger/v1',artifacts:[],releases:[],updatedAt:null};
  var active='overview',toastTimer=null,axmReady=false,outputAbort=null,lastOutput=null;
  function now(){return new Date().toISOString();}
  function uid(prefix){return prefix+'-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,7);}
  function clean(v,n){return String(v==null?'':v).trim().slice(0,n||4000);}
  function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function load(){try{var raw=localStorage.getItem(STORE_KEY),d=raw&&JSON.parse(raw);if(d&&d.schema==='axm.publish-library.ledger/v1'){state=d;state.artifacts=Array.isArray(d.artifacts)?d.artifacts:[];state.releases=Array.isArray(d.releases)?d.releases:[];}}catch(e){}renderAll();}
  function save(message){state.updatedAt=now();try{localStorage.setItem(STORE_KEY,JSON.stringify(state));}catch(e){status('Save failed: '+e.message,true);return false;}$('saveState').textContent='Saved '+new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});if(message)status(message);return true;}
  function status(message,bad){$('statusText').textContent=message;$('truthTitle').textContent=bad?'Pipeline needs attention':'Local pipeline ready';$('truthDetail').textContent=bad?message:'Nothing uploads or releases itself';var t=$('toast');t.textContent=message;t.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(function(){t.classList.remove('show');},2200);if(window.AXMHub)AXMHub.log(message);}
  function icon(name){var p='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round">';var m={home:'<path d="M4 11l8-7 8 7v9H4z"/><path d="M9 20v-6h6v6"/>',library:'<path d="M4 5h6v15H4zM10 7h5v13h-5zM15 4h5v16h-5z"/>',pack:'<path d="M4 7l8-4 8 4-8 4z"/><path d="M4 7v10l8 4 8-4V7M12 11v10"/>',release:'<path d="M12 3v12M7 10l5 5 5-5"/><path d="M4 19h16"/>',package:'<rect x="3" y="5" width="18" height="15" rx="2"/><path d="M3 9h18M9 13h6"/>',distribution:'<circle cx="6" cy="12" r="3"/><circle cx="18" cy="6" r="3"/><circle cx="18" cy="18" r="3"/><path d="M9 11l6-4M9 13l6 4"/>'};return p+(m[name]||m.home)+'</svg>';}
  function buildNav(){var nav=$('viewNav');nav.innerHTML='';Core.groups().forEach(function(group){var label=document.createElement('div');label.className='nav-group';label.textContent=group.name;nav.appendChild(label);group.views.forEach(function(v){var b=document.createElement('button');b.className='nav-button';b.dataset.view=v.id;b.innerHTML=icon(v.icon)+'<span>'+esc(v.short)+'</span>';b.onclick=function(){selectView(v.id);};nav.appendChild(b);});});}
  function lazy(frame){if(frame&&!frame.src)frame.src=frame.dataset.src;}
  function selectView(id){var v=Core.byId(id);active=v.id;document.querySelectorAll('.nav-button').forEach(function(b){b.classList.toggle('active',b.dataset.view===active);});$('viewGroup').textContent=v.group+' view';$('viewTitle').textContent=v.title;$('viewDescription').textContent=v.description;$('overviewSurface').hidden=active!=='overview';$('releaseSurface').hidden=active!=='release';$('frameSurface').hidden=v.route==='native'||v.route==='release';Object.keys(frames).forEach(function(key){var f=frames[key];f.hidden=v.route!==key;if(v.route===key)lazy(f);});try{localStorage.setItem(WORK_KEY,JSON.stringify(Core.normalize({view:active,updatedAt:now()})));}catch(e){}status('Opened '+v.title);}
  function renderTotals(){var open=state.artifacts.filter(function(a){return a.state==='INBOX';}).length;$('artifactTotal').textContent=state.artifacts.length;$('reviewTotal').textContent=open;$('releaseTotal').textContent=state.releases.length;$('inboxBadge').textContent=open+' open';$('exportManifest').disabled=!state.releases.length;}
  function renderArtifacts(){var list=$('artifactList'),select=$('releaseArtifact');select.innerHTML='';if(!state.artifacts.length){list.innerHTML='<div class="empty">No artifacts in the release ledger.</div>';select.innerHTML='<option value="">No reviewed artifact</option>';return;}state.artifacts.forEach(function(a){var opt=document.createElement('option');opt.value=a.id;opt.textContent=a.name+' · '+a.version;opt.disabled=a.state==='INBOX'||a.state==='BLOCKED';select.appendChild(opt);});var eligible=state.artifacts.some(function(a){return a.state!=='INBOX'&&a.state!=='BLOCKED';});if(!eligible)select.insertAdjacentHTML('afterbegin','<option value="">Review an artifact first</option>');list.innerHTML='';state.artifacts.slice().reverse().forEach(function(a){var r=document.createElement('article');r.className='record';r.innerHTML='<header><div><h4>'+esc(a.name)+'</h4><div class="meta">'+esc(a.source)+' · '+esc(a.format)+' · '+esc(a.version)+' · '+esc(a.license||'rights unknown')+'</div></div><span class="state">'+esc(a.state)+'</span></header><p>'+esc(a.provenance||'No provenance supplied.')+'</p><div class="record-actions"></div>';var actions=r.querySelector('.record-actions');if(a.state==='INBOX'){actions.appendChild(action('Review metadata','primary-action',function(){a.state='REVIEWED';a.reviewedAt=now();save('Artifact metadata reviewed · no export claimed');renderAll();}));}else if(a.state==='REVIEWED'){actions.appendChild(action('Mark output ready','primary-action',function(){a.state='READY';a.readyAt=now();save('Artifact marked ready · source engine output expected');renderAll();}));}else if(a.state==='READY'){actions.appendChild(action('Record exported','primary-action',function(){if(!confirm('Record this artifact as exported? This should only be used after the output file exists.'))return;a.state='EXPORTED';a.exportedAt=now();save('Export recorded with human confirmation');renderAll();}));}actions.appendChild(action('Delete','',function(){if(!confirm('Delete this ledger record? Source files are not touched.'))return;state.artifacts=state.artifacts.filter(function(x){return x.id!==a.id;});save('Artifact ledger record deleted');renderAll();}));list.appendChild(r);});}
  function action(label,cls,fn){var b=document.createElement('button');b.textContent=label;if(cls)b.className=cls;b.onclick=fn;return b;}
  function outputProgress(update){var value=Math.max(0,Math.min(100,Number(update&&update.value)||0));$('outputProgress').hidden=false;$('outputProgressBar').value=value;$('outputProgressValue').textContent=Math.round(value)+'%';$('outputProgressLabel').textContent=clean(update&&update.label,160)||'Working locally';}
  function setOutputBusy(busy){document.querySelectorAll('.output-builder button[type=submit]').forEach(function(button){button.disabled=busy;});$('cancelOutput').disabled=!busy;if(!busy)outputAbort=null;}
  function fileDataUrl(file){return new Promise(function(resolve,reject){var reader=new FileReader();reader.onload=function(){resolve(String(reader.result));};reader.onerror=function(){reject(Error('Could not read the selected image'));};reader.readAsDataURL(file);});}
  async function renderOutputCapabilities(){var box=$('outputCapabilities');if(!window.AXMOutput){box.innerHTML='<span class="unavailable">Output engine unavailable</span>';return;}try{var capabilities=await AXMOutput.capabilities();box.innerHTML='';capabilities.forEach(function(c){var span=document.createElement('span');span.className=c.state==='READY'?'ready':'unavailable';span.textContent=(c.engine||c.id)+' '+(c.version||'')+' - '+c.state;span.title=[c.id,c.license,c.execution,c.reason].filter(Boolean).join(' - ');box.appendChild(span);});}catch(e){box.innerHTML='<span class="unavailable">Engine check failed</span>';}}
  async function runOutput(job){
    if(outputAbort)return status('An output job is already running',true);
    outputAbort=new AbortController();lastOutput=null;$('outputResult').hidden=true;setOutputBusy(true);outputProgress({value:2,label:'Starting isolated output job'});
    try{
      var result=await AXMOutput.run(job,{signal:outputAbort.signal,onProgress:outputProgress,timeoutMs:job.kind==='pdf.generate'?20000:60000});
      lastOutput=result;var receipt=result.receipt;
      $('outputResult').hidden=false;$('outputResultName').textContent=receipt.filename+' - '+Math.max(1,Math.round(receipt.bytes/1024))+' KB';$('outputResultEvidence').textContent=receipt.engine.name+' '+receipt.engine.version+' - '+receipt.engine.license+' - SHA-256 '+receipt.sha256.slice(0,16)+'...';
      addArtifact({name:receipt.filename,source:'AXM Output Engine',format:receipt.format,version:'0.1.0',license:receipt.engine.license,provenance:'Engine: '+receipt.engine.name+' '+receipt.engine.version+'\nSource: '+receipt.engine.source+'\nSHA-256: '+receipt.sha256+'\nEvidence: '+receipt.evidence.join(' | '),handoff:true});
      status('Verified output created - review still required');
    }catch(e){if(e&&e.name==='AbortError')status('Output job cancelled - no artifact recorded');else status('Output failed: '+e.message,true);}
    finally{setOutputBusy(false);$('outputProgress').hidden=true;}
  }
  function bindOutputEngine(){
    if(!window.AXMOutput||!window.AXMOutputCore){status('Output Engine scripts are unavailable',true);return;}
    AXMOutput.registerExporterAdapters(window.AXMEngines);renderOutputCapabilities();
    $('pdfOutputForm').onsubmit=function(event){event.preventDefault();runOutput({schema:AXMOutputCore.JOB_SCHEMA,kind:'pdf.generate',name:clean($('pdfTitle').value,120),actor:{id:'local-user',kind:'human'},payload:{title:$('pdfTitle').value,body:$('pdfBody').value,filename:$('pdfFilename').value||$('pdfTitle').value,subject:'Generated locally through AXM Publish & Library'}});};
    $('imageOutputForm').onsubmit=async function(event){event.preventDefault();var file=$('imageInput').files&&$('imageInput').files[0];if(!file)return status('Choose an image first',true);if(file.size>15*1024*1024)return status('Image input must be 15MB or smaller',true);try{var dataUrl=await fileDataUrl(file);runOutput({schema:AXMOutputCore.JOB_SCHEMA,kind:'image.transform',name:file.name,actor:{id:'local-user',kind:'human'},payload:{dataUrl:dataUrl,format:$('imageFormat').value,width:Number($('imageWidth').value)||0,height:Number($('imageHeight').value)||0,quality:Number($('imageQuality').value)||88,filename:file.name.replace(/\.[^.]+$/,'')+'-axm'}});}catch(e){status(e.message,true);}};
    $('cancelOutput').onclick=function(){if(outputAbort)outputAbort.abort();};$('cancelOutput').disabled=true;
    $('downloadOutput').onclick=function(){if(!lastOutput)return status('No verified output is ready',true);AXMOutput.download(lastOutput);status('Download started - ledger record remains unreviewed');};
  }
  function renderReleases(){var list=$('releaseList');if(!state.releases.length){list.innerHTML='<div class="empty">No release records yet.</div>';return;}list.innerHTML='';state.releases.slice().reverse().forEach(function(r){var a=state.artifacts.find(function(x){return x.id===r.artifactId;});var el=document.createElement('article');el.className='record';el.innerHTML='<header><div><h4>'+esc(r.name)+'</h4><div class="meta">'+esc(a?a.name:'missing artifact')+' · '+esc(r.version)+' · '+esc(r.channel)+'</div></div><span class="state">'+esc(r.accepted?'ACCEPTED':'NEEDS REVIEW')+'</span></header><p>'+esc(r.evidence)+'</p><div class="record-actions"></div>';var actions=el.querySelector('.record-actions');if(!r.accepted)actions.appendChild(action('Accept evidence','primary-action',function(){if(!confirm('Accept this release evidence as a human review decision?'))return;r.accepted=true;r.acceptedAt=now();if(a&&a.state==='EXPORTED')a.state='RELEASED';save('Release evidence accepted by human');renderAll();}));else actions.appendChild(action('Reopen review','',function(){r.accepted=false;r.acceptedAt=null;if(a&&a.state==='RELEASED')a.state='EXPORTED';save('Release review reopened');renderAll();}));actions.appendChild(action('Delete','',function(){if(!confirm('Delete this release record? Exported files are not touched.'))return;state.releases=state.releases.filter(function(x){return x.id!==r.id;});save('Release record deleted');renderAll();}));list.appendChild(el);});}
  function renderAll(){renderTotals();renderArtifacts();renderReleases();}
  function addArtifact(packet){var name=clean(packet.name,120),source=clean(packet.source,120),format=clean(packet.format,40),version=clean(packet.version,40);if(!name||!source||!format||!version){status('Artifact needs name, source, format and version',true);return false;}state.artifacts.push({id:uid('artifact'),name:name,source:source,format:format,version:version,license:clean(packet.license,120),provenance:clean(packet.provenance,1800),state:'INBOX',receivedAt:now(),handoff:!!packet.handoff});save('Artifact received · review still required');renderAll();return true;}
  function addFromForm(){if(addArtifact({name:$('artifactName').value,source:$('artifactSource').value,format:$('artifactFormat').value,version:$('artifactVersion').value,license:$('artifactLicense').value,provenance:$('artifactProvenance').value})){['artifactName','artifactSource','artifactVersion','artifactLicense','artifactProvenance'].forEach(function(id){$(id).value='';});}}
  function addRelease(){var aid=$('releaseArtifact').value,a=state.artifacts.find(function(x){return x.id===aid;});var name=clean($('releaseName').value,120),version=clean($('releaseVersion').value,40),evidence=clean($('releaseEvidence').value,2200);if(!a||a.state==='INBOX'||a.state==='BLOCKED'){status('Choose a reviewed artifact',true);return;}if(!name||!version||!evidence){status('Release needs name, version and evidence',true);return;}state.releases.push({id:uid('release'),name:name,artifactId:a.id,version:version,channel:$('releaseChannel').value,evidence:evidence,accepted:false,createdAt:now(),acceptedAt:null});save('Release recorded · evidence not accepted automatically');renderAll();$('releaseName').value='';$('releaseVersion').value='';$('releaseEvidence').value='';}
  function exportManifest(){var packet={schema:'axm.release-manifest/v1',generatedAt:now(),artifacts:state.artifacts,releases:state.releases,boundary:'Ledger evidence only. This manifest does not prove upload, conversion, installation or marketplace publication.'};var text=JSON.stringify(packet,null,2),blob=new Blob([text],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='AXM_RELEASE_MANIFEST_'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(function(){URL.revokeObjectURL(url);},1000);status('Release manifest exported · no upload performed');}
  function handleMessage(event){if(event.origin!==location.origin)return;var d=event.data;if(!d||d.schema!=='axm.publish-artifact/v1'||d.type!=='axm-publish-artifact')return;var p=d.artifact&&typeof d.artifact==='object'?d.artifact:{};addArtifact({name:p.name,source:p.source||'AXM workspace',format:p.format,version:p.version,license:p.license,provenance:p.provenance,handoff:true});selectView('release');}
  function bind(){document.querySelectorAll('[data-open-view]').forEach(function(b){b.onclick=function(){selectView(b.dataset.openView);};});$('openInbox').onclick=function(){selectView('release');};$('addArtifact').onclick=addFromForm;$('addRelease').onclick=addRelease;$('exportManifest').onclick=exportManifest;window.addEventListener('message',handleMessage);}
  async function init(){buildNav();Core.FORMATS.forEach(function(f){var o=document.createElement('option');o.textContent=f;$('artifactFormat').appendChild(o);});load();bind();var ws={};try{ws=JSON.parse(localStorage.getItem(WORK_KEY)||'{}');}catch(e){}selectView(Core.normalize(ws).view);if(window.AXM&&AXM.init){await AXM.init({id:'publish-library',name:'AXM Publish & Library',version:'v1.0'});axmReady=true;}if(window.AXMHub){AXMHub.ready({version:'v1.0',capabilities:['library','packs','artifact-inbox','release-ledger','verified-packages','distribution']});AXMHub.verifyPass();}status('Publish & Library ready · local and review-gated');}
  bindOutputEngine();
  init().catch(function(e){status('Publish & Library failed: '+e.message,true);});
})();
