const fs=require('fs'),path=require('path'),root=__dirname;
const read=n=>fs.readFileSync(path.join(root,n),'utf8');
const core=require('./publish-library-core.js');
let fail=0;function check(ok,label){if(!ok){fail++;console.error('FAIL '+label);}else console.log('PASS '+label);}
const html=read('index.html'),js=read('publish-library.js'),manifest=JSON.parse(read('manifest.json')),contract=JSON.parse(read('module.contract.json'));
check(manifest.schema==='axm.tool-manifest/v1'&&manifest.kind==='service','published manifest declares the modern service schema');
check(JSON.stringify(manifest.permissions)===JSON.stringify(contract.permissions),'published manifest permissions match the contract');
check(JSON.stringify(contract.lifecycle)===JSON.stringify({state_owner:'browser',reload:'resume',disconnect:'not-applicable',cleanup:'explicit'}),'contract declares browser persistence lifecycle seams');
const attr=(tag,name)=>{const match=String(tag).match(new RegExp('\\s'+name+'\\s*=\\s*(["\\\'])([\\s\\S]*?)\\1','i'));return match?match[2]:null;},markup=html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,'').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,''),labelIds=new Set(Array.from(markup.matchAll(/<label\b[^>]*\bfor\s*=\s*(["'])(.*?)\1/gi),match=>match[2]));for(const label of markup.matchAll(/<label\b[^>]*>([\s\S]*?)<\/label>/gi)){for(const control of label[1].matchAll(/<(?:input|select|textarea)\b[^>]*>/gi)){const id=attr(control[0],'id');if(id)labelIds.add(id);}}const unnamedControls=Array.from(markup.matchAll(/<(?:input|select|textarea)\b[^>]*>/gi),match=>match[0]).filter(tag=>{const type=String(attr(tag,'type')||'').toLowerCase();if(['hidden','button','submit'].includes(type))return false;const id=attr(tag,'id'),name=attr(tag,'aria-label')||attr(tag,'aria-labelledby')||attr(tag,'title');return !name&&!(id&&labelIds.has(id));});check(unnamedControls.length===0,'every Publish & Library form control has an accessible name');
check(core.VIEWS.length===6,'six beginner-facing views');
check(core.VIEWS.some(v=>v.route==='library')&&core.VIEWS.some(v=>v.route==='packs'),'library and packs views');
check(core.VIEWS.some(v=>v.route==='release')&&core.VIEWS.some(v=>v.route==='packages')&&core.VIEWS.some(v=>v.route==='distribution'),'release, packaging and distribution views');
check(core.FORMATS.includes('PNG')&&core.FORMATS.includes('WebP')&&core.FORMATS.includes('PDF')&&core.FORMATS.includes('SVG')&&core.FORMATS.includes('Audio')&&core.FORMATS.includes('Video')&&core.FORMATS.includes('3D')&&core.FORMATS.includes('Web')&&core.FORMATS.includes('Executable'),'requested output families are visible');
check(/data-src="\.\.\/asset-vault\//.test(html)&&/data-src="\.\.\/asset-pack-lab\//.test(html),'existing asset engines load lazily');
check(/data-src="\.\.\/workshop-packager\//.test(html)&&/data-src="\.\.\/launcher-card-installer\//.test(html),'existing package and distribution engines load lazily');
check(/axm\.publish-artifact\/v1/.test(js)&&/state:'INBOX'/.test(js),'versioned handoff enters unreviewed inbox');
check(/Review metadata/.test(js)&&/Accept evidence/.test(js),'artifact and release reviews stay separate');
check(/confirm\('Record this artifact as exported/.test(js),'export state requires confirmation');
check(/axm\.release-manifest\/v1/.test(js)&&/does not prove upload/.test(js),'release export keeps no-fake-done boundary');
check(/pdfOutputForm/.test(html)&&/imageOutputForm/.test(html)&&/axm-output-client\.js/.test(html),'one Output Engine exposes PDF and image jobs inside Publish');
check(/AXMOutput\.run/.test(js)&&/AbortController/.test(js)&&/review still required/.test(js),'real output jobs are cancellable and enter review');
check(manifest.id==='publish-library'&&manifest.version==='v1.1','manifest declares unified workspace v1.1');
check(contract.handoffs.accepts.includes('axm.publish-artifact/v1'),'contract declares artifact handoff');
check(contract.boundaries.refuses.includes('marketplace-publication'),'marketplace later is explicit');
check(contract.boundaries.refuses.includes('proprietary-cloud-conversion')&&contract.boundaries.refuses.includes('trial-locked-output-engine'),'trial and proprietary output engines are refused');
if(fail)process.exit(1);console.log('Publish & Library selftest: PASS (shared library, reviewed release ledger, packages and distribution)');
