#!/usr/bin/env node
'use strict';

const assert = require('assert');
const Pulse = require('./axm-body-pulse-core');
let pass = 0;
function test(name, fn) { try { fn(); pass += 1; console.log('PASS ' + name); } catch (error) { console.error('FAIL ' + name + '\n  ' + error.stack); process.exitCode = 1; } }
function setup(now) {
  let state = Pulse.createState();
  state = Pulse.registerModule(state, { moduleId: 'asset-fabric', name: 'Asset Fabric', enabled: true, priority: 60, activeCadenceMs: 900000, idleCadenceMs: 3600000, cost: { cpu: 2, memory: 1, gpu: 0 }, authority: 'incubator-only', promotionGate: 'independent-dual-review' }, now);
  state = Pulse.sampleBody(state, { cpuUsedRatio: .2, memoryUsedRatio: .3 }, now);
  return state;
}

test('defaults stopped and grants no autonomous work', () => { const result = Pulse.requestPulse(setup(1000), { moduleId: 'asset-fabric' }, 1000); assert.equal(result.granted, false); assert.equal(result.reason, 'body-stopped'); });
test('active mode still requires a bounded goal', () => { let state = Pulse.setMode(setup(1000), 'ACTIVE', 'mike', 1000); const result = Pulse.requestPulse(state, { moduleId: 'asset-fabric' }, 1000); assert.equal(result.reason, 'no-open-goal'); });
test('green body grants one short lease for an open goal', () => { let state = Pulse.setMode(setup(1000), 'ACTIVE', 'mike', 1000); state = Pulse.upsertGoal(state, { goalId: 'g1', moduleId: 'asset-fabric', title: 'Create revive icon family', priority: 80, maxPulses: 2, createdBy: 'mike' }, 1000); const result = Pulse.requestPulse(state, { moduleId: 'asset-fabric' }, 1000); assert(result.granted); assert.equal(result.lease.goalId, 'g1'); assert.equal(result.lease.authority, 'incubator-only'); });
test('red body pressure holds even high-priority goals', () => { let state = Pulse.setMode(setup(1000), 'ACTIVE', 'mike', 1000); state = Pulse.upsertGoal(state, { goalId: 'g1', moduleId: 'asset-fabric', title: 'Heavy work', priority: 100 }, 1000); state = Pulse.sampleBody(state, { cpuUsedRatio: .93, memoryUsedRatio: .5 }, 1000); const result = Pulse.requestPulse(state, { moduleId: 'asset-fabric' }, 1000); assert.equal(result.reason, 'body-pressure-red'); });
test('conserve mode holds low-priority work', () => { let state = Pulse.setMode(setup(1000), 'CONSERVE', 'mike', 1000); state = Pulse.upsertGoal(state, { goalId: 'g1', moduleId: 'asset-fabric', title: 'Optional polish', priority: 40 }, 1000); const result = Pulse.requestPulse(state, { moduleId: 'asset-fabric' }, 1000); assert.equal(result.reason, 'conserve-priority-hold'); });
test('one body capacity prevents cross-heartbeat pressure', () => { let state = Pulse.registerModule(setup(1000), { moduleId: 'world-lineage', enabled: true, priority: 80 }, 1000); state = Pulse.setMode(state, 'ACTIVE', 'mike', 1000); state = Pulse.upsertGoal(state, { goalId: 'g1', moduleId: 'asset-fabric', title: 'Asset', priority: 80 }, 1000); state = Pulse.upsertGoal(state, { goalId: 'g2', moduleId: 'world-lineage', title: 'World', priority: 80 }, 1000); const first = Pulse.requestPulse(state, { moduleId: 'asset-fabric' }, 1000); const second = Pulse.requestPulse(first.state, { moduleId: 'world-lineage' }, 1000); assert(first.granted); assert.equal(second.reason, 'body-capacity-busy'); });
test('completion creates a receipt with no promotion authority', () => { let state = Pulse.setMode(setup(1000), 'ACTIVE', 'mike', 1000); state = Pulse.upsertGoal(state, { goalId: 'g1', moduleId: 'asset-fabric', title: 'Asset', priority: 80 }, 1000); const grant = Pulse.requestPulse(state, { moduleId: 'asset-fabric' }, 1000); const done = Pulse.completePulse(grant.state, { leaseId: grant.lease.leaseId, outcome: 'COMPLETED', summary: 'Candidate family created.' }, 2000); assert.equal(done.receipt.promotionAuthority, 'NONE'); assert.equal(done.receipt.outcome, 'COMPLETED'); });
test('rest mode is distinct from death or deletion', () => { let state = Pulse.setMode(setup(1000), 'REST', 'mike', 1000); const status = Pulse.status(state, 1000); assert.equal(status.mode, 'REST'); assert.equal(status.modules.length, 1); });
test('paused requests remain present but cannot receive work', () => { let state = Pulse.setMode(setup(1000), 'ACTIVE', 'mike', 1000); state = Pulse.upsertGoal(state, { goalId: 'g1', moduleId: 'asset-fabric', title: 'Pause me', status: 'PAUSED' }, 1000); const result = Pulse.requestPulse(state, { moduleId: 'asset-fabric' }, 1000); assert.equal(result.reason, 'no-open-goal'); assert.equal(Pulse.status(result.state, 1000).goals[0].status, 'PAUSED'); });
test('completed requests enter a measurable archive', () => { let state = Pulse.upsertGoal(setup(1000), { goalId: 'g1', moduleId: 'asset-fabric', title: 'Archive me', status: 'DONE' }, 1000); const status = Pulse.status(state, 1000); assert.equal(status.retention.archivedGoalCount, 1); assert(status.retention.approximateBytes > 0); assert.equal(status.retention.policy, 'manual-forget'); });
test('empty archive reports zero retained bytes', () => { assert.equal(Pulse.status(setup(1000), 1000).retention.approximateBytes, 0); });
test('forgetting removes request memory and linked logs only', () => { let state = Pulse.upsertGoal(setup(1000), { goalId: 'g1', moduleId: 'asset-fabric', title: 'Forget me', status: 'DONE' }, 1000); state.receipts.push({ goalId: 'g1', receiptId: 'r1' }, { goalId: 'other', receiptId: 'r2' }); state.events.push({ goalId: 'g1', kind: 'linked' }, { goalId: 'other', kind: 'unrelated' }); state = Pulse.deleteGoals(state, ['g1'], 'mike', 2000); assert.equal(state.goals.g1, undefined); assert.deepEqual(state.receipts.map(item => item.receiptId), ['r2']); assert.deepEqual(state.events.filter(item => item.goalId).map(item => item.kind), ['unrelated']); });
test('active requests cannot be mistaken for forgettable archive', () => { let state = Pulse.upsertGoal(setup(1000), { goalId: 'g1', moduleId: 'asset-fabric', title: 'Still active' }, 1000); assert.throws(() => Pulse.deleteGoals(state, ['g1'], 'mike', 2000), /only archived goals/); });

if (!process.exitCode) console.log('\n' + pass + ' PASS · 0 FAIL · body-pulse ' + Pulse.VERSION);
