(function(){
  'use strict';
  var state=null,simulation=null,$=function(id){return document.getElementById(id);},STORE='axm.sensorium-lab.config.v1';
  function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(char){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char];});}
  function age(value){var stamp=Date.parse(value||'');if(!Number.isFinite(stamp))return'unknown';var seconds=Math.max(0,Math.round((Date.now()-stamp)/1000));return seconds<60?seconds+'s':seconds<3600?Math.round(seconds/60)+'m':Math.round(seconds/3600)+'h';}
  function badge(label,value){var tone=/PASS|READY|AVAILABLE|EXECUTABLE/.test(value)?'pass':/FAIL|BLOCKED/.test(value)?'fail':/HOLD|DEGRADED|MISSING|UNKNOWN|MEDIATED/.test(value)?'hold':'';return'<span class="badge '+tone+'">'+esc(label)+' '+esc(value)+'</span>';}
  function rowWithSimulation(row){if(!simulation||simulation.senseId!==row.senseId)return row;var copy=JSON.parse(JSON.stringify(row));if(simulation.kind==='missing'){copy.adapterStatus='MISSING_ADAPTER';copy.holds=['MISSING_ADAPTER'];}else{copy.proofStatus='FAIL';copy.holds=['FAILED_OBSERVATION'];}return copy;}
  function renderSummary(){var executable=state.senses.filter(function(row){return row.executorStatus==='EXECUTABLE';}).length,mediated=state.senses.filter(function(row){return row.executorStatus==='HOST_MEDIATED';}).length,holds=Array.isArray(state.knownHolds)?state.knownHolds:[];$('routeCounts').textContent=executable+' executable · '+mediated+' host-mediated';$('holdCount').textContent=holds.length+' OPEN';$('holdSummary').textContent=holds.length?holds.join(' · '):'no named capability gaps';}
  function render(){if(!state)return;var filter=$('filter').value,rows=state.senses.map(rowWithSimulation).filter(function(row){return filter==='all'||row.executorStatus===filter||(filter==='holds'&&row.holds&&row.holds.length);});$('senseGrid').innerHTML=rows.map(function(row){var proof=row.proof||{};return'<article class="card" data-sense="'+esc(row.senseId)+'"><header><div><span class="eyebrow">'+esc(row.capability)+'</span><h3>'+esc(row.senseId)+'</h3></div>'+badge('',row.freshnessStatus)+'</header><div class="badges">'+badge('skill',row.skillStatus)+badge('executor',row.executorStatus)+badge('adapter',row.adapterStatus)+badge('proof',row.proofStatus)+badge('authority',row.authorityStatus)+'</div><div class="facts"><div><span>Latest bounded receipt</span><b>'+esc(row.latestReceiptId||'none')+'</b></div><div><span>Evidence</span><b>'+esc(proof.verdict||'UNTESTED')+' · '+esc(proof.negativeCases||0)+' safety checks</b></div><div><span>Retention</span><b>'+esc(row.rawRetainedBytes)+' bytes · '+esc(row.rawRetainedItems)+' items</b></div><div><span>Lease scope / expiry</span><b>'+esc(row.lease.scope||'none')+' / '+esc(row.lease.expiresAt||'none')+'</b></div></div><p>'+esc(row.cheapestAlternative)+'</p>'+(row.holds&&row.holds.length?'<ul class="holds">'+row.holds.map(function(hold){return'<li>'+esc(hold)+'</li>';}).join('')+'</ul>':'')+'</article>';}).join('')||'<div class="loading">No senses match this filter.</div>';$('senseCount').textContent=state.senses.length;$('conformance').textContent=state.conformance.verdict;$('proofAge').textContent='evidence '+age(state.conformance.generatedAt)+' old · '+state.conformance.negativeProofs+' safety checks';$('rawBytes').textContent=state.summary.rawRetainedBytes;$('rawItems').textContent=state.summary.rawRetainedItems+' raw items';$('status').textContent='Canonical state read · '+age(state.generatedAt)+' old · source '+String(state.sourceDigest).slice(0,12);$('simulation').textContent=simulation?'SYNTHETIC ONLY · '+simulation.kind+' on '+simulation.senseId+' · canonical state unchanged':'Synthetic controls are browser-local examples and never alter canonical state.';$('trace').innerHTML=simulation?['Touch preflight','Time stamps assumptions',simulation.kind==='missing'?'Dependent sense returns capability gap':'Sense returns FAIL receipt','Time stamps evidence','Evidence router holds claim','Continuity carries digest only'].map(function(step,index){return'<li>'+esc((index+1)+'. '+step)+'</li>';}).join(''):'<li>No synthetic or live journey selected.</li>';}
  function simulate(kind){if(!state)return;simulation={kind:kind,senseId:kind==='missing'?'eye-live-visual-verifier':'ears-stream-listener'};render();}
  async function load(){try{var response=await fetch('/shared/sensorium/lab-state.json',{cache:'no-store'});if(!response.ok)throw new Error('HTTP '+response.status);state=await response.json();render();renderSummary();}catch(error){$('senseGrid').innerHTML='<div class="loading">Canonical state unavailable. No cached state was substituted.</div>';$('conformance').textContent='UNAVAILABLE';$('status').textContent='Sensorium state unavailable · '+error.message;}}
  try{var config=JSON.parse(localStorage.getItem(STORE)||'{}');$('filter').value=config.filter||'all';}catch(error){}
  $('filter').onchange=function(){localStorage.setItem(STORE,JSON.stringify({filter:this.value}));render();};$('simulateMissing').onclick=function(){simulate('missing');};$('simulateFailure').onclick=function(){simulate('failure');};$('clearSimulation').onclick=function(){simulation=null;render();};load();
})();
