#!/usr/bin/env node
'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const read = name => fs.readFileSync(path.join(__dirname, name), 'utf8');
const manifest = JSON.parse(read('manifest.json'));
const contract = JSON.parse(read('module.contract.json'));
const html = read('index.html'), app = read('app.js'), css = read('command-center.css');
const controls = JSON.parse(fs.readFileSync(path.join(__dirname,'..','..','shared','cognitive-resource','command-center-controls.json'),'utf8'));
assert.equal(manifest.schema, 'axm.tool-manifest/v1');
assert.equal(manifest.kind, 'product');
assert.equal(manifest.id, 'workshop-command-center');
assert.equal(manifest.status, 'TEST');
assert.equal(manifest.audience, 'human-machine');
assert.deepStrictEqual(manifest.permissions, []);
assert.equal(contract.version, manifest.version);
assert(!/https?:\/\//.test(html + css), 'Command Center must have no external runtime dependency');
assert(contract.provides.includes('beginner-one-page-cockpit'));
assert(contract.provides.includes('explicit-human-review-seat'));
assert(contract.provides.includes('read-only-system-needs-and-cognitive-summary'));
assert(contract.consumes.includes('axm.workshop-needs-observatory/v1'));
assert(contract.consumes.includes('axm.workshop-readiness-view/v1'));
assert(contract.boundaries.refuses.includes('automatic-vote'));
assert(contract.boundaries.refuses.includes('generic-post-control-execution'));
assert(contract.boundaries.refuses.includes('direct-body-pulse-start'));
assert(contract.boundaries.refuses.includes('need-acceptance-authority'));
assert(contract.boundaries.refuses.includes('readiness-as-promotion'));
assert(html.includes('What do you want to make or fix?'));
assert(html.includes('One machine. Two honest perspectives.'));
assert(html.includes('data-seat="human"') && html.includes('data-seat="mirror"'));
assert(html.includes('COMPLETE MEASUREMENT BANK'));
['totalFiles','textFiles','binaryFiles','characters','lines','bytes','modules','worlds','games','tests','hands','schemas','protocols','validators','exactCapabilities','capabilityDeclarations','codeFiles','codeLines','testLines','documentLines','otherTextLines','assetFiles','assetBytes'].forEach(key => assert(html.includes('data-growth-key="' + key + '"'), 'missing growth instrument ' + key));
assert(html.includes('../game-hub/index.html'));
assert(html.includes('../chroma-studio/chroma-studio.html'));
assert(html.includes('../device-handoff/index.html?start=1&amp;from=command-deck'));
assert(html.includes('../ui-fx/index.html'));
assert(html.includes('../presentation-spine/index.html'));
assert(html.includes('../../shared/presentation-spine/presentation-spine.css'));
assert(html.includes('data-axm-profile="cockpit"'));
assert(contract.provides.includes('chroma-studio-navigation'));
assert(contract.provides.includes('explicit-phone-drop-navigation'));
assert(contract.provides.includes('ui-fx-navigation'));
assert(contract.provides.includes('presentation-spine-navigation'));
assert(contract.boundaries.refuses.includes('network-authority'));
assert(html.includes('../../shared/elements/dual-operator-command-deck.css'));
assert(app.includes('function renderDeck('));
assert(app.includes("$('commandForm').requestSubmit()"));
assert(html.includes('REFRESH SAVED PLANS'));
assert(html.includes('Read-only · saves nothing'));
assert(html.includes('REVIEW PANEL'));
assert(html.includes('10 reviewers'));
assert(html.includes('PLANS NEEDING A DECISION'));
assert(app.includes('SEND TO REPAIR'));
assert(app.includes('CANCEL COMPLETELY'));
assert(html.includes('NET CODE LINES / HOUR'));
assert(html.includes('NET TEST LINES / HOUR'));
assert(html.includes('id="openNeedCount"'));
assert(html.includes('id="reviewCandidateCount"'));
assert(html.includes('OPEN NEEDS &amp; MODULE REVIEW OWNER'));
assert(app.includes('codeLinesPerHour'));
assert(app.includes('hourlyVelocity'));
assert(app.includes('MEASUREMENT RESUMED'));
assert(app.includes('RESUMED_AFTER_GAP'));
assert(app.includes('unknown rather than zero'));
assert(app.includes("'/api/workshop-growth'"));
const renderNeedsFunction = app.slice(app.indexOf('function renderNeeds('), app.indexOf('function renderSystem('));
assert(renderNeedsFunction.includes("readiness.state === 'CURRENT'"), 'review candidates require current owner evidence');
assert(renderNeedsFunction.includes('Waiting for Mike · not promoted'), 'human gate must remain visible');
assert(!/post\(|SATISFIED|PROMOTED/.test(renderNeedsFunction), 'health composition must not accept needs or promote modules');
const refreshAllFunction = app.slice(app.indexOf('async function refreshAll()'), app.indexOf("$('priority').oninput"));
assert(refreshAllFunction.includes("api('/api/workshop-needs')"), 'health refresh must read the Observatory owner');
assert(refreshAllFunction.includes('operationResult(results[5].value)'), 'health refresh must unwrap the shared operations envelope');
assert(!refreshAllFunction.includes("post('/api/workshop-needs"), 'health refresh must not mutate Observatory state');
const refreshPlansFunction = app.slice(app.indexOf('async function refreshPlans()'), app.indexOf('async function refreshReviews()'));
assert(refreshPlansFunction.includes("api('/api/workshop-direction')"), 'saved-plan refresh must be a read');
assert(!/post\(|workshop-growth|snapshot/i.test(refreshPlansFunction), 'saved-plan refresh must not write or save a snapshot');
assert(app.includes("'/api/reviews/vote'"));
assert(app.includes("'/api/reviews/discuss'"));
assert(app.includes("'/api/reviews/route'"));
assert(app.includes("'REVIEW EXACT DIGEST'"));
assert(app.includes("'ROUTE REVIEW ITEM'"));
assert(!/localStorage|sessionStorage/.test(app), 'service state must not be shadowed in the browser');
assert.equal(controls.presentationOwner, 'workshop-command-center');
assert(controls.controls.every(control => control.automatic === false));
assert(Object.values(controls.authority).every(value => value === false));
assert(fs.existsSync(path.join(__dirname,'assets','command-core.svg')));
assert(fs.existsSync(path.join(__dirname,'assets','dual-operator-roadmap-reference.png')));
assert(fs.existsSync(path.join(__dirname,'DUAL_OPERATOR_ROADMAP.md')));
console.log('PASS Workshop Command Center · beginner cockpit · 1–10 review queue · Decision Pool · honest output/hour signals');
