#!/usr/bin/env node
'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const read = name => fs.readFileSync(path.join(__dirname, name), 'utf8');
const manifest = JSON.parse(read('manifest.json'));
const contract = JSON.parse(read('module.contract.json'));
const html = read('index.html'), app = read('app.js'), css = read('command-center.css');
const controls = JSON.parse(fs.readFileSync(path.join(__dirname,'..','..','shared','cognitive-resource','command-center-controls.json'),'utf8'));
assert.equal(manifest.id, 'workshop-command-center');
assert.equal(manifest.status, 'TEST');
assert.equal(manifest.audience, 'human-machine');
assert.deepStrictEqual(manifest.permissions, []);
assert(!/https?:\/\//.test(html + css), 'Command Center must have no external runtime dependency');
assert(contract.provides.includes('beginner-one-page-cockpit'));
assert(contract.provides.includes('explicit-human-review-seat'));
assert(contract.boundaries.refuses.includes('automatic-vote'));
assert(contract.boundaries.refuses.includes('generic-post-control-execution'));
assert(contract.boundaries.refuses.includes('direct-body-pulse-start'));
assert(html.includes('What should AXM do?'));
assert(html.includes('REVIEW PANEL'));
assert(html.includes('10 votes'));
assert(html.includes('DECISION POOL'));
assert(app.includes('SEND TO REPAIR'));
assert(app.includes('CANCEL COMPLETELY'));
assert(html.includes('NET CODE LINES / HOUR'));
assert(html.includes('NET TEST LINES / HOUR'));
assert(app.includes('codeLinesPerHour'));
assert(app.includes('hourlyVelocity'));
assert(app.includes("'/api/workshop-growth'"));
assert(app.includes("'/api/reviews/vote'"));
assert(app.includes("'/api/reviews/discuss'"));
assert(app.includes("'/api/reviews/route'"));
assert(app.includes("'REVIEW EXACT DIGEST'"));
assert(app.includes("'ROUTE REVIEW ITEM'"));
assert(!/localStorage|sessionStorage/.test(app), 'service state must not be shadowed in the browser');
assert.equal(controls.presentationOwner, 'workshop-command-center');
assert(controls.controls.every(control => control.automatic === false));
assert(Object.values(controls.authority).every(value => value === false));
assert(fs.existsSync(path.join(__dirname,'assets','command-core.svg')));
console.log('PASS Workshop Command Center · beginner cockpit · 1–10 review queue · Decision Pool · honest output/hour signals');
