#!/usr/bin/env node
'use strict';
const assert = require('assert');
const fs = require('fs');
const path = require('path');
const canonicalText = value => String(value).replace(/\r\n/g, '\n');
const readText = file => canonicalText(fs.readFileSync(file, 'utf8'));
const read = name => readText(path.join(__dirname, name));
const manifest = JSON.parse(read('manifest.json'));
const contract = JSON.parse(read('module.contract.json'));
const html = read('index.html'), app = read('app.js'), css = read('command-center.css'), draftCss = read('code-draft-review.css');
const operationsApi = readText(path.join(__dirname,'..','..','shared','operations','operations-api.js'));
const technicalReviewer = readText(path.join(__dirname,'..','..','shared','operations','code-draft-technical-reviewer.js'));
const DecisionGuide = require('./code-draft-decision-guide.js');
const controls = JSON.parse(readText(path.join(__dirname,'..','..','shared','cognitive-resource','command-center-controls.json')));
assert.equal(canonicalText('alpha\r\nbeta\r\n'), 'alpha\nbeta\n');
assert.equal(canonicalText('alpha\rbeta'), 'alpha\rbeta');
assert.equal(manifest.schema, 'axm.tool-manifest/v1');
assert.equal(manifest.kind, 'product');
assert.equal(manifest.id, 'workshop-command-center');
assert.equal(manifest.status, 'TEST');
assert.equal(manifest.audience, 'human-machine');
assert.deepStrictEqual(manifest.permissions, []);
assert.equal(contract.version, manifest.version);
assert(!/https?:\/\//.test(html + css + draftCss), 'Command Center must have no external runtime dependency');
assert(contract.provides.includes('beginner-one-page-cockpit'));
assert(contract.provides.includes('explicit-human-review-seat'));
assert(contract.provides.includes('heartbeat-code-draft-review-queue'));
assert(contract.provides.includes('deterministic-exact-candidate-technical-check'));
assert(contract.provides.includes('bounded-batch-deterministic-technical-check'));
assert(contract.provides.includes('deterministic-stale-exact-copy-retirement'));
assert(contract.provides.includes('ready-for-human-prioritization'));
assert(contract.provides.includes('machine-hold-human-vote-refusal'));
assert(contract.provides.includes('technical-first-plain-language-code-draft-review'));
assert(contract.provides.includes('exact-digest-code-draft-up-down-vote'));
assert(contract.provides.includes('read-only-system-needs-and-cognitive-summary'));
assert(contract.consumes.includes('axm.workshop-needs-observatory/v1'));
assert(contract.consumes.includes('axm.workshop-readiness-view/v1'));
assert(contract.boundaries.refuses.includes('automatic-vote'));
assert(contract.boundaries.refuses.includes('uninformed-human-code-draft-vote'));
assert(contract.boundaries.refuses.includes('human-code-draft-vote-before-machine-review'));
assert(contract.boundaries.refuses.includes('caller-supplied-machine-seat'));
assert(contract.boundaries.refuses.includes('caller-supplied-technical-verdict'));
assert(contract.boundaries.refuses.includes('caller-supplied-batch-selection'));
assert(contract.boundaries.refuses.includes('caller-supplied-batch-limit'));
assert(contract.boundaries.refuses.includes('technical-refusal-as-vote'));
assert(contract.boundaries.refuses.includes('opinion-based-technical-retirement'));
assert(contract.boundaries.refuses.includes('human-vote-on-machine-hold'));
assert(contract.boundaries.refuses.includes('generic-post-control-execution'));
assert(contract.boundaries.refuses.includes('direct-body-pulse-start'));
assert(contract.boundaries.refuses.includes('need-acceptance-authority'));
assert(contract.boundaries.refuses.includes('readiness-as-promotion'));
assert(html.includes('What do you want to make or fix?'));
assert(html.includes('One machine. Two honest perspectives.'));
assert(html.includes('data-seat="human"') && html.includes('data-seat="mirror"'));
assert(html.includes('COMPLETE MEASUREMENT BANK'));
['totalFiles','textFiles','binaryFiles','characters','lines','bytes','modules','worlds','games','tests','hands','schemas','protocols','validators','exactCapabilities','capabilityDeclarations','codeFiles','codeLines','testLines','documentLines','otherTextLines','assetFiles','assetBytes'].forEach(key => assert(html.includes('data-growth-key="' + key + '"'), 'missing growth instrument ' + key));
assert(html.includes('../game-hub/index.html'));
assert(html.includes('../chroma-studio/chroma-studio.html'));
assert(html.includes('../device-handoff/index.html?start=1&amp;from=command-deck'));
assert(html.includes('../ui-fx/index.html'));
assert(html.includes('../presentation-spine/index.html'));
assert(html.includes('../../shared/presentation-spine/presentation-spine.css'));
assert(html.includes('data-axm-profile="cockpit"'));
assert(contract.provides.includes('chroma-studio-navigation'));
assert(contract.provides.includes('explicit-phone-drop-navigation'));
assert(contract.provides.includes('ui-fx-navigation'));
assert(contract.provides.includes('presentation-spine-navigation'));
assert(contract.boundaries.refuses.includes('network-authority'));
assert(html.includes('../../shared/elements/dual-operator-command-deck.css'));
assert(app.includes('function renderDeck('));
assert(app.includes("$('commandForm').requestSubmit()"));
assert(html.includes('REFRESH SAVED PLANS'));
assert(html.includes('Read-only · saves nothing'));
assert(html.includes('REVIEW PANEL'));
assert(html.includes('10 reviewers'));
assert(html.includes('PLANS NEEDING A DECISION'));
assert(html.includes('Improvement drafts waiting for us'));
assert(html.includes('id="codeDraftReviews"'));
assert(html.includes('id="codeDraftReadyCount"'));
assert(html.includes('id="codeDraftRepairCount"'));
assert(html.includes('id="codeDraftRetiredCount"'));
assert(html.includes('DRAFTING DORMANT'));
assert(html.includes('Machine-held drafts wait for repair without asking Mike to judge code.'));
assert(html.includes('Technical drafts are checked by a machine steward first.'));
assert(app.includes('SEND TO REPAIR'));
assert(app.includes('CANCEL COMPLETELY'));
assert(html.includes('NET CODE LINES / HOUR'));
assert(html.includes('NET TEST LINES / HOUR'));
assert(html.includes('id="openNeedCount"'));
assert(html.includes('id="reviewCandidateCount"'));
assert(html.includes('OPEN NEEDS &amp; MODULE REVIEW OWNER'));
assert(app.includes('codeLinesPerHour'));
assert(app.includes('hourlyVelocity'));
assert(app.includes('MEASUREMENT RESUMED'));
assert(app.includes('RESUMED_AFTER_GAP'));
assert(app.includes('unknown rather than zero'));
assert(app.includes("'/api/workshop-growth'"));
const renderNeedsFunction = app.slice(app.indexOf('function renderNeeds('), app.indexOf('function renderSystem('));
assert(renderNeedsFunction.includes("readiness.state === 'CURRENT'"), 'review candidates require current owner evidence');
assert(renderNeedsFunction.includes('Waiting for Mike · not promoted'), 'human gate must remain visible');
assert(!/post\(|SATISFIED|PROMOTED/.test(renderNeedsFunction), 'health composition must not accept needs or promote modules');
const refreshAllFunction = app.slice(app.indexOf('async function refreshAll()'), app.indexOf("$('priority').oninput"));
assert(refreshAllFunction.indexOf('await Promise.allSettled([refreshReviews()])') < refreshAllFunction.indexOf("api('/api/workshop/technical-glasses')"), 'human decision queue must load before heavyweight Workshop scans');
assert(refreshAllFunction.includes('priorityResults.concat(results)'), 'priority queue failure must remain isolated while later status scans continue');
assert(refreshAllFunction.includes("api('/api/workshop-needs')"), 'health refresh must read the Observatory owner');
assert(refreshAllFunction.includes('operationResult(results[5].value)'), 'health refresh must unwrap the shared operations envelope');
assert(!refreshAllFunction.includes("post('/api/workshop-needs"), 'health refresh must not mutate Observatory state');
const refreshPlansFunction = app.slice(app.indexOf('async function refreshPlans()'), app.indexOf('async function refreshReviews()'));
assert(refreshPlansFunction.includes("api('/api/workshop-direction')"), 'saved-plan refresh must be a read');
assert(!/post\(|workshop-growth|snapshot/i.test(refreshPlansFunction), 'saved-plan refresh must not write or save a snapshot');
assert(app.includes("'/api/reviews/vote'"));
assert(app.includes("item.kind === 'code-improvement-draft'"));
assert(app.includes('data-code-draft-vote'));
assert(app.includes('function technicalCodeDraftReview('));
assert(app.includes("technical.verdict === 'APPROVE' ? 0"));
assert(app.includes('READY FOR MIKE'));
assert(app.includes('NEEDS REPAIR · NOT YOUR VOTE'));
assert(app.includes("if (technical.verdict !== 'APPROVE')"));
assert(app.includes('There is no useful vote for Mike to cast yet.'));
assert(html.includes('code-draft-decision-guide.js?v=20260728-human-decision-1'));
assert(app.includes('AXMCodeDraftDecisionGuide.guide(item)'));
assert(app.includes('No decision needed from Mike'));
assert(app.includes('WHY AXM RECOMMENDS THIS'));
assert(app.includes('YES - KEEP FOR LATER'));
assert(app.includes('NO - DISCARD THIS COPY'));
assert(app.includes('data-code-draft-understood'));
assert(app.includes('informedExplanation:true'));
assert(app.includes('choice stays locked until a machine steward checks'));
assert(app.includes('RUN SAFE TECHNICAL CHECK'));
assert(app.includes("'/api/reviews/technical-check'"));
assert(app.includes("'deterministic-technical-check'"));
assert(app.includes("confirmation:'RUN READ-ONLY TECHNICAL CHECK'"));
const decisionFixture = { title:'game-hub', sourceRef:'heartbeat:declare-empty-manifest-permissions-field', artifactDigest:'abc123', action:{ moduleId:'game-hub' }, votes:[] };
const waitingGuide = DecisionGuide.guide(decisionFixture);
assert.equal(waitingGuide.phase, 'CHECK_FIRST');
assert.equal(waitingGuide.humanDecision, false);
assert.equal(waitingGuide.recommendation, 'WAIT - DO NOT VOTE YET');
const readyGuide = DecisionGuide.guide(Object.assign({}, decisionFixture, { votes:[{ actorKind:'machine', artifactDigest:'abc123', verdict:'APPROVE', note:'Exact receipt, contract and unchanged source passed the bounded candidate check.' }] }));
assert.equal(readyGuide.phase, 'READY');
assert.equal(readyGuide.humanDecision, true);
assert.equal(readyGuide.openExplanation, true);
assert.match(readyGuide.recommendation, /KEEPING THIS CANDIDATE/);
assert.equal(readyGuide.installsCode, false);
const repairGuide = DecisionGuide.guide(Object.assign({}, decisionFixture, { votes:[{ actorKind:'machine', artifactDigest:'abc123', verdict:'HOLD', note:'HOLD - Exact receipt matches but bounded contract file is not declared for this candidate.' }] }));
assert.equal(repairGuide.phase, 'REPAIR');
assert.equal(repairGuide.humanDecision, false);
assert.match(repairGuide.why, /cannot prove.*zero permissions/i);
const wrongDigestGuide = DecisionGuide.guide(Object.assign({}, decisionFixture, { votes:[{ actorKind:'machine', artifactDigest:'different', verdict:'APPROVE', note:'This long note belongs to another exact copy and must not unlock a human choice.' }] }));
assert.equal(wrongDigestGuide.phase, 'CHECK_FIRST');
assert(operationsApi.includes("url === '/api/reviews/technical-check'"));
assert(operationsApi.includes('return codeDraftTechnicalReviewer.review(parsed.id, parsed.artifactDigest)'));
assert(!operationsApi.includes('codeDraftTechnicalReviewer.review(parsed.id, parsed.verdict)'), 'caller cannot supply the technical verdict');
assert(html.includes('id="checkAllCodeDrafts"'));
assert(html.includes('Maximum 25 exact candidates per click'));
assert(app.includes("'/api/reviews/technical-check-pending'"));
assert(app.includes("'deterministic-technical-check-batch'"));
assert(app.includes("confirmation:'RUN BOUNDED READ-ONLY TECHNICAL CHECKS'"));
assert(app.includes('finally {\n      renderCodeDraftReviews();'), 'batch control must restore the exact settled queue label');
assert(operationsApi.includes("url === '/api/reviews/technical-check-pending'"));
assert(operationsApi.includes('return codeDraftTechnicalReviewer.reviewPending()'));
assert(!operationsApi.includes('reviewPending(parsed'), 'caller cannot choose batch members or size');
assert(technicalReviewer.includes('const BATCH_LIMIT = 25'));
assert(technicalReviewer.includes('.slice(0, BATCH_LIMIT)'));
assert(technicalReviewer.includes("const REFUSAL_SCHEMA = 'axm.code-draft-technical-refusal/v1'"));
assert(technicalReviewer.includes('recordTechnicalRefusal(item.id, refusal)'));
assert(technicalReviewer.includes("status:'RETIRED'"));
assert(app.includes('batch.retired'));
assert(app.includes("item.technicalRefusal.schema === 'axm.code-draft-technical-refusal/v1'"));
assert(technicalReviewer.includes("applyAuthority:'NONE'"));
assert(technicalReviewer.includes("applyAuthority: 'NONE'"));
assert(technicalReviewer.includes('candidate manifest hash changed after drafting'));
assert(technicalReviewer.includes('Workshop source changed after this candidate was drafted'));
assert(draftCss.includes('.technical-review.waiting'));
assert(draftCss.includes('.batch-technical-check'));
assert(draftCss.includes('.code-draft-review.ready-for-mike'));
assert(draftCss.includes('.draft-repair-box'));
assert(draftCss.includes('.technical-review.held'));
assert(draftCss.includes('.draft-explanation'));
assert(draftCss.includes('.draft-vote-box button:disabled'));
assert(app.includes("'/api/reviews/discuss'"));
assert(app.includes("'/api/reviews/route'"));
assert(app.includes("'REVIEW EXACT DIGEST'"));
assert(app.includes("'ROUTE REVIEW ITEM'"));
assert(!/localStorage|sessionStorage/.test(app), 'service state must not be shadowed in the browser');
assert.equal(controls.presentationOwner, 'workshop-command-center');
assert(controls.controls.every(control => control.automatic === false));
assert(Object.values(controls.authority).every(value => value === false));
assert(fs.existsSync(path.join(__dirname,'assets','command-core.svg')));
assert(fs.existsSync(path.join(__dirname,'assets','dual-operator-roadmap-reference.png')));
assert(fs.existsSync(path.join(__dirname,'DUAL_OPERATOR_ROADMAP.md')));
console.log('PASS Workshop Command Center · beginner cockpit · 1–10 review queue · Decision Pool · honest output/hour signals');
